### ISSUE TITLE
F5 doesn't work on Node <v8.0

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#1]
Today we're hard-coding the debug protocol to be 'inspector' which only works on Node 8.0+.

Ideally we remove the protocol and VSCode auto-detects whether it needs to use "legacy" or "inspector" protocol - however that wasn't working for me on Node 8.0+
![screen shot 2017-10-05 at 1 51 57 pm](https://user-images.githubusercontent.com/11282622/31251954-7ad83a1a-a9d4-11e7-8fb0-c8ed04b449aa.png)

VSCode checks this url to detect the version `http://localhost:5858/json/version`. It's possible that url isn't up until after `Job host started` is printed.

This could also be related (the func cli does not use the default 9229 port for debugging v8.0+): https://github.com/Azure/azure-functions-cli/issues/261

**Comment by jdneo** [comment]
I can repro this issue when I do the following actions:

1. trigger the 'add function' command, select a folder that is not inited (Let's say an empty folder).
2. after the function file is added, open that folder
3. hit F5

Though I'm 100% sure, but I guess it is because in this line: https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/commands/createFunction.ts#L52, we just call method in FunctionsCli, so the .vscode setting folder is generated by the function CLI not by the extension, so the preLaunchTask is not get executed.

**Comment by auchenberg** [comment]
Our Node debugger will auto detect the protocol if you set `protocol: 'auto'` and remove the `port` when launching.

**Comment by EricJizbaMSFT** [comment]
@auchenberg when you say 'our' are you talking about 'VS Code'? This issue is not in VS Code (I've tried what you suggested), it's in the func cli.

This url is not ready in time for VS Code to 'auto' detect the protocol: http://localhost:5858/json/version

**Comment by EricJizbaMSFT** [comment]
We call 'func host start', which is basically a black box that starts the node process for us

**Comment by auchenberg** [comment]
@EricJizbaMSFT Yes I mean "our " as in "our VS Code debugger" in case you didn't know that we supported protocol detection.

**Comment by jdneo** [comment]
F5 seems not work on VS Code 1.18.

![image](https://user-images.githubusercontent.com/6193897/32637909-70180274-c5f7-11e7-9849-0cf64a782a1f.png)

Note sure if it is related to my own environment setting.

**Comment by EricJizbaMSFT** [comment]
The error in your window says "No job functions found". You have to create a function before you F5

**Comment by jdneo** [comment]
Ha, sorry, my bad

**Comment by EricJizbaMSFT** [comment]
Since creating this issue, Node 8.0+ has become the [LTS](https://nodejs.org/) release. We will no longer fix this issue.

As a workaround for old versions of Node, users can manually remove `protocol: 'inspector',` from their `.vscode/launch.json` file after creating a new project.
