### ISSUE TITLE
Improve performance of creating a Java function

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#100]
Currently, the first time creating a Java function takes ~50 seconds. The median time creating a Java function is 11.95s. This should ideally be instantaneous in both cases.

A few ideas:
1. We somehow trigger maven to fetch and cache the templates _before_ the user creates a function
1. We remove the dependency on maven. Package management systems  are somewhat slow (by nature) and ill-equipped for this scenario (related to #84)

**Comment by brunoborges** [comment]
Are other languages not using package managers/build tools?

**Comment by ejizba** [comment]
JavaScript, TypeScript, Python, and PowerShell do _not_ use build tools to create a function. C# uses "dotnet", but it's much faster than "maven". Haven't tested the timing for maven in a while - might not be as bad as it was 3 years ago

**Comment by brunoborges** [comment]
I'd appreciate your feedback on the true performance cost of Maven.

In my experience, there are no issues.

**Comment by ejizba** [comment]
Seems okay from a quick test just now. Will go ahead and close
