### ISSUE TITLE
Unable to find default nuget package manager path to restore and deploy 

### ISSUE THREAD

**Issue by dilipprasad** [Microsoft/vscode-azurefunctions#1001]
Repro steps:
Publish the Dev translator  app
unable to restore the dll with default nuget package manager while deploying.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\username\Documents\IoTWorkbenchProjects\examples\devkit_translator\Functions\bin\Release\netcoreapp2.1\publish

Version: 0.14.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@dilipprasad does `dotnet restore` and `dotnet build` succeed in your project? If not - can you copy the logs here? It seems like you're failing to restore some nuget package, which means the build will fail and the path to deploy won't exist.
