### ISSUE TITLE
Entry not found in cache while deploying azure functions

### ISSUE THREAD

**Issue by dilipprasad** [Microsoft/vscode-azurefunctions#1002]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.14.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@dilipprasad can you give more detailed repro steps? Does this happen consistently or does deploy work for you most of the time?
