### ISSUE TITLE
Error on new function creation

### ISSUE THREAD

**Issue by gauravdixit3** [Microsoft/vscode-azurefunctions#1003]
Issue Type: <b>Bug</b>

Create a new function app project and returns error while resolving the csproj file: NU1100: Unable to resolve 'Microsoft.Net.Sdk.Functions (V=1.0.24)'  for '.NetCoreApp,Version=v2.1'.

Extension version: 0.14.0
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by EricJizbaMSFT** [comment]
@gauravdixit3 does this error go away if you run `dotnet restore`? This should happen automatically when you debug or deploy
