### ISSUE TITLE
Space in path causes debugging to fail

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1004]
From a customer email:

> When I go to run the function locally The space in the directory name `c:\Users\User Name\` is causing the following error: `python: can't open file 'C:\Users\User': [Errno 2] No such file or directory`

**Comment by EricJizbaMSFT** [comment]
Filed an issue on python extension: https://github.com/Microsoft/vscode-python/issues/4966

**Comment by EricJizbaMSFT** [comment]
This was fixed...but then re-appeared...but is now tracked with https://github.com/microsoft/vscode-azurefunctions/issues/2000
