### ISSUE TITLE
Failed to create Java function in Visual studio code 

### ISSUE THREAD

**Issue by adipola** [Microsoft/vscode-azurefunctions#1014]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run "mvn" command. Check output window for more details.

Version: 0.14.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@adipola please check the logs in the output window and copy them here if you're still having problems
