### ISSUE TITLE
Enable Application Insights by default

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1017]
The portal's already doing this. We want to adopt similar behavior in the client tools as well. 

/cc @alexkarcher-msft

**Comment by alexkarcher-msft** [comment]
Specifically, we'd like to add a creation and selection flow for App Insights, in the same way that we have for a storage account now when you create a Function in Azure from VS Code.

**Comment by EricJizbaMSFT** [comment]
Assigning to @fiveisprime so that we can iron out the experience

**Comment by fiveisprime** [comment]
The portal experience:

- Last option in the list is Application Insights, which is disabled by default
- Clicking into the option let's users enable AI, which then unlocks the resource options
- Options are "Create new resources" (name and location) or "Select an existing resource"

In advanced creation mode, the last prompt should be "Application Insights" with the options:

- Create new Application Insights
- Skip for now
- List existing AI resoureces for selection

When "Create new AI" is chosen, prompt for name and location. This should also create the AI_KEY app setting.

**Comment by alexkarcher-msft** [comment]
Hi Matt! I sent you over the API to provide region recommendations to create an App Insights instance in an adjacent region to almost every region a user can deploy Functions to. This should enable you to enable App Insights by default in this flow.

You're also not quite correct in your current portal experience. App Insights is enabled by default, if you are deploying your app to a region which also has Application Insights. If you deploy your app to West US 2 you'll see app insights light up in the creation blade. We're integrating the same region pairing API into the portal soon to light up AI for more new apps.
