### ISSUE TITLE
Error occurs if folder path contains whitespace

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-azurefunctions#102]
[platform: osx]

I selected a folder named `test folder`  in `Create New Project` step. Two errors block me along the way.
* In inputbox of artifactId, the default value is same as folder name, i.e. `test folder`, which should be illegal for artifactId. Should add validation, otherwise it fails the maven command.

* In `tasks.json`, the whitespace also breaks the maven command, should be quoted or escaped.
    ```
    "osx" : {
        "command": "sh -c \"mvn clean package -B && func host start --script-root target/azure-
    functions/test folder-1512092704461/\""
    }
    ```
    It's also supposed to fail in other platform.

**Comment by jdneo** [comment]
The first point has already been fixed in #97
