### ISSUE TITLE
Display 'Function host is not running' after deploying a TypeScript project to Linux Preview

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1022]
**OS:** Windows/ Mac/Linux
**Func:** V2.4.317
**Build Version:** [20190222.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3467)

**Repro Steps:**
1. Create a TypeScript project.
2. Debug --> Deploy to a function app with Windows OS.

**Expect:**
Succeed to deploy and get a valid Function URL.

**Actual:**
Display 'Function host is nor running'.
![image](https://user-images.githubusercontent.com/34729092/53233452-5139e180-3642-11e9-8df9-429bdb08a646.png)

**More Info:**
 No URL displays after deploying to a function app with Linux OS.
![image](https://user-images.githubusercontent.com/34729092/53233498-66167500-3642-11e9-9dc4-a5976a0e3ecb.png)

**Comment by EricJizbaMSFT** [comment]
@v-dantch can you give more information on this:
1. You said "function app with Windows OS", but the screenshot at the bottom says "Linux Preview"
1. Did debug work just fine?
1. What triggers did you add? Just an http trigger? And what "authLevel" did it have?
1. If you're deploying to Windows, can you try streaming logs right after you deploy and see if there's an error preventing the host from starting up

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT, thanks for your reply and please get more info from below:
We verified this issue on the **latest** Azure Function Extension build [20190227.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3645)
1. Windows OS--Succeed to deploy a TypeScript project to the function app.
   Linux OS--**There is nothing** under 'Functions' node after deploying TypeScript project to function apps. Does it make sense?
![image](https://user-images.githubusercontent.com/34729092/53537615-69d14e00-3abf-11e9-8320-bb06fe69c7fa.png)
2. Yes, 'Debug' works well.
3. Function template--just Http trigger
   AuthLevel--Function

**Comment by EricJizbaMSFT** [comment]
@v-dantch can you check your application settings and see what `FUNCTIONS_WORKER_RUNTIME` is? If it's not set to "node", this might not work. We have an open issue to validate that setting before deploying: https://github.com/Microsoft/vscode-azurefunctions/issues/924

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT , verified this issue on the latest Azure Function Extension build: [20190306.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3753). And there displays nothing after deploying a TypeScript project and the 'FUNCTIONS_WORKER_RUNTIME' sets to "node" like below:
![image](https://user-images.githubusercontent.com/34729092/53929743-98ad6e00-4043-11e9-96be-d206d45a5908.png)
