### ISSUE TITLE
Make html error with image more readable

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1025]
**OS:** Windows
**Func:** V2.4.317
**Build Version:** [20190222.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3467)

**Repro Steps:**
1. Create a Python project --> Debug --> Deploy.
2. Expand the 'Functions' node --> Right click one function and select 'Delete Function...'.
3. Check the result.

**Expect:**
Succeed to delete the functions.

**Actual:**
Fail to delete functions with error.
![image](https://user-images.githubusercontent.com/34729092/53234087-9ca0bf80-3643-11e9-960a-1a0290e2dedb.png)

**More Info:**
This issue also reproduces for C#/JavaScript/TypeScript project.

**Comment by EricJizbaMSFT** [comment]
Yeah delete won't work. We're tracking that here https://github.com/Microsoft/vscode-azurefunctions/issues/652 and here https://github.com/Microsoft/vscode-azurefunctions/issues/654

However that error is pretty ugly so I'll at least make that more readable
