### ISSUE TITLE
[Discussion] Run `npm install` after creating TypeScript project

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#1026]
OS: All
**Func:** V2.4.317
**Build Version:** [20190222.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3467)

**Steps to reproduce:**
1. Set "azureFunctions.templateVersion" to "2.18.1" then restart VS Code.
2. Create a new project with Typescript -> Create a function then change the filter from “Verified” to “Core” -> Add HttpTrigger.
3. Check the opened file index.ts.

**Expect**:
There is no problems.

**Actual:**
Cannot find module '@azure/functions'.
![image](https://user-images.githubusercontent.com/34729022/53234900-6f551100-3645-11e9-9b2a-cc7cac99bb96.png)

**Comment by EricJizbaMSFT** [comment]
This is somewhat expected - "@azure/functions" will be installed when you run `npm install`, which happens automatically if you F5 or deploy.

That being said, we can discuss if we run `npm install` by default for new projects

**Comment by EricJizbaMSFT** [comment]
Closing this as won't fix due to the "cons" listed above. Once you F5 it'll install and it'll work fine
