### ISSUE TITLE
Azure function deploy python

### ISSUE THREAD

**Issue by codeclan04** [Microsoft/vscode-azurefunctions#1027]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/r.wasilewski/Documents/AZURE/Python/CosmosFunctionPython/CosmosFunctionPython.zip

Version: 0.14.0
OS: linux

**Comment by EricJizbaMSFT** [comment]
@codeclan04 When deploying a python project, the "func pack" task is run before deploying, which creates that zip file. If the task failed, the file won't exist. Please copy the output of that task so we can investigate further
