### ISSUE TITLE
Deploy python azure function

### ISSUE THREAD

**Issue by codeclan04** [Microsoft/vscode-azurefunctions#1028]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.configureDeploymentSource
Error type: Error
Error Message: Entry not found in cache.

Version: 0.14.0
OS: linux

**Comment by EricJizbaMSFT** [comment]
@codeclan04 can you give more detailed repro steps? Does this happen consistently or does it work most of the time?
