### ISSUE TITLE
Creating new Python project in VS Code is very slow on Windows

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#1029]
_originally filed by @gbowerman [here](https://github.com/Azure/azure-functions-python-worker/issues/339)_

VS Code 1.31.1
Azure Functions extension 0.14.0.
Create a new project, use browse to create new folder, and select Python as language.
Project creation takes minutes on Windows compared to seconds on Mac.

**Comment by EricJizbaMSFT** [comment]
This is only because we're creating a virtual environment. Separate issue here for possibly removing venv: https://github.com/Microsoft/vscode-azurefunctions/issues/1092

**Comment by gbowerman** [comment]
@EricJizbaMSFT is it slower on Windows than Mac because there is no venv on Mac?

**Comment by EricJizbaMSFT** [comment]
Both have a venv and there is a delay for both when we create that venv. I don't know why your windows machine is so much slower than your mac, but it just depends on the machine. Either way, removing the venv will speed up creating a project on _both_ OS's
