### ISSUE TITLE
URL to trigger the function not shown after deployment

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-azurefunctions#103]
During local debug, URL is shown in terminal as:
```
Http Functions:
      funtionname: http://localhost:7071/api/functionname
```
But after deployment it only prints:
```
10:05:20 functionAppName: Deplotment completed.
```
Nowhere to find the corresponding URL. Am I supposed to open azure portal in browser for it?

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/72
