### ISSUE TITLE
[JavaScript] Add Durable triggers to verified category

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#1031]
There's a few templates that should be stable that still show up only in the All filter.  Ideally all the templates could now be verified now that we've GA'd and things have settled, but prioritized list of ones that should show up

* Durable Functions (activity, HTTP starter, orchestrator)
* IoT Hub
* Event Grid

**Comment by EricJizbaMSFT** [comment]
Event Grid was added here, to be released soon: https://github.com/Microsoft/vscode-azurefunctions/pull/1010

For Durable, we haven't done it because those templates aren't labeled as "Core" and we only consider "Core" templates for our "Verified" category. Are those a core scenario or not?

**Comment by jeffhollan** [comment]
Yes - and maybe that's a work item for  @soninaren as well but believe now that durable JS is GA it should be Core

//cc @kashimiz

**Comment by EricJizbaMSFT** [comment]
I prefer to track each template type separately, so I've re-purposed this issue to be specific to durable functions on JavaScript. Like I said above, Event Grid is already done. Here's an issue to track IoT: https://github.com/Microsoft/vscode-azurefunctions/issues/1036

**Comment by soninaren** [comment]
@jeffhollan, we had put durable in its own category. We can certainly add it to core as well. let me know.

**Comment by jeffhollan** [comment]
Since the categorization doesn't really show up anywhere, makes sense to just label these as Core to stick to how they are managing today per this:

> For Durable, we haven't done it because those templates aren't labeled as "Core" and we only consider "Core" templates for our "Verified" category. Are those a core scenario or not?
