### ISSUE TITLE
[python] Start terminal with virtual env activated

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#1033]
I believe this is the behavior when I code on my mac and open bash?  But either way when developing on windows in Python my terminal opens up with a PowerShell instance (as I prefer), but would be good if it could automatically activate the venv as well.  Know this opens up a lot of combinations (if cmd need to call this script, if powershell need to call this one, etc.) but would still be nice.

**Comment by EricJizbaMSFT** [comment]
@jeffhollan this behavior already occurs for me on Windows (although it doesn't always happen 
instantaneously). In any case, this is generic Python behavior provided by the Python extension, so I would file a bug here if it's not working for you: https://github.com/Microsoft/vscode-python

**Comment by jeffhollan** [comment]
Thanks - realized it only doesn’t occur when I’m in a workspace instead of opening just that file directly
