### ISSUE TITLE
Python function project takes >250 Mb on disk

### ISSUE THREAD

**Issue by gbowerman** [Microsoft/vscode-azurefunctions#1034]
Create a new project with a simple Python Azure Function. Disk space is >250 Mb on Windows.

A good user experience might be something like:
- Create simple function that can be tested locally without requiring a virtual env, or even do basic syntax check and allow option of not running locally.
- Basic check for requirements.txt
- Deploy to Azure

Azure Functions VS Code extension 0.14.0.
VS Code 1.31.1.
Windows 10.

**Comment by EricJizbaMSFT** [comment]
@gbowerman the func cli requires a virtual environment to run locally. If you want that requirement removed, I suggest filing an issue here https://github.com/Azure/azure-functions-core-tools

However your second suggestion ("do basic syntax check and allow option of not running locally") might be possible from our extension's point of view. We could delay creating a virtual environment until the user tries to debug. This might help speed up project creation (https://github.com/Microsoft/vscode-azurefunctions/issues/1029), but it might also be confusing. @fiveisprime thoughts?

That being said, I'm not even sure deploy is supported without a virtual environment. @asavaritayal is `func pack` supported without a venv? It wasn't working for me, but that might just be my machine.

**Comment by EricJizbaMSFT** [comment]
This is only because we're creating a virtual environment. Separate issue here for possibly removing venv: https://github.com/Microsoft/vscode-azurefunctions/issues/1092
