### ISSUE TITLE
Pop up an error when editing application setting value

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1045]
**OS:** Windows, Mac, Linux
**Extension Version:** [20190228.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3662)

**Repro Steps:**
1. Create a Windows function app.
2. Expand 'Application Settings' node --> Edit the value of 'WEBSITE_CONTENTSHARE' with 'Content-testing'.
![image](https://user-images.githubusercontent.com/34729092/53555215-55f50e80-3af6-11e9-9d06-f4159fca6cf5.png)

**Expect:**
No error pops up.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/53555189-483f8900-3af6-11e9-9d67-f769c02b3610.png)

**More Info:**
This issue does not reproduce when editing with 'content-testing'.
![image](https://user-images.githubusercontent.com/34729092/53555287-7e7d0880-3af6-11e9-9521-7bbfbe0322ad.png)

**Comment by EricJizbaMSFT** [comment]
We generally don't recommend users edit the WEBSITE_CONTENT* app settings as they have special meaning for the platform. Thus I'll close this as won't fix
