### ISSUE TITLE
Add links to the serverless library

### ISSUE THREAD

**Issue by ColbyTresness** [Microsoft/vscode-azurefunctions#1047]
Per discussion with @fiveisprime, we'd like to add links to the serverless library in two places before Build:

1. README presented after extension installation
2. under the Sign in to Azure/Create an account options on in the extension blade

**Comment by ColbyTresness** [comment]
1 is docs, but 2 requires a code change I think. @fiveisprime can we confirm that we can do this for Build?

**Comment by EricJizbaMSFT** [comment]
Still need to figure out the best place for the link in the code. We think most users are logged in and won't see 2 as mentioned above

**Comment by EricJizbaMSFT** [comment]
For example maybe in the "Create New Project" workflow it could have something like "See sample projects"

**Comment by ColbyTresness** [comment]
Yeah I think that makes sense. As long as its on project/app create and not function create - that feels too late in the process.
