### ISSUE TITLE
Missing runtimes when creating app in Azure

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#1048]
Right-click subscription and choose "Create Function App in Azure..." step through until you get to language selection. Only JavaScript, .NET, and Java are available.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime what runtime is missing?

![screen shot 2019-03-05 at 10 57 52 am](https://user-images.githubusercontent.com/11282622/53829692-8fce7680-3f35-11e9-8dfc-519f700f44b7.png)

If you're looking for Python, that's not available on Windows. User has to turn on advancedCreation if they want OS prompt

**Comment by fiveisprime** [comment]
I'm going to close as by design on this. The confusion around this came from the workflow: the user was attempting to create the Function App on Azure prior to creating the local project and they were confused by the lack of Python. It makes sense and I think the other issue (PR?) to normalize the terms (app v. project) will solve this.
