### ISSUE TITLE
A ScriptHost error has occurred when locally debug BlobTrigger

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-azurefunctions#105]
OS: Ubuntu 16.10

I have an error when I debug the Blotrigger locally. 
![image](https://user-images.githubusercontent.com/22470312/33472621-1a0aa59a-d6ae-11e7-9365-c80e62457696.png)
And Same issue for QueueTrigger and TimerTrigger.

**Comment by jdneo** [comment]
Seems this is related with the tool chain not installed correctly.

I can trigger blob trigger function locally.

![image](https://user-images.githubusercontent.com/6193897/33481466-8c1ded92-d6cf-11e7-95a6-70c486b92c93.png)

**Comment by bsaby** [comment]
I find that the error related to the storage account type of blobtrigger i used.
![image](https://user-images.githubusercontent.com/22470312/33535879-5a2135a6-d8eb-11e7-9241-db59177c2578.png)
Blob storage type: error occurs
Genneral purpose: works fine

**Comment by jdneo** [comment]
@bsaby , the finding is correct.

Please take a look at this article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob

```
Blob-only storage accounts are not supported. 
Blob storage triggers and bindings require a general-purpose storage account.
```

**Comment by bsaby** [comment]
closed it because not a azure function issue.
