### ISSUE TITLE
unable to use command "func" even after insatlling all dependencies

### ISSUE THREAD

**Issue by socialexps** [Microsoft/vscode-azurefunctions#1050]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run ".env\Scripts\activate && func init ./ --worker-runtime python" command. Check output window for more details.

Version: 0.15.0
OS: win32
VS Code Version: 1.31.1

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:1:132939)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:1:132003)
```

</details>

**Comment by socialexps** [comment]
more details confirming that azure function tools are installed
> azure-functions-core-tools@2.4.419 postinstall C:\Users\yadavm\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.4.419/Azure.Functions.Cli.win-x64.2.4.419.zip"

+ azure-functions-core-tools@2.4.419
updated 1 package in 33.08s
Finished running command: "npm install -g azure-functions-core-tools@2".
Running command: ".env\Scripts\activate && func init ./ --worker-runtime python "...
'func' is not recognized as an internal or external command,
operable program or batch file.

**Comment by socialexps** [comment]
more information as i have path variable also added 
C:\WINDOWS\system32>path
PATH=C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\anaconda3\lib\site-packages;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\local\opencv3.10\build\x64\vc14\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft Network Monitor 3\;C:\Users\yadavm\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\GVFS;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA Corporation\NVSMI;C:\local\cudnn-9.0-v7.0\cuda\bin;c:\local\mklml-2018.0.1\lib;C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Anaconda3\Lib\site-packages\cntk;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\platform-tools;C:\ProgramData\iotedge;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Users\yadavm\AppData\Roaming\Python\Python36\Scripts;C:\gstreamer\1.0\x86\bin;C:\gstreamer\1.0\x86\lib;C:\Users\yadavm\AppData\Roaming\nvm;C:\Program Files\nodejs;c:\local\mklml-201;C:\Users\yadavm\AppData\Roaming\Python\Python35\Scripts;C:\Users\yadavm\AppData\Local\Programs\Microsoft VS Code\bin;C:\605boardfun\dlc\myMl\tensorflow-r1.4\tensorflow\python\tools;C:\gstreamer\1.0\x86_64\bin;C:\gstreamer\1.0\x86_64\lib;C:\Users\yadavm\.dotnet\tools;C:\Users\yadavm\AppData\Roaming\nvm;C:\Program Files\nodejs

C:\WINDOWS\system32>func
'func' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>npm list --g
C:\Users\yadavm\AppData\Roaming\npm
`-- azure-functions-core-tools@2.4.419
  +-- chalk@2.4.2
  | +-- ansi-styles@3.2.1
  | | `-- color-convert@1.9.3
  | |   `-- color-name@1.1.3
  | +-- escape-string-regexp@1.0.5
  | `-- supports-color@5.5.0
  |   `-- has-flag@3.0.0
  +-- command-exists@1.2.8
  +-- glob@7.1.3
  | +-- fs.realpath@1.0.0
  | +-- inflight@1.0.6
  | | +-- once@1.4.0 deduped
  | | `-- wrappy@1.0.2
  | +-- inherits@2.0.3
  | +-- minimatch@3.0.4
  | | `-- brace-expansion@1.1.11
  | |   +-- balanced-match@1.0.0
  | |   `-- concat-map@0.0.1
  | +-- once@1.4.0
  | | `-- wrappy@1.0.2 deduped
  | `-- path-is-absolute@1.0.1
  +-- https-proxy-agent@2.2.1
  | +-- agent-base@4.2.1
  | | `-- es6-promisify@5.0.0
  | |   `-- es6-promise@4.2.5
  | `-- debug@3.2.6
  |   `-- ms@2.1.1
  +-- progress@2.0.3
  +-- rimraf@2.6.3
  | `-- glob@7.1.3 deduped
  +-- tmp@0.0.33
  | `-- os-tmpdir@1.0.2
  `-- unzipper@0.9.7
    +-- big-integer@1.6.40
    +-- binary@0.3.0
    | +-- buffers@0.1.1
    | `-- chainsaw@0.1.0
    |   `-- traverse@0.3.9
    +-- bluebird@3.4.7
    +-- buffer-indexof-polyfill@1.0.1
    +-- duplexer2@0.1.4
    | `-- readable-stream@2.3.6 deduped
    +-- fstream@1.0.11
    | +-- graceful-fs@4.1.15
    | +-- inherits@2.0.3 deduped
    | +-- mkdirp@0.5.1
    | | `-- minimist@0.0.8
    | `-- rimraf@2.6.3 deduped
    +-- listenercount@1.0.1
    +-- readable-stream@2.3.6
    | +-- core-util-is@1.0.2
    | +-- inherits@2.0.3 deduped
    | +-- isarray@1.0.0
    | +-- process-nextick-args@2.0.0
    | +-- safe-buffer@5.1.2
    | +-- string_decoder@1.1.1
    | | `-- safe-buffer@5.1.2 deduped
    | `-- util-deprecate@1.0.2
    `-- setimmediate@1.0.5

**Comment by EricJizbaMSFT** [comment]
@socialexps sometimes you have to restart VS Code or your command prompt for environment variables to take effect. Are you still seeing issues?
