### ISSUE TITLE
Run/Debug attempts to install requirements.txt every time, can take a while

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#1052]
What can be done to speed this up?

**Comment by EricJizbaMSFT** [comment]
This behavior was request by @asavaritayal here: https://github.com/Microsoft/vscode-azurefunctions/issues/666. That being said, users can always edit their tasks.json to remove this behavior.

**Comment by asavaritayal** [comment]
We received similar feedback on other fronts as well and are soon getting rid of the virtual environment requirement for Python completely. Once this is done, we can give the user complete control of their environment and installing any dependencies. I'll send an update once this is ready on the runtime side. 

/cc @maiqbal11 @ankitkumarr

**Comment by EricJizbaMSFT** [comment]
Tracking this as a part of https://github.com/Microsoft/vscode-azurefunctions/issues/1092
