### ISSUE TITLE
Updating .NET templates for runtime "~1" to version "1.8.0"...

### ISSUE THREAD

**Issue by ChakritRakuang** [Microsoft/vscode-azurefunctions#1053]
Updating .NET templates for runtime "~1" to version "1.8.0"...
You must have the .NET CLI installed to perform this operation.
Command "dotnet "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetTemplates\itemTemplates-~1.nupkg" --require "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetTemplates\projectTemplates-~1.nupkg" --operation list" failed with exit code "1":
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

Updating .NET templates for runtime "~2" to version "2.18.3"...
You must have the .NET CLI installed to perform this operation.
Command "dotnet "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\chakr\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.15.0\resources\dotnetTemplates\projectTemplates-~2.nupkg" --operation list" failed with exit code "1":
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

Running command: "npm install -g azure-functions-core-tools@2"...
npm WARN rollback Rolling back azure-functions-core-tools@2.4.419 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'C:\Users\chakr\AppData\Roaming\npm\node_modules\azure-functions-core-tools'
npm ERR! path C:\Users\chakr\AppData\Roaming\npm\node_modules\azure-functions-core-tools
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\chakr\AppData\Roaming\npm\node_modules\azure-functions-core-tools' -> 'C:\Users\chakr\AppData\Roaming\npm\node_modules\.azure-functions-core-tools.DELETE'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chakr\AppData\Roaming\npm-cache\_logs\2019-03-04T17_38_58_322Z-debug.log
Error: Failed to run "npm" command. Check output window for more details.

**Comment by EricJizbaMSFT** [comment]
@ChakritRakuang can you detail what your repros steps were and what your desired behavior is?
