### ISSUE TITLE
Make progress notifications clickable

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1055]
![image](https://user-images.githubusercontent.com/8435148/53791718-e8265980-3ede-11e9-971a-fdb836c0d224.png)

In cases where it could take a long time to execute a task, make the progress notification clickable so users can navigate to the terminal to view the steps being executed. 

/cc @fiveisprime @gbowerman

**Comment by EricJizbaMSFT** [comment]
Currently not possible - tracking issue in VS Code: https://github.com/Microsoft/vscode/issues/60979

**Comment by EricJizbaMSFT** [comment]
We do this now with "View Output" links
