### ISSUE TITLE
Schedule for timer trigger

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#1058]
![image](https://user-images.githubusercontent.com/8435148/53792835-6dab0900-3ee1-11e9-80fa-9ea08d78b96e.png)

![image](https://user-images.githubusercontent.com/8435148/53792874-80bdd900-3ee1-11e9-976b-8be4f5362e48.png)

Two issues here: 

1. Helper link only appears when there is invalid input. Instead, we should surface it from the get go.
2. Link doesn't render correctly. Raw HTML syntax is visible. 

/cc @fiveisprime @gbowerman

**Comment by EricJizbaMSFT** [comment]
So this string is defined here: https://github.com/Azure/azure-functions-templates/blob/20bde0b0ea46ebde088f257a333501e6dd89a3e3/Functions.Templates/Resources/Resources.resx#L982

But I believe that string is also displayed in the portal. Do we want to change it for both or special case Timer Trigger in our extension?

**Comment by asavaritayal** [comment]
Re #1 - I think we want to display the string here: 
https://github.com/Azure/azure-functions-templates/blob/20bde0b0ea46ebde088f257a333501e6dd89a3e3/Functions.Templates/Resources/Resources.resx#L213

For #2, issue isn't really the string itself but that the HTML isn't rendering correctly. Is it possible for Code to make the links clickable?

**Comment by EricJizbaMSFT** [comment]
Fixed the first part, which I think is the more important piece. I'll have to file an issue on VS Code for the second piece

**Comment by EricJizbaMSFT** [comment]
Closing this as fixed since the description is way better at this point. Rendering the link would be more difficult and unclear how VS COde would support that. Wont-fixing that aspect
