### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Govindmallurwar** [Microsoft/vscode-azurefunctions#1072]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.15.0
OS: win32
VS Code Version: 1.31.1

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
TLSSocket.emit (events.js:182:13)
TLSSocket._finishInit (_tls_wrap.js:635:8)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Govindmallurwar are you behind a corporate proxy or something similar? We've been mostly relying on VS Code to fix this for us, which is tracked here: https://github.com/Microsoft/vscode/issues/60773. I believe most situations are fixed already, but perhaps not all.

**Comment by EricJizbaMSFT** [comment]
Could try something like this: https://github.com/Microsoft/vscode-docker/pull/627

**Comment by EricJizbaMSFT** [comment]
I was debugging with Fiddler and was able to repro this bug since it inserts a cert to decrypt https traffic. However, it's fixed for me on VS Code insiders - see here for more info: https://github.com/Microsoft/vscode/issues/52880

Closing as external
