### ISSUE TITLE
Run-From-Zip is set to a remote URL using WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/vscode-azurefunctions#1073]
I randomly started getting this. I don't see any spot where the config property 'WEBSITE_USE_ZIP' would be configured.

Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: Run-From-Zip is set to a remote URL using WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.

Version: 0.15.0
OS: darwin
VS Code Version: 1.32.0

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline (dist/extension.bundle.js:333:388473)
s (dist/extension.bundle.js:277:110820)
s (dist/extension.bundle.js:165:25754)
dist/extension.bundle.js:165:26994
o (dist/extension.bundle.js:223:7055)
dist/extension.bundle.js:165:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] (dist/extension.bundle.js:1:578626)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.EventEmitter.emit (domain.js:442:20)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
$.EventEmitter.emit (domain.js:442:20)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
IncomingMessage.EventEmitter.emit (domain.js:442:20)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mswilson4040 what language is your project? And are you deploying to a Windows or Linux function app in Azure? (Windows is the default for all languages except Python)

Do your application settings look similar to mine?
![Screen Shot 2019-03-08 at 12 49 02 PM](https://user-images.githubusercontent.com/11282622/54055014-97458800-41a0-11e9-83ac-9bfa36784f49.png)

**Comment by mswilson4040** [comment]
@EricJizbaMSFT The language is c#. The error went away after I deleted the WEBSITE_USE_ZIP from the application menu. My guess is that somehow that value got in there and wasn't configured properly so vs code was throwing the error.

**Comment by EricJizbaMSFT** [comment]
We should figure out why `WEBSITE_USE_ZIP` was added and potentially check for this setting before deploying

**Comment by EricJizbaMSFT** [comment]
This should be covered by https://github.com/microsoft/vscode-azurefunctions/issues/1684 and https://github.com/microsoft/vscode-azurefunctions/issues/1683
