### ISSUE TITLE
error macos

### ISSUE THREAD

**Issue by cluzier** [Microsoft/vscode-azurefunctions#1074]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.15.0
OS: darwin
VS Code Version: 1.32.0

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:391:72921)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:391:71912)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@cluzier can you give more information on this or repro steps?
For example:
1. Does this consistently happen?
1. Was this a brand new clean project?
1. What triggers were you using?
1. How is your workspace folder configured?
