### ISSUE TITLE
Deploy Javascript project doesn't create function

### ISSUE THREAD

**Issue by gecko-8** [Microsoft/vscode-azurefunctions#1076]
I'm trying to use the Javascript quick-start guide from the Microsoft docs to test creating a simple function. Unfortunately, it's working fine until I deploy to Azure. After deployment the function app exists but not the function itself. Any help would be greatly appreciated.

Steps to reproduce:
1. Follow this tutorial: [Javascript Getting Started](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code)
2. Deploy to Azure.

Expected results:
- Function app is created on Azure.
- Function app contains HttpTrigger function

Actual results:
- Function app is created on Azure.
- No HttpTrigger function reported in Azure portal or VS Code Azure Functions.
- Not found error in browser when attempting to use function.

Notes:
The function runs fine when testing locally. I've attached the project. Using the following versions:
Node: 10.13.0
Azure Functions Core Tools: 2.4.419 
Azure Functions VS Code extension: 0.15.0

[azureFunctions.zip](https://github.com/Microsoft/vscode-azurefunctions/files/2946714/azureFunctions.zip)

**Comment by EricJizbaMSFT** [comment]
@gecko-8 that project looks just fine to me. How did you create the function app in Azure? Is it a windows function app (the default) or is it "Linux Preview"?

Also can you check the value of the application setting `FUNCTIONS_WORKER_RUNTIME`? It should be set to "node"

**Comment by gecko-8** [comment]
@EricJizbaMSFT I created the function app through the extension's wizard so it should be all defaults. I double checked that it's a Windows instance. FUNCTIONS_WORKER_RUNTIME is set to "node".

**Comment by gecko-8** [comment]
I was just able to manually create a working function app through the portal. I then tried deploying my original function from VS Code to the new function app and once again, the function doesn't appear but all output shows a successful deployment.

**Comment by EricJizbaMSFT** [comment]
Hmm I had no problem deploying your project from VS Code. How are you deploying from VS Code? Aka what entry point (the blue up arrow, right clicking on a folder, right clicking on a function app)?

Also can you post a screenshot of your workspace? We expect it at the project to be at the root of the workspace

**Comment by gecko-8** [comment]
@EricJizbaMSFT Thanks for the quick responses! I'm deploying via the blue arrow.
![Screen Shot 2019-03-08 at 1 41 28 PM](https://user-images.githubusercontent.com/24754972/54054623-efcc5380-41a7-11e9-91ef-1e714e08663f.png)

**Comment by EricJizbaMSFT** [comment]
Still stumped. Did the "func: extension install" task succeed before deploying? It's honestly not needed if you're deploying just an HttpTrigger, so you could remove the "azureFunctions.preDeployTask" from settings.json...

Can you post the full deploy log maybe?

**Comment by gecko-8** [comment]
@EricJizbaMSFT Yeah, I'm stumped too. I don't think the extension install task worked but I tried removing it and I'm still getting a warning about it at the top of the output. Here's the full deployment output if that's what you mean by the deploy log.
```
WARNING: Did not find recommended preDeploy task "func: extensions install". The deployment will continue, but the selected folder may not reflect your latest changes.
In order to ensure that you always deploy your latest changes, add a preDeploy task with the following steps:
1. Open Command Palette (View -> Command Palette...)
2. Search for "Azure Functions" and run command "Initialize Project for Use with VS Code"
3. Select "Yes" to overwrite your tasks.json file when prompted
1:51:26 p.m. jlfuncapp: Creating zip package...
1:51:26 p.m. jlfuncapp: Starting deployment...
1:51:29 p.m. jlfuncapp: Updating submodules.
1:51:29 p.m. jlfuncapp: Preparing deployment for commit id '397b04bf1f'.
1:51:30 p.m. jlfuncapp: Skipping build. Project type: Run-From-Zip
1:51:30 p.m. jlfuncapp: Skipping post build. Project type: Run-From-Zip
1:51:32 p.m. jlfuncapp: Syncing 0 function triggers with payload size 2 bytes successful.
1:51:32 p.m. jlfuncapp: Updating D:\home\data\SitePackages\packagename.txt with deployment 20190308205128.zip
1:51:32 p.m. jlfuncapp: Deployment successful.
Deployment to "jlfuncapp" completed.
```

**Comment by EricJizbaMSFT** [comment]
Well when I deploy, I see this:
```
12:57:59 PM emjjs1: Syncing 2 function triggers with payload size 158 bytes successful.
```

So it seems like you're not getting everything pushed up that should be. Have you edited your `.funcignore` file at all? That controls the files we ignore when deploying. You could try removing that file as a workaround

**Comment by gecko-8** [comment]
@EricJizbaMSFT I haven't changed the .funcignore file but removing it did seem to fix the problem. I'll see if I can narrow things down a bit more.

**Comment by gecko-8** [comment]
@EricJizbaMSFT Looks like it's the local.settings.json line in the .funcignore. That would imply to me that the default settings in the auto-created function app are incorrect. When I download the function app, here's the local.settings.json file I get:

**Comment by gecko-8** [comment]
@EricJizbaMSFT Okay, this is really weird, but I've confirmed it's the .vscode line in the funcignore file. As soon as I remove that line, it works.

**Comment by EricJizbaMSFT** [comment]
I still can't repro this. If we can get more detailed repro steps we'll re-open, but it sounds like @gecko-8 got a good enough workaround
