### ISSUE TITLE
feature: support monorepo format

### ISSUE THREAD

**Issue by thefliik** [Microsoft/vscode-azurefunctions#1087]
The VSCode Azure Functions extension does not seem to support a functions app in a monorepo (where the functions app is in a subfolder of the current project root). Attempting to execute the `Deploy to functions app...` option results in a "Select function app" dropdown list which *only* includes an option to "Create new function app". It appears that you cannot select a function app located in a subfolder of the current project root.

Additionally, the automatically generated "func: host start` debugging task does not seem to allow specifying the functions app project root, and will not work in a monorepo.

**Comment by EricJizbaMSFT** [comment]
Two things here:
1. The naming between a local project and a resource in Azure is confusing. We cleaned up the naming here and it will be included in the next release: https://github.com/Microsoft/vscode-azurefunctions/pull/1070. It sounds like the prompt you're talking about is for the resource in Azure
1. We're tracking support for a monorepo in this issue https://github.com/Microsoft/vscode-azurefunctions/issues/686, but you should be able to make it work with a few manual steps. See this comment: https://github.com/Microsoft/vscode-azurefunctions/issues/686#issuecomment-466252387. I used a C# project as an example - let me know if you want an example for a different project language.

> Additionally, the automatically generated "func: host start` debugging task does not seem to allow specifying the functions app project root, and will not work in a monorepo.

This task should automatically use the folder containing your "host.json" when debugging, even if it's in a sub folder. Let me know if that's not the case.

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate - feel free to add to the other issue
