### ISSUE TITLE
Duplicate output in "Log Stream"

### ISSUE THREAD

**Issue by Braincompiler** [microsoft/vscode-azurefunctions#1089]
I got a duplicate output of logs via the "Log Stream"-Feature:
![Screenshot 2019-03-14 at 17 26 22](https://user-images.githubusercontent.com/142524/54374467-75a43f00-467f-11e9-8fe7-e2c295cae7f9.png)

But the logs are not duplicated at the Azure Portal:
![Screenshot 2019-03-14 at 17 26 29](https://user-images.githubusercontent.com/142524/54374481-7d63e380-467f-11e9-94dd-b8fc8d5c5931.png)

The version I use: 0.15.0

**Comment by EricJizbaMSFT** [comment]
Yeah I can repro this - thanks for reporting. IMO the extra blank lines are also annoying

**Comment by EricJizbaMSFT** [comment]
@Braincompiler fyi the portal doesn't have duplicate lines because it only streams logs for one function at a time. You can replicate that in our extension by right clicking on a function instead of a function app
