### ISSUE TITLE
Standardize virtual env creation Python Functions

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#1092]
Python 3.7 should be supported soon and we might not want to create a virtual environment any more. See: https://github.com/Azure/azure-functions-core-tools/issues/923

**Comment by ankitkumarr** [comment]
With https://github.com/Azure/azure-functions-core-tools/issues/1023 closed and released, there shouldn't be any need to create a virtual environment anymore. :)
