### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:1021

### ISSUE THREAD

**Issue by bjwtufv701** [Microsoft/vscode-azurefunctions#1093]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:1021

Version: 0.15.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@bjwtufv701 can you add repro steps and more information on what type of project you're deploying?
