### ISSUE TITLE
DoITGirls

### ISSUE THREAD

**Issue by OniciBianca** [Microsoft/vscode-azurefunctions#1094]
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run "mvn" command. Check output window for more details.

Version: 0.15.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:9:132016)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:9:130479)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@OniciBianca can you copy the output logs here?
