### ISSUE TITLE
Azure Python Function Deployment Error

### ISSUE THREAD

**Issue by AkkiRai** [Microsoft/vscode-azurefunctions#1103]
Repro steps:

1. Create python function app (http trigger) using visual studio.
2. Deploy the project to azure using visual studio deploy option.
3. Provide provide appropriate like App Name,Region , Storage account, etc.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.15.0
OS: linux
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline (dist/extension.bundle.js:277:2475943)
s (dist/extension.bundle.js:277:110820)
s (dist/extension.bundle.js:165:25754)
dist/extension.bundle.js:165:26994
o (dist/extension.bundle.js:223:7055)
dist/extension.bundle.js:165:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:578661)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@AkkiRai Linux Consumption is still in preview and occasionally reports ServiceUnavailable. Does this happen consistently for you? If you wait a while after creating the function app - does deploying succeed?

**Comment by AkkiRai** [comment]
@EricJizbaMSFT It happened every time whenever I tried to deploy Python Function app on azure using visual studio code on linux. Today I tried it again but  they have removed the python runtime from the deployment as it was not listed in the options for deployment. Deployment succeeded by using javascript runtime but not with python.

**Comment by AkkiRai** [comment]
Thanks @EricJizbaMSFT . It happened every time whenever I tried to deploy Python Function app on azure using visual studio code on linux. Today I tried it again but they have removed the python runtime from the deployment as it was not listed in the options for deployment. Deployment succeeded by using javascript runtime but not with python. Any updates on this?

**Comment by EricJizbaMSFT** [comment]
What region are you deploying to? I believe there were some issues in East US. You could try deploying to a different region.

Also, the list of runtimes depends on which OS you're creating a function app for. If you creating a windows function app (the default since it's not in preview), you will not see python. We default the OS based on your currently open workspace. You can set `azureFunctions.advancedCreation` to `true` in your VS Code settings if you want to be asked for OS/runtime every time.
