### ISSUE TITLE
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

### ISSUE THREAD

**Issue by yashag66** [Microsoft/vscode-azurefunctions#1104]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@yashag66 can you comment with repro steps? Does this happen consistently for you?

Additionally, you can try upgrading to the latest version of the extension (0.15.0). NOTE: you'll have to make sure you're on VS Code version at least 1.31.0 before you can update our extension.

**Comment by sstojanovic-ispt** [comment]
I'm getting the same error consistently as of yesterday. (Deploying was working fine two days ago and prior)

Info:
VS Code Version: 1.32.3
Azure-Functions-Extension: 0.15.0
Azure-Functions-Core-Tools: 2.4.419
OS: Windows 10 - 64
Docker: 18.09.2

Have tried deploying separate Function apps to different subscriptions and Linux App-Service-Plans.

(Side Note: This same error pops up in the portal when trying to access Function app settings.)

**Comment by blair223** [comment]
I'm having exact same issue.  Been happening since 3/16

Deleted all linux function apps and created fresh one and same issue

**Comment by sstojanovic-ispt** [comment]
I tried deploying to a different region (Linux App Service Plan) with success. 

All of my deployments on US-East since yesterday have failed failed while US-West works okay.

**Comment by EricJizbaMSFT** [comment]
@sstojanovic-ispt good to know about the regions - could've been an outage in US-East

Let me know if y'all are still having issues in all regions
