### ISSUE TITLE
Deployment hangs while "creating zip package ..." if a .ts file is opened

### ISSUE THREAD

**Issue by wiggisser** [microsoft/vscode-azurefunctions#1105]
When I try to deploy to azure the task keeps hanging on "creating zip package" step and never finishes. It worked one time after I quit VS-Code and restarted the deployment. But since then I was not able to deploy anymore

Environment: Windows 8.1, VS Code 1.32.3, Azure Functions extension 0.15. Deploying to an azure functions app created via portal

**Comment by EricJizbaMSFT** [comment]
What is your project language?

You can try removing the `.funcignore` file if it exists in your project. (That file is used to exclude files when deploying, but may be causing the bug in "Create zip package")

**Comment by wiggisser** [comment]
Forgot to mention. It's a Typescript project ... Removed the `.funcignore`. No change ...

**Comment by wiggisser** [comment]
that's the content of the `.funcignore` file which was autogenerated by the extension. Did not touch it later on

*.js.map
*.ts
.git*
.vscode
local.settings.json
test
tsconfig.json

**Comment by EricJizbaMSFT** [comment]
Can you expand on `But after a restart of VS Code it seems to work ...`? It's working consistently now? And the only change you made was to remove that file and restart VS Code?

Support for `.funcignore` is pretty new, so it's definitely possible there's a bug related to that... Is there anything unique about this project? Or is this a brand new project created directly from our extension? Maybe you're symlinked to other folders or something?

**Comment by wiggisser** [comment]
I created the project with the extension a few days ago. No symlinks to external folders. I developed and debugged the functions locally and today I decided to deploy them to azure. So I 

1) created a new function app in the portal, 
2) signed in to azure in VS Code, 
3) hit "deploy" 
4) selected my newly created app. 

The project was built without errors. But deploment hung on "creating zip package" for about 5 minutes.

1) Quit VS Code and restarted
2) hit "deploy" and selected my app

The project was build without errors and deployment ran through without any problems (with `.funcignore` still present at that time)

Later I changed some code and wanted to deploy again. It built fine, but again hung at "creating zip package". I tried to restart VS code a few times, but deployment always kept hanging at "creating zip package"

Than I renamed the `.funcignore` file to "foo.bar" and started deployment again (without restarting VS code). Hanging at `creating zip package`. I restarted VS Code and after that deployment worked fine.

I also tried to rename the file back to `.funcignore` and deploy again. It always worked, even after I restarted VS code and the `.funcignore` file is present. All this test deployments where done without any code change.

I then again changed something in my code and the deployment again starts to hang at "creating zip packages". And now I'm stuck there, even after I removed the `.funcignore` file again.

**Comment by wiggisser** [comment]
OK. I think I figured out the reason. It does not have anything to do with the `.funcignore` file. But it does not work if a `.ts` file is opened in an editor. I have a dev-dependency to `@types/node`  in my package json. And while building for the deployment `npm install` is called, which of course installs this dependency. Later in the deployment process `npm prune` is called, which tries to uninstall this package again. 

But if a `.ts` file is open VS-Code has a lock on the folder `node_modules/@types`. While the deployment is stuck, I can still see it in the explorer but when trying to enter I get 'access denied'. As soon as I exit VS-Code the folder vanishes from explorer. This must somehow interfere with creating the zip package.

**Comment by EricJizbaMSFT** [comment]
Hmm yeah it doesn't repro for me with the default dev dependencies, but I can repro if I add `@types/node`. Now that I have a repro we can look into it - thanks for figuring that out!

In the meantime you can always modify the `azureFunctions.preDeployTask` from `prune` to `build`. That seemed to prevent a hang in my case, although it took just a touch longer than previous (successful) deployments since it's zipping up the dev dependencies as well.

**Comment by EricJizbaMSFT** [comment]
Looks like this could be a bug in VS Code: https://github.com/Microsoft/vscode/issues/70865

**Comment by wiggisser** [comment]
Thanks for your answer and the workaround.

**Comment by EricJizbaMSFT** [comment]
Closing as this is fixed on VS Code insiders (https://github.com/microsoft/TypeScript/issues/29407#issuecomment-488466807)
