### ISSUE TITLE
Clearer indication of progress

### ISSUE THREAD

**Issue by jawache** [Microsoft/vscode-azurefunctions#111]
One feature I think would be great would be a clearer visual indicator of progress.

In a normal terminal we know when the script is finished becasue we can see the prompt again, in the vscode it just stops and you never see a terminal. I had to double check by going to the portal to make sure it had worked.

We can have something like a ">> COMPLETE <<" message or maybe a spinner whilst it's running which ends when it finished.

<img width="1539" alt="image001" src="https://user-images.githubusercontent.com/897523/33514618-c9a3872e-d74e-11e7-9202-b52c49854c13.png">

**Comment by EricJizbaMSFT** [comment]
@jawache we released a new version of the extension last Friday - could you try it out and close this issue if you're satisfied with the experience?

We added a spinner as you described:
![create](https://user-images.githubusercontent.com/11282622/33570661-6a61fcb0-d8e2-11e7-8557-96e31caaae84.gif)

**Comment by EricJizbaMSFT** [comment]
Added spinner and more prominent message in log.
