### ISSUE TITLE
"command 'azureFunctions.<function>' not found" Is appearing on every action of the extension.

### ISSUE THREAD

**Issue by charlie632** [Microsoft/vscode-azurefunctions#1114]
`command 'azureFunctions.<function>' not found `

This error message is appearing on every action I do with the extension. Cannot create, nor deploy anything.

My setup is the following:

VSCode: February 2019 (version 1.32)
azure-functions-core-tools@2.4.419
Azure Functions Extension: 0.15.0
Azure Account Extension: 0.8.0

**Comment by charlie632** [comment]
I managed to solve this by deleting the extension folder from `C:\Users\<myuser>\.vscode\extensions`. I had two versions of the extension (0.14 and 0.15). Deleted both folders and installed again the extension and everything worked just fine.

**Comment by EricJizbaMSFT** [comment]
Glad you got that figured out! If you ever get a stable repro let me know and we can file a bug on VS Code. This has happened to me once in a blue moon, but no idea why and it always goes away after deleting that folder
