### ISSUE TITLE
region err

### ISSUE THREAD

**Issue by supremejoondaum** [Microsoft/vscode-azurefunctions#1116]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Requested features are not supported in region.

Version: 0.15.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
module.exports.Ps.l.pipeline (dist/extension.bundle.js:277:2538438)
s (dist/extension.bundle.js:277:110820)
s (dist/extension.bundle.js:165:25754)
$.module.exports.t.create.o.statusCode.t.registerRP.n [as _callback] (dist/extension.bundle.js:165:26967)
$.module.exports.$.init.t._callback.t.callback.t.callback [as callback] (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.EventEmitter.emit (domain.js:442:20)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:182:13)
$.EventEmitter.emit (domain.js:442:20)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
IncomingMessage.EventEmitter.emit (domain.js:442:20)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@supremejoondaum can you describe the repro steps for this issue? For example, what type of project were you deploying? And to what region? Does it work in other regions?

**Comment by supremejoondaum** [comment]
I followed MSDN and proceeded, and I made an error when I chose it as Central Korea.
However, when I chose East Asia, distribution was successful.

**Comment by EricJizbaMSFT** [comment]
Hmm I was able to successfully create a windows function app in the Korea Central region. What OS were you deploying to? We default to Windows OS unless you're deploying a Python project.

In any case, glad the other region worked for you
