### ISSUE TITLE
can not run npm install in win10 pro

### ISSUE THREAD

**Issue by pw007** [Microsoft/vscode-azurefunctions#1117]
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.15.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:1:132939)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:1:132003)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@pw007 can you copy the output of the npm command?
