### ISSUE TITLE
Add documentation for running multiple function projects in the same workspace

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#1118]
Nvm. After some changes on the files similar to what you did on the C# ones I was able to make it work. 

I think it should be documented somewhere that we require those changes.

Thanks!

_Originally posted by @galvesribeiro in https://github.com/Microsoft/vscode-azurefunctions/issues/1081#issuecomment-476220095_

**Comment by EricJizbaMSFT** [comment]
Added here: https://github.com/Microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

Also part of a "Learn more" button added here: https://github.com/Microsoft/vscode-azurefunctions/pull/1124

**Comment by galvesribeiro** [comment]
Thank you!
