### ISSUE TITLE
"View Commit in GitHub" doesn't work on Windows \Mac

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1130]
**OS**: All
**Build Version**: [20190327.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4473)
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure you have signed in GitHub.
2. Right click one function app-->Select "Configure Deployment Source..." --> Select "GitHub".
3. Right click one deployment and select "View Commit in GitHub".

**Expect:**
Navigate to the GitHub --> Commit.
![image](https://user-images.githubusercontent.com/34729092/55072469-6bebe580-5048-11e9-8068-3c5341b90a02.png)

**Actual:**
"View Commit in GitHub" doesn't work.

**More Info:**
This issue dos not reproduce on Linux.

**Comment by nturinski** [comment]
I tested this on Windows and it doesn't seem to reproduce for me.
