### ISSUE TITLE
No 'HttpTrigger' function shows under Functions node after deploying a C# project

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#1131]
**OS:** Linux
**Build Version:** [20190327.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4473)
**Regression:** Previous release

**Repro Steps:**
1. Create a C# project with HTTP trigger template.
2. Debug --> Deploy.
3. Expand the Functions node under the deployed function app -> Check the result.

**Expect:**
'HttpTrigger' function shows under Functions node.

**Actual:**
No 'HttpTrigger' function shows under Functions node.

**Comment by EricJizbaMSFT** [comment]
@v-xianya does this only repro for you on Linux? And do the triggers show up if you restart the function app?

**Comment by v-xianya** [comment]
Hi @EricJizbaMSFT, Thanks for your updates. 
After restarting the function app this issue doesn't reproduce.

**Comment by EricJizbaMSFT** [comment]
Okay I've seen this occasionally and I think it just takes a little bit for the triggers to be synced (restarting the app forces the triggers to sync). Let me know if you see this consistently and we can bother the platform team. Otherwise, closing for now.
