### ISSUE TITLE
Error while publishing Azure Function App

### ISSUE THREAD

**Issue by abashutosh** [Microsoft/vscode-azurefunctions#1134]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.15.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError (dist/extension.js:1:49013)
b.<anonymous> (dist/extension.js:229:176356)
dist/extension.js:229:170971
dist/extension.js:229:42963
dist/extension.js:229:40956
dist/extension.js:229:40578
i.module.exports.i.find (dist/extension.js:229:75071)
module.exports.find.init.then (dist/extension.js:229:22902)
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - closing as external issue: https://github.com/Microsoft/vscode-azure-account/issues/53
