### ISSUE TITLE
Cannot deploy function app from VSCODE: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by etaham** [Microsoft/vscode-azurefunctions#1135]
Repro steps:
I am behind a corp proxy that has it's own SSL/TLS cert. The cert is added to my computer's CA store (keychain).

I have the following setting in my settings.json:
"http.proxyStrictSSL": false

I have latest version of the extension and function tools installed. 

To Reproduce:
1. Sign into azure account
2. Attemped to deploy a function App

Action: azureFunctions.deploy
Error type: SELF_SIGNED_CERT_IN_CHAIN
Error Message: self signed certificate in certificate chain

Version: 0.15.0
OS: darwin
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
TLSSocket.emit (events.js:182:13)
TLSSocket.EventEmitter.emit (domain.js:442:20)
TLSSocket._finishInit (_tls_wrap.js:635:8)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@etaham can you try [VS Code Insiders](https://code.visualstudio.com/insiders/)? @chrmarti recently did some work to use a computer's CA store here: https://github.com/Microsoft/vscode/issues/52880

**Comment by etaham** [comment]
The insiders version fixed the issue. Thank you!
