### ISSUE TITLE
Formerly disabled subscription is not recognized as enabled

### ISSUE THREAD

**Issue by Strernd** [Microsoft/vscode-azurefunctions#1146]
I had a function, that was disabled due to disabled subscription. I now changed the subscription in the Azure Web UI and the function is working again.
However performing actions in VS Code gives me the error.

```
The subscription 'xxxxxxxx-xxxxxxxx-xxxxxxxxx' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.
```

This does not seem to reflect the actual state.

Sign out and Sign In didn't work.

**Comment by EricJizbaMSFT** [comment]
Moved to azure account repo: https://github.com/Microsoft/vscode-azure-account/issues/137
