### ISSUE TITLE
Create new Java HttpTrigger ignores AuthorizationLevel selection

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#115]
Even if I select 'Admin' or 'Function', it's always set to 'Anonymous'

**Comment by jdneo** [comment]
Yes, this is because currently maven plugin does not have that property prompted. I'll raise a PR for that fix in maven plugin repo.

**Comment by jdneo** [comment]
Update: I create a PR in the maven plugin repo to fix this issue. https://github.com/Microsoft/azure-maven-plugins/pull/70

**Comment by jdneo** [comment]
The maven azure function plugin has been updated and released. Now if you are creating a new Java function project, the project will use the newest version of maven azure function plugin, which support specifying authorization level.

If you are using the projected which was created before, please make sure the maven azure function plugin version is 0.1.9 or higher. The version can be set in the ```pom.xml```:

```
<build>
    <pluginManagement>
        <plugins>

            ...

            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <version>0.1.9</version>
            </plugin>
        </plugins>
    </pluginManagement>

    ...

</build>
```

**Comment by EricJizbaMSFT** [comment]
Verified this has been fixed - closing the issue.
