### ISSUE TITLE
[Suggestion]Can't use curl command on the machine which has no 'Internet Explorer' browser

### ISSUE THREAD

**Issue by v-ruizh** [Microsoft/vscode-azurefunctions#1153]
OS: Windows
Node.js: V10.15.0
Build Version: [20190402.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4643)
Azure Functions Core Tools: V2.4.498

Repro Steps:

1. Create a C# project on the machine which has no 'Internet Explorer' browser.
2. Create a new function with 'HTTP trigger' template and 'Function' level.
3. Set a breakpoint in HttpTrigger file and F5.
4. Copy the HttpTrigger URL that shows in 'Terminal' view and run 'curl <HttpTrigger URL> ?name=123'.

Result:
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/55463297-4dc74c00-562b-11e9-9bc8-a05c8e45b387.png)

Suggestion:
It's not convenient to use the curl command on the machine without IE browser, could you also support it for Microsoft Edge?

**Comment by EricJizbaMSFT** [comment]
@v-ruizh we have no control over curl or your browser. Closing as external
