### ISSUE TITLE
Include simple package.json file by default for plain JS

### ISSUE THREAD

**Issue by ColbyTresness** [Microsoft/vscode-azurefunctions#1155]
We include a package.json file for TS, and we should include a very simple package.json file by default on function app creation. This is something we're planning on adding to the CLI experience as well.

**Comment by fiveisprime** [comment]
Is this to increase visibility of where to run npm install or will this also include all the scripts like we do for TS?

**Comment by ColbyTresness** [comment]
@mhoeger is planning on including some simple scripts, but not all those in the TS package.json. Primary purpose is showing people how to do the right things.

**Comment by mhoeger** [comment]
https://github.com/Azure/azure-functions-core-tools/pull/1206
