### ISSUE TITLE
unable to deploy a python ML predictor function

### ISSUE THREAD

**Issue by haripravin** [Microsoft/vscode-azurefunctions#1157]
Repro steps:

1. use the below command to push the python based code
func azure functionapp publish <app name> --build-native-deps --no-bundler

note: previously it was working fine, its not working for the past 2 days 

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/haripravins/Mobi/AutoSuggestMultiple/AutoSuggestMultiple.zip

Version: 0.15.0
OS: darwin
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:333:479084)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:333:478665)
i (dist/extension.js:126:22071)
dist/extension.js:126:22415
```

</details>

**Comment by EricJizbaMSFT** [comment]
@haripravin How are you deploying? With the above command or through VS Code?

**Comment by haripravin** [comment]
@EricJizbaMSFT tried deploying the command line , later was able to successfully deploy through VScode. Just wondering why the Zip file went missing wen using the command line

**Comment by EricJizbaMSFT** [comment]
For python projects, the `func` cli deletes and re-creates the zip file every time you deploy. If it failed to install dependencies or some other error happened, it might have failed to create the zip file. It's hard to know without more detailed repro steps
