### ISSUE TITLE
Error on first compile

### ISSUE THREAD

**Issue by psined1** [Microsoft/vscode-azurefunctions#1160]
Created Azure C# function in VSC 1.33 for MacOS. Without any modifications, the first attempt to debug (F5) the project leads to the following error -

```
> Executing task: dotnet clean <

Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/local/share/dotnet/sdk/2.1.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/Users/denisp/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj]
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

```

1.2.Action: azureFunctions.pickProcessError type: ErrorError Message: Failed to start debugging. Task "clean" failed with exit code "1".Version: 0.16.0OS: darwinVS Code Version: 1.33.0<details><summary>Call Stack</summary>```module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.e (dist/extension.bundle.js:391:81272)u.fire (/Applications/Visual Studio extensionHostProcess.js:44:708)D.<anonymous> (/Applications/Visual Studio extensionHostProcess.js:571:708)Generator.next (<anonymous>)s (/Applications/Visual Studio extensionHostProcess.js:11:9)```</details>

**Comment by EricJizbaMSFT** [comment]
@psined1 this line seems to be the important error:

> /usr/local/share/dotnet/sdk/2.1.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/Users/denisp/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj]

Can you try following those directions?

**Comment by psined1** [comment]
Thanks!

I have 2 .Net Core versions installed -

`
MacBook-Pro:~ user1$ ls /usr/local/share/dotnet/shared/Microsoft.NETCore.App/
2.0.5	2.2.3
MacBook-Pro:~ user1$
`

So, I had downgraded target framework in csproj from 2.1 to 2.0 and everything worked.

`<TargetFramework>netcoreapp2.0</TargetFramework>`

Does this essentially mean .Net Core 2.2 is not supported for Azure functions?

**Comment by psined1** [comment]
I should mention that pointing target framework to 2.2 appear to break things..

**Comment by EricJizbaMSFT** [comment]
Hmm that error seems to be coming from `/usr/local/share/dotnet/sdk/2.1.4/`, aka not anything functions related. Do you have .NET Core 2.2 installed on your machine and is it the default one in your path? (Try running `dotnet --info` to see what the versions are)

It looks like other people have had similar issues. Maybe check out things like this: https://developercommunity.visualstudio.com/content/problem/213229/the-current-net-sdk-does-not-support-targeting-net.html

**Comment by EricJizbaMSFT** [comment]
Based on https://github.com/Azure/azure-functions-host/issues/3611, it looks like .NET Core 2.2 should be supported by functions

**Comment by psined1** [comment]
Here's the dump -

```
MacBook-Pro:~ user1$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
MacBook-Pro:~ user1$ 

```

**Comment by EricJizbaMSFT** [comment]
Yeah so I see 2.1.4 listed for .NET Core SDKs, but not anything 2.2.

Try installing the latest 2.2 sdk from here: https://dotnet.microsoft.com/download

**Comment by psined1** [comment]
Thanks for your continued support!

OK, just refreshed SDK. Showing the following now -

`
MacBook-Pro:~ user1$ ls /usr/local/share/dotnet/shared/Microsoft.NETCore.App/
2.0.5	2.2.3	2.2.4
MacBook-Pro:~ user1$ 
`

Showing 2.2 SDK installed -

`
.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
`
Updated target framework in csproj to netcoreapp2.2 -

`
<TargetFramework>netcoreapp2.2</TargetFramework>
`

Restarted VSC. Attempting to rebuild solution, getting errors -

```
> Executing task: dotnet clean <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/10/19 8:56:53 AM.
     1>Project "/Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj" on node 1 (Clean target(s)).
     1>/usr/local/share/dotnet/sdk/2.2.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1005: Assets file '/Users/user1/Desktop/VM/Integrations/Comfort/Functions/obj/project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project. [/Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj]
     1>Done Building Project "/Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj" (Clean target(s)) -- FAILED.

Build FAILED.

       "/Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj" (Clean target) (1) ->
       (ResolvePackageAssets target) -> 
         /usr/local/share/dotnet/sdk/2.2.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1005: Assets file '/Users/user1/Desktop/VM/Integrations/Comfort/Functions/obj/project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project. [/Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.45
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

```
Reverting back to 2.0 target solves the problem.

**Comment by EricJizbaMSFT** [comment]
I think that error will go away if you delete the `obj` and `bin` folders after you change the targetFramework. Basically it wrote some files specific to your old target framework and it needs to start clean on the new target framework.

As an aside, make sure to do a "find" with the old target framework in the `.vscode` folder and update any settings there. Just curious - did you do that already? If not - I may repurpose this issue to automatically update those settings if we detect users have changed their target framework...

**Comment by psined1** [comment]
That would allow me compile the solution. However, the terminal output looks very different and I get "No process with specified id is currently running" warning dialog, pointing to launch.json, in which I have the following -

```
{
  "version": "0.2.0",
  "configurations": [
    
    {
      "name": "Attach to .NET Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    }
  ]
}
```

No process is started. Here's the terminal output -

```
> Executing task: dotnet build <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 45.68 ms for /Users/user1/Desktop/VM/Integrations/Comfort/Functions/Functions.csproj.
  Functions -> /Users/user1/Desktop/VM/Integrations/Comfort/Functions/bin/Debug/netcoreapp2.2/bin/Functions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.57

Terminal will be reused by tasks, press any key to close it.

> Executing task: func host start <

chdir(2) failed.: No such file or directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by EricJizbaMSFT** [comment]
Yes please see the second section of my previous comment

**Comment by psined1** [comment]
I think that last thing has nailed it! I had 2.1 referenced in 2 different places -

in settings.json:

`"azureFunctions.deploySubpath": "bin/Release/netcoreapp2.2/publish"`

and in tasks.json:

```
{
      "type": "func",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netcoreapp2.2"
      },

```
Thanks for your help. It works great now!
