### ISSUE TITLE
test

### ISSUE THREAD

**Issue by liuliyang** [Microsoft/vscode-azurefunctions#1173]
Repro steps:1.2.Action: azureFunctions.createFunctionError type: ErrorError Message: Failed to run "mvn" command. Check output window for more details.Version: 0.16.0OS: win32VS Code Version: 1.33.0<details><summary>Call Stack</summary>```Object.<anonymous> (C:/Users/Sea dist/extension.bundle.js:1:532913)Generator.next (<anonymous>)o (C:/Users/Sea dist/extension.bundle.js:1:531355)o (C:/Users/Sea out/extension.js:1:69130)C:/Users/Sea out/extension.js:1:69474```</details>

**Comment by EricJizbaMSFT** [comment]
@liuliyang can you copy the output of the mvn command that failed?
