### ISSUE TITLE
Freshly created JavaScript Azure Functions project throws an error when starting debug

### ISSUE THREAD

**Issue by petmat** [Microsoft/vscode-azurefunctions#1175]
I just created a new JavaScript Azure Functions project with a HttpTrigger function and now when I hit F5 to debug it I get the following error in the terminal:

```
> Executing task: func extensions install <

Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.The terminal process terminated with exit code: 1
```
Why could this be?

I have installed:
Visual Studio Code v1.33.0
Azure Functions extension v0.16.0
azure-functions-core-tools v2.5.553
Windows Pro 10.0.17134

Here's my tasks.json:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "dependsOn": "func: extensions install",
      "isBackground": true
    }
  ]
}
```
and here's my launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Node Functions",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "preLaunchTask": "func: host start"
    }
  ]
}
```

**Comment by EricJizbaMSFT** [comment]
@petmat can you post a screenshot of your workspace? I'm just wondering what files you have and what the folder structure looks like

**Comment by petmat** [comment]
Sure thing @EricJizbaMSFT , here you go

![image](https://user-images.githubusercontent.com/3600035/55952789-18da7b00-5c63-11e9-814d-befc6d6da828.png)

**Comment by EricJizbaMSFT** [comment]
Hmm I'm kind of stumped on this one - your project looks fine. Since you're only doing http triggers, you can actually remove `"dependsOn": "func: extensions install",` from your launch.json file. That might simplify things a bit. You'd have to add that back if you do any trigger other than http or timer.

**Comment by petmat** [comment]
Removing `"dependsOn": "func: extensions install"` just results in:

```
> Executing task: func host start <

Unable to find project root. Expecting to find one of host.json, local.settings.json in project root. The terminal process terminated with exit code: 1
```

So both `func extensions install` and `func host start` result in the same error.  I know this is weird but I would really like to get this to work since I'll be demoing Azure Functions in front of live audience in couple of days and I would really like to be able to say this is really easy, but now it seems like it really isn't for some reason...

**Comment by EricJizbaMSFT** [comment]
Okay a few things you can try:
- Explicitly add the workspace folder as the cwd and then debug:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "options": {
        "cwd": "${workspaceFolder}"
      }
    }
  ]
}
```

- Try creating a new terminal in VS Code (while you have that workspace open) and manually run `func host start`. This won't help you debug, but I'm just curious if you get the same error

- Add this to your tasks.json and try running that task to see what the current directory is. Again this won't help you debug - just curious if it shows the right directory. (`$PWD` should show the current directory if you're using powershell by default. If you're using command prompt, you'd have to change this to `cd` I think):
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "Show directory",
      "command": "$PWD",
      "problemMatcher": []
    }
  ]
}
```

- Try using VS Code insiders: https://code.visualstudio.com/insiders/ (just in case this was a bug in VS Code core)

**Comment by petmat** [comment]
Thank you for giving so many things to try. I couldn't figure out the problem trying them out but it gave me an idea about what I was doing wrong.

The way the problem started to unravel was when I read your second thing to try. When I open the integrated terminal it always points to the root of my C-drive `C:\`. So I could not just run `func host start` unless I first run `cd folder1/folder2`. Then I remembered something that I did a long time ago that might be interferring with how the Visual Studio Code integrated terminal works.

I'm using Powershell as the integrated terminal in Visual Studio Code. Some time ago I set the profile file to do the following things:```
Set-Location C:\
```

I did that because the default way Powershell works is that when you start it the default folder is the profile-folder in Windows and I would prefer it to be the root of the C-drive.

However this has an unwanted side-effect of forcing the integrated terminal in Visual Studio Code to always open in the same `C:\` directory.

So it turns out the problem was my Powershell profile file all along.

Not sure if this is something that could be fixed in a way that would allow the `Set-Location` in the profile file, but for now I'm really happy to just remove it and get the debugging working!

Once again thank you for being helpful and undestanding. Turns out there is nothing wrong with your product and it was just my own scripting all along. I'm happy to be able to do my demo now.

**Comment by EricJizbaMSFT** [comment]
Awesome - glad you got that figured out! In terms of improvements, I don't think there's much we can do in the VS Code extension, but I did file an issue on the func cli to make the original error message more clear: https://github.com/Azure/azure-functions-core-tools/issues/1214
