### ISSUE TITLE
Error message after deleting a function

### ISSUE THREAD

**Issue by pdaverh** [Microsoft/vscode-azurefunctions#1177]
Repro steps:1.2.Action: azureFunctions.deleteFunctionError type: 404Error Message: 404 - ""Version: 0.16.0OS: darwinVS Code Version: 1.33.0<details><summary>Call Stack</summary>```new i (dist/extension.bundle.js:333:448608)$.callback (dist/extension.bundle.js:333:447457)$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:333:446511)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:182:13)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@pdaverh can you give more detailed repro steps? For example, what type of project were you deploying and how did you create this function app?
