### ISSUE TITLE
Can't deploy functionapp from VSCode

### ISSUE THREAD

**Issue by fabricioruela** [Microsoft/vscode-azurefunctions#1179]
Repro steps:1.2.Action: azureFunctions.deployError type: BadRequestError Message: Encountered an error (InternalServerError) from host runtime.Version: 0.16.0OS: darwinVS Code Version: 1.33.0<details><summary>Call Stack</summary>```module.exports.a.pipeline (dist/extension.bundle.js:277:2559146)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@fabricioruela can you give us repro steps for this issue?
