### ISSUE TITLE
Azure python function creation only work if I create in desktop because python version difference

### ISSUE THREAD

**Issue by anindya5** [microsoft/vscode-azurefunctions#1182]
I have both python 3.6 and 3.7 in system.

While creating the function for first time I used my desktop as the starting folder. I gave the path for python 3.6 at that time.

however, now I can only create my function in my desktop, and if I select any other folder, it'll tell me

"""unning command: ". .env/bin/activate && func init ./ --worker-runtime python "...
Python 3.6 is required. Current python version is '
Python 3.7.2

'
Error: Failed to run ". .env/bin/activate && func init ./ --worker-runtime python" command. Check output window for more details.
"""

**Comment by EricJizbaMSFT** [comment]
@anindya5 can you show me some screenshots of your workspace in VS Code? And is it asking you for the path to python when you try to create a project?

A few other questions:
1. Version of the functions extension in VS Code
1. Version of func cli (run `func --version`)

**Comment by asavaritayal** [comment]
This is probably related to - https://github.com/Azure/azure-functions-core-tools/issues/1229

**Comment by EricJizbaMSFT** [comment]
Closing this issue as the python version resolution logic has changed in both VS Code (see https://github.com/microsoft/vscode-azurefunctions/pull/1188) and the func cli since (see above linked issue)
