### ISSUE TITLE
Error after changing something on files

### ISSUE THREAD

**Issue by Wankishh** [Microsoft/vscode-azurefunctions#1191]
Repro steps:1.2.Action: azureFunctions.deployError type: EPERMError Message: EPERM: operation not permitted, scandir 'c:\Users\Ivan\Desktop\projects\importexternalsource\node_modules\@types'Version: 0.16.0OS: win32VS Code Version: 1.33.1

**Comment by EricJizbaMSFT** [comment]
Likely a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/1105
