### ISSUE TITLE
403 error when deploying Java demo function app from VS Code

### ISSUE THREAD

**Issue by SekharMatli** [Microsoft/vscode-azurefunctions#1195]
Repro steps:1.2.Action: azureFunctions.deployError type: 403Error Message: Failed with code "403".Version: 0.16.0OS: darwinVS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@SekharMatli please post repro steps for your issue

**Comment by SekharMatli** [comment]
@EricJizbaMSFT The steps are as follows:
In VSC
1. Create a Java function using "Add Function" in an already created Http trigger project.
2. Click on Deploy Function App(Upwards Arrow)
3. click on "Create a new Function App in Azure"
4. Enter the globally unique name for the app. Click Enter

403 error  resulted.

**Comment by EricJizbaMSFT** [comment]
Thanks for the info - can you try setting azureFunctions.advancedCreation to true in your VS Code settings and trying again? That will prompt you for more values and it might help me figure out exactly which step is failing

**Comment by SekharMatli** [comment]
I have the same 403 issue when I try to deploy the function from CLI. Suspecting a network issue. Will try on home network and update.

**Comment by EricJizbaMSFT** [comment]
@SekharMatli could yours be the same issue as https://github.com/Microsoft/vscode-azurefunctions/issues/1194? In that case, the user doesn't have permissions to create a resource group, but it will succeed if they use the advancedCreation flag and select an existing resource group

**Comment by SekharMatli** [comment]
@EricJizbaMSFT I tried to deploy FUnction, not the Function App. When I deployed FunctionApp, it worked. But for some reason, it threw 403, instead of erroring FunctaionApp to be deployed etc..
