### ISSUE TITLE
Language detection for creating functions displays wrong triggers

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#120]
1. Create a Java function project in a folder
2. In the same folder, create a new JavaScript function project and overwrite the old Java project
3. Create a function in the new JavaScript function project and it will prompt you to create Java functions

**Comment by EricJizbaMSFT** [comment]
Closing as wont-fix. We don't expect users to be mixing project languages like this and it happens because you have a "pom.xml" in a JavaScript project
