### ISSUE TITLE
Deploy error 403

### ISSUE THREAD

**Issue by jiayanguo** [microsoft/vscode-azurefunctions#1205]
Repro steps:1.2.Action: azureFunctions.deployError type: 403Error Message: Failed with code "403".Version: 0.16.0OS: darwinVS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@jiayanguo please add repro steps to this issue
