### ISSUE TITLE
Azure Functions debug failed

### ISSUE THREAD

**Issue by diwa2508** [microsoft/vscode-azurefunctions#1206]
1.2.Action: azureFunctions.pickProcessError type: ErrorError Message: Failed to detect running Functions host within 60 seconds. You may want to adjust the azureFunctions.pickProcessTimeout setting.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```Object.<anonymous> (dist/extension.bundle.js:391:80825)Generator.next (<anonymous>)o (dist/extension.bundle.js:391:79342)```</details>

**Comment by EricJizbaMSFT** [comment]
@diwa2508 please add repro steps for this issue
