### ISSUE TITLE
Running Azure function crashing with VS Code

### ISSUE THREAD

**Issue by DevendraRawat** [Microsoft/vscode-azurefunctions#1209]
Repro steps:1.2.Action: azureFunctions.pickProcessError type: ErrorError Message: Functions host is no longer running.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```dist/extension.bundle.js:391:81737Generator.next (<anonymous>)o (dist/extension.bundle.js:391:79342)```</details>

**Comment by EricJizbaMSFT** [comment]
@DevendraRawat please add repro steps to this issue

**Comment by DevendraRawat** [comment]
@EricJizbaMSFT ,

Here are the steps:
1. Installed Azure Functions for VSCode. 
2. Created sample function as per Azure docs.
3. F5
4. Getting popup "You must have the Azure Functions Core Tools installed to debug your local functions.". Even though I installed it multiple times.
5. And then this error which is sent.

Hope this helps

**Comment by EricJizbaMSFT** [comment]
Have you tried restarting VS Code after installing the Azure Functions Core Tools? Perhaps your PATH environment variable wasn't up to date.

Also try running `func --version` from the command line and let me know what it says to see if you successfully installed the cli

**Comment by DevendraRawat** [comment]
Restarted VS Code but no luck.

I executed command - func --version , but got below error. It seems it's
not installed properly.

'func' is not recognized as an internal or external command,
operable program or batch file.

Do I need to follow some specific steps to ensure its installed
appropriately?

I've got node ver 11.x
.Net Core . 2.2.x



Regards,
Devendra Singh Rawat
99635 20791

**Comment by EricJizbaMSFT** [comment]
If you're on windows, this is the command to install the func cli:
```
npm i -g azure-functions-core-tools@2
```

There's more instructions here: https://github.com/Azure/azure-functions-core-tools/blob/master/README.md#installing

**Comment by DevendraRawat** [comment]
I tried this earlier. Here is the screen shot of fresh try again:
[image: image.png]

I am trying it on windows 10 machine with .net net core version - 2.2.x and
2.1.x installed.

Regards,
Devendra Singh Rawat
99635 20791

**Comment by EricJizbaMSFT** [comment]
Hmm in your screenshot it looks like you're running in `D:\`, but the npm commands are running in `C:\`. Could that be part of the problem?

**Comment by DevendraRawat** [comment]
Hi Eric,

Thanks for continuous follow up on this. It was an issue as path was not
setup. I thought I've setup path variable appropriately. It is all working
and up after setting up path environment variable.

Thanks again for your continuous support.

Regards,
Devendra Singh Rawat
99635 20791

**Comment by EricJizbaMSFT** [comment]
Glad to hear you got that figured out!
