### ISSUE TITLE
Function Debugging error

### ISSUE THREAD

**Issue by DevendraRawat** [microsoft/vscode-azurefunctions#1216]
Repro steps:1.2.Action: azureFunctions.pickProcessError type: ErrorError Message: Functions host is no longer running.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```dist/extension.bundle.js:391:81737Generator.next (<anonymous>)o (dist/extension.bundle.js:391:79342)```</details>

**Comment by EricJizbaMSFT** [comment]
@DevendraRawat please add repro steps
