### ISSUE TITLE
Error While Debugging

### ISSUE THREAD

**Issue by neudurgeshp** [microsoft/vscode-azurefunctions#1217]
Repro steps:1.2.Action: azureFunctions.pickProcessError type: ErrorError Message: Failed to start debugging. Task "clean" failed with exit code "2".Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.e (dist/extension.bundle.js:391:81272)u.fire (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:44:708)D.<anonymous> (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:571:708)Generator.next (<anonymous>)s (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:11:9)```</details>

**Comment by EricJizbaMSFT** [comment]
@neudurgeshp please add repro steps or copy the output logs from the "clean" task that failed
