### ISSUE TITLE
ErrorVS code on linux

### ISSUE THREAD

**Issue by hartou** [microsoft/vscode-azurefunctions#1219]
Repro steps:1.2.Action: azureFunctions.createFunctionError type: ErrorError Message: Failed to run "python3.6" command. Check output window for more details.Version: 0.16.0OS: linuxVS Code Version: 1.33.1<details><summary>Call Stack</summary>```Object.<anonymous> (dist/extension.bundle.js:1:131455)Generator.next (<anonymous>)o (dist/extension.bundle.js:1:130519)```</details>

**Comment by EricJizbaMSFT** [comment]
@hartou please add repro steps or copy the output of python command from the "Azure Functions" output window
