### ISSUE TITLE
Deploying a python function to azure does not work

### ISSUE THREAD

**Issue by yannickmorel** [microsoft/vscode-azurefunctions#1222]
Repro steps:1.2.Action: azureFunctions.deployError type: ErrorError Message: Python projects are not supported on Windows Function Apps.  Deploy to a Linux Function App instead.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```Object.<anonymous> (dist/extension.bundle.js:391:67390)Generator.next (<anonymous>)o (dist/extension.bundle.js:391:64243)```</details>

**Comment by EricJizbaMSFT** [comment]
@yannickmorel please add repro steps to the issue. If you selected a Windows function app when deploying a python project - that is not supported
