### ISSUE TITLE
Don't prompt for storage account when running locally

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1225]
Currently, if you pick a non-HTTP trigger, Code prompts you to pick a storage account for your project. This is not required to run locally and instead should be prompted for during app creation in Azure.

**Comment by EricJizbaMSFT** [comment]
@asavaritayal can you expand on this? Was this a recent change?

**Comment by EricJizbaMSFT** [comment]
Yeah I see this in my logs:
```
> Executing task: func host start <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.6.1048 Commit hash: f289117b0d44b321307bae9c96cd910f92057735)
Function Runtime Version: 2.0.12408.0
Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Perhaps you just meant users could leverage the local emulator on Windows? In any case, we have an open issue to improve this experience: https://github.com/Microsoft/vscode-azurefunctions/issues/976. Closing this as duplicate, but I would love to get your opinion on that issue in terms of best user experience.

**Comment by asavaritayal** [comment]
> Was this a recent change?
No 

Core Tools adds a dummy app setting e.g.

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "{AzureWebJobsStorage}"
  }
}

```

The dummy setting is enough for local debugging.

**Comment by EricJizbaMSFT** [comment]
@asavaritayal that may work for http triggers, but as soon as I add anything else, I see this:

> [4/30/19 4:41:44 PM] The listener for function 'Functions.TimerTrigger' was unable to start.
> [4/30/19 4:41:44 PM] The listener for function 'Functions.TimerTrigger' was unable to start. Microsoft.WindowsAzure.Storage: Settings must be of the form "name=value".

In addition, this is what [the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) say, with no mention of that placeholder:

> AzureWebJobsStorage is a required app setting for triggers other than HTTP. 
> Version 2.x of the Functions runtime requires the FUNCTIONS_WORKER_RUNTIME setting, which is generated for your project by Core Tools. 
> When you have the Azure storage emulator installed locally, you can set AzureWebJobsStorage to UseDevelopmentStorage=true and Core Tools uses the emulator. This is useful during development, but you should test with an actual storage connection before deployment.

As an aside, the core tools _will_ use an environment variable if you set `AzureWebJobsStorage` on your machine in the past. If you're not seeing the same errors that I'm seeing - perhaps you set that environment variable a while ago and forgot about it?
