### ISSUE TITLE
Remove .env from Python function projects

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1227]
We no longer require a virtual environment for the development of Python Functions. Instead, we should prompt the user to pick the Python interpreter for their app.

**Comment by EricJizbaMSFT** [comment]
@asavaritayal we already have a setting to turn off virtual environment creation if desired, but there's a difference between "no requirement" and "removing". I think a virtual environment is still recommended best practice, correct? (At least from our perspective where we're creating a new project)

See https://github.com/Microsoft/vscode-azurefunctions/pull/1188 for more information.
