### ISSUE TITLE
vscode created project, hit deploy without any changes and got error

### ISSUE THREAD

**Issue by manish-shukla01** [microsoft/vscode-azurefunctions#1230]
Repro steps:1.2.Action: azureFunctions.deployError type: ErrorError Message: Did not find preDeploy task "func: extensions install". Change the "azureFunctions.preDeployTask" setting, manually edit your task.json, or re-initialize your VS Code config with the following steps:1. Open Command Palette (View -> Command Palette...)2. Search for "Azure Functions" and run command "Initialize Project for Use with VS Code"3. Select "Yes" to overwrite your tasks.json file when promptedVersion: 0.16.0OS: darwinVS Code Version: 1.32.3<details><summary>Call Stack</summary>```dist/extension.bundle.js:391:70867Generator.next (<anonymous>)module.exports.n (dist/extension.bundle.js:391:64410)new Promise (<anonymous>)module.exports.n (dist/extension.bundle.js:391:64187)dist/extension.bundle.js:391:69667Object.<anonymous> (dist/extension.bundle.js:391:71746)Generator.next (<anonymous>)o (dist/extension.bundle.js:391:64243)```</details>

**Comment by EricJizbaMSFT** [comment]
@manish-shukla01 can you post a screenshot of your workspace? I'm wondering what your folder structure looks like

In addition, how did you create your project? Directly from VS Code? And what language is the project?
