### ISSUE TITLE
Improve the experience of getting a fresh local.settings.json

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1233]
I wanted to get a fresh `local.settings.json` for an existing function app and had to click "No" quite a few times (7-8).

**Comment by EricJizbaMSFT** [comment]
User ran into this here: https://github.com/microsoft/vscode-azurefunctions/issues/1356

We could theoretically detect when the file is missing and automatically prompt just to recreate the file
