### ISSUE TITLE
Task and launch config does not get updated for multi-root workspace

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1235]
Repro steps:
1. File -> Add folder to workspace
1. Add an empty folder
1. Create a new project in that folder

Expected:
.vscode/tasks.json and .vscode/launch.json exist and enable user to F5/deploy

Actual:
Those files don't exist

**Comment by alexweininger** [comment]
I tried to repro this bug and couldn't. It worked each time for me. What is the status of this bug, specifically in relation to #1236?

**Comment by EricJizbaMSFT** [comment]
Well I implemented a workaround in #1236, which is why you can't repro, but my workaround shouldn't be necessary. I believe there's a bug in VS Code, but at this point I don't think it's worth the time filing
