### ISSUE TITLE
Bug: cannot see "Azure slots (preview)" in explorer

### ISSUE THREAD

**Issue by ianychoi** [Microsoft/vscode-azurefunctions#1242]
According to https://github.com/Microsoft/vscode-azurefunctions/issues/82 , "Azure slots (preview)" should be shown in explorer after `0.14.0`, but a user reports that the user cannot see Azure slots. I am reporting with more details:

- vscode-azurefunctions version: 0.16.0
- VSCode information
```
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

- My Azure Portal screen:
![image](https://user-images.githubusercontent.com/6965982/56951029-be518200-6b71-11e9-8931-dcdbbd6ef168.png)

- Explorer status:
![image](https://user-images.githubusercontent.com/6965982/56951061-cf01f800-6b71-11e9-8bef-a026e38cdc4a.png)

Would you investigate in whether it is a bug or guide how to well make use of such a nice functionality which were already implemented?

**Comment by EricJizbaMSFT** [comment]
Slots are hidden behind a feature flag right now. You have to change the setting `azureFunctions.enableSlots` to `true` in your VS Code settings.

We will show them by default once we fix this bug: https://github.com/Microsoft/vscode-azurefunctions/issues/830

**Comment by ianychoi** [comment]
Thanks a lot for your quick and prompt help on it - sharing a screenshot for future reference.

![image](https://user-images.githubusercontent.com/6965982/56999138-eaf4b080-6be8-11e9-88c3-5c9c11e7f7f6.png)

(Closing the issue since there is the resolution and showing them by default is mentioned in another issue)
