### ISSUE TITLE
Failed to debug second time if using Azurite

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1245]
Repro steps:
1. Create a javascript project
1. Add a timer trigger
1. Set `AzureWebJobsStorage` to  `UseDevelopmentStorage=true`
1. Make sure azurite is running (https://github.com/Azure/Azurite/blob/master/README.md#installation-and-usage)
1. Debug
1. Detach
1. Debug again

Expected:
It attaches

Actual:
It never attaches because the following is never printed: 
> Host lock lease acquired by instance ID '000000000000000000000000D21F4D53'.

**Comment by EricJizbaMSFT** [comment]
https://github.com/Azure/Azurite/issues/37

**Comment by JustinGrote** [comment]
This happens if you use any remote storage in my observation.

To fix, the problemMatcher for the task should match on the Job host starting, not on the lease request.

```
[5/3/2019 1:02:23 AM] Host initialized (632ms)
[5/3/2019 1:02:23 AM] Host started (644ms)
[5/3/2019 1:02:23 AM] Job host started
```

**Comment by EricJizbaMSFT** [comment]
@JustinGrote we used to do that, but it doesn't work in all cases. See https://github.com/Microsoft/vscode-azurefunctions/issues/660 

Azurite specifically does not work as described in the above issue. If you're not seeing `Host lock lease acquired by instance ID` in a remote case, please file a separate issue with repro steps, project language, etc. and we can look into it.

**Comment by EricJizbaMSFT** [comment]
Seems like both messages (`Job host start` and `Host lock lease acquired`) are not ideal, so I filed an issue on the func cli: https://github.com/Azure/azure-functions-host/issues/4384

**Comment by JustinGrote** [comment]
I ended up just going back to Azure Storage Explorer due to a lot of issues
beyond that. Hopefully it gets working but for cross-plat development I
just point it to a "real" queue in my dev subscription for now as a
workaround.

**Comment by EricJizbaMSFT** [comment]
I tried the latest version of Azurite and this seems to be working now
