### ISSUE TITLE
Location prompt should filter based on support for Elastic Premium plans

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1249]
Repro steps:

1. Turn on advanced creation
2. Create a function app in West US 2

Expected:
The location prompt step only shows locations that support elastic premium

Actual:
The location prompts shows a bunch of locations and you get this error message:

Action: azureFunctions.deploy
Error type: Conflict
Error Message: The pricing tier 'ElasticPremium' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764

Version: 0.17.0
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.34.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.l.pipeline extension.bundle.js:262:3376627
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:606007
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
You probably already know, but there is this command `this._client.listSkus`.  I think `SkuInfos` might have the `capabilities` of the SKU.
