### ISSUE TITLE
can't edit or start azure function logging from visual studio code or portal

### ISSUE THREAD

**Issue by mahesh2000** [microsoft/vscode-azurefunctions#1256]
i can't edit function code or start azure function logging from visual studio code or the portal. same thing with storage (tables). yes, the storage account exists, i can access it and the tables within from the azure storage explorer desktop application. but not from the portal or visual studio code. the error below is from visual studio code:

Repro steps:1.2.Action: azureFunctions.startStreamingLogsError type: BadRequestError Message: Cannot resolve https://ls01storage.file.core.windows.net/. Please check if storage account exists.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.l.pipeline (dist/extension.bundle.js:277:1572169)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@mahesh2000 can you add repro steps describing how you got into this position? For example, how did you create the function app? How did you deploy? And what language is your project?

**Comment by mahesh2000** [comment]
hi, 

1. everything started working again after 30 minutes. must've been a system problem on your end. 

2. sometimes i have to log out and log in to azure portal several times (in the incognito window, because in the regular window it defaults to some other non-personal account with the same email address and even after i get it going with the right one, it will eventually go back to that; i don't want to keep clearing my cookies all the time) to get things to go right. 

3. the azure function editor (online) won't work properly after about 30-60 minutes, so i copy the entire code to a local notepad, click on something else in the browser (say Storage) at which point i'm asked to save my changes (they don't get changed, so there's no point) and then clicking on functions again to get everything in the function blade to work again. 

4. the log window will often disconnect.

5. there doesn't seem to be a way to edit existing functions in visual studio code, so if the portal isn't working, i'm stuck.

thanks!

mahesh

**Comment by EricJizbaMSFT** [comment]
@mahesh2000 you're correct - we don't support editing existing functions. If you want to edit functions, we suggest creating/editing the functions on your local machine and deploying from VS Code. You can follow the steps as outlined in this tutorial:
https://code.visualstudio.com/tutorials/functions-extension/getting-started
