### ISSUE TITLE
Error in Azure Function App Deployment

### ISSUE THREAD

**Issue by Dens2017** [microsoft/vscode-azurefunctions#1258]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message:  404 Web Site not found.
You may be seeing this error due to one of the reasons listed below :

 * Custom domain has not been configured inside Azure. See how to map an existing domain [https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-tutorial-custom-domain] to resolve this.
 * Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.

Checkout App Service Domain FAQ [https://blogs.msdn.microsoft.com/appserviceteam/2017/08/08/faq-app-service-domain-preview-and-custom-domains/] for more questions.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline extension.bundle.js:332:741129
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:606028
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Dens2017 can you add repro steps for this issue? Does it happen consistently? How did you create the function app and what language is your project?
