### ISSUE TITLE
Updating an existing app resulted in a "forbidden" error

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1261]
Repro steps:

1. Create an HTTP triggered function with auth level function key and deploy
2. Change auth level to anonymous instead and redeploy

Action: azureFunctions.deploy
Error type: Forbidden
Error Message: Forbidden

Version: 0.17.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Function.module.exports.j._normalizeError extension.bundle.js:332:65127
Object.module.exports.j._processResponse extension.bundle.js:332:60937
$.h [as _callback] extension.bundle.js:332:54789
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@asavaritayal this doesn't repro for me. Can you give more details:
1. I assume this is a Python project?
1. How did you create the function app? From VS Code or the portal?
1. Does this happen consistently for this function app?
