### ISSUE TITLE
Entry not found in cache

### ISSUE THREAD

**Issue by consultordeveloper1** [microsoft/vscode-azurefunctions#1264]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176642
extension.js:229:171257extension.js:229:171257
extension.js:229:43312extension.js:229:43312
extension.js:229:41305extension.js:229:41305
extension.js:229:40927extension.js:229:40927
i.module.exports.i.find extension.js:229:75420
module.exports.find.init.then extension.js:229:22917
i extension.js:1:101710
extension.js:1:102054extension.js:1:102054
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - this is being tracked upstream: https://github.com/microsoft/vscode-azure-account/issues/53

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)
