### ISSUE TITLE
Entry not found in cache

### ISSUE THREAD

**Issue by Agazoth** [microsoft/vscode-azurefunctions#1265]
Repro steps:
Working with the extension during a day, the error is encountered frequently. It is hard to trigger a refresh. Seems like refresh is satisfied by the incomplete cache

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176642
extension.js:229:171257extension.js:229:171257
extension.js:229:43364extension.js:229:43364
extension.js:229:42231extension.js:229:42231
B.module.exports.e.exports.createRequestHandler [as _callback] extension.js:1:182121
B.module.exports.B.init.t._callback.t.callback.t.callback extension.js:181:5498
B.emit events.js:182:13
B.<anonymous> extension.js:181:18326
B.emit events.js:182:13
IncomingMessage.<anonymous> extension.js:181:17168
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
