### ISSUE TITLE
Randomly getting this error when running a funciton

### ISSUE THREAD

**Issue by gerardoboss** [microsoft/vscode-azurefunctions#1267]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.17.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:87999
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@gerardoboss can you add repro steps to this issue?

**Comment by hariharan618** [comment]
I'm facing this as well.

- Created a Http Triggered azure function from vscode
- I try to debug it using F5 key
- dotnet build succeeds , func host starts but the breakpoint never gets hit

After sometime i can see a popup from vscode
![image](https://user-images.githubusercontent.com/20477956/58081001-e1e87500-7bd1-11e9-9dc2-312d30312572.png)


Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.e extension.bundle.js:390:88446
u.fire extensionHostProcess.js:47:720
D.<anonymous> extensionHostProcess.js:629:772
s extensionHostProcess.js:13:221
```

**Comment by EricJizbaMSFT** [comment]
@hariharan618 Does it work if you restart VS Code? Even if this is the case - I'd love to hear more about how you got those dialogs to appear because we're having a hard time repro-ing. For example you're saying the build succeeded even though the error message says "Task "build" failed with exit code "1""? Can you copy the logs of the build task? Also - did you try to F5 multiple times?
