### ISSUE TITLE
Unable to run Iothubtrigger function locally in VS code

### ISSUE THREAD

**Issue by iotrock** [microsoft/vscode-azurefunctions#1268]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:87999
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@iotrock can you add repro steps to this issue?
