### ISSUE TITLE
Error when reading the functions treeItem 

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azurefunctions#1271]
I'm already signed in, but there seems to be an auth issue when trying to access the URL of a function within a recently deployed function app. 

<img width="427" alt="Screen Shot 2019-05-10 at 3 31 50 PM" src="https://user-images.githubusercontent.com/30420973/57559969-1d18b780-7339-11e9-9ca0-ac0acd5575bf.png">

Action: azureFunctions.deploy
Error type: 500
Error Message:  Server Error in '/' Application.

 The user name or password is incorrect.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code...

Version: 0.17.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

**Comment by EricJizbaMSFT** [comment]
I've never seen this before - let me know how you created the function app, what type of project langauge this was, and if it continues to repro even on new function apps.

I suppose you could also just share that function app with me
