### ISSUE TITLE
Not seeing the Azure Functions v2 selection option when creating a new Azure function

### ISSUE THREAD

**Issue by westerdaled** [microsoft/vscode-azurefunctions#1272]
Hi

I am testing out the extension by following this tutorial [Create your first PowerShell function with Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell) . However, I have run into  a few issues despite installing all the prereqs

I am simply not seeing this option tho I can happily create by azure function starter project.

> Select Powershell (preview) as the language for your function app project and then Azure Functions v2

On the subject of PowerShell preview ( in my case v6.2) do we need to also edit the shell settings in our VSCode user settings ?
`%APPDATA%\Code\User\settings.json`

**Comment by EricJizbaMSFT** [comment]
@westerdaled what version of the functions extension do you have installed? And what version of VS Code? The PowerShell support was added in v0.17.0 of the functions extension, which relies on at least v1.31.0 of VS Code

**Comment by westerdaled** [comment]
Hi @EricJizbaMSFT ,

I have both AZ Function extension 0.17.0 and VSCode : 1.33.1 (system setup) installed. I am also running PowerShell preview 2.02.

**Comment by EricJizbaMSFT** [comment]
So what do you see when you hit this button?
![Screen Shot 2019-05-13 at 3 39 18 PM](https://user-images.githubusercontent.com/11282622/57658926-636a5280-7595-11e9-8a0e-386b9fe45986.png)

This is what I see:
![Screen Shot 2019-05-13 at 3 40 24 PM](https://user-images.githubusercontent.com/11282622/57658944-71b86e80-7595-11e9-9a24-1d64eee46e21.png)

Also - do you have "azureFunctions.projectLanguage" set in your VS Code user settings? If so - it will use that language automatically.

**Comment by westerdaled** [comment]
Hi

I am using my client's Azure subscription:
![AzureFunction new project](https://user-images.githubusercontent.com/937208/57685495-e9d37280-762f-11e9-97b4-62c1f5f16235.jpg)

However, I don't see your language options menu 

![Azure function settings](https://user-images.githubusercontent.com/937208/57686201-13d96480-7631-11e9-9050-7da5ad33cae2.jpg)

I wonder if the PowerShell version needs to added to user settings (  I have't added these yet) e.g. 

`
  "shellLauncher.shells.windows": [{
        "shell": "c:\\Program Files\\PowerShell\\6-preview\\pwsh.exe",
        "label": "PowerShell Core"
    },
    {
        "shell": "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe",
        "label": "Windows PowerShell"
    }
],

`

**Comment by EricJizbaMSFT** [comment]
We don't check powershell version or shell. The only setting that affect this is the above setting. You can do "Reset Setting" to clear the value
![Screen Shot 2019-05-14 at 9 40 41 AM](https://user-images.githubusercontent.com/11282622/57715852-7f6d0300-762c-11e9-9790-18e7a599e043.png)

Also to be clear - the prompt for language is after your first screenshot. You have to select the folder first.

**Comment by westerdaled** [comment]
Hi 

 it appears that I do have the Azure Functions V2 set in the project runtime settings

![Azure Functions project runtime](https://user-images.githubusercontent.com/937208/57784131-4b2a3d00-7727-11e9-8216-d658200980ac.jpg)

Oddly I am now seeing the option at create function time  
![Azure functions select runtime](https://user-images.githubusercontent.com/937208/57784579-08b53000-7728-11e9-9ecc-6391f8e9154e.PNG)

This could be one of those user error situations 😵

**Comment by EricJizbaMSFT** [comment]
> Oddly I am now seeing the option at create function time

And this is a PowerShell project? We should only prompt for runtime if the following are true:
1. It's a language that supports both v1 and v2 (like JavaScript or C#)
1. We can't detect the version of the func cli installed on your local machine

**Comment by westerdaled** [comment]
Hi

Yes this is is a PowerShell project.  Prior to the above,  I was able to create 2 test AZ Function and never saw the version prompt.  For the first of these, I had a incorrect login to azure as in an account without any subscriptions, so this may have been a factor

Also, he extension detected I was missing a prereq when I came to to perform a test run.: 
> Running command: "npm install -g azure-functions-core-tools@2"...

**Comment by EricJizbaMSFT** [comment]
Okay so is there anything left blocking you here? Or can we close this issue?
