### ISSUE TITLE
Keep expanding the applied subscription about 1-2 mins 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1274]
**OS**: Windows
**Build Version**: [20190513.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5942)

**Repro Steps:**
1. Install the Azure Function extension --> Make sure there is 1 applied subscription at least.
2. Try to expand the applied subscription.

**Expect:**
Expand it immediately.

**Actual:**
Keep expanding the applied subscription about 1-2 mins. Meanwhile there are not many azure function apps under the subscription.

**Comment by EricJizbaMSFT** [comment]
Does this consistently repro? There could always be internet or Azure issues

**Comment by v-dantch** [comment]
This issue consistently reproduces on 3 test machines on our side in this week. And I cannot make sure whether it is an internet issue or not. Due to we are not allowed to install VS Code on our local machine.

**Comment by EricJizbaMSFT** [comment]
Hmm - can you try either the portal or Cloud Explorer and see if they're just as slow at displaying function apps on that VM?

**Comment by v-dantch** [comment]
Tried to expand the applied subscription with below:

More | State
-- | --
Cloud Explorer | Not repro
Storage Explorer | Not repro
Portal | Not repro
App Service   Extension | Not repro
Azure Storage   Extension | Not repro
Cosmos DB   Extension | Not repro
Docker Extension | Not repro
Azure Function   Extension | Repro



Does this issue reproduce for you?

**Comment by EricJizbaMSFT** [comment]
No it doesn't repro for me. Can you either do a screen recording or give me access to the machine?

**Comment by v-dantch** [comment]
Ok, the machine info has sent to you.

**Comment by EricJizbaMSFT** [comment]
Okay I think I know what's going on here - will investigate a fix

**Comment by v-dantch** [comment]
👍So cool! 🤔Could you help to share any info about this issue?
