### ISSUE TITLE
error when deploying python azure python function which has pyodbc library

### ISSUE THREAD

**Issue by ruwansriw** [microsoft/vscode-azurefunctions#1275]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to find preDeploy task "func: pack". Modify the setting "azureFunctions.preDeployTask" or add that task to tasks.json.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:80704
o extension.bundle.js:390:79113
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ruwansriw please add repro steps for this issue

**Comment by ruwansriw** [comment]
I did a python azure htttp-trigger function to connect to the azure-sql-database and execute a update query. It works when i ran it locally. When I'm trying to deploy that function, I'm getting this error. I have done some other python azure functions and it deployed perfectly. 
I think the problem is with the pyodbc library. When i add it to requirements.txt and try to deploy I'm getting following error.
"There was an error restoring dependencies.ERROR: cannot install pyodbc-4.0.26 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish
"

**Comment by EricJizbaMSFT** [comment]
@ruwansriw what version of the func cli do you have installed? You have to add the `--build-native-deps` flag if you want to deploy with `pyodbc` and our extension should prompt you to do that.

You can also do it manually. I believe you just need to change the setting `azureFunctions.preDeployTask` from `func: pack` to `func: pack --build-native-deps`
