### ISSUE TITLE
"Create new project" with Java function uses old Maven archetype

### ISSUE THREAD

**Issue by jwalter** [microsoft/vscode-azurefunctions#1280]
When I create a new Java functions project, the extension uses version 1.0 of the azure-functions-archetype:

```
[INFO] --- maven-archetype-plugin:3.1.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype [com.microsoft.azure:azure-functions-archetype:1.0] found in catalog remote
```

**Comment by EricJizbaMSFT** [comment]
@jwalter I see this:
```
[INFO] Archetype [com.microsoft.azure:azure-functions-archetype:1.22] found in catalog remote
```

A few questions:
1. What version of maven do you have installed?
1. What version of the VS Code extension do you have?
1. What OS?

**Comment by jwalter** [comment]
1. 3.5.2
2. v0.17.0
3. Mac OS

**Comment by EricJizbaMSFT** [comment]
That all looks the same as me. In the "Azure Functions" log, you should see something like this:
```
Running command: "mvn archetype:generate -DarchetypeGroupId='com.microsoft.azure' -DarchetypeArtifactId='azure-functions-archetype' -DgroupId='com.function' -DartifactId='ja9' -Dversion='1.0-SNAPSHOT' -Dpackage='com.function' -DappName='ja9-1558392757140' -B"...
```

All we're doing is running that command and the rest of the output is coming directly from maven. It looks like we're not passing any archetype version, so I'm not sure what to do here. Is it possible your machine was using a cached version for some reason (no internet/bad internet)? You could try running that command manually and see if you get the same output...

**Comment by jwalter** [comment]
After investigating further it seems this was caused by our local Maven mirror. Ideally the plugin would provide some guidance in a situation like this but on the other hand it may be rare enough that it's not worth the effort.

**Comment by EricJizbaMSFT** [comment]
Sounds like you figured it out, so I'll go ahead and close this.

In terms of "Ideally the plugin would provide some guidance", I'm not very familiar with the plugin itself. If you think the experience can be improved, I recommend filing an issue directly on their repo: https://github.com/microsoft/azure-maven-plugins
