### ISSUE TITLE
Error not found in cache

### ISSUE THREAD

**Issue by jeanpoelie** [microsoft/vscode-azurefunctions#1281]
Repro steps:

1. have a azure function online based on payment
2. use it for a couple days

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457extension.js:229:171457
extension.js:229:43512extension.js:229:43512
extension.js:229:41505extension.js:229:41505
extension.js:229:41127extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
