### ISSUE TITLE
Prompt to select the function app twice when executing "Azure Functions: Restart"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1284]
**OS**: Windows
**Build Version**: [20190516.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6054)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -->Type and select "Azure Functions: Restart".
2. Check the result.

**Expect:**
Complete the "Stop--> Start" at once and there is no the second request.

**Actual:**
Prompt to select one function app to stop --> After that, prompt to select the function app again to start. 
In this case, we can select another function app at the second. 
![image](https://user-images.githubusercontent.com/34729092/57910522-6043c080-783a-11e9-8a57-d05a6f7a22e4.png)

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-azurefunctions/pull/1320
