### ISSUE TITLE
Not allowed to create a local storage

### ISSUE THREAD

**Issue by jhoenscheid** [microsoft/vscode-azurefunctions#1285]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: RequestDisallowedByPolicy
Error Message: Resource 'vatvalidator' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Enforce tagging of resources: department","id":"/subscriptions/0f952bb2-a760-453a-a199-4c86bc382e71/providers/Microsoft.Authorization/policyAssignments/01dcd3c3aa914db3959b6247"},"policyDefinition":{"name":"Require specified tag","id":"/providers/Microsoft.Authorization/policyDefinitions/871b6d14-10aa-478d-b590-94f262ecfa99"}}]'.

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@jhoenscheid can you add repro steps to this issue?

Also - you might want to try the latest extension (v0.17.0). It requires version 1.31.0 of VS Code
