### ISSUE TITLE
Could you help me ?

### ISSUE THREAD

**Issue by bgbeppe** [microsoft/vscode-azurefunctions#1287]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\gborasio\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.17.0\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\gborasio\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\gborasio\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~2.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name "ProductsApi" --arg:AzureFunctionsVersion v2" failed with exit code "4294967295":
ERROR: Failed to find template with identity "Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x".

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134101
o extension.bundle.js:1:133039
```

</details>

**Comment by EricJizbaMSFT** [comment]
@bgbeppe does this consistently happen for you? Or does it work if you restart VS Code? Can you check the following path to see if it exists?
```
c:\Users\gborasio\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\
```
