### ISSUE TITLE
Subfolders of a symbolically linked folder are not included when deploying

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1289]
Repro steps:
1. Create a function project
1. Add a symbolic link to a directory with subfolders
1. Deploy

Expected:
Linked directory _and_ sub folders are deployed

Actual:
Only top level files of linked directory are deployed

**Comment by EricJizbaMSFT** [comment]
Moved over from https://github.com/microsoft/vscode-azurefunctions/issues/1115#issuecomment-492493351 by @kobyl

**Comment by armanio123** [comment]
I'm experiencing the same issue. Is there a work around for this problem?

**Comment by EricJizbaMSFT** [comment]
Only workaround at the moment is to manually copy the folders before deploying instead of using a sym link.

**Comment by EricJizbaMSFT** [comment]
FYI - @kobyl @armanio123 we just released v0.19.0 of the extension which includes a fix for this
