### ISSUE TITLE
Default tasks.json does not work with nested folder structure

### ISSUE THREAD

**Issue by ahmedelnably** [microsoft/vscode-azurefunctions#1290]
Original issue https://github.com/Azure/azure-functions-core-tools/issues/1325

I have a function that sits somewhere under a src subfolder. The default tasks.json creates me the following task to start the function:

    {
      "type": "func",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/src/FuncClaims.Api/bin/Debug/netstandard2.0"
      },
      "command": "host start",
      "isBackground": true,
      "problemMatcher": "$func-watch"
    }
When attempting to build it, I get the following reported back:

Error: The func task detection didn't contribute a task for the following configuration:
{
    "type": "func",
    "dependsOn": "build",
    "options": {
        "cwd": "${workspaceFolder}/src/FuncClaims.Api/bin/Debug/netstandard2.0"
    },
    "command": "host start",
    "isBackground": true,
    "problemMatcher": "$func-watch"
}
The task will be ignored.
I found a older version of the task, and this does seem to work OK:

    {
      "label": "runFunctionsHost",
      "type": "shell",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/src/FuncClaims.Api/bin/Debug/netstandard2.0"
      },
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$func-watch"
    }

**Comment by RadekTester** [comment]
So what's the current workaround for this?

**Comment by EricJizbaMSFT** [comment]
@RadekTester the current workaround is to use the older version of the task mentioned above instead of the default task in the template

**Comment by EricJizbaMSFT** [comment]
Actually you can use the existing task if you set the VS Code setting `azureFunctions.projectSubpath`
