### ISSUE TITLE
Unable to debug azure function locally in vs code

### ISSUE THREAD

**Issue by iotrock** [microsoft/vscode-azurefunctions#1294]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:390:88911extension.bundle.js:390:88911
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@iotrock please add repro steps to this issue

**Comment by iotrock** [comment]
Environment:
OS : Windows 10 version 1803
Editor: Visual studio Code

Steps followed to develop azure function locally in VS Code
1 Installed azure function tool to run  npm install -g azure-functions-core-tools command in VS code terminal.
2  Installed the Azure Functions extension for Visual Studio Code 
3 Create an Azure Functions project
4 Create a function which is IoThubtrigger
5 When pressed F5 to run function project locally, windows popped up show message to install azure function tool to run function locally, during azure function tool installation got error message "Error: Functions host is no longer running"

**Comment by iotrock** [comment]
EricJizbaMSFT **Any update on this issue**

**Comment by EricJizbaMSFT** [comment]
Can you elaborate on step 5? Were you able to successfully install the func cli? If you run `func --version`, what do you see?

**Comment by iotrock** [comment]
> When run func --version 

shows below result in terminal of the vs code
PS C:\Users\iotrock> func --version
func : The term 'func' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ func --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (func:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


>

**Comment by EricJizbaMSFT** [comment]
Okay so you have to install the func cli and make sure it's on your PATH.

Try running this command to install the func cli and let me know if it doesn't work:
```
npm i -g azure-functions-core-tools
```

Here are the full instructions on how to install the func cli: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools

**Comment by iotrock** [comment]
Thanks for your response

Run the npm i -g azure-functions-core-tools in terminal of vs code
 
Got below error message
PS C:\Users\iotrock> npm install -g azure-functions-core-tools@2
C:\Users\iotrock\AppData\Roaming\npm\func -> C:\Users\iotrock\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\iotrock\AppData\Roaming\npm\azfun -> C:\Users\iotrock\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\iotrock\AppData\Roaming\npm\azurefunctions -> C:\Users\iotrock\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.7.1158 postinstall C:\Users\iotrock\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1158/Azure.Functions.Cli.win-x64.2.7.1158.zip"
[==================] Downloading Azure Functions Core Tools
+ azure-functions-core-tools@2.7.1158
updated 1 package in 38.907s


PS C:\Users\iotrock> func --version
func : The term 'func' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ func --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (func:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\iotrock>


![FunctionIssue](https://user-images.githubusercontent.com/49762230/58346639-306b6d00-7e79-11e9-8a09-5b70a517c4fe.jpg)

**Comment by EricJizbaMSFT** [comment]
Okay it looks like it installed successfully, but `func` is not on your path. Maybe take a look at these:

https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

**Comment by iotrock** [comment]
> Okay it looks like it installed successfully, but `func` is not on your path. Maybe take a look at these:
> 
> https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows
> 
> https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

Yeyeeee!!! Thanks EricJizbaMSFT

**Comment by EricJizbaMSFT** [comment]
Glad that worked for you!
