### ISSUE TITLE
BadRequest on Azure Functions Deploy

### ISSUE THREAD

**Issue by shietpas** [microsoft/vscode-azurefunctions#1297]
Repro steps:

1. Create Python function app
2. Create new Ptyhon function for HttpTrigger (based on template)
3. Attempt to deploy

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: BadRequest

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.module.exports.j._normalizeError extension.bundle.js:332:65127
Object.module.exports.j._processResponse extension.bundle.js:332:60937
$.h [as _callback] extension.bundle.js:332:54789
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```
Python 3.6.8
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0

</details>

**Comment by EricJizbaMSFT** [comment]
@shietpas can you add more details to this issue? For example:
1. Does this consistently happen or does it work the next time you deploy?
1. How did you create the function app in Azure? From VS Code or the portal?
1. Can you copy the deployment logs?

**Comment by shietpas** [comment]
@EricJizbaMSFT I ended up uninstalled the 32-bit version and installed 64-bit instead.
