### ISSUE TITLE
Entry not found in cache

### ISSUE THREAD

**Issue by Agazoth** [microsoft/vscode-azurefunctions#1300]
Repro steps:

1. Deploy Azure Functions for a few hours
![image](https://user-images.githubusercontent.com/15127301/58228751-fe022880-7d2f-11e9-926f-b539444ca16a.png)

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457extension.js:229:171457
extension.js:229:43564extension.js:229:43564
extension.js:229:42431extension.js:229:42431
B.module.exports.e.exports.createRequestHandler [as _callback] extension.js:1:182121
B.module.exports.B.init.t._callback.t.callback.t.callback extension.js:181:5498
B.emit events.js:182:13
B.<anonymous> extension.js:181:18326
B.emit events.js:182:13
IncomingMessage.<anonymous> extension.js:181:17168
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
