### ISSUE TITLE
Docker is required to build native dependencies for python function apps

### ISSUE THREAD

**Issue by anindya5** [microsoft/vscode-azurefunctions#1303]
HI,

I am trying to deploy a function that works fine when debugging via VS Code.

Once I deploy, the function get created as well.

When I click output, I get these:-

`Executing task: . .env/bin/activate && func pack --build-native-deps <

source /Users/adey1/Documents/GitHub/HTM_integration/AzureFunctionBatch/.env/bin/activate
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 23.44 ms for /Users/adey1/Documents/GitHub/HTM_integration/AzureFunctionBatch/extensions.csproj.
  extensions -> /Users/adey1/Documents/GitHub/HTM_integration/AzureFunctionBatch/bin/extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.56

Deleting the old .python_packages directory
Docker is required to build native dependencies for python function apps
The terminal process terminated with exit code: 1
`

and the deployment halts.

**Comment by EricJizbaMSFT** [comment]
@anindya5 I recommend taking a look at the docs here:

https://docs.microsoft.com/azure/azure-functions/functions-reference-python#publishing-to-azure

If you're using a package that requires a compiler and does not support the installation of manylinux-compatible wheels from PyPI, you have to have docker on your machine to bundle those packages before deploying.

**Comment by anindya5** [comment]
I am not able to do it, using standard packages also. Even when I am removing all requirements, I am still getting this error

**Comment by anindya5** [comment]
If I choose to deploy anyway, I get the issue listed below

https://github.com/microsoft/vscode-azurefunctions/issues/1301

**Comment by EricJizbaMSFT** [comment]
You can change `azureFunctions.preDeployTask` in `.vscode/settings.json` to just `func: pack` instead of `func: pack --build-native-deps`
