### ISSUE TITLE
Failed to deploy path that does not exist: 

### ISSUE THREAD

**Issue by ricafort** [microsoft/vscode-azurefunctions#1306]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\francis.ricafort\repos\AzureFunctions\bin\Release\netcoreapp2.1\publish

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ricafort can you add repro steps? Did the "publish" task succeed or did you select "Deploy Anyway"?
