### ISSUE TITLE
The terminal name becomes odd for Python project

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1307]
**OS**: Windows
**Build Version:** [20190523.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6283)

**Repro Steps:**
1. Create a Python project.
2. Debug.
3. Make some changes --> Save the _init_.py file --> click the "Terminal" window.
4. Check the Terminal window.

**Expect:**
The terminal name displays well.

**Actual:**
The terminal name becomes odd.
![image](https://user-images.githubusercontent.com/34729092/58318031-98a25a80-7e49-11e9-8139-25d26d2c9f52.png)

**Comment by EricJizbaMSFT** [comment]
This extension does not control the terminal. That would either be a VS Code bug or small chance a bug in the Python extension.

**Comment by v-dantch** [comment]
Got you.
