### ISSUE TITLE
It is inconsistent for the default function name between Windows/Linux and Mac

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1308]
**OS**: Windows/Linux
**Build Version:** [20190523.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6283)

**Repro Steps:**
Create a non-C# project and check the default function name in the process.

**Expect:**
It is consistent for the default function name between Windows/Linux and Mac.

**Actual:**
It is inconsistent for the default function name between Windows/Linux and Mac.
![image](https://user-images.githubusercontent.com/34729092/58318405-431a7d80-7e4a-11e9-8227-a5d3ecfc34ea.png)

**Comment by EricJizbaMSFT** [comment]
I see "HttpTrigger" on a mac. Can you check these settings in both workspace and global settings?

"azureFunctions.templateVersion"
"azureFunctions.projectRuntime"

Also - can you check the "Azure Functions" output window after you create the function? We normally get the templates from online, but we also ship a backup version of the templates with the extension. The output window should show errors or something if we're using the backup templates.

**Comment by v-dantch** [comment]
Hi Eric, verified this issue on MacBook, please get more info from below:

Item | Version /Result | Version /Result | Version /Result
-- | -- | -- | --
azureFunctions.templateVersion | 2.8.1 | 2.8.1 | 2.8.1
azureFunctions.projectRuntime | ~1 | ~2 | beta
Output window after   creating the function | No error | No error | No error
  | Repro | Repro | Repro


But it makes me very confused 😕. We verified this issue on Mac mini and MacBook with same build:

Platform | Result
-- | --
Mac Mini | Not repro
MacBook | Repro

Does it make sense to change the default function name as _**_function template+language_**_ 😃?

**Comment by EricJizbaMSFT** [comment]
> Does it make sense to change the default function name as function template+language 

I think "HttpTrigger" is a better default than "HttpTriggerPython". Most people only use one language and so that information is unnecessary.

Can you try removing the "azureFunctions.templateVersion" setting? Like I mentioned, we get these templates dynamically and I'm guessing that mac is just stuck on v2.8.1 of the templates. Most people leave that setting blank and get the latest templates.

**Comment by v-dantch** [comment]
Got you.

And, yeah, it displays well after removing the "azureFunctions.templateVersion" setting.
