### ISSUE TITLE
Keep connecting to log stream for Linux Function apps with App Service Plan 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1309]
**OS**: All
**Build Version:** [20190523.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6283)

**Repro Steps:**
1. Select "Start Streaming Logs" from a Linux function app tree menu.
2. Check the result.

**Expect:**
Succeed to start and list the streaming logs.

**Actual:**
Keep connecting to log stream...

**Comment by EricJizbaMSFT** [comment]
Is this a consumption plan or dedicated plan? EIther way, closing as duplicate:
- Consumption: https://github.com/microsoft/vscode-azurefunctions/issues/589
- Dedicated: https://github.com/microsoft/vscode-azurefunctions/issues/1199
