### ISSUE TITLE
Feature Request: Azure Functions Debug - Split Terminal Option

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#1311]
_originally filed by @JustinGrote in https://github.com/PowerShell/vscode-powershell/issues/1941_

**Summary of the new feature**

When debugging with Azure Functions Powershell, you have to toggle back and forth on the terminal window between the Azure Function Host task window and the integrated terminal.

**Proposed technical implementation details**

VSCode has API calls for splitting the terminal. If an option is set (e.g. powershell.SplitTerminalOnAzureFunctionDebug), then it should split the function host start and the integrated console so the result looks like below:

![image](https://user-images.githubusercontent.com/15258962/57101559-5c5e5d00-6cd6-11e9-9147-9aff712dea8e.png)

**Comment by EricJizbaMSFT** [comment]
More conversation here: https://github.com/PowerShell/vscode-powershell/issues/1941

Not gonna copy every single comment
