### ISSUE TITLE
I am trying to play with Azure functions using VS code. I am not an Azure expert but for some reason the function does not get deployed.

### ISSUE THREAD

**Issue by AnugitNL** [microsoft/vscode-azurefunctions#1312]
Repro steps:

1. Create a function using VS code 
2. Try to Deploy the function

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to find preDeploy task "func: pack". Modify the setting "azureFunctions.preDeployTask" or add that task to tasks.json.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:80704
o extension.bundle.js:390:79113
```

</details>

**Comment by EricJizbaMSFT** [comment]
@AnugitNL can you send me a screenshot of your workspace? I'm wondering if you have an unexpected folder structure. If the function project isn't set up how we expect it, we might not be providing the "func: pack" task

**Comment by EricJizbaMSFT** [comment]
Also this is related to https://github.com/microsoft/vscode-azurefunctions/issues/1290 - which we plan to fix by improving the task detection.
