### ISSUE TITLE
Unable to locally debug Azure Functions

### ISSUE THREAD

**Issue by robwhitehouse** [microsoft/vscode-azurefunctions#1313]
Repro steps:

1. Create a new Azure Functions App
2. Attempt to debug using "Attach to .NET Functions"

Contents of local.settings.json:

```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet"
    }
}
```

Have tried modifying file with different encoding/formats (MacOS/DOS etc) with no luck.

Function runs and correctly reads the local.settings.json file when using `func start` from cli.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:319974
o extension.bundle.js:1:319384
```

</details>

**Comment by EricJizbaMSFT** [comment]
@robwhitehouse it's possible the task is running in the wrong folder - is that the only local.settings.json file you have? Could you share a screenshot of your workspace so that I can get an idea of the folder structure?

**Comment by robwhitehouse** [comment]
That is exactly the problem - thanks! I have multiple projects in my workspace; opening the project folder directly in a standalone Code window reads the json file perfectly. I can work around it for now with multiple windows, unless there's a way to set the root launch/build folder (couldn't see anything in Intellisense that would work)?

**Comment by EricJizbaMSFT** [comment]
@robwhitehouse take a look at this wiki page and let me know if it's any help:
https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

If you have any issues let me know your desired folder structure for multiple projects and we might be able to improve the experience.

**Comment by robwhitehouse** [comment]
Sorry I missed that wiki page - it perfectly resolves my issue, should have looked a little harder before posting. Thanks for all your help!
