### ISSUE TITLE
Syncing trigger failed to deploy python (cli)

### ISSUE THREAD

**Issue by baby-girl** [microsoft/vscode-azurefunctions#1315]
Hi,

I'm trying to deploy my function app (func azure functionapp publish <app_function>) but it's not working. 
I have : 
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Response status code does not indicate success: 408 (Request Timeout).

Few days ago it was working but since yesterday nothing.

Does anyone could help me ?
Thanks

**Comment by TomasKunka** [comment]
Today I got the same error. I suspect the fault is on azure side.

**Comment by EricJizbaMSFT** [comment]
Can either of you confirm if this is still reproducing? If so - what language are you deploying and to what region? As @TomasKunka mentioned, I'm guessing it was a problem on the Azure side, in which case we couldn't do anything here

**Comment by TomasKunka** [comment]
seems fine by now. but I experience this outages from time to time.

**Comment by EricJizbaMSFT** [comment]
If you get a consistent repro - let us know and we can investigate. Otherwise I'll close this as external (aka a bug in Azure)
