### ISSUE TITLE
when i deploy the function,it says Encountered an error (Forbidden) from extensions API.

### ISSUE THREAD

**Issue by heiway** [microsoft/vscode-azurefunctions#1316]
Repro steps:

1.Click "Deploy to Function App..." 

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: Encountered an error (Forbidden) from extensions API.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@heiway can you give more info?
1. What project language are you using?
1. Does this happen consistently?
1. Is this a new function app or existing one?

**Comment by heiway** [comment]
> @heiway can you give more info?
> 
> 1. What project language are you using?
> 2. Does this happen consistently?
> 3. Is this a new function app or existing one?

I create a new project and copy the function in, and the error disappeared.
thanks.
