### ISSUE TITLE
Make advancedCreation more discoverable

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1317]
Ideas discussed so far:
1. Add a separate command like "Create Function App in Azure (Advanced)..."
    - If we do this, we should consider removing the existing setting. It feels weird to me if one entry point is controlled by the setting and the other is not.
1. Add a settings button in the create wizard that turns on advanced creation
    - This still might not be that discoverable

Related to https://github.com/microsoft/vscode-azurefunctions/issues/1194

**Comment by fiveisprime** [comment]
I like the idea of a separate "Create project (advanced)" and maybe we could expose the advanced creation command as part of the first prompt in the create project flow. Something like this?

![image](https://user-images.githubusercontent.com/1186948/61325889-86e68f00-a7ca-11e9-85a6-32720dbd2dfe.png)

**Comment by EricJizbaMSFT** [comment]
@fiveisprime this issue is for creating a function app in Azure, but the dialog you mentioned is for creating a new project.
