### ISSUE TITLE
123

### ISSUE THREAD

**Issue by locedubo** [microsoft/vscode-azurefunctions#1318]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: d:\SVN\ningbo\iot\iotFunction\target\azure-functions\tadopTest1-1559181527158\

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
i extension.js:1:101710
extension.js:1:102054extension.js:1:102054
```

</details>

**Comment by EricJizbaMSFT** [comment]
@locedubo can you add repro steps to this issue?
