### ISSUE TITLE
[Python] Log streaming for Python - Open Browser 

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1323]
See context - https://github.com/Azure/azure-functions-core-tools/issues/1334

On deployment, if a user clicks on "start stream", launch the Live Metrics Stream view in the browser.

**Comment by EricJizbaMSFT** [comment]
@asavaritayal this is the second time you've created this bug 😂 https://github.com/microsoft/vscode-azurefunctions/issues/1292

This is already being tracked here: https://github.com/microsoft/vscode-azurefunctions/issues/589

**Comment by asavaritayal** [comment]
I'm sorry, you know I really want this feature for GA :)
