### ISSUE TITLE
Local Azure function apps via Visual Studio Code Failed to deploy path that does not exist

### ISSUE THREAD

**Issue by SophySym** [microsoft/vscode-azurefunctions#1329]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: h:\Localhost\ManualPushNotification

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
@SophySym could you add repro steps?
