### ISSUE TITLE
VS Code Azure Functions extension for Python still has a Dotnet dependency

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1334]
Azure Functions extension 0.17.1 (Windows) fails with a dotnet dependency error:

![pythondotnet](https://user-images.githubusercontent.com/4258913/59138343-67458680-8941-11e9-8fdb-f136cb97ac2e.png)

**Comment by EricJizbaMSFT** [comment]
@gbowerman what version of the func cli do you have? If you're on the latest and create a new project - it shouldn't need dotnet.

**Comment by gbowerman** [comment]
@EricJizbaMSFT 
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0

**Comment by gbowerman** [comment]
However, I think this was being called from the VS Tools Azure Functions extension 0.17.1
