### ISSUE TITLE
Make pre-deploy task error dialog more similar to debug error dialog

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1335]
This is during the standard function deployment flow with Azure Functions extension 0.17.1 on Windows. 
As well as fixing the error, this type of message needs to be more understandable.

![funcpack](https://user-images.githubusercontent.com/4258913/59138501-58130880-8942-11e9-8b86-f983a4b0d5fa.png)

**Comment by EricJizbaMSFT** [comment]
Looks like the "func: pack" task failed due to https://github.com/microsoft/vscode-azurefunctions/issues/1334

What are you suggesting we do differently here?

**Comment by gbowerman** [comment]
@EricJizbaMSFT  my suggestion is to surface an actionable error to the user. The above error doesn't tell me what happened or what I should do about it in terms that I can understand. It's more of an operational error for a component that means something to an internal developer.

**Comment by EricJizbaMSFT** [comment]
@gbowerman this is modeled after the standard "Debug Anyway" dialog that comes from VS Code:
![Screen Shot 2019-07-17 at 10 15 51 AM](https://user-images.githubusercontent.com/11282622/61396147-ec468880-a87b-11e9-8a40-2715cd7b0ec2.png)

I might be able to add add something like the "Show errors" button which takes you to the task output.
