### ISSUE TITLE
VS Azure Azure Functions extension Python wizard creates a requirements.txt file with unnecesary libraries

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1337]
VS Code Azure Functions extension 0.17.1 on Windows creates a requirements file with import libraries that are no longer necessary like grpcio-tools, protobuf​, six

**Comment by EricJizbaMSFT** [comment]
@gbowerman what version of the func cli do you have? We only add those libraries if we detect an older version of the func cli that still needed them.

**Comment by gbowerman** [comment]
@EricJizbaMSFT  do I need both the VS Code Azure Functions extension and the Func CLI?
Either way, if it included the extra files in requirements.txt because of the func version, and then it failed because of the extra files, then something is broken isn't it?
![image](https://user-images.githubusercontent.com/4258913/61012181-3686b180-a332-11e9-8e7a-787fc89da428.png)

**Comment by EricJizbaMSFT** [comment]
Yes you need both the func cli and the VS Code extension. I don't understand what you mean by "it failed because of the extra files" because I don't see any error in the issue description

In addition, if I create a python project with func cli version `2.7.1373` I see an empty `requirements.txt`
