### ISSUE TITLE
Cannot Deploy or Debug on Windows DSVM

### ISSUE THREAD

**Issue by grecoe** [microsoft/vscode-azurefunctions#1338]
Repro steps:

1. Create function app in Azure Portal
     Linux
     Python
2. Read instructions about npm and such, all good.
3. Install core tools.
4. Launch VS code
      See in VS Code I need to install functions (thought I just did)
      Finally see functions in Azure panel.
5. Try to create something in the function app, but I didn't capture the error. Eventually create something local. 
6. Try to debug but it keeps telling me 
       Core tools not installed and options are .NET standard or framework, pick standard.
       Launch fails with connection refused.
7. Give up debugging, go to deploy. First time, makes me create a function....so I create another standard HTTP Trigger.
8. Deploy again, again tells me core tools not installed just like in 6, again pick standard. 
9. Deploy fails. 

NOTE: Is this related to the fact that I'm using a Win DSVM to do this work and not a Linux DSVM? I can try on one of those, just thought I'd capture this here.  

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Chevron\PythonFunctionApp\PythonFunctionApp.zip

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.31.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
> See in VS Code I need to install functions (thought I just did)

Is the func cli on your path? It's possible it installed, but we can't detect it. Try running `func --version` from a command prompt
