### ISSUE TITLE
Wie üblich!

### ISSUE THREAD

**Issue by AndreasKarz** [microsoft/vscode-azurefunctions#1339]
Nimm eine Anleitung von Microsoft, gehe Schritt für Schritt durch und sei Dir eins sicher:

ES WIRD NICHT FUNKTIONIEREN!!!

Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.e extension.bundle.js:390:88446
u.fire extensionHostProcess.js:47:720
k.<anonymous> extensionHostProcess.js:636:613
s extensionHostProcess.js:13:221
```

</details>

**Comment by EricJizbaMSFT** [comment]
@AndreasKarz can you add repro steps to this issue?
