### ISSUE TITLE
Python Function deployment

### ISSUE THREAD

**Issue by friaN7331** [microsoft/vscode-azurefunctions#1340]
Repro steps:

1. Generate the Azure Functions sample code
2. Deploy approch VSCode Azure Functions Core Tools

Action: azureFunctions.deploy
Error type: Error
Error Message: "AzureWebJobsStorage" app setting is required for Run From Package deployment.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:332:7463extension.bundle.js:332:7463
o extension.bundle.js:332:6713
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@friaN7331 is the `AzureWebJobsStorage` application setting defined in your function app in Azure? How did you create the function app in Azure? That value should be defined by default and removing it will lead to a lot of problems...

You can check in the Functions view in VS Code:
![Screen Shot 2019-06-12 at 4 19 14 PM](https://user-images.githubusercontent.com/11282622/59392796-d77f4e00-8d2d-11e9-8873-9cb613ada39f.png)

**Comment by friaN7331** [comment]
You got it, this was my problem. 

After recreating the app (to autogenerate this value) it was working fine!

**Thanks a lot!**

Cheers,
Florian
