### ISSUE TITLE
Issue deploying function

### ISSUE THREAD

**Issue by Crazedpeanut** [microsoft/vscode-azurefunctions#1341]
Repro steps:

1. Right click functions project, click deploy to functions app
2. Select functions app to deploy to
3. Receive prompt to set up project to use vscode
4. Select C# as language
5. Receive error

Action: azureFunctions.deploy
Error type: Error
Error Message: Expected to find a single project file in folder "undefined", but found zero or multiple instead.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
DotnetInitVSCodeStep.<anonymous> extension.bundle.js:1:731759
o extension.bundle.js:1:730269
```

</details>

**Comment by EricJizbaMSFT** [comment]
@CrazedPeanut can you give more more information about how your project is set up? Maybe a screenshot of your workspace or a link to a github repo if it's open-source?
