### ISSUE TITLE
VS Code - Azure Functions: Advanced Creation

### ISSUE THREAD

**Issue by ricardomerces** [microsoft/vscode-azurefunctions#1342]
Repro steps:

1.Azure Functions: Advanced Creation (ENABLE)
2.Deploy function
3.Create New Function
4.Select an OS
5.Consumption Plan

Action: azureFunctions.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: name

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.bundle.js:1:160617
Object.module.exports.t.nonNullValueAndProp extension.bundle.js:1:160797
SiteCreateStep.<anonymous> extension.bundle.js:164:80811
module.exports.n extension.bundle.js:164:79934
module.exports.n extension.bundle.js:164:79711
SiteCreateStep.execute extension.bundle.js:164:80239
AzureWizard.<anonymous> extension.bundle.js:262:681915
module.exports.n extension.bundle.js:262:679970
module.exports.n extension.bundle.js:262:679747
module.exports.t.AzureWizard.execute.s.window.withProgress.t extension.bundle.js:262:681538
c._withProgress extensionHostProcess.js:454:323
c.withProgress extensionHostProcess.js:454:77
Object.withProgress extensionHostProcess.js:722:635
AzureWizard.<anonymous> extension.bundle.js:262:681479
module.exports.n extension.bundle.js:262:679970
module.exports.n extension.bundle.js:262:679747
AzureWizard.execute extension.bundle.js:262:681431
FunctionAppProvider.<anonymous> extension.bundle.js:164:310043
o extension.bundle.js:164:305781
```

</details>

**Comment by nturinski** [comment]
Hi @ricardomerces

Thanks for reporting this.  Could you tell me what inputs you are picking to cause this error?  I have tried several combinations but haven't been able to reproduce the error.

**Comment by ricardomerces** [comment]
Nathan,

-Enable Azure functions Advanced Creation
-Deploy function
-Select OS --> LINUX
-Select APP Service Plan
-Create New Function APP in Azure
-Select Pricing --> (b1)
-create new Function app --> East US
-select runtime --> python
-create new resource group --> foo
-select storage account --> foo

ERROR - Cannot Read proper ´name´of undefined

Thanks

**Comment by nturinski** [comment]
Hi @ricardomerces

I still haven't been able to reproduce this issue following these steps.  Could you copy your Output Channel logs so I can see which step is failing?
 
Do you happen to not have full access to the subscription that you are creating this app in?  

Can you think of anything other configurations in your workspace that might be different from mine?

**Comment by MLopesSousa** [comment]
HI Guys, same error!!!

-Enable Azure functions Advanced Creation
-Deploy function
-Select OS --> LINUX
-Select APP Service Plan
-Create New Function APP in Azure
-create new Function app --> East US
-select runtime --> python

**Comment by nturinski** [comment]
Hi @MLopesSousa, thanks for contributing.

Could you copy the output from the Output Channel when this creation fails?  I haven't been able to reproduce this, but I'd like to know which step is failing.

Also, does this issue occur every deploy/creation or is it just every once and a while?  Can you think of anything other configurations in your workspace that might be different from mine? Do you happen to not have full access to the subscription that you are creating this app in?
