### ISSUE TITLE
Bundle dependency not added when adding a binding to an existing function

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1343]
1. Create a function app with an HTTP trigger
1. Right-click `function.json` and choose add binding
1. Choose "out", "Azure Queue Storage", then accept the defaults
1. Choose "AzureWebJobsStorage" for the storage account

Expected: `host.json` is updated with the bundle dependency the same way as when a new function is added.

Actual: the binding is added to `function.json`, but `host.json` is not updated.

**Comment by EricJizbaMSFT** [comment]
As a manual workaround, users can add the "extensionBundle" property to their host.json like this:

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

See [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles) for more info
