### ISSUE TITLE
error NU1101: Unable to find package Microsoft.NET.Sdk.Functions.

### ISSUE THREAD

**Issue by KornelK** [microsoft/vscode-azurefunctions#1345]
Repro steps:
All done  via Windows Powershell
Followed these instructions for installation for Azure Functions:
**_https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local_**

1.Initialise new Azure Function  with command func init
2.Create new  function  with func new command
3. Select HttpTrigger option 
4. Give it a name e.g. test

5. open project in VS code (v. 1.35.1)
6. press F5 to debug

I get the following error:
**error NU1101: Unable to find package Microsoft.NET.Sdk.Functions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages**

Tried to restore by clicking on the popup stating 
**_"There are unresolved dependencies. Please execute the restore command to continue"_**
 I get this error.:
**_ error NU1101: Unable to find package Microsoft.NET.Sdk.Functions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages_**

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.e extension.bundle.js:390:88446
u.fire extensionHostProcess.js:47:720
k.<anonymous> extensionHostProcess.js:636:613
s extensionHostProcess.js:13:221
```

</details>

**Comment by nturinski** [comment]
Hi @KornelK,

Thanks for reporting this issue.  Could you try creating the new function project with the extension rather than the Azure CLI?  There are some settings that we generate for you to optimize usage with VS Code and I'm wondering if that's what's causing these errors.

**Comment by KornelK** [comment]
Running dotnet restore from windows powershell:
![image](https://user-images.githubusercontent.com/18438969/60014576-966a3080-9681-11e9-8812-f699a87d9569.png)

Creating anew function using vsCode same issue.
Note: creating a new function using Javascript or java as the source code works fine and I can start the debugger.

**Comment by nturinski** [comment]
@KornelK Could you post your `.csproj` file?  

According to this documentation (https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1101), the package you are looking for doesn't exist on any source.  That link has a few recommended solutions, maybe try those out?

**Comment by KornelK** [comment]
Thanks will do and will revert with any updated progress.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
