### ISSUE TITLE
Deployment Error - Linux Python Function 

### ISSUE THREAD

**Issue by Mentate** [microsoft/vscode-azurefunctions#1346]
Repro steps:

1. Connect to your tenant
2. Attempt to deploy a python function to Azure

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.17.1
OS: win32
Product: VSCodium
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by msajidirfan** [comment]
Three days back, I created a Python-based Azure Function that reads messages from the Azure Service Bus topic, successfully deployed using VSCode and tested end to end functionality. Today I found that Service Bus trigger function is missing inside that Azure Function while the configuration and application insights are still available. Now, I'm unable to publish any python based Azure Function (not even HTTP trigger based Azure function) and getting the same error specified in previous message.

**Comment by ionsphere** [comment]
Same issue. Previously deployed Python function is no longer visible on Portal. And deployment from VSCode fails with 500.

**Comment by ionsphere** [comment]
As repro, tried creating a new blank TimerTrigger and deploying it.
1. Create a function from TimerTrigger template.
2. Hit deploy.
3. After 6 attempts get 500 InternalServerError

**Comment by jpendyala** [comment]
Same issue:

Repro steps:

Create a python Function using below doc
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python
2.Deploy the Function in VsCode using deploy button in Function Extension
Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

**Comment by nturinski** [comment]
@asavaritayal Do you happen to know what's causing this issue?  It seems that this happened rather suddenly.

**Comment by divyagandhii** [comment]
can you please confirm what region your app is in?

**Comment by ionsphere** [comment]
In my case it is EastUS.
Plan is EastUSLinuxDynamicPlan.

**Comment by balag0** [comment]
@ionsphere Could you restart your app and try again. Let us know if you are still seeing these failures

**Comment by ionsphere** [comment]
Everything return to normal. Can see the function, can deploy an update even before restarting it. Restarted anyway.

**Comment by balag0** [comment]
Great. Thanks for confirming

**Comment by nturinski** [comment]
@ionsphere Really appreciate your prompt responses and feedback.  Makes our life very easy 😄 

@Mentate @jpendyala @msajidirfan Could you try deploying again and let me know the results?  Hopefully, this is all resolved. Thanks!

**Comment by jpendyala** [comment]
yep, it worked like a charm

Thanks for the swift response @nturinski @balag0  @divyagandhii

**Comment by Mentate** [comment]
Okay, so I tried creating an entirely new project from scratch in VS Code and that was able to deploy. It seems the project got corrupted some how. Thanks for the help.
