### ISSUE TITLE
Azure Functions deploy InternalServerError

### ISSUE THREAD

**Issue by ionsphere** [microsoft/vscode-azurefunctions#1347]
Repro steps:
1. Create python Azure Function. Use TimerTrigger as in and CosmosDB as out.
2. Attempt Deploy to Azure Functions.

Expected: succeed or fail with meaningful error.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by ionsphere** [comment]
Dupe of #1346

**Comment by divyagandhii** [comment]
can you please confirm what region your subscription is in?
