### ISSUE TITLE
Central Directory Corrupt

### ISSUE THREAD

**Issue by vincearcher23** [microsoft/vscode-azurefunctions#1351]
got this error when deploying function

11:23:23 PM jsfunctionsbittrex: Central Directory corrupt.
Error: Deployment to "jsfunctionsbittrex" failed. See output channel for more details.

Action: azureFunctions.deploy
Error type: Error
Error Message: Deployment to "jsfunctionsbittrex" failed. See output channel for more details.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:531359
o extension.bundle.js:1:529349
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @vincearcher23,

Thanks for reporting this.  Does this error repo consistently?  Could you list the repo steps?

This seems like it could be an issue with the zip file.  What are you trying to deploy and how are you trying to deploy it?

**Comment by cha000** [comment]
Getting the same error here when trying to do my initial deploy on a brand new Function App.

**Comment by vincearcher23** [comment]
this is the normal steps Im doing when publishing using VSCODE. See my
screenshot below:

[image: image.png]

**Comment by nturinski** [comment]
Hi @vincearcher23, the screenshot didn't show up.  I think this might be because you sent it through email.  But like @cha000, does it resolve itself eventually?  Sometimes new resources take a while to actually spin up and be deployable.
