### ISSUE TITLE
Error: "Failed to detect running Functions host within "60" seconds." on build failure

### ISSUE THREAD

**Issue by bcraun** [microsoft/vscode-azurefunctions#1353]
Repro steps:

1. Create C# function
2. Debug function with F5
3. After ~60s error dialog appears

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:87999
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@bcraun does this always happen for you? Or only in cases where you get a build error or something? We've seen this error occasionally, but it's hard to repro so we'd love to get more info on how exactly you made this happen

**Comment by bcraun** [comment]
@EricJizbaMSFT, yes, I seem to see it only after build errors. If I have a clean compile, I don't see it. Hope that helps.

**Comment by EricJizbaMSFT** [comment]
@bcraun just merged a PR to improve this experience. If you've got the time, you can try out a preview build with these instructions and let us know how it goes: https://aka.ms/azCodeInsiders
