### ISSUE TITLE
Publishing 

### ISSUE THREAD

**Issue by paeppers** [microsoft/vscode-azurefunctions#1357]
Repro steps:

1. VSCode Ubuntu WSL 18.04 project, only differences are ran the environment's python3.6 -m pip install -U on azure_cli and pylint, then freeze > requirements.txt, and removed the pkg-resources=0.0.0 line.
2. Ran func azure functionapp publish meruacrmirror --build-native-deps --no-bundler, got errors in portal. Deploy to Function App (e.g. clicking in VSCode) failed with below.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.17.1
OS: linux
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605866
$.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by paeppers** [comment]
As soon as update requirements.txt with the venv's pip output, fails

**Comment by paeppers** [comment]
Can no longer deploy even provided template python azure function to function app.

**Comment by EricJizbaMSFT** [comment]
@paeppers if the default template is failing to deploy - perhaps something is wrong with the function app in Azure? How did you create it - from VS Code or the portal? What region? If you create a new function app does it work?
