### ISSUE TITLE
Ignores 'disabled' flag in functions.json

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1358]
Taken from https://github.com/microsoft/vscode-node-azure-pack/issues/8

> When debugging/executing in local environment, the `disabled` flag value in `functions.json` is ignored: All functions are started regardless of if they're disabled or not.

**Comment by EricJizbaMSFT** [comment]
The disabled flag was only used in v1. You have to set an app setting like this if you want to disable a function in v2:
```
AzureWebJobs.<function name>.Disabled
```

See https://docs.microsoft.com/en-us/azure/azure-functions/disable-function
