### ISSUE TITLE
[Discussion] Don't always default to West US

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1359]
We default to West US for basic-create mode, but it might not be a good idea to put so many apps in one region.

Potential solutions include:
1. Prompt for location even in basic create
1. Randomly pick a default location
1. Figure out what region has the least number of function apps and use that (we could periodically change this as necessary)

cc @asavaritayal

**Comment by asavaritayal** [comment]
I vote for #1 as it is deterministic.

**Comment by StephenWeatherford** [comment]
FYI, I could be wrong, but I think Azure returns the locations in the order it prefers for the person requesting the list of locations.

**Comment by fiveisprime** [comment]
I'm okay with adding the location prompt. It's not my favorite thing, but Functions has so few prompts already that it's not a huge deal.

**Comment by EricJizbaMSFT** [comment]
The portal selects a default of "Central US" for me
![Screen Shot 2019-07-17 at 11 19 35 AM](https://user-images.githubusercontent.com/11282622/61400312-d9848180-a884-11e9-9170-af3942e0f974.png)

I believe they're doing what @StephenWeatherford suggested, but either way they're picking a default somehow and we should be able to leverage the same API. Doing this would keep our wizard at one prompt, be consistent with the portal (The portal lets them change the location, but I doubt many people do), and still avoid the situation where all apps go into one hard-coded region.

**Comment by EricJizbaMSFT** [comment]
I can't find evidence that the default location ever changes based on user, so not sure that proposal will actually avoid the situation where all apps go into one region. Aka seems like everyone might be getting "Central US" as the default for windows.

I'll capitulate for now and show the location prompt - but I reserve the right to change this behavior if I ever find an api that conclusively suggests different default regions for different users 😃
