### ISSUE TITLE
Entry not found in cache error when trying to create a new fucntion app. 

### ISSUE THREAD

**Issue by Dave-0-0** [microsoft/vscode-azurefunctions#1360]
Repro steps:

1. Following the Azure SignalR chat tutorial at https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-authenticate-azure-functions. 
2. Step 2 in the section "Deploy function app to Azure" states to "select Azure Functions: Deploy to Function App." 
3. When selecting "Create New Function App" the error "Entry not found in cache." is displayed in the lower right corner. 

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457extension.js:229:171457
extension.js:229:43573extension.js:229:43573
extension.js:229:41975extension.js:229:41975
extension.js:229:41127extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
