### ISSUE TITLE
Passing options to func host start?

### ISSUE THREAD

**Issue by foucdeg** [microsoft/vscode-azurefunctions#1361]
I need to customize the command that the debugger runs when starting the local function runner.
Specifically, I need to pass a `--script-root` argument because my functions are in a subdirectory.

My launch.json is the default generated one :

```
{
  "name": "Attach to Python Functions",
  "type": "python",
  "request": "attach",
  "port": 9091,
  "preLaunchTask": "func: host start"
}
```

and the associated task from tasks.json is also the default one:

```
{
  "type": "func",
  "command": "host start",
  "problemMatcher": "$func-watch",
  "isBackground": true,
  "dependsOn": "pipInstall"
},
```

and I expected to be able to add a "args" key in there with arguments to pass to `func host start`.

When I do, the linter tells me that "args" is an unexpected option and it is ignored. The command that is run is just `.env/bin/activate && func host start`.

My current alternative is to run `func host start --script-root  functions` as a shell command but I'm having trouble making it attach to the debugger.

Any way to pass options to `func host start` from the launch or task configuration?

**Comment by EricJizbaMSFT** [comment]
@foucdeg you should have a few options. Something like this:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "command": "host start",
            "problemMatcher": "$func-watch",
            "isBackground": true,
            "dependsOn": "pipInstall",
            "options": {
                "cwd": "${workspaceFolder}/sub"
            }
        },
    ]
}
```

Or something like this:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "command": "host start --script-root",
            "problemMatcher": "$func-watch",
            "isBackground": true,
            "dependsOn": "pipInstall"
        },
    ]
}
```
(If you do this option, you have to change the id of `preLaunchTask` in launch.json as well)

**Comment by foucdeg** [comment]
Thanks!

I made it work by adding a label to the task:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "command": "host start --script-root",
            "label": "func: host start",
            "problemMatcher": "$func-watch",
            "isBackground": true,
            "dependsOn": "pipInstall"
        },
    ]
}
```

**Comment by EricJizbaMSFT** [comment]
@foucdeg I agree it's awkward, but I've been waiting for VS Code to fix this bug to do anything about it: https://github.com/microsoft/vscode/issues/58836

I'm guessing any PR you did would have to work-around that bug, but you're welcome to try.

**Comment by alexweininger** [comment]
https://github.com/microsoft/vscode/issues/58836 is done
