### ISSUE TITLE
Unable to debug function with VS Code

### ISSUE THREAD

**Issue by androidand** [microsoft/vscode-azurefunctions#1363]
Repro steps:

1. Pressed Debug > Start Debugging
2. Error pops up

Deleting the actual _valid_ json in local.settings.json makes it possible to continue with the debugging. Running the Function with func host start works, running and debugging with Visual Studio for Mac 2019 and Visual Studio 2019 works.

Creating a new function project and debugging it in VS Code, with the local.settings.json present works.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:319974
o extension.bundle.js:1:319384
```

</details>

**Comment by EricJizbaMSFT** [comment]
@androidand can you show me what your local.settings.json looks like? (Obviously removing any sensitive information)

Also can you post a screenshot of your project structure? I'm wondering if you have multiple projects in one workspace, a project in a subfolder, or some other non-default setup that might not be working.
