### ISSUE TITLE
Bad Request - Invalid URL: 400 Error code.

### ISSUE THREAD

**Issue by banurekha-r** [microsoft/vscode-azurefunctions#1364]
Repro steps:

1. Install VS code 
2. Install Azure Account and Azure Functions extension.
3. Create a new project and use Function F5 to test it locally
4. While trying to deploy the code to Azure, with valid subscription, getting the following error.  

Action: azureFunctions.deploy
Error type: 400
Error Message: Bad Request - Invalid URL

HTTP Error 400. The request URL is invalid.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:1534761
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@banurekha-r how did you create your function app in Azure? From VS Code, the portal, the az cli, etc.? If you were creating a function app while deploying, you could try setting "azureFunctions.advancedCreation" to "true" in your VS Code settings, which will give you more options.

Does this always happen? Are you behind any unique corporate proxy or something like that?

**Comment by banurekha-r** [comment]
Function app is created via portal. And I tried creating functions both via portal and also adding functions via VS Code. And yes, it always happen and I am in my company network and I configured proxy in VS code

**Comment by EricJizbaMSFT** [comment]
@banurekha-r yeah I'm kinda stumped on this one, but I'm guessing it's related to proxy settings in VS Code
