### ISSUE TITLE
Remove feature flag for slots

### ISSUE THREAD

**Issue by ahmedelnably** [microsoft/vscode-azurefunctions#1367]
Need to add support to:
- Create a slot
- Delete a slot
- Deploy to a slot
- Swap slots

**Comment by EricJizbaMSFT** [comment]
@ahmedelnably most of that should be supported if you set `azureFunctions.enableSlots` to `true` in your VS Code settings. The only thing left to do is https://github.com/microsoft/vscode-azurefunctions/issues/830 and then we plan to remove the feature flag

**Comment by EricJizbaMSFT** [comment]
Re-purposing this issue to track removal of the feature flag

**Comment by EricJizbaMSFT** [comment]
Also probably need to do https://github.com/microsoft/vscode-azurefunctions/issues/1441 to remove feature flag
