### ISSUE TITLE
Unable to create Azure solution in VS Code in MacOS

### ISSUE THREAD

**Issue by avinashsharma5** [microsoft/vscode-azurefunctions#1368]
Repro steps:

1. Create new Azure Function
2. C#

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Could not find template with language "C#", runtime "~2", and id "Azure.Function.CSharp.IotHubTrigger.2.x".

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.<anonymous> extension.bundle.js:164:253583
o extension.bundle.js:164:252718
```

</details>

**Comment by EricJizbaMSFT** [comment]
@avinashsharma5 
1. can you check the Azure Functions output window and copy the logs from there
![Screen Shot 2019-07-09 at 5 11 55 PM](https://user-images.githubusercontent.com/11282622/60930968-ab8fb380-a26c-11e9-88da-95543b08aece.png)
1. Do you have the dotnet cli installed and on your path?
1. Does it work if you do a different template, like http trigger?
