### ISSUE TITLE
Error trying azure functions macos python 3.6 from conda.

### ISSUE THREAD

**Issue by mpeaton** [microsoft/vscode-azurefunctions#1369]
Repro steps:

1.  https://code.visualstudio.com/docs/python/tutorial-azure-functions
2. conda create -n azure_env python=3.6.3
3. Specify python binary path to conda env python in dialog box

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "~/anaconda3/envs/azure_env/bin/python" command. Check output window for more details.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.36.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133974
o extension.bundle.js:1:133039
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mpeaton can you check the "Azure Functions" output window and copy the logs here?

**Comment by mpeaton** [comment]
Is this what you mean?



iMac:wells-fargo mpeaton$ cd /Users/mpeaton/WF ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /Users/mpeaton/anaconda3/envs/wf/bin/python /Users/mpeaton/.vscode-insiders/extensions/ms-python.python-2019.6.22090/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 55014 /Users/mpeaton/WF/azurefunc/.env/pyvenv.cfg 
Traceback (most recent call last):
  File "/Users/mpeaton/.vscode-insiders/extensions/ms-python.python-2019.6.22090/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/mpeaton/.vscode-insiders/extensions/ms-python.python-2019.6.22090/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/Users/mpeaton/.vscode-insiders/extensions/ms-python.python-2019.6.22090/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/mpeaton/anaconda3/envs/wf/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/mpeaton/anaconda3/envs/wf/lib/python3.7/runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/Users/mpeaton/WF/azurefunc/.env/pyvenv.cfg", line 1
    home = /Users/mpeaton/anaconda3/envs/azure_env/bin

**Comment by EricJizbaMSFT** [comment]
The error says `Check output window for more details.`. If you already closed VS Code, the error might not be in the logs any more in which case please try to re-create it.

The output channel will look like this:
![Screen Shot 2019-07-09 at 5 11 55 PM](https://user-images.githubusercontent.com/11282622/60930968-ab8fb380-a26c-11e9-88da-95543b08aece.png)

**Comment by mpeaton** [comment]
Updating Script templates for runtime "~1" to version "1.9.0"...
invalid local file header signature: 0x0
Falling back to version "1.8.0" for Script templates for runtime "~1".
Updating Script templates for runtime "~2" to version "2.24.0"...
end of central directory record signature not found
Falling back to version "2.18.1" for Script templates for runtime "~2".
Running command: "git init"...
Initialized empty Git repository in /Users/mpeaton/WF/.git/
Finished running command: "git init".
Running command: "~/anaconda3/envs/azure_env/bin/python -m venv .env"...
Error: Command '['/Users/mpeaton/WF/.env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: Failed to run "~/anaconda3/envs/azure_env/bin/python" command. Check output window for more details.
Running command: "~/anaconda3/envs/azure_env/bin/python -m venv .env"...
Error: Command '['/Users/mpeaton/WF/azurefunc/.env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: Failed to run "~/anaconda3/envs/azure_env/bin/python" command. Check output window for more details.
Running command: "/Users/mpeaton/anaconda3/envs/azure_env/bin/python3.6 -m venv .env"...
Error: Command '['/Users/mpeaton/WF/azurefunc/.env/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: Failed to run "/Users/mpeaton/anaconda3/envs/azure_env/bin/python3.6" command. Check output window for more details.
Running command: "~/anaconda3/envs/azure_env/bin/python -m venv .env"...
Error: Command '['/Users/mpeaton/WF/azurefunc/.env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: Failed to run "~/anaconda3/envs/azure_env/bin/python" command. Check output window for more details.

**Comment by EricJizbaMSFT** [comment]
Hmm unfortunately that's still not super helpful since it just says "returned non-zero exit status 1."

Can you try running `~/anaconda3/envs/azure_env/bin/python -m venv .env` manually from the command line and seeing if you get more detailed errors?

**Comment by mpeaton** [comment]
(azure_env) iMac:bin mpeaton$ ~/anaconda3/envs/azure_env/bin/python -m venv .env
Error: Command '['/Users/mpeaton/WF/azurefunc/.env/bin/.env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

**Comment by EricJizbaMSFT** [comment]
@mpeaton if you're getting the same error from the command line then I'm not sure what we can do. It must be a problem with how your python environment is set up. Maybe try searching that error
