### ISSUE TITLE
WEBSITE_CONTENTSHARE is required for Standard Plan when it should not be required when deploying properties

### ISSUE THREAD

**Issue by borysl** [microsoft/vscode-azurefunctions#1370]
Repro steps:

1. Have functional app version beta
2. Upload local settings without WEBSITE_CONTENTSHARE

Action: azureFunctions.appSettings.upload
Error type: BadRequest
Error Message: Required parameter WEBSITE_CONTENTSHARE is missing.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.E.l.pipeline extension.bundle.js:262:1531503
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@borysl what type of function app is this? Linux/windows? And what language?

That setting has a special meaning and sometimes will exist when you create a function app. You might want to re-create the function app if you're seeing that error.
