### ISSUE TITLE
Azure DevOps Continuous Delivery requires you to have permissions to write to Azure Active Directory and create a service 

### ISSUE THREAD

**Issue by bbakermmc** [microsoft/vscode-azurefunctions#1371]
What permission in AAD do you need set.  In testing I was set to a Global Admin, re-logged and still cant create an CI/CD from the portal UI.

Azure DevOps Continuous Delivery requires you to have permissions to write to Azure Active Directory and create a service

**Comment by EricJizbaMSFT** [comment]
@bbakermmc it sounds like your problem is with Azure Dev Ops or the portal, but this repo is for the VS Code extension. Can you clarify?

**Comment by bbakermmc** [comment]
@EricJizbaMSFT If you google this error, this code base has a reference to this error message.
Yes this issue is occurring when you try to configure a CI/CD from azure.  But as typical with most azure things, documentation is non existent, error messages dont provide details, so I googled the error and it lead me here.

![image](https://user-images.githubusercontent.com/30090055/60932117-91fd6480-a28a-11e9-82cf-ad4432aeb5ae.png)

**Comment by EricJizbaMSFT** [comment]
Perhaps this link will help: https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment#option-2-use-azure-pipelines-preview

It says:
> For App Service to create the necessary Azure Pipelines in your Azure DevOps Services organization, your Azure account must have the role of Owner in your Azure subscription.

**Comment by bbakermmc** [comment]
@EricJizbaMSFT Yup that's what I would be looking for.  But its pretty bad that I would need owner access to a subscription to create it :P  But thats beyond you.

Thanks.
