### ISSUE TITLE
"Toggle App Setting Visibility" button doesn't work on Insiders

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1375]
**OS**: Win10
**Build Version**: [20190710.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7601)
**VS Code Insiders Version**: 1.37.0-insiders (user setup)

**Repro Steps:**
1. Drill down from one function app -> Application Settings node.
2. Click the "Toggle App Setting Visibility" button for one application setting and check the result.

**Expect:**
The "Toggle App Setting Visibility" button works well and succeed to see the application setting value.

**Actual:**
"Toggle App Setting Visibility" button doesn't work.

**More Info:**
1. The "Toggle App Setting Visibility" button works well in **App Service Explorer** with **VS Code Insiders**.
2. The "Toggle App Setting Visibility" button works well in **Azure Functions Explorer** with **VS Code.**

**Comment by EricJizbaMSFT** [comment]
Filed bug on VS Code: https://github.com/microsoft/vscode/issues/77677

**Comment by EricJizbaMSFT** [comment]
Filed another bug on VS Code: https://github.com/microsoft/vscode/issues/78222

**Comment by EricJizbaMSFT** [comment]
This was fixed in VS Code. No longer repros for me on this version:
Version: 1.37.0-insider
Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
Date: 2019-07-31T05:21:45.449Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
