### ISSUE TITLE
Unable to get local issuer certificate when trying to publish azure functions via vscode

### ISSUE THREAD

**Issue by chemicalspaceman** [microsoft/vscode-azurefunctions#1376]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1049:34
TLSSocket.emit events.js:182:13
TLSSocket._finishInit _tls_wrap.js:631:8
```

</details>

**Comment by EricJizbaMSFT** [comment]
@chemicalspaceman please add repro steps to this issue. In general, proxy support and/or certificate support is handled in VS Code, not our extension
