### ISSUE TITLE
Handle lack of internet connection or if the www.powershellgallery.com is down when creating PowerShell function apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [microsoft/vscode-azurefunctions#1379]
For PowerShell function apps, we enable Managed Dependencies (MDs) at creation time. During this process, we need to connect to the www.powershellgallery.com to retrieve the latest available module version for the Azure Az modules. If the www.powershellgallery.com is down or the user has no internet connection, we need to provide the correct guidance to the user.

This experience will look exactly like the one in the Core Tools. For reference, please see  https://github.com/Azure/azure-functions-core-tools/pull/1434.

Please update the Requirements.psd1 template to the following:
```
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'. [GUIDANCE]
    # 'Az' = 'MAJOR_VERSION.*'
}
```

### Scenario 1: 
The user has internet connection and the www.powershellgallery.com is available.

Customer creates a PowerShell function app. At app creation, we connect to the www.powershellgallery.com to get the latest module version. The code to connect to the powershellgallery.com is already available in the Core Tools (https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/Helpers/PowerShellHelper.cs). It just needs to be written Type Script.

Generating requirements.pd1 file: ```template + (replace "# 'Az'" with "'Az'" and [GUIDANCE] with string.empty)```

If we were able to connect to the PSGallery, then the requirements.psd1 file will look like this:
```
# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in public preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    'Az' = '2.*'
}
```

### Scenario 2: 
The user has no internet connection or the www.powershellgallery.com is not available.

For this scenario, if we failed to get the latest module version for Az, we need to write the warning (or equivalent in VSCode) to the user: **Failed to get Az module version. Edit the requirements.psd1 file when the powershellgallery.com is accessible.**

Generating requirements.pd1 file: ```template + (replace [GUIDANCE] with "Uncomment the next line and replace the MAJOR_VERSION, e.g., 'Az' = '2.*'")```

Requirements.psd1 file will look like this:
```
# This file enables modules to be automatically managed by the Functions service.
# Only the Azure Az module is supported in public preview.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'. Uncomment the next line and replace the MAJOR_VERSION, e.g., 'Az' = '2.*'
    # 'Az' = 'MAJOR_VERSION.*'
}
```

**Comment by EricJizbaMSFT** [comment]
@Francisco-Gamino is the `Az` module actually needed for most triggers? Can you share example code where it's used? I'm beginning to wonder if we should avoid writing `Az` as a dependency in projects that may never use it, especially considering Http and Timer triggers are by far the most popular and I doubt those need `Az`

**Comment by Francisco-Gamino** [comment]
Hello @EricJizbaMSFT, one of our main scenarios for PowerShell in Functions is to manage Azure resources. Adding @eamonoreilly to help answer the question above. Thanks.

cc: @AnatoliB @anirudhgarg

**Comment by eamonoreilly** [comment]
By far the most common use case (almost all customers) is managing Azure resources with PowerShell in functions. This is why we want to default the inclusion of the Az modules so customers can focus on writing the PowerShell tasks and not need to worry about the Az dependencies.
Thanks,
Eamon

**Comment by EricJizbaMSFT** [comment]
@eamonoreilly I'm still curious to see some example code if you have it. None of the templates that I tried referenced `Az` directly as far as I could tell. If it's such an important scenario - maybe there should be some templates using `Az`?

**Comment by eamonoreilly** [comment]
@EricJizbaMSFT Hi Eric, you can see samples on https://serverlesslibrary.net/?language=PowerShell on using functions to manage Azure resources.
Thanks,
Eamon
