### ISSUE TITLE
Fail to run "func host start" with an error on Mac 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1385]
**OS:** Mac
**Build Version:** [20190717.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7757)
**Func Version:** 2.7.1468
**Dotnet Version**: 2.2.105

**Repro Steps:**
1. Create a C# project.
2. Try to debug it.

**Expect:**
Succeed to debug the C# project.

**Actual:**
Pop up an error "Setting unsupported .NET environment variables (empty string) is not implemented.".
![image](https://user-images.githubusercontent.com/34729092/61444692-7c6cf680-a97e-11e9-88ed-3df8048e1a4e.png)

**More Info:**
This issue **doesn't** reproduce on Windows with below configurations.
![image](https://user-images.githubusercontent.com/34729092/61444688-75de7f00-a97e-11e9-8ed4-2ce8f2e6ad49.png)

**Comment by aaldrin23** [comment]
I'm also facing this error, I just started my first azure function and this happen. can't proceed for deployment.
but simple local function works.

**Comment by EricJizbaMSFT** [comment]
Filed an issue on the func cli: https://github.com/Azure/azure-functions-core-tools/issues/1447

**Comment by EricJizbaMSFT** [comment]
As a workaround, you can remove `"AzureWebJobsStorage": "",` from `local.settings.json`

**Comment by v-dantch** [comment]
Hi Eric, thanks for your share, and it works well after removing the "AzureWebJobsStorage":""  from local.settings.json.

**Comment by aaldrin23** [comment]
It works! thanks.

**Comment by EricJizbaMSFT** [comment]
This was fixed in v2.7.1480 of the func cli

**Comment by jfversluis** [comment]
Hope you also noticed the typo in the error message “environemt”

**Comment by v-dantch** [comment]
Hi @jfversluis , thanks a lot for your reminding. And I will pay more attention to the spelling :).
