### ISSUE TITLE
[Discussion] `azureFunctions.pythonVenv` vs. `python.pythonPath`

### ISSUE THREAD

**Issue by keitherskine** [microsoft/vscode-azurefunctions#1393]
I have a query about the version of Python used when I deploy an Azure Function from VS Code using the "up-arrow" in the Azure extension.  This is the "up-arrow" that is labelled "Deploy to Function App..." when you hover over it.

In my case, I am using a Python virtual environment that is set up for Python 3.6, although I also have Python 3.7 installed on my PC.  The name of the venv can be seen in the lower left corner of VS Code as, correctly, "3.6.6 64-bit ('azure': venv)".  Yet when I deploy the function, it appears VS Code is using the default Python version (3.7) on my PC.  Here is the start of the output:
```
> Executing task: func pack <

Deleting the old .python_packages directory
Python 3.6.x is recommended, and used in Azure Functions. You are using Python version Python 3.7.3.
Collecting azure-storage-blob==2.0.1 (from -r C:\Users\Keith\Documents\GitHub\MyAzureFunctionProj\requirements.txt (line 1))
```
As you can see, it warns about using version 3.7.3, even though I previously selected my 3.6 virtual environment.

In an attempt to fix this, I set the `azureFunctions.pythonVenv` settings to "C:\\Users\\Keith\\pyvenvs\\azure".  Here is the new output:
```
> Executing task: C:\Users\Keith\pyvenvs\azure\Scripts\activate ; func pack <

& C:/Users/Keith/pyvenvs/azure/Scripts/activate.ps1
Deleting the old .python_packages directory
Python 3.6.x is recommended, and used in Azure Functions. You are using Python version Python 3.7.3.
Collecting azure-storage-blob==2.0.1 (from -r C:\Users\Keith\Documents\GitHub\MyAzureFunctionProj\requirements.txt (line 1))
```
VS Code now appears to be trying to activate the Python 3.6 venv from `azureFunctions.pythonVenv`, yet still warns about using Python 3.7.  Is VS Code using the venv? Did the venv get activated?  Curious that both `activate.bat` and `Activate.ps1` seem to be being called.

This doesn't look right, although it has to be said it doesn't appear to be causing an issue.  Nevertheless, it would still be nice if the Azure extension used the venv defined in the `python.venvPath` setting rather than having a separate `azureFunctions.pythonVenv` setting.

**Comment by EricJizbaMSFT** [comment]
@keitherskine Based on the logs, it seems like the venv is not being activated correctly. Can you try running the commands manually and see if you get any more descriptive errors? Specifically:
```
C:\Users\Keith\pyvenvs\azure\Scripts\activate ; python --version
```

What is your default terminal in VS Code?

The `azureFunctions.pythonVenv` should almost always be auto-set for the user when you initialize a functions project in VS Code. Can you describe repro steps for how you got into a situation where `python.venvPath` was set, but `azureFunctions.pythonVenv` was not? The functions setting actually existed before the python setting and has slightly different behavior. We might be able to merge the settings, but just haven't had anyone ask for that so far 🙂

**Comment by keitherskine** [comment]
After investigation, it looks like the venv is not being set because my default terminal in VSCode is Powershell, and apparently you have to run `set-executionpolicy remotesigned` before running anything in Powershell.  Hence, when `C:\Users\Keith\pyvenvs\azure\Scripts\activate` was run in the terminal, it simply failed (along with Activate.ps1), and the default system-wide version of Python (3.7) was used instead.  Probably best if I use the command shell as my default terminal.

On the question of the VSCode settings, the relevant ones here seem to be `python.pythonPath`, `python.venvPath`, and `azureFunctions.pythonVenv`.  There seems to be some overlap between them.  The one that shows the Python venv seen in the bottom left-hand corner of VSCode is apparently `python.pythonPath`.  I'm guessing `azureFunctions.pythonVenv` is used when deploying, although I can't think of a scenario where the two would need to be different.  Lastly, `python.venvPath` seems to be the path to a folder that contains multiple venv folders, not a venv in itself (perhaps `python.venvsPath` might have been a better name?).

Anyway, this seems to have been a problem with my setup, so I'm closing this issue.  Many thanks for your help, @EricJizbaMSFT !

**Comment by keitherskine** [comment]
On further investigation, I'm getting an error saying my venv folder doesn't exist, even though I'm sure it does.
![image](https://user-images.githubusercontent.com/1158224/61805081-bfa1ec00-adfa-11e9-8e66-d79b41bb84e2.png)
Looking at this code:
https://github.com/microsoft/vscode-azurefunctions/blob/2577a975668599ca8b4310b7bc0b7072a614c1a4/src/vsCodeConfig/verifyVSCodeConfigOnActivate.ts#L43
it appears that VSCode expects or requires the venv to be located within the project workspace.  Is that correct @EricJizbaMSFT ?
To see what VSCode does by default, I created a brand new Azure Function from within VSCode using the Azure extension.  The `azureFunctions.pythonVenv` setting was ".env" and the `python.pythonPath` setting was ".env\\Scripts\\python.exe".  These are both relative paths, relative to the workspace.  Does this mean those settings have to be relative paths, @EricJizbaMSFT ?  Or can they be absolute paths?  It would be good to know.  My preference would be to use a venv completely separate from the workspace.  Any and all guidance appreciated.  Thanks in advance.

**Comment by EricJizbaMSFT** [comment]
I'm not sure about `python.pythonPath` (that would be a question for the python extension) - but yes the Azure Functions one _does_ have to be inside the workspace. We prioritized the scenario where a project would be committed to git and pulled down by another team member. The `.vscode` folder should be committed to git (since it describes how to debug and a lot of people customize it for their project) and it would not make sense to commit an absolute path because that won't work for someone else.

A few cases where `azureFunctions.pythonVenv` is unique:
1. It's directly referenced in `tasks.json`
1. Users will be prompted to re-create the venv if we see the setting, but not the venv (again this is mainly for the scenario where someone clones a project since the venv is not committed)
1. When re-creating a venv, it will automatically install `azure-functions` types so that users get intellisense (we didn't want to add this to "requirements.txt" since it's more of a "dev" package and not needed for production)

I'm totally willing to consider merging these settings or supporting an absolute path. We just haven't had anyone request it yet and as I mentioned before the functions setting was created first and so it was just easier to keep it as-is

**Comment by keitherskine** [comment]
Thank your for the comprehensive explanation, @EricJizbaMSFT .  What you're saying does largely make sense.  There seem to be three things here:
1) Keeping `azureFunctions.pythonVenv` as a folder within the workspace.  If this really is necessary, it might be an idea to make this clear in the description of the setting (e.g. when you hover over it).
2) Keeping the `python.pythonPath` and `azureFunctions.pythonVenv` settings in sync.  It's kinda handy if they point to the same venv.  Right now, it's very easy to change the `python.pythonPath` setting by clicking on the Python venv label in the bottom left-hand corner of VSCode.  Perhaps this can be greyed-out/disabled if the `azureFunctions.pythonVenv` setting exists.
3) Installing the "azure-functions" module into the venv.  I appreciate this is necessary for local development work and very much not necessary when deploying to Azure, hence your reluctance to put it into the "requirements.txt" file.  Nevertheless, that does make things a bit opaque.  Perhaps the Azure extension could generate a file called "requirements_local.txt" (containing just "azure-functions") which would be "pip install"ed when the venv is created.  I don't think it would matter if that file was included in git.

Anyway, those were just a few thoughts.  I will use a local venv in the workspace from now on, to keep things simple.  Thanks again.

**Comment by EricJizbaMSFT** [comment]
Thanks for your responses. Re-opening so that my team and I can discuss/triage the feedback
