### ISSUE TITLE
cannot package python regex

### ISSUE THREAD

**Issue by eriakul** [microsoft/vscode-azurefunctions#1397]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/erika/Documents/TinderApp/APPys/getAuthToken/getAuthToken.zip

Version: 0.17.1
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
@eriakul please add repro steps to this issue. This problem happens most often if the "func pack" task failed for a python project. Check for any errors that happen during that task
