### ISSUE TITLE
Azure function project generates error when trying to start

### ISSUE THREAD

**Issue by MennoKlup** [microsoft/vscode-azurefunctions#1398]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:319974
o extension.bundle.js:1:319384
```

</details>

**Comment by EricJizbaMSFT** [comment]
@MennoKlup check your "local.settings.json" file and make sure it is valid JSON. Otherwise please add repro steps

**Comment by mennolaan** [comment]
I switched to visual studio 2019 for mac.
