### ISSUE TITLE
cannot create a new function app project

### ISSUE THREAD

**Issue by RichardThomas215** [microsoft/vscode-azurefunctions#1399]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\rthomas\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.17.1\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\rthomas\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\rthomas\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~2.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name "Function app practice" --arg:AzureFunctionsVersion v2" failed with exit code "4294967295":
ERROR: Failed to find template with identity "Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x".

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134101
o extension.bundle.js:1:133039
```

</details>

**Comment by EricJizbaMSFT** [comment]
@RichardThomas215 please add repro steps to this issue

In addition -
1. Do you have the dotnet cli installed and on your path? If so - what version?
1. Can you check the output window for "Azure Functions" and copy any logs from there?

**Comment by RichardThomas215** [comment]
Repro
1. create a new function app project clicking on the "create new project" icon

dotnet cli version : 2.2.301
now output in logs relating to azure

LOGS:

Updating .NET templates for runtime "~1" to version "1.10.0"...
self signed certificate in certificate chain
EPERM: operation not permitted, open 'c:\Users\rthomas\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~1.nupkg'
Updating .NET templates for runtime "~2" to version "2.26.0"...
self signed certificate in certificate chain
EPERM: operation not permitted, unlink 'c:\Users\rthomas\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~1.nupkg'

**Comment by EricJizbaMSFT** [comment]
Are you behind a corporate proxy or something? Can you double check your proxy settings in VS Code?

Also do those files exist at the stated path?
c:\Users\rthomas\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~1.nupkg
