### ISSUE TITLE
Streaming Azure Function Logs - not working/supported

### ISSUE THREAD

**Issue by kprpg** [microsoft/vscode-azurefunctions#1402]
Repro steps:

1.
2.

Action: azureFunctions.startStreamingLogs
Error type: Error
Error Message: This operation is not supported by this app service plan.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
SiteClient.get kudu [as kudu] extension.bundle.js:332:359969
Object.<anonymous> extension.bundle.js:332:832250
o extension.bundle.js:332:831321
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by kprpg** [comment]
Repro:-
1. Create Python Azure Function per https://docs.microsoft.com/en-us/azure/azure-functions/tutorial-vs-code-serverless-python#visual-studio-code-python-and-the-azure-functions-extension
2. Right click on the Azure Function Project from the Azure Tab in VS Code, and click on "Start Streaming Logs". 
You will get the error in the output window - this is not supported.

**Comment by EricJizbaMSFT** [comment]
@kprpg correct this is not supported yet. See https://github.com/microsoft/vscode-azurefunctions/issues/589
