### ISSUE TITLE
Make default Python virtual environment folder name ".venv", not ".env"

### ISSUE THREAD

**Issue by keitherskine** [microsoft/vscode-azurefunctions#1404]
When creating a new Azure Functions project through VSCode, the Python virtual environment folder is called ".env".  This name is easily confused with environment variable files.
Brett Cannon (one of the Python committers) raised this in the Azure Docs repo:
https://github.com/MicrosoftDocs/azure-docs/issues/33886
would it be possible to make the default name for the Python virtual environment folder `.venv` rather than `.env` to avoid clashing with anything that looks like environment variables?  Many thanks.

Let me know if this is better reported in https://github.com/Azure/azure-functions-python-worker .

**Comment by EricJizbaMSFT** [comment]
Already done :) https://github.com/microsoft/vscode-azurefunctions/pull/1373

Should be included in the next release. You're welcome to try the latest from master with these instructions: https://aka.ms/azCodeInsiders

**Comment by keitherskine** [comment]
That's great to hear, @EricJizbaMSFT , many thanks!

Just FYI, though, I did notice these lines in the "azure-functions-python-worker" repo that include references to a ".env" Python virtual environment:
https://github.com/Azure/azure-functions-python-worker/blob/master/pack/scripts/nix_deps.sh#L3-L4
https://github.com/Azure/azure-functions-python-worker/blob/master/pack/scripts/win_deps.ps1#L1-L2
Not sure if it's necessary to change them, but I thought I'd let you know.
