### ISSUE TITLE
Cannot debug project locally

### ISSUE THREAD

**Issue by mengyaoh** [microsoft/vscode-azurefunctions#1406]
Dotnet build will build the project it will build successfully.

but when > Executing task: func host start < it gives the error:

Unknown Error: 0x80070459

Then the application will start normally and function well but the debugging toolbar will then disappear and the breakpoints wouldn't work.

Also giving an issue of:

Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

This happens everytime. I used to have this problem but after I upgrade my OS system it was fixed but now it appears again. Tried to upgrade VScode too still not fixed.

Version: 0.17.1
OS: Mojave

My launch.json:

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to C# Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    },
    {
      "name": ".NET Core Launch (console)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/Db.Tests/bin/Debug/netcoreapp2.2/Db.Tests.dll",
      "args": [],
      "cwd": "${workspaceFolder}/Db.Tests",
      "console": "internalConsole",
      "stopAtEntry": false,
      "internalConsoleOptions": "openOnSessionStart"
    },
    {
      "name": "ResourceGroup Launch (console)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build1",
      "program": "${workspaceFolder}/ResourceGroup/bin/Debug/netcoreapp2.2/ResourceGroup.dll",
      "args": [],
      "cwd": "${workspaceFolder}/ResourceGroup/bin/Debug/netcoreapp2.2",
      "console": "internalConsole",
      "stopAtEntry": false,
      "internalConsoleOptions": "openOnSessionStart"
    },
    {
      "name": ".NET Core Attach",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:pickProcess}"
    }
  ]
}

**Comment by EricJizbaMSFT** [comment]
@mengyaoh what version of the .net cli do you have? Run `dotnet --version` to see

**Comment by mengyaoh** [comment]
> dotnet --version

2.2.301

I restarted the computer. It worked but momentarily it fails I have to restart it again.

**Comment by EricJizbaMSFT** [comment]
@mengyaoh try running `func host start` from the command line. If it fails from the command line, that implies there's a problem with your dotnet, func cli, or machine set up. I'm not sure VS Code can help with that
