### ISSUE TITLE
Unable to view app settings in the extension

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurefunctions#1407]
When i click the icon to show the settings, they do not appear. see the video below.

v0.17.1

![2019-07-26_13-19-46](https://user-images.githubusercontent.com/1202528/61969337-4cd67380-afa8-11e9-970f-e6306d540d26.gif)

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1375

Unfortunately it's a bug in VS Code Insiders that we have little control over
