### ISSUE TITLE
Local package doesn't get deployed correctly

### ISSUE THREAD

**Issue by armanio123** [microsoft/vscode-azurefunctions#1411]
I have a TypeScript Azure Function that uses local npm package. My local package contains an `index.js` file in the root path and a `subFolder` folder containing all of the necessary `js` files.

When deploying the Function the node_modules folder doesn't contain the whole local package files. The `node_modules` folder contains the local package folder but only the `index.js` is there. Any sub-folders like `source` are missing. 

I don't see that behavior when installing it in my local environment. Also I checked the path `D:\local\Temp\zipdeploy\extracted` and noticed that the sub-folders are missing from here as well.

Project files:
```
/project
    /localPackage
        /subFolder
            (.js files used on index.js)
        index.js
    /functionFolder
        (index.ts, function.json, and other ts files)
    package.json
```

package.json:
```json
...
"dependencies": {
    "local-package": "file:localPackage"
}
...
```

**Comment by EricJizbaMSFT** [comment]
Is `localPackage` by chance a symlink? Could be a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1289

**Comment by armanio123** [comment]
@EricJizbaMSFT Yes it is. `npm` do a symlink by default when installing a local package.

**Comment by armanio123** [comment]
This seems like a duplicate as you stated. I'll close this bug and follow up on the other one.
