### ISSUE TITLE
Azure function deployment failure for python

### ISSUE THREAD

**Issue by gopalvaddi** [microsoft/vscode-azurefunctions#1412]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@gopalvaddi please add repro steps

**Comment by gopalvaddi** [comment]
> azure-functions-core-tools@2.7.1575 postinstall C:\Users\562854\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1575/Azure.Functions.Cli.win-x64.2.7.1575.zip"

+ azure-functions-core-tools@2.7.1575
updated 1 package in 14.551s
Finished running command: "npm install -g azure-functions-core-tools@2".
21:55:16 AnomalyFramework: Starting deployment...
21:55:18 AnomalyFramework: Uploading zip package to storage container...
21:55:32 AnomalyFramework: Syncing triggers...
21:55:40 AnomalyFramework: Syncing triggers (Attempt 2/6)...
21:55:51 AnomalyFramework: Syncing triggers (Attempt 3/6)...
21:56:12 AnomalyFramework: Syncing triggers (Attempt 4/6)...
21:56:52 AnomalyFramework: Syncing triggers (Attempt 5/6)...
21:58:14 AnomalyFramework: Syncing triggers (Attempt 6/6)...
Error: Encountered an error (ServiceUnavailable) from host runtime.

**Comment by EricJizbaMSFT** [comment]
@gopalvaddi yeah we occasionally see a ServiceUnavailable error from Azure. Were you ever able to deploy successfully? Perhaps try a different region?

Also if you can send more details about your project that might be helpful. I assume it's python based on the logs from above - how did you create the project? What kind of triggers do you have (http, timer, etc.)?
