### ISSUE TITLE
Simplify typescript scripts in package.json

### ISSUE THREAD

**Issue by ethanroday** [microsoft/vscode-azurefunctions#1413]
- VSCode Version: 1.36.0
- OS Version: 10.0.17763

Steps to Reproduce:
1. Create a new function app from Typescript template.

The command `npm start` doesn't work on Windows, since the `&` in `npm run start:host & npm run watch` does not cause commands to be run concurrently.

**Fix:** Using [npm-run-all](https://www.npmjs.com/package/npm-run-all), you can just say `run-p start:host watch`, which seems to work well for me.

**Comment by ethanroday** [comment]
I understand the rationale, @EricJizbaMSFT, nonetheless it's still a little bit concerning to me that there's a template that doesn't actually work out of the gate. Maybe there's somewhere that a note could be added to the user?

**Comment by EricJizbaMSFT** [comment]
Yeah good point about working out of the gate. Rather than add a comment, I'd prefer to simplify the scripts so that they "work" - even if that means they do a little less. As another reason, the scripts are already out of date since we don't need to run "func extensions install" anymore.

This is what we currently have:
```json
{
  "name": "ts1",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "prestart": "npm run build && func extensions install",
    "start:host": "func start",
    "start": "npm run start:host & npm run watch",
    "build:production": "npm run prestart && npm prune --production",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {},
  "devDependencies": {
    "@azure/functions": "^1.0.2-beta2",
    "typescript": "^3.3.3"
  }
}
```

This is what I propose:
```
{
  "name": "ts1",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "prestart": "npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {},
  "devDependencies": {
    "@azure/functions": "^1.0.2-beta2",
    "typescript": "^3.3.3"
  }
}
```
