### ISSUE TITLE
Simple HelloWorld Function in C# does not get deployed (no errors, deployment shows "completed" message)

### ISSUE THREAD

**Issue by argenacho** [microsoft/vscode-azurefunctions#1415]
Hi, I'm using VSCode 1.36.1 on MacOS, .NET Core SDK 2.2.401 (only SDK and runtime installed in my machine), and the Azure Functions Extension v 0.17.1. I create a simple function using the extension, in C# and with HTTP Binding. I try it locally and everything runs smoothly. I then tried to deploy this to my Azure subscription (both creating a function app from the extension and selecting an existing function app, always running in functions v2). The compilation and deployments seem to finish correctly, but when I go the portal I can't find the function deployed. 
Everything I'm using is a "vainilla" as it gets, and followed this tutorial:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code#enable-publishing-with-advanced-create-options

**Comment by EricJizbaMSFT** [comment]
@argenacho can you copy the output of the deploy logs here?

**Comment by argenacho** [comment]
Hi, thanks for reaching out and sorry for the delay. I've updated the functions extension to the latest version, and the error persists. Here are the output logs:

Running command: "git init"...
Initialized empty Git repository in /Users/Nacho/repos/HelloFunction/.git/
Finished running command: "git init".
4:52:01 PM whcampus-test-fcn: Creating zip package...
4:52:04 PM whcampus-test-fcn: Starting deployment...
4:52:43 PM whcampus-test-fcn: Fetching changes.
4:52:43 PM whcampus-test-fcn: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\m003pxz4.zip (6.44 MB) to D:\local\Temp\zipdeploy\extracted
4:52:48 PM whcampus-test-fcn: Updating submodules.
4:52:48 PM whcampus-test-fcn: Preparing deployment for commit id '5b1fbcc990'.
4:52:48 PM whcampus-test-fcn: Generating deployment script.
4:52:49 PM whcampus-test-fcn: Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
4:52:50 PM whcampus-test-fcn: Running deployment command...
4:52:50 PM whcampus-test-fcn: Command: "D:\home\site\deployments\tools\deploy.cmd"
4:52:52 PM whcampus-test-fcn: Handling Basic Web Site deployment.
4:52:54 PM whcampus-test-fcn: Creating app_offline.htm
4:52:54 PM whcampus-test-fcn: KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
4:52:54 PM whcampus-test-fcn: Deleting file: 'HelloFunction2.cs'
4:52:54 PM whcampus-test-fcn: Deleting file: 'HelloFunction2.csproj'
4:52:54 PM whcampus-test-fcn: Copying file: '.gitignore'
4:52:55 PM whcampus-test-fcn: Copying file: 'HelloFunction.cs'
4:52:55 PM whcampus-test-fcn: Copying file: 'HelloFunction.csproj'
4:52:55 PM whcampus-test-fcn: Copying file: 'host.json'
4:52:55 PM whcampus-test-fcn: Copying file: 'local.settings.json'
4:52:55 PM whcampus-test-fcn: Copying file: '.vscode\extensions.json'
4:52:55 PM whcampus-test-fcn: Copying file: '.vscode\launch.json'
4:52:55 PM whcampus-test-fcn: Copying file: '.vscode\settings.json'
4:52:55 PM whcampus-test-fcn: Copying file: '.vscode\tasks.json'
4:52:55 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\HelloFunction2.deps.json'
4:52:55 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\HelloFunction.deps.json'
4:52:55 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\host.json'
4:52:55 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\local.settings.json'
4:52:55 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\HelloFunction2\function.json'
4:52:55 PM whcampus-test-fcn: Deleting directory: 'bin\Release\netcoreapp2.1\HelloFunction2'
4:52:55 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\bin\HelloFunction2.dll'
4:52:55 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\bin\HelloFunction2.pdb'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\bin\extensions.json'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\bin\HelloFunction.dll'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\bin\HelloFunction.pdb'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\HelloFunction\function.json'
4:52:56 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\publish\HelloFunction2.deps.json'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\HelloFunction.deps.json'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\host.json'
4:52:56 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\publish\HelloFunction2\function.json'
4:52:56 PM whcampus-test-fcn: Deleting directory: 'bin\Release\netcoreapp2.1\publish\HelloFunction2'
4:52:56 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\publish\bin\HelloFunction2.dll'
4:52:56 PM whcampus-test-fcn: Deleting file: 'bin\Release\netcoreapp2.1\publish\bin\HelloFunction2.pdb'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\bin\extensions.json'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\bin\HelloFunction.dll'
4:52:56 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\bin\HelloFunction.pdb'
4:52:57 PM whcampus-test-fcn: Copying file: 'bin\Release\netcoreapp2.1\publish\HelloFunction\function.json'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\HelloFunction2.csproj.nuget.cache'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\HelloFunction2.csproj.nuget.dgspec.json'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\HelloFunction2.csproj.nuget.g.props'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\HelloFunction2.csproj.nuget.g.targets'
4:52:57 PM whcampus-test-fcn: Copying file: 'obj\HelloFunction.csproj.nuget.cache'
4:52:57 PM whcampus-test-fcn: Copying file: 'obj\HelloFunction.csproj.nuget.dgspec.json'
4:52:57 PM whcampus-test-fcn: Copying file: 'obj\HelloFunction.csproj.nuget.g.props'
4:52:57 PM whcampus-test-fcn: Copying file: 'obj\HelloFunction.csproj.nuget.g.targets'
4:52:57 PM whcampus-test-fcn: Copying file: 'obj\project.assets.json'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\Release\netcoreapp2.1\HelloFunction2.AssemblyInfo.cs'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\Release\netcoreapp2.1\HelloFunction2.AssemblyInfoInputs.cache'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\Release\netcoreapp2.1\HelloFunction2.assets.cache'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\Release\netcoreapp2.1\HelloFunction2.csproj.CopyComplete'
4:52:57 PM whcampus-test-fcn: Deleting file: 'obj\Release\netcoreapp2.1\HelloFunction2.csproj.CoreCompileInputs.cache'
4:52:57 PM whcampus-test-fcn: Omitting next output lines...
4:52:58 PM whcampus-test-fcn: Finished successfully.
4:52:58 PM whcampus-test-fcn: Running post deployment command(s)...
4:52:59 PM whcampus-test-fcn: Syncing 0 function triggers with payload size 2 bytes successful.
4:52:59 PM whcampus-test-fcn: Deployment successful.
Deployment to "whcampus-test-fcn" completed.

**Comment by EricJizbaMSFT** [comment]
@argenacho can you copy the `.vscode/settings.json` file in the root of your repo? The default `azureFunctions.deploySubpath` setting should be something like `bin/Release/netcoreapp2.1/publish`, but it appears you're deploying the root of the workspace instead.

You can run "Initialize Project for use with VS Code" from the command palette (view -> Command palette) to change settings back to their defaults

**Comment by argenacho** [comment]
Hi, here are the file contents below. Looks pretty much like what you said:

{
  "azureFunctions.deploySubpath": "bin/Release/netcoreapp2.1/publish",
  "azureFunctions.projectLanguage": "C#",
  "azureFunctions.projectRuntime": "~2",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "publish"
}
I ran the  "Initialize Project for use with VS Code" and after that I was able to deploy correctly, though no visible changes appeared in my project.

I'm curious on why this didn't work out of the box. I'm going to create a new function from scratch and give it another try.

One more question: when I choose to deploy the function, I have to browse the folder of the function I want to deploy. What folder is that? root folder of the function project, or /bin/release/ ....?

Thanks again for looking at this!

**Comment by EricJizbaMSFT** [comment]
> One more question: when I choose to deploy the function, I have to browse the folder of the function I want to deploy. What folder is that? root folder of the function project, or /bin/release/ ....?

If deploySubpath is set, you shouldn't be asked for a folder and it should just deploy that folder
