### ISSUE TITLE
Failed to deploy path that does not exist

### ISSUE THREAD

**Issue by GJP123** [microsoft/vscode-azurefunctions#1419]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\britgp1-dev\prj\AzDev\testTest\bin\Release\netcoreapp2.1\publish

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
@GJP123 please add repro steps
