### ISSUE TITLE
reporting error deploying azure function

### ISSUE THREAD

**Issue by donniekerr** [microsoft/vscode-azurefunctions#1423]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: An error has occurred.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:332:396699
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.EventEmitter.emit domain.js:442:20
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
$.EventEmitter.emit domain.js:442:20
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
IncomingMessage.EventEmitter.emit domain.js:442:20
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@donniekerr please add repro steps

**Comment by thetre97** [comment]
@EricJizbaMSFT 

I get the same error by simply going to the extension, right clicking on a function app, and selecting 'Deploy to function app...'. When viewing the output, it shows this.

```bash
12:24:29 PM trustsertus: Creating zip package...
12:24:43 PM trustsertus: Starting deployment...
12:24:44 PM trustsertus: Uploading zip package to storage container...
12:25:16 PM trustsertus: Syncing triggers...
12:25:22 PM trustsertus: Syncing triggers (Attempt 2/6)...
12:25:36 PM trustsertus: Syncing triggers (Attempt 3/6)...
12:25:57 PM trustsertus: Syncing triggers (Attempt 4/6)...
12:26:38 PM trustsertus: Syncing triggers (Attempt 5/6)...
12:28:09 PM trustsertus: Syncing triggers (Attempt 6/6)...
Error: Failed with code "404".
```

**Comment by EricJizbaMSFT** [comment]
@thetre97 I still need more information - like
1. How did you create the function app? Throught VS Code or the portal?
1. Is it a linux/windows function app?
1. Is it a consumption or dedicated plan?
1. What type of project are you deploying and how did you create the project?

**Comment by thetre97** [comment]
1) Created this through the VSCode extension (right click on subscription, select 'Create FunctionApp in Azure').
2) Linux Function App
3) Consumption Plan
4) Javascript project, v2, created through the extension (via 'Create new project').

There are two functions - an Http trigger, and a Timer trigger - I believe it is the timer trigger causing the issue, as have never seen this issue with purely http trigger projects before.

I had also tried deploying with the `func` cli, and had the exact same issue.

I actually managed to get the project to deploy, by deleting the function app, and then creating a new one. Deploying then worked fine. Not an optimal solution though.

**Comment by EricJizbaMSFT** [comment]
@thetre97 if you can get concrete repro steps let me know. It's entirely possible that new function apps have some sort of fix that doesn't automatically get applied to old function apps. Linux consumption plans are still in preview and hopefully this less than optimal solution won't be necessary after they GA
