### ISSUE TITLE
Error while deploying azure function app

### ISSUE THREAD

**Issue by Pratikraut18** [microsoft/vscode-azurefunctions#1435]
Repro steps:

1. Create function from visual studio code
2. Deploy same function on azure portal

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND otiftestfunctio8629.blob.core.windows.net otiftestfunctio8629.blob.core.windows.net:443

Version: 0.17.1
OS: linux
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:50:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Pratikraut18 can you add more detailed repro steps - for example:
1. What is your project language?
1. How did you create the function app in Azure?
1. What do you mean "Deploy on azure portal"?
