### ISSUE TITLE
Azure Functions Project Detected (repeatedly)

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-azurefunctions#1437]
I keep getting this alert - "Detected an Azure Functions Project in folder "AyafiProject" that may have been created outside of VS Code. Initialize for optimal use with VS Code?"

I say yes every time, but it never sticks. Any suggestions?

**Comment by EricJizbaMSFT** [comment]
@aronchick that check looks for the VS Code settings "azureFunctions.projectLanguage" and "azureFunctions.projectRuntime" to make sure they're defined. After you click "Yes", it should create a ".vscode" folder with at least "settings.json" containing those settings.

Is it creating that folder? Also make sure it's not listed in gitignore - if it is you might be deleting it every time if you clean your repo.

**Comment by aronchick** [comment]
Yep, all there --

```
username@COMPUTERNAME:~/AyafiProject$ ls -la
total 0
drwxrwxrwx 1 username username 4096 Aug  6 11:43 .
drwxr-xr-x 1 username username 4096 Aug  6 10:23 ..
-rw-rw-rw- 1 username username  142 Aug  6 11:43 .code-workspace.code-workspace
-rw-rw-rw- 1 username username  412 Aug  6 13:40 .gitignore
drwxrwxrwx 1 username username 4096 Jul 14 19:29 .vscode
-rw-rw-rw- 1 username username  150 Jul 13 13:27 host.json
-rw-rw-rw- 1 username username  138 Jul 13 12:36 local.settings.json
drwxrwxrwx 1 username username 4096 Jul 13 19:22 pages
-rw-rw-rw- 1 username username    0 Jul 13 12:36 requirements.txt
username@COMPUTERNAME:~/AyafiProject$ ls -la .vscode/
total 0
drwxrwxrwx 1 username username 4096 Jul 14 19:29 .
drwxrwxrwx 1 username username 4096 Aug  6 11:43 ..
-rw-rw-rw- 1 username username   97 Aug  6 13:40 extensions.json
-rw-rw-rw- 1 username username  221 Aug  6 13:40 launch.json
-rw-rw-rw- 1 username username  322 Aug  6 13:40 settings.json
-rw-rw-rw- 1 username username  174 Aug  6 13:40 tasks.json
username@COMPUTERNAME:~/AyafiProject$ more .vscode/settings.json
{
    "python.pythonPath": "/usr/bin/python3",
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "azureFunctions.deploySubpath": "AyafiProject.zip",
    "azureFunctions.projectLanguage": "Python",
    "azureFunctions.projectRuntime": "~2",
    "azureFunctions.preDeployTask": "func: pack"
```

**Comment by EricJizbaMSFT** [comment]
@aronchick can you post a screenshot of your workspace? Is it a standard workspace or a multi-root workspace (asking since I see a "code-workspace" file)

**Comment by aronchick** [comment]
sure! what screenshot would you like?

This? 

![image](https://user-images.githubusercontent.com/51317/62836219-d2e3f280-bc15-11e9-93b4-c12b6e4ee9fe.png)

**Comment by EricJizbaMSFT** [comment]
@aronchick I've tried everything to duplicate your environment (wsl, using a "code-workspace" file, same folder name haha, etc.) and I can't repro
![Screen Shot 2019-08-29 at 10 43 16 AM](https://user-images.githubusercontent.com/11282622/63963454-eda5cc00-ca49-11e9-88bf-2eee671d41fa.png)

Perhaps you've fixed this by now? Also if you don't need the functions stuff you should be able to just click "Don't warn again" and never see the prompt

**Comment by aronchick** [comment]
Feel free to close - I'll reopen if I find it.
________________________________
