### ISSUE TITLE
Error creating Azure Function from IoTHubTrigger

### ISSUE THREAD

**Issue by gusanche** [microsoft/vscode-azurefunctions#1438]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:57:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@gusanche please add repro steps
