### ISSUE TITLE
Suddenly Azure python function can't find local files.

### ISSUE THREAD

**Issue by anindya5** [microsoft/vscode-azurefunctions#1439]
In my deployment I had few files the function need to read and was placed in the function parent folder. The code still work smoothly in local and before Sunday on the deployed version as well. Suddenly it started failing.

Based on research, added '/home/site/wwwroot/FunctionName/FileName' as the path, and put the files in function folder. Deployed and it was working only to have it again stop working with a File not found error again in afternoon.

**Comment by EricJizbaMSFT** [comment]
@anindya5 I'm a little confused by your scenario. Can you post a screenshot of your workspace? And what are you using that `/home/site/...` path for?

Also:
- What is your project language?
- How did you create your project?
- How did you create your function app in Azure?

**Comment by anindya5** [comment]
My folder structure is say

```
AzureFunctionName
......file1.csv
......Function1
       ......__init.py__
.....Function2
       ......__init.py__
```

Previously, if in  __init.py__ if I write `pd.read_csv('file1.csv')` it used to read seamlessly. Now, we have to put the file inside the particular function and then use '/home/site/wwwroot/HardwareHelperBeta/file1.csv' for function to read it.

The old file structure works for local debugging but start failing suddenly after new update in deployment.

The new folder structure that works:-

```
AzureFunctionName
......Function1
       ......__init.py__
       ......file1.csv
.....Function2
       ......__init.py__
```

along with 
`pd.read_csv('/home/site/wwwroot/HardwareHelperBeta/file1.csv' )`

**Comment by EricJizbaMSFT** [comment]
@anindya5 yeah I would advise against using the absolute path like that. It could possibly change in the future. Something like this should work and be more reliable:

```
function_dir = os.path.dirname(os.path.realpath(__file__))
csv_path = os.path.join(function_dir, 'file1.csv')
data = pd.read_csv(csv_path)
```

Taken from here: https://stackoverflow.com/questions/4934806/how-can-i-find-scripts-directory-with-python

**Comment by EricJizbaMSFT** [comment]
Closing this issue as the code change above should fix it for you. If it doesn't feel free to reopen with more details

**Comment by anindya5** [comment]
That would be ideal, but as far i remembered it did not work previously. Will cehck again
