### ISSUE TITLE
Docker-based function app Encountered an error (InternalServerError) from host runtime

### ISSUE THREAD

**Issue by bukarev** [microsoft/vscode-azurefunctions#1445]
I'm working with an Docker-based Python function app on B1 linux service plan in Australia East. It was working well until today, when it stopped.
When I click on a function name in the function app blade, there is a small popup window with error "The function runtime is unable to start. ". If I try to navigate to Manage part of a function, there is also a second popup window with message "Encountered an error (InternalServerError) from host runtime. "
The app still works fine in debugging mode, deployment process doesn't indicate any errors, and function app shows in the portal as Running and Available.
I tried to delete, recreate and redeploy the whole app, but to no avail.
Are there any logs I can check?

**Comment by bukarev** [comment]
Alright. I deleted the func app, service plan, and purged the associated storage account, then redeployed everything. Then it started working well. Is it how it's supposed to be?

**Comment by EricJizbaMSFT** [comment]
@bukarev Typically `InternalServerError` stems from a problem on the platform side, not VS Code. Let me know if you can get consistent repro steps from VS Code and I can investigate. The platform team actually just just announced GA of Python and Linux Consumption (see [here](https://twitter.com/AzureFunctions/status/1163511532417765376)) so hopefully it should be more reliable now anyways

**Comment by bukarev** [comment]
Let's close it for now, as I did a couple of successful redeployments of the Function App in question after I purged the associated storage account.
