### ISSUE TITLE
Remote build does not work when creating a new Linux Consumption function app

### ISSUE THREAD

**Issue by Hazhzeng** [microsoft/vscode-azurefunctions#1450]
Version:
Release candidate: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8861

Repro:
https://docs.microsoft.com/en-us/azure/azure-functions/tutorial-vs-code-serverless-python#deploy-to-azure-functions

Will receive
```
Creating resource group "maiqbalgatestappwestus" in location "westus"...
Successfully created resource group "maiqbalgatestappwestus".
Creating storage account "maiqbalgatestappwestus" in location "westus" with sku "Standard_LRS"...
Successfully created storage account "maiqbalgatestappwestus".
Verifying that Application Insights is available for this location...
Creating new Application Insights resource "maiqbalGaTestAppWestUS"...
Created new Application Insights resource "maiqbalgatestappwestus"...
Creating new function app "maiqbalGaTestAppWestUS"...
3:46:01 PM maiqbalGaTestAppWestUS: Starting deployment...
Error: Failed with code "401"
```

**Comment by EricJizbaMSFT** [comment]
@Hazhzeng does it work if you enable server side build with these steps?: https://aka.ms/AA5vsfd

**Comment by Hazhzeng** [comment]
@EricJizbaMSFT
So there are two different issues here, both are related to **Linux Consumption**:
1. The server side build fails if we try to deploy to a new Linux Consumption Python function app.
![image](https://user-images.githubusercontent.com/48038149/63204986-9a4b7b00-c052-11e9-952b-3cbd5c6e6544.png), it will receive 401 from api/zipdeploy endpoint
2. The default scenario in the [tutorial ](https://docs.microsoft.com/en-us/azure/azure-functions/tutorial-vs-code-serverless-python) does not work. It will attempt to use api/zipdeploy endpoint for deployment and will receive 401 from api/zipdeploy endpoint

**Comment by EricJizbaMSFT** [comment]
@Hazhzeng I think I know what's going on here. Should have a fix soon

**Comment by Hazhzeng** [comment]
Thanks @EricJizbaMSFT, much appreciated 👍
