### ISSUE TITLE
Functions host is no longer running.

### ISSUE THREAD

**Issue by thamilarasinataraj** [microsoft/vscode-azurefunctions#1452]
Repro steps:

1.While running Azure functions locally
2.Functions host is no longer running.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:390:88911extension.bundle.js:390:88911
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@thamilarasinataraj is there any output from the "func host" task with errors? Does this happen consistently?

Also try updating to v0.18.0 which was just released today. It includes some changes that might help with this
