### ISSUE TITLE
LocalGit Deployment to Azure Functions app (Linux Consumption Plan) fails

### ISSUE THREAD

**Issue by rcarmo** [microsoft/vscode-azurefunctions#1457]
Repro steps:

1. Create an Azure Functions App (Python, Linux Consumption Plan)
2. Configure it for LocalGit deployment
3. Try to deploy using VSCode

Action: azureFunctions.deploy
Error type: Error
Error Message: fatal: repository 'https://$foo-functions:***@foo-functions.scm.azurewebsites.net:443/foo-functions.git/' not found

Version: 0.18.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:331:354725
a extension.bundle.js:331:354365
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rcarmo yeah I'm honestly not sure if Linux Consumption supports local git deployment

**Comment by EricJizbaMSFT** [comment]
Yeah the portal doesn't even let you change deployment type to local git. We should probably just create a better error message for this until Azure supports it
