### ISSUE TITLE
fail deploy

### ISSUE THREAD

**Issue by TNP-artem** [microsoft/vscode-azurefunctions#1459]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.18.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.afterWrite [as oncomplete] net.js:788:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@TNP-artem please add repro steps
