### ISSUE TITLE
"command 'azureFunctions.refresh' not found" and similar errors

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode-azurefunctions#146]
All of the commands on the Azure Functions (and Azure CosmosDB!) give similar errors.  Here's having pushed the refresh button on the panel tools:

![image](https://user-images.githubusercontent.com/17498172/34358344-e4b57636-ea1c-11e7-9195-8f3935ca88f2.png)

i have node v8.9.3, Azure CLI-Tools, Azure Functions, Azure CosmosDB installed.  I am running the Cosmos DB local emulator.

I am also having this issue with my installation generally - it might all be related.  I suspect a missing dependency or something but I don't know what it is!  https://stackoverflow.com/questions/47970988/azure-functions-locally-the-system-cannot-find-the-file-specified-during-types

**Comment by EricJizbaMSFT** [comment]
Do you have the azure account extension installed? https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account

It's a dependency of all our azure extensions, but it should have been installed for you (assuming you installed these extensions from the VS Code marketplace).

**Comment by JasonKleban** [comment]
I did install this through the vs code "install" button.  `ms-vscode.azure-account` is not installed.  After installation, it does seem like the behavior is different.  Thanks.
