### ISSUE TITLE
Can deploy azure function to Azure

### ISSUE THREAD

**Issue by sufham** [microsoft/vscode-azurefunctions#1463]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.t extension.bundle.js:361:89170
u.fire extensionHostProcess.js:50:207
k.<anonymous> extensionHostProcess.js:659:390
o extensionHostProcess.js:13:812
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sufham check the output of the "clean" task to see if you had any errors that need addressing. Otherwise, please add repro steps to this issue
