### ISSUE TITLE
[Suggestion] Show the latest installed extension even though it has been hidden

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1466]
**OS:** Win10 & Mac
**Build Version**: [20190826.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9174)
**Regression:** Not a Regression

**Repro Steps:**
1. Install Azure Functions Extension.
2. Navigate to "Azure" tab --> Right Click "AZURE: FUNCTIONS " and uncheck it to hide the extension.
3. Re-install Azure Functions Extension.
4. Check whether the latest installed extension shows in "Azure" tab or not.

**Actual:**
Azure Functions Explorer doesn't show.

**Suggestion:**
Show the latest installed extension.

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. This is controlled by VS Code and we don't view uninstall/reinstall scenarios as high enough priority to fix

**Comment by v-dantch** [comment]
Got it.
