### ISSUE TITLE
[Suggestion]Add a new dialog when deploying projects to function apps at the first time

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1469]
**OS:** Win10 & Mac
**Build Version**: [20190826.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9174)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new function app.
2. Open a project in VS Code.
3. Right click the new function app --> Select "Deploy to Function App...".
4. Pop up a dialog --> Check the content.

**Actual:**
Pop up below dialog and tell the users that this action will overwrite any previous deployment and cannot be undone. But the actual is that there is no any deployment for the new function app.
![image](https://user-images.githubusercontent.com/34729092/63763051-8b888200-c8f6-11e9-83c7-e31bc833024d.png)

**Suggestion:**
Add a judge for deploying. Only asking the users whether want to deploy or not for a new function app at the first time. Does it make sense?

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. The only downside is they might have to click "Deploy" one extra time. If we tried to fix this, the downside is we might not detect correctly if they have a previous deployment and that could cause data loss if we don't prompt

**Comment by v-dantch** [comment]
Got it.
