### ISSUE TITLE
Encountered an error (ServiceUnavailable) from host runtime.

### ISSUE THREAD

**Issue by harshavardhan001** [microsoft/vscode-azurefunctions#1474]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:218:2795621
s extension.bundle.js:218:110861
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:164:644607
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:626255
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5443
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18256
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17098
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by tonghuikang** [comment]
same, but mine is working now

**Comment by EricJizbaMSFT** [comment]
Yeah if either of you can get consistent repro steps for this that would be very helpful. We see this occasionally, but usually it's fixed by just trying again. It's a [somewhat common issue](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503) in Azure that is affected by what App Service plan you're running on.

We should investigate improving this from our side - maybe automatically re-trying a few times if we see this type of error

**Comment by tonghuikang** [comment]
For me, it has not worked for 4 hours again :(

I could not really debug because I am chose Linux OS, and error 503s does not appear on the logs

**Comment by EricJizbaMSFT** [comment]
@tonghuikang I would recommend following one of the resources listed here to get help directly from the platform: https://github.com/Azure/Azure-Functions#questions--help

They will have more information specific to your function app that we don't have working on VS Code

**Comment by EricJizbaMSFT** [comment]
Let us know if that helps and what you did
