### ISSUE TITLE
Creating new python function app project failed on UNC paths

### ISSUE THREAD

**Issue by JackHartCNB** [microsoft/vscode-azurefunctions#1475]
Repro steps:

1. try to create new python azure function app project

2.  Running command: "py -3.6 -m venv .venv"...
'\\CNFCNPL40E\ISHomeDir02\<userID>\My Documents\dev\python\incapsula-token-app'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Error: [WinError 5] Access is denied: 'C:\\Windows\\.venv'
Error: Failed to run "py -3.6" command. Check output window for more details.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "py -3.6" command. Check output window for more details.

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135603
o extension.bundle.js:1:134668
```

</details>

**Comment by EricJizbaMSFT** [comment]
@JackHartCNB looks like VS Code doesn't support this by default and you have to follow a few extra steps to make it work. See https://github.com/Microsoft/vscode/issues/22872#issuecomment-288240595
