### ISSUE TITLE
virtual environment create fails while creating python Azure functions

### ISSUE THREAD

**Issue by thamilarasinataraj** [microsoft/vscode-azurefunctions#1477]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python" command. Check output window for more details.

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135603
o extension.bundle.js:1:134668
```

</details>

output window

Error: Command '['e:\\SampleApps\\Azure Function\\Nestle_APIs\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: Failed to run "python" command. Check output window for more details.

**Comment by EricJizbaMSFT** [comment]
@thamilarasinataraj you can skip creating a virtual environment by changing the `azureFunctions.createPythonVenv` to `false` if you want. Ultimately I think you'll have to figure out what is causing that command to fail in the output. I'm guessing you would see the same error if you ran the command manually from the terminal
