### ISSUE TITLE
Python azure function won't deploy due to datalake store not found error.  

### ISSUE THREAD

**Issue by Manofdesign** [microsoft/vscode-azurefunctions#1479]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND pacdatalakestore.blob.core.windows.net pacdatalakestore.blob.core.windows.net:443

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:57:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Manofdesign please add repro steps
