### ISSUE TITLE
Put browse to the last option

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#148]
I'm considering when we need to select folder in some actions, will it be better if we put the workspacefolder as the default option?

Now the select dialog is:
![image](https://user-images.githubusercontent.com/6193897/34508853-16d73f4c-f07f-11e7-9658-13a172315ca4.png)

While I think in most cases the users tend to select current workspacefolder directly.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime thoughts? I'm fine with this change

**Comment by fiveisprime** [comment]
I'm more than fine with it. :shipit:
