### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sunyreza** [microsoft/vscode-azurefunctions#1481]
- Issue Type: `Performance`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `0.18.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.38.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sunyreza\ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by EricJizbaMSFT** [comment]
@sunyreza please attach the cpuprofile.txt file as described in the comment above

**Comment by twentytwokhz** [comment]
It could be related to this issue...so I'm writing here.
When debugging azure functions in VS Code I get a crash every two debug sessions and it's incredibly frustrating. 
I tried checking for new updates of VS Code as well as the azure functions core tools. 
It didn't help.

Please investigate this issue!

**Comment by EricJizbaMSFT** [comment]
@twentytwokhz this is somewhat of a known issue, but we're looking for help diagnosing the root cause. Please try the setting mentioned in this comment and add to that thread with any findings: https://github.com/microsoft/vscode-azurefunctions/issues/1401#issuecomment-541936242
