### ISSUE TITLE
azureFunctions.deploy 403 error

### ISSUE THREAD

**Issue by Herman-Wu** [microsoft/vscode-azurefunctions#1484]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.18.1
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.39.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:218:501110
s extension.bundle.js:218:110861
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:164:644607
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:626255
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5443
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18256
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17098
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by Herman-Wu** [comment]
Use Advanced deployment  and it successed . It's a Java Function.

**Comment by EricJizbaMSFT** [comment]
@Herman-Wu could you tell me what options you selected in advanced deployment? We select several defaults for you in the "basic" deployment and it's possible you just didn't have permissions for one of the defaults in your subscription
