### ISSUE TITLE
Support "Add Binding..." for C#

### ISSUE THREAD

**Issue by wonderplayer** [microsoft/vscode-azurefunctions#1485]
Repro steps:

1. Create new function
2. Add extension bundle to host.json file as written in here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles
3. Try to add binding with Ctrl+P -> Azure functions: Add binding...  in function file

Action: azureFunctions.addBinding
Error type: Error
Error Message: No matching resources found.

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:1:622502
o extension.bundle.js:1:617043
```

</details>

**Comment by EricJizbaMSFT** [comment]
@wonderplayer what language is your project? Can you send a screenshot of your workspace so that I can see what the file structure looks like?

**Comment by wonderplayer** [comment]
Language, C#
![Annotation 2019-09-16 140249](https://user-images.githubusercontent.com/15668343/64956386-b8dba680-d88a-11e9-945b-d16e0a727590.png)

**Comment by EricJizbaMSFT** [comment]
@wonderplayer ah that explains it. The "Add Binding" feature doesn't support C# yet

**Comment by wonderplayer** [comment]
Ok, I see. Thank you :)
