### ISSUE TITLE
Add support for Azure Functions 3.0

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1489]
https://github.com/Azure/app-service-announcements/issues/200

**Comment by EricJizbaMSFT** [comment]
_From @ColbyTresness in https://github.com/microsoft/vscode-azurefunctions/issues/1546_:
> Per email:
> 
> •	Whenever anyone opens the extension, check their core tools version
> •	If V3, use V3, if V1, use V1. Nothing complex here
> •	If V2, show info bubble about V3, with a forward link to a doc explaining how to update and the differences V3 provides. Until customer manually updates core tools version, use V2.
> •	Allow customers to preview V3 alongside V2 if they wish by leveraging dev containers. The doc referenced above should contain a link to instructions on how to set this up.

**Comment by fiveisprime** [comment]
Regarding this point:

>  If V2, show info bubble about V3, with a forward link to a doc explaining how to update and the differences V3 provides. Until customer manually updates core tools version, use V2.

Let's skip the notification until we have compelling guidance on why customers should upgrade to v3.

**Comment by EricJizbaMSFT** [comment]
Closing this as v3 support is basically done. Any remaining work should be covered by other issues:
https://github.com/microsoft/vscode-azurefunctions/labels/v3
