### ISSUE TITLE
Improve error message when trying to delete a function on a read-only app from command palette

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/vscode-azurefunctions#1491]
**Repro steps:**

1. Create function app (works)
2. Create function (works)
3. Delete function (Selecting Subscription works, Selecting Function App works, but then the error occurs)

**Observed behavior:**

After selecting the function app Visual Studio Code displays the error message "No matching resources found" in the lower right corner. No function to delete can be chosen.

**Expected behavior:**

I can select the function to delete.

**More Info (generated by choosing "Report an issue" in the error message):**

Action: azureFunctions.deleteFunction
Error type: Error
Error Message: No matching resources found.

Version: 0.18.1
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.39.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
RemoteFunctionsTreeItem.<anonymous> extension.bundle.js:1:622502
o extension.bundle.js:1:617043
```

</details>

**Comment by EricJizbaMSFT** [comment]
If you look at the Function App in the tree view - does it say "Read Only" on the "Functions" node? If so, that means your app is in ["Run From Package"](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package) mode which has several benefits, but means you can't edit your app (including deleting a function) without doing a full re-deploy.

![Screen Shot 2019-09-16 at 1 47 01 PM](https://user-images.githubusercontent.com/11282622/64992316-7ca74680-d888-11e9-9fa7-698123c574f1.png)

All that being said, the error message we display here could definitely be better

**Comment by heinrich-ulbricht** [comment]
@EricJizbaMSFT Yes, it does. So the problem is actually a misleading error message. Good to know and good new issue title.
