### ISSUE TITLE
There is an error in functions node for Linux function App 

### ISSUE THREAD

**Issue by v-weigu** [microsoft/vscode-azurefunctions#1495]
**OS**: Windows
**Build Version**: [20190917.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10055)
**Regression**: Not a Regression

**Repro Steps**:
1. Create a Function App with Linux OS.
2. Expand the "Functions" node and check it.

**Expect**:
The functions node is expanded successfully without any error.

**Actual**:
The functions node is expanded successfully with an error.
![image](https://user-images.githubusercontent.com/55121584/65125984-0a219c80-da29-11e9-88b5-a7da5a777e8e.png)

**More Info**:
This issue reproduces on all runtime(Javascript/.NET/Python).

**Comment by v-dantch** [comment]
More Info:
There is no error after deploying a project to a Linux function app.
![image](https://user-images.githubusercontent.com/34729092/65210363-82419e00-dacd-11e9-9869-63ba0fb257be.png)

**Comment by EricJizbaMSFT** [comment]
@jeffhollan @ColbyTresness we see InternalServerError and ServiceUnavailable somewhat frequently reported. Any tips or tricks to avoid those types of errors?

**Comment by ColbyTresness** [comment]
@dariagrigoriu, this is a linux platform question

**Comment by EricJizbaMSFT** [comment]
This should be mitigated in https://github.com/microsoft/vscode-azurefunctions/pull/1536 - seems like retrying listing the triggers after a deploy will help. If the user hits this error unrelated to a deploy (aka if they manually open the tree some other time), it'll likely be fixed by just refreshing the node.
