### ISSUE TITLE
Miss the "Back" button when creating a new function app with the latest VS Code Insiders

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1498]
**OS**: Win10
**Build Version:** [20190917.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10055)

**Repro Steps:**
1. F1 --> Type and select "Azure Functions: Create Function App in Azure...".
2. Enter a valid name --> Press "Enter" to next.
3. Check whether there is a "Back" button or not.

**Expect:**
There is a "Back" button.

**Actual:**
No "Back" button displays.
![image](https://user-images.githubusercontent.com/34729092/65234152-a372b080-db06-11e9-90bb-6b876b49ff08.png)

**More Info:**

1. This issue reproduces on the latest and preview release builds with the latest VS Code Insiders 1.39.0-insider(user setup).
2. This issue DOES NOT reproduce on the latest VS Code 1.38.1 (user setup).
3. There is a similar bug [1159 ](https://github.com/microsoft/vscode-azureappservice/issues/1159)in App Service Extension.
4. There is still no "Back" button when creating a new project.
![image](https://user-images.githubusercontent.com/34729092/65234232-c43b0600-db06-11e9-99af-9ad8d308f25b.png)
5. Pop up below error when canceling to create a new project with below error.
![image](https://user-images.githubusercontent.com/34729092/65234270-d61ca900-db06-11e9-8fc3-6a858e2a54b3.png)

**Comment by EricJizbaMSFT** [comment]
Likely fixed in https://github.com/microsoft/vscode/issues/81142

Need to try tomorrow's insider build of VS Code

**Comment by v-dantch** [comment]
Verified on Windows and Mac with the latest VS Code - Insiders, this issue doesn't reproduce. So close this bug for now.

**VS Code -Insiders Info:**
Version: 1.39.0-insider (user setup)
Commit: 817eb6b0c720a4ecbc13c020afbbebfed667aa09
Date: 2019-09-25T05:28:51.690Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
