### ISSUE TITLE
Installing python and / or azure functions extensions crashes vs code

### ISSUE THREAD

**Issue by JackHartCNB** [microsoft/vscode-azurefunctions#1501]
I'm following the steps in "Create your first function in azure using visual studio code" (https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code).

When I install the python extension or the azure functions extension, if I open a python source file (the python source file I'm using is from the tutorial), my vs code app crashes.  Once this has happened, anytime I open a python source file the app crashes.  The only way I've found to stop the crashing is to uninstall vs code from "Programs and Features", and then delete all remnants as described in this page: https://superuser.com/questions/1380208/how-to-completely-uninstall-visual-studio-code-from-windows-10

After I do that, I also have to go to my function app project and delete the .vscode directory there and then reinstall.  Once I've reinstalled, vs code will be stable, until I add either the python extension or the azure functions extension and open a python source file. Once I do that, it crashes again.  

Is there a way to make this work or is it just broken?

**Comment by JackHartCNB** [comment]
Since these plugins are crashing my editor, can you please recommend another way to publish my python azure function?  I will use another editor but given that this broken tool chain is the recommended means of publishing azure function apps, I will need an alternative until you are able to fix your software.  Thank you.

**Comment by fiveisprime** [comment]
As a workaround you can deploy from the Functions CLI. The steps for that are here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli

Next, we'll need some help understanding what's going on. Please disable all extensions (do this manually rather than from the CLI) then enable only the Azure Functions and Python extensions. Let me know if VS Code crashes with only those two enabled.

What platform and VS Code version are you on?

**Comment by JackHartCNB** [comment]
I've been trying to use the version installed by this installer: VSCodeUserSetup-x64-1.38.1 (6).exe

Unfortunately, the last time I uninstalled, cleaned up all the other things up as per the web page I originally listed and reinstalled, the vs code app wouldn't even start without crashing, even though I had not yet installed *any* extensions.

**Comment by JackHartCNB** [comment]
I did try disabling all the extensions (the python and the azure functions extensions) yesterday.  This didn't work and what did work was to fully uninstall, remove all the other things, reboot and then reinstall the app without installing any extensions.

**Comment by JackHartCNB** [comment]
My bad -- I forgot to delete the .vscode directory in my function app project.  I have the app up and it's not crashing at the moment when I open a python source file.  There are no extensions installed (system fully cleaned as per the above web page).  Please advise what info you need and how you'd like me to collect it, etc., thanks.

**Comment by fiveisprime** [comment]
Can you help me understand the crashing behavior? Typically when an extension fails, only the extension host crashes. This results in an error notification, but the window shouldn't crash.

When you install the extensions, how long does it take to crash? Does the CPU spike or is there any odd behavior on load?

The `.vscode` directory that you're talking about, is that in your workspace or in your home directory (global vs code config)? Can you share the contents of that directory when the crashing occurs?

Sorry for all the questions, I really want to understand what's going on here.

**Comment by JackHartCNB** [comment]
I've usually been installing the python extension first, and then installing the azure functions extension afterwards and the two of them in that order definitely crashes.  I

'm not sure which of these two (or the combination) is causing the problem but I just installed only the azure functions extension and so far the app hasn't crashed and I have been able to open my python source file successfully.  I'm guessing this tends to indicate that the problem may be with the python extension.  

There *is* one other extension installed (I just figured out how to query what's installed), it's the Azure Account extension.  Since the app hasn't crashed yet, can I leave this installed?  I'm willing to bet that if I install the python extension I'll see another crash, but so far with only the Azure functions and Azure Account extensions installed I'm not crashing.  Do you want me to try installing the python extension?  

Another question I have is will I be able to publish my function app having just the Azure Functions and Azure Account extensions installed, or does publishing require the Python extension?

**Comment by fiveisprime** [comment]
Yeah, the publish will work without the Python extension.

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65357079-d79fad00-dbaa-11e9-9329-efdd0db04d1d.png)

**Comment by JackHartCNB** [comment]
I also get offered the above "init for optimal use" notification shown above, and I *was* accepting the offer.  I also found just earlier this AM that I need to delete the .vscode folder in my function app project to fully uninstall and clean out the vs code installation after it starts crashing. Does the "Initialization for optimal use" create the .vscode directory in my project?

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65357277-73311d80-dbab-11e9-8efa-e3871c106e60.png)

**Comment by JackHartCNB** [comment]
Pretty sure one of the above 2 is the culprit (or perhaps the two of them together).  What do I need these for?  Do I need them?

**Comment by fiveisprime** [comment]
Yeah, that will create all the necessary config for the Functions extension to run and deploy the app. Does answering "Yes" to that cause a crash.

**Comment by fiveisprime** [comment]
Choose "Yes" to initialize the project (second prompt in your screenshot) and don't install the Python extension. See if it remains stable.

**Comment by JackHartCNB** [comment]
That notification went away, how do I init the project after that thing goes away?  I've been looking through the recommended extensions and various other places but I'm not seeing it

**Comment by fiveisprime** [comment]
The notifications collapse into the bell icon down in the bottom right, click that to show them after they have gone away.

**Comment by JackHartCNB** [comment]
OK, I installed it and...

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65358740-35ce8f00-dbaf-11e9-811d-ab865897a336.png)

**Comment by JackHartCNB** [comment]
After this happens, you can click "Close" and code exits.  Or you can click "Reopen" but as soon as it opens, it does and you get the above error dialog and this will go on until you change you mind and click Close.  

I just had an idea and let the app die and then went and deleted the .vscode directory in my project and now I can run the app without crashing again.

It looks like both python and project init for optimal use are broken, but if I can write a function in python and publish it without them that would be perhaps the best route at this point.  What do I need the project init for optimal use for?  Can I publish functions without it?

**Comment by fiveisprime** [comment]
The project init sets the deployment paths so it's required to deploy from the extension. :( You can deploy using the Functions CLI (from the article I linked above) without needing the config in `.vscode`.

Can you paste the content of the `.vscode` files (settings.json, tasks.json, etc..) to a [gist](https://gist.github.com) so I can try to reproduce this?

**Comment by JackHartCNB** [comment]
Sure, I'll send it to you but I need a way to make this work.  I'm trying to run this tutorial project locally (https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code) but I'm at the "Run the function locally" but I'm unable to start the function app project or set a breakpoint.  I need the python extension for this?  Or can I do this somehow without the python extentsion?

Also, I can publish with the CLI?  That will allow me to avoid the the "init the project" problem, but how do I run locally?

**Comment by JackHartCNB** [comment]
OK, I tried to get this auto-generated project going without installing the python extension, but even when I open up a bash terminal and try to execute the project directly, it doesn't seem to work, and I suspect that the project isn't getting set up properly because there's no pip install happening to pull in the azure.functions import.  

I zipped up my .vscode directory from the project folder and will attach it here.  Please let me know how I can run this code locally also.  I eventually realized that vs code doesn't seen to be able to properly run python within the editor so I installed the damn python extension and it worked for a minute but started crashing again when I tried to create a new projkect, super frustrating and I'm wasting time screwing around with this. 

[.vscode.zip](https://github.com/microsoft/vscode-azurefunctions/files/3637990/default.vscode.zip)

**Comment by JackHartCNB** [comment]
I can't sort out how to create a gist but I attached a zip file to the previous comment, let me know if that will work

**Comment by JackHartCNB** [comment]
Hi Matt,

See below for details…

**Comment by JackHartCNB** [comment]
From: Matt Hernandez <notifications@github.com>
Sorry for all the questions, I really want to understand what's going on here.

--------------------------------------

Please ask whatever is necessary to fix this – I’m making zero progress on what I’m supposed to be working on this is causing problematic delays.  Thanks,

--j

**Comment by JackHartCNB** [comment]
Hey Matt,

Thanks for the details.  So I get that I can publish from the command line, I’ll check out that article today.  However, I will need to be able to run my program locally also – don’t I need the python extension for that?

Can you advise on how to run my python function locally without the python extension?

--j

**Comment by JackHartCNB** [comment]
Hi Matt,

I've got a few steps further, I have now created an HTTP function and run it locally via the CLI.  Now I'm on this page:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python

I"m now trying to create a resource group by running this command:

az group create --name mobile-header-resource-group --location westus

When I run this, I get the following error:

Please run 'az login' to setup account.

When I run 'az login', it opens a page in my browser and I click on my email address to login.  See the screen below

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65467751-08841a00-de17-11e9-8374-66fc547bd73f.png)

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65467791-32d5d780-de17-11e9-9b6b-8f5781b33c5f.png)

**Comment by JackHartCNB** [comment]
However, when I run the 'az login' command and log in as shown above, I get an error in the cmd prompt "shell" that says this:

H:\dev\python\tutorial\mobile-header-app>az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

If I try to run the command to create the resource group again, it tells me to login again and the whole process repeats.

I also tried to create the resource group in the azure web console.  First, I clicked the icon/text for "Resource groups" under FAVORITES on the left hand side of the portal to get to the page for resource groups.  Note that I am logged in (see the banner showing my user in the upper right corner of the web console):

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65468905-66663100-de1a-11e9-9474-bcab2a27fe28.png)

**Comment by JackHartCNB** [comment]
However, when I click the blue "Create resource group" button in the middle of the page, it takes me to a page to "Create a free account".  WTF?  I'm already logged in to CNB's account, what is going on here?  See below for the page to create an account, even though I'm already in my company account:

**Comment by JackHartCNB** [comment]
![image](https://user-images.githubusercontent.com/47367831/65469063-eab8b400-de1a-11e9-9c5c-4e2336f04e64.png)

**Comment by ggailey777** [comment]
@JackHartCNB have you tried to to run the `az` commands in the Cloud Shell in [Azure portal](https://portal.azure.com) instead of from your local machine....
![image](https://user-images.githubusercontent.com/1388263/65827897-e856bf80-e249-11e9-8e33-4f5f123fcb44.png)
![image](https://user-images.githubusercontent.com/1388263/65827903-00c6da00-e24a-11e9-99fe-948863601e71.png)

**Comment by EricJizbaMSFT** [comment]
Closing - see https://github.com/microsoft/vscode-azurefunctions/issues/1519#issuecomment-599793164
