### ISSUE TITLE
Unable to run azure functions locally on VS Code

### ISSUE THREAD

**Issue by amed128** [microsoft/vscode-azurefunctions#1504]
Trying to run an HttpTrigger python function on VS Code.

**Repro Steps:**

- Installed python 3.6.8 and Vs Code 
- Downloaded Azure Functions and Python extensions in VS Code
- Installed Azure-Functions-Core-Tools V2
- Created a virtual environment in my project directory with "py -3.6 -m venv C:\..."
- Selected "Python: Select Interpreter" and created a terminal with "Python: Create Terminal" using the command palette
- Created an HttpTrigger function using "func new".

When I tried to debug or run with "func host start", the execution always blocks at this stage on the following screenshot:
![Capture0](https://user-images.githubusercontent.com/55672623/65396519-43e70000-dda7-11e9-8bf6-295ede79292d.JPG)

Uninstalling and re-installing VS Code did not change anything.
I have already tried the suggestions on the issues #1016 and #892 but still won't work.

Here is my launch.json file by default:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 7071,
            "preLaunchTask": "func: host start"
        }
    ]
}

And here is the tasks.json file:

{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "command": "host start",
            "problemMatcher": "$func-watch",
            "isBackground": true,
            "dependsOn": "pipInstall"
        },
        {
            "label": "pipInstall",
            "type": "shell",
            "osx": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "windows": {
                "command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
            },
            "linux": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "problemMatcher": []
        }
    ]
}

Here is the project directory created:
![Capture1](https://user-images.githubusercontent.com/55672623/65396673-084d3580-dda9-11e9-896b-7806fe8fab1d.JPG)

OS: Windows 10

**Comment by EricJizbaMSFT** [comment]
@amed128 are you manually running `func host start`? The tasks and launch config is set up to automatically run it for you when you debug and you shouldn't need to do that. I think I've seen that blank output when I'm running `func host start` on a machine that already has it running somewhere else

**Comment by amed128** [comment]
@EricJizbaMSFT Yes I was manually running **func host start** but I also tried to debug with **F5** and it's still not working.

**Comment by EricJizbaMSFT** [comment]
This used to happen when you have multiple `func host start` commands running at the same time, but now they display a better error message:
> Port 7071 is unavailable. Close the process using that port, or specify another port using --port [-p].

**Comment by Keerthana21** [comment]
I'm trying to fun "func start" but it throws me this error:

```
func : The term 'func' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ func host start
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (func:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
how can i fix this?
