### ISSUE TITLE
Incorrect terminal separator used by default on old versions of Windows

### ISSUE THREAD

**Issue by HoLue** [microsoft/vscode-azurefunctions#1505]
Repro steps:

1. Create Azure Functions python project
2. Create Function (HTTP trigger)
3. F5 -> Message: "You must have the Azure Functions Core Tools installed to debug your local functions."
But Azure Functions Core Tools are installed:  
```
c:\del>node -v
v10.15.3
c:\del>npm -v
6.4.1
c:\del>npm i -g azure-functions-core-tools --unsafe-perm true
C:\Users\HL\AppData\Roaming\npm\func -> C:\Users\HL\AppData\Roaming\npm\node_mod
ules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\azfun -> C:\Users\HL\AppData\Roaming\npm\node_mo
dules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\azurefunctions -> C:\Users\HL\AppData\Roaming\np
m\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.7.1585 postinstall C:\Users\HL\AppData\Roaming\np
m\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1585/Azure.Func
tions.Cli.win-x64.2.7.1585.zip"
[==================] Downloading Azure Functions Core Tools
+ azure-functions-core-tools@2.7.1585
updated 1 package in 50.091s

```
4. Reply to the Message (from 3.): Install. Then  select Azure functions V2

Next error message:  Failed to attach (connect ECONNREFUSED 127.0.0.1:9091)
Output in Terminal:
```
> Executing task: .venv\Scripts\python -m pip install -r requirements.txt <

You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Terminal will be reused by tasks, press any key to close it.

> Executing task: .venv\Scripts\activate ; func host start <

Parameterformat falsch - 850.
Terminal will be reused by tasks, press any key to close it.
```

Output in Output:
```
Running command: "npm install -g azure-functions-core-tools@2"...
C:\Users\HL\AppData\Roaming\npm\func -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\azfun -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\azurefunctions -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.7.1585 postinstall C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1585/Azure.Functions.Cli.win-x64.2.7.1585.zip"

+ azure-functions-core-tools@2.7.1585
updated 1 package in 50.729s
Finished running command: "npm install -g azure-functions-core-tools@2".
Running command: "npm install -g azure-functions-core-tools@2"...
C:\Users\HL\AppData\Roaming\npm\azurefunctions -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\azfun -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\HL\AppData\Roaming\npm\func -> C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.7.1585 postinstall C:\Users\HL\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1585/Azure.Functions.Cli.win-x64.2.7.1585.zip"

+ azure-functions-core-tools@2.7.1585
updated 1 package in 49.947s
Finished running command: "npm install -g azure-functions-core-tools@2".

```
5. Reply to the Message (from 4.): Open launch.json
File: launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9091,
      "preLaunchTask": "func: host start"
    }
  ]
}

```

Remark: I have installed Python 3.7 and 3.6 (3.6 because of Azure functions)

OS: Windows 7
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@HoLue what happens if you run `func --version`? Sometimes the func core tools is installed, but not set up correctly on your path. Here are a few links that might help if that's your problem:

https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found
https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

**Comment by HoLue** [comment]
@EricJizbaMSFT Thanks. I tried and first I put the path into the system environment path. Then 
func --version
gives: 2.7.1585
But the error as I described did not change. :-(

**Comment by EricJizbaMSFT** [comment]
Can you send the output of the `func host start` task after you fixed the path?

**Comment by HoLue** [comment]
D:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFunc> func host start
Python 3.6.x is required, and used in Azure Functions. You are using Python version Python 3.7.2. Please install Python 3.6, and use a virtual environment to switch to Python 3.6.

But: Actually I changed in the left hand bottom corner the python version to
"Python 3.6.8_64bit('.venv':venv)

**Comment by EricJizbaMSFT** [comment]
That setting comes directly from the python extension, but we use a different setting: `azureFunctions.pythonVenv`. You can manually change it in your `.vscode/settings.json` file 

We're debating consolidating the settings in https://github.com/microsoft/vscode-azurefunctions/issues/1393

**Comment by HoLue** [comment]
Thanks, but sorry I cannot fix it.... I read the link bt could not see a answeer fitting for me. I tried changing values in the .vscode/settings.json file without any success.

That's my settings.json (unchanged):
```
{
  "azureFunctions.deploySubpath": "AZ01_ServerlessFunc.zip",
  "azureFunctions.pythonVenv": ".venv",
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~2",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "func: pack",
  "python.pythonPath": ".venv\\Scripts\\python.exe"
}
```

The version of venv\\Scripts\\python.exe is 3.6.8150.1013 (product version 3.6.8). So this should be ok, shouldn't it?

**Comment by HoLue** [comment]
Perhaps it helps, deployment (blue up error) fails, too:
Failed to deploy path that does not exist: d:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFunc\AZ01_ServerlessFunc.zip

```
Object.<anonymous> extension.bundle.js:331:10173
o extension.bundle.js:331:9759
```

**Comment by EricJizbaMSFT** [comment]
> I tried changing values in the .vscode/settings.json file without any success.

Can you describe how it failed in this case? Was it the same error or different error?

**Comment by HoLue** [comment]
Yes, it was the same error:
I changed in  .vscode/settings.json:
```
 //"python.pythonPath": ".venv\\Scripts\\python.exe"
 "python.pythonPath": "c:\\Python36_64bit\\python.exe"

```
Terminal output:
```
> Executing task: .venv\Scripts\python -m pip install -r requirements.txt <

You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Terminal will be reused by tasks, press any key to close it.

> Executing task: .venv\Scripts\activate ; func host start <

Parameterformat falsch - 850.

Terminal will be reused by tasks, press any key to close it.
```
Error Message:
```
[Window Title]
Visual Studio Code

[Content]
Failed to attach (connect ECONNREFUSED 127.0.0.1:9091)

[Open launch.json] [Cancel]
```
Typing `func host start` as you said before:
```
D:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFunc>func host start
Python 3.6.x is required, and used in Azure Functions. You are using Python version Python 3.7.2. Please install Python 3.6, and use a virtual environment to switch to Python 3.6.

D:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFunc>
```

**Comment by HoLue** [comment]
One more remark: in launch.json some values are grey - I don't know if this is ok.
![ScreenshotLaunchJson](https://user-images.githubusercontent.com/55573836/65663091-1e235a80-e036-11e9-876a-2d8f03c199b9.jpg)

**Comment by EricJizbaMSFT** [comment]
This seems to be the error you need to fix:
> Parameterformat falsch - 850.

I would try searching to find a fix for that issue - here's one link I came up with: https://bugs.python.org/issue35148

The gray values are fine. Also typing `func host start` is expected to fail with that error unless you're in the virtual environment that is python 3.6

**Comment by HoLue** [comment]
I changed the activate.bat as described in https://github.com/python/cpython/commit/3c9c2dc8dde709a5f27c74aff1614d6ed3456964
Then the error `Parameterformat falsch - 850.` is solved (at least this message disappears) but the main error remains:

Terminal:
```
> Executing task: .venv\Scripts\python -m pip install -r requirements.txt <

You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Terminal will be reused by tasks, press any key to close it.

> Executing task: .venv\Scripts\activate ; func host start <


Terminal will be reused by tasks, press any key to close it.
```
Error Message:
```
[Window Title]
Visual Studio Code

[Content]
Failed to attach (connect ECONNREFUSED 127.0.0.1:9091)

[Open launch.json] [Cancel]

```

There seems to be another problem....

**Comment by EricJizbaMSFT** [comment]
You're going to keep getting connection refused until the "func host start" task works. Maybe try running `.venv\Scripts\activate ; func host start` manually and see if it displays any output (since your above output doesn't even have any errors)

**Comment by HoLue** [comment]
This seems to work:

```
D:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFu
nc>.venv\Scripts\activate ; func host start

(.venv) D:\Di\Z_InfosTestTry\Z_Programmier\Azure\AZ01_ServerlessFunc>

```

**Comment by EricJizbaMSFT** [comment]
Well it activates the virtual environment, but it never actually runs `func host start`

From an above screenshot, it looks like you're using cmd for your terminal, right? I believe the problem is that the task uses a PowerShell separator (`;`) instead of a cmd separator (`&&`). It's supposed to auto-detect that kind of stuff and use the correct separator. What's the value of your VS Code setting `terminal.integrated.shell.windows`?

**Comment by HoLue** [comment]
**That's it!! Thanks a lot!!**
I added the following line in my settings.json:
`  "terminal.integrated.shell.windows": "&&",
`
So the whole file settings.json is:
```
{
  "azureFunctions.deploySubpath": "AZ01_ServerlessFunc.zip",
  "azureFunctions.pythonVenv": ".venv",
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~2",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "func: pack",
  "terminal.integrated.shell.windows": "&&",
  "python.pythonPath": ".venv\\Scripts\\python.exe"
  //"python.pythonPath": "c:\\Python36_64bit\\python.exe"
}
```

**Comment by HoLue** [comment]
And - forgot to mention - it worked!!

**Comment by EricJizbaMSFT** [comment]
Huh well usually that setting is the _path_ to your terminal. Something like this:
```
C:\Windows\System32\cmd.exe
```

or this:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

Do you remember ever changing this setting? The above is your _workspace_ settings, but is it perhaps set in your _user_ settings? I'm just trying to figure out if there's a bug in our code

**Comment by HoLue** [comment]
Well, of course, both exist:
```
C:\Windows\System32\cmd.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```
But in which user setting can I search? 

I don't think I changed something.... I am using Windows 7, German, the only somehow special setting is that I choose the decimal separator '.' instead of the ',' which is typical (and default) for German.

**Comment by HoLue** [comment]
:-(
Now, I changed something simple (I installed datetime and want to output it, just to test installing and using a package). I tried to deploy and the the attached error / warning occured.
![VSCodeAzureDeploy](https://user-images.githubusercontent.com/55573836/65920996-276b4900-e3e1-11e9-8e8b-50f9fe803db1.jpg)

Seems to be once more something with a separator !? But how to solve?

**Comment by EricJizbaMSFT** [comment]
Take a look at these docs on the "terminal.integrated.shell.windows" setting: https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

Setting it to "&&" looks like the problem. It has to be a path to the terminal you want to use.

**Comment by EricJizbaMSFT** [comment]
It looks like VS Code defaults to "PowerShell" on Windows 10 and "cmd" on some earlier versions of Windows. We only tested on Windows 10 and probably have a bug we need to fix for prior versions. In the meantime, you should be able to work around the issue by setting "terminal.integrated.shell.windows" to "C:\\Windows\\System32\\cmd.exe" in your user settings as described in the above link.

**Comment by HoLue** [comment]
**Thanks!**

Both of the following possibilities are working with using a package.

Possibility A:
In settings.json of project add (or replace):
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"

Possibility B:
1) VS Code: Ctrl-Shift+P -> Terminal: Select Default Shell -> Select Command prompt: C:\Windows\System32\cmd.exe
2) In settings.json of project delete (or comment):
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"

**Comment by EricJizbaMSFT** [comment]
Awesome glad it's working now! In the meantime, I'll leave this issue open so that we can investigate default behavior on older versions of Windows

**Comment by HoLue** [comment]
Thanks for all!!!
