### ISSUE TITLE
debugger not working

### ISSUE THREAD

**Issue by jdschmitz15** [microsoft/vscode-azurefunctions#1507]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.18.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.t.pickFuncProcess.s.tasks.onDidEndTaskProcess.t extension.bundle.js:361:89170
u.fire extensionHostProcess.js:50:207
L.<anonymous> extensionHostProcess.js:711:727
o extensionHostProcess.js:13:918
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jdschmitz15 please check the output of the build task and address any errors from that
