### ISSUE TITLE
403 when deploying function app

### ISSUE THREAD

**Issue by jonathanlintott** [microsoft/vscode-azurefunctions#1510]
Repro steps:
1. Following instructions step-by-step given here https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-05
2. Error when finishing step "Deploy to Function App"

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:218:501110
s extension.bundle.js:218:110861
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:164:644607
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:626255
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5443
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18256
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17098
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jonathanlintott a few questions:
1. Does this error happen consistently for you? 
1. Does this error happen when it's creating a new function app or during the actual deploy?
1. Can you copy deploy logs here?

You're also welcome to try a new deployment method for Python projects as detailed here: https://github.com/microsoft/vscode-azurefunctions/wiki/Server-Side-Build

It's still in preview, but it addresses a few known issues with Python deployments and we hope to make it the default soon
