### ISSUE TITLE
Failed to attach (connect ECONNREFUSED 127.0.0.1:9095)

### ISSUE THREAD

**Issue by vefae** [microsoft/vscode-azurefunctions#1515]
Hi, I followed this tutorial to create and deploy Azure functions using VS code: https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-01
However, I received the error below at the 4th step (Debug the function code locally):

Failed to attach (connect ECONNREFUSED 127.0.0.1:9095)

I went through earlier Issues and proposed solutions, but could not solve the problem.

Details:
Python Extension: 2019.9.34911
Azure Functions: 0.18.1
Azure CLI Tools: 0.4.6

launch.json

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9095,
      "preLaunchTask": "func: host start"
    }
  ]
}
```

tasks.json

```

{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "pipInstall"
    },
    {
      "label": "pipInstall",
      "type": "shell",
      "osx": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "windows": {
        "command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
      },
      "linux": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "problemMatcher": []
    }
  ]
}
```

requirements.txt

`azure-functions`

**Comment by EricJizbaMSFT** [comment]
@vefae can you copy the output of the `func host start` task? Also what version of the func cli and python do you have?

**Comment by vefae** [comment]
Hi, @EricJizbaMSFT I figured out the problem. When I checked the output of the func host start:
```

 File C:\Users\Documents\WindowsPowerShell\profile.ps1 cannot be loaded because running scripts is disabled on this system. For more 
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```

So, I changed the execution policy from restricted to remotesigned and it works now.
