### ISSUE TITLE
Debugger not attaching when running via workspaces

### ISSUE THREAD

**Issue by meds** [microsoft/vscode-azurefunctions#1517]
I have a workspace set up with a few projects, one of which is an azure functions one with the following config:
```

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Compile in watch mode",
      "type": "node",
      "request": "launch",
      "preLaunchTask": "tsc"
    },
    {
      "name": "Attach to Node Functions",
      "type": "node",
      "request": "attach",
      "port": 9230,
      "preLaunchTask": "func: host start"
    },
    {
      "name": "Attach",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "processId": "${command:PickProcess}"
    },
  ],
  "compounds": [
    {
      "name": "Azure",
      "configurations": ["Attach to Node Functions"]
    }
  ]
}

```

When I run "Attach to Node Functions" in VSCode through the azure functions in workspaces the debugger does not attach (breakpints don't hit), there's a constant loading under the debug picker.

If I open the functions folder and run the same launch config it works fine and connects.

The terminal has no output indicating any errors.

**Comment by EricJizbaMSFT** [comment]
@meds perhaps this wiki page will help: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

It has examples on how best to run multiple projects in one workspace

**Comment by meds** [comment]
> @meds perhaps this wiki page will help: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects
> 
> It has examples on how best to run multiple projects in one workspace

Yes I did go through that, unfortunately no luck on my end. Really not sure what I'm doing wrong...

**Comment by meds** [comment]
ok I decided to wholesale copy the configs from your linked examples, it works great now with the debugger attaching through workspaces.

Unfortuantely I'm running typescript and having tsc -w running over the folder causes the functions to stop working when I change a function. Is there a way around this?

**Comment by EricJizbaMSFT** [comment]
There's a known issue where changing a file will stop the debug session. See the following:
https://github.com/microsoft/vscode-azurefunctions/issues/781
https://github.com/Azure/azure-functions-host/issues/3543

Unfortunately we don't have a solution yet

**Comment by meds** [comment]
> There's a known issue where changing a file will stop the debug session. See the following:
> #781
> [Azure/azure-functions-host#3543](https://github.com/Azure/azure-functions-host/issues/3543)
> 
> Unfortunately we don't have a solution yet

Ah, very curiously if you use the following task with tsc -w:

```
    {
      "type": "func",
      "command": "npm start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "npm build",
    },
    },
    {
      "type": "shell",
      "label": "npm build",
      "command": "npm run build",
      "dependsOn": [
        "func: extensions install",
      ],
      "problemMatcher": "$tsc"
    },
```

Run time recompiling works without crashing and the debugger does not disconnect.


That was my original task in the first post but it doesn't work in workspaces.

I'll post in that thread. If we could just fix workspaces debugger attaching with the config above it would solve all the problems.

**Comment by EricJizbaMSFT** [comment]
Closing in favor of the other linked issues
