### ISSUE TITLE
unable to login from CLI to publish azure function

### ISSUE THREAD

**Issue by JackHartCNB** [microsoft/vscode-azurefunctions#1518]
I'm trying to publish a very simple azure function using the CLI:

func azure functionapp publish mobile-header-fn-app

This results in an error:
"Unable to connect to Azure. Make sure you have the `az` CLI or `Az.Accounts` PowerShell module installed and logged in and try again"

I do have the CLI installed and I'm able to create functions projects (func init, func new), run my function locally (func start) but when I try to publish, I get the error above.

In response to the error above, I tried to run "az login" and I get the following error:
"az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))"

The browser does launch as advertised and I'm able to login via the browser, but if I re-run the publish command shown above, I just get the error shown above about "Unable to connect to Azure.  Make sure..." etc.

How do I get this to work?  Or is there another way to publish my function?

**Comment by EricJizbaMSFT** [comment]
If the browser isn't launched, you can try running `az login --use-device-code` to log in

If that still doesn't work, I recommend filing an issue directly on the func cli here: https://github.com/Azure/azure-functions-core-tools

For VS Code deploy, we'll use your other issue here: https://github.com/microsoft/vscode-azurefunctions/issues/1519
