### ISSUE TITLE
Error Message: connect ECONNREFUSED 127.0.0.1:10000

### ISSUE THREAD

**Issue by YacineYak95** [microsoft/vscode-azurefunctions#1521]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:10000

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@YacineYak95 please add repro steps
