### ISSUE TITLE
Azure function

### ISSUE THREAD

**Issue by DineshMohan0001** [microsoft/vscode-azurefunctions#1522]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '/home/dineshmohan/.config/libreoffice/4/.lock'

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@DineshMohan0001 please add repro steps
