### ISSUE TITLE
AzureWebJobsStorage value is blank in local.settings.json and will override value in Azure if local settings are uploaded

### ISSUE THREAD

**Issue by FISHMANPET** [microsoft/vscode-azurefunctions#1523]
I'm just getting started with Azure Functions, and I'm following [this tutorial](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-05).

Part of the tutorial it has you upload your local settings into Azure.  It appears that the local settings includes the key "AzureWebJobsStorage" but with an empty string as the value.  Following the tutorial I was able to overwrite the connection string in Azure this way.  I've already submitted feedback on that tutorial, but it seems like generally it shouldn't be possible to do that?  It looks like that value is required to be there to do local debugging so it shouldn't be omitted from local.settings.json when creating a new function, but perhaps there could be some safety checks around this particular value?  I was able to fix it by getting the connection string for the storage account which I found out how to do with [this closed issue in the function core tools project](https://github.com/Azure/azure-functions-core-tools/issues/1212#issuecomment-485517447).

I also found [this previous issue in this repo](https://github.com/microsoft/vscode-azurefunctions/issues/1340), I suspect the issue there as well was that they had overwritten the value for AzureWebJobsStorage in Azure with their blank value that was local.

**Comment by EricJizbaMSFT** [comment]
@FISHMANPET thanks for filing! I agree we should handle this situation better

This simplest option is to special-case `AzureWebJobsStorage` (and a few other well-known app settings) and skip uploading those if they are an empty string locally.

After we fix that, I feel like there's a few more edge cases we might want to discuss:
1. Should we _ever_ let users overwrite `AzureWebJobsStorage` on their remote function app? Aka what should we do if it's _not_ an empty string locally? (Today's experience will prompt to ask if they want to overwrite)
1. Should we always ignore empty app settings when uploading? We never delete app settings on the remote and we could debate whether or not changing it to an empty string equates to "deleting" an app setting

cc @fiveisprime

**Comment by fiveisprime** [comment]
imo..

1. Yeah, we should let customers overwrite the setting and prompt to ask if the want to overwrite
1. Yeah, ignore empty settings values
