### ISSUE TITLE
Function not showing up under Azure Function App though Server Side Build deployment was successfully done from VS Code

### ISSUE THREAD

**Issue by mbprodev** [microsoft/vscode-azurefunctions#1524]
I was getting some errors with python modules running the func: pack task during preDeploy task.
So, I have followed the directions to do Server Side Build following below link:
https://github.com/microsoft/vscode-azurefunctions/wiki/Server-Side-Build

When _'Deploy to Function App'_ runs, I get a message saying the Deployment to Function App was completed. However, on azure under the Function App I see that the function has not showed up. 
In the output terminal, below is the final message I get.
![image](https://user-images.githubusercontent.com/46756021/65795135-90c82f00-e137-11e9-83ee-e70ce6c647ce.png)

What does the above warning message mean? Could this be the reason the function does not show in the azure portal?

**Comment by EricJizbaMSFT** [comment]
@mbprodev there's a large variety of reasons why we might fail to list functions. It could be a problem with the project, the function app configuration in azure, a temporary outage, a timeout, etc. Try expanding the functions node under the function app and see if there's a more specific error there:
![Screen Shot 2019-09-27 at 3 51 07 PM](https://user-images.githubusercontent.com/11282622/65806495-a5f48c00-e13e-11e9-8fee-833263d79bbe.png)

You can see the deployment logs from under the Deployments node, but that will be the same exact logs that were printed as you deployed.

**Comment by mbprodev** [comment]
Thank you, the Deployment logs were helpful in finding the source of failure.
