### ISSUE TITLE
Win 10 Pro, Azure Functions Project in VS Code, WSL Ubuntu 18, can't create project

### ISSUE THREAD

**Issue by rttilghman** [microsoft/vscode-azurefunctions#1526]
Repro steps:

1.dotnet --version
3.0.100
2.VS Code, Installed Azure Functions Extension
3. New project
4. Home Directory
5. C#
6. No Functions are listed
7. Skip 
Error, Project not created, says I need dotnet 2.0
I can't downgrade, I tried from the command line, it refused to install old libraries, and 2.0 is end of life.. (duh?)

Action: azureFunctions.createFunction
Error type: Error
Error Message: Command "dotnet '/home/rttilghman/.vscode-server/extensions/ms-azuretools.vscode-azurefunctions-0.18.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/home/rttilghman/.vscode-server/data/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg' --require '/home/rttilghman/.vscode-server/data/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg' --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name 'rttilghman' --arg:AzureFunctionsVersion v2" failed with exit code "150":
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135637
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rttilghman that error isn't the most accurate - it should work with any 2.* version (aka 2.2 or 2.1)

We're tracking support for Azure Functions 3.0 and .NET Core 3.0 in https://github.com/microsoft/vscode-azurefunctions/issues/1489
