### ISSUE TITLE
trying to create a python function in VS Code on Mac

### ISSUE THREAD

**Issue by rlimberger** [microsoft/vscode-azurefunctions#1530]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3.7" command. Check output window for more details.

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135510
o extension.bundle.js:1:134575
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rlimberger please take a look at the output window for more details and add repro steps if you're still having issues
