### ISSUE TITLE
repotrt

### ISSUE THREAD

**Issue by VivekaR18** [microsoft/vscode-azurefunctions#1532]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to find preDeploy task "func : desk". Modify the setting "azureFunctions.preDeployTask" or add that task to tasks.json.

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:361:81122
o extension.bundle.js:361:79501
```

</details>

**Comment by EricJizbaMSFT** [comment]
@VivekaR18 please add repro steps. You're also welcome to try this preview feature, which no longer relies on the "func: pack" task: https://github.com/microsoft/vscode-azurefunctions/wiki/Server-Side-Build
