### ISSUE TITLE
Move (elastic) premium as a hosting plan option

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1544]
In the top level selection here:

![image](https://user-images.githubusercontent.com/1186948/66142314-0d389300-e5ba-11e9-9cb0-144ff9ebea9b.png)

Should be

- App Service Plan
- Consumption Plan
- Premium Plan

@ColbyTresness

**Comment by ColbyTresness** [comment]
If possible, I'd love to change the ordering above to:
* Consumption
* Premium
* App Service

**Comment by EricJizbaMSFT** [comment]
Note to self: the portal has a "preview" experience that's essentially what's described in this issue (that we can model after)
![Screen Shot 2019-10-03 at 2 29 48 PM](https://user-images.githubusercontent.com/11282622/66165794-68827980-e5ea-11e9-95b7-7a3e75841ee5.png)
![Screen Shot 2019-10-03 at 2 30 14 PM](https://user-images.githubusercontent.com/11282622/66165796-68827980-e5ea-11e9-994e-366403efbd40.png)
