### ISSUE TITLE
Better handle function apps created before remote build was released

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1548]
We need to better handle the situation when the user tries to deploy to a function app that doesn't support remote build (especially since that will be the default per https://github.com/microsoft/vscode-azurefunctions/issues/1541).

Right now they see "This operation is not supported by this app service plan."

**Comment by fiveisprime** [comment]
How about..?

> The Function app you are deploying to doesn't support your current build configuration. Downgrade your build configuration or deploy to a newly created Function app.

Cancel | Learn More | Downgrade Configuration

In the "learn more" link mention that this was changed in August 2019 and provide a recommendation. I believe deploying to a new app would be best, but there are cases where a downgrade makes sense.

Should it also provide an option to create a new app that would dump them into the create experience? That seems like overkill to me..

**Comment by EricJizbaMSFT** [comment]
Tweaked a bit:
> The selected Function App doesn\'t support your project\'s configuration. Deploy to a newer function app or downgrade your configuration.

A little shorter and honestly I never understood why this feature is called "build" in the first place. It's packaging up dependencies, not building anything.
