### ISSUE TITLE
Improve error message when execute function is not supported from command palette

### ISSUE THREAD

**Issue by pesabonsi** [microsoft/vscode-azurefunctions#1561]
Repro steps:

1.
2.

Action: azureFunctions.executeFunction
Error type: Error
Error Message: No matching resources found.

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
LocalFunctionsTreeItem.<anonymous> extension.bundle.js:1:622502
o extension.bundle.js:1:617043
```

</details>

**Comment by EricJizbaMSFT** [comment]
@pesabonsi we don't support execute function in a few scenarios:
1. For C#/Java projects
1. If you don't have a timer trigger

I've updated the title of the issue to improve the error message
