### ISSUE TITLE
Authn error when already authenticated in vs code

### ISSUE THREAD

**Issue by JackHartCNB** [microsoft/vscode-azurefunctions#1566]
Repro steps:

1. Set up ASE (mobile-header-fn-app-ase)
2. Turn on Express mode for AAD apps in App Service
3. Try to publish python function app
4. Got authn error below -- I *am* logged in via vs code....?!?!?

Action: azureFunctions.deploy
Error type: 407
Error Message:  [http://www.cnb.com] Authentication Required You must be authenticated to access this URL. URL: 

Company Acceptable Use Policy Bank information and telecommunications systems and equipment, including Internet, electronic mail, telephone, pager, voicemail, and fax, are provided for official and authorized Bank business purposes. Any use of such systems and equipment perceived to be illegal, harassing, offensive, or in violation of other Bank policies, standards, or guidelines, or any other uses that would reflect adversely on the Bank, can be considered a violation of this policy. For assistance, please contact Colleague Services X38080 (213-673-8080).

Proxy: mwg7.fire.cityntl.com Policy: default
RuleSet: Authenticate With NTLM Rule: Trigger Authentication
User: IP: 10.25.93.72
generated 2019-10-09 11:42:51 by McAfee Web Gateway

Version: 0.18.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline extension.bundle.js:331:748337
s extension.bundle.js:218:110861
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
```

</details>

**Comment by EricJizbaMSFT** [comment]
Closing - see https://github.com/microsoft/vscode-azurefunctions/issues/1519#issuecomment-599793164

**Comment by JackHartCNB** [comment]
Hey Eric,

So yeah, none of these were resolved, we ended up not being able to sort out the problems related to publishing a function.

--j
