### ISSUE TITLE
No dialog about 'Initialize for optimal use with VS Code' pops up after opening an outside project in VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1571]
**Build Version:** [20191010.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11102)
**OS:** Windows

**Repro Steps:**
1. Create a C# project with the command "func init --worker-runtime dotnet".
2. Add an HttpTrigger with the following command "func new --template HttpTrigger --name HttpTrigger1".
3. Open the project in VS Code.

**Expect:**
The below dialog pops up after waiting a few seconds.
![image](https://user-images.githubusercontent.com/45614674/66563738-0a790780-eb91-11e9-9bb2-b1bf2956aeb0.png)

**Actual:**
No dialog about 'Initialize for optimal use with VS Code' pops up.

**More info:**
1. This issue also reproduces for JavaScript and Python project.
2. This issue does not reproduce on Mac.

**Comment by EricJizbaMSFT** [comment]
@v-ruizh hmm I can't repro this on Windows. Is it possible you clicked "Don't warn again" on that machine? You can look for the setting `azureFunctions.showProjectWarning` and remove it if you see it

**Comment by EricJizbaMSFT** [comment]
@v-ruizh my gut feeling is this is an environment issue. Can you try on a different windows machine?

**Comment by v-ruizh** [comment]
@EricJizbaMSFT Verified this issue using the build [20191127.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12722), it is no longer reproduce, close it.
