### ISSUE TITLE
Error: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.

### ISSUE THREAD

**Issue by andreib94** [microsoft/vscode-azurefunctions#1576]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.

Version: 0.18.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:323376
o extension.bundle.js:1:322780
```

</details>

**Comment by EricJizbaMSFT** [comment]
@andreib94 please check your local.settings.json file and see if it has improper syntax. Otherwise please add repro steps

**Comment by ramnadh** [comment]
> Repro steps:
> 
> 
> Action: azureFunctions.pickProcess
> Error type: Error
> Error Message: Failed to parse "local.settings.json": Unexpected token ﻿ in JSON at position 0.
> 
> Version: 0.18.1
> OS: darwin
> Product: Visual Studio Code
> Product Version: 1.39.1
> Language: en
> 
> Call Stack

I had the same issue while trying to debug azure function from VS code but working fine from Visual studio. The issue there is with the BOM character in the JSON. Upon saving the JSON in UTF-8 without BOM, the issue got resolved.
