### ISSUE TITLE
[Suggestion] Update the version of Node.js

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1580]
**OS**: All
**Build Version:** [20191014.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11199)

**Repro Steps:**
1. Install a new Node.js v12.11.0.
2. Create a new JS project --> Deploy the new created project to the new function app with JS runtime.

**Actual:**
There is an error "Incompation Node.js version"

**Suggestion:**
Update the version of Node.js.
![image](https://user-images.githubusercontent.com/34729092/66813000-85ae3500-ef66-11e9-912c-e9b5f0936da0.png)

**Comment by EricJizbaMSFT** [comment]
Closing as upstream issue: https://github.com/Azure/azure-functions-nodejs-worker/issues/200
