### ISSUE TITLE
[Suggestion] Add a command to run "View Properties" for the Function URL 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1581]
**OS**: All
**Build Version:** [20191014.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11199)

**Repro Steps:**
1. Deploy a project to a function app.
2. F1 --> Type "View Properties".

**Actual:**
Prompt to select a function app.
![image](https://user-images.githubusercontent.com/34729092/66813505-78457a80-ef67-11e9-8ca4-1a92768835e2.png)

**Suggestion:**
Add a command to select "View Properties" for Function URL.
![image](https://user-images.githubusercontent.com/34729092/66813498-754a8a00-ef67-11e9-9a9d-e224ecd79b2d.png)

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix
