### ISSUE TITLE
There is no obvious refreshing indication for "Local Projects" node when clicking "Refresh" button at the top

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1582]
**OS**: All
**Build Version:** [20191014.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11199)

**Repro Steps:**
1. Create a new project and add it in workspace.
2. Debug.
3. Click "Refresh" button at the top.
![image](https://user-images.githubusercontent.com/34729092/66813984-61535800-ef68-11e9-9fc9-f0b2662d6c45.png)

**Expect:**
Refresh all resources in the Azure Functions Explorer panel.

**Actual:**
There is no obvious refreshing indication for "Local Projects" node.

**More Info:**
"Collapse All" works well both for the applied subscriptions and "Local Projects" node.

**Comment by EricJizbaMSFT** [comment]
Closing as by-design. Local projects auto-refresh so that's why you won't see the loading indicator for any noticeable amount of time
