### ISSUE TITLE
Improve create experience on subscription with limited permissions

### ISSUE THREAD

**Issue by JamesDLD** [microsoft/vscode-azurefunctions#1583]
Repro steps:

1. In Visual Studio Code, press F1 to open the command palette. In the command palette, search for and select "Azure Functions: Deploy to function app...".
2. Type a globally unique name that identifies your function app and press Enter. Valid characters for a function app name are a-z, 0-9, and -.
3. Select the location "West Europe" (same issue with "West US")

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.19.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
o.pipeline extension.bundle.js:218:502525
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:669956
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:635899
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@JamesDLD a few questions:
1. Does this error happen consistently for you? 
1. Does this error happen when it's creating a new function app or during the actual deploy?
1. Can you copy deploy logs here?
1. Does your subscription have restricted permissions by chance? You could try the "Create function app (Advanced)" option in case one of our defaults is causing the problem

**Comment by JamesDLD** [comment]
Please find below additional info :
1. Yes. I had to create the function app manually.
2. Only when creating a new function app. With existing function app the deploy works.
3. I founded the following logs, is there any other logs you need, if so can you tell me how to consult them 

<details>
<summary>Log from the Visual Studio code extension</summary>
Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

```
o.pipeline extension.bundle.js:218:502525
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:637004
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```
</details>

4. I am contributor on my resource group, i did manage to create the function app with same account through an arm template and using the "Create function app (Advanced)" option but the PowerShell option was not available, a warning appears to invite to update the remote function and it worked.
