### ISSUE TITLE
Fail to collapse the function app when the 'Functions' node is refreshing

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#159]
Repro Steps:
1. Right click one subscription and select 'Create Function App in Azure' to create a new function app.
2. Expand and right click the 'Functions' node then select 'Refresh'.
3. Check whether this function app can be collapsed or not when the 'Functions' node is refreshing.

Expect:
This function app can be collapsed and 'Refresh' action is canceled.

Actual:
Fail to collapse the function app. Please get the detailed video from
\\trinlab2\BAQAFiles\CloudToolsTest\v-dantch\Video\Fail-to-callapse.mp4

**Comment by EricJizbaMSFT** [comment]
This no longer repros for me. It was likely fixed by VS Code
