### ISSUE TITLE
error while : azure function deploy on cloud using vscode

### ISSUE THREAD

**Issue by AanjaneyaSinghDhoni** [microsoft/vscode-azurefunctions#1595]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49013
b.<anonymous> extension.js:229:177015
extension.js:229:171630extension.js:229:171630
extension.js:229:43713extension.js:229:43713
extension.js:229:41706extension.js:229:41706
extension.js:229:41328extension.js:229:41328
i.find extension.js:229:75821
init.then extension.js:229:23101
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
