### ISSUE TITLE
error thrown in VS Code Mac - trying to deploy/re-deploy

### ISSUE THREAD

**Issue by SogoGolf** [microsoft/vscode-azurefunctions#1596]
Repro steps:
1. deleted the function app "userlogs-changefeed" in VS Code/Azure functions plugin - worked and i checked in Azure portal that the function app was deleted.
2. then, tried to redeploy the same local function app JS code to Azure, using the exact same function app name "userlogs-changefeed"

threw this error. tried a few times no luck!

Action: azureFunctions.deploy
Error type: 404
Error Message:  404 Web Site not found.
You may be seeing this error due to one of the reasons listed below :

 * Custom domain has not been configured inside Azure. See how to map an existing domain [https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-tutorial-custom-domain] to resolve this.
 * Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.

Checkout App Service Domain FAQ [https://blogs.msdn.microsoft.com/appserviceteam/2017/08/08/faq-app-service-domain-preview-and-custom-domains/] for more questions.

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:393194
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:636969
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.EventEmitter.emit domain.js:442:20
$.<anonymous> extension.bundle.js:194:18450
```

</details>

**Comment by EricJizbaMSFT** [comment]
@SogoGolf why type of function app was it? 
1. Linux/Windows
1. Consumption plan/App Service Plan/Premium/Isolated
1. Project language

Sounds like it worked if you just used a different name? If so not sure we can do anything for this - at least from VS Code

**Comment by SogoGolf** [comment]
No worries that’s fine will close this
