### ISSUE TITLE
Unable to register the resource provider Microsoft.Web through VS Code

### ISSUE THREAD

**Issue by natrajsr** [microsoft/vscode-azurefunctions#1598]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
l.pipeline extension.bundle.js:218:2860471
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
o.statusCode.t.registerRP extension.bundle.js:164:26925
n.statusCode.t.getRegistrationStatus extension.bundle.js:164:27796
$.n.get [as _callback] extension.bundle.js:164:27902
t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.onRequestError extension.bundle.js:194:14671
ClientRequest.emit events.js:187:15
TLSSocket.socketErrorListener _http_client.js:391:9
TLSSocket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@natrajsr take a look at these docs to fix registration problems: https://docs.microsoft.com/azure/azure-resource-manager/resource-manager-register-provider-errors
