### ISSUE TITLE
Create new C# environment failed

### ISSUE THREAD

**Issue by hazelnutsgz** [microsoft/vscode-azurefunctions#1600]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to get latest templates: Command "dotnet '/Users/hashibami/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.19.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/hashibami/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg' --require '/Users/hashibami/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg' --operation list" failed with exit code "150":
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:382699
o extension.bundle.js:164:379638
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hazelnutsgz thanks for filing! We don't support .NET Core 3.0 yet - tracking that work here: https://github.com/microsoft/vscode-azurefunctions/issues/1489

For now you have to have a 2.* version of .NET Core installed
