### ISSUE TITLE
Java on Linux

### ISSUE THREAD

**Issue by ColbyTresness** [microsoft/vscode-azurefunctions#1601]
Add support for Java on Linux (default should still be Windows)

**Comment by kulkarnisonia16** [comment]
Scenarios:
Create Java function app in Azure in Linux Consumption (bring your own code scenario)
Create Java function app in Azure in Linux Dedicated and Premium plans (bring your own code scenario)
Deploy to Java function app in Azure in Linux Consumption, Dedicated and Premium plans (bring your own code scenario) 
Support remote debugging for Java function apps in Linux for Consumption, Dedicated and Premium
