### ISSUE TITLE
The requested URL /admin/host/synctriggers was not found on this server.

### ISSUE THREAD

**Issue by svangeti** [microsoft/vscode-azurefunctions#1611]
Repro steps:

1. deploy python function from local to azure
2. Deploy it as package

Action: azureFunctions.deploy
Error type: 404
Error Message: Not Found
The requested URL /admin/host/synctriggers was not found on this server.

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.pipeline extension.bundle.js:218:2797976
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:637004
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by svangeti** [comment]
Update: If I deploy it on consumption app service plan it works fine but if I deploy on Standard App service plan then it doesn't work.

**Comment by EricJizbaMSFT** [comment]
@svangeti what type of plan exactly? Elastic premium/standard/free/etc.?

Also is your Python project brand new or is it an old project? Can you copy the settings in `.vscode/settings.json` here? What about the function app in Azure - is that brand new?

**Comment by svangeti** [comment]
> @svangeti what type of plan exactly? Elastic premium/standard/free/etc.?
> 
> Also is your Python project brand new or is it an old project? Can you copy the settings in `.vscode/settings.json` here? What about the function app in Azure - is that brand new?

@EricJizbaMSFT It's a standard plan.
`{
  "azureFunctions.deploySubpath": ".",
  "azureFunctions.pythonVenv": ".venv",
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~2",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "func: pack --build-native-deps",
  "python.pythonPath": "/Users/abc/Documents/environments/azure/az-functionapp-setup/src/python/.venv/bin/python3",
  "python.linting.pylintPath": ".venv/bin/pylint",
  "azureFunctions.templateFilter": "All",
  "azureFunctions.scmDoBuildDuringDeployment": true
}
`
