### ISSUE TITLE
C# Function DotNet 3.0 Support?

### ISSUE THREAD

**Issue by AdamCoulterOz** [microsoft/vscode-azurefunctions#1613]
Is this going to be fixed soon?

Repro steps:

1. brew cask install visual-studio-code (1.39.2)
2. brew cask install dotnet-sdk (3.0.100)
3. brew install azure-functions-core-tools-v3-preview (3.0.1740)
4. code --install-extension ms-azuretools.vscode-azurefunctions (0.19.1)
5. Create a Functions Project using C# in VS Code

Failed to get latest templates: Command failed with exit code "150":
```sh
dotnet '.../ms-azuretools.vscode-azurefunctions-0.19.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll'
   --require '.../ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg'
   --require '.../ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg'
   --operation list
```

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.0.0 [Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

Product: Visual Studio Code
Version: 1.39.2
Language: en
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:382699
o extension.bundle.js:164:379638
```

</details>

**Comment by EricJizbaMSFT** [comment]
> Is this going to be fixed soon?

Yep - a few relevant issues to track: https://github.com/microsoft/vscode-azurefunctions/issues/1489 https://github.com/microsoft/vscode-azurefunctions/issues/1604
