### ISSUE TITLE
[error] Incompatible Node.js version

### ISSUE THREAD

**Issue by andytael** [microsoft/vscode-azurefunctions#1614]
When running my javascript (Azure functions) from Visual Code I get the following error:

`[error] Incompatible Node.js version. The version you are using is v12.12.0, but the runtime requires an LTS-covered major version (ex: 8.11.1 or 10.14.1). LTS-covered versions have an even major version number (8.x, 10.x, etc.) as per https://github.com/nodejs/Release#release-plan. For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, install or switch to a supported node version (make sure to quit and restart your code editor to pick up the changes).`

The web site https://github.com/nodejs/Release#release-plan tells me that Release 12.x is Active TLS.

Andy idea what I can do to fix the problem?

Thanks
Andy

**Comment by EricJizbaMSFT** [comment]
@andytael take a look at this issue: https://github.com/Azure/azure-functions-nodejs-worker/issues/200

Looks like Azure Functions doesn't support 12 yet, but sounds like it's coming soon. Closing this issue since we can't control this from VS Code
