### ISSUE TITLE
Error on immediatly hit debug after startin MS Visual Studio Code

### ISSUE THREAD

**Issue by philipp-bananaware** [microsoft/vscode-azurefunctions#1616]
Repro steps:

1. Started Microsoft Visual Studio Code
2. Hit "Start Debug" button

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:68067extension.bundle.js:353:68067
o extension.bundle.js:353:66701
```

</details>

**Comment by EricJizbaMSFT** [comment]
@philipp-bananaware we see this error occasionally, but not with consistent repro steps. Can you give us more info, for example:
1. What version of `dotnet` sdk do you have?
1. What version of `func` cli?
1. What type of functions do you have - just http?
