### ISSUE TITLE
Improve error message when executionFunction fails with ECONNREFUSED

### ISSUE THREAD

**Issue by vency-pcci** [microsoft/vscode-azurefunctions#1617]
Repro steps:

1.
2.

Action: azureFunctions.executeFunction
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:7071

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:218:1076707
$.callback extension.bundle.js:218:1075381
$.e.callback.t.callback [as _callback] extension.bundle.js:218:1074827
t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.onRequestError extension.bundle.js:194:14671
ClientRequest.emit events.js:182:13
Socket.socketErrorListener _http_client.js:391:9
Socket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@vency-pcci this isn't the best error message, but it likely means your project isn't running. Can you trying debugging and _then_ execute the function?

The other possibility is you are using a non-default port?
