### ISSUE TITLE
Unable to Deploy Python Azure Function to West US from VS Code

### ISSUE THREAD

**Issue by andrewtuplin** [microsoft/vscode-azurefunctions#1620]
Repro steps:
1.  From VS Code (Azure Extension).  Deploy new Python Function
2.  Region: West Us. 

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
l.pipeline extension.bundle.js:218:2860471
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
$.n [as _callback] extension.bundle.js:164:27007
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@adrewtuplin seems like your subscription doesn't have permissions for some of the default values. Can you try using the "Advanced" option to pick different values?
