### ISSUE TITLE
Support adding tag when creating a function app

### ISSUE THREAD

**Issue by dariuszbz** [microsoft/vscode-azurefunctions#1621]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: RequestDisallowedByPolicy
Error Message: Resource 'emaiurllverification' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Enforce Billing Tags on Resource Groups","id":"/subscriptions/c9521a5f-da33-4293-a5ec-30cffce21063/providers/Microsoft.Authorization/policyAssignments/9662f5a468f7406987ddafed"},"policyDefinition":{"name":"Enforce Billing Tags on Resource Groups","id":"/subscriptions/c9521a5f-da33-4293-a5ec-30cffce21063/providers/Microsoft.Authorization/policyDefinitions/13d6fe92-982f-4d38-9e4d-004b52e9990d"}}]'.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.pipeline extension.bundle.js:218:505562
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:637004
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
```

</details>

**Comment by EricJizbaMSFT** [comment]
@dariuszbz can you explain a little more about the tag policy on your subscription and what experience you expect here?

**Comment by dariuszbz** [comment]
Policy required resources to be created with at least one tag.
Using creator from Vs code I can't add any tag so creator fails. I need to
create resources from portal and than deploy from Vs code.

Just add two more questions to the creator: tag name, tag value

Thank you.
