### ISSUE TITLE
Support remote debug for functions written in C#

### ISSUE THREAD

**Issue by sfumato-admin** [microsoft/vscode-azurefunctions#1622]
Repro steps:

1.
2.

Action: azureFunctions.startRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js Function Apps running on Linux App Service plans. Consumption plans are not supported.

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.checkForRemoteDebugSupport extension.bundle.js:353:77791
extension.bundle.js:353:77501
o extension.bundle.js:353:76816
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by RickC37** [comment]
any updates to this?

**Comment by EricJizbaMSFT** [comment]
No plans at the moment. Related to https://github.com/microsoft/vscode-azurefunctions/issues/314
