### ISSUE TITLE
Issue with Deploying to Azure Functions

### ISSUE THREAD

**Issue by masonhuemmer** [microsoft/vscode-azurefunctions#1637]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\git\az-functions\bin\Release\netcoreapp2.1\publish

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:13568
o extension.bundle.js:288:13149
```

</details>

**Comment by EricJizbaMSFT** [comment]
@masonhuemmer can you double check that path? Perhaps the preDeployTask (which runs a `dotnet publish`) failed? Or maybe you recently changed the TargetFramework to something other than "netcoreapp2.1"?

**Comment by wmekal-pgs** [comment]
@masonhuemmer I ran into the same issue. I have `.NET CORE 2.2` on my machine and it published to `netcoreapp2.2`. 

I did following 3 things:
1. Updated `TargetFramework` in csproj to `<TargetFramework>netcoreapp2.2</TargetFramework>`
2, Updated `azureFunctions.deploySubpath` in  `settings.json` to `"azureFunctions.deploySubpath": "bin/Release/netcoreapp2.2/publish",`
3. Updated relevant path in `tasks.json` to point to `netcoreapp2.2`.

**Comment by EricJizbaMSFT** [comment]
@wmekal-pgs you can also run this from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and it should reset all settings as appropriate:
![Screen Shot 2019-11-08 at 10 38 21 AM](https://user-images.githubusercontent.com/11282622/68501817-e4886680-0213-11ea-91b1-fd366304eeab.png)

If you're still running into issues, please copy all logs from the "Azure Functions" output channel and the `dotnet publish` task

**Comment by wmekal-pgs** [comment]
@EricJizbaMSFT Thank you for tip. 

It does the job, but resets to .NET CORE 2.1 - looks like template is outdated.
If this is not enough, then you need to update the entries like I did.

**Comment by EricJizbaMSFT** [comment]
We get the target framework from the csproj in your project - not from a template. Do you have multiple csproj's? Also can you paste the full contents of your csproj? Perhaps it has something we don't expect

**Comment by masonhuemmer** [comment]
I was able to resolve the issue.
You can close the ticket.

I didn’t have a specific package installed with dotnet.




Sent from my iPhone
________________________________

**Comment by EricJizbaMSFT** [comment]
@wmekal-pgs if you're still having issues after looking more closely at your csproj - let's start a new issue instead of continuing on this one

**Comment by wmekal-pgs** [comment]
@EricJizbaMSFT Yes, I have multiple csrpoj's, but all of them are 2.2. I've also tried on empty folder with the same result.

Nevertheless, this is not an issue for me - just wanted to reply in case someone is experiencing it in the future.

Thanks for comments.
