### ISSUE TITLE
Fail to run C# Class library function on mac/linux

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#164]
For some reason the generated 'function.json' file has the dll path specified as `bin/example.dll` when it should be `../bin/example.dll`. On windows, it has the correct path.

**Comment by EricJizbaMSFT** [comment]
Looks like this will be fixed here: https://github.com/Azure/azure-functions-vs-build-sdk/issues/142

We just need to wait for the fix to be released

**Comment by EricJizbaMSFT** [comment]
FYI - projects created after the recent 0.6.0 release should work on mac/linux. If you have an old project, simply change the version of "Microsoft.NET.Sdk.Functions" in your csproj file to 1.0.8 or later

**Comment by anujb** [comment]
Huzzah! 🎉 :partyparrot
