### ISSUE TITLE
The get_body() method (python) does not work for local development fro chunked encoding

### ISSUE THREAD

**Issue by tezzigator** [microsoft/vscode-azurefunctions#1641]
If pushed to an azure function, the `req.get_body().decode('utf-8')` will correctly de-encapsulate and return the chunked data sent as described by the included `transfer-encoding: chunked` header of the POST request.

But just doesnt work at all locally in VSCode (latest VS code and functions extension, python 3.6.8, Win10, all 64bit), it just returns null.

**Comment by EricJizbaMSFT** [comment]
@tezzigator In VS Code, we basically just start the runtime with `func host start` and attach to the process. The func cli actually handles running it locally. I would file an issue on one of these repos:
- The func cli: https://github.com/Azure/azure-functions-core-tools
- The python worker inside the func cli: https://github.com/Azure/azure-functions-python-worker
