### ISSUE TITLE
Pop up an error when debugging a PS project

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1642]
**OS:** All
**Build**: [20191031.33](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11905)

**Repro Steps:**
1. Make sure  PowerShell Core 6.0 or higher is installed.
2. Create a PowerShell project --> Debug.

**Expect:**
Succeed to debug.

**Actual:**
Pop up an error when debugging. 
![image](https://user-images.githubusercontent.com/34729092/68013058-dcd23a80-fcc6-11e9-838c-9947e9fb3f66.png)

**More Info:**
Please get the details about launch.json file from below screenshot:
![image](https://user-images.githubusercontent.com/34729092/68013075-ee1b4700-fcc6-11e9-8c08-fe123c505670.png)

**Comment by EricJizbaMSFT** [comment]
@v-dantch can you copy the full logs of the "func host start" task?

In addition:
1. What version of PowerShell do you have on your machine?
1. What version of PowerShell extension for VS Code?
1. What version of func cli?

**Comment by v-dantch** [comment]
Hi Eric, thanks for your response.

Due to Azure Functions Extension v0.20.0 is public for now. So today we verified this issue on the released Azure Functions Extension.

Hmmmm, I'm a bit embarrassed now to say that I found the root cause -- .NET Core SDK should be 2.2.
![image](https://user-images.githubusercontent.com/34729092/68182753-4b6c0c80-ffd5-11e9-8d54-17a093dfb9e1.png)
And the reason why this issue occurs is that .NET Core 3.1 preview 1 was installed. And Debug works well with .NET Core 2.2 installed. Could you help to close this bug?

Meanwhile is it doable to update the compatible framework version? Due to .NET Core 2.2 is no longer supported in December.

**Comment by EricJizbaMSFT** [comment]
> Meanwhile is it doable to update the compatible framework version? Due to .NET Core 2.2 is no longer supported in December.

The platform team controls this, not my team. And .NET Core 3 support is coming with Azure Functions v3: https://docs.microsoft.com/azure/azure-functions/functions-versions

**Comment by v-dantch** [comment]
Oh, I see. I had thought that it belongs to VS Code Team. Thanks for correcting me.
