### ISSUE TITLE
Fail to get the Python version when verifying the response from http trigger 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1643]
**OS:** All
**Build**: [20191031.33](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11905)

**Repro Steps:**
1. Create a new Python project.
2. Modify the __init_.py_ file like below.
	import logging
	import sys
	import azure.functions as func
	
	def main(req: func.HttpRequest) -> func.HttpResponse:
	logging.info('Python HTTP trigger function processed a request.')
	return func.HttpResponse(
	f"Python Version: {sys.version_info[0]}.{sys.version_info[1]}",
	status_code=400
	)
3. Deploy this project tp a new project created using basic creation.
4. Query the http trigger after deploying finishes.
5. Verify the result. 

**Expect:**
Succeed to get the correct Python version that selected in previous step.

**Actual:**
Nothing displays. 
![image](https://user-images.githubusercontent.com/34729092/68014581-f2496380-fcca-11e9-82ed-963fa4357c14.png)

**Comment by EricJizbaMSFT** [comment]
@v-dantch whitespace matters in python files. I probably didn't copy/paste the code correctly into OneNote, but @nturinski has since updated the test case. Try copying/pasting again and see if it looks more like this:
![Screen Shot 2019-11-04 at 3 19 18 PM](https://user-images.githubusercontent.com/11282622/68166219-878c6800-ff16-11e9-9ca0-29a89bcdc9c6.png)

**Comment by v-dantch** [comment]
Hi Eric, Nathan, today we verified this issue on the public Azure Functions Extension v0.20.0 and it works well lol according to your share. And I will close this bug for now.

**Comment by v-ruizh** [comment]
This issue also reproduces on Azure Functions extension [20200406.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17411), reopen it.

**Comment by EricJizbaMSFT** [comment]
@v-ruizh this one was not a bug in the extension, but a bug in the `__init__.py` file, so please double check that file. If you're still having problems - please file a new issue with new repro steps
