### ISSUE TITLE
Prompt to select a "Debug Configuration" in "Untitled" workspace

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1644]
**OS:** All
**Build Version**:[ 20191031.33](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11905)
**Regression** : Not a Regression

**Repro Steps:**
1. F1 --> Type and select "Azure Functions: Uninstall Azure Functions Core Tools".
2. Click a new Python project --> Select "Azure Functions v3 Preview (.NET Core)" when asked to select a version --> Select "Http Trigger" template.
![image](https://user-images.githubusercontent.com/34729092/68017956-ebbeea00-fcd2-11e9-93c0-0494485601e6.png)
3. Prompt to install Linter pylint --> Intsall.
![image](https://user-images.githubusercontent.com/34729092/68018098-3f313800-fcd3-11e9-98f2-5ed5c21d0433.png)
4. Debug.
5. Prompt to install the Azure Functions Core Tools --> Install.
![image](https://user-images.githubusercontent.com/34729092/68018168-71429a00-fcd3-11e9-831c-48ac06edeec2.png)

**Expect:**
Do not prompt to select a debug configuration.

**Actual:**
Prompt to select a debug configuration.
![image](https://user-images.githubusercontent.com/34729092/68018582-70f6ce80-fcd4-11e9-8dc4-5a47e4c179c7.png)

**Note:**
This prompting only pops up **one time** **at the first time** to debug the Python project on **each platform.**

**Comment by EricJizbaMSFT** [comment]
@v-dantch can you verify the `.vscode` folder exists at the root of the repo and send the contents if it does?

**Comment by v-dantch** [comment]
Hi Eric,

There is .vscode folder like below:
![image](https://user-images.githubusercontent.com/34729092/69525756-be98eb00-0fa3-11ea-8dfd-b805fdf21cfe.png)

**extensions.json**
{
  "recommendations": [
    "ms-azuretools.vscode-azurefunctions",
    "ms-python.python"
  ]
}
**launch.json**
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9091,
      "preLaunchTask": "func: host start"
    }
  ]
}

**settings.json**
  "azureFunctions.deploySubpath": ".",
  "azureFunctions.scmDoBuildDuringDeployment": true,
  "azureFunctions.pythonVenv": ".venv",
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~3",
  "debug.internalConsoleOptions": "neverOpen"
}

**tasks.json**
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "pipInstall"
    },
    {
      "label": "pipInstall",
      "type": "shell",
      "osx": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "windows": {
        "command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
      },
      "linux": {
        "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
      },
      "problemMatcher": []
    }
  ]
}

**Comment by EricJizbaMSFT** [comment]
Ah - I bet this only happens for "Untitled" workspaces

**Comment by v-xinda** [comment]
Verified on the build [20200107.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13470&view=results), this issue doesn't reproduce for now. So closed it.
