### ISSUE TITLE
Encounter an error when deploying a project with v3 func cli to a Linux function app with Python runtime

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1645]
**OS:** Win10
**Build Version:** [20191031.33](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11905)

**Repro Steps:**
1. F1 --> Type and select "Azure Functions: Uninstall Azure Functions Core Tools".
2. Click a new Python project --> Select "Azure Functions v3 Preview (.NET Core)" when asked to select a version --> Select "Http Trigger" template.
![image](https://user-images.githubusercontent.com/34729092/68017956-ebbeea00-fcd2-11e9-93c0-0494485601e6.png)
3. Prompt to install Linter pylint --> Intsall.
4. Debug.
5. Prompt to install the Azure Functions Core Tools --> Install.
6. Deploy--> Check the result.

**Expect:**
Succeed to deploy without any errors.

**Actual:**
Pop up an error when deploying.
![image](https://user-images.githubusercontent.com/34729092/68020685-35f79980-fcda-11e9-9b01-e718b58bbf0e.png)

**Comment by v-xinda** [comment]
Verified on the build [20200107.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13470&view=results), this issue doesn't reproduce for now. So I close it temporarily.
