### ISSUE TITLE
Azure Function Deploy Issues

### ISSUE THREAD

**Issue by subramankala** [microsoft/vscode-azurefunctions#1652]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ETIMEDOUT
Error Message: connect ETIMEDOUT 172.25.109.11:443

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.31.1
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1161:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@subramankala please add repro steps
