### ISSUE TITLE
azure function python deploy fail

### ISSUE THREAD

**Issue by moneysqtw** [microsoft/vscode-azurefunctions#1656]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Deployment to "smeFinancingMonitoring" failed. See output channel for more details.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:536257
o extension.bundle.js:1:533536
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@moneysqtw please copy the logs from the output channel and add more detailed repro steps
