### ISSUE TITLE
Debug PowerShell projects hits breakpoints I never set

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1660]
Seems like every single time I debug I hit a breakpoint I never set. A few examples:
![Screen Shot 2019-11-05 at 10 11 35 AM](https://user-images.githubusercontent.com/11282622/68234400-fbca1880-ffb5-11e9-9b5b-7ef6f24cd2d0.png)

![Screen Shot 2019-11-05 at 10 12 47 AM](https://user-images.githubusercontent.com/11282622/68234406-ff5d9f80-ffb5-11e9-8bd4-b6fff983fead.png)

**Comment by MrDRamos** [comment]
I am having the same issue

**Comment by ThomVanL** [comment]
Also experiencing this issue, breakpoints always appear to get triggered inside of profile.ps1.

- macOS 10.15.3
- azure-functions-core-tools@3/3.0.2106
- VS Code Version: 1.42.1

**Comment by sebastianzolg** [comment]
Same here! Any update?

**Comment by EricJizbaMSFT** [comment]
Might be fixed in PowerShell 7, coming soon to Functions: https://github.com/Azure/azure-functions-powershell-worker/issues/371
