### ISSUE TITLE
Breakpoints don't work for PowerShell projects

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#1661]
Instead users have to add `Wait-Debugger` to their code as described in this tutorial:
https://docs.microsoft.com/azure/azure-functions/functions-debug-powershell-local

**Comment by sebastianzolg** [comment]
Any update on this?

**Comment by EricJizbaMSFT** [comment]
Last I heard the fix would be a part of PowerShell 7, which is coming soon to Functions: https://github.com/Azure/azure-functions-powershell-worker/issues/371
