### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by varshabhijeet** [microsoft/vscode-azurefunctions#1667]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\Users\varsha\Application Data'

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

**Comment by EricJizbaMSFT** [comment]
@varshabhijeet please add repro steps. Also perhaps try using a project in a different folder path
