### ISSUE TITLE
AuthorizationFailed

### ISSUE THREAD

**Issue by bassyboy** [microsoft/vscode-azurefunctions#1673]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: AuthorizationFailed
Error Message: The client 'live.com#gatoohoo@outlook.com' with object id '545105db-ac40-4672-a22a-e3c300f70c8a' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/write' over scope '/subscriptions/b8f2ff04-0a81-4cf9-95ef-5828d16981d2/resourceGroups/COSMOS_RG_East_US_2_10f09450-8ea8-419e-aac5-7aef97f5db13/providers/Microsoft.Storage/storageAccounts/bassboy' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:738885extension.bundle.js:218:738885
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
```

</details>

**Comment by EricJizbaMSFT** [comment]
@bassyboy can you try using Advanced create? For example if your subscription doesn't have permission to create a storage account, that will let you select an existing account. We're tracking improvements to basic create here: https://github.com/microsoft/vscode-azurefunctions/issues/1583
