### ISSUE TITLE
What kind of problem!?

### ISSUE THREAD

**Issue by YehChunChuan** [microsoft/vscode-azurefunctions#1674]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EBUSY
Error Message: EBUSY: resource busy or locked, scandir 'c:\WINDOWS\system32\catroot2\edb.log'

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

**Comment by EricJizbaMSFT** [comment]
@YehChunChuan please add repro steps. Also perhaps try using a different root folder when working with your project as we might not have permissions for the "c:\WINDOWS\system32" path
