### ISSUE TITLE
azure function deployment issue

### ISSUE THREAD

**Issue by tdrjin** [microsoft/vscode-azurefunctions#1675]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
TCP.onStreamRead stream_base_commons.js:183:27
```

</details>

**Comment by EricJizbaMSFT** [comment]
@tdrjin please add repro steps
