### ISSUE TITLE
SignalR learning module: The scale operation is not allowed for this subscription in this region

### ISSUE THREAD

**Issue by pcseanmckay** [microsoft/vscode-azurefunctions#1676]
Repro steps:

1. Start running through the learning path module: Enable automatic updates in a web application using Azure Functions and SignalR Service
2. When you get to the deploy function app section in the last exercise, watch the error occur.

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.20.0
OS: linux
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
l.pipeline extension.bundle.js:218:2860478
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by pcseanmckay** [comment]
As a side note for anyone suggesting to select a different subscription and try again, this error occurs specifically when using the subscription that is autogenerated as part of the sandbox being used in a learning path exercise for Azure learning paths.  The specific learning path module I was attempting to accomplish was: Enable automatic updates in a web application using Azure Functions and SignalR Service.

**Comment by EricJizbaMSFT** [comment]
@pcseanmckay thanks for the info - I'll try the learning module you mentioned. Rather than change subscriptions - what if you just select a different location? (Just as a workaround - I will still investigate this issue)

**Comment by pcseanmckay** [comment]
I will check into selecting a different location...

**Comment by EricJizbaMSFT** [comment]
I went through the learning module and could not reproduce this error. I have a feeling they may have updated the module recently as it seemed very up-to-date with our extension. The module says to use "Advanced" create, but if I ignore that and use "Basic" create I got it to work just fine with the help of https://github.com/microsoft/vscode-azuretools/pull/651
