### ISSUE TITLE
Azure Functions from VS Code - start without debugging failed

### ISSUE THREAD

**Issue by kprpg** [microsoft/vscode-azurefunctions#1677]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "host start" failed with exit code "-3".

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:75642extension.bundle.js:353:75642
l.fire extensionHostProcess.js:47:207
m.$onDidEndTaskProcess extensionHostProcess.js:695:468
```

</details>

**Comment by EricJizbaMSFT** [comment]
@kprpg please check the logs of the "host start" task. If that doesn't help you solve the problem, please post more detailed repro steps here
