### ISSUE TITLE
Azure Functions: add binding does not work

### ISSUE THREAD

**Issue by knaidoo33** [microsoft/vscode-azurefunctions#1680]
Repro steps:

1. create new function in vs code (I used an http trigger)
2. F1 -> Azure Functions: add binding

Action: azureFunctions.addBinding
Error type: Error
Error Message: No matching resources found.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:1:632589
o extension.bundle.js:1:627099
```

</details>

**Comment by EricJizbaMSFT** [comment]
@knaidoo33 what language is your project? We don't support this feature on several languages (https://github.com/microsoft/vscode-azurefunctions/issues/1485). We should probably improve the error message here

**Comment by knaidoo33** [comment]
Thanks for the quick response. 
I am using C# 
Is there a different way I can add a binding directly from VS code?

**Comment by EricJizbaMSFT** [comment]
Unfortunately no there isn't. C# bindings are controlled directly in the .cs file and other languages just use json. It was relatively easy to inject a binding into json, but injecting a binding into a .cs file is something we haven't found a solution for

**Comment by knaidoo33** [comment]
Is there a way I can add bindings manually?

**Comment by EricJizbaMSFT** [comment]
Yeah here's an example:
https://docs.microsoft.com/azure/azure-functions/functions-bindings-example#class-library-example

More relevant docs:
https://docs.microsoft.com/azure/azure-functions/functions-dotnet-class-library
https://docs.microsoft.com/azure/azure-functions/functions-triggers-bindings

**Comment by knaidoo33** [comment]
Thank you!
