### ISSUE TITLE
Fail to deploy a Node.js project to a Linux function app with error "Service Unavailable"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1685]
**OS:** Win 10
**Build Version:** [20191112.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12367)

**Repro Steps:**
1. Create a Linux function app with Premium hosting plan and node.js 10 template.
2. Create a Linux project with JavaScript language and Http trigger template.
3. Debug --> Deploy.

**Expect:**
Succeed to deploy the Node.js 10 project to the Linux function app.

**Actual:**
Fail to deploy with error "ServiceUnavailable".
![image](https://user-images.githubusercontent.com/34729092/68843971-f5e5dd00-0703-11ea-9d6c-622c7a3ab2af.png)

**More Info:**
1. This issue does not reproduce when deploying a project to Windows function apps.
2. Please get more info from the "Output" window when deploying.
1:15:57 AM: Creating resource group "linnodejs10premium" in location "southeastasia"...
1:16:03 AM: Successfully created resource group "linnodejs10premium".
1:16:03 AM: Ensuring App Service plan "linnodejs10premium" exists...
1:16:04 AM: Creating App Service plan "linnodejs10premium"...
1:16:17 AM: Successfully created App Service plan "linnodejs10premium".
1:16:17 AM: Creating storage account "linnodejs10premium" in location "southeastasia" with sku "Standard_LRS"...
1:16:52 AM: Successfully created storage account "linnodejs10premium".
1:16:52 AM: Verifying that Application Insights is available for this location...
1:16:53 AM: Creating new Application Insights resource "lin-nodejs10-premium"...
1:17:02 AM: Created new Application Insights resource "linnodejs10premium"...
1:17:02 AM: Creating new function app "lin-nodejs10-premium"...
1:17:41 AM lin-nodejs10-premium: Creating zip package...
1:17:41 AM lin-nodejs10-premium: Starting deployment...
1:20:25 AM lin-nodejs10-premium: Waiting for long running command to finish...
1:17:57 AM lin-nodejs10-premium: Updating submodules.
1:17:57 AM lin-nodejs10-premium: Preparing deployment for commit id 'c8259cb282'.
1:17:57 AM lin-nodejs10-premium: Generating deployment script.
1:17:57 AM lin-nodejs10-premium: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
1:17:58 AM lin-nodejs10-premium: Generating deployment script for Web Site
1:17:58 AM lin-nodejs10-premium: Generated deployment script files
1:17:58 AM lin-nodejs10-premium: Running deployment command...
1:17:58 AM lin-nodejs10-premium: Command: "/home/site/deployments/tools/deploy.sh"
1:17:58 AM lin-nodejs10-premium: Handling Basic Web Site deployment.
1:17:58 AM lin-nodejs10-premium: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
1:17:58 AM lin-nodejs10-premium: Copying file: '.funcignore'
1:17:58 AM lin-nodejs10-premium: Copying file: 'host.json'
1:17:58 AM lin-nodejs10-premium: Copying file: 'package.json'
1:17:58 AM lin-nodejs10-premium: Copying file: 'proxies.json'
1:17:58 AM lin-nodejs10-premium: Copying file: 'HttpTriggerJS/function.json'
1:17:58 AM lin-nodejs10-premium: Copying file: 'HttpTriggerJS/index.js'
1:17:58 AM lin-nodejs10-premium: Copying file: 'HttpTriggerJS/sample.dat'
1:17:58 AM lin-nodejs10-premium: Finished successfully.
1:17:58 AM lin-nodejs10-premium: Running post deployment command(s)...
1:17:58 AM lin-nodejs10-premium: Deployment successful.
1:17:59 AM lin-nodejs10-premium: App container will begin restart within 10 seconds.
1:23:26 AM lin-nodejs10-premium: Syncing triggers...
1:23:33 AM lin-nodejs10-premium: Syncing triggers (Attempt 2/6)...
1:23:45 AM lin-nodejs10-premium: Syncing triggers (Attempt 3/6)...
1:24:07 AM lin-nodejs10-premium: Syncing triggers (Attempt 4/6)...
1:24:49 AM lin-nodejs10-premium: Syncing triggers (Attempt 5/6)...
1:26:11 AM lin-nodejs10-premium: Syncing triggers (Attempt 6/6)...
1:26:15 AM: Error: Encountered an error (ServiceUnavailable) from host runtime.

**Comment by EricJizbaMSFT** [comment]
Could be related to https://github.com/microsoft/vscode-azurefunctions/issues/1682

**Comment by EricJizbaMSFT** [comment]
I can't repro this anymore. Could have been fixed on the platform side or could have been fixed with 1682
