### ISSUE TITLE
Trouble when deploying a simple entity function.

### ISSUE THREAD

**Issue by hazelnutsgz** [microsoft/vscode-azurefunctions#1692]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to find preDeploy task "publish". Modify the setting "azureFunctions.preDeployTask" or add that task to tasks.json.

Version: 0.20.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:353:65385
o extension.bundle.js:353:63771
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hazelnutsgz please add repro steps and copy the contents of your "tasks.json" file here
