### ISSUE TITLE
Wrong AuthorizationLevel for FSharp HttpTrigger function

### ISSUE THREAD

**Issue by Ma3yTa** [microsoft/vscode-azurefunctions#1693]
```powershell
dotnet --version
3.0.100
func --version
3.0.1740
```
I chose Anonymous but extension creates a file with AuthorizationLevel.Function.
Please check the video for details.
[![](https://i.imgur.com/LiWM5bR.png)](https://www.dropbox.com/s/i1itte7ozdgmdj9/xIUvlFTZss.mp4)

**Comment by EricJizbaMSFT** [comment]
This is controlled by the templates in this repo: https://github.com/Azure/azure-functions-templates
