### ISSUE TITLE
assadasd

### ISSUE THREAD

**Issue by ikmalsyafiq** [microsoft/vscode-azurefunctions#1694]
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: DisallowedProvider
Error Message: The operation is not permitted for namespace 'Microsoft.Storage'. List of permitted provider namespaces is 'Microsoft.AlertsManagement,Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'.

Version: 0.20.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:703405
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ikmalsyafiq please add repro steps. It seems like your subscription might not have the right permissions
