### ISSUE TITLE
depolying issue. 

### ISSUE THREAD

**Issue by anjaneyulu-bods** [microsoft/vscode-azurefunctions#1696]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/sai/GP-Infrastructure/Deployments/SEAsia/GP-Orders/ComosDb-Backups/BlobTrigger/bin/Release/netcoreapp2.1/publish

Version: 0.19.1
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:13568
o extension.bundle.js:288:13149
```

</details>

**Comment by EricJizbaMSFT** [comment]
@anjaneyulu-bods please add repro steps
