### ISSUE TITLE
Update marketplace icon 

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1697]
Use the new Functions icon

![image](https://user-images.githubusercontent.com/1186948/69075208-c7a71c80-09e5-11ea-9c88-51c84ccf7e10.png)

**Comment by btardif** [comment]
you can get the icon here: https://cds-icons.azurewebsites.net/downloads/All_Icons/Compute/Icon-compute-29-Function-Apps.svg

**Comment by EricJizbaMSFT** [comment]
@btardif do you have a "png" version of that icon - or a preferred tool for converting svgs to pngs? Seems like VS Code doesn't like svgs for the marketplace
![Screen Shot 2019-11-19 at 10 08 15 AM](https://user-images.githubusercontent.com/11282622/69173458-abbe7c00-0ab4-11ea-81e5-3f7aa13451aa.png)
