### ISSUE TITLE
Azure Function deployment error - Error Message: An error has occured

### ISSUE THREAD

**Issue by rmeneely** [microsoft/vscode-azurefunctions#1701]
Repro steps:

1. Under Functions right-click 'p2pevent' and select 'Deploy to Function App'
2. Select Azure function 'P2PEvents'

Action: azureFunctions.deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:393195
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:636475
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.EventEmitter.emit domain.js:442:20
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
$.EventEmitter.emit domain.js:442:20
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
IncomingMessage.EventEmitter.emit domain.js:442:20
endReadableNT _stream_readable.js:1092:12
glue.js:188:31async-listener/glue.js:188:31
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rmeneely please add more detailed repro steps. Here are some of the basic questions we need to know:
1. What language was your project?
1. Have you ever successfully deployed this project?
1. What type of triggers?
1. How did you create the function app in Azure?

**Comment by rmeneely** [comment]
Hi Eric, thanks for following up. Please see my answers below.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Eric Jizba <notifications@github.com> Date: 11/21/19  2:02 PM  (GMT-08:00) To: microsoft/vscode-azurefunctions <vscode-azurefunctions@noreply.github.com> Cc: rmeneely <rick@meneely.com>, Author <author@noreply.github.com> Subject: Re: [microsoft/vscode-azurefunctions] Azure Function deployment error
  - Error Message: An error has occured (#1701) @rmeneely please add more detailed repro steps. Here are some of the basic questions we need to know:

What language was your project?Node.js
Have you ever successfully deployed this project? Yes, I  created this function app about 6 months ago and it was working fine.  I noticed that I can no longer connect to the Azure function url https://p2pevent.azurewebsites.net and so tried to redeploy the app.  It runs locally, however when I try to deploy via the Azure Functions extension I get the "Error: An error has occured" with no additional detail. I get this error about 2-3 minutes after "Starting deployment" is displayed in the output window.
What type of triggers?Http
How did you create the function app in Azure?I believe I originally created it through the Azure web portal. 


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/vscode-azurefunctions/issues/1701?email_source=notifications\u0026email_token=AAPMVXOUZZQ7SQTR4PLPAWTQU4AQLA5CNFSM4JPX2SGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE3Z2BI#issuecomment-557292805",
"url": "https://github.com/microsoft/vscode-azurefunctions/issues/1701?email_source=notifications\u0026email_token=AAPMVXOUZZQ7SQTR4PLPAWTQU4AQLA5CNFSM4JPX2SGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE3Z2BI#issuecomment-557292805",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EricJizbaMSFT** [comment]
Sorry about the delay here - hopefully you figured out a workaround (create a new function app?) or moved on at this point. Unfortunately the error was coming directly from Azure, not our extension, and there was likely very little we could do. Azure support would be much more helpful
