### ISSUE TITLE
auto-detect c# function app when not in root directory

### ISSUE THREAD

**Issue by richcoresln** [microsoft/vscode-azurefunctions#1705]
If I have the following directory structure:

- root/ (opened in vscode)
  - src/
  - src/MyFunctionApp/ (contains MyFunctionApp.csproj for function app)
  - test/..
  - MyFunctionApp.sln

vscode does not auto-detect the azure function app for debugging (.vscode directory does not contain correct launch config files).
If I move the root/src/MyFunctionApp directory to root/MyFunctionApp, auto-detection works as expected allowing debugging.

If I use the setting "azureFunctions.projectSubpath" set to src/MyFunctionApp then it works as expected, however, this isn't much use when working with multiple projects.

Is there a better way to do this?

**Comment by EricJizbaMSFT** [comment]
@richcoresln take a look at this page and let me know if you still have questions: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

**Comment by richcoresln** [comment]
@EricJizbaMSFT yes, I still have question.
I am currently using the azureFunctions.projectSubpath setting but each time I open a different solution (with the directory structure above) I have to change this value.

**Comment by EricJizbaMSFT** [comment]
I'm still a little confused by your scenario. Are you saying you have to set "azureFunctions.projectSubpath" every time you set up a _new_ solution with that directory structure? Or do you have one existing solution where you constantly have to change that setting for some reason?

**Comment by richcoresln** [comment]
The issue is if there are multiple, different solutions.
The different solutions contain different project names.
Therefore, the projectSubpath needs to be changed each time you wish to switch between solutions.

**Comment by EricJizbaMSFT** [comment]
Do you have an open source project? Could you send me a link on GitHub so I can take a closer look? If not - can you at least send a few screenshots of your repo? Or even create a sample project on GitHub without your real code?
