### ISSUE TITLE
Host runtime error - while deploying Pythone code from VScode to Azure

### ISSUE THREAD

**Issue by gopalvaddi** [microsoft/vscode-azurefunctions#1706]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2797983extension.bundle.js:218:2797983
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>
10:01:19 AWS-OT-func-DEV-01: Waiting for long running command to finish...
10:02:22 AWS-OT-func-DEV-01: Waiting for long running command to finish...
10:03:03 AWS-OT-func-DEV-01: Writing the artifacts to a Zip file
10:03:08 AWS-OT-func-DEV-01: Running post deployment command(s)...
10:03:08 AWS-OT-func-DEV-01: Triggering recycle (preview mode disabled).
10:03:09 AWS-OT-func-DEV-01: Deployment successful.
10:03:23 AWS-OT-func-DEV-01: Syncing triggers...
10:03:50 AWS-OT-func-DEV-01: Syncing triggers (Attempt 2/6)...
10:04:01 AWS-OT-func-DEV-01: Syncing triggers (Attempt 3/6)...
10:04:22 AWS-OT-func-DEV-01: Syncing triggers (Attempt 4/6)...
10:05:47 AWS-OT-func-DEV-01: Syncing triggers (Attempt 5/6)...
10:07:16 AWS-OT-func-DEV-01: Syncing triggers (Attempt 6/6)...
10:07:26: Error: Encountered an error (InternalServerError) from host runtime.

**Comment by EricJizbaMSFT** [comment]
@gopalvaddi unfortunately this error happens somewhat often from Azure and is difficult to diagnose. Could you add more detailed repro steps including:
1. Does it happen consistently?
1. What region?
1. What plan type (consumption/premium/etc.)
1. Is this a brand new project?
1. What type of triggers do the project have?

**Comment by stewrutledge** [comment]
I am having the sdame issue, but from mac os

1. Yes
2. North Europe
3. App Service
4. No, it works on the first deploy with a new project, subsequent have issue
5. Timer, though I've seen it with httpTriggers.

**Comment by EricJizbaMSFT** [comment]
Sorry about the delay here - hopefully you figured out a workaround or moved on at this point. Unfortunately the error was coming directly from Azure, not our extension, and there was likely very little we could do. Azure support would be much more helpful
