### ISSUE TITLE
Unable to deploy HTTPTrigger function to the function app

### ISSUE THREAD

**Issue by jaylamrin** [microsoft/vscode-azurefunctions#1707]
Repro steps:

1. Deploy a local python function to my Azure subscription function app
![2019-11-21_8-58-38](https://user-images.githubusercontent.com/44527922/69355329-d4727d00-0c3e-11ea-8003-4aa5ed935238.png)
[VS Code output deploy FA.txt](https://github.com/microsoft/vscode-azurefunctions/files/3875618/VS.Code.output.deploy.FA.txt)

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2797983extension.bundle.js:218:2797983
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
This seems like the important line:
```
Failed to upload because Azure Storage responds 403.
8:56:09 AM avtdevwus2fasilvercreekplt: This request is not authorized to perform this operation.
```

Do you have permissions for that storage account?

You can also try a new deployment method which doesn't directly access the storage account like that. See https://github.com/microsoft/vscode-azurefunctions/wiki/Remote-Build
