### ISSUE TITLE
Add command to generate local.settings.json file

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurefunctions#1714]
When cloning a repo the `local.settings.json` file often is not in the repo (on purpose). This causes a problem when people clone a repo with functions and want to run them. They have to manually create the file. It would be really nice if the file could be generated from a command using this extension.

Something like this ...

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "node"
  }
}
```

**Comment by johnpapa** [comment]
cc @ColbyTresness @fiveisprime

**Comment by ColbyTresness** [comment]
This is a smart feature to add, and something that might benefit the CLI experience as well @ahmedelnably

**Comment by johnpapa** [comment]
Would you be interested in me creating a PR for this?

If so, please let me know what this file would look like for different language/platforms.

**Comment by ahmedelnably** [comment]
@johnpapa sure, we love any contributions :) the core tools repo is here https://github.com/Azure/azure-functions-core-tools

**Comment by johnpapa** [comment]
awesome. @ahmedelnably - can you point me to where I can see what this file would look like for different language/platforms?

wouldnt this be an addition to the extension?

**Comment by ColbyTresness** [comment]
Ahmed was referring to the CLI experience. For where to contribute this to the extension, @EricJizbaMSFT can help you out

**Comment by EricJizbaMSFT** [comment]
@johnpapa we should already be auto-generating a simple "local.settings.json" when you debug (assuming you don't have one). Can you try on the latest extension? v0.20.0

**Comment by EricJizbaMSFT** [comment]
Closing since we generate this file when users debug now
