### ISSUE TITLE
azureFunctions.createNewProject

### ISSUE THREAD

**Issue by rashmipatil** [microsoft/vscode-azurefunctions#1717]
Repro steps:

1. Create a new function app (C# timer triggered)
2. add value for cron job and click next

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Expected to find a single project file in folder "undefined", but found zero or multiple instead.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
DotnetInitVSCodeStep.<anonymous> extension.bundle.js:1:793397
o extension.bundle.js:1:791679
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rashmipatil can you send a screenshot of your workspace when you get this error? It's possible you already had a csproj in the folder when you tried to create a project and we ran into issues with that. Try creating a project in an empty folder instead
