### ISSUE TITLE
Failed to detect running Functions host within "60" seconds. You may want to adjust 

### ISSUE THREAD

**Issue by SatishPaiB** [microsoft/vscode-azurefunctions#1718]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:75291extension.bundle.js:353:75291
o extension.bundle.js:353:73918
```

</details>

**Comment by nturinski** [comment]
Hi @SatishPaiB

Thanks for reporting.  Please provide repro steps.
