### ISSUE TITLE
Pop up an error when restoring a C# project with .NET Core SDK 2.2.x installed

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1719]
**OS:** Win10
**Build Version**: [20191120.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12597)
**Func Version:** 3.0.1704

**Repro Steps**:
1. Make sure there is no any .NET Core SDKs --> Create a C# project.
2. Pop up an error to prompt the users to install 2.x or 3.x of the .NET Core SDK.
![image](https://user-images.githubusercontent.com/34729092/69719986-a0222380-114c-11ea-95be-ffee1aed40ce.png)
3. Install .NET Core SDK 2.2.207.
4. Create a C# project -->Prompt to restore the C# project.

**Expect:**
Succeed to restore.

**Actual:**
Fail to restore with an error "The current .NET SDK does not support targeting .NET Core 3.0...".
![image](https://user-images.githubusercontent.com/34729092/69718611-c2667200-1149-11ea-8cef-8c2c9e088092.png)

**More Info:**
Restore C# projects well with .NET Core SDK 3.0.101 installed.

**Comment by EricJizbaMSFT** [comment]
So here's the problem:
1. User has v3 of the func cli
1. We tell them to install 2.x or 3.x of the .NET Core sdk
1. If user installs 2.x, they run into a mismatch because the default template uses 3.x

Users can work around this by modifying the target framework directly in the csproj to 2.x. Not exactly sure what we should do here

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing. 
So we need to make sure the version of .NET Core SDK matches the version of func cli?

**Comment by EricJizbaMSFT** [comment]
@v-dantch you don't need to do anything for now. We still have to decide how to handle this scenario

**Comment by v-dantch** [comment]
Got it :) .

**Comment by EricJizbaMSFT** [comment]
Let's change our error message to tell people 3.x is recommended
