### ISSUE TITLE
Error when creating azure funtion via VScode

### ISSUE THREAD

**Issue by moedeveloper** [microsoft/vscode-azurefunctions#1720]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to get latest templates: Command "dotnet "c:\Users\momor1\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.20.0\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\momor1\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\momor1\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~3.nupkg" --operation list" failed with exit code "2147516566":
It was not possible to find any compatible framework version
T...

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@moedeveloper please check to make sure you have the [.NET Core sdk](https://dotnet.microsoft.com/download) installed 

Here's more info about what version to use: https://docs.microsoft.com/azure/azure-functions/functions-versions
