### ISSUE TITLE
No way to connect to the log stream

### ISSUE THREAD

**Issue by ernestoalarcongallo** [microsoft/vscode-azurefunctions#1721]
Repro steps:

1.
2.

Action: azureFunctions.startStreamingLogs
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078
extension.js:229:46161
extension.js:229:44154
extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
