### ISSUE TITLE
Fail to debug the C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1722]
**OS:** Ubuntu 19.04
**Build Version:** [20191120.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12597)
**Func Version:** 2.7.1948
**.NET Core SDK:** 3.0.101

**Repro Steps:**
1. Create a C# project with HttpTrigger function in VS Code.
2. Set a breakpoint.
3. F5.

**Expect:**
Debug the project successfully.

**Actual:**
Fail to debug the C# project.
![image](https://user-images.githubusercontent.com/45614674/69796230-9b22aa00-1208-11ea-9dd5-012670ff78d3.png)
![image](https://user-images.githubusercontent.com/45614674/69796247-9f4ec780-1208-11ea-9046-dd40de550a36.png)

**More Info:**
This issue does not reproduce on Windows and Mac.

**Comment by EricJizbaMSFT** [comment]
v2 of the func cli doesn't support .NET Core 3.0. Per the errors shown in the build task, you have to install v2.x of the .NET Core sdk.

**Comment by v-ruizh** [comment]
@EricJizbaMSFT Thanks for your guidance. We can debug C# project successfully with .NET Core 2.2.
