### ISSUE TITLE
Debug (F5) starts the func host but it stops immediately

### ISSUE THREAD

**Issue by lbugnion** [microsoft/vscode-azurefunctions#1727]
**Summary**

On 2 different Windows machines, I am able to start debugging an HTTP Triggered function in VS Code with dotnet core, but as soon as the func host starts, it ends without any error message.

**Repro**

1. Install VS Code on a Windows machine.
1. Install all the tools needed to run functions.
1. Create a new HTTP Triggered function
1. Select Debug from the menu

Result: The func host starts in the Terminal and shows the URL for the function to be triggered. However before anything can be done, the func host stops without error messages.

**Note**

I have this error running in a VM on Azure, in case the team wants to check it out and is unable to repro.

When starting the Function via Terminal / func start, everything runs just fine. It's just when starting via Debug menu that this happens.

**Logs**

[FunctionsLog.txt](https://github.com/microsoft/vscode-azurefunctions/files/3912842/FunctionsLog.txt)

**Comment by EricJizbaMSFT** [comment]
Per offline discussions sounds like it could be caused by installing the func cli with choco https://github.com/Azure/azure-functions-core-tools/issues/693

**Comment by TroyWitthoeft** [comment]
+ 1 I am experiencing this too.   Yes, I installed the func cli with choco.

**Comment by 23min** [comment]
Pause or quit your Dropbox client

**Comment by TroyWitthoeft** [comment]
For others that land here, as of Feb 2020, you can choco install the azure functions core tools with the 64-bit debugger using the following command. 

`choco install azure-functions-core-tools --params "'/x64:true'"`

**Comment by EricJizbaMSFT** [comment]
Thanks for the update @TroyWitthoeft. You are correct that should work for people. Since we don't install with choco for users, I'll go ahead and close our issue here
