### ISSUE TITLE
Running Locally behind a firewall

### ISSUE THREAD

**Issue by 20v100** [microsoft/vscode-azurefunctions#1731]
I'm probably making a newbie mistake here, but I couldn't find any working solutions here or in StackOverflow.

I get the following error when running the debugger:  ```failed to attach (connect ECONNREFUSED 127.0.0.1:9091).```

The terminal error is: ```A host error has occurred during startup operation '95caa2be-164e-42a2-950f-14e169ad7627'.
[2019-12-04 17:29:16] System.Net.Http: No such host is known. System.Private.CoreLib: No such host is known.
Value cannot be null.
Parameter name: provider```

**I only get the error if a work behind a firewall.**

Setting proxies in the setting.json (user-level settings) did not work. 

The solutions in [https://github.com/microsoft/vscode-azurefunctions/issues/892](https://github.com/microsoft/vscode-azurefunctions/issues/892) did not work.

More details:
- python 3.7.3 in virtual env.
- Windows 10

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9091,
            "preLaunchTask": "func: host start",
        }
    ]
}

```
settings.json (workspace):
```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.scmDoBuildDuringDeployment": true,
    "azureFunctions.pythonVenv": ".venv",
    "azureFunctions.projectLanguage": "Python",
    "azureFunctions.projectRuntime": "~2",
    "debug.internalConsoleOptions": "neverOpen",
    "python.pythonPath": ".venv\\Scripts\\python.exe",
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true
}

```
settings.json (user)
```
{
    "terminal.integrated.rendererType": "dom",
    "workbench.colorTheme": "Dracula",
    "http.systemCertificates": false,
    "http.proxySupport": "on",
    "http.proxyStrictSSL": false
    "http.proxy": "http://xxx:xxx@xxx:8080"
}

```

**Comment by EricJizbaMSFT** [comment]
@20v100 can you copy the full log from the "func host start" task?

**Comment by 20v100** [comment]
Should I add my proxy to the Windows command? ```"command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
```

task.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "func",
            "command": "host start",
            "problemMatcher": "$func-watch",
            "isBackground": true,
            "dependsOn": "pipInstall"
        },
        {
            "label": "pipInstall",
            "type": "shell",
            "osx": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "windows": {
                "command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
            },
            "linux": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by EricJizbaMSFT** [comment]
No I don't think you need to add proxy in that place. Can you copy the full terminal log here?

Also double check any storage connection strings you're using in local.settings.json. I vaguely remember seeing a similar error when I my connection string was for an account that had been deleted

**Comment by 20v100** [comment]
@EricJizbaMSFT updating the connection strings did not solve the issues.

The terminal log:
'''> Executing task: .venv\Scripts\python -m pip install -r requirements.txt --proxy http://a324448:VV432432vb@cloudpxgso1.srv.volvo.com:8080 <

Requirement already satisfied: azure-functions in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 1)) (1.0.5)
Requirement already satisfied: azure-storage-blob in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 2)) (12.0.0)
Requirement already satisfied: pandas in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 3)) (0.25.3)
Requirement already satisfied: xlrd in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: XlsxWriter in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 5)) (1.2.6)
Requirement already satisfied: gensim in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 6)) (3.8.1)
Requirement already satisfied: tensorflow in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 7)) (2.0.0)
Requirement already satisfied: scikit-learn in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 8)) (0.21.3)
Requirement already satisfied: nltk in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 9)) (3.4.5)
Requirement already satisfied: keras in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from -r requirements.txt (line 10)) (2.3.1)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: msrest>=0.6.10 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (0.6.10)
Requirement already satisfied: azure-core<2.0.0,>=1.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from pandas->-r requirements.txt (line 3)) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from pandas->-r requirements.txt (line 3)) (1.17.4)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from pandas->-r requirements.txt (line 3)) (2.8.1)
Requirement already satisfied: six>=1.5.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from gensim->-r requirements.txt (line 6)) (1.13.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from gensim->-r requirements.txt (line 6)) (1.9.0)
Requirement already satisfied: scipy>=0.18.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from gensim->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (0.8.1)
Requirement already satisfied: tensorboard<2.1.0,>=2.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (2.0.2)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (1.25.0)
Requirement already satisfied: wheel>=0.26 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (0.33.6)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (1.0.8)
Requirement already satisfied: tensorflow-estimator<2.1.0,>=2.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (0.8.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (3.1.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (3.11.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: gast==0.2.2 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (0.2.2)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (1.11.2)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorflow->-r requirements.txt (line 7)) (0.1.8)
Requirement already satisfied: joblib>=0.11 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from scikit-learn->-r requirements.txt (line 8)) (0.14.0)
Requirement already satisfied: h5py in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from keras->-r requirements.txt (line 10)) (2.10.0)
Requirement already satisfied: pyyaml in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from keras->-r requirements.txt (line 10)) (5.1.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from cryptography>=2.1.4->azure-storage-blob->-r requirements.txt (line 2)) (1.13.2)
Requirement already satisfied: requests~=2.16 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: isodate>=0.6.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2))
(2019.9.11)
Requirement already satisfied: requests-oauthlib>=0.5.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: boto>=2.32 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from smart-open>=1.8.1->gensim->-r requirements.txt (line 6)) (2.49.0)
Requirement already satisfied: boto3 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from smart-open>=1.8.1->gensim->-r requirements.txt (line 6)) (1.10.28)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (1.7.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (42.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (0.4.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (0.16.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7))
(3.1.1)
Requirement already satisfied: pycparser in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4->azure-storage-blob->-r requirements.txt (line 2)) (2.19)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from requests~=2.16->msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from requests~=2.16->msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (1.25.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from requests~=2.16->msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from requests-oauthlib>=0.5.0->msrest>=0.6.10->azure-storage-blob->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from boto3->smart-open>=1.8.1->gensim->-r requirements.txt (line
6)) (0.2.1)
Requirement already satisfied: botocore<1.14.0,>=1.13.28 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from boto3->smart-open>=1.8.1->gensim->-r requirements.txt (line 6)) (1.13.28)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from boto3->smart-open>=1.8.1->gensim->-r requirements.txt (line 6)) (0.9.4)
Requirement already satisfied: cachetools<3.2,>=2.0.0 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (3.1.1)
Requirement already satisfied: rsa<4.1,>=3.1.4 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (0.2.7)
Requirement already satisfied: docutils<0.16,>=0.10 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from botocore<1.14.0,>=1.13.28->boto3->smart-open>=1.8.1->gensim->-r
requirements.txt (line 6)) (0.15.2)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\a324448\onedrive - volvo group\az_func\fc191126\.venv\lib\site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow->-r requirements.txt (line 7)) (0.4.8)

Terminal will be reused by tasks, press any key to close it.

> Executing task: .venv\Scripts\activate ; func host start <

Found Python version 3.7.3 (python).

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0
[2019-12-09 22:42:53] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'ea21884f-df1e-44f9-a391-365f9258d287'
[2019-12-09 22:42:53] Reading host configuration file 'C:\Users\a324448\OneDrive - Volvo Group\az_func\fc191126\host.json'
[2019-12-09 22:42:53] Host configuration file read:
[2019-12-09 22:42:53] {
[2019-12-09 22:42:53]   "version": "2.0",
[2019-12-09 22:42:53]   "extensionBundle": {
[2019-12-09 22:42:53]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2019-12-09 22:42:53]     "version": "[1.*, 2.0.0)"
[2019-12-09 22:42:53]   }
[2019-12-09 22:42:53] }
[2019-12-09 22:42:54] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\a324448\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[2019-12-09 22:42:54] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2019-12-09 22:42:54] A host error has occurred during startup operation 'ea21884f-df1e-44f9-a391-365f9258d287'.
[2019-12-09 22:42:54] System.Net.Http: No such host is known. System.Private.CoreLib: No such host is known.
Value cannot be null.
Parameter name: provider
Application is shutting down...
[2019-12-09 22:42:54] Initialization cancellation requested by runtime.
Hosting environment: Production
Content root path: C:\Users\a324448\OneDrive - Volvo Group\az_func\fc191126
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[2019-12-09 22:42:54] Stopping host...
[2019-12-09 22:42:54] Host shutdown completed.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
'''

**Comment by pauldj54** [comment]
Hi everyone, 
I am facing the same issue, I cannot work behind the company proxy and firewall.
I may need to create some rules.
I can sign-in into my azure account, but then I am not able to navigate the subscriptions.
At home in my private network works.

![image](https://user-images.githubusercontent.com/706754/73746130-d683ac80-4754-11ea-9811-8978915e6458.png)

Any help will be appreciated.
Best, 
Paul

**Comment by EricJizbaMSFT** [comment]
We use standard VS Code support for proxies. Make sure you have everything configured as described here: https://code.visualstudio.com/docs/setup/network

You might have better luck filing an issue about this on VS Code
