### ISSUE TITLE
WEBSITE_CONTENTSHARE should not be removed when deploying to Linux Premium

### ISSUE THREAD

**Issue by Hazhzeng** [microsoft/vscode-azurefunctions#1733]
When testing v0.20.0, deploying to a Linux Premium function app will remove the following app settings.
- WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
- WEBSITE_CONTENTSHARE

According to the conversation with Paul, https://github.com/microsoft/vscode-azurefunctions/issues/1682#issuecomment-555769696
We should **not** remove these two app settings when doing deployment.

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1682
