### ISSUE TITLE
Entry not found in cache VS Code error during deploy of new function app

### ISSUE THREAD

**Issue by lhale** [microsoft/vscode-azurefunctions#1734]
(

Repro steps:

1. per docs @ https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-04
2. Basic and advanced results in same "Entry not found in cache" error when submitting unique app name

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49056
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46161extension.js:229:46161
extension.js:229:44154extension.js:229:44154
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
init.then extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
