### ISSUE TITLE
JavaScript Azure Function, error during deploy to azure function app and NodeJs 10

### ISSUE THREAD

**Issue by eduflornet** [microsoft/vscode-azurefunctions#1737]
Repro steps:

1. Create new project azure funtion
2. I have selected: javascript language
3.- After that F1, I selected > Azure Functions: Deploy to Function App
4.- I selected : Create new Function App in Azure,
5.- I selected : NodeJs 10x
6.- finally in this moment it was failed.

 

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46161extension.js:229:46161
extension.js:229:44154extension.js:229:44154
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
