### ISSUE TITLE
BadRequest deploying azure function with vscode

### ISSUE THREAD

**Issue by mahuge** [microsoft/vscode-azurefunctions#1741]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2797983extension.bundle.js:218:2797983
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mahuge please add repro steps

**Comment by mahuge** [comment]
Repro Steps:
1. Started Deployment of Azure function via VS Code Context Menu -> Deploy Azure Function
2. Chose the already existing Azure Function over the dropdown menu 

But it looks like it just happend once.

**Comment by EricJizbaMSFT** [comment]
Yeah unfortunately InternalServerError can happen from time to time in Azure and there's not much we can do about it from VS Code. If it is happening consistently for you feel free to reopen with more details.
