### ISSUE TITLE
Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker'

### ISSUE THREAD

**Issue by nnekaede** [microsoft/vscode-azurefunctions#1744]
I am no expert in functions, so please bear with me. 

But I have a PowerShell Function App which I would like to build and test locally. Previously, I could run locally with no issue, but now this is no the case. When I type `func host start` or F5, I am prompted with the following error: 

> You must have the Azure Functions Core Tools installed to debug your local functions.

When I click install, I get the following error: 

> Could not attach to process with CustomPipeName: 'AzureFunctionsPSWorker'

**Comment by EricJizbaMSFT** [comment]
Looks like this is mostly being handled here: https://github.com/Azure/azure-functions-powershell-worker/issues/368 Sounds like this is an issue related to using git bash as the default terminal
