### ISSUE TITLE
Python functions cannot reliabely sync triggers with vnet

### ISSUE THREAD

**Issue by stewrutledge** [microsoft/vscode-azurefunctions#1746]
I have a function app with a vpn VNET that I am attempting to use python on. Syncing triggers typically only works on the first deploy, and fails on subsequent deploys.

Repro steps:

It's a little unclear what is actually causing the triggers to no longer sync, however I have done:

1. Create function app on app standard app service plan
2. Choose python 3.7 and linux os
3. Deploy function(s) to function app (this usually works)
4. Setup Vnet integration for site to site VPN
5. Deploy again and get the following:

10:07:00 AM MyFunctionApp: Syncing triggers (Attempt 2/6)...
10:08:08 AM MyFunctionApp: Syncing triggers (Attempt 3/6)...
10:09:26 AM MyFunctionApp: Syncing triggers (Attempt 4/6)...
10:11:03 AM MyFunctionApp: Syncing triggers (Attempt 5/6)...
10:13:22 AM MyFunctionApp: Syncing triggers (Attempt 6/6)...
10:14:16 AM: Error: Encountered an error (InternalServerError) from host runtime.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2797976
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:673009
extension.bundle.js:164:24705
$._callback extension.bundle.js:1:632208
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by stewrutledge** [comment]
After some trial and error this seems to only be a problem when I have the vnet attached.

Is this not a supported configuration?

**Comment by EricJizbaMSFT** [comment]
@stewrutledge It seems like a vnet should be supported based on [this tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-vnet). Can you describe exactly how you configured your vnet so that I can try to repro? It's entirely possible the problem is on the Azure side instead of the VS Code side, in which case you might have better luck getting help as described here: https://github.com/Azure/Azure-Functions#questions--help
