### ISSUE TITLE
28162af9ada7d6fbb8cbbfba5e5053fe1ca4ca5957f7b1c2012ebc67f0ce75f5

### ISSUE THREAD

**Issue by 65398t** [microsoft/vscode-azurefunctions#1748]
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: LocationNotAvailableForResourceType
Error Message: The provided location 'germanywestcentral' is not available for resource type 'Microsoft.Storage/storageAccounts'. List of available regions for the resource type is 'eastus,eastus2,westus,westeurope,eastasia,southeastasia,japaneast,japanwest,northcentralus,southcentralus,centralus,northeurope,brazilsouth,australiaeast,australiasoutheast,southindia,centralindia,westindia,canadaeast,canadacentral,westus2,westcentralus,uksouth,ukwest,koreacentral,koreasouth,francecentral,australiacentral,southafricanorth,uaenorth'.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:738885extension.bundle.js:218:738885
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:673009
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:632208
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
```

</details>

**Comment by EricJizbaMSFT** [comment]
@65398t please add repro steps and/or try a different region
