### ISSUE TITLE
Issue while debugging Azure function for viscose + Mac

### ISSUE THREAD

**Issue by nemana** [microsoft/vscode-azurefunctions#1749]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:83493
l.fire extensionHostProcess.js:47:207
m.$onDidEndTaskProcess extensionHostProcess.js:695:468
```

</details>

**Comment by EricJizbaMSFT** [comment]
@nemana please check the logs from the "clean" task. If you still need help after that, please add more detailed repro steps
