### ISSUE TITLE
Unable to create c# function project

### ISSUE THREAD

**Issue by leewadhams** [Microsoft/vscode-azurefunctions#175]
I have the following pre-requisites installed in VS code but when creating a function app I only get "javascript" and "java" as options in the language selection dropdown.

OS: MacOS High Sierra 10.13.2
.Net Core: 2.0.3
Azure Functions Core Tools: 2.0.1-beta.22
VS Code: 1.19.2
C# Extension: 1.13.1
Azure Functions Extension: 0.4.0

Update: If I try to select "Java" it reports that I don't have "maven" set on PATH (which is true). So questioning the correctness of this option. Could it be showing the wrong options here? Java instead of c#?

**Comment by EricJizbaMSFT** [comment]
The README in this repo has features that have not been released yet. We plan to release C# support in version [0.5.0](https://github.com/Microsoft/vscode-azurefunctions/milestone/8) of the extension.

Please see the README in the VS Code marketplace for the latest _released_ features https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

**Comment by leewadhams** [comment]
Thanks @EricJizbaMSFT 
My bad :-(
