### ISSUE TITLE
You must have the Azure Functions Core Tools installed to debug your local functions

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-azurefunctions#1750]
Today, VS Code Insiders refused to run my Functions project suddenly claiming that the Functions Core Tools needed to be installed. 

I was able to run `func start` from the integrated terminal. 

Executing "Reload Window" resolved the issue.

![image](https://user-images.githubusercontent.com/686963/70742244-b4d0f080-1ce2-11ea-92e6-964dba4af1e1.png)

**Comment by EricJizbaMSFT** [comment]
We check for `func` in your path. It's possible Insiders had a bug where they weren't loading environment variables properly or something. If this persists please let us know

**Comment by galgrunfeld-madtrix** [comment]
I'm having the same issue.

I installed a new VSCode installation on a new Windows installation, installed Node.js v13.6.0 via NVM for Windows, installed the package (v2) and it started claiming this from the beginning which doesn't make sense to me. I have the dep on `package.json` and can get the version for the package via `nvm` so it seems it was installed correctly.

**Comment by EricJizbaMSFT** [comment]
@galgrunfeld-madtrix the func cli needs to be installed as a global npm package and on your path, not in your package.json just for that project. You can verify by opening a terminal and running `func --version`. If it fails, that means it's not in your path.

Run the following to install v2 globally:
```
npm install -g azure-functions-core-tools
```
