### ISSUE TITLE
Improve error message when Add Binding is not supported from command palette

### ISSUE THREAD

**Issue by jaypaddy** [microsoft/vscode-azurefunctions#1751]
Repro steps:

1.
2.

Action: azureFunctions.addBinding
Error type: Error
Error Message: No matching resources found.

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:1:628415
o extension.bundle.js:1:622925
```

</details>

**Comment by EricJizbaMSFT** [comment]
Similar to https://github.com/microsoft/vscode-azurefunctions/issues/1561, we don't support Add Binding in a few situations - probably not for your project language. Just need to do a better error message here.
