### ISSUE TITLE
Error "Invalid Version: 2.7.15+" when creating new python project

### ISSUE THREAD

**Issue by sgodfreys** [microsoft/vscode-azurefunctions#1754]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: TypeError
Error Message: Invalid Version: 2.7.15+

Version: 0.20.1
OS: linux
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
new W extension.bundle.js:1:172662
oe.test extension.bundle.js:1:183826
Function.ce [as satisfies] extension.bundle.js:1:178804
extension.bundle.js:1:801512
Object.t.isSupportedPythonVersion extension.bundle.js:1:801502
extension.bundle.js:164:360847
o extension.bundle.js:164:359890
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sgodfreys this is related to our logic of creating a virtual environment. Looks like there's a version we don't expect with a plus sign at the end. Can you copy the output of `python --version` here?

As a workaround, you have two options:
1. Create a virtual environment before you create the project:
    1. Open the folder you want the project in
    1. Run `python3 -m venv .venv` (You must use either v3.6 or v3.7 of python, hence why I used `python3` as the alias)
    1. Create a project
1. Skip creating a virtual environment altogether
    1. Set `azureFunctions.createPythonVenv` to `false` in your VS Code user settings before creating a project
