### ISSUE TITLE
Please get the local certificate

### ISSUE THREAD

**Issue by vdhosi** [microsoft/vscode-azurefunctions#1755]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.32.3
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1055:34
TLSSocket.emit events.js:182:13
TLSSocket.EventEmitter.emit domain.js:442:20
TLSSocket._finishInit _tls_wrap.js:635:8
```

</details>

**Comment by EricJizbaMSFT** [comment]
@vdhosi please add detailed repro steps. In addition, take a look at these docs if you're working behind a proxy: https://code.visualstudio.com/docs/setup/network
