### ISSUE TITLE
Error Message: unable to get local issuer certificate

### ISSUE THREAD

**Issue by snmishra7** [microsoft/vscode-azurefunctions#1756]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:200:13
TLSSocket.EventEmitter.emit domain.js:471:20
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by EricJizbaMSFT** [comment]
@snmishra7 please add detailed repro steps. In addition, take a look at these docs if you're working behind a proxy: https://code.visualstudio.com/docs/setup/network
