### ISSUE TITLE
java project not running for debug in vscode

### ISSUE THREAD

**Issue by acoroian** [microsoft/vscode-azurefunctions#1757]
Could not find the task 'mvn azure-functions:run'. this is the error i get when i press play to start the project.

Command line works
 mvn clean package then
mvn azure-functions:run

**Comment by EricJizbaMSFT** [comment]
@acoroian I'm not familiar with the "mvn azure-functions:run" task. When I debug a java project it runs "mvn clean package" and then "func host start". Perhaps send some screenshots so I can see what you're talking about?
