### ISSUE TITLE
The terminal process terminated with exit code: 1

### ISSUE THREAD

**Issue by beraybentesen** [microsoft/vscode-azurefunctions#1762]
Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.20.1
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:83493
l.fire extensionHostProcess.js:48:519
v.$onDidEndTaskProcess extensionHostProcess.js:732:104
```

</details>

**Comment by EricJizbaMSFT** [comment]
@beraybentesen please check the output of the task for more info and add detailed repro steps if you're still stuck
