### ISSUE TITLE
create new templete azure functions f5 error

### ISSUE THREAD

**Issue by billjonescn** [microsoft/vscode-azurefunctions#1763]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:83493
l.fire extensionHostProcess.js:46:893
v.$onDidEndTaskProcess extensionHostProcess.js:730:664
```

</details>

**Comment by EricJizbaMSFT** [comment]
@billjonescn please check the output of the task for more info and add detailed repro steps if you're still stuck
