### ISSUE TITLE
The running preDeployTask "publish" task isn't stopped after clicking "Terminate Task" button

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1765]
**OS:** All
**Build Version:** [20191218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13217&view=results)
**Func Version:** 2.7.1948

**Repro Steps:**

1. Create 2 Function App with .NET runtime.
2. Create a C# project.
3. Deploy this C# project to these 2 created Function App almost the same time.
4. The notification "Running preDeployTask 'publish'" and "The task publish(cs) is already active" pop up.
![image](https://user-images.githubusercontent.com/45614674/71240937-51c80500-2345-11ea-9cce-b4829e7d3bd6.png)
5. Click "Terminate Task" button in the notification.

**Expect:**
The running preDeployTask "publish" task is stopped.

**Actual:**
The running preDeployTask "publish" task isn't stopped.
![image](https://user-images.githubusercontent.com/45614674/71241054-9653a080-2345-11ea-99c3-1f017d023a2f.png)

**More Info:**
Fail to restart the "publish" task after clicking "Restart Task" button.
![image](https://user-images.githubusercontent.com/45614674/71240800-057cc500-2345-11ea-9563-b5041f268dd5.png)

**Comment by EricJizbaMSFT** [comment]
This was improved as a part of https://github.com/microsoft/vscode-azuretools/pull/679

If I terminate the task, the "Running predeploy" task message goes away and I see this error:
<img width="466" alt="Screen Shot 2020-05-12 at 4 54 53 PM" src="https://user-images.githubusercontent.com/11282622/81756773-87df6000-9471-11ea-973f-bac82753233b.png">

Which feels reasonable given that the path won't exist unless you let the "dotnet publish" task finish.
