### ISSUE TITLE
can't create python3.6 runtime

### ISSUE THREAD

**Issue by tamitarai** [microsoft/vscode-azurefunctions#1768]
Repro steps:

1.open the Command Palette (F1)
2.select the Azure Function
3. Create Function App in Azure command
4. enter name
5.  “Python 3.6.x” runtime

Action: azureFunctions.createFunctionAppAdvanced
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46161extension.js:229:46161
extension.js:229:44154extension.js:229:44154
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
