### ISSUE TITLE
Trying to deploy function from code error

### ISSUE THREAD

**Issue by IkePCampbell** [microsoft/vscode-azurefunctions#1769]
Repro steps:

1. Click deploy on function extension

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46161extension.js:229:46161
extension.js:229:44154extension.js:229:44154
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by IkePCampbell** [comment]
Lmao my bad just needed a restart

**Comment by EricJizbaMSFT** [comment]
Yeah we're tracking that issue here https://github.com/microsoft/vscode-azure-account/issues/53, but as you discovered it's easy to workaround
