### ISSUE TITLE
version issue with VScode plugin

### ISSUE THREAD

**Issue by GogineniManojkumar** [microsoft/vscode-azurefunctions#1770]
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: TypeError
Error Message: Invalid Version: 2.7.15+

Version: 0.20.1
OS: linux
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
new W extension.bundle.js:1:172662
oe.test extension.bundle.js:1:183826
Function.ce [as satisfies] extension.bundle.js:1:178804
extension.bundle.js:1:801512
Object.t.isSupportedPythonVersion extension.bundle.js:1:801502
extension.bundle.js:164:360847
o extension.bundle.js:164:359890
```

</details>

**Comment by EricJizbaMSFT** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1754. Please see that issue for recommended workarounds
