### ISSUE TITLE
npm azure core tool installation

### ISSUE THREAD

**Issue by venkateswarluaduru** [microsoft/vscode-azurefunctions#1775]
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:111874
o extension.bundle.js:1:110912
```

</details>

**Comment by EricJizbaMSFT** [comment]
@venkateswarluaduru check the output window for more details. If that doesn't help, please copy the output here and add repro steps
