### ISSUE TITLE
Auto complete even the remote directory name is not exist on local(development) machine.

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-azurefunctions#1778]
Since I am developing [Azure Function application using Python](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#folder-structure),
I usually create a custom class file and put them in the `__app__` folder of the function app, but the autocomplete is not working for `__app__` as it does not really exist on my development machine, but the code below will works fine when I deploy it to Azure Function App host.
![image](https://user-images.githubusercontent.com/21082770/71391155-97324e00-2635-11ea-8187-1826a2394309.png)

I want a feature that VSCODE can autocomplete even the `__app__` folder is not exist on my development machine, the solution can be adding some mapping to the `.vscode/settings.json` like
```json
"pathMappingRemote": "__app__",
"pathMappingLocal": "/path/to/my_proj/"
```

**Comment by noppGithub** [comment]
@fiveisprime Thank you for the guess, I think I may have to create a ticket in Azure Portal and let Microsoft work from there or maybe I have to post an issue at https://github.com/Azure/Azure-Functions since this is specific when I develop the Azure Function only.

**Comment by fiveisprime** [comment]
I'd recommend reaching out to the folks that work on the python extension first, open an issue here: https://github.com/Microsoft/vscode-python
