### ISSUE TITLE
Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.

### ISSUE THREAD

**Issue by spjeff** [microsoft/vscode-azurefunctions#1779]
Error with new project after following steps at https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio

"host.json" file exists in VSCode open folder.   Same as Terminal current working folder.

Any suggestions welcome.  Thank you.

![b](https://user-images.githubusercontent.com/5648223/71944627-02c60080-318a-11ea-8364-dff46696f5ce.png)

Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:84157extension.bundle.js:353:84157
o extension.bundle.js:353:81769
```

</details>

**Comment by EricJizbaMSFT** [comment]
What is your default terminal? If it's Powershell - do you by chance have a profile that is running `Set-Location` to use a different default folder? We had people run into that problem as mentioned [here](https://github.com/microsoft/vscode-azurefunctions/issues/1260#issuecomment-489612400)
