### ISSUE TITLE
Debugger is not working

### ISSUE THREAD

**Issue by mshinnie** [microsoft/vscode-azurefunctions#1781]
Issue Type: <b>Bug</b>

Debugger can not attach to an azure function I am running since it is a 32 bit process.  I am not sure how to turn this into a 64 bit process.  Thanks.

Extension version: 0.20.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EricJizbaMSFT** [comment]
Hopefully this will help: https://github.com/microsoft/vscode-azurefunctions/wiki/Debug-.NET-Framework-functions
