### ISSUE TITLE
Tengo problemas para correr mi aplicación de Azure Functions

### ISSUE THREAD

**Issue by anderking** [microsoft/vscode-azurefunctions#1782]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:83493extension.bundle.js:353:83493
l.fire extensionHostProcess.js:46:893
v.$onDidEndTaskProcess extensionHostProcess.js:730:664
```

</details>

**Comment by anderking** [comment]
C:\Program Files\dotnet\sdk\3.1.100\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: No se encuentran los ensamblados de referencia para .NETFramework,Version=v4.6.1. Para resolver este problema, instale el Paquete de desarrollador (SDK o Paquete de compatibilidad) de esta versión de .NET Framework o redestine la aplicación. Para descargar los paquetes de desarrollador de .NET Framework, vaya a https://aka.ms/msbuild/developerpacks [c:\Users\Erinson\Desktop\AzureFunctions\AzureFunctions.csproj]

**Comment by EricJizbaMSFT** [comment]
You have to install the .NET Core SDK as described in the above error. https://aka.ms/msbuild/developerpacks
