### ISSUE TITLE
VS Code corruption after trying to run Azure function

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1789]
VS Code 1.41.1 on macOS.

After creating new Azure functions I pressed "F5" in order to run them.
The debug toolbar appeared but nothing was running in the VS Code terminal.

After restarting VS Code I got this dialog on startup:

![2020-01-14_15-35-25](https://user-images.githubusercontent.com/1898161/72353956-2dadd880-36e5-11ea-896c-56993e99717d.png)

Even restarting macOS did not help. 

After deleting VS Code and downloading and installing VS Code, things came back to normal.

It looks like something modified the VS Code installation.

**Comment by arjun27** [comment]
Ran into the same issue, and was quite crippling. A basic reinstall did not help, and I had to clean up my installation (with https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec) and then reinstall again.

**Comment by EricJizbaMSFT** [comment]
@weinand is there anything in particular that makes you think this is a bug in the extension vs. VS Code itself? Any tips for investigating? I've never seen that before and I can't think of any reason our code would be modifying the VS Code installation.
