### ISSUE TITLE
Show an "Open in Browser" action for Azure functions based on the HTTP template

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1791]
Most context menus for the items in the "Azure Function" view are pretty bleak...
I suggest to take any opportunity to add some helpful functionality.
E.g. have an "Open in Browser" action for Azure functions based on the HTTP template.
In this case it even would make sense to have the double-click action associated with "Open in Browser".

**Comment by EricJizbaMSFT** [comment]
We don't want to do both "Open in Browser" and "Copy Function Url" and the second option gives more flexibility for users to use curl (instead of a browser) or modify the url with parameters, etc.
