### ISSUE TITLE
C# Scripts cannot be debugged on Windows

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurefunctions#180]
It appears that the C# Script is attached, but does not hit breakpoints.

I am on Windows 10 with Function Runtime Version: 2.0.11370.0.

**Comment by timmyreilly** [comment]
Is this working now?

**Comment by EricJizbaMSFT** [comment]
@timmyreilly no it's still not working. We prioritized C# Class libraries over C# Scripts, so I'm not sure if/when we'll get to this.

**Comment by EricJizbaMSFT** [comment]
No plans to improve this - we recommend people use C# class libraries
