### ISSUE TITLE
Consider to support remote debugging Azure functions

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1801]
Local debugging of Azure functions does not allow to get a faithful picture of the context that the function will have when running in production on Azure.

It would be great if the function could be debugged remotely on Azure.

**Comment by EricJizbaMSFT** [comment]
We already support java/node.js remote debugging under a feature flag. See settings here: https://github.com/microsoft/vscode-azurefunctions#features

C# is tracked here: https://github.com/microsoft/vscode-azurefunctions/issues/1622

We don't plan to invest any more heavily until we hear more users asking for this
