### ISSUE TITLE
[Suggestion] Add the "PowerShell" runtime to runtime list when creating a Linux Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1816]
**OS:** All
**Build Version:** [20200118.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13926&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression

**Repro Steps:**
1. F1->Azure Functions: Create Function App in Azure...->Enter a name->Select Linux OS.
2. Check the runtime list.

**Actual:**
There is no "PowerShell" runtime.
![image](https://user-images.githubusercontent.com/45614674/72679114-02f9c080-3ae7-11ea-9530-630eb46d329a.png)

**Suggestion:**
Add the "PowerShell" runtime to runtime list. 

**More Info:**
Powershell project can be deployed successfully to one Linux Function App which runtime setting changed to "powershell".

**Comment by EricJizbaMSFT** [comment]
I'm not super worried about this because I don't think PowerShell is officially supported on Linux. I'm surprised it can be successfully deployed

**Comment by EricJizbaMSFT** [comment]
@fiveisprime didn't you ping someone about this?

**Comment by fiveisprime** [comment]
Here's the response I received:

> We don't support PowerShell for Linux Consumption.
