### ISSUE TITLE
The outside C# project runtime is ~2 after initialing it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1817]
**OS:** All
**Build Version:** [20200118.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13926&view=artifacts&type=publishedArtifacts)
**Function Core tools:** 3.0.2009
**.NET Core:** 3.0.101
**Regression:** Not a Regression

**Repro Steps:**
1. Create a C# project with func cli using the following command:
    func init --worker-runtime dotnet
    func new --template HttpTrigger --name HttpTrigger1
2. Open this C# project in VS Code.
3. Select "Yes" to initial this project.
![image](https://user-images.githubusercontent.com/45614674/72712185-7f52d900-3ba5-11ea-87c5-3e42f2ce62bd.png)
4. Check the "azureFunctions.projectRuntime" version.

**Expect:**
The project runtime version is ~3.
![image](https://user-images.githubusercontent.com/45614674/72712482-1455d200-3ba6-11ea-92bb-560f0a639132.png)

**Actual:**
The project runtime version is ~2.
![image](https://user-images.githubusercontent.com/45614674/72712470-0bfd9700-3ba6-11ea-9e5c-47cabcf59d57.png)

**More Info:**
This issue does not reproduce in JavaScript/Python project which created from func cli.

**Comment by EricJizbaMSFT** [comment]
Huh this might be a bug on the func cli. Unlike other languages, for C# we get the version from the .csproj file. There's a property like this:
```
<AzureFunctionsVersion>v2</AzureFunctionsVersion>
```

I'm not sure why that's v2 - need to follow up

**Comment by EricJizbaMSFT** [comment]
Looks like they already fixed this, but it hasn't been released yet: https://github.com/Azure/azure-functions-core-tools/pull/1728 Putting this in tracking to verify once they release.

**Comment by v-ruizh** [comment]
This issue does not reproduce on Azure Function extension [20200203.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14327&view=artifacts&type=publishedArtifacts), close it.
