### ISSUE TITLE
Unable to create Function App

### ISSUE THREAD

**Issue by kylesaffy** [microsoft/vscode-azurefunctions#1818]
When trying to create an Azure Function App I am getting an error. The template deployment 'Microsoft.Web-FunctionApp-Portal-xxx' is not valid according to the validation procedure. No further details are given and back tracking to try and find the root cause of the issue is not giving any additional insights. Below is a screenshot of the error
![image](https://user-images.githubusercontent.com/5206534/72730869-0c446500-3b9b-11ea-9839-cf8d94a27269.png)

**Comment by EricJizbaMSFT** [comment]
@kylesaffy it looks like that screenshot is for the Azure Portal - this repo is for the Azure Functions extension in VS Code. Also did you click the option that says "See inner errors for details"? If that doesn't work, I would recommend using the "Help" question mark button in the portal.

Of course, you're welcome to try creating a function app from VS Code :)
