### ISSUE TITLE
Creating a new function UX when name not unique

### ISSUE THREAD

**Issue by carlowahlstedt** [Microsoft/vscode-azurefunctions#183]
When creating a new function, it prompts for a "globally unique name". However, if you quickly type one in that is not unique and then hit enter the box disappears. I had to go back through it slowly to realize that it's validating in the box in realtime and enter dismisses the box.

My suggestion would be to not allow enter to dismiss the box, only escape. This would allow the user to better see the validation. Additionally, it could be beneficial to log to the output window that the name found wasn't unique.

**Comment by EricJizbaMSFT** [comment]
VS Code made some improvements recently around input boxes. Tested on insiders and enter will _not_ dismiss the box if it's still validating. Closing as fixed.
