### ISSUE TITLE
Creating a function creates Application Insights resource (and gets stuck there)

### ISSUE THREAD

**Issue by arjun27** [microsoft/vscode-azurefunctions#1830]
I created a new function with this VS Code, and was surprised to see that a new Application Insights resource is being created. It also seems to be stuck on that step. Is there a way to disable this? I don't think I need this resource.

**Comment by arjun27** [comment]
My second attempt at this went through, but I'm now left with a resource group and storage account that I can't use. Resource creation operations should be atomic.

**Comment by EricJizbaMSFT** [comment]
If you want more fine-tuned control, I would suggest trying the "Advanced" option when creating a function app. It gives you many more options, including skipping the App Insights resource completely.

If you can get us consistent repro steps for getting stuck at the App Insights step we can investigate that. In addition, if you have suggestions for the behavior we can look into - are you saying we should delete the resource group and storage account if something fails?

**Comment by arjun27** [comment]
Thanks, Eric! Ah, I didn't realize the differences between the advanced vs base option. I don't think I will be able to get consistent repro steps for the issue, sorry.

Yes, imo, the 2/4 resources that were created should be reversed, since the operation of creating of function has failed.

**Comment by EricJizbaMSFT** [comment]
> Yes, imo, the 2/4 resources that were created should be reversed, since the operation of creating of function has failed.

We discussed this and it's somewhat of a complicated/risky issue. We allow users to select existing or new resources throughout the wizard and it would be very bad if we deleted something that shouldn't be deleted. For now we say it's not worth the work
