### ISSUE TITLE
Not able to use the core tools

### ISSUE THREAD

**Issue by pelletierjf** [microsoft/vscode-azurefunctions#1833]
Repro steps:

1. Make a new function in Visual Studio Code
2. Run in debug mode

You can also reproduce the error just by asking "func --version" in the terminal.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "host start" failed with exit code "1".

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:83493extension.bundle.js:353:83493
l.fire extensionHostProcess.js:46:893
v.$onDidEndTaskProcess extensionHostProcess.js:730:664
```

</details>

**Comment by EricJizbaMSFT** [comment]
@pelletierjf can you copy the logs from the "func host start" task? Also make sure you have the .NET Core Sdk installed. https://dotnet.microsoft.com/download/dotnet-core
