### ISSUE TITLE
Can't see templates when I try to create a new project

### ISSUE THREAD

**Issue by JanIHC** [microsoft/vscode-azurefunctions#1834]
Can't see templates when I try to create a new project. What could be the issue?

![image](https://user-images.githubusercontent.com/60238444/73020541-b4ec1080-3e8a-11ea-891a-754c30d890b4.png)

Azure Functions 0.20.1

VSCode Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by EricJizbaMSFT** [comment]
@JanIHC what language did you select? Do you have the func cli installed? If so - what version?

**Comment by JanIHC** [comment]
This morning the extension was showing that I need to "Reload" after that I tried it again and suddenly the templates where showing up:

![image](https://user-images.githubusercontent.com/60238444/73141088-faa41580-40e4-11ea-9280-1881832fac39.png)

I selected C# as language
