### ISSUE TITLE
Encountered an error (InternalServerError) from host runtime.

### ISSUE THREAD

**Issue by piyushkacha7** [microsoft/vscode-azurefunctions#1838]
Syncing triggers...

Repro steps:
when I deploy Azure Function App, after deployment every time I got the error message "Encountered an error (InternalServerError) from host runtime."
Logs:-
Deployment successful.
Syncing triggers...
.....................
Syncing triggers (Attempt 6/6)...
Error: Encountered an error (InternalServerError) from host runtime.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>

```
extension.bundle.js:218:2800648extension.bundle.js:218:2800648
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635041
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.EventEmitter.emit domain.js:471:20
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
$.EventEmitter.emit domain.js:471:20
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@piyushkacha7 does this repro consistently? Please add repro steps, including type of project and how you created the function app

**Comment by piyushkacha7** [comment]
Yes, that repro used consistently. The below image specify repro steps. 
![image (2)](https://user-images.githubusercontent.com/47378765/73842917-92230a00-4843-11ea-9562-872abd06989a.png) 
The project is created from the Azure portal.

**Comment by EricJizbaMSFT** [comment]
Unfortunately `InternalServerError` is a pretty generic error coming from Azure and here on VS Code it's hard to tell what the root issue is. You can try getting support from the Azure team directly: https://github.com/Azure/Azure-Functions#questions--help

Otherwise I'll need much more detailed steps here so that I can try to repro

**Comment by piyushkacha7** [comment]
Nevermind, my azure function app deployed successfully just gives `InternalServerError`, I don't have a more detailed step.
Thank you for support.
