### ISSUE TITLE
Create new Project (C# version ~1) fails on existing project

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurefunctions#184]
1.  Click on 'Create new Project'
2. Choose the directory
3. Choose C# and version ~1 when prompted.

I see this error : 
![functionsc 1](https://user-images.githubusercontent.com/30420973/35416794-5ef97314-01df-11e8-903e-122779a2e83e.PNG)

Text: 
___start___
Downloading dotnet templates for Azure Functions...
Installing "microsoft.azurefunctions.projecttemplates.1.0.3.10152"
Installing "azure.functions.templates.1.0.3.10152"
Finished installing Azure Functions templates.
Creating this template will make changes to existing files:
  Overwrite   .gitignore
  Overwrite   host.json
  Overwrite   local.settings.json

Rerun the command and pass --force to accept and create.
Error: Command "dotnet new,azureFunctionsProjectTemplates" failed with exit code "2147500036".
___end___

**Comment by EricJizbaMSFT** [comment]
The error is pretty clear in the logs. You tried to create a new project in a folder that already had a project. However, we could automatically check this case and ask the user if they want to overwrite those files
