### ISSUE TITLE
Can we have an option to turn off the "Are you sure you want to deploy..." dialog?

### ISSUE THREAD

**Issue by x509cert** [microsoft/vscode-azurefunctions#1842]
This is the dialog I mean after I select the Subscription and Function app...

[Window Title]
Visual Studio Code

[Content]
Are you sure you want to deploy to "hopemh"? This will overwrite any previous deployment and cannot be undone.

[Deploy] [Cancel]

**Comment by EricJizbaMSFT** [comment]
@x509cert I added a setting `azureFunctions.showDeployConfirmation` to turn this off. Will be included in the next release

**Comment by EricJizbaMSFT** [comment]
@x509cert FYI this just shipped. Update to version 0.21.0 if you want to use it
