### ISSUE TITLE
Failed to upload because SCM_RUN_FROM_PACKAGE is not provided or misconfigured by function app setting.

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoft/vscode-azurefunctions#1843]
publishing using VS Code runs into above mentioned problem:
14.36.38 CreateAzureResGroup: Creating zip package...
14.41.34 CreateAzureResGroup: Starting deployment...
14.46.33 CreateAzureResGroup: Fetching changes.
14.46.33 CreateAzureResGroup: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/20caf6e2-dd8e-4238-9032-0854c40d460e.zip (1566.61 MB) to /tmp/zipdeploy/extracted
14.46.40 CreateAzureResGroup: Waiting for long running command to finish...
14.47.40 CreateAzureResGroup: Waiting for long running command to finish...
14.48.41 CreateAzureResGroup: Waiting for long running command to finish...
14.49.02 CreateAzureResGroup: Updating submodules.
14.49.02 CreateAzureResGroup: Preparing deployment for commit id 'a4aa251f82'.
14.49.02 CreateAzureResGroup: Repository path is /tmp/zipdeploy/extracted
14.49.03 CreateAzureResGroup: Running oryx build...
14.49.03 CreateAzureResGroup: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.6 -p packagedir=.python_packages/lib/python3.6/site-packages
14.49.04 CreateAzureResGroup: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
14.49.04 CreateAzureResGroup: You can report issues at https://github.com/Microsoft/Oryx/issues
14.49.04 CreateAzureResGroup: Oryx Version      : 0.2.20191018.1, Commit: b56054ad55c50d02d333db35752b7f0aee706ad5, ReleaseTagName: 20191018.1
14.49.04 CreateAzureResGroup: Build Operation ID: |uDNAaEBRXEA=.1a42d604_
14.49.04 CreateAzureResGroup: Repository Commit : a4aa251f826544bf90cae35ad5a5b04a
14.49.04 CreateAzureResGroup: Warning: An outdated version of python was detected (3.6.9). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx
14.49.04 CreateAzureResGroup: Source directory     : /tmp/zipdeploy/extracted
14.49.04 CreateAzureResGroup: Destination directory: /home/site/wwwroot
14.49.04 CreateAzureResGroup: Python Version: /opt/python/3.6.9/bin/python3
14.49.04 CreateAzureResGroup: Running pip install...
14.49.16 CreateAzureResGroup: Running post deployment command(s)...
14.49.16 CreateAzureResGroup: Triggering recycle (preview mode disabled).
14.49.16 CreateAzureResGroup: Writing the artifacts to a squashfs file
14.49.16 CreateAzureResGroup: Parallel mksquashfs: Using 1 processor
14.49.16 CreateAzureResGroup: Creating 4.0 filesystem on /home/site/deployments/functionappartifact.squashfs, block size 131072.
14.49.37 CreateAzureResGroup: [/                                                           ]   200/30887   0%
14.49.41 CreateAzureResGroup: [======\                                                     ]  3600/30887  11%
14.49.48 CreateAzureResGroup: Waiting for long running command to finish...
14.50.04 CreateAzureResGroup: [=======|                                                    ]  3700/30887  11%
14.50.26 CreateAzureResGroup: [==========/                                                 ]  5500/30887  17%
14.50.36 CreateAzureResGroup: [=============|                                              ]  7000/30887  22%
14.50.50 CreateAzureResGroup: Waiting for long running command to finish...
14.50.59 CreateAzureResGroup: [================|                                           ]  8500/30887  27%
14.51.33 CreateAzureResGroup: [====================\                                       ] 10500/30887  33%
14.51.50 CreateAzureResGroup: [===========================\                                ] 14400/30887  46%
14.51.57 CreateAzureResGroup: Waiting for long running command to finish...
14.52.07 CreateAzureResGroup: [===============================/                            ] 16300/30887  52%
14.52.37 CreateAzureResGroup: [=================================/                          ] 17600/30887  56%
14.52.41 CreateAzureResGroup: [======================================|                     ] 20100/30887  65%
14.52.58 CreateAzureResGroup: Waiting for long running command to finish...
14.53.40 CreateAzureResGroup: [=======================================\                    ] 20500/30887  66%
14.53.59 CreateAzureResGroup: Waiting for long running command to finish...
14.54.01 CreateAzureResGroup: [=================================================/          ] 25700/30887  83%
14.54.12 CreateAzureResGroup: [===================================================\        ] 27100/30887  87%
14.54.41 CreateAzureResGroup: [======================================================\     ] 28600/30887  92%
14.54.41 CreateAzureResGroup: [===========================================================\] 30887/30887 100%
14.54.41 CreateAzureResGroup: Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
14.54.41 CreateAzureResGroup: 	compressed data, compressed metadata, compressed fragments, compressed xattrs
14.54.41 CreateAzureResGroup: 	duplicates are removed
14.54.41 CreateAzureResGroup: Filesystem size 1084885.43 Kbytes (1059.46 Mbytes)
14.54.41 CreateAzureResGroup: 	39.19% of uncompressed filesystem size (2768297.63 Kbytes)
14.54.41 CreateAzureResGroup: Inode table size 185170 bytes (180.83 Kbytes)
14.54.41 CreateAzureResGroup: 	32.13% of uncompressed inode table size (576314 bytes)
14.54.41 CreateAzureResGroup: Directory table size 174070 bytes (169.99 Kbytes)
14.54.41 CreateAzureResGroup: 	28.69% of uncompressed directory table size (606791 bytes)
14.54.41 CreateAzureResGroup: Number of duplicate files found 8402
14.54.41 CreateAzureResGroup: Number of inodes 15431
14.54.41 CreateAzureResGroup: Number of files 12872
14.54.41 CreateAzureResGroup: Number of fragments 403
14.54.41 CreateAzureResGroup: Number of symbolic links  0
14.54.41 CreateAzureResGroup: Number of device nodes 0
14.54.41 CreateAzureResGroup: Number of fifo nodes 0
14.54.41 CreateAzureResGroup: Number of socket nodes 0
14.54.41 CreateAzureResGroup: Number of directories 2559
14.54.41 CreateAzureResGroup: Number of ids (unique uids + gids) 1
14.54.41 CreateAzureResGroup: Number of uids 1
14.54.41 CreateAzureResGroup: 	root (0)
14.54.41 CreateAzureResGroup: Number of gids 1
14.54.41 CreateAzureResGroup: 	root (0)
14.54.41 CreateAzureResGroup: Uploading built content /home/site/deployments/functionappartifact.squashfs -> 
14.54.41 CreateAzureResGroup: Failed to upload because SCM_RUN_FROM_PACKAGE is not provided or misconfigured by function app setting.
14.54.53 CreateAzureResGroup: Syncing triggers...
14.55.01 CreateAzureResGroup: Syncing triggers (Attempt 2/6)...
14.55.12 CreateAzureResGroup: Syncing triggers (Attempt 3/6)...
14.55.32 CreateAzureResGroup: Syncing triggers (Attempt 4/6)...
14.56.13 CreateAzureResGroup: Syncing triggers (Attempt 5/6)...
14.57.34 CreateAzureResGroup: Syncing triggers (Attempt 6/6)...
14.57.35: Error: Encountered an error (InternalServerError) from host runtime.

**Comment by EsaHeikkiPoutanen** [comment]
I don't have any SCM_RUN_FROM_PACKAGE in function app settings nor Application settings in my python function in azure. should I have one ?

**Comment by EsaHeikkiPoutanen** [comment]
tweaked one setting, tried again,, did the publishing procedure (judging by the outpu) twice, bots tries ending:
10.16.44 CreateAzureResGroup: Syncing triggers (Attempt 6/6)...
10.16.46: Error: Encountered an error (InternalServerError) from host runtime.

**Comment by EsaHeikkiPoutanen** [comment]
and this from my CLI publish attempt from yesterday:
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = '13fb9156-ff40-4d9a-961a-43879a8fb294'.

**Comment by EsaHeikkiPoutanen** [comment]
tällä kertaa VS Code publish pysähty tähän: 2.19.34: Error: connect EACCES 52.178.92.96:443

**Comment by EricJizbaMSFT** [comment]
@EsaHeikkiPoutanen how did you create you function app in azure? And how did you create your local project? Could you copy your local `.vscode/settings.json` at the root of your repo here?

**Comment by EsaHeikkiPoutanen** [comment]
well, to start from the beginning....I had been writing and successfully publishing c# Azure functions aplenty using Visual Studio 2019...then management ordered me to start writing them in Python...so I wrote my first ever Python program there (VS2019) installing all the 'bells and wistles' for Python development, got it working...how to turn it to azure function,, couldn't figure out how....so, after some google searching installed VS Code and all the 'bells and wistles' for Python development and Azure extensions too. Created my first ever Python Azure Function there, saved it to where my Azure functions are (mostly c# and now 1 Python), got it working nicely locally in VS Code so started  to deploy it to Function App in Azure, first tried to deploy it to the same resource group where my c# functions are...soon found out that to be a no-no...so created (or actually our Azure manager did) a brand new linux resource group and storage and stuff for my Python function, deployed there, got some errors, went to Azure, to the resource group, function is there, up n' running, go in to look, NO CODE AT ALL (how can it be running when there's no code?), so deleted it and turned to CLI deployment (having installed Azure CLI) using az commands in Power shell, az functionapp create...-> func azure functionapp publish..., judging by the log, did hell of a lot work, in the end syncing triggers...the above mentioned error (now function in Azure has code int it, but is still not quite right,, there's some error there), went back to VS Code, tried deployment from there, ended up having the same problem as with CLI... sorry about the long story...

**Comment by EsaHeikkiPoutanen** [comment]
Here's the .vscode/settings.json:
{
  "azureFunctions.deploySubpath": ".",
  "azureFunctions.scmDoBuildDuringDeployment": true,
  "azureFunctions.pythonVenv": ".venv",
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~2",
  "debug.internalConsoleOptions": "neverOpen",
  "python.pythonPath": ".venv\\Scripts\\python.exe"
}
nothing is in Git as of yet..

**Comment by EsaHeikkiPoutanen** [comment]
now I got this deployed succesfully, and tested too, works, not quite sure what did the trick....

**Comment by EricJizbaMSFT** [comment]
Hmm yeah your settings look like what I would expect. I'll close this for now since you said you got it working. Let us know if you run into issues again
