### ISSUE TITLE
Azure Functions failed to import modules

### ISSUE THREAD

**Issue by anthonyteal** [microsoft/vscode-azurefunctions#1845]
Issue Type: <b>Bug</b>

I went though the process of creating the 'hello <name>' demo for Azure functions through VSCode.  I tested the function through the debugger, and everything worked fine.  When I deployed to the cloud, then the code failed to import pandas or numpy.  I used the upload functionality in the Azure sidebar.  I am also using a module called Pulp, and that imported fine.  It is running from a .zip file in blob storage.

Extension version: 0.20.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EricJizbaMSFT** [comment]
@anthonyteal can you copy the deploy logs here? Also do you have `azureFunctions.scmDoBuildDuringDeployment` set in `.vscode/settings.json` at the root of your repo?
