### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by kulkarnisonia16** [microsoft/vscode-azurefunctions#1854]
Enable all scenarios for Python 3.8 similar to 3.7

**Comment by EricJizbaMSFT** [comment]
@kulkarnisonia16 can you give us a timeline for this?

**Comment by EricJizbaMSFT** [comment]
Aka when will this be available in the platform - and will it be v3-only or also v2?

**Comment by kulkarnisonia16** [comment]
V3 only, Az cli/core-tools/Portal should all be able to light this by early March.

**Comment by fiveisprime** [comment]
This should be landing in the core tools and platform on the 18th for us to test.
