### ISSUE TITLE
Durable Functions quickstart demo fails with "Cannot find module 'durable-functions'" once deployed to Azure

### ISSUE THREAD

**Issue by GuSuku** [microsoft/vscode-azurefunctions#1857]
I am following through MS quick start instructions here for Durable Functions in JS: https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode

It works fine when I tested it locally. But when I deploy it to Azure and open the function url, I get the following:
```2020-02-02T14:22:30.452 [Information] Executing 'Functions.HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=***-07b698515b50)
2020-02-02T14:22:30.562 [Error] Executed 'Functions.HttpStart' (Failed, Id=***-07b698515b50)
Result: Failure
Exception: Worker was unable to load function HttpStart: 'Error: Cannot find module 'durable-functions''
Stack: Error: Cannot find module 'durable-functions'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\HttpStart\index.js:1:74)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

This is the Host Status from log stream:

```
2020-02-02T14:19:57.341 [Information] Host Status: {
  "id": "testdurablejs***0818",
  "state": "Running",
  "version": "2.0.12961.0",
  "versionDetails": "2.0.12961.0 Commit hash: 2990a47e373bb2c15efd685d06e06a33b048e702",
  "processUptime": 3625618,
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "1.1.1"
  }
}
```

Project's `.vscode/settings.json`
```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.projectLanguage": "JavaScript",
    "azureFunctions.projectRuntime": "~2",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.preDeployTask": "npm prune"
}
```

My VS Code build:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic
```

**Comment by EricJizbaMSFT** [comment]
@GuSuku is `durable-functions` listed in your package.json? As a dependency and not a dev dependency?

**Comment by GuSuku** [comment]
Thats it! I had it under `devDependencies` but moving it to `dependencies` fixed it. Thanks.

From Azure Functions output in VS Code, I am seeing:
```
7:15:13 AM  testdurablejs: Creating zip package...
7:15:14 AM  testdurablejs: Starting deployment...
7:15:18 AM  testdurablejs: Updating submodules.
7:15:18 AM  testdurablejs: Preparing deployment for commit id 'ca0703048c'.
7:15:18 AM  testdurablejs: Skipping build. Project type: Run-From-Zip
7:15:18 AM  testdurablejs: Skipping post build. Project type: Run-From-Zip
7:15:19 AM  testdurablejs: Triggering recycle (preview mode disabled).
7:15:22 AM  testdurablejs: Syncing 5 function triggers with payload size 533 bytes successful.
7:15:22 AM  testdurablejs: Deployment successful.
```

I had read this before: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#dependency-management

Above deployment logs suggested like they zip all dependencies and not re-trigger a npm install. But the `commit id` also suggests it is a "deploy from source control" process (see above link). Can you point me to relevant documentation on how the extension deploys node functions, behind the scenes? Thanks.

**Comment by EricJizbaMSFT** [comment]
I don't know if I have a doc on that. It's all controlled by the files in the `.vscode` folder. Specifically, in `settings.json` it has `azureFunctions.preDeployTask` set to `npm prune`, which is a task configured in `tasks.json`. Here's the npm docs for that command: https://docs.npmjs.com/cli-commands/prune.html It removes all dev dependencies (to keep production deploys smaller and faster), which is why you hit that problem.

You're welcome to change your config if you want. For example, if you:
1. Remove `azureFunctions.preDeployTask`, it will deploy your workspace as-is without trying to install any dependencies
1. Change `azureFunctions.preDeployTask` to `npm install`, it will install production _and_ dev dependencies before deploying

**Comment by GuSuku** [comment]
Thanks, that was helpful!
