### ISSUE TITLE
A warning dialog pops up when debugging an outside C# project 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1864]
OS: Windows
Build Version: [20200203.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14327&view=artifacts&type=publishedArtifacts)
Function Core tools: 3.0.2009
.NET Core: 3.0.2106

Repro Steps:
1. Create a C# project with func cli using the following command:
   func init --worker-runtime dotnet
   func new --template HttpTrigger --name HttpTrigger1
2. Open this C# project in VS Code.
3. Select "Yes" to initial this project.
4. Debug this project.

Expect:
Debug this project successfully without any warning.

Actual:
A warning dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/73731175-fc1fae80-4772-11ea-9c44-202cba9205f1.png)

More Info:
1. This issue does not reproduce in JavaScript/Python project which created from func cli.
2. This issue does not reproduce in C# project which created from VS Code.
3. Debug this C# project successfully after clicking "Debug anyway" in this warning dialog.

**Comment by EricJizbaMSFT** [comment]
This is due to a behavior difference between VS Code and the func cli. At the end of the day, the user can just "Debug Anyway" in this situation so we'll close as wont-fix
