### ISSUE TITLE
Deploy to Azure failed with code 401

### ISSUE THREAD

**Issue by siwon** [microsoft/vscode-azurefunctions#1868]
Hi, 

When I tried to deploy on azure, I get a 401 error.
![image](https://user-images.githubusercontent.com/1249874/73843492-0b5c3600-481f-11ea-8b01-dbe524ef1dcc.png)

Repro steps:

1. I simply followed this tutorial and when I try to push the application to Azure, 
https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-01

Action: azureFunctions.deploy
Error type: 401
Error Message: Failed with code "401".

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:393387extension.bundle.js:323:393387
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635006
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

Did I miss something ?

Thanks for your help.

**Comment by EricJizbaMSFT** [comment]
@siwon your subscription might not have permissions for something. You can try the "Advanced" option which should give you more control when creating the function app in Azure

**Comment by siwon** [comment]
After a new try, it works. Thanks and sorry :)
