### ISSUE TITLE
Logging does not appear to work for Linux Functions in VSC

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azurefunctions#1873]
Expanding the logging folder returns an error that the plan does not support viewing files for Linux functions.

![image](https://user-images.githubusercontent.com/37638436/73867921-6466a280-47fc-11ea-8a26-6cf2061b396a.png)

In the interim, can we update the messaging to reflect the limitation or share a clickable element to view the live streaming logs instead?

**Comment by EricJizbaMSFT** [comment]
Can you suggest a better message? It seems pretty clear to me

**Comment by EricJizbaMSFT** [comment]
We can add a stream logs button. It'll have to take them to app insights in the portal as that's currently the only way to stream logs on Linux
