### ISSUE TITLE
Cannot update or download azure

### ISSUE THREAD

**Issue by mdbecerra** [microsoft/vscode-azurefunctions#1878]
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135821
o extension.bundle.js:1:134852
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting, @mdbecerra  

Please provide repro steps.  And the output from the output channel would be helpful as well.
