### ISSUE TITLE
Unable to create Azure Function

### ISSUE THREAD

**Issue by krishnaastica** [microsoft/vscode-azurefunctions#1879]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3.6" command. Check output window for more details.

Version: 0.20.2
OS: linux
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:106670
o extension.bundle.js:1:105708
```

</details>

**Comment by krishnaastica** [comment]
python3-env is already installed but still Project creation fails

**Comment by EricJizbaMSFT** [comment]
@krishnaastica please add repro steps and copy the output here
