### ISSUE TITLE
Not sure about this issue is about

### ISSUE THREAD

**Issue by annguyen281** [microsoft/vscode-azurefunctions#1880]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:87318extension.bundle.js:353:87318
o extension.bundle.js:353:84930
```

</details>

**Comment by EricJizbaMSFT** [comment]
@annguyen281 please add detailed repro steps
