### ISSUE TITLE
Failed to get latest templates

### ISSUE THREAD

**Issue by flira85** [microsoft/vscode-azurefunctions#1882]
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to get latest templates: Failed to detect Azure Functions maven plugin version.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:388174
o extension.bundle.js:164:385154
o extension.bundle.js:1:255993
extension.bundle.js:1:256490extension.bundle.js:1:256490
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please check your pom.xml and make sure it doesn't have any errors. Also check for the property `azure.functions.maven.plugin.version` to make sure it exists. If you're still having problems, add more detailed repro steps
