### ISSUE TITLE
How can a c# function open in Visual Studio 2019 prevent deploying a python function in VS Code ?

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoft/vscode-azurefunctions#1885]
I'm getting this error message:

EBUSY: resource busy or locked, scandir
'c\source\repos\AzureFunctions2\CreateResGroup\.vs\CreateResGroupv16\Server\sqlite3\db.lock'

Source: Azure Functions (Extension)

the python function is under the same directory (c\source\repos\AzureFunctions2) in it's own directory, surely this can't be the problem. CAN IT ?

**Comment by EricJizbaMSFT** [comment]
Can you show me a screenshot of your workspace so that I can get an idea of the file structure? In your python project, you should have a `.funcignore` file which controls the files we deploy. Anything listed there will be ignored - you could add the `CreateResGroup.vs` folder (or whatever folder is causing problems) to make sure it's ignored

**Comment by EsaHeikkiPoutanen** [comment]
My structure is like this:

under ....AzureFunctions2 directory are number of c# functions and this one python function all in their own directories.

CreateResGroup is in c#(VS 2019), the one I was trying to deploy (CreateAzureResGroup) in Python (VS Code)

and yes I do have .funcignore  (and requirements and local_settings and..) in AzureFunctions2 directory. WHY ? why are they not in CreateAzureResGroup directory ?

and why is Deployment trying to deploy anything other than I have asked it to deploy ?

I've been working as a software developer for over 30 years with over 10 different programming languages...and this baffles me...

**Comment by EricJizbaMSFT** [comment]
So does your file structure look like this?
![Screen Shot 2020-02-12 at 11 20 53 AM](https://user-images.githubusercontent.com/11282622/74369179-c9387480-4d89-11ea-8e86-6762be7a689b.png)

And do you have `AzureFunctions2` or `CreateAzureResGroup` open as the workspace? I would recommend opening just the Python project by itself as a workspace in VS Code.
