### ISSUE TITLE
Hi @SatishPaiB

### ISSUE THREAD

**Issue by suryapratap** [microsoft/vscode-azurefunctions#1887]
Hi @SatishPaiB

Thanks for reporting.  Please provide repro steps.

_Originally posted by @nturinski in https://github.com/microsoft/vscode-azurefunctions/issues/1718#issuecomment-558746523_

Can you provide a way to set the timeout mentioned, it is not evident from the message where this property needs to be set

**Comment by EricJizbaMSFT** [comment]
It should be done in your VS Code settings: https://code.visualstudio.com/docs/getstarted/settings

If you give us more detailed repro steps we might be able to be more helpful. It's possible the setting mentioned in the error message won't help
