### ISSUE TITLE
func.ps1 is not digitally signed. You cannot run this script on the current system.

### ISSUE THREAD

**Issue by hdd42** [microsoft/vscode-azurefunctions#1888]
Hi, I'm trying to run/test my function locally through vs code. I've installed azure function core tools@3 via npm the function I'm trying to test is a timer function. 

Both hitting F5 to start debug mode or func host start from terminal failing and getting this error : 

```
func.ps1 cannot be loaded. The file C:\Program Files\nodejs\func.ps1 is not
digitally signed. You cannot run this script on the current system.
```

looks like it  complains about PowerShells Execution_Policies . I've removed azure function core tools and re-install it via choco install azure-functions-core-tools and host is starting without any problems. (since choco is modifying PowerShells Execution_Policies that works. )

I was wondering is there any way to fix this issue without choco (or not modifying PowerShells Execution_Policies) because per company policy I'm not allow to change PowerShells Execution_Policies

Windows 10,
VS Code 
1.42.0 ,
 Node 12.4

Thanks.

**Comment by EricJizbaMSFT** [comment]
Moved to https://github.com/Azure/azure-functions-core-tools/issues/1821

Also related to https://github.com/microsoft/vscode-azurefunctions/issues/1678
