### ISSUE TITLE
Cannot deploy powershell based code to function app

### ISSUE THREAD

**Issue by hoswell-OW** [microsoft/vscode-azurefunctions#1895]
Repro steps:

1. deploy powershell function to azure function apps
2. ? get error?

Action: azureFunctions.executeFunction
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:218:1077293
$.callback extension.bundle.js:218:1076136
$.e.callback.t.callback [as _callback] extension.bundle.js:218:1075184
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:200:13
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hoswell-OW we will need more detailed repro steps to investigate this. Unfortunately `InternalServerError` is coming from Azure and can happen for a variety of reasons. In addition, your title says "deploy", but the action listed is "executeFunction" - please clarify
