### ISSUE TITLE
error deploying function in existing functionapp

### ISSUE THREAD

**Issue by dmelgarejoPDESGO** [microsoft/vscode-azurefunctions#1896]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\dimel\Source\Repos\bin\Release\netcoreapp2.1\publish

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:13566
o extension.bundle.js:288:13148
```

</details>

**Comment by EricJizbaMSFT** [comment]
@dmelgarejoPDESGO did the `dotnet publish` task succeed? If not, that's likely your problem. Check the task output when you deploy for errors
