### ISSUE TITLE
Unable to create new project using Azure function extension

### ISSUE THREAD

**Issue by Hari-c4** [microsoft/vscode-azurefunctions#1897]
Repro steps:

1. Click create new project in Azure function extension
2. Select language as python 
3. Select any trigger and press Enter

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "C:\Users\Harikishore.KA\AppData\Local\Programs\Python\Python37\python.exe" command. Check output window for more details.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:106670
o extension.bundle.js:1:105708
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Hari-c4 please take a look at the output window for any errors - if you're still having issues, add repro steps here and copy the output logs

**Comment by Hari-c4** [comment]
@EricJizbaMSFT  I've added the repro steps above. This issue is only while creating Local projects for python language. Here is the output log that I'm getting

![az-Proj](https://user-images.githubusercontent.com/56388643/74819530-8ac12d80-5326-11ea-9a84-b2685b068d3c.JPG)

**Comment by EricJizbaMSFT** [comment]
Can you try running that command in the terminal outside of VS Code? I'm guessing it'll fail with the same error - in which case it might be an issue with python setup on your machine. I would try googling that error

As a workaround, you could also try skipping create of a virtual environment
