### ISSUE TITLE
UAE Central is not avaliable

### ISSUE THREAD

**Issue by Bougyz** [microsoft/vscode-azurefunctions#1898]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: LocationNotAvailableForResourceGroup
Error Message: The provided location 'uaecentral' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast,eastus2euap,centraluseuap'.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:505608extension.bundle.js:218:505608
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635041
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.EventEmitter.emit domain.js:471:20
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
$.EventEmitter.emit domain.js:471:20
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Bougyz is `uaecentral` if you try to create a function app in the portal? Also, please add repro steps including what options you selected when you created the resource
