### ISSUE TITLE
Python azure function running in linux VM getting FORBIDDEN error when trying to read a keyvault secret

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoft/vscode-azurefunctions#1899]
I have a azure function written in Python (using VS Code) running on a linux VM,
[CreateAzureResGroup_permissions.docx](https://github.com/microsoft/vscode-azurefunctions/files/4218695/CreateAzureResGroup_permissions.docx)

this document shows the permissions I have for the function, to me everything looks to be all right,
but I still get FORBIDDEN error when trying to read a secret from keyvault.

Keyvault i'm using is in windows VM

here's the code:
[__init__.txt](https://github.com/microsoft/vscode-azurefunctions/files/4218740/__init__.txt)

I can't figure out what the problem is, please help.

**Comment by EricJizbaMSFT** [comment]
@EsaHeikkiPoutanen this seems like a coding question, not an issue with the VS Code extension. Unfortunately, I don't think I'll be very much help with that. I would recommend following up directly with the functions team using one of the channels described here: https://github.com/Azure/Azure-Functions#questions--help
