### ISSUE TITLE
Deploying Azure Function

### ISSUE THREAD

**Issue by mahendra48** [microsoft/vscode-azurefunctions#1900]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\mahen\Desktop\Mahendra\Text Translater\Multilingual-QnAMaker-master\DotNet\bin\Release\netcoreapp2.1\publish

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:13566
o extension.bundle.js:288:13148
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mahendra48 did the `dotnet publish` task succeed? If not, that's likely your problem. Check the task output when you deploy for errors
