### ISSUE TITLE
VS Code - Azure functions

### ISSUE THREAD

**Issue by Naresh-Les** [microsoft/vscode-azurefunctions#1908]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:86654extension.bundle.js:353:86654
l.fire extensionHostProcess.js:48:541
y.$onDidEndTaskProcess extensionHostProcess.js:746:693
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Naresh-Les please check the output of the clean task. If that doesn't help, copy the output here and add detailed repro steps
