### ISSUE TITLE
failed to deploy C# function to Azure /bin/Release/netcoreapp3.0/publish does not exist

### ISSUE THREAD

**Issue by Xa4vier** [microsoft/vscode-azurefunctions#1914]
Repro steps:

1. I Created a C# function in Visual Studio Code
2. I changed nothing
3. I published the code to Azure just like i Publisch my Python function

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/<username>/Documents/repos/Azure functions Applications /<projectname>/bin/Release/netcoreapp3.0/publish

Version: 0.20.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:13566
o extension.bundle.js:288:13148
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Xa4vier did the `dotnet publish` task succeed? If not, that's likely your problem. Check the task output when you deploy for errors
