### ISSUE TITLE
401 error while updating cloud function

### ISSUE THREAD

**Issue by Hongrun** [microsoft/vscode-azurefunctions#1916]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 401
Error Message: Failed with code "401".

Version: 0.20.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:393387
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635006
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @Hongrun

Thanks for reporting.  Your subscription might not have permissions for something. You can try the "Advanced" option which should give you more control when creating the function app in Azure
