### ISSUE TITLE
Remove references to .NET from Install Functions Core Tools command 

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#1918]
Currently, when installing Core Tools with the extension, the prompt displays .NET versions. This is confusing to folks who want to write Functions in other languages.

![image](https://user-images.githubusercontent.com/3982077/75184962-1f96a300-56fa-11ea-966c-c6faebc6fc3a.png)

Selecting "Learn more..." already opens a page with language version information. Suggest removing the .NET versions from the above prompt. (And perhaps changing the v3 one to `Azure Functions v3 (Recommended)`)

**Comment by EricJizbaMSFT** [comment]
I'm fine with that - although I did it that way because of `displayVersion` in https://functionscdn.azureedge.net/public/cli-feed-v3.json

I assume @soninaren did that - any thoughts?

**Comment by soninaren** [comment]
I agree, we should remove `(.Net Core)` and `(.NET Framework)` from the prompt. `cli-feed-v3.json` was originally designed to be consumed by Visual Studio only. Since it only created C# projects, we added it  to the title to differentiate between v1 and v2.

**Comment by EricJizbaMSFT** [comment]
Sounds good. To be clear - we don't actually use the feed for this, I just manually copied the strings at some point. So I don't need any changes from you @soninaren
