### ISSUE TITLE
Cursor issue with blob trigger path input

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#192]
When choosing blob trigger path, the cursor will sometimes move to the end of the string. It seems to be related to when validation is run.

Repro: walk through creating a blob trigger; when entering the path, move the cursor to the beginning and delete "sample-workitems". The cursor will jump to the end of the string upon validating.

**Comment by EricJizbaMSFT** [comment]
Filed an issue on VS Code here: https://github.com/Microsoft/vscode/issues/42763

**Comment by StephenWeatherford** [comment]
Beat me to this one, too. :-( :-)

**Comment by EricJizbaMSFT** [comment]
Closing this - I verified it was fixed on the latest insiders build of VS Code.
