### ISSUE TITLE
Create New Project For Azure Functions v3

### ISSUE THREAD

**Issue by zbernhardtme** [microsoft/vscode-azurefunctions#1923]
Hi, I've been struggling with this all day.  I'm using the Azure Functions (0.20.0) extension in VS Code (1.31.1).  It will not recognize that I have the Functions runtime v3  installed (by way of the Azure Core Tools (3.0.2106))  

When I go through the `Azure Functions: Create New Project...` command I am unable to select v3.  My choices are: `Azure Functions v2 (.NET Standard)`, and `Azure Functions v1 (.NET Framework)`

If I create a Functions project from `cmd`, it creates a project with the v3 references.  Cool.  But when I open it in VS Code, VS Code shows warnings.  If I try to deploy the v3 Functions App by the little blue arrow at the top of the extension, I get a warning that I must set the remote Functions to use v2.  If I click ok, it deploys it, but the app doesn't run.

When I run `npm list -g --depth=0`, the only result is: `azure-functions-core-tools@3.0.2106`

I've read many of the existing issues here, but they all end with "it's fixed in X release".  It's not fixed for me. What should my next step be?

**Comment by EricJizbaMSFT** [comment]
The latest version of the extension is `0.20.2`. The v3 support is pretty recent, so can you try updating?

**Comment by zbernhardtme** [comment]
Thanks for that suggestion.  I looked and actually I do have `0.20.2` installed.  That's my bad.

**Comment by EricJizbaMSFT** [comment]
Can you also make sure your VS Code is up to date? Our minimum version of VS Code is `1.37.0` and sounds like you're on `1.31.1`? That might be preventing you from running our version `0.20.2` even if it's somehow installed. Unfortunately, I don't think VS Code has very good warnings/errors in this case
