### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by thirups** [microsoft/vscode-azurefunctions#1926]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:86303extension.bundle.js:353:86303
o extension.bundle.js:353:84930
```

</details>

**Comment by EricJizbaMSFT** [comment]
@thirups please add repro steps
