### ISSUE TITLE
Node version 12.16.1

### ISSUE THREAD

**Issue by rakunnath** [microsoft/vscode-azurefunctions#1933]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\Users\7000019886\Application Data'

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@rakunnath I would suggest putting your project in a different folder. You probably don't have permissions for the "Application Data" folder. If that doesn't help, please add detailed repro steps
