### ISSUE TITLE
Error type: EPIPE

### ISSUE THREAD

**Issue by warkarth** [microsoft/vscode-azurefunctions#1937]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.20.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:83:16
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @warkarth.  Please provide repro steps.
