### ISSUE TITLE
Unable to select template for a new function

### ISSUE THREAD

**Issue by ravishekharreddy** [microsoft/vscode-azurefunctions#1938]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to get latest templates: Command "dotnet "c:\Users\C37147\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.20.2\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\C37147\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\C37147\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~3.nupkg" --operation list" failed with exit code "2147516566":
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview7-27912-14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by ...

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@ravishekharreddy based on the error message it seems like you need to install a non-preview version of .NET Core 3.x

If that doesn't help, please add more detailed repro steps
