### ISSUE TITLE
C# Script problems

### ISSUE THREAD

**Issue by mshinnie** [microsoft/vscode-azurefunctions#1939]
Issue Type: <b>Bug</b>

So I made a deafult C# script azure Http function and I get many errors showing that it could not find many of the namespaces.  However when I try running it it works fine.  Also as a side note should the defualt template include a bin folder or a function.proj file, or do we just have to add these ourselves?  As a side note when I tried adding a function.proj file and tried adding a nugget package it was not able to find any proj file.  Any help is greatly appreaciated!

Extension version: 0.20.2
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.13GB free)|
|Process Argv|C:\Users\mshinnie\OneDrive - Value Partners Investments\CapIQ\CapitalIQ|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EricJizbaMSFT** [comment]
We prioritize C# class library over C# Script and I'm honestly not that familiar with C# Script. This looks like the best docs if you haven't look at them already: https://docs.microsoft.com/azure/azure-functions/functions-reference-csharp

How did you create your function? We don't support bin/function.proj by default

**Comment by mshinnie** [comment]
I set the default language to C# script in the extensions settings and created the function using the extension.  Unfortunately looking at the docs did not provide any insight to my problem.

**Comment by EricJizbaMSFT** [comment]
Sounds like you need general help authoring C# Script functions - I would advise trying one of these options: https://github.com/Azure/Azure-Functions#questions--help

The folks there will have much more knowledge on the subject
