### ISSUE TITLE
Make it obvious that the app name is the hostname

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1940]
The portal does this

![image](https://user-images.githubusercontent.com/1186948/75580325-6945fd00-5a1c-11ea-98cf-c6367a3c4c4b.png)

Which makes it obvious that the name is also the subdomain for the app. The extension could have some right justified text with "azurewebsites.net" to clarify this.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime can you tell us what you want to do in VS Code here? VS Code doesn't support the right justified text like that screenshot

We could add a watermark, but that'll go away once they start typing. Is that good enough?
