### ISSUE TITLE
Fail to uninstall azure-functions-core-tools by command "Uninstall Azure Functions Core Tools"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#1942]
**OS:** Ubuntu
**Build:** [20200228.9]( https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15481&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Install the Azure Functions Core Tools by command.
2.  Click the "Azure Functions: Uninstall Azure Functions Core Tools" from command palette.

**Expect:**
Uninstall successfully.

**Actual:**
Can't uninstall Azure Functions Core Tools.
![image](https://user-images.githubusercontent.com/57662131/75661851-0b7a1500-5ca9-11ea-98c0-7544c74e719b.png)

**More Info:**
![image](https://user-images.githubusercontent.com/57662131/75678650-104ec100-5cc9-11ea-836c-8b5d2f8b7608.png)

**Comment by EricJizbaMSFT** [comment]
Not exactly a duplicate, but this should be covered by https://github.com/microsoft/vscode-azurefunctions/issues/311. Once we add support for "install" on Linux we will also add support for "uninstall"

**Comment by v-xinda** [comment]
Got it. Thanks for your sharing.
