### ISSUE TITLE
No 'Ok' button shows when trying to select subscriptions 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurefunctions#1943]
**OS**: Windows
**Build Version**: [20200228.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15481&view=results)
**Regression:** Not a Regression
**VsCode Version**: 1.42.1

**Repro Steps:**
1. Make sure one account signed in.
2. Click the filter icon to select subscriptions.
3. Select some subscriptions then try to click 'Ok' button.

**Expect:**
There shows 'Ok' button.

**Actual:**
No 'Ok' button shows.
![image](https://user-images.githubusercontent.com/41351993/75679429-90c1f180-5cca-11ea-96f9-47cdc6de6cd8.png)

**Comment by EricJizbaMSFT** [comment]
This doesn't repro for us. Does it still happen for you?
