### ISSUE TITLE
Remove '...' for actions 'Delete Function App' and 'Deploy to Function App'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurefunctions#1945]
**OS**: Windows
**Build Version**: [20200228.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15481&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Select one function app then right click it.
2. Check the action 'Delete Function App' and 'Deploy to Function App' on conext menu.

**Expect:**
No '...' shows next to actions 'Delete Function App' and 'Deploy to Function App'.

**Actual:**
An extra '...' shows next to actions 'Delete Function App' and 'Deploy to Function App'.
![image](https://user-images.githubusercontent.com/41351993/75677586-c5cc4500-5cc6-11ea-9374-ab85bb0b5d2d.png)

**More Info:**
This issue also reproduces for one slot.
![image](https://user-images.githubusercontent.com/41351993/75678139-e517a200-5cc7-11ea-8a91-7f118c47ce01.png)

**Comment by EricJizbaMSFT** [comment]
This is by design. Per [the docs](https://docs.microsoft.com/windows/win32/uxguide/cmd-menus#using-ellipses), an ellipses should be used in these cases:
> Indicate a command that needs additional information (including a confirmation) by adding an ellipsis at the end of the label.
