### ISSUE TITLE
Why I can't deploy python function in vs code?

### ISSUE THREAD

**Issue by cmdaniel** [microsoft/vscode-azurefunctions#1949]
Repro steps:
1. I already update the azure function at VS Code
2. Just right clicked at project files root and selected the option: Deploy to Function app...

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.20.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: pt-br

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2863163
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635041
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@cmdaniel it looks like you need to select a different region when creating a Function App in Azure
