### ISSUE TITLE
Get Error Debugging in F5 start( function created from template)

### ISSUE THREAD

**Issue by daisuke19891023** [microsoft/vscode-azurefunctions#1951]
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.20.2
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.43.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:86654extension.bundle.js:353:86654
l.fire extensionHostProcess.js:48:845
y.$onDidEndTaskProcess extensionHostProcess.js:758:693
```

</details>

**Comment by EricJizbaMSFT** [comment]
@daisuke19891023 check the output of the build task for errors
