### ISSUE TITLE
remote debugging of Function apps for java

### ISSUE THREAD

**Issue by foramkumar-parekh** [microsoft/vscode-azurefunctions#1956]
Does this occur consistently? 
Repro steps:

1. Go to Azure function apps extension
2. Right-click on the function app and select Start Remote Debugging

Action: azureFunctions.startRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js Function Apps running on Linux App Service plans. Consumption plans are not supported.

Version: 0.21.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.getRemoteDebugLanguage extension.bundle.js:526:105986
extension.bundle.js:526:105633extension.bundle.js:526:105633
fulfilled extension.bundle.js:526:104861
o extension.bundle.js:1:255993
extension.bundle.js:1:256490extension.bundle.js:1:256490
processTicksAndRejections task_queues.js:89:5
```

</details>

I was able to remote debug the java function apps with the same configurations few months back. Not sure what changed. But point is how can I do it now.

**Comment by EricJizbaMSFT** [comment]
There's a separate setting for Java now. Set this to true: `azureFunctions.enableJavaRemoteDebugging`

See https://github.com/microsoft/vscode-azurefunctions/pull/1458 for more info
