### ISSUE TITLE
Azure Function Core Tool not installing on VSCode

### ISSUE THREAD

**Issue by joda10** [microsoft/vscode-azurefunctions#1957]
Does this occur consistently? 
Repro steps:

1. Open the Command Palette
2. Enter Azure Functions: Install or Update Azure Functions Core Tools and press enter
3. Then I get an error in the bottom right hand side "Install or update is only supported for brew or npm" "Source: Azure Functions (Extenison) - Report an issue.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Install or update is only supported for brew or npm.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:50060extension.bundle.js:526:50060
fulfilled extension.bundle.js:526:49473
```

</details>

**Comment by nturinski** [comment]
Hi @joda10

Do you npm install on your machine? https://www.npmjs.com/get-npm

**Comment by joda10** [comment]
Yes this was installed on windows ubuntu session: version 3.5.2 but I haven't installed in the VSCode session!

**Comment by EricJizbaMSFT** [comment]
@joda10 we don't support installing on linux - that's being tracked here: https://github.com/microsoft/vscode-azurefunctions/issues/311

You'll have to manually install on Ubuntu with these instructions: https://github.com/Azure/azure-functions-core-tools#linux
