### ISSUE TITLE
Failed to get status of deployment.

### ISSUE THREAD

**Issue by hari-swaas-2018** [microsoft/vscode-azurefunctions#1958]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:575011
fulfilled extension.bundle.js:1:573270
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hari-swaas-2018 can you add repro steps?

Related to https://github.com/microsoft/vscode-azureappservice/issues/1425.

**Comment by EricJizbaMSFT** [comment]
Checked telemetry and this is happening for linux consumption python function apps. Unlike App service, this does not seem related to local git

**Comment by alxy** [comment]
I have the same issue. Maybe it is related to the size of the zip archive beeing deployed, as the examples from the docs worked fine for me, however uploading a custom project with a bigger trained ML model leads to thhis very same error.

**Comment by eduardomb08** [comment]
I'm having the same problem... @alxy may be right.. I'll investigate tomorrow if removing some files from deployment and thus reducing the size of the zip does anything...

**Comment by eduardomb08** [comment]
I decided to do a quick test now by adding the model extension (.pkl) to the .funcignore file and was able to successfully complete the deployment. So yes, it seems the issue may in fact be related to the deployment/file size. @alxy

**Comment by eduardomb08** [comment]
Oddly enough I removed .pkl extension from .funcignore and redeployed with no issues. @alxy

**Comment by EricJizbaMSFT** [comment]
@eduardomb08 darn I was hoping you had identified the root cause 😂

**Comment by alxy** [comment]
It may still be a timeout issue or something like that, that would also depend on the network and the file size
