### ISSUE TITLE
does not match local run time node

### ISSUE THREAD

**Issue by vaniall2000** [microsoft/vscode-azurefunctions#1959]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: The remote runtime "dotnet" for function app "metamicroFunction1" does not match your local runtime "node".

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:247:322837extension.bundle.js:247:322837
extension.bundle.js:247:322389extension.bundle.js:247:322389
s extension.bundle.js:247:322075
verifyVersionAndLanguage extension.bundle.js:247:322553
Object.<anonymous> extension.bundle.js:247:323558
fulfilled extension.bundle.js:247:322143
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Hi @vaniall2000 

It seems like your local project is a node functions project while your function app is .NET.  You need to create a Node.js Function App to deploy to.
