### ISSUE TITLE
Entry not found in cache on Create New Project (VSCode Extension)

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/vscode-azurefunctions#1960]
Does this occur consistently?  No
Repro steps:

1. Change subscription (Azure Sign In command from VS Code)
2. Click Create New Project in Functions extension

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Entry not found in cache.

Version: 0.21.0
OS: win32
OS Release: 10.0.19569
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46222extension.js:229:46222
extension.js:229:44624extension.js:229:44624
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
