### ISSUE TITLE
Can't deploy function with Consumption plan

### ISSUE THREAD

**Issue by SergeyElchinsky** [microsoft/vscode-azurefunctions#1964]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.21.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078
extension.js:229:46161
extension.js:229:44154
extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
