### ISSUE TITLE
401 error when deploying http function

### ISSUE THREAD

**Issue by preachermaan** [microsoft/vscode-azurefunctions#1965]
Does this occur consistently? 
Repro steps:

1. Followed steps here https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-python

Action: azureFunctions.deploy
Error type: 401
Error Message: Failed with code "401".

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:496:399875extension.bundle.js:496:399875
retryCallback extension.bundle.js:338:114595
retryCallback extension.bundle.js:127:31063
extension.bundle.js:127:32676extension.bundle.js:127:32676
handleRedirect extension.bundle.js:254:7752
extension.bundle.js:127:29848extension.bundle.js:127:29848
Request._callback extension.bundle.js:1:686346
Request.n._callback.n.callback.n.callback extension.bundle.js:314:6016
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:314:19288
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:314:18078
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@preachermaan please add more detailed repro steps. This doesn't repro for us with just that tutorial. It could be something related to your subscription or even a temporary error that goes away if you try again

**Comment by preachermaan** [comment]
Fixed by creating the function app manually in the console first.
