### ISSUE TITLE
Powershell: Remove (Preview) tag from New Project

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-azurefunctions#1966]
![image](https://user-images.githubusercontent.com/15258962/76338222-9ebcd700-62b5-11ea-9f35-671a46d0c56e.png)
https://azure.microsoft.com/en-us/updates/powershell-support-in-azure-functions-is-now-generally-available/

**Comment by EricJizbaMSFT** [comment]
Yeah the reason we haven't removed the label yet is there's a few unacceptable bugs relating to the local debugging experience. In other words, the platform support is GA (you'll notice there's no "Preview" label when creating a function app in Azure), but we're not ready to call the local support "GA". It's a fine line, I know

Here are the bugs: https://github.com/microsoft/vscode-azurefunctions/issues?q=is%3Aopen+label%3APowerShell+label%3Abug

Last I heard, they were mostly blocked by features in PowerShell itself

**Comment by JustinGrote** [comment]
@EricJizbaMSFT Fair enough, I assume this will align with the PS7 functions rollout to get everything "clean". Thanks for the clarification!

**Comment by JustinGrote** [comment]
@TylerLeonhardt Are the blocks that Eric mentioned above now cleared at least in PS7 with the new support that was added?

**Comment by TylerLeonhardt** [comment]
Not until Azure Functions PowerShell worker moves to PS7

**Comment by EricJizbaMSFT** [comment]
Re-opening this for tracking purposes
