### ISSUE TITLE
Host.json: Update JSON Schema to include ManagedDependency

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-azurefunctions#1967]
![image](https://user-images.githubusercontent.com/15258962/76339751-c01ec280-62b7-11ea-90bc-959d0e5c6fa7.png)

**Comment by EricJizbaMSFT** [comment]
Unfortunately my team doesn't own that schema. Looks like there's at least one other issue on the team that does: https://github.com/Azure/Azure-Functions/issues/1203
