### ISSUE TITLE
Issue with Azure function connect to Github repository

### ISSUE THREAD

**Issue by SrinadhBSL** [microsoft/vscode-azurefunctions#1969]
I am unable to connect to Github repository using Azure Function command line in VS Code. Shows below error.

The subscription is not registered for the resource type 'components' in the location 'southindia'. Please re-register for this provider in order to have access to this location.

![image](https://user-images.githubusercontent.com/60921691/76493192-1296e500-6458-11ea-96ea-d2aecb2300ef.png)

**Comment by nturinski** [comment]
Please follow this guide to register the proper component.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types
