### ISSUE TITLE
Error raised when python function is deployed from VS code

### ISSUE THREAD

**Issue by 5MarsR** [microsoft/vscode-azurefunctions#1972]
Erreur de la fonction (muclitech/EventHubTrigger1) : Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.EventHubTrigger1'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.

everytime I try to create an eventhub trigger i get this error when I go to the portal.

**Comment by EricJizbaMSFT** [comment]
@5MarsR event hub triggers require a few app settings. Did you set those when running in Azure? If you already have the settings on your local machine, you can right click on "Application Settings" under the function app and upload the settings

Here are more docs on the event hub trigger: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python

**Comment by 5MarsR** [comment]
yep it seems like I forgot about that I am really sorry about the disturbance
thanks a lot
