### ISSUE TITLE
Azure Function debug not working in VS Code 

### ISSUE THREAD

**Issue by tkopacz** [microsoft/vscode-azurefunctions#1974]
Does this occur consistently? Yes
Repro steps:

1. Create Azure Function project
2. Run it (debug)

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.21.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:96182extension.bundle.js:526:96182
l.fire extensionHostProcess.js:48:845
y.$onDidEndTaskProcess extensionHostProcess.js:758:693
```

</details>

**Comment by tkopacz** [comment]
Forgot to add - function IS working correctly, and compiled correctly etc.

**Comment by EricJizbaMSFT** [comment]
@tkopacz I'm a little confused - so did the build task succeed? Did you get debugging to work eventually? If not, please copy the output from the build task here
