### ISSUE TITLE
Use MSI for installation of core tools on Windows

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#1976]
There's a new Windows installer for the core tools, this may be a good option as it removes node and choco requirements for installing the CLI.

You can find the MSI in their releases here: https://github.com/Azure/azure-functions-core-tools/releases

I have an open question with the team about where else the MSI may be hosted.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime any update on where the MSI is hosted? Don't think it would be good enough to point to that releases page - pretty hard to navigate

**Comment by fiveisprime** [comment]
This isn't ready yet. It's still pending an auto-update mechanism to be released officially.

**Comment by anthonychu** [comment]
@fiveisprime @stefanushinardi Forgot to bring this up today. MSI is ready now and it could help a lot of Windows customers if we use it to install when npm is not available. Please consider for the September release. https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#v2

**Comment by nturinski** [comment]
@anthonychu Anthony, I'm a little uncertain what you wanted to be considered for the release.  Right now, when no package managers are detected (npm/brew), we direct users to this page: https://github.com/Azure/azure-functions-core-tools#installing

This wiki page has direct links for both 64-bit/32-bit versions of the .msi.  Would this be enough to consider this issue resolved, or was there something else that you had in mind?
