### ISSUE TITLE
Can't deploy Python app to Azure function

### ISSUE THREAD

**Issue by l-henri** [microsoft/vscode-azurefunctions#1978]
$
Does this occur consistently? Yes
Repro steps:

1. Create a Python AZF in Azure
2. Create a python project in Visual Studio Code
3. Try to deploy
4. Get an error

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:398:1735889extension.bundle.js:398:1735889
retryCallback extension.bundle.js:338:114595
retryCallback extension.bundle.js:127:31063
extension.bundle.js:127:32676extension.bundle.js:127:32676
handleRedirect extension.bundle.js:254:7752
extension.bundle.js:127:29848extension.bundle.js:127:29848
Request._callback extension.bundle.js:1:686381
Request.n._callback.n.callback.n.callback extension.bundle.js:314:6016
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:314:19288
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:314:18078
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by l-henri** [comment]
Found this
https://github.com/microsoft/vscode-azurefunctions/issues/1027

..\Pablo-monitoring> func pack
Found Python version 3.7.6 (python).
Collecting azure-functions (from -r ..\Pablo-monitoring\requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/2a/82/58337ae36e465df298f61767d6e9977c6170bc0479a99bde42ec70f460db/azure_functions-1.2.0-py3-none-any.whl
  Saved c:\..~1\appdata\local\temp\azureworkermtn84e86\azure_functions-1.2.0-py3-none-any.whl
Successfully downloaded azure-functions
...\AppData\Local\Programs\Python\Python37\python.exe -m pip download -r ...\Documents\Workshop\Pablo-monitoring\requirements.txt --dest ...\AppData\Local\Temp\azureworkermtn84e86
...\AppData\Local\Programs\Python\Python37\python.exe -m pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 37 --implementation cp --abi cp37m --dest ...\AppData\Local\Temp\azureworkergnvweqy6 azure_functions==1.2.0

Creating a new package ...\Pablo-monitoring\Pablo-monitoring.zip

**Comment by EricJizbaMSFT** [comment]
We actually refactored away from "func pack". If you created the project recently, it shouldn't need that. Was this a brand new project? And what type of triggers did you add? `InternalServerError` is a pretty generic error that's hard for us to diagnose - sometimes it works if you just try deploying again
