### ISSUE TITLE
Can't deploy Python Azure TimerTrigger Function

### ISSUE THREAD

**Issue by Smurfffje** [microsoft/vscode-azurefunctions#1979]
When trying to deploy my Python Azure function towards Azure I stumble upon the fact that my TimerTrigger function is not deployed e.g. not visible in the Azure portal. The deployment goes without any errors. Other default template functions like the HTTP trigger and QueueTrigger work fine.

Repro steps:

1. Create an Azure Functions Python project
2. Add a Timer Function
3. Add code to write a message towards a DataTable to verify it ran
4. Run function locally --> works like a charm
5. Click "Deploy to Function App.."
6. Refresh DataTable and notice that there is no new message

VisualStudioCode: v1.43.0
AzureFunctionsExtension: v0.21.0
OS: win10x64
OS Release: 10.0.18362

**Comment by EricJizbaMSFT** [comment]
@Smurfffje the DataTable stuff require a few app settings. Did you remember to set those when running in Azure? If you already have the settings on your local machine, you can right click on "Application Settings" under the function app and upload the settings

If this project is on GitHub somewhere I might be able to take a look. Seems weird that the timer trigger isn't even showing up in the portal

**Comment by Smurfffje** [comment]
@EricJizbaMSFT thanks for the reply, The DataTable stuff is fine since the exact same code in an HTTP trigger function gives the desired output.

It is just the TimerTrigger function, If I create an empty project with just the timertrigger template and deploy it to Azure I get an empty function app. If I add a HTTP trigger function and then redeploy, the function app only has the HTTP trigger function

**Comment by EricJizbaMSFT** [comment]
Okay so I can essentially ignore the DataTable stuff? I'm still gonna need more info here because it works fine for me. Maybe post a screenshot of your workspace and copy the deploy logs here. Also - how did you create the Function App in Azure - from VS Code or the portal? Anything special about it?

**Comment by Smurfffje** [comment]
@EricJizbaMSFT yes that can be ignored, it is purely about the Timer function. I used VS code for everything, nothing special just the basic template like VS code creates them. I have uploaded a screenshot of the workspace, the buildlog as seen in VS code and the important files from the TimerTrigger function
[gitbuildlog.txt](https://github.com/microsoft/vscode-azurefunctions/files/4356383/gitbuildlog.txt)
![workspace](https://user-images.githubusercontent.com/28750403/77102605-68036100-6a19-11ea-8b91-432f30ccf943.PNG)


[__init__.txt](https://github.com/microsoft/vscode-azurefunctions/files/4356387/__init__.txt)

**Comment by Smurfffje** [comment]
This is how it looks from the Azure Portal
![image](https://user-images.githubusercontent.com/28750403/77102933-ecee7a80-6a19-11ea-99ba-7cbfaf6b5fcb.png)

**Comment by EricJizbaMSFT** [comment]
How about the function.json file for the timer trigger

**Comment by Smurfffje** [comment]
```

{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "mytimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    }
  ]
}
```

**Comment by EricJizbaMSFT** [comment]
Yeah I honestly have no idea what's going on here. If this is still happening - you might have better luck with the [Azure Functions support directly](https://github.com/Azure/azure-functions#questions--help). Sometimes the Azure teams has access to more logs which might explain the problem. We also have https://github.com/microsoft/vscode-azurefunctions/issues/1848, but that is usually a momentary problem that goes away after a few minutes

**Comment by Smurfffje** [comment]
Right now it is deploying as expected, however sometimes deployment says that it completed but it did not since it hang on a module installation from the requirements.txt file. But these errors do not end up in the deployment window.

**Comment by EricJizbaMSFT** [comment]
> however sometimes deployment says that it completed but it did not since it hang on a module installation from the requirements.txt file. But these errors do not end up in the deployment window.

This piece should be fixed as a part of https://github.com/microsoft/vscode-azuretools/pull/703. Going to close since that's already tracked in other issues
