### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by khacson** [microsoft/vscode-azurefunctions#1980]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: d:\FPT\UPS\UPS_EU_Plugins.Server\b2cpm-20190507\b2cpm\UPS.ECP.PluginsApis.AzureFunctions.Analytics\bin\Release\netcoreapp2.2\publish

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:468:14354
fulfilled extension.bundle.js:468:13859
```

</details>

**Comment by EricJizbaMSFT** [comment]
@khacson did the `dotnet publish` task succeed? If not, check the output of the task and fix any relevant errors
