### ISSUE TITLE
Install & Update for AZfunction is not working

### ISSUE THREAD

**Issue by MANakib** [microsoft/vscode-azurefunctions#1982]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Install or update is only supported for brew or npm.

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:50060extension.bundle.js:526:50060
fulfilled extension.bundle.js:526:49473
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @MANakib

Do you have npm installed on your machine?  If not, do you have choco installed?  Today we only support npm on Windows.

We currently have an issue tracking Chocolatey support here: https://github.com/microsoft/vscode-azurefunctions/issues/366

Though we may just opt to use the MSI in the future, tracked here: https://github.com/microsoft/vscode-azurefunctions/issues/1976.
