### ISSUE TITLE
Deploy to azure functions, projectLanguage Expected value to be neither null, undefined, nor empty

### ISSUE THREAD

**Issue by damnedOperator** [microsoft/vscode-azurefunctions#1984]
Does this occur consistently? Yes 
Repro steps:

1. Create Function via VS Code
2. Reload Window
3. Try to Deploy via VS Code

Action: azureFunctions.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 0.21.0
OS: linux
OS Release: 4.15.0-1066-oem
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:1:80035
Object.<anonymous> extension.bundle.js:1:835495
fulfilled extension.bundle.js:1:834695
propagateAslWrapper async-listener/index.js:504:23
async-listener/glue.js:188:31
async-listener/index.js:541:70
async-listener/glue.js:188:31
```

</details>

**Comment by EricJizbaMSFT** [comment]
This doesn't reproduce for me with those steps, although could be a linux-specific bug and I'm testing on mac. Could you post a screenshot of your workspace when this happens? Did you open in a new window or add to workspace?

**Comment by damnedOperator** [comment]
This was an issue for me when trying to create a new function with the VS Code extension and the blue flash icon. I added the function to a folder in a workspace. Now - that I create the function project outside of the workspace and add this folder afterwards, it kinda works. In the first function I created and deployed, everything went perfectly. The second one fails with symptoms like Azure-Functions/#1108 

`SCM_RUN_FROM_PACKAGE` for a python app?

![image](https://user-images.githubusercontent.com/49755051/78333067-7446fc80-7589-11ea-8e16-5ccc5b0535a8.png)

VS Code is still giving me a "deployment completed". I am now trying to deploy the function from scratch out of VS Code (normally we build our infrastructure with terraform) and will give you an update.

**Comment by cory-orennia** [comment]
Experiencing this issue as well...

<img width="291" alt="image" src="https://user-images.githubusercontent.com/85305202/211941450-723865eb-133e-4004-9413-f66ea9aed127.png">

Trying to create a brand new function. VS Code 1.74.2 WSL2

**Comment by sadranyi** [comment]
I am also facing similar issues

**Comment by alexweininger** [comment]
@sadranyi could you provide detailed steps that you took to run into this issue? What language and other options did you pick when creating a functions project?
