### ISSUE TITLE
Error during deploy function 

### ISSUE THREAD

**Issue by vglu** [microsoft/vscode-azurefunctions#1985]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:574949
fulfilled extension.bundle.js:1:573208
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
@vglu can you add repro steps?

Related to microsoft/vscode-azureappservice#1425.

**Comment by vglu** [comment]
Hi, @nturinski 

Yes, sure ...
VS Code, Azure function extension, right click on existing function and select deploy to Function app
That's all

Regards,
Vitaliy

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1958
