### ISSUE TITLE
Failed to get latest templates: You must have the .NET Core SDK installed to perform this operation

### ISSUE THREAD

**Issue by xul8tr** [microsoft/vscode-azurefunctions#1986]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to get latest templates: You must have the .NET Core SDK installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:247:349541
fulfilled extension.bundle.js:247:346473
```

</details>

**Comment by EricJizbaMSFT** [comment]
@xul8tr make sure you have the .NET Core sdk installed. See the above link for more information
