### ISSUE TITLE
initail

### ISSUE THREAD

**Issue by holictoweb** [microsoft/vscode-azurefunctions#1987]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python" command. Check output window for more details.

Version: 0.21.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:120540
fulfilled extension.bundle.js:1:119483
```

</details>

**Comment by EricJizbaMSFT** [comment]
@holictoweb please check the output window and copy the contents here if you still need help after that
