### ISSUE TITLE
Error Message: connect ECONNREFUSED 127.0.0.1:10000 

### ISSUE THREAD

**Issue by DenisBalan** [microsoft/vscode-azurefunctions#1988]
Does this occur consistently? Yes
Repro steps:

1. deploy into newly created function app (make sure function is running)
2. make some changes, deploy new version into azure

Action: azureFunctions.deploy
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:10000

Version: 0.21.0
OS: win32
OS Release: 10.0.19587
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1056:14
```

</details>

![image](https://user-images.githubusercontent.com/33955091/77332807-35b07700-6d2b-11ea-84fc-70d01455cb71.png)

There is already same issue, #1521 which was closed with no resolution

**Comment by EricJizbaMSFT** [comment]
@DenisBalan this doesn't reproduce for me with those simple steps. I'll need more information - for example what language your project is, what type of triggers it has, how you created the function app in Azure, etc.

**Comment by DenisBalan** [comment]
@EricJizbaMSFT 
function app linux os
language c#
http trigger
function app created in azure, deployed function from vscode

**Comment by EricJizbaMSFT** [comment]
Are you by chance behind a proxy? Make sure you set that up in VS Code https://code.visualstudio.com/docs/setup/network

Also, [this comment](https://github.com/microsoft/vscode-azureappservice/issues/1460#issuecomment-605388909) seems to suggest all that's needed is a VS Code restart
