### ISSUE TITLE
Offer Assistance on the timer Cron  

### ISSUE THREAD

**Issue by PsychoData** [microsoft/vscode-azurefunctions#1989]
It would be nice if there was a helper for the timer binding for when you are making changes to the schedule - it doesn't use the "normal" linux cron, and that can result in silly things like telling your function to run once every ten seconds instead of every ten minutes. 
![image](https://user-images.githubusercontent.com/3719116/77452772-b5dae900-6dcc-11ea-8399-fe9ae91376ad.png)

It does offer something similar when you are going through the Command "Azure Functions: Add Binding" or that part of the Create Function
![image](https://user-images.githubusercontent.com/3719116/77452806-c12e1480-6dcc-11ea-9541-9f9e4521e7c7.png)

But since this is not "normal" linux cron, it might be nice if it popped up a tooltip or something saying "Hey, use NCRONTAB format - * insert details link *"  or something like that and a link to https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#ncrontab-expressions maybe

**Comment by EricJizbaMSFT** [comment]
Moved to https://github.com/Azure/azure-functions-host/issues/5840
