### ISSUE TITLE
python 3.8.2 does not match supported versions

### ISSUE THREAD

**Issue by odisseo** [microsoft/vscode-azurefunctions#1990]
Windows 10 1909
Visual studio code 1.43.2 (system setup) 64bit
Azure functions 0.21.0
python 3.8.2 64 bit, path OK, VS code python extension OK

When I try to create a new Project it doesn't find the Python interpreter.
I try to enter the Python interpreter manually.

I have this error: "Python version 3.8.2 does not match supported version"
But in your documentation it's written: "Python 3.6.x, 3.7.x, or 3.8.x"

I tried also with Python 3.8 from windows store. Same error.
No problem with Python 3.7.7.

I can't find a why.
Thanks in advance

**Comment by EricJizbaMSFT** [comment]
@odisseo what version of the func cli do you have? You need at least 3.0.2245 to work with Python 3.8

**Comment by odisseo** [comment]
Great Eric!
I though to all but not the obvious :)
Have a good day
