### ISSUE TITLE
Can't create function via vscode

### ISSUE THREAD

**Issue by acollier88** [microsoft/vscode-azurefunctions#1993]
Repro steps:
1. Trying to deploy a function to azure for company's internal ase .
2. Error

Action: azureFunctions.deploy
Error type: UNABLE_TO_VERIFY_LEAF_SIGNATURE
Error Message: unable to verify the first certificate

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@acollier88 looks like you're on a pretty old version of the extension. Try updating both your VS Code version (latest is 1.43.2) and our extension version (latest is 0.21.0). VS Code in particular has done quite a bit of work to fix issues around proxies and certificates
