### ISSUE TITLE
Update create flow to set linuxFxVersion for dotnet function apps

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/vscode-azurefunctions#1994]
cc  @ankitkumarr @divyagandhii
- For V3 linux function apps - set linuxFxVersion to `dotnet|3.1`
- For V2 linux function apps - set linuxFxVersion to `dotnet|2.2`

**Comment by EricJizbaMSFT** [comment]
@pragnagopa I'm pretty sure we already do this. Any particular reason you believe otherwise?

**Comment by pragnagopa** [comment]
we recently started supporting runtime|runtimeVersion format for linux function apps. Can you please double check? If it is in the expected format, please go ahead and close this issue.

**Comment by EricJizbaMSFT** [comment]
This was fixed in https://github.com/microsoft/vscode-azurefunctions/pull/1904
