### ISSUE TITLE
Function host is no longer running?

### ISSUE THREAD

**Issue by swaraadam** [microsoft/vscode-azurefunctions#1997]
Does this occur consistently? 
Repro steps:

1. Run ddebugging
2. install azure functions core tools

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:96869extension.bundle.js:526:96869
fulfilled extension.bundle.js:526:94354
```

</details>

**Comment by EricJizbaMSFT** [comment]
@swaraadam this doesn't reproduce for me with those steps. Can you add more information? For example - what version of the func cli did you install? Does it work if you reload the window? How did you create the project?
