### ISSUE TITLE
Support testing templates from extension bundles from a custom source

### ISSUE THREAD

**Issue by soninaren** [microsoft/vscode-azurefunctions#1998]
We need a configuration from vs code extension that would allow us to test the templates from extension bundles that are a different source that default. This is mainly for the purpose of testing, not for production support.

The config setting should expect a URI that follows the same convention as : https://functionscdn.azureedge.net/public
`ExtensionBundleTemplateSourceURI`

Since the setting is only responsible for testing templates, the only way to verify the setting would be to look at the templates loaded from the specific extension bundle.

For users this setting would make sense to be used in conjunction with the environment variable `FUNCTIONS_EXTENSIONBUNDLE_SOURCE_URI` supported by runtime to bundles from a custom source.

**Comment by EricJizbaMSFT** [comment]
Added support for the same environment variable - `FUNCTIONS_EXTENSIONBUNDLE_SOURCE_URI`
