### ISSUE TITLE
C# Attach fails if function.cs file is deleted

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#200]
Not sure if this classifies as a bug.

Repro:
1.) Create a trigger.
2.) Delete the trigger .cs file from the root of your project.
3.) F5

Because the trigger still exists in Debug -> net461 -> bin, the func host start will get stuck and fail.

**Comment by EricJizbaMSFT** [comment]
Yeah this is valid. The easy workaround is to run `dotnet clean` after you delete a function. However, we could consider running that for every F5
