### ISSUE TITLE
Keep running preDeployTask "npm prune" more than 10 mins for JS project

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#2001]
**OS:** Windows , Mac
**Build Version:** [20200401.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17095&view=results)
**Node.js Version**: v12.16.1

**Repro Steps:**
1. Create a JS project --> Click the Deploy button --> New a function app.
2. Deploy --> Check the progress.

**Expect:**
Succeed to deploy in time.

**Actual:**
Keep running preDeployTask "npm prune" more than 10 mins.
![image](https://user-images.githubusercontent.com/34729092/78118681-ed373e80-7439-11ea-855c-b4d1b17180b7.png)

**More Info:**
Not reproduce for C#, TS, PS, Python.

**Comment by EricJizbaMSFT** [comment]
Probably related to https://github.com/microsoft/vscode-azureappservice/issues/1428
