### ISSUE TITLE
View with id 'azureStorage' already registered

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-azurefunctions#2002]
I hate how open this bug is, but I don't even know how to diagnose, or turn off:

![image](https://user-images.githubusercontent.com/51317/78159873-05866980-73f8-11ea-946a-9c941a63fb4a.png)

This came after installing azureFunctions - here's the data on my installation:

Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Where should I start to investigate?

**Comment by EricJizbaMSFT** [comment]
That is quite odd. The error message in the screenshot is mentioning our "Azure Storage" extension, not the "Functions" extension. I would start by checking which extensions you have installed and making sure it looks right. You can try reloading VS Code or uninstalling/installing extensions. If that doesn't work, I'd look at the extensions folder on your machine. It should be at this path:

Windows `%USERPROFILE%\.vscode\extensions`
macOS `~/.vscode/extensions`
Linux `~/.vscode/extensions`

Look for folders with the "ms-azuretools.vscode-azurestorage" id and delete any duplicate ones

**Comment by aronchick** [comment]
I uninstalled every extension and it went away (as I would have expected it to) - if I need the extension and it comes back on reinstall, I'll reopen.
