### ISSUE TITLE
Error while deploying using VS Code

### ISSUE THREAD

**Issue by merciabcs** [microsoft/vscode-azurefunctions#2005]
Does this occur consistently? Yes, My first experience with azure functions and this is happening every time I need to deploy.
Repro steps:
1. Azure Tab
2. Deploy to function app
3. Choose the function

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:398:1735889extension.bundle.js:398:1735889
retryCallback extension.bundle.js:338:114595
retryCallback extension.bundle.js:127:31063
extension.bundle.js:127:32676extension.bundle.js:127:32676
handleRedirect extension.bundle.js:254:7752
extension.bundle.js:127:29848extension.bundle.js:127:29848
Request._callback extension.bundle.js:1:686381
Request.n._callback.n.callback.n.callback extension.bundle.js:314:6016
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:314:19288
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:314:18078
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@merciabcs please walk me through the steps on how you created the local project and how you created the function app in Azure. Did you do it in the func cli, VS Code, or the portal? If you did it in VS Code - let me know which options you picked

**Comment by merciabcs** [comment]
Hi Eric,
I solved with my company’s support. The security closed the network access to this so we ended up using VSTS pipeline to deploy the function instead of VS Code
Regards
Mercia
