### ISSUE TITLE
azure cloud function error

### ISSUE THREAD

**Issue by rvigneshw** [microsoft/vscode-azurefunctions#2006]
Does this occur consistently?  Yes 

1.click deploty icon in vs code

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rvigneshw I cannot reproduce your error with just those steps. Are you behind a proxy? Please check out VS Code's docs on how to set that up: https://code.visualstudio.com/docs/setup/network
