### ISSUE TITLE
Improve webpack require time

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode-azurefunctions#2008]
- Issue Type: `Performance`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.19592`
- VSCode version: Code - Insiders `1.44.0-insider` (20b88fa0694cae8e46ffd305a1450ba58ae6065b, 2020-04-01T08:35:20.764Z)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Extension | Author (truncated) | Version
-- | -- | --
vscode-django | bat | 0.20.0
npm-intellisense | chr | 1.3.0
vscode-markdownlint | Dav | 0.34.0
vscode-eslint | dba | 2.1.2
githistory | don | 0.6.3
python-extension-pack | don | 1.6.0
prettier-vscode | esb | 4.0.0
code-runner | for | 0.9.17
beautify | Hoo | 1.5.0
vscode-peacock | joh | 3.6.0
chat | kar | 0.33.0
vscode-codemetrics | kis | 1.24.0
vscode-github | Kni | 0.30.3
MagicPython | mag | 1.1.0
vscode-azurefunctions | ms- | 0.21.0
python | ms- | 2020.3.71659
remote-wsl | ms- | 0.44.2
azure-account | ms- | 0.8.8
powershell-preview | ms- | 2020.3.2
vsliveshare | ms- | 1.0.1891
vsliveshare-audio | ms- | 0.1.80
vsliveshare-pack | ms- | 0.3.4
debugger-for-chrome | msj | 4.12.6
vscode-for-node-js-development-pack | nod | 2.0.1
subtitles-editor | pep | 1.0.4
java | red | 0.59.1
vscode-xml | red | 0.11.0
vscode-checkstyle | she | 1.3.2
vscodeintellicode | Vis | 1.2.6
vscode-java-debug | vsc | 0.25.1
vscode-java-dependency | vsc | 0.9.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.3
vscode-maven | vsc | 0.21.2
python-auto-venv | whi | 1.0.0
jinja | who | 0.0.8
vscode-import-cost | wix | 2.12.0
vscode-preview-server | yui | 1.3.0
markdown-all-in-one | yzh | 2.7.0

</details>

I have **attached** this file from my *home*-directory:
[ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azurefunctions/files/4429866/ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt)

**Comment by EricJizbaMSFT** [comment]
Looks like the slowest piece was it took ~7 seconds to load the extension itself ("\_\_webpack\_require\_\_"). That's on the slow side considering we're using webpack, but not the worst. Could look into lazy-loading some modules

**Comment by EricJizbaMSFT** [comment]
Improved in https://github.com/microsoft/vscode-azurefunctions/pull/2257. The new packages in the sdk are much smaller than the old, making us faster to load.
