### ISSUE TITLE
unable to create blobtrigger function

### ISSUE THREAD

**Issue by alyssakayo** [microsoft/vscode-azurefunctions#2011]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token   in JSON at position 5.

Version: 0.21.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:320812
fulfilled extension.bundle.js:1:320105
```

</details>

**Comment by EricJizbaMSFT** [comment]
@alyssakayo please double check your "local.settings.json" file and make sure it is valid json
