### ISSUE TITLE
problem debugging second function in my function app

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoft/vscode-azurefunctions#2014]
My directory structure:

PythonFunctions/  # should be "__app__"?
    MyFunc1/
        __init__.py  # fixed; was "init.py"
        function.json
    MyFunc2/
        __init__.py  # fixed; was "init.py"
        function.json
    local.settings.json
    requirements.txt
...just as 'Azure Functions Python developer guide' recommends.

I can successfully debug MyFunc1, but trying to debug MyFunc2 returns "404 Not Found" when I call it using Postman, even when I close MyFunc1 from VS Code...
WHY ???

VS Code version: Code 1.43.0 (78a4c91, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by EricJizbaMSFT** [comment]
@EsaHeikkiPoutanen can you post a screenshot of your workspace? You should have "PythonFunctions" open as the root folder to debug both functions. In addition, you can use our "Create Project" and "Create Function" buttons which will set up the correct file structure for you.

<img width="289" alt="Screen Shot 2020-04-06 at 11 24 57 AM" src="https://user-images.githubusercontent.com/11282622/78592111-68617180-77f9-11ea-91e2-b381c10e7ec8.png">

**Comment by EsaHeikkiPoutanen** [comment]
Idid have:
![PyhtonFunctions](https://user-images.githubusercontent.com/45006491/79203689-0e3d5d80-7e44-11ea-89eb-fc45b97bd912.PNG)
at lesat I think so..

**Comment by EricJizbaMSFT** [comment]
Sorry I meant a screenshot of the file explorer view. Something like this:
<img width="455" alt="Screen Shot 2020-04-14 at 10 15 34 AM" src="https://user-images.githubusercontent.com/11282622/79253995-e8f72200-7e38-11ea-9186-55a59497add9.png">

**Comment by EsaHeikkiPoutanen** [comment]
Oh, ok:

![PythonFunctions_dir](https://user-images.githubusercontent.com/45006491/79299021-8f9bfb00-7eeb-11ea-8220-3a62359b12d2.PNG)

**Comment by alexweininger** [comment]
Closing as stale. Please open another issue if you're still facing this.
