### ISSUE TITLE
Python Azure Function Failed

### ISSUE THREAD

**Issue by joshdotexe** [microsoft/vscode-azurefunctions#2015]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Deployment to "fazbear-py" failed. See output channel for more details.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:576131
fulfilled extension.bundle.js:1:573270
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@joshdotexe please check the output window for errors. If that doesn't help, add repro steps and copy the output here
