### ISSUE TITLE
There is a deployment currently in progress. Please try again when it completes

### ISSUE THREAD

**Issue by wernerchao** [microsoft/vscode-azurefunctions#2018]
I keep getting this error message, although last time I deployed was several days ago. There is nothing in progress. I tried logging out and back in. Still getting the same error.
In the past when I get this message, the only solution is to delete the Azure Function and create a new one, but this is very time consuimg.

Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.21.0
OS: darwin
OS Release: 19.0.0
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:496:399875
retryCallback extension.bundle.js:338:114595
retryCallback extension.bundle.js:127:31063
extension.bundle.js:127:32676
handleRedirect extension.bundle.js:254:7752
extension.bundle.js:127:29848
Request._callback extension.bundle.js:1:686346
Request.n._callback.n.callback.n.callback extension.bundle.js:314:6016
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:314:19288
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:314:18078
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@wernerchao unfortunately that error is coming directly from Azure, not our extension. We've seen [other people](https://github.com/microsoft/vscode-azureappservice/issues/1462) run into it, too, but don't have a way to fix. I would suggest contacting Azure support directly - I believe the easiest way is through the question mark button in the portal.
