### ISSUE TITLE
[Unstable]Creating a new function app loses the Step selecting OS when deploying 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#2022]
**OS:** Windows
**Build Version:** [20200406.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17411&view=results)

**Repro Steps:**
1, Right click one applied subscription --> Select "Create Function App in Azure..." -->  Check the steps of creating a new function app with basic creation.
2. There are 4 steps.
3. Create a project --> Click the deploy button --> Select "Create new Function App in Azure..." when prompting to select a function app --> Check the steps.

**Expect:**
There are still 4 steps when creating a basic function app.

**Actual:**
Lose the Step selecting OS.
![image](https://user-images.githubusercontent.com/34729092/78648165-37169d80-78ee-11ea-9ffd-08681659d5ed.png)

**Comment by v-ruizh** [comment]
This is a by design issue, please get the details from https://github.com/microsoft/vscode-azurefunctions/issues/1771.
