### ISSUE TITLE
I got this issue when use VS code to deploy Azure function, does anyone have the solution?

### ISSUE THREAD

**Issue by RainWuGuy** [microsoft/vscode-azurefunctions#2031]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: ETIMEDOUT
Error Message: connect ETIMEDOUT 220.250.64.225:443

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
See https://github.com/microsoft/vscode-azurefunctions/issues/2032#issuecomment-612143166

**Comment by RainWuGuy** [comment]
> See [#2032 (comment)](https://github.com/microsoft/vscode-azurefunctions/issues/2032#issuecomment-612143166)

I found the issue eventually I set the wrong storage account for the functions
