### ISSUE TITLE
deploy Azure function get ENOTFOUND issue

### ISSUE THREAD

**Issue by RainWuGuy** [microsoft/vscode-azurefunctions#2032]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND storageaccountstoreabb5.blob.core.windows.net storageaccountstoreabb5.blob.core.windows.net:443

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@RainWuGuy looks like you're on a pretty old version of the extension - please update to the latest (v0.22.0). NOTE: This requires at least version 1.37.0 of VS Code (the latest is 1.44.0), so make sure that is up to date as well

**Comment by RainWuGuy** [comment]
> @RainWuGuy looks like you're on a pretty old version of the extension - please update to the latest (v0.22.0). NOTE: This requires at least version 1.37.0 of VS Code (the latest is 1.44.0), so make sure that is up to date as well

I found the issue eventually I set the wrong storage account for the functions
