### ISSUE TITLE
Better native node module support

### ISSUE THREAD

**Issue by rolledback** [microsoft/vscode-azurefunctions#2034]
If you're on 64bit Windows, creating a Windows node function that uses native node modules, the default tasks won't ever successfully deploy a working function.

Since Windows Azure Functions use 32bit node, then your native modules need to be compiled to 32bit. But by default, node will compile to 64bit.

I had thought that adding an `.npmrc` at my root with `npm_config_arch=ia32` would fix this, but it seems that when npm is invoked by the deploy tasks it doesn't see my `.npmrc`. Ultimately, I had to modify the install task:
```json
{
  "type": "shell",
  "label": "npm install",
  "command": "npm install --arch=ia32"
}
```

I would be nice if when deploying to a Windows function, the `--arch=ia32` argument was added automatically.

**Comment by EricJizbaMSFT** [comment]
> I had thought that adding an .npmrc at my root with npm_config_arch=ia32 would fix this

I don't think you're supposed to specify `npm_config_` in a `.npmrc` file. Try just `arch=ia32`

> Since Windows Azure Functions use 32bit node

Fwiw, this is configurable in the portal:

![Screen Shot 2020-04-13 at 1 37 46 PM](https://user-images.githubusercontent.com/11282622/79159446-efc85b00-7d8c-11ea-89b3-c23e36a063b1.png)

Also, linux function apps default to 64 bit.

**Comment by rolledback** [comment]
> I don't think you're supposed to specify npm_config_ in a .npmrc file. Try just arch=ia32
Perfect, that worked!

> Since Windows Azure Functions use 32bit node
Thanks for pointing this out. Maybe 64 bit would be a better default for Windows?

**Comment by rolledback** [comment]
> Fwiw, this is configurable in the portal:

It actually looks like you have to do quite a few more steps to get the 64 bit Node going: https://github.com/Azure/azure-functions-nodejs-worker/issues/158#issuecomment-540232863
