### ISSUE TITLE
No VSCode remote debugging even with required Linux App Service Plan

### ISSUE THREAD

**Issue by lhale** [microsoft/vscode-azurefunctions#2036]
Does this occur consistently? Yes
Repro steps:

1. https://docs.microsoft.com/en-us/azure/azure-functions/create-function-app-linux-app-service-plan
2. Start remote debugging of function app from VSCode

Expected: Same levels of debugging as could be done locally.

Action: azureFunctions.startRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js Function Apps running on Linux App Service plans. Consumption plans are not supported.

Version: 0.22.0
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.getRemoteDebugLanguage extension.bundle.js:334:109769
extension.bundle.js:334:109416extension.bundle.js:334:109416
fulfilled extension.bundle.js:334:108644
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Is your Linux App Service plan running Node.js Function triggers?  Also, note that consumption plans are not supported.
