### ISSUE TITLE
Maven not found in path when creating Java Function

### ISSUE THREAD

**Issue by dgpoulet** [microsoft/vscode-azurefunctions#2038]
Trying to create a new Java function re: https://code.visualstudio.com/docs/java/java-azurefunctions

I'm getting the following error when I try to create the new function in VS Code:
"Failed to find "maven", please ensure that the maven bin directory is in your system path."

Maven is in the system path, JAVA_HOME is set correctly to the JDK folder. I can run up mvn in the terminal window in VSCode no problem. I've restarted VSCode, restarted the machine, I still get the same error. 

I'm running VS Code on Windows 10
Maven version: 3.6.3
JDK version: 1.8.0

**Comment by EricJizbaMSFT** [comment]
It's possible `mvn` is in your PATH for PowerShell (is that your terminal in VS Code?), but not `cmd` which is what we use. I want to fix that as a part of https://github.com/microsoft/vscode-azurefunctions/issues/2019. In the meantime, you could try opening up a `cmd` window and making sure `mvn --version` works there

**Comment by dgpoulet** [comment]
No, `mvn` was in my path for `cmd` also, but after playing around I discovered the problem: I did not have `%SystemRoot%\System32` in my system path, and this was throwing up **this** error as part of the output when `mvn` was invoked: 

> 'cmd' is not recognized as an internal or external command, operable program or batch file...

So although it seemed that `mvn` was working, it was obviously not able to find `cmd` itself and that was causing an issue.

Once I added the System32 path above the error went away and the create function operation started working.
