### ISSUE TITLE
core prob

### ISSUE THREAD

**Issue by sofasofa** [microsoft/vscode-azurefunctions#2039]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Install or update is only supported for brew or npm.

Version: 0.21.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.0
Language: fr

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:50060extension.bundle.js:526:50060
fulfilled extension.bundle.js:526:49473
```

</details>

**Comment by nturinski** [comment]
Hi @sofasofa

If you don't have npm installed, you can follow the instructions [here](https://github.com/Azure/azure-functions-core-tools#installing) to install the Function Core Tools
