### ISSUE TITLE
Failed to deploy path that does not exist target\azure-functions\TestDataAsAService

### ISSUE THREAD

**Issue by 903447** [microsoft/vscode-azurefunctions#2042]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\sukummar\git\Azure\Azure-MGMIntegrationTestAutomation\target\azure-functions\TestDataAsAService

Version: 0.22.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:281:26571
fulfilled extension.bundle.js:281:26075
o extension.bundle.js:1:255722
extension.bundle.js:1:256219extension.bundle.js:1:256219
```

</details>

**Comment by nturinski** [comment]
@903447 Thanks for reporting.  Could you provide repro steps?
