### ISSUE TITLE
Encountered an error (InternalServerError) from host runtime when syncing trigger

### ISSUE THREAD

**Issue by sparisSigfox** [microsoft/vscode-azurefunctions#2043]
Does this occur consistently? Yes
Repro steps:

1. Deploy app via Visual Studio
2. 20:18:40 timetrigger3: Syncing triggers...
20:19:21 timetrigger3: Syncing triggers (Attempt 2/6)...
20:19:32 timetrigger3: Syncing triggers (Attempt 3/6)...
20:19:52 timetrigger3: Syncing triggers (Attempt 4/6)...
20:20:33 timetrigger3: Syncing triggers (Attempt 5/6)...
20:21:54 timetrigger3: Syncing triggers (Attempt 6/6)...
20:21:59: Error: Encountered an error (InternalServerError) from host runtime.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.22.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2842864extension.bundle.js:225:2842864
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:669125
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sparisSigfox this does not reproduce for me with just those steps. Please add more detailed information about your setup and how you got to this point
