### ISSUE TITLE
Not possible to deploy functions from VS Code. Region error on multiple regions.

### ISSUE THREAD

**Issue by dev-ruben-lopez** [microsoft/vscode-azurefunctions#2044]
Does this occur consistently? 
Repro steps:

1. Following the Azure Training https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account

2. After set up VS Code with the Subscription ID, and then trying to use Azure Function: Deploy Advance and Basic modes, neither works. 

3. Tried on 4 different zones, none works.

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.22.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2905728extension.bundle.js:225:2905728
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:669125
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
Request.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Unfortunately, there's quite a few restrictions on regions right now. You can read more [here](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/) and just try a different region to see if it works

> As demand continues to grow, if we are faced with any capacity constraints in any region during this time, we have established clear criteria for the priority of new cloud capacity. Top priority will be going to first responders, health and emergency management services, critical government infrastructure organizational use, and ensuring remote workers stay up and running with the core functionality of Teams. We will also consider adjusting free offers, as necessary, to ensure support of existing customers.
