### ISSUE TITLE
Microsoft Learn - "Build Serverless APIs with Azure Functions"

### ISSUE THREAD

**Issue by albertodenatale** [microsoft/vscode-azurefunctions#2047]
Does this occur consistently? Yes
Repro steps:

When reaching unit 12/13 of Microsoft Learn "Build Serverless APIs with Azure Functions".

![image](https://user-images.githubusercontent.com/11591862/80064730-09aa3080-8539-11ea-98cf-336d0dabe63a.png)

The error is triggered when I reach the step where I have to specify my hosting plan ("Consumption").

The same error is visible here:

![image](https://user-images.githubusercontent.com/11591862/80065513-8d185180-853a-11ea-8b09-3d7b31af9b28.png)

It fixed by signing out from Azure and signing back in.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092extension.js:229:174092
extension.js:229:46175extension.js:229:46175
extension.js:229:44168extension.js:229:44168
extension.js:229:43790extension.js:229:43790
i.find extension.js:229:78283
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53

**Comment by albertodenatale** [comment]
@EricJizbaMSFT thank you a lot for your help
