### ISSUE TITLE
Fail to get the Python version when verifying the response from http trigger

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2048]
**OS:** All
**Build**: [20200417.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17972&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a new Python project.
2. Modify the __init_.py_ file like below.
```
        import logging
	import sys
	import azure.functions as func
	
	def main(req: func.HttpRequest) -> func.HttpResponse:
	    logging.info('Python HTTP trigger function processed a request.')
	    return func.HttpResponse(
	        f"Python Version: {sys.version_info[0]}.{sys.version_info[1]}",
	        status_code=400
	    )
```

3. Deploy this project to a new Function App.
4. Query the http trigger after deploying finishes.
5. Verify the result. 

**Expect:**
Succeed to get the correct Python version that selected in previous step.

**Actual:**
Nothing displays. 
![image](https://user-images.githubusercontent.com/57662131/80195664-c7731300-864e-11ea-825e-2dea9070a3e3.png)

**Comment by EricJizbaMSFT** [comment]
This doesn't repro for me. curl is sometimes weird on windows cmd. Does it work if you just enter the url into your browser?

**Comment by v-xinda** [comment]
Show "HTTP 500 error" after entering the url into browser.
![image](https://user-images.githubusercontent.com/57662131/80452262-7158e500-8958-11ea-9c61-9becaf496301.png)

**Comment by EricJizbaMSFT** [comment]
Can you copy/paste the deployment logs, and try streaming logs when you hit the url and copy that output as well.

Also - double-check the whitespace in your `__init__.py`. Python will break if the whitespace isn't correct

**Comment by v-xinda** [comment]
Get the Python version successfully by manually editing the `__init__.py`, rather than copy content from testcase.
