### ISSUE TITLE
facing issue while executing azure function host not start

### ISSUE THREAD

**Issue by yogendra068** [microsoft/vscode-azurefunctions#2049]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.22.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:100652extension.bundle.js:334:100652
fulfilled extension.bundle.js:334:98074
```

</details>

**Comment by EricJizbaMSFT** [comment]
@yogendra068 please add repro steps
