### ISSUE TITLE
Incorrect HTTPTrigger URLs in the console when custom route is defined 

### ISSUE THREAD

**Issue by simonaco** [Microsoft/vscode-azurefunctions#205]
Steps:
Define custom route in function.json
Publish function app to Azure using extension 
Notice URLs listed in the console are incorrect( https://sicotin-servelessapi2.azurewebsites.net/api/CreateHero instead of 
https://sicotin-servelessapi2.azurewebsites.net/api/hero )

<img width="1156" alt="screen shot 2018-02-05 at 07 26 07" src="https://user-images.githubusercontent.com/1573904/35804471-fde5cc3e-0a45-11e8-9f01-5bab6abb8f1f.png">

**Comment by BadgerCode** [comment]
The same happens if you have a custom route prefix in the host.json file.

**host.json**
```json
{
    "http": {
        "routePrefix": ""
    }
}
```

**function.json**
```json
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "route": "v1/lenny",
      "methods": [ "get" ],
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "disabled": false
}
```

Expected url: ```https://live-uksouth-lenny-today.azurewebsites.net/v1/lenny```
Actual url: ```https://live-uksouth-lenny-today.azurewebsites.net/api/v1-lenny```

**Comment by EricJizbaMSFT** [comment]
Removing from future milestone. As a part of https://github.com/Azure/azure-functions-host/issues/3994, there will be a new ARM api that creates this url for us (instead of us having to manually parse out the route, etc.)
