### ISSUE TITLE
error when deploy to azure from visual studio code"Azure IoT Device Workbench: Deploy to Azure". 

### ISSUE THREAD

**Issue by tmalahlela** [microsoft/vscode-azurefunctions#2053]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\tmala\Documents\IoTWorkbenchProjects\examples\devkit_translator\Functions\bin\Release\netcoreapp2.1\publish

Version: 0.22.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:281:26571
fulfilled extension.bundle.js:281:26075
```

</details>

**Comment by EricJizbaMSFT** [comment]
@tmalahlela did the publish task succeed? That path won't exist if it failed. Please check your task output and if that doesn't help, add more detailed repro steps here
