### ISSUE TITLE
Add support for CI/CD

### ISSUE THREAD

**Issue by mhoeger** [microsoft/vscode-azurefunctions#2054]
Maybe this is already being tracked or discussed somewhere, but it would be awesome if the extension could try to encourage folks to set up CI/CD. Especially if the project is already being source controlled and we know that integration would be smooth (like GitHub actions or DevOps). Thinking a lot about how users might be pushing directly to PROD because it's so easy to deploy through VS Code (which is so amazing but would be nice to surface easy best practices too)

**Comment by fiveisprime** [comment]
This would be beyond the current GitHub deployment source and include the ability to run a build/test step. Ideally this would hook into GH Actions and work like other products.
