### ISSUE TITLE
Reported Issues from VS Code

### ISSUE THREAD

**Issue by vermavarun** [microsoft/vscode-azurefunctions#2055]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postDeploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.22.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@vermavarun please add repro steps
