### ISSUE TITLE
Resource type could not be found in the namespace 'Microsoft.Insights' for api version '2015-05-01'.

### ISSUE THREAD

**Issue by mouaxiong** [microsoft/vscode-azurefunctions#2057]
Does this occur consistently? 
Repro steps:

1.  Create a node app Azure Function
2.  Deploy to Azure Germany Central as Azure Function
3.  During the storage account creation, failing due to message below

Action: azureFunctions.deploy
Error type: InvalidResourceType
Error Message: The resource type could not be found in the namespace 'Microsoft.Insights' for api version '2015-05-01'.

Version: 0.22.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:897101extension.bundle.js:225:897101
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:669125
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mouaxiong as a workaround you can use "Advanced" creation and select "Skip for now" when it asks about App Insights
