### ISSUE TITLE
Add gestures to manage extension bundles

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2058]
Related: https://github.com/Azure/azure-functions-core-tools/issues/1913

V2 extension bundles are on the way, so an app could be in these 4 states:

- No extensions or extension bundles
- Manually installed extensions in extensions.csproj
- Bundles V1
- Bundles V2

Would like to add a gesture to set extension bundles in a project (perhaps a context menu on host.json):

- V1 -> V2
- V2 -> V1
- No extensions -> V1/V2
- extensions.csproj -> V1/V2

User should be warned about the consequences and include an option to open bundles docs. The extension also needs to update the launch settings accordingly.

Unlike the Core Tools, VS Code probably doesn't need to consider moving from bundles to manually installed extensions.

**Comment by EricJizbaMSFT** [comment]
@anthonychu can you expand on the motivation for this issue?

AFAIK - the only change required to switch between bundle version is editing host.json. If the user is advanced enough to know they need to change bundle version - would a right click menu to change bundle add value over simply editing the file?

**Comment by anthonychu** [comment]
I think there are cases where the user isn't necessarily "advanced" but they need to do it to take advantage of a capability. A concrete example is a JS dev who wants to use Durable Entities, which needs Durable Functions V2 in bundles V2.. The first thing they need to do after creating a new project is to change to bundles V2 before entities would work and they see the entities template (when the template becomes available).

This gesture will help in docs as well, especially in quickstarts. In the case of Durable Functions, one of the first steps in the quickstart will be to switch to Bundles V2, and the simpler we make that, the less likely that we'll lose the person on that step.

I think in general it would be great to make it easier to change the bundle version and minimize mistakes, even for advanced users.

I know there's also an obvious way to solve it and that is to default to v2, but I think we might want to wait on that. In the past we talked about establishing a cadence for updating the defaults for tooling. /cc @mattchenderson @soninaren

**Comment by EricJizbaMSFT** [comment]
I just feel like updating a dependency version is a common concept - in a package.json, requirements.txt, or csproj. I'm not saying these have to be super advanced users, but if they've figured out they need a non-default version of a bundle, it seems on-par for them to update that version in a functions-specific file (host.json).

In terms of the docs, this:

> If you're using VS Code, right click on your "host.json" file, select "Update bundle" and choose "V2"

doesn't feel any simpler to me than this:

> Ensure the version of your extension bundle in "host.json" is `[2.*, 3.0.0)`

In addition the second option has the following benefits:
1. It's the same regardless of CLI, VS Code, or no tooling at all
1. It teaches the user how the bundle is actually controlled and where to go if they have a problem with bundles
1. It's not hiding anything. The first option makes me suspicious there's more going on under the covers for a simple version update
