### ISSUE TITLE
linter using v1 schema to validate v2 host.json

### ISSUE THREAD

**Issue by probablyup** [microsoft/vscode-azurefunctions#2060]
```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
    "http": {
      "customHeaders": {
        "Content-Type": "application/json"
      }
    }
  }
}
```

The "http" and "customHeaders" fragments are flagged as linter warnings where they're allowed by the JSON schema `version-2`: http://json.schemastore.org/host

**Comment by EricJizbaMSFT** [comment]
For "http", the linter warning I see is `Missing property "routePrefix".` which is accurate

For "customHeaders", I think there's a bug in the schema. I don't see it on the "http-extension" object. You might want to file an issue here: https://github.com/Azure/azure-functions-host
