### ISSUE TITLE
Error deployment function app

### ISSUE THREAD

**Issue by workuniversity** [microsoft/vscode-azurefunctions#2061]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092
extension.js:229:46175
extension.js:229:44168
extension.js:229:43790
i.find extension.js:229:78283
extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
