### ISSUE TITLE
Having issues with azure functions. New to the product. Any help?

### ISSUE THREAD

**Issue by jaredguy** [microsoft/vscode-azurefunctions#2063]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.viewProperties
Error type: Error
Error Message: cannot open azureextensionuiReadonly:/eb890a84aa5508ebb21773af3c56c9f037fc778864ea327c645828ee286d7a2d/systemateadminfnapp1.json. Detail: Internal error: Expected value to be neither null nor undefined: ReadOnlyContentProvider._contentMap.get

Version: 0.22.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:4437:262
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jaredguy please add repro steps
