### ISSUE TITLE
Error: "Entry not found in cache" after selecting the folder to deploy the Python function

### ISSUE THREAD

**Issue by fjanon** [microsoft/vscode-azurefunctions#2064]
Looks the same as #2061

Does this occur consistently?
Yes
Repro steps:

1. Select the folder with the Python Function
2. Click on the Upload icon in Visual Code

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092
extension.js:229:46227
extension.js:229:45094
B._callback extension.js:1:182028
B.t._callback.t.callback.t.callback extension.js:181:5470
B.emit events.js:203:13
B.<anonymous> extension.js:181:18298
B.emit events.js:203:13
IncomingMessage.<anonymous> extension.js:181:17140
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
