### ISSUE TITLE
Entry Not Found

### ISSUE THREAD

**Issue by ah6511** [microsoft/vscode-azurefunctions#2068]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092
extension.js:229:46227
extension.js:229:45094
B._callback extension.js:1:182028
B.t._callback.t.callback.t.callback [as callback] extension.js:181:5470
B.emit events.js:203:13
B.EventEmitter.emit domain.js:476:20
B.<anonymous> extension.js:181:18298
B.emit events.js:203:13
B.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.js:181:17140
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
