### ISSUE TITLE
Create Function doesn't honour azureFunctions.deploySubpath?

### ISSUE THREAD

**Issue by o-o00o-o** [microsoft/vscode-azurefunctions#2069]
Not sure what is going wrong here

I already have a Functions folder and it is in a subfolder of my root. I have the following in my .vscode\settings.json

```
"azureFunctions.deploySubpath": "src\\Functions",
```

When I use the Azure Functions \ Create Function.. it tells me 

```
[Window Title]
Visual Studio Code

[Content]
The selected folder is not a function project. Create new project?

[Yes] [Cancel]
```

If I click ok it will put it all in the root of the folder that I have open.

Do I really have to explicitly open the functions folder in vscode to be able to add new functions?

**Comment by EricJizbaMSFT** [comment]
Try the setting `azureFunctions.projectSubpath` instead. We automatically detect projects based on the "host.json" file, but only search one folder deep. Looks like yours is two levels deep, so you would need that setting

**Comment by EricJizbaMSFT** [comment]
Going to close this issue as the above recommended setting should solve your issue. Let me know if it doesn't
