### ISSUE TITLE
Unable to deploy to function app VS Code

### ISSUE THREAD

**Issue by brgsstm** [microsoft/vscode-azurefunctions#2072]
Does this occur consistently? Yes
Repro steps:
Deploy to Function app...

Action: azureFunctions.deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.22.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399876extension.bundle.js:309:399876
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:669090
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @brgsstm

Thanks for reporting.  This error usually comes up if you try to deploy to the same app back-to-back.  Have you tried waiting and deploying later?  Restarting the app can help with this issue as well.

If that doesn't work, could you try creating a new function app and deploying to that one?

**Comment by brgsstm** [comment]
waited and deployed successfully - frustrating.  you can close
