### ISSUE TITLE
Issue with Azure function 3.0 on Linux (normally published through container - this attempt from VS Code)

### ISSUE THREAD

**Issue by Filipowicz251** [microsoft/vscode-azurefunctions#2075]
Somehow correlated report (publication through docker and image from Azure Container Registry) is here: https://stackoverflow.com/questions/61567697/azure-function-http-triggered-on-linux-container-function-not-working-404

I suppose the root cause could be the same

Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.22.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2842864extension.bundle.js:225:2842864
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:669125
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Filipowicz251 please add detailed repro steps

**Comment by Filipowicz251** [comment]
In Visual Studio Code i did choose option Open folder. I've opened folder with Azure Function and i opened Azure addon and in Azure functions section i did choose Publish. That's it.

**Comment by EricJizbaMSFT** [comment]
I can't reproduce with just those steps. I need more information like what language is your project, what functions did you add, does the error always happen, etc. Also if you could copy the deploy logs that would be helpful
