### ISSUE TITLE
Deploying function app manually through azure vs code plugin. hostname error.

### ISSUE THREAD

**Issue by anmk1709** [microsoft/vscode-azurefunctions#2087]
Does this occur consistently? Yes
Repro steps:

1. I tried to manually deploy my function app using the azure functions plugin in VS code.
2. Chose my subscription
3. Chose my function
4. Error pops up.
Action: azureFunctions.deploy
Error type: ERR_TLS_CERT_ALTNAME_INVALID
Error Message: Hostname/IP does not match certificate's altnames: Host: orchestrator-reporting-app-prod.scm.azure.somename.dk. is not in the cert's altnames: DNS:*.azure.somename.dk, DNS:azure.somename.dk

Version: 0.22.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>
```
Object.checkServerIdentity tls.js:279:12
TLSSocket.onConnectSecure _tls_wrap.js:1327:27
TLSSocket.emit events.js:203:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```
</details>

I thought that *.azure.somename.dk would include all, is that understanding incorrect?

**Comment by EricJizbaMSFT** [comment]
@anmk1709 I'm not that familiar with the TLS error you're referencing. Did you already go through the VS Code docs regarding network settings: https://code.visualstudio.com/docs/setup/network

**Comment by anmk1709** [comment]
We Changed the certificate to include scm.azure.dsb.dk and now the manual deployment works from vs code deployment, I am yet to see if it worked on the automatic deployment also.

Fra: Eric Jizba <notifications@github.com>
Sendt: 19. maj 2020 00:18
Til: microsoft/vscode-azurefunctions <vscode-azurefunctions@noreply.github.com>
Cc: Andreas Mads Kronstam <anmk@dsb.dk>; Mention <mention@noreply.github.com>
Emne: Re: [microsoft/vscode-azurefunctions] Deploying function app manually through azure vs code plugin. hostname error. (#2087)


@anmk1709<https://github.com/anmk1709> I'm not that familiar with the TLS error you're referencing. Did you already go through the VS Code docs regarding network settings: https://code.visualstudio.com/docs/setup/network

**Comment by EricJizbaMSFT** [comment]
Closing since it sounds like you got it working in VS Code
