### ISSUE TITLE
Add the detailed uploaded settings info and uploading state in output panel

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2088]
**OS:** Win10
**Build Version:** [20200513.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19233&view=results)

**Repro Steps:**
1. Create one project.
2. Deploy it to a function app.
3. Click "Upload settings" button (like below) and check the output log.
![image](https://user-images.githubusercontent.com/45614674/81790083-72cd0480-9537-11ea-854b-b9f4439e88d5.png)

**Expect:**
The output is clear to check the uploaded settings and uploading state.

**Actual:**
There is no uploaded settings info and uploading state in output.
![image](https://user-images.githubusercontent.com/45614674/81789857-25509780-9537-11ea-88e4-5ca237a472c1.png)

_1:06:52 AM: Uploading settings to "serene-bas-win-node12"...
1:06:53 AM: Ignored the following settings that were already the same:_
- FUNCTIONS_WORKER_RUNTIME
_1:06:53 AM: WARNING: This operation will not delete any settings in "serene-bas-win-node12". You must manually delete settings if desired._

**Suggestion:**
Add the detailed uploaded settings info and uploading state in output, it will be obvious to check the uploaded settings and uploading state if added the detail info in output log.

**Comment by EricJizbaMSFT** [comment]
I'm guessing you only have two settings in your local.settings.json. One was empty (AzureWebJobsStorage) and the other was already the same - as the logs say (FUNCTIONS_WORKER_RUNTIME).

So most of the detail is already there, but I added a completion message in https://github.com/microsoft/vscode-azurefunctions/pull/2096
