### ISSUE TITLE
There are 4 "Syncing triggers..." logs in output panel when deploying to Python 3.8 Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2089]
**OS:** Win10
**Build Version:** [20200513.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19233&view=results)

**Repro Steps:**
1. Create a Function App with Python 3.8 runtime.
2. Create a Python project with HttpTrigger function.
3. Deploy the Python project to the function app.
4. Check the output log for "Syncing triggers...".

**Expect:**
There is only one "Syncing triggers..." log in output panel.

**Actual:**
There are 4 "Syncing triggers..." logs in output panel.
2:27:35 AM serene-adv-linux-py38: Creating zip package...
2:27:35 AM serene-adv-linux-py38: Starting deployment...
2:28:01 AM serene-adv-linux-py38: Fetching changes.
2:28:01 AM serene-adv-linux-py38: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/d174da3a-daab-4184-b3a8-b437962cdd85.zip (0.00 MB) to /tmp/zipdeploy/extracted
2:28:02 AM serene-adv-linux-py38: Updating submodules.
2:28:02 AM serene-adv-linux-py38: Preparing deployment for commit id '2d590d4951'.
2:28:02 AM serene-adv-linux-py38: Generating deployment script.
2:28:03 AM serene-adv-linux-py38: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
2:28:04 AM serene-adv-linux-py38: Generating deployment script for Web Site
2:28:05 AM serene-adv-linux-py38: Generated deployment script files
2:28:05 AM serene-adv-linux-py38: Running deployment command...
2:28:05 AM serene-adv-linux-py38: Command: "/home/site/deployments/tools/deploy.sh"
2:28:05 AM serene-adv-linux-py38: Handling Basic Web Site deployment.
2:28:06 AM serene-adv-linux-py38: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
2:28:06 AM serene-adv-linux-py38: Copying file: '.funcignore'
2:28:06 AM serene-adv-linux-py38: Copying file: 'host.json'
2:28:07 AM serene-adv-linux-py38: Copying file: 'proxies.json'
2:28:07 AM serene-adv-linux-py38: Copying file: 'requirements.txt'
2:28:07 AM serene-adv-linux-py38: Copying file: 'HttpTrigger1/__init__.py'
2:28:07 AM serene-adv-linux-py38: Copying file: 'HttpTrigger1/function.json'
2:28:07 AM serene-adv-linux-py38: Copying file: 'HttpTrigger1/sample.dat'
2:28:07 AM serene-adv-linux-py38: Finished successfully.
2:28:07 AM serene-adv-linux-py38: Running post deployment command(s)...
2:28:08 AM serene-adv-linux-py38: Triggering recycle (preview mode disabled).
2:28:08 AM serene-adv-linux-py38: Deployment successful.
**2:28:25 AM serene-adv-linux-py38: Syncing triggers...
2:29:20 AM serene-adv-linux-py38: Syncing triggers (Attempt 2/6)...
2:30:21 AM serene-adv-linux-py38: Syncing triggers (Attempt 3/6)...
2:31:31 AM serene-adv-linux-py38: Syncing triggers (Attempt 4/6)...**
2:32:09 AM serene-adv-linux-py38: Querying triggers...
2:32:16 AM serene-adv-linux-py38: HTTP Trigger Urls:
  HttpTrigger1: https://serene-adv-linux-py38.azurewebsites.net/api/HttpTrigger1

**More Info:**
1. This issue does not reproduce when deploying again.
2. This issue does not reproduce when deploying to Function App (3.6 and 3.7 runtime).

**Comment by EricJizbaMSFT** [comment]
This is by-design. The call to sync triggers isn't the most reliable, so we retry if it fails - looks like it succeeded on the 4th try for you

Related to https://github.com/microsoft/vscode-azuretools/pull/372
