### ISSUE TITLE
Fail to swap slot between the new slot and production 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2092]
**OS:** Mac/Linux
**Build Version:** [20200513.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19233&view=results)

**Repro Steps:**

1. F1-->Create a  windows Function App in Azure...(Advanced)
2. Create a project-->Deploy to the function app
3. Create a slot for this Function App
4. Right click on the slot and select "Swap Slot"-->Production
5. Verify the functions listed have switched

**Expect:**
 Swap slot successfully

**Actual:**
Fail to swap slot between the new slot and production
![Screen Shot 2020-05-13 at 4 20 07 PM](https://user-images.githubusercontent.com/62053665/81807027-e5e27500-954f-11ea-91b7-2870adf45028.png)

**Comment by EricJizbaMSFT** [comment]
This doesn't repro for me. It could've been a transient issue

**Comment by v-mengwe** [comment]
Verified on the latest build 20200703.6, this issue does not reproduce, so close it.
