### ISSUE TITLE
[Suggestion] Remove "Create new Function App in Azure..." from command list when deploying Python project to slot

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2101]
**OS:** Win10
**Build Version:** [20200514.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19334&view=results)

**Repro Steps:**
1. Open a Python project in VS Code.
2. F1->Azure Functions: Deploy to Slot....
3. Check the command list.

**Actual:**
"Create new Function App in Azure..." command shows in the list.

**Suggestion:**
Remove "Create new Function App in Azure..." from command list. Linux Consumption apps do not support slots.
![image](https://user-images.githubusercontent.com/45614674/81914676-2ef40100-9604-11ea-92ed-5c50ed13465f.png)

**Comment by EricJizbaMSFT** [comment]
In this case the value isn't worth the effort to fix. It's more complicated than other suggestions to hide the "Create" pick since it's python-specific
