### ISSUE TITLE
No data shows in Azure View after installing the Functions extension in oldest VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2103]
**OS:** Win10
**Build Version:** [20200514.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19334&view=results)

**Repro Steps:**
1. Figure out the oldest vscode version that the extension supports, the version is 1.37.0.
2. Install VS Code 1.37.1 from https://code.visualstudio.com/updates.
3. Install the Azure Function extension.
4. Navigate to Azure View and check the resource.

**Expect:**
The resources show well.

**Actual:**
No data shows in Azure View, a message "There is no data provider registered that can provide view data" shows in it.
![image](https://user-images.githubusercontent.com/45614674/81923219-e2aebe00-960f-11ea-9e4d-3c41926a3326.png)

**Comment by EricJizbaMSFT** [comment]
Root cause was https://github.com/microsoft/vscode-extension-telemetry/issues/47
