### ISSUE TITLE
Azure Functions: Building Serverless apps for Azure using Visual Studio Code

### ISSUE THREAD

**Issue by askabdulhaseeb** [microsoft/vscode-azurefunctions#2106]
Action: azureFunctions.deploy
Error type: Error
Error Message: The remote runtime "dotnet" for function app "f178018" does not match your local runtime "node".

Version: 0.22.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:164:366375
extension.bundle.js:164:365927
s extension.bundle.js:164:365613
verifyVersionAndLanguage extension.bundle.js:164:366091
Object.<anonymous> extension.bundle.js:164:367096
fulfilled extension.bundle.js:164:365681
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@askabdulhaseeb Function Apps in Azure are tied to a specific runtime (Node.js, .NET, Python, etc.). If the runtime doesn't match your local project, it won't work. I suggest deploying to a different or new function app
