### ISSUE TITLE
Deployment hung in Visual Studio Codespaces & WSL

### ISSUE THREAD

**Issue by chunliu** [microsoft/vscode-azurefunctions#2108]
I created a new Azure Function project with .net core 3.1 in a VS Codespaces environment. The project could run locally and it could be deployed with command line in the terminal. 

However, when I tried to deploy it to Azure, the deployment hung at the `Creating zip package` step. The following is the log from output: 

```
1:22:06 PM: Creating new function app "funcappinst2"...
1:22:27 PM: Successfully created function app "funcappinst2": https://funcappinst2.azurewebsites.net
1:22:35 PM funcappinst2: Creating zip package...
```

The instance type of the codespace was Standard (Linux). The OS of the function app in Azure was also Linux. 
Runtime version: 3.0.13113
Azure Functions Extension version: 0.22.1

**Comment by nturinski** [comment]
Thanks for reporting @chunliu 

Is this problem recurring?  Have you tried just deploying your project to the create function app?  

If it's getting hung up at the zipping step, perhaps your project is really large?

**Comment by EricJizbaMSFT** [comment]
@nturinski we should try deploying in Codespaces ourselves before labeling this issue "needs more info" (I assume you haven't tried it). I could totally see us having problems specific to Codespaces

**Comment by chunliu** [comment]
@nturinski the problem keeps happening with Codespaces. It happened with a new project created by the extension so the project is not large. No matter if it is an existing function app or a new one created by the extension, the deployment hung. I would be surprised if you cannot reproduce it with Codespaces.

**Comment by techfg** [comment]
Encountering this issue as well (hung at Creating zip package...) and I'm not using codespaces and am running WSL 1.

Was running VSCode 1.42.1 and all was good.  Upgraded to 1.45.1 and started encountering the issue.  Uninstalled back to 1.42.1 and everything worked as expected.  Installed 1.43.0 and problem occurred.  Uninstalled back to 1.42.1 and all was good so appears problem was introduced between 1.42.1 and 1.43.0.  

Additional Info:
- Problem does not seem to occur when not using WSL.
- Occurs regardless of whether or not files are on WSL (~/myproject) or outside (/mnt/c)
- Azure Functions Extension Version 0.22.1

Steps to repro:
1) Create new Function App using all defaults
2) Deploy to Azure using all defaults

Expected Result:
Function App Deploys

Actual Result:
Hangs on "Deploying zip package..."

**Comment by anthonychu** [comment]
If anyone else is hitting this issue, I was able to get it to work (at least temporarily) by uninstalling and reinstalling the extension. Not sure if it was a fluke or would work for everyone but it fixed it for me on a couple of occasions. Sharing in case anyone is running into this before the fix is published.

**Comment by sebastianrogers** [comment]
I can get it to work if I open the folder, not the workspace in VS Codespaces (Online)

**Comment by EricJizbaMSFT** [comment]
@sebastianrogers can you clarify what you mean? Is there some important difference between "folder" and "workspace" (If so, what?) or is it all about normal VS Code vs. VS Codespaces?

**Comment by sebastianrogers** [comment]
I only use VS Codespaces and the key is when starting the Codespaces to use a URL in this format

https://online.visualstudio.com/environment/[guid]?folder=%2Fhome%2Fvsonline%2Fworkspace%2F[folder]&autostart=true

rather than

https://online.visualstudio.com/environment/[guid]?workspace=%2Fhome%2Fvsonline%2F[workspace]&autostart=true

**Comment by benc-uk** [comment]
Same
WSL2 user here, hangs at creating zip, even on an empty and brand new functions project (`func init`)

I don't think this is just Codespaces related. It happens in WSL2 and VS Code remote containers (which is effectively a local version of Codespaces)

**Comment by anthonychu** [comment]
I ran into this this week locally in a devcontainer as well. (Stuck at creating zip)

**Comment by FredChap** [comment]
Does anyone could solve this issue ?
It's actually really painful to uninstall and reinstall the Azure Function extension (which requires re-authenticating)
just to make a deployment.

**Comment by gpolyn** [comment]
Hitting same issue...
```
request to https://unanetexport.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up
```

**Comment by cdennig** [comment]
Hi...any news on that one? Unfortunately, it makes using the extension impossible in WSL2.

**Comment by elasticdotventures** [comment]
ditto, same issues - Azure functions with Microsoft VS Code, with Microsoft Windows WSL2

**Comment by cdennig** [comment]
Hi folks, do you have any news on that? This bug is so annoying and makes working in WSL2 with the extension impossible! Thanks for any updates on that topic.

**Comment by benc-uk** [comment]
I find it incredible the Azure Functions team don't test anything under WSL or even use it themselves. This is isn't the first time there's been WSL specific issues

**Comment by cdennig** [comment]
@benc-uk, it's not only AzFunctions...it's also the AppService extension. Both use the same lib for the zip-deployment.

**Comment by nturinski** [comment]
Hi @cdennig I'm trying to repro this issue on WSL2, but not having any luck.  I've tried with both a node.js and .NET 3.1 project.  

Could you let me know what distro you're using?  I was trying on Ubuntu 18.04 so I'm wondering if maybe certain distributions don't work with our npm zip package.

**Comment by cdennig** [comment]
Hi @nturinski, I'm running VS Code in WSL2 with Ubuntu 20.04 LTS version. I could narrow the problem down to "runWithZipStream" of the vscode-azureappservice module. 

`runWithZipStream` function: 

```
// Setup several tasks related to the zip stream and await them all together
const streamTasks = [];
// 1. Generic task that will reject if there's an error with the stream
streamTasks.push(new Promise((resolve, reject) => {
    zipStream.on('end', resolve);
    zipStream.on('error', reject);
}));
// 2. `callback` sets up where the zip stream is piped
streamTasks.push(callback(zipStream));
// 3. `zipStream.finalize` lets "archiver" know we're done adding files to the zip
if (zipStream.finalize) {
    streamTasks.push(zipStream.finalize());
}
yield Promise.all(streamTasks);
``` 

All of those 3 promises in `streamTasks` seem to not resolve. `zipStream` is of type `Archiver` (version 4.0.1 - there is a major as well as a new minor version available) and it is correctly initialized with all the relevant files that need to be deployed.

Hope this helps...

**Comment by cdennig** [comment]
Hi @nturinski, I can confirm that - with the merge from yesterday - the deployment from VS Code to an Azure Function app is successful. Just tried with a clean environment.

Thank you very much 🙏 Looking forward to the next release of the extension 😊

**Comment by ejizba** [comment]
Hey all - we included a [fix](https://github.com/microsoft/vscode-azuretools/pull/857) for this in v1.3.0 of the extension released last week. Thank you to @cdennig for verifying! I'll go ahead and close this issue, but let us know if you're still running into this bug after the update.
