### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by aadamsx** [microsoft/vscode-azurefunctions#2109]
Now that Deno has reached version 1.0, can we get this option added to this tool?  https://deno.land/v1  

Here is an implementation: https://github.com/anthonychu/azure-functions-deno-worker

**Comment by EricJizbaMSFT** [comment]
@aadamsx can you describe what features you want added? For someone that's not familiar with Deno

**Comment by aadamsx** [comment]
Hi @EricJizbaMSFT 

Like this tool does for Nodejs, I'd like to make it easy to create, run, and deploy Deno Azure Functions apps.  

There is already a CLI tool that does this today: https://github.com/anthonychu/azure-functions-deno-worker, but I'd like this built in to VSCode.  I have a workflow for both my Nodejs and C# Web APIs today using this tool, basically I'd like to use the same workflow to build out my APIs using Deno using your tool.
