### ISSUE TITLE
azure-function-estatement

### ISSUE THREAD

**Issue by hequanfeng** [microsoft/vscode-azurefunctions#2117]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
InitLocalProjectTreeItem.<anonymous> extension.bundle.js:1:666886
fulfilled extension.bundle.js:1:660687
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hequanfeng please add repro steps
