### ISSUE TITLE
Fail to load the App Service Plan when creating a Function App (Advance)

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2119]
**OS:** Win10
**Build Version:** [20200519.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19691&view=results)
**VS Code-Insider:** 1.46.0
![image](https://user-images.githubusercontent.com/45614674/82429635-d5d21480-9abe-11ea-9d75-10cb10f3de80.png)

**Repro Steps:**
F1->Azure Functions: Create Function App in Azure...(Advance)->Provide a name for this Function App->Select a runtime->Select an OS->Select Premium or App Service Plan

**Expect:**
Load the Linux/Windows App Service Plan successfully.

**Actual:**
Keep loading the App Service Plan more than 3 mins, an error occurs "Resource provider 'Microsoft.Web' failed to return collection response for type 'serverFarms'." after several mins.
![image](https://user-images.githubusercontent.com/45614674/82423875-fdbd7a00-9ab6-11ea-9477-524381d9ae4b.png)

**More Info:**
This issue only reproduces in VS Code Insider, does not reproduce in VS Code.

**Comment by EricJizbaMSFT** [comment]
@v-ruizh does this reproduce consistently? I'm skeptical I can reproduce this or fix this. It's probably just an intermittent error in Azure

**Comment by v-ruizh** [comment]
@EricJizbaMSFT This issue only reproduces on 1 subscription. There is something wrong with this subscription. We will use other subscription to test.
