### ISSUE TITLE
Warn when using x86 version of Python

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#2122]
From ADO:

> Currently, when a user tries to deploy an azure app using VSCode + Python x32 bit, it throws an error.  In this tutorial that is still live and searchable, https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01 the images used show x32 versions of python being installed.  In the more recent quickstart, it is explicitly stated that x64 is necessary.
> 
> The VSCode solution to this should be that VSCode should alert the user in some way that explicitly tells them that the issues with their deployment is that they're trying to use a 32bit version of python instead of a 64bit version.  
> A few ideas:
> - Alert the user predeployment (maybe when creating the function or don't even show x32 versions of python when choosing) with a popup saying the version of python is incompatible
> - On deployment, alert the user saying the version of python is incompatible and a blurb about why and what they should do
> 

It makes sense to gracefully error out for this.

**Comment by EricJizbaMSFT** [comment]
Exclude x86 versions when creating a project and validate when debugging.

Shouldn't affect deploy if they're doing remote build (the default). Might need to check out local build scenario
