### ISSUE TITLE
Error when npm i -g azure-functions-core-tools@3 --unsafe-perm true

### ISSUE THREAD

**Issue by khlynet** [microsoft/vscode-azurefunctions#2124]
Does this occur consistently? 
Repro steps:

1. npm i -g azure-functions-core-tools@3 
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.22.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133816
fulfilled extension.bundle.js:1:132699
processTicksAndRejections task_queues.js:85:5
```

</details>
npm ERR! EEXIST: file already exists,

**Comment by EricJizbaMSFT** [comment]
@khlynet check the output window - that should help you fix the error. If not, copy the full logs here
