### ISSUE TITLE
Deployment hangs in "Creating zip package" phase

### ISSUE THREAD

**Issue by cagrimunyas** [microsoft/vscode-azurefunctions#2126]
I have tried to deploy my Python function (Python 3.6.9) on VS Code running on WSL. However, after many tries it just keep hanging in "Creating zip package" step. It's a simple function, it shouldn't take long to deploy, longest I wait was 30+ min yet it didn't pass "Creating Zip Package"

**Comment by cagrimunyas** [comment]
Update:
- Close the WSL connection and tried deploying again. Successfully deployed in ~1 min. and have a function running. Issue seems to occur because of Azure function on VS Code on WSL

**Comment by chunliu** [comment]
Could be the similar issue of #2108.

**Comment by EricJizbaMSFT** [comment]
Let's track this with https://github.com/microsoft/vscode-azurefunctions/issues/2108
