### ISSUE TITLE
 Action: azureFunctions.deploy Error

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode-azurefunctions#2127]
The issue text was copied to the clipboard.  Please paste it into this window.

  Does this occur consistently?  Repro steps:   1. 2.  Action: azureFunctions.deploy Error type: AuthorizationFailed Error Message: The client 'live.com#xgqfrms@outlook.com' with object id '006022c1-a7fb-43fd-b5a8-e1f3e57b9ef2' does not have authorization to perform action 'Microsoft.Web/sites/read' over scope '/subscriptions/8254cfcc-22cc-4e2f-867f-1235ba2ea380' or the scope is invalid. If access was recently granted, please refresh your credentials.  Version: 0.22.1 OS: darwin OS Release: 18.7.0 Product: Visual Studio Code Product Version: 1.45.0 Language: en  <details> <summary>Call Stack</summary>  ``` extension.bundle.js:225:1760299 retryCallback extension.bundle.js:225:114550 retryCallback extension.bundle.js:157:31063 extension.bundle.js:157:32676 handleRedirect extension.bundle.js:171:7752 extension.bundle.js:157:29848 Request._callback extension.bundle.js:1:670871 Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483 Request.emit events.js:203:13 Request.EventEmitter.emit domain.js:476:20 Request.<anonymous> extension.bundle.js:201:17592 Request.emit events.js:208:15 Request.EventEmitter.emit domain.js:476:20 IncomingMessage.<anonymous> extension.bundle.js:201:16382 Object.onceWrapper events.js:291:20 IncomingMessage.emit events.js:208:15 IncomingMessage.EventEmitter.emit domain.js:476:20 endReadableNT _stream_readable.js:1168:12 processTicksAndRejections task_queues.js:77:11 ```  </details>

**Comment by EricJizbaMSFT** [comment]
@xgqfrms You probably don't have permissions to something in your subscription. Any idea what? As a workaround, you can try the "Advanced" option when creating a function app

Could be related to https://github.com/microsoft/vscode-azureappservice/issues/1490
