### ISSUE TITLE
Error when attempting to create a function

### ISSUE THREAD

**Issue by kpm-at-hfi** [microsoft/vscode-azurefunctions#2128]
Does this occur consistently? Unsure... happened one out of one times...
Repro steps:
1. Walked throught the steps of creating a node12 linux function
Action: azureFunctions.createFunctionApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.1
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902
extension.js:229:54224
extension.js:229:52217
extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

If you try it again with a fresh instance of VS Code, it should work just fine :)

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
