### ISSUE TITLE
Error Message: getaddrinfo ENOTFOUND when deploying Azure function app

### ISSUE THREAD

**Issue by jasonachonu** [microsoft/vscode-azurefunctions#2129]
Does this occur consistently? 
Repro steps:

1. Trying to Deploy an Azure Function app from VScode
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND kpfunctionapp.scm.asedev.xxx.org

Version: 0.22.1
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2131
