### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by hequanfeng** [microsoft/vscode-azurefunctions#2130]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "mvn" command. Check output window for more details.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:544376
fulfilled extension.bundle.js:1:542702
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @hequanfeng

Are you trying to create a Java Functions project?  Could you check the output window for the details as to why the maven command failed?
