### ISSUE TITLE
Cant deploy python scripts for Azure function app via viscose 

### ISSUE THREAD

**Issue by jasonachonu** [microsoft/vscode-azurefunctions#2131]
Does this occur consistently? 
Repro steps:

1. Tried deploy python script by pressing the arrow button
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND functionapppython.scm.asedev.xx.org

Version: 0.22.1
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jasonachonu please add detailed repro steps
