### ISSUE TITLE
Not able to create the Azure Function using Visual Studio Code

### ISSUE THREAD

**Issue by amolmore3171** [microsoft/vscode-azurefunctions#2133]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: The version in your launch.json must be "0.2.0" to work with Azure Functions.

Version: 0.22.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PythonInitVSCodeStep.<anonymous> extension.bundle.js:1:886764
extension.bundle.js:1:884213extension.bundle.js:1:884213
s extension.bundle.js:1:883899
PythonInitVSCodeStep.writeLaunchJson extension.bundle.js:1:886659
PythonInitVSCodeStep.<anonymous> extension.bundle.js:1:884928
fulfilled extension.bundle.js:1:883967
```

</details>

**Comment by amolmore3171** [comment]
Submitted

**Comment by EricJizbaMSFT** [comment]
@amolmore3171 please add repro steps. Also double check your `.vscode/launch.json`. We only support for 0.2.0
