### ISSUE TITLE
Outputted HTTP Trigger URL Incorrect When Specifying RoutePrefix

### ISSUE THREAD

**Issue by ChrisTruncer** [microsoft/vscode-azurefunctions#2135]
Hi there,

I'm not sure if this is a bug in the Azure Functions Plugin, or within VS Code itself, but figured I would start here. I am using VSCode to deploy a function with the Azure Functions plugin. The deployment works without any issues, however the HTTP Trigger URL is incorrect when specifying a route prefix.

Regardless of the route prefix specified in the host.json file, the output when the Azure Functions plugin runs always shows "api" as the route prefix.

<img width="937" alt="routeprefix" src="https://user-images.githubusercontent.com/1674822/83188528-10eecc00-a0ed-11ea-8167-13ee8319c9de.png">

However, within the Azure Portal, the correct HTTPTrigger URL is shown.

<img width="906" alt="httptrigger url in azure portal" src="https://user-images.githubusercontent.com/1674822/83188563-22d06f00-a0ed-11ea-9a09-74a6b29c8fbb.png">

**Comment by EricJizbaMSFT** [comment]
I assume you've got a Python project running on a Linux Consumption plan? I tried JavaScript on Windows Consumption first with no problems, but I could repro in the Python case

**Comment by ChrisTruncer** [comment]
Correct, this was with a Python project
