### ISSUE TITLE
data tree not found

### ISSUE THREAD

**Issue by regap4693** [microsoft/vscode-azurefunctions#2136]
Does this occur consistently? 
Repro steps:

1.
2.

Action: api.revealTreeItem
Error type: Error
Error Message: TreeError [azFuncTree] Data tree node not found: [object Object]

Version: 0.22.1
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
U.getDataNode workbench.desktop.main.js:1107:184
U.expand workbench.desktop.main.js:1105:305
processTicksAndRejections task_queues.js:85:5
async expand workbench.desktop.main.js:6245:814
async e.reveal workbench.desktop.main.js:4016:589
```

</details>

**Comment by EricJizbaMSFT** [comment]
Yeah I've seen this. @regap4693 I assume it works if you just try again?
