### ISSUE TITLE
Support creating Python on Linux Consumption

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#214]

**Comment by fiveisprime** [comment]
Python will be deployed to Linux so we'll need to include the time to research the Linux deployment API (assuming there's a difference).

**Comment by PandaKillsLot** [comment]
So, currently. python is not supported, right?

**Comment by EricJizbaMSFT** [comment]
That is correct

**Comment by asavaritayal** [comment]
## Prerequisites
- Python 3.6 or above
- Azure Functions core tools

## Create Workflow

#### Create new project

1. File explorer : Pick a folder for your Python App.
2. Select a language for your function project.
3. Determine if Python 3.6 or up is installed. 
    _If yes_, print Python version number and proceed.    
    _Else_, prompt the user to install Python 3.6.4 or above to continue.
4. 2. Determine if a virtual environment is currently active. 
    _If yes_, continue. 
    _Else_, prompt the user to create a virtual environment and activate it.
5. Install the python worker and azure functions package.
    ```bash    
    pip install git+git: https://github.com/Azure/azure-functions-python-worker/tree/dev/azure
    ```

#### Create function

1. Select a function template
2. Provide a function name

## Resources
- [Templates feed](https://functionscdn.azureedge.net/public/TemplatesApi/2.0.0-beta-10180.zip) (feature flag - python3)
- [func CLI spec](https://github.com/Azure/azure-functions-core-tools/issues/380)
- [Setting up the development environment](https://github.com/Azure/azure-functions-python-worker/wiki/Setting-up-development-environment)

**Comment by asavaritayal** [comment]
FYI, here are the updated instructions / workflow for the CLI - https://github.com/Azure/azure-functions-python-worker/wiki/Create-Function-(CLI) . We want the VS Code extension to closely mimic this workflow.

**Comment by fiveisprime** [comment]
Updated to be a little more generic. This is the creation scenario for creating an app on Linux consumption, which will only become available if the user has the feature flag enabled and chooses to create a Python app.

**Comment by EricJizbaMSFT** [comment]
@asavaritayal a few comments about your updated scenario above:

We try to avoid using the core tools in VS Code for everything except debugging. This is primarily because the func cli is just not designed to be used by tooling (see https://github.com/Azure/azure-functions-core-tools/issues/273 and https://github.com/Azure/azure-functions-core-tools/issues/272). As far as I can tell - it's almost entirely designed to be used interactively.

In addition, I think there's value in creating a project and deploying it from VS Code without needing to install the core tools. One of VS Code's primary strengths is that it's so lightweight and we want to keep that trend going with our extension.

I'm also concerned about the fact that the core tools implementation of `pack` and `publish` is essentially a black box. I would prefer to implement most of that logic in the user's `.vscode\tasks.json` file so that the user can see exactly what's going on and customize it if necessary.

**Comment by asavaritayal** [comment]
@EricJizbaMSFT I'm okay with not using the core tools for `func new` but we're constantly iterating on `func init` and `func publish` for python. Not all of the functionality is located in the standalone `pack` module since we also offer options like `--build-native-deps` that are implemented in the core tools logic itself. Given that we've already tweaked the pack and publish gestures numerous times and are going to extend it in the future to encompass support for the Anaconda environment, I don't think it makes sense to fork this logic for VS Code. 

The VS Code experience is valuable for our customers because of the F5 debugging capabilities provided by the Azure Functions and Python extensions. As I understand, this is anyway not possible today without having to install the core tools. Asking the users to install the tools midway the development workflow is a further distraction in my opinion.

**Comment by EricJizbaMSFT** [comment]
Any plans on fixing those bugs I mentioned? Again - those are the primary thing blocking us from leveraging the func core tools more.

**Comment by asavaritayal** [comment]
One of them is now fixed. I'll discuss the other one @ahmelsayed tomorrow.

**Comment by EricJizbaMSFT** [comment]
Awesome - definitely helpful thanks.

I'm still struggling to understand all the implications of using `func publish` though. Is it like ["dotnet publish"](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21) which "Packs the application and its dependencies into a folder for deployment to a hosting system."? Or does it actually deploy?

Secondly - how would local git deploy or GitHub deploy work for Python? Would all of the extra python stuff be run as a part of SCM_DO_BUILD_DURING_DEPLOYMENT?

**Comment by asavaritayal** [comment]
> I'm still struggling to understand all the implications of using func publish though. Is it like "dotnet publish" which "Packs the application and its dependencies into a folder for deployment to a hosting system."? Or does it actually deploy?

`func azure functionapp publish` for Python primary does two things - 
1. Creates a virtual environment and installs the required Linux based dependencies to this environment
2. Packages up the function app and virtual environment to deploy to Seabreeze (Functions on Linux)

> Secondly - how would local git deploy or GitHub deploy work for Python? Would all of the extra python stuff be run as a part of SCM_DO_BUILD_DURING_DEPLOYMENT?

Currently, we don't have support for local git deploy (kudu) for Functions on Linux but we are going to provide a sample Travis script in our docs as an example for users to setup their own CI/CD for GitHub deploy.

**Comment by EricJizbaMSFT** [comment]
> Packages up the function app and virtual environment to deploy to Seabreeze (Functions on Linux)

I'm still confused. Does it just package it up - or does it also deploy? I'm hoping we can have some way that _just_ packages it without deploying. Users are already logged in to Azure through VS Code and we don't want to force them to log in to the func cli as well. This is how we do it for C# functions (We run a `dotnet publish` which packages everything up _as if_ you were deploying, but then we handle the actual deployment ourselves).

**Comment by ahmelsayed** [comment]
`func azure functionapp publish` will package it and publishes it. 

[`func pack`](https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/LocalActions/PackAction.cs) will create a package for you that you can then publish some other way. 

The command doesn't show up in help now because I wasn't too sure about its final shape. But the options it takes are:


```
pack    Pack function app into a zip that's ready to run.
    --output [-o]  output directory for the packed archive
    --build-native-deps will spin up a docker container to run any build commands in the container. 
```

**Comment by EricJizbaMSFT** [comment]
@ahmelsayed when you're using "publish" above to describe what something does, I assume you mean publish **_to Azure_**? Just trying to be extra careful because `dotnet publish` always publishes to a folder on the local file system and has nothing to do with Azure or any cloud

Assuming that's what you mean, it sounds like `func pack` is what we want. Is that finalized yet? Is it safe for us to rely on that?

It sounds like we would only rely on the func cli for `func init` and `func pack`. In which case I don't think we are actually blocked by https://github.com/Azure/azure-functions-core-tools/issues/273

**Comment by ahmelsayed** [comment]
yes, your understanding is correct. 

My only reservation about `func pack` as a command is possible confusion with https://github.com/Azure/azure-functions-pack I'm open to input about it

**Comment by EricJizbaMSFT** [comment]
It seems like the python stuff and the nodejs stuff are doing similar things (creating a ready-to-run function app) so it makes sense that the naming is similar. I guess the only confusing part is why python is directly in the func cli and nodejs is in it's own cli. Is there some reason why funcpack is it's own separate cli? Why wasn't that added as a pack command to the func cli in the first place?
