### ISSUE TITLE
Failed installation: You must have the Azure Functions Core Tools installed to debug your local functions.

### ISSUE THREAD

**Issue by bcbeatty** [microsoft/vscode-azurefunctions#2140]
Does this occur consistently?  Yes  
Repro steps:
 

1. Trying to Start Debugging a Workspace with 2 Azure Functions written in c#
2.I get prompted "You must have the Azure Functions Core Tools installed to debug your local functions." (Its already installed). I tried as a user and administrator

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token / in JSON at position 148.

Version: 0.22.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:326786extension.bundle.js:1:326786
fulfilled extension.bundle.js:1:326079
```

</details>

**Comment by EricJizbaMSFT** [comment]
We have one known issue where we're not correctly detecting the func cli: https://github.com/microsoft/vscode-azurefunctions/issues/2019. As a workaround, you can set "azureFunctions.validateFuncCoreTools" to `false` in your VS Code settings to bypass that check. Let me know if that helps
