### ISSUE TITLE
cannot deploy azure function app in VS Code

### ISSUE THREAD

**Issue by thiendd01898** [microsoft/vscode-azurefunctions#2141]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: Deployment '9d95c13f0c87469a8a7a724f8eeaec4c' not found.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:37037extension.bundle.js:309:37037
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@thiendd01898 yeah I see this kind of error occasionally, but it usually goes away if I try to deploy again. Unfortunately, we've been unable to get consistent repro steps. Let me know if you can
