### ISSUE TITLE
Install Azure function core tools using "npm" command on Mac which has no Homebrew installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2142]
**OS:** Mac
**Build Version:** 20200603.1

**Repro Steps:**
1. Make sure there is no Homebrew installed on Mac.
2. F1 -> Type and select "Azure Functions: Install or Update Azure Functions Core Tools"->Select "Azure Functions v3".
3. Check the Azure Functions output.

**Expect:**
It runs "brew" command to install Azure function core tools. Pop up a warning, such as "Please install Homebrew first...".

**Actual:**
It runs "npm install -g azure-functions-core-tools@3" command on Mac.
![image](https://user-images.githubusercontent.com/45614674/83729952-fbdce480-a67a-11ea-81ae-40f71e601baa.png)

**More info:**
This issue does not reproduce if Homebrew is installed on Mac.

**Comment by EricJizbaMSFT** [comment]
@v-ruizh take a look at the logs. It's using npm instead of brew and the error seems to be related to permissions. I'm guessing that's unique to your machine instead of a more general problem for our users

**Comment by v-ruizh** [comment]
@EricJizbaMSFT this issue reproduces on 3 Macs (2 Mac Mini and 1 MacBook air), it will use npm instead of brew to install Azure function core tools if there is no Homebrew installed on Mac. This issue does not reproduce and it uses brew to install Azure function core tools if Homebrew is installed on Mac. 
Could we remind the users to install Homebrew first if they install Azure function core tools using command in VS Code?

**Comment by EricJizbaMSFT** [comment]
Mac users don't need "brew" - it should work with npm

Here's a doc I found about how to fix EACCES errors with npm: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by v-ruizh** [comment]
@EricJizbaMSFT Thanks for your sharing. 
F1 -> "Azure Functions: Install or Update Azure Functions Core Tools" -> Select v3, now no error occurs when running command with npm, But this installation seems not take effect.
![Screen Shot 2020-06-17 at 1 49 22 PM](https://user-images.githubusercontent.com/45614674/84861970-d8fff680-b0a4-11ea-9a17-6ffe76f5bb57.png)
It shows "command not found" when using "func -v" to check the version.
![Screen Shot 2020-06-17 at 2 01 43 PM](https://user-images.githubusercontent.com/45614674/84862127-3005cb80-b0a5-11ea-9aae-7c8624768d62.png)

After above steps, I create a JavaScript project and debug it. It will prompt to install Azure Function Core tools again, install it again. The installation logs shows as the same as above and debug failed with an error. 
![Screen Shot 2020-06-17 at 2 01 25 PM](https://user-images.githubusercontent.com/45614674/84863017-c8e91680-b0a6-11ea-8ae7-c8d8fb377d5c.png)
![Screen Shot 2020-06-17 at 2 00 42 PM](https://user-images.githubusercontent.com/45614674/84862683-2f216980-b0a6-11ea-9c73-ce0590a453ee.png)

**Comment by EricJizbaMSFT** [comment]
I would suggest you look at docs like this:

https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found
