### ISSUE TITLE
Unable to deploy azure function

### ISSUE THREAD

**Issue by gigsvinoth** [microsoft/vscode-azurefunctions#2145]
Does this occur consistently? Yes
Repro steps:

1. Unable to deploy in both VS Code or Visual Studio 2019 Enterprise version
2. I have Latest .NET Core SDK 3.1 but still im facing issue to deploy sample hello function app

Action: azureFunctions.deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>
12:12:32 AM indaosubscriberfnapp: Creating zip package...
12:12:33 AM indaosubscriberfnapp: Starting deployment...
12:14:43 AM: Error: An error has occurred.
```
extension.bundle.js:309:399345extension.bundle.js:309:399345
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
@gigsvinoth Sometimes Azure just has temporary outages/hiccups, so you can try deploying again and it might just work. 😄  

Otherwise please check the VS Code output window for any logs/errors that you could show us.

**Comment by gigsvinoth** [comment]
Hi Team,
I tried to deploy azure function through visual studio 2019 version 16.6.1. i getting below error
1>THSubscriber -> C:\Users\v.a.vijayakumar\source\repos\THSubscriber\THSubscriber\bin\Release\netcoreapp3.1\bin\THSubscriber.dll
1>Done building project "THSubscriber.csproj".
2>------ Publish started: Project: THSubscriber, Configuration: Release Any CPU ------
2>THSubscriber -> C:\Users\v.a.vijayakumar\source\repos\THSubscriber\THSubscriber\bin\Release\netcoreapp3.1\bin\THSubscriber.dll
2>THSubscriber -> C:\Users\v.a.vijayakumar\source\repos\THSubscriber\THSubscriber\obj\Release\netcoreapp3.1\PubTmp\Out\
2>Publishing C:\Users\v.a.vijayakumar\source\repos\THSubscriber\THSubscriber\obj\Release\netcoreapp3.1\PubTmp\THSubscriber - 20200605111755471.zip to https://thsubscriberpoc.scm.azurewebsites.net/api/zipdeploy...
2>The attempt to publish the ZIP file through https://thsubscriberpoc.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code InternalServerError.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

Thanks

**Comment by nturinski** [comment]
@gigsvinoth Based off your errors, it seems like this is an Azure error.  VS Code and Visual Studio can't control server errors unfortunately.

Usually these problems are transient though.  If you're still experiencing issues, I recommend creating a new Function App and trying to deploy to that instead.
