### ISSUE TITLE
The remote version "~3" for function app "try-azure-functions" does not match your local version "~2".

### ISSUE THREAD

**Issue by Albert-Gao** [microsoft/vscode-azurefunctions#2146]
After clicking the `Deploy to Function App` Button, I get this error.

![image](https://user-images.githubusercontent.com/18282328/83827966-a0226200-a733-11ea-8660-58c7a74d7a71.png)

But the local settings in the settings.json is `~3`
![image](https://user-images.githubusercontent.com/18282328/83828049-db249580-a733-11ea-802b-e90192c179b7.png)

What am I missing here? Thanks

**Comment by Albert-Gao** [comment]
Found it, it generates a local settings.json inside the project folder:

![image](https://user-images.githubusercontent.com/18282328/83833679-981cef00-a740-11ea-9ff8-75dced7d00b2.png)

Once I changed it, the error is gone. Maybe we could say something in the error log? Like the path to settings.json.

**Comment by EricJizbaMSFT** [comment]
@Albert-Gao the "Learn More" button in your first screenshot takes users to this doc: https://aka.ms/azFuncRuntime, which does mention the path to "settings.json". Is that sufficient?

**Comment by Albert-Gao** [comment]
No, it is not sufficient and exactly how I got confused.

Because I opened the VSC settings menu, then the JSON format an did a search, then I saw a ”~3” 😂

Did not know it creates a new settings.json for me 🙂

**Comment by EricJizbaMSFT** [comment]
Do you have a suggestion for how to change the doc? https://github.com/Microsoft/vscode-azurefunctions/wiki/Project-Runtime

I would prefer to do that instead of changing the error message, which can look cluttered very quickly.

**Comment by Albert-Gao** [comment]
Hi, Eric

Thanks for the reply

I think the error message is totally and leads me to the correct document,
I think somehow the document needs to point it out that at least for a 1st timer user, it is the `project-path/.vscode/settings.json` that the user should look into rather than the one from the global VS settings.json
