### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by maybeLiang** [microsoft/vscode-azurefunctions#2147]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND pjlincoln.scm.azurewebsites.net

Version: 0.22.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by nturinski** [comment]
@maybeLiang Thanks for reporting.  Please provide repro steps.
