### ISSUE TITLE
Can direct the user to the prerequiste page when mvn is not in sys path

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#215]
I'm thinking if we can direct to the Java Function prerequisite page if the extension detects `mvn` is not in sys path.

@EricJizbaMSFT Could we change the `validateMavenInstalled()` from return `void` to return `boolean`, and open the webpage in the `catch` block?

**Comment by EricJizbaMSFT** [comment]
That sounds fine to me - just keep in mind that if you swallow the error, then we won't be able to track it in telemetry.

Currently any error you throw _will_ be displayed to the user. However, @nturinski said he might make it possible to throw an error without displaying it to the user. This would allow you to have the custom error handling that you mentioned and still track the error in our telemetry.

**Comment by jdneo** [comment]
@EricJizbaMSFT I'm thinking that could we export the TelemetryReporter into a standalone *.ts file, just like we do for the `localize.ts`. Then we can call `callWithTelemetryAndErrorHandling` without passing the report instance through several methods.

**Comment by jdneo** [comment]
Addressed in #530
