### ISSUE TITLE
cannot import name 'run' (aio_compat.py)

### ISSUE THREAD

**Issue by pauldj54** [microsoft/vscode-azurefunctions#2151]
I created a simple python function and deployed to a repo. A working colleague migrated to another repo. I cloned the code and tried to debug it again.

When I press F5 I got the following Error:

![image](https://user-images.githubusercontent.com/706754/84229327-9446ef00-aae9-11ea-821b-3b63cdcc980e.png)

I tried to recreate the function and spend several hours but I was not able to find a solution.

I started visual studio code from the conda shell activating the desired environment. I verified the environment is set in vs code.

Any feedback would be appreciated.

**Comment by EricJizbaMSFT** [comment]
@pauldj54 are you sure that's a blocking exception? From looking at your screenshot, it looks like it's inside of a "try" block - implying that might be okay if it fails. In any case, I think that error is specific to the code you've got there
