### ISSUE TITLE
Unable to install azure-functions-core-tools in VSCode

### ISSUE THREAD

**Issue by rakeshmotghare** [microsoft/vscode-azurefunctions#2152]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:101651extension.bundle.js:334:101651
fulfilled extension.bundle.js:334:99073
```

</details>

**Comment by nturinski** [comment]
@rakeshmotghare Please add repro steps.
