### ISSUE TITLE
Azure Blob Trigger with Python

### ISSUE THREAD

**Issue by JakePaul787** [microsoft/vscode-azurefunctions#2154]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54276extension.js:229:54276
extension.js:229:53143extension.js:229:53143
H._callback extension.js:1:186814
H.t._callback.t.callback.t.callback extension.js:181:5470
H.emit events.js:203:13
H.<anonymous> extension.js:181:18298
H.emit events.js:203:13
IncomingMessage.<anonymous> extension.js:181:17140
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
