### ISSUE TITLE
De-dupe subscriptions

### ISSUE THREAD

**Issue by joeskeen** [microsoft/vscode-azurefunctions#2155]
I saw an old bug closed for this, but it is locked so I can't re-open it.

When I start VSCode and the Azure functions pane loads, it flashes with content then becomes empty.  A toast message pops up in the lower-right corner saying that "Element with id /subscriptions/... is already registered".  Clicking the refresh button at the top of the pane does not cause a flash of data, but pops the same toast again.  I can never get anything to render there, so the extension is currently unusable for me :'( 

I am running the latest Insiders build of VSCode on the latest Windows 10 version:
![image](https://user-images.githubusercontent.com/12286274/84446416-acf6f800-ac02-11ea-86db-ce6a5555b2f5.png)

I should say as well that I have A LOT of Azure subscriptions...
![image](https://user-images.githubusercontent.com/12286274/84446598-1119bc00-ac03-11ea-8c27-629aef3fa533.png)

**Comment by joeskeen** [comment]
Possibly related: https://github.com/microsoft/vscode-azurefunctions/issues/983

**Comment by joeskeen** [comment]
Also possibly related: https://github.com/microsoft/vscode/issues/71698

**Comment by EricJizbaMSFT** [comment]
@joeskeen do you see two subscriptions with the same name in that list? If so, that could be causing the issue. I didn't think that was possible, but if it is we would need to de-dupe the list.

As a workaround, it might help if you run "Select subscriptions" from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) so that fewer subscriptions are shown in the tree.

**Comment by joeskeen** [comment]
I looked at the subscription list, and don't see any named the same.  I didn't check the subscription GUIDs for dupes (too much mental load since it's not sorted by that value).  I did run the "Select subscriptions" command and selected 3 of the 53 in the list and it works now.  Great workaround.

**Comment by joeskeen** [comment]
I spoke too soon - on second inspection of the list, I do see two subscriptions with the same name, and same subscription ID.  Not sure how that happened...
