### ISSUE TITLE
cannot udpate settings in vscode

### ISSUE THREAD

**Issue by helloanh** [microsoft/vscode-azurefunctions#2157]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.appSettings.download
Error type: Error
Error Message: Failed to run "func" command. Check output window for more details.

Version: 0.22.1
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133816
fulfilled extension.bundle.js:1:132699
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @helloanh 

Thanks for reporting.  Could you provide repro steps please?  Just by running the Download Remote Settings... command, I'm not able to reproduce this bug.
