### ISSUE TITLE
 Entry not found in cache.

### ISSUE THREAD

**Issue by shailendramonu** [microsoft/vscode-azurefunctions#2159]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.appSettings.upload
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902
extension.js:229:54224
extension.js:229:52217
extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
