### ISSUE TITLE
Support viewing logs/file on linux consumption

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2162]
**OS:** Windows
**Build Version:** 20200614.1

**Repro Steps:**
1. Create a new Function App with Consumption hosting plan.
2. Unfold the "Logs" node and check the result.

**Expect:**
There is no error and show the files under the "Logs" node.

**Actual:**
Display an error "This plan does not support viewing files.".
![image](https://user-images.githubusercontent.com/57662131/84758037-81f01800-aff7-11ea-9e1e-eeb9dda741b4.png)

**Comment by EricJizbaMSFT** [comment]
Currently blocked by the platform
