### ISSUE TITLE
"Your function app XXX does not support remote build as it was created before August 1st, 2019." Created today

### ISSUE THREAD

**Issue by SeaDude** [microsoft/vscode-azurefunctions#2165]
Hello,
I have a bash script that uses `az cli` to create an Azure Function App and support resources (Storage account, Key vault, etc.). When I try to deploy my code to the Function App using terminal from within VS Code with command `func azure functionapp publish XXX --publish-local-settings`, I receive the error:

```
(.venv) user@system:~/Documents/funcTest$ func azure functionapp publish XXX --publish-local-settings
Getting site publishing info...
Remote build is a new feature added to function apps.
Your function app XXX does not support remote build as it was created before August 1st, 2019.
Please use '--build local' or '--build-native-deps'.
For more information, please visit https://aka.ms/remotebuild
```

**How can the message say my app was created almost a year ago when I created it 20 mins ago?**

Please advise on how to get past this error.

Thank you

**Comment by EricJizbaMSFT** [comment]
What version of the func cli do you have? Does it work if you deploy from VS Code (the blue up arrow in the Azure Functions view, not the terminal)? If the problem only reproduces in the terminal, this might be a better place to file an issue: https://github.com/Azure/azure-functions-core-tools

**Comment by SeaDude** [comment]
Fixed it. I had defined some unnecesary flags for the Azure Storage Account that supports the Function App. 

**Specifically**:
```
--access-tier Cool
    --default-action Deny
    --kind StorageV2
```

Once I removed these from the `az cli` command to build the associated storage account, the Function App deployment worked. (Thank you @MarceloSilva!)

Ref: https://stackoverflow.com/questions/62422774/azure-function-error-your-function-app-does-not-support-remote-build/62439531#62439531

**Comment by SeaDude** [comment]
The problem ended up being the Azure Storage account I was using. I had some flags set that were causing this (very weird) error message. The two flags in question were something like `--default-access deny` and `--tier Cool`. I removed both of them and let the defaults take over. Redeployed. All good.
