### ISSUE TITLE
vscode azure function

### ISSUE THREAD

**Issue by sidhukumar** [microsoft/vscode-azurefunctions#2168]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133816
fulfilled extension.bundle.js:1:132699
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting, @sidhukumar 
Please provide repro steps. And the output from the output channel would be helpful as well.
