### ISSUE TITLE
Can't create new Python project following the tutorial

### ISSUE THREAD

**Issue by synergiator** [microsoft/vscode-azurefunctions#2169]
Does this occur consistently? 
YES
Repro steps:

1. Follow tutorial instructions until need to select Python interpreter
2a . Select Python interpreter from displayed list 
2b. Type manually "Python3"

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3" command. Check output window for more details.

Version: 0.22.1
OS: linux
OS Release: 4.15.0-106-generic
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133816
fulfilled extension.bundle.js:1:132699
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@synergiator check the output window. If that doesn't help, copy the logs here
