### ISSUE TITLE
Problem executing functions locally

### ISSUE THREAD

**Issue by uaag** [microsoft/vscode-azurefunctions#2170]
Hi! This is my problem, after installing the azure cli, log into it, and runnig this command "func azure functionapp fetch-app-settings 'function-app'" one of my functions stopped working. I did all of that because I created a EventHub triggered function and it wasn't working, after doing that, that specific function worked, except one. I think is related to a Cosmos DB binding, I attach an ss of the error.

![erro1](https://user-images.githubusercontent.com/17261065/85080426-c104a180-b18e-11ea-83f8-df7c9827d97c.PNG)

I hope you can help me!

TIA!

**Comment by EricJizbaMSFT** [comment]
Check your "local.settings.json" and "function.json" files. I think "HostName" (as shown in the error) is related to Event Hubs, not Cosmos DB. Maybe one of the connection strings in your local.settings.json is messed up

**Comment by uaag** [comment]
Yeah, but error only happens when that functions that appear in the log, that is a HttpTrigger functions is executed, not the EventHub one. When the event hub function is executed, it works as expected.

**Comment by EricJizbaMSFT** [comment]
Yeah I'm not sure what to say here - perhaps if your project is on GitHub you could share a link to that? I'm pretty sure the error is coming from the project
