### ISSUE TITLE
deploy python function failed

### ISSUE THREAD

**Issue by joshdotexe** [microsoft/vscode-azurefunctions#2171]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND fazbear-py.scm.azurewebsites.net

Version: 0.22.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@joshdotexe please add detailed repro steps
