### ISSUE TITLE
Entry not found in cache error

### ISSUE THREAD

**Issue by swildermann** [microsoft/vscode-azurefunctions#2172]
Does this occur consistently? yes
Repro steps:

Deploy to Function App -> Create new function -> Python 3.6 -> Error 

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: de

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54224extension.js:229:54224
extension.js:229:52217extension.js:229:52217
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
