### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by sssanthosh107** [microsoft/vscode-azurefunctions#2173]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ETIMEDOUT
Error Message: connect ETIMEDOUT 13.92.237.218:443

Version: 0.22.1
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1056:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sssanthosh107 please add detailed repro steps
