### ISSUE TITLE
Failed to run "brew" command. Check output window for more details.

### ISSUE THREAD

**Issue by proth1** [microsoft/vscode-azurefunctions#2174]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "brew" command. Check output window for more details.

Version: 0.22.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:133816
fulfilled extension.bundle.js:1:132699
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@proth1 please check the output window. If that doesn't help, copy the output here and add repro steps
