### ISSUE TITLE
Support initializing custom handler apps

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2176]
Related #2175 

Custom handler apps have:

* `FUNCTIONS_WORKER_RUNTIME` set to `Custom`
* a `customHandler` section in host.json
* should launch the same way as any other runtime stack (`func start`).
    - some modifications to the startup command may be needed but that's up to the customer to do that ([example](https://github.com/anthonychu/azure-functions-deno-template/blob/66adfe7a17c675396821367b9867a0e12c02f3a2/.vscode/tasks.json))

See https://github.com/Azure/azure-functions-core-tools/issues/2052 for host.json

* Add `Custom Handler` to *Select a language* prompt
* We're adding templates to bundles https://github.com/Azure/azure-functions-templates/issues/955
    - templates will only include a *function.json* and no code file

**Comment by anthonychu** [comment]
@pragnagopa @yojagad

**Comment by anthonychu** [comment]
@pragnagopa @EricJizbaMSFT Please review details.

**Comment by pragnagopa** [comment]
cc @soninaren
ACK. Will update the issue once we have bundles ready to test.
