### ISSUE TITLE
Error: Azure Function Deployment using Visual Studio

### ISSUE THREAD

**Issue by VINODETRX** [microsoft/vscode-azurefunctions#2177]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: MissingRegistrationForLocation
Error Message: The subscription is not registered for the resource type 'components' in the location 'southindia'. Please re-register for this provider in order to have access to this location.

Version: 0.22.1
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:898333
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@VINODETRX please add repro steps. You can also try "Advanced" create
