### ISSUE TITLE
Deploy failing

### ISSUE THREAD

**Issue by saihaj** [microsoft/vscode-azurefunctions#2181]
Does this occur consistently? _Yes_
Repro steps:

1. Click the deploy to azure functions  takes a while and then get error. So far it has failed three times
Action: azureFunctions.deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.22.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2903676
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
Request.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@saihaj unfortunately we can't reproduce on those steps alone. Please add more detailed info, like how you created the function app, what options you chose when creating it, any logs from deploying, etc.
