### ISSUE TITLE
Linux consumption slot support

### ISSUE THREAD

**Issue by shivaniseth** [microsoft/vscode-azurefunctions#2185]
I wanted to understand if Slots on Linux consumption for function apps is even supported or not. Because when i test its seem to be able to create a slot via portal. But trying to deploy via VS code doesn't list the slots. we are currently giving a try by deploying via CLI. But my question is  ... are slots for Linux consumption Function apps are supported or not. If they aren't, why are we able to create them via portal. If they are then , should we update the doc. 

Refereed : 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots

![image](https://user-images.githubusercontent.com/54183841/85895164-bf089700-b7bb-11ea-87d4-c72b276d28e9.png)

**Comment by EricJizbaMSFT** [comment]
I believe the docs are accurate in this case - I don't think slots are officially supported on Linux Consumption. When I tried it out, it wasn't working for me. I could create and deploy to it, but the function itself returned some sort of generic "unavailable" or "bad request" error. Not sure why the portal allows it

**Comment by shivaniseth** [comment]
Thank you
