### ISSUE TITLE
AuthorizationFailed when switching between Learn Modules

### ISSUE THREAD

**Issue by hamzahamidi** [microsoft/vscode-azurefunctions#2186]
Does this occur consistently? Yes 
Repro steps:
I use Azure sandboxes for Azure learning paths. I don't see the new subscription even when I refresh in vscode. I have the following error:

Action: azureFunctions.createFunctionApp
Error type: AuthorizationFailed
Error Message: The client 'live.com#xxxxxxxxxxx@yyyy.com' with object id 'cafee073-eba5-4c2a-8166-864643125a29' does not have authorization to perform action 'Microsoft.Resources/subscriptions/locations/read' over scope '/subscriptions/0cb1fffd-fe14-44ea-a686-6eff61f986fc' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.22.1
OS: linux
OS Release: 4.15.0-106-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<summary>Call Stack</summary>

```
extension.bundle.js:225:374996
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

**Comment by EricJizbaMSFT** [comment]
@hamzahamidi can you link me to a specific learn module where this reproduces for you? I've tried a few learn modules in the past and they seemed to work

**Comment by hamzahamidi** [comment]
Hello @EricJizbaMSFT. Thank you for your response. I was following the [create serverless application path ](https://docs.microsoft.com/en-us/learn/paths/create-serverless-applications/) and then when moving from a course to another I had this problem. I believe it's because at the end of each course the sandbox is deleted & a new one is created when beginning a new course.

**Comment by EricJizbaMSFT** [comment]
Ah so it only happened right after switching courses?

**Comment by hamzahamidi** [comment]
Yes. Reinstalling Vscode does force the force thus solving the issue though.
