### ISSUE TITLE
Azure Function not able to debug.

### ISSUE THREAD

**Issue by maulinshah1015** [microsoft/vscode-azurefunctions#2187]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.22.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:101651extension.bundle.js:334:101651
fulfilled extension.bundle.js:334:99073
```

</details>

**Comment by EricJizbaMSFT** [comment]
@maulinshah1015 please add repro steps
