### ISSUE TITLE
Show `httpWorker` in `host.json` as warning 

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode-azurefunctions#2188]
`httpWorker` in `host.json` is defined as a property for custom handler feature (still in preview) in following doc.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#configuration

Otherwise vscode shows warning when the property is in `host.json` as following.
![image](https://user-images.githubusercontent.com/4566555/85933947-7c5bd180-b917-11ea-94e1-6373ead65e69.png)

**Comment by horihiro** [comment]
Is this caused by that `httpWorker` definition isn't in https://json.schemastore.org/host ?

**Comment by anthonychu** [comment]
`httpWorker` will be deprecated soon and obsolete before custom handlers is GA. We'll be changing it to a [`customHandler` section](https://github.com/Azure/azure-functions-host/issues/6080). We'll update schemastore after the change is complete.

**Comment by horihiro** [comment]
Thanks @anthonychu !
I look forward to the update

**Comment by EricJizbaMSFT** [comment]
Closing since this repo doesn't own the schema for host.json and sounds like Anthony is already on it
