### ISSUE TITLE
The default app service plan name is truncated with 24 characters during Function App creation

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2189]
**OS:** All
**Build Version:** 20200625.7

**Repro Steps:**
1. F1 --> Azure Functions: Create Function App in Azure... (Advanced) --> Input name "serene-adv-win-node12-appserviceplan" --> Node.js 12 --> Windows --> App Service Plan --> + Create new App Service Plan.
2. Check the default name for this app service plan.

**Expect:**
The default name shows as "serene-adv-win-node12-appserviceplan".

**Actual:**
The default name is truncated as "sereneadvwinnode12appser".
![image](https://user-images.githubusercontent.com/45614674/85944217-a341f400-b967-11ea-85c9-7b90c4a7b339.png)

**More Info:**
1. This issue also reproduces for the next creating new resources "resource group/AI...", we can edit it with longer characters.
2. This issue also reproduces for the next creating storage account, but this is expected.
![image](https://user-images.githubusercontent.com/45614674/85944213-9d4c1300-b967-11ea-9773-7911a5f83496.png)

**Comment by EricJizbaMSFT** [comment]
This is by design. We want to use the same name for the sake of consistency, matching the most restrictive rules (in this case storage).
