### ISSUE TITLE
An extra group glyph displays before the application setting

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#219]
Repro Steps:

1. Expand one function app.
2. Right click 'Application Settings' and select 'Add new setting...'.
3. Input valid setting key and setting value to complete the new setting.
4. Expand the 'Application Settings' node and check whether there is a group glyph before the new application setting or not.

Expect:
There is no the group glyph.

Actual:
Display an extra group glyph.
![application settings](https://user-images.githubusercontent.com/34729092/36092144-3ccbaeb2-0fde-11e8-9bc1-c9e4950f60d8.PNG)

More Info:
1. This issue also reproduces for Azure Account. 
![sign in](https://user-images.githubusercontent.com/34729092/36091898-5842df18-0fdd-11e8-8559-d840cddf39a2.png)
2. This issue also reproduces for other extensions before the leaf node.
3. Pop up below error after expanding the group glyph.
![error](https://user-images.githubusercontent.com/34729092/36091991-afa356ca-0fdd-11e8-8b0f-2a87d2b84f6b.png)

**Comment by EricJizbaMSFT** [comment]
Filed an issue on VS Code: https://github.com/Microsoft/vscode/issues/43608

**Comment by EricJizbaMSFT** [comment]
This is fixed on the latest version of Insiders
