### ISSUE TITLE
failed to load function template when create function project in codespace envrionment

### ISSUE THREAD

**Issue by nonokangwei** [microsoft/vscode-azurefunctions#2191]
tried ceate function project under codespace environment, it pending on load template stage.
![image](https://user-images.githubusercontent.com/12394417/85979131-8f9f9780-ba12-11ea-83c2-ad1cff572135.png)

**Comment by EricJizbaMSFT** [comment]
@nonokangwei what language did you select? And is there any output in the "Azure Functions" output channel?

**Comment by nonokangwei** [comment]
The language is python with 3.8 version. I just re-test in the my test codespace environment. It seems works fine now.
Thanks
BR
