### ISSUE TITLE
Debug Launch Not Building Project

### ISSUE THREAD

**Issue by allan-mobley-jr** [microsoft/vscode-azurefunctions#2196]
# Bug

When launching a C# http trigger function created with this project, the "host start" task fails saying it cannot find the specified dll in the bin folder. The bin folder is not there because the build task did not run even though it is clearly depended on in the "host start" task.

Only works if you first do a `dotnet build` in terminal or manually fire the build task. And you must continue to do these manual steps if you wish to see any code changes take effect.

NOTE: The build task is present and set as a depends on in the func start task. These task and a couple of others are created by this extension.

# Steps to Reproduce

* Create a new function project with a C# http trigger using this extension
* Once the project is created, go to debug and select "Attach to..." and try running it.

# Environment
* Latest VS Code Preview (although I noticed this prior to the past couple of daily updates
* Latest version of this extension v0.22.1
* azure-functions-core-tools@3.0.2630

**Comment by EricJizbaMSFT** [comment]
I can reproduce this on VS Code Insiders, but not stable VS Code. @allan-mobley-jr is that what you're seeing as well?

**Comment by allan-mobley-jr** [comment]
Yes @EricJizbaMSFT.

I use VS Code Insiders exclusively.

**Comment by EricJizbaMSFT** [comment]
Filed an issue on VS Code: https://github.com/microsoft/vscode/issues/101884

**Comment by EricJizbaMSFT** [comment]
Fixed for me on the latest insiders. Thanks for filing @allan-mobley-jr!

**Comment by allan-mobley-jr** [comment]
Awesome! I'll try it out.
