### ISSUE TITLE
Are Java functions not supported for remote debug ?

### ISSUE THREAD

**Issue by kasra21** [microsoft/vscode-azurefunctions#2197]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.startRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js Function Apps running on Linux App Service plans. Consumption plans are not supported.

Version: 0.22.1
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.getRemoteDebugLanguage extension.bundle.js:334:110768
extension.bundle.js:334:110415
fulfilled extension.bundle.js:334:109643
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
There's a bit of preview support for remote debugging Java apps. To try it, set "azureFunctions.enableJavaRemoteDebugging" to "true" in your VS Code settings
