### ISSUE TITLE
please help :'(

### ISSUE THREAD

**Issue by leozhang1** [microsoft/vscode-azurefunctions#2199]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/leozhang/Desktop/DesktopStuff/aSenior Design/MyAzureStuff/bin/Release/netcoreapp3.1/publish

Version: 0.22.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:281:26571
fulfilled extension.bundle.js:281:26075
```

</details>

**Comment by EricJizbaMSFT** [comment]
@leozhang1 check the output of the "publish" task. If that didn't succeed, the path mentioned won't exist
