### ISSUE TITLE
[Unstable]Fail to create new Linux Function App with EP2 pricing tier and Central US location

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2210]
**OS:** Windows/Mac
**Build Version:** 20200703.6

**Repro Steps:**
1. Create a new Linux Function App --> Select EP2 Pricing Tier --> Select Central US location.
2. Check the result.

**Expect:**
Success to create new Linux Function App.

**Actual:**
Fail to create new Linux Function App.
![image](https://user-images.githubusercontent.com/57662131/86436118-31d1bf00-bd34-11ea-8b22-e6d68cb4e58c.png)

**More Info:**
1. This issue reproduces for EP3 Pricing Tier.
2. Success to create new Function App with EP2 pricing tier and Central US location in portal.
3. The result of creating new Linux Function App with EP2 pricing tier in below locations.

    Location | Result
   -- | --
   East US2 | Fail
   Central US | Fail
   Australia East | Fail
   East Asia | Success
   Japan East | Success
   East US | Success

**Comment by EricJizbaMSFT** [comment]
What are you selecting for App Insights ("Skip for now" or "create new")? And what do you select for runtime stack? I just tried once with EP2 in Central US and it worked

**Comment by v-xinda** [comment]
Select "Create new App Insights resource..." and any one runtime stack when creating a new Function App. I test with EP2 in Central US and it also works, but it doesn't work in East US2.

**Comment by EricJizbaMSFT** [comment]
Will track this with https://github.com/microsoft/vscode-azurefunctions/issues/2258 instead
