### ISSUE TITLE
Azure function deployment in VS code

### ISSUE THREAD

**Issue by myousefzadeh** [microsoft/vscode-azurefunctions#2212]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\Users\myousefzadeh\Application Data'

Version: 0.22.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2215
