### ISSUE TITLE
App function deployment error

### ISSUE THREAD

**Issue by myousefzadeh** [microsoft/vscode-azurefunctions#2215]
Does this occur consistently? 
Repro steps:

I want to follow this Azure sample: https://github.com/Azure-Samples/azure-functions-pytorch-image-identify/tree/ea99ab8925d493001713f9e309061336ed94a497#set-the-application-settings-for-the-directory-and-the-model

1. I created an Azure function HTTP trigger
2. then followed the instruction to deploy the function where I faced this error:

Action: azureFunctions.deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\Users\myousefzadeh\Application Data'

Version: 0.22.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@myousefzadeh please add repro steps. Also, you may want to try putting your project in a folder other than "Application Data", which you may have restricted permissions

**Comment by myousefzadeh** [comment]
Thank you Eric. By restarting the laptop I could pass this issue.
