### ISSUE TITLE
Python Azure Functions Select Resource Group During Deployment

### ISSUE THREAD

**Issue by devorekristen** [microsoft/vscode-azurefunctions#2216]
It creates a resource group with the same name as the function, that contains the function, the storage account, and the consumption plan. 

Problem Statement: Currently unable to select the resource group when deploying a Python Azure function from Visual Studio Code using the Azure Function Extension.

Desired Experience: Ability to select the resource group when deploying a Python Azure Function from Visual Studio Code using the Azure Function Extension.

Users are unable to select the resource group when deploying a Python Azure function from Visual Studio Code using the Azure Function Extension. Currently, the extension creates a resource group with the same name as the function, that contains the function, the storage account, and the consumption plan.

**Comment by EricJizbaMSFT** [comment]
@devorekristen you should see an "Advanced" option which will give you many more options (including selecting an existing resource group) when you create a function app
