### ISSUE TITLE
Fail to start PowerShell session with PowerShell 6.2.x installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2218]
**OS:** Mac
**Build Version:** 20200706.1

**Repro Steps:**
1. Install PowerShell 6.2.6.
2. Create a PowerShell project with HttpTrigger function.
3. Open the .ps file of this project.
4. Check the PowerShell session.

**Expect:**
PowerShell session shows successfully with 6.2 version.

**Actual:**
Keep "Starting PowerShell..." state, an error occurs when clicking it.
![Screen Shot 2020-07-07 at 3 54 55 PM](https://user-images.githubusercontent.com/45614674/86765682-12140100-c07c-11ea-9020-50f94d211a03.png)

**More Info:**
1. Can't debug the PowerShell project due to this issue.
2. This issue does not reproduce with 7.0.2 PowerShell installed, but PowerShell 7 isn't supported yet.

**Comment by EricJizbaMSFT** [comment]
That error is coming from the PowerShell extension. We don't control the PowerShell session
