### ISSUE TITLE
Azure functions deployment failed

### ISSUE THREAD

**Issue by niraj246** [microsoft/vscode-azurefunctions#2223]
Does this occur consistently? No
Repro steps:
1. From "Azure" Extension > Functions window, perform "Deploy to Function App..." command.
2. In my case, the first attempt (when dpeloying for the first time) succeeded. Second attempt (to update) failed.

Action: azureFunctions.deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399345extension.bundle.js:309:399345
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add more information about your local project, how you created the function app in Azure, and any logs you see when deploying
