### ISSUE TITLE
Azure function fails to deploy to Linux host

### ISSUE THREAD

**Issue by niraj246** [microsoft/vscode-azurefunctions#2224]
Does this occur consistently? YES
Repro steps:
1. Deploy Azure Function (using Azure extention). Resource is Linux based.

Action: azureFunctions.deploy
Error type: Error
Error Message: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:281:31064extension.bundle.js:281:31064
fulfilled extension.bundle.js:281:29201
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1983
