### ISSUE TITLE
Error: Encountered an error (ServiceUnavailable) from host runtime when i am trying to deploy to a serverless Function App

### ISSUE THREAD

**Issue by khaledalarja** [microsoft/vscode-azurefunctions#2226]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2840812extension.bundle.js:225:2840812
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @khaledalarja  

We see this occasionally, but usually it's fixed by just trying again. It's a [somewhat common issue](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503) in Azure that is affected by what App Service plan you're running on.

Since this is really an Azure issue, the extension team can't do much to help you.  If you provide very detailed repro steps, including how you set up your local project, we may be able to offer some more insights though.

**Comment by khaledalarja** [comment]
hey @nturinski 
I can't remember what I have done, but is there any way to re-install with the right configs in order to not let that happen again?
thanks

**Comment by nturinski** [comment]
I'm sorry, I'm not sure I totally understand your question.  If you want to uninstall and reinstall the extension, you can do so through VS Code.

If you want to make sure it's a completely clean install, please look %USER%\.vscode\extensions. Deleting that gets rid of them completely.

For Windows : `%USER%\\.vscode\extensions` (or) `%USERPROFILE%\.vscode\extensions`

Location of extensions for `Linux/MAC: ~/.vscode/extensions`
