### ISSUE TITLE
8:44:12 am: Error: Failed to run "python3" command. Check output window for more details.

### ISSUE THREAD

**Issue by sanupanji** [microsoft/vscode-azurefunctions#2231]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.initProjectForVSCode
Error type: Error
Error Message: Failed to run "python3" command. Check output window for more details.

Version: 0.23.0
OS: linux
OS Release: 5.3.0-51-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134212
fulfilled extension.bundle.js:1:133095
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sanupanji please add repro steps and the logs from the output window
