### ISSUE TITLE
Deploy Azure Function project in sub folder

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azurefunctions#2233]
I am trying to deploy an Azure Function project in sub folder, however I meet with below popup.
![image](https://user-images.githubusercontent.com/1050213/87019209-e83a1600-c204-11ea-98e7-bd9954aeda0d.png)

From the code, it seems azureFunctions.projectRuntime and azureFunctions.projectLanguage are required in settings.json
https://github.com/microsoft/vscode-azurefunctions/blob/9d9a73014c5edb17db523ba907ab017ff005dabb/src/vsCodeConfig/verifyInitForVSCode.ts#L22

I need to add below settings.json to skip the popup, if I want to deploy an Azure Function project in sub folder. But I am not sure whether it is a best practise.

![image](https://user-images.githubusercontent.com/1050213/87019334-115aa680-c205-11ea-99c2-ed7b72eee141.png)

So I want to know whether there is a better way to deploy an Azure Function project in sub folder? Thanks!

**Comment by EricJizbaMSFT** [comment]
If you hit "Yes" for that warning, it will add all the settings you need, including the projectRuntime and projectLanguage. It should be able to find the project in a sub folder if it's one level down. If it's multiple levels down, you can add the "azureFunctions.projectSubpath" setting pointing to the right folder before you hit yes

**Comment by formulahendry** [comment]
As we have several projects in the workspace, we want to generate launch.json and tasks.json by ourselves during project scaffolding. So I want to confirm whether projectRuntime and projectLanguage are enough to make that..

**Comment by EricJizbaMSFT** [comment]
Yes those settings are the bare minimum to do things like "Create Function"/"Deploy". I would suggest you create a simple project from our extension and use those settings/tasks/launch as a guide when setting up your own stuff, but otherwise yes you're completely welcome to customize the tasks/launch/etc. as you see fit
