### ISSUE TITLE
Installed Azure Functions Extension, created new project, hit F5 to run (per your instructions https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-csharp) and get this error message.

### ISSUE THREAD

**Issue by wehnertb** [microsoft/vscode-azurefunctions#2236]
Does this occur consistently? 
Repro steps:

1. Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:123695extension.bundle.js:334:123695
fulfilled extension.bundle.js:334:121117
```

</details>

**Comment by EricJizbaMSFT** [comment]
@wehnertb I can reproduce with the steps you've listed. Please add detailed steps, including what your workspace looks like
