### ISSUE TITLE
When using a VSCode Workspace deploying an Azure Function hangs on Creating zip package...

### ISSUE THREAD

**Issue by sebastianrogers** [microsoft/vscode-azurefunctions#2239]
I have an basic function created via Azure Functions.

In VS CodeSpaces when I open a workspace containing the project attempts to deploy the project fail hanging when trying to build the zip file.

When I open the project folder directly it works.

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2108
