### ISSUE TITLE
Keep loading after closing the sign in browser 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#224]
Repro Steps:
1. Click 'Sign in to Azure...' when there is no account added and select 'Copy & Open', then make sure the browser is opened.
2. Close the opened browser without pasting the copied code.
3. Check whether the sign-in action is canceled or not.

Expect:
The 'Sign in to Azure' action is canceled.

Actual:
Keep loading to sign in.
![keeploading](https://user-images.githubusercontent.com/34729092/36147488-55fdf228-10b0-11e8-8b4c-3b72c7724786.png)

More Info:
This issue reproduces on Mac, Linux and Windows.

**Comment by EricJizbaMSFT** [comment]
Closing as this no longer repros and the azure account extension has changed a ton since the issue was originally filed.
