### ISSUE TITLE
Unable to signin after building code

### ISSUE THREAD

**Issue by yatna** [microsoft/vscode-azurefunctions#2243]
I am able to install the latest Azure Function extension from the marketplace and it works fine. 
However, when I try to build the latest code from this repo, the signin option is not working. I followed the following steps
1. Get latest code - git clone https://github.com/microsoft/vscode-azurefunctions.git
2. npm install
3. Press F5 to build and run

(It works when the user is already signed in before pressing F5, however if you signout in the new window you can't signin again. Also, if you are not signed in at the time you press f5, you cant sign in in the new window).

**Comment by nturinski** [comment]
Hi @yatna

Your steps seem to be correct and I haven't been able to repro the issue. Do you have the Azure Account extension installed?  The Functions extension relies on that to sign in so maybe there's some problems there?

You can install that here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account

**Comment by yatna** [comment]
This issue was resolved after pulling latest changes.
