### ISSUE TITLE
Error Deploying Function to Azure

### ISSUE THREAD

**Issue by coreyjb** [microsoft/vscode-azurefunctions#2244]
I m trying to do the DevKit State Project for the MXCHIP - https://github.com/Azure-Samples/mxchip-iot-devkit-state. I cannot "Deploy azure functions" and get an error.

Does this occur consistently?  Yes
Repro steps:

1. Go to https://github.com/Azure-Samples/mxchip-iot-devkit-state
2. Follow instructions until "Deploy Azure Functions" and get the error.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\<>\Documents\IoTWorkbenchProjects\examples\ZNew\Functions\bin\Release\netcoreapp2.1\publish

Version: 0.23.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3761934
fulfilled extension.bundle.js:225:3761426
```

</details>

**Comment by EricJizbaMSFT** [comment]
@coreyjb did the publish task succeed? If not, that path won't exist. Check the task output for more details

**Comment by coreyjb** [comment]
@EricJizbaMSFT - It did not but I did need to install the V2.1 of .NET Core, created a new project and deployed the azure function without error.  It looks like it did publish in the folder.  However, I the dev kit state does not seem to be working. I cannot connect to the App function I specified.

**Comment by EricJizbaMSFT** [comment]
So you got it to deploy successfully this time? Unfortunately, I'm not very familiar with the iot-devkit-state sample you mentioned. What error is blocking you?
