### ISSUE TITLE
Function Error

### ISSUE THREAD

**Issue by Pball01** [microsoft/vscode-azurefunctions#2245]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.23.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2840812
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:673128
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @Pball01

We see this occasionally, but usually it's fixed by just trying again. It's a somewhat common issue in Azure that is affected by what App Service plan you're running on.

Since this is really an Azure issue, the extension team can't do much to help you. If you provide very detailed repro steps, including how you set up your local project, we may be able to offer some more insights though.

**Comment by Pball01** [comment]
This is what I have on the local.settings.json file

`{
  "IsEncrypted": false,
  "Values": {
    "type": "",
    "project_id": "",
    "private_key_id": "",
    "private_key": "-----BEGIN PRIVATE KEY-----\n  \n-----END PRIVATE KEY-----\n",
    "client_email": "",
    "client_id": "",
    "auth_uri": "",
    "token_uri": "",
    "auth_provider_x509_cert_url": "",
    "client_x509_cert_url": "",
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "DefaultEndpointsProtocol"
  }
}`

**Comment by nturinski** [comment]
What kind of project are you trying to deploy?  The runtime of the project and also what kind of app service plan is the function app hosted on?

Have you tried deploying again?  Sometimes this error just goes away-- or you could also try creating a new app to deploy to.

**Comment by Pball01** [comment]
I am using Timer Function. I have trying to run it and deploy it since the morning and it is not working. I just created a new file and tried to deploy it, it is giving me the same error.

**Comment by nturinski** [comment]
Have you tried creating a new Function App?
