### ISSUE TITLE
Display an invalid HttpTriggerCSharp1 under the local project tree view during debugging

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2247]
**OS:** Win10
**Build Version:** 20200715.3
**VS Code insider Version:** 1.48.0

**Repro Step:**

1. Create a new C# project with HTTP Trigger function.
2. Open this project in VS Code --> Restore the dependencies.
3. Create a new Timer Trigger Function to this project.
4. F5.

**Expect:**
There is no invalid HttpTriggerCSharp1 under the local project tree view during debugging.

**Actual:**
Display an invalid HttpTriggerCSharp1 under the local project tree view during debugging.
![image](https://user-images.githubusercontent.com/62053665/87660224-4d57b380-c791-11ea-9281-2fa8de0db2a0.png)

**Comment by EricJizbaMSFT** [comment]
@v-mengwe what is the error if you expand the invalid HttpTriggerCSharp1?

**Comment by v-mengwe** [comment]
@EricJizbaMSFT Verified on the latest build: 20200720.1, this issue still reproduces for now. 

1. There is an error when expanding the invalid HttpTriggerCSharp1.
 ![image](https://user-images.githubusercontent.com/62053665/88003042-80ee6100-cb36-11ea-9c01-c16cc9ad0818.png)
3. There is the host.json file under the path in the error message.
 ![image](https://user-images.githubusercontent.com/62053665/88003232-ef332380-cb36-11ea-8dce-c1202d1786b1.png)
3. There is no invalid HttpTriggerCSharp1 under the local project tree view after finishing debugging.
![image](https://user-images.githubusercontent.com/62053665/88003808-4a194a80-cb38-11ea-827b-d0eb5d1f9345.png)
