### ISSUE TITLE
Invalid language "Javascript".

### ISSUE THREAD

**Issue by donniekerr** [microsoft/vscode-azurefunctions#2249]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: RangeError
Error Message: Invalid language "Javascript".

Version: 0.23.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.47.1
Language: en

<details>
<summary>Call Stack</summary>

```
ScriptFunctionCreateStep.<anonymous> extension.bundle.js:1:888704
fulfilled extension.bundle.js:1:887147
```

</details>

**Comment by EricJizbaMSFT** [comment]
@donniekerr please add repro steps. Not sure how you got there, but try changing your VS Code setting "azureFunctions.projectLanguage" to "JavaScript" with a capital "S"

**Comment by donniekerr** [comment]
Your VS Code system generated this issue.  I did not. so if it doesn't have enough info, I have no control over it.
