### ISSUE TITLE
[Linux]No 'Copy' item displays in Sign-in prompting dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#225]
Repro steps:
1. Click 'Sign in to Azure...' when ther is no account added.
2. Check the popped promoting dialog.

Expect:
It displays 'Copy & Open' item in Sign-in prompting dialog.
![copy](https://user-images.githubusercontent.com/34729022/36148758-0eac3164-10b5-11e8-885c-8d2bc0dd02bb.png)

Actual:
It only displays 'Open' item in Sign-in prompting dialog。

![open](https://user-images.githubusercontent.com/34729022/36148791-22cb5530-10b5-11e8-96bb-141c23acdb74.png)

More info:
**Pop an a new prompting dialog after clickign 'Open' item every time.**

**Comment by EricJizbaMSFT** [comment]
This is by-design on Linux as the copy-paste package we use only works if 'xclip' is installed on the user's machine. The user has to copy the code themselves

See here for more info:
https://github.com/Microsoft/vscode-azure-account/issues/9
https://github.com/Microsoft/vscode-azure-account/commit/1f351339da5f39755dcd4fe107de2da6bcebe10d
