### ISSUE TITLE
[Suggestion] Add "+ Create new Slot..." to the command list when executing swap slot command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2250]
**OS:** Win10
**Build Version:** 20200716.4

**Repro Steps:**

1. F1 --> Azure Functions: Swap Slot... --> Select a Function App --> Select a Slot.
2. Check the command list.

**Actual:**
There is no "+ Create new Slot..." in command list..

**Suggestion:**
Add "+ Create new Slot..." to the command list, such as:
![image](https://user-images.githubusercontent.com/62053665/87761344-df1ff900-c843-11ea-8d0d-21fefe7f3808.png)

**Comment by EricJizbaMSFT** [comment]
This is by design per https://github.com/microsoft/vscode-azurefunctions/issues/2100. There's no value in swapping something that was just created.
