### ISSUE TITLE
Deployment not found

### ISSUE THREAD

**Issue by humblemat810** [microsoft/vscode-azurefunctions#2251]
Does this occur consistently? 
Repro steps:

1.   occurs when changing config to enable FUNCTION_WORKER_RUNTIME bool using portal when I am also updating the new code from vs code
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: Deployment '9bbb4bad558044a58310f54b28461b9f' not found.

Version: 0.23.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:27747extension.bundle.js:309:27747
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:673128
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@humblemat810 can you expand on your repro steps? How did you create your function app? What type of app was it? And what were you doing with `FUNCTION_WORKER_RUNTIME`?

**Comment by humblemat810** [comment]
everything was done with UI... deployment was with the deploy button (upward arrow) and I sit back and watch.
was just switching from 2 to 3 when deployment as I forget the code tested local was 3.0
and so i was switching from 2 to 3 in azure portal

**Comment by EricJizbaMSFT** [comment]
Can you add some screenshots of your steps? Does this repro consistently? We've seen it happen occasionally, but it usually goes away if you try again
