### ISSUE TITLE
Requested features are not supported in region

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-azurefunctions#2258]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: BadRequest
Error Message: Requested features are not supported in region. Please try another region.

Version: 0.23.0
OS: linux
OS Release: 5.3.0-1032-azure
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2903676
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:673066
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@aronchick please add repro steps. We have logic to filter the list of regions, but that list is different based on which options you select. Perhaps we have a bug where we don't take into account the specific options you selected

**Comment by aronchick** [comment]
1. Go to VS Code
2. Quick action bar
3. "create function app in Azure"
4. Select subscription
5. Choose a unique name
6. Choose Python 3.7 as runtime
7. See regions where functions is available

Expected:
Only be presented with regions where functions can be placed.

Actual:
See all regions

**Comment by EricJizbaMSFT** [comment]
I thought we filtered that scenario. Any idea what region you selected when you got the error?

**Comment by aronchick** [comment]
Just repro'd for Japan West

![image](https://user-images.githubusercontent.com/51317/88982409-0aabd600-d27d-11ea-9af3-6a37c241c88a.png)
