### ISSUE TITLE
Error deploying to Azure Functions in ASE

### ISSUE THREAD

**Issue by thegeophysicist** [microsoft/vscode-azurefunctions#2264]
Trying to deploy an Azure Function to ASE using VS Code Azure Functions extension.  Received the error below.

Does this occur consistently? Yes
Repro steps:

1.  Deploy to Azure Functions

Action: azureFunctions.deploySlot
Error type: UNABLE_TO_VERIFY_LEAF_SIGNATURE
Error Message: unable to verify the first certificate

Version: 0.23.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:203:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by EricJizbaMSFT** [comment]
Hmm I've successfully deployed to an ASE in the past without seeing that error. Are you behind a corporate proxy? If so, this might help: https://code.visualstudio.com/docs/setup/network

**Comment by thegeophysicist** [comment]
This ended up being an issue with my certificate.
