### ISSUE TITLE
Debugging over remote doesn't seem to work?

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-azurefunctions#2265]
Honestly, I'm not sure what the issue is - 

I'm on a remote VM, and am able to start the debugging session using the following:
```
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9091,
      "preLaunchTask": "func: host start"
    }
```

But when I set a breakpoin and curl the endpoint, it just hangs. My best guess is that it's hanging but not updating VS Code correctly. Is there anything else I should do here to debug?

**Comment by EricJizbaMSFT** [comment]
When you say you're on a remote VM - you mean you're using the VS Code Remote SSH extension?

Can you copy the logs from the "func host start" task here?
