### ISSUE TITLE
Fails to create env when in a conda environment

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode-azurefunctions#2267]
It looks like the VS Code Extension assumes it can create a python virtual environment, which fails when using conda:

> 
> 4:12:18 PM: Running command: "C:\ProgramData\anaconda3\python.exe -m venv .venv"...
> Error: [Errno 2] No such file or directory: 'C:\\ProgramData\\anaconda3\\lib\\venv\\scripts\\nt\\python.exe'
> 4:12:19 PM: Error: Failed to run "C:\ProgramData\anaconda3\python.exe" command. Check output window for more details.

Note that python exe exists:

> > C:\ProgramData\anaconda3\python.exe
> Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>

**Comment by EricJizbaMSFT** [comment]
Hmm well it seems like this is the file causing problems:
> C:\ProgramData\anaconda3\lib\venv\scripts\nt\python.exe

Does that file exist?

As a workaround, you should have the option to "Skip for now" relating to the virtual environment when creating a project. You can also create a virtual environment in the project's folder _before_ you create a project and it should automatically detect and use that venv.
