### ISSUE TITLE
.json wont open

### ISSUE THREAD

**Issue by khutchin** [microsoft/vscode-azurefunctions#2268]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.openFile
Error type: Error
Error Message: cannot open azureextensionuiReadonly:/f9193bca29f0633867ad5c739945d34b8226a5e55480afe6fb73255c6a82d73c/BackToWorkFunctions.deps.json. Detail: Internal error: Expected value to be neither null nor undefined: ReadOnlyContentProvider._contentMap.get

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6082:388
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@khutchin please add repro steps. Does it only happen for this file and does it happen consistently? Do other files work?
