### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by lonpalmer** [microsoft/vscode-azurefunctions#2269]
Does this occur consistently? Yes
Repro steps:
1. Try to connect an Azure Function using Gradle to VS-Code using the functions plugin by clicking the +(lightning bolt): Create Function button.
2. Select Java as the Language

The plugin throws an error complaining that there is no pom.xml file.  build.gradle file does exist in the directory. The plugin should be able to use the build.gradle file now that Azure Functions has a Gradle plugin. 

Action: azureFunctions.createFunction
Error type: Error
Error Message: Cannot find pom.xml file in current project, please make sure the language setting is correct.

Version: 0.23.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
JavaInitVSCodeStep.<anonymous> extension.bundle.js:164:314024
fulfilled extension.bundle.js:164:313387
```

</details>

**Comment by opticyclic** [comment]
How is this out of scope??

**Comment by ejizba** [comment]
@opticyclic it's not out of scope _yet_. You're welcome to upvote the issue and get your coworkers/friends to do the same if you want the issue to stay open.
