### ISSUE TITLE
Can't hit the breakpoint for JavaScript project which created from func cli

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2273]
**OS:** Win10
**Build Version:** 20200804.3

**Repro Steps:**

1. Create a JavaScript project from func cli --> Open the created project in VS Code.
2. Click "Yes" when prompting a dialog.
3. Set breakpoint in index.js file --> F5.
4. Expand the Local Project tree view and right click on the function --> Select "Copy Function Url".
5. Paste the url into a browser.
6. Check the result.

**Expect:**
The breakpoint should be hit.

**Actual:**
The breakpoint is not hit.

**More Info:**
This issue does not reproduce on Mac.

**Comment by EricJizbaMSFT** [comment]
Nathan says he can repro on Windows. Will look into it

**Comment by EricJizbaMSFT** [comment]
Same problem as https://github.com/microsoft/vscode-azurefunctions/issues/2261
