### ISSUE TITLE
Functions host is no longer running.

### ISSUE THREAD

**Issue by vishal-hex** [microsoft/vscode-azurefunctions#2279]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:123695extension.bundle.js:334:123695
fulfilled extension.bundle.js:334:121117
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
