### ISSUE TITLE
Trouble with Using Node to Connect to Azure Function Locally

### ISSUE THREAD

**Issue by aronchick** [microsoft/vscode-azurefunctions#2288]
I have a function which I start normally:

```
func start
```

And it gives me a response. I can curl against it with `curl --request POST http://0.0.0.0:7071/api/fxn_name --data @tests/root_data.json`, and it works correctly. But when I try to execute a standard node query against it - 

```
                var options = {
                    host: host_val,
                    port: port_val,
                    path: fullpath,
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Content-Length': data.length
                      },
                    rejectUnauthorized: false
                  };
                  
```

I get the following error:
```
Error: write EPROTO 140228987283328:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at TLSSocket.Socket._destroy (net.js:679:5)
    at TLSSocket.destroy (internal/streams/destroy.js:38:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:93:12) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}

```

This ONLY happens locally! If I publish the function to Azure, it works great. Is there anything I'm missing here?

**Comment by aronchick** [comment]
I solved this because it was trying to connect locally using SSL and just disabled that.

It'd be nice if there was a hack for allowing local SSL to enable debugging.

**Comment by EricJizbaMSFT** [comment]
Can you give me more context on how you're using the node query mentioned above? Is it a completely different node app whose only purpose is to make an http request into the function app? And what setting did you change to fix the ssl stuff?

**Comment by aronchick** [comment]
The node app is completely separate and makes a request to this endpoint (both are running locally). 

Terminal 1:
``` 
~/dir_1# func start
<MUCH OUTPUT>
http://localhost:7071/api/func_name
```

Terminal 2:
```
~/dir_2# node index.js
```

`index.js` hits `localhost:7071` to test the function. I disabled `https` by swapping it out for the `http` package when I detected it was running locally. Nothing special.

**Comment by EricJizbaMSFT** [comment]
It seems like the func cli does support https if you want to use that. Take a look at the "useHttps" and "cert" arguments as described in these docs: https://docs.microsoft.com/azure/azure-functions/functions-run-local?#start
