### ISSUE TITLE
Use a newer durable functions package reference when creating functions

### ISSUE THREAD

**Issue by lintFan** [microsoft/vscode-azurefunctions#2291]
When I use version 0.23.0 of the Azure Functions extension to create a function using:
"Azure Functions: Create Function... " and selecting "DurableFunctionsOrchestration"  it references version 2.1.1 of [Durable functions](https://github.com/Azure/azure-functions-durable-extension/releases)
`<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1" />`

This version is from January 2020 and doesn't have fixes from later versions.  Creating a durable function using this process is what is described in the Durable functions [quickstart docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-create-first-csharp?pivots=code-editor-vscode#add-functions-to-the-app)

I ran into [this bug](https://github.com/microsoft/vscode-azurefunctions/issues/2067) with Durable entities  which is fixed in the later versions, so users who don't realize they are on an old version are not going to have a good experience if they use Durable entities. 

FYI @anthonychu

**Comment by anthonychu** [comment]
Looks like this PR was never merged. Thanks for the reminder. https://github.com/Azure/azure-functions-templates/pull/959

**Comment by EricJizbaMSFT** [comment]
Sounds like this is fixed in the templates repo.
