### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by hatsem78** [microsoft/vscode-azurefunctions#2292]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3.7" command. Check output window for more details.

Version: 0.23.0
OS: linux
OS Release: 5.4.0-42-generic
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134212
fulfilled extension.bundle.js:1:133095
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hatsem78 please add detailed repro steps and copy the output here
