### ISSUE TITLE
Cant create .NET Core 3.1 function

### ISSUE THREAD

**Issue by ottosson** [microsoft/vscode-azurefunctions#2297]
Does this occur consistently? Yes

Repro steps:
1. In VSCode, Select Create Function App in Azure... (Advanced)
2. Go through the steps: .NET Core 3.1 application / Linux / Consumption
3. Error...

Action: azureFunctions.createFunctionAppAdvanced
Error type: 500
Error Message: An error has occurred.

Version: 0.23.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2903676extension.bundle.js:225:2903676
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:673128
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
I tried to repro, but had no problems creating a linux consumption .net core 3.1 app. Can you give any more details, including copying the Azure Functions logs

**Comment by ottosson** [comment]
I'm not sure what I did wrong. I used the command palette to initiate the project. When I tried to use the "create function" button under the Azure tab it did work. Not sure if this needs to be open anymore.
