### ISSUE TITLE
Publish Function App

### ISSUE THREAD

**Issue by DAD713** [microsoft/vscode-azurefunctions#2301]
This is the first time I'm doing this, so it may be me.

Does this occur consistently? 
Repro steps:

1. Select Deploy to Function App
2. Create new function app in Azure...
3. Enter Name of new Function App
4. Press Enter

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.23.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54224extension.js:229:54224
extension.js:229:52217extension.js:229:52217
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
