### ISSUE TITLE
cant deploy

### ISSUE THREAD

**Issue by leozhang1** [microsoft/vscode-azurefunctions#2304]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/leozhang/Desktop/FALL 2020 STUFF/aSenior Design/BACK_END_API/Azure-Http-Function/bin/Release/netcoreapp3.1/publish

Version: 0.23.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3761934
fulfilled extension.bundle.js:225:3761426
```

</details>

**Comment by EricJizbaMSFT** [comment]
@leozhang1 did the publish task succeed? If not, that would explain why the path does not exist. If you're still stuck, add repro steps and copy the task logs here

**Comment by leozhang1** [comment]
> @leozhang1 did the publish task succeed? If not, that would explain why the path does not exist. If you're still stuck, add repro steps and copy the task logs here

Hey Eric! I don't see any repro steps, but the message in the terminal i got is here:

Executing task: dotnet clean --configuration Release /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

execvp(3) failed.: No such file or directory
The terminal process "dotnet 'clean', '--configuration', 'Release', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.

**Comment by EricJizbaMSFT** [comment]
Haha yeah when I asked for repro steps, I just mean tell me step by step how you got into that situation.

Do you have the dotnet cli installed and on your path? If not, you can install it from here: https://dotnet.microsoft.com/download
