### ISSUE TITLE
Design view does not work after turning on computer for the first time in a month.

### ISSUE THREAD

**Issue by mikaelsand** [microsoft/vscode-azurefunctions#2305]
Does this occur consistently? 
Repro steps:

1. I followed the install guide, including turning off auto-update. 
2. Come back from vacation.
3. Logic Apps design view cannot open. I get a very unspecific error.

I tried uninstalling everything and reinstall: Same issue.
I tried installing the latest version of Azure Functions and the add the VSIX-file: Same issue.

The only thing I have not tried (because I do not know how) is to: "please uninstall them first or make sure that the PATH environment variable points to the specific version here" as there are no values in the PATH variable to indicate any version of Functions.

I just want to get something working for a demo, and I have already uninstalled everything, is there anything else I can do?

Action: azureFunctions.openDesigner
Error type: Error
Error Message: {}

Version: 0.22.1-alpha
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:427722
fulfilled extension.bundle.js:164:424631
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
The official Azure Functions extension does not support this scenario. How did you get the logic apps functionality? I would follow up through those channels as my team isn't directly working on that

**Comment by mikaelsand** [comment]
Oops! Sorry.
This was in conjunction with a preview of a possible next for Logic Apps. The report was filed directly from VS code, and I thought it got routed to those guys.
