### ISSUE TITLE
Deployment slots for Linux Consumption

### ISSUE THREAD

**Issue by dariagrigoriu** [microsoft/vscode-azurefunctions#2307]
Enable deployment slots for Linux Consumption

**Comment by EricJizbaMSFT** [comment]
@dariagrigoriu is this fully supported? I seem to be getting a ServiceUnavailable error consistently when I attempt to sync triggers on a slot. It works perfectly if I deploy the same thing to production. We're using this ARM api:

subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/slots/{slot}/syncfunctiontriggers
