### ISSUE TITLE
azureFunctions.pickProcess only works if preLaunchTask is the last task in tasks.json

### ISSUE THREAD

**Issue by bijeebuss** [microsoft/vscode-azurefunctions#2310]
Does this occur consistently? Yes
Repro steps:

1.  Check out https://github.com/bijeebuss/vscode-azurefunctions-bug
2.  Launch the Config1 debug config (it fails)
3. Launch Config2 (it works)
4. Switch the order of task1 and task2 in tasks.json and now its the other way around

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to find "task1" task.

Version: 0.23.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:122218extension.bundle.js:334:122218
fulfilled extension.bundle.js:334:121117
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bijeebuss** [comment]
I am open to suggestions if there is a better way to have multiple debug configurations with different env variables

**Comment by EricJizbaMSFT** [comment]
Well it's a bit of a hack, but if you change one of `"command": "host start"` to `"command": "start"` - it should make both tasks work. I guess VS Code thinks they're the same task if "command" is the same and using "start" instead tricks VS Code into thinking they're different. We're just lucky "host start" and "start" both exist and both do the same thing

**Comment by bijeebuss** [comment]
After doing some testing I don't think the extension supports debugging multiple function apps at once either way, so I'm going a different route with this.

**Comment by EricJizbaMSFT** [comment]
We do support debugging multiple function apps at once. See this doc: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

**Comment by bijeebuss** [comment]
oh good to know. Although I have been having issues with multi root workspaces as well. I think it is related to this 
https://github.com/OmniSharp/omnisharp-vscode/issues/3988

**Comment by bijeebuss** [comment]
In my case I don't think that would help anyway since I wanted to start two instances of the same function app project with different env variables

**Comment by EricJizbaMSFT** [comment]
@bijeebuss yeah haven't really thought of that scenario. Sounds like you might be "going a different route" anyways? If so, we'll probably close this issue.

**Comment by bijeebuss** [comment]
I decided to just combine my function apps into one project and I will deploy it to different function app instances with different configurations. I still think this is a bug but you can close if you want since I wont be needing a fix

**Comment by EricJizbaMSFT** [comment]
Looked into it and added a comment to this VS Code bug: https://github.com/microsoft/vscode/issues/94381#issuecomment-681187182
