### ISSUE TITLE
Workflow design time could not be started when try to open workflow template in designer

### ISSUE THREAD

**Issue by amirjalali65** [microsoft/vscode-azurefunctions#2312]
Does this occur consistently? Yes
Repro steps:
1. Testing Azure Functions version 0.22.1-alpha to test new logic app features 
2. Followed the tutorial video and open a workflow in designer on Mac os while Azurite Blob service and queue service are running locally. 

Action: azureFunctions.openDesigner
Error type: Error
Error Message: {}

Version: 0.22.1-alpha
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:427722
fulfilled extension.bundle.js:164:424631
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
The official Azure Functions extension does not support this scenario. How did you get the logic apps functionality? I would follow up through those channels as my team isn't directly working on that
