### ISSUE TITLE
Error Message: EPERM: operation not permitted, lstat ......

### ISSUE THREAD

**Issue by alex4cranfield** [microsoft/vscode-azurefunctions#2316]
The following happens everytime I try to create a project (using Azure functions) in VS Code.  It has never succeeded.  Please help. ;)

Action: azureFunctions.createFunction
Error type: EPERM
Error Message: EPERM: operation not permitted, lstat 'C:\Users\user\AppData\Local\Temp\652143b394\userproject\.gitignore'

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

**Comment by EricJizbaMSFT** [comment]
I would try opening a folder that's _not_ under "C:\Users\user\AppData\Local\Temp". You probably just don't have permissions for that folder
