### ISSUE TITLE
Azure having too much issue with deployment into Azure function.

### ISSUE THREAD

**Issue by rahulmodu** [microsoft/vscode-azurefunctions#2318]
These couple of days Azure annoying to me. Taking too much time to deploy azure function.

Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.23.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rahulmodu please add detailed repro steps - including what type of project you have, how you created the function app in Azure, and are you by chance behind a corporate proxy?
