### ISSUE TITLE
Function Deployment annoying me 

### ISSUE THREAD

**Issue by rahulmodu** [microsoft/vscode-azurefunctions#2322]
Function Deployment annoying me 

Does this occur consistently? 
Repro steps:

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND storageaccountorder99ab.blob.core.windows.net

Version: 0.23.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2318
