### ISSUE TITLE
Azure functions bundle resolution in vscode

### ISSUE THREAD

**Issue by yojagad** [microsoft/vscode-azurefunctions#2323]
While testing newer bundle with vscode, it was realized that certain ordering is expected with respect to how bundle versions are ordered in index-v2.json  in order to pick up 1.3.3. Example current index-v2.json which is not in order https://functionscdnstaging.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index-v2.json
@EricJizbaMSFT 

cc: @soninaren @pragnagopa

**Comment by EricJizbaMSFT** [comment]
Seems like I'm getting 1.3.3 if I try the staging feed. How did you verify if it was on 1.3.3 or not?

**Comment by yojagad** [comment]
We had templates that were specifically in 1.3.3 and 2.0.1 but not in the previous versions (custom handler templates). Not sure if that's a sure shot way of knowing. If loading both of them still work despite the order , please feel free to close this issue .

**Comment by EricJizbaMSFT** [comment]
It's unlikely custom handler templates would show up. Tracking that work as a part of https://github.com/microsoft/vscode-azurefunctions/issues/2176

**Comment by soninaren** [comment]
@EricJizbaMSFT, @yojagad , We also tried by changing some of the contents in the the blob trigger template. The updated content would not show up until we changed the order of the version in the index-v2.json. I can try and provide a full end to end repro, but i do think there is a bug here.
