### ISSUE TITLE
When deploying 64 bit project, Azure function app should be updated to 64 bit mode

### ISSUE THREAD

**Issue by prabh-62** [microsoft/vscode-azurefunctions#2326]
## System 
- Visual Studio Code - `1.48.1`
- [Azure Functions extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) - `0.23.0`

Create a 64-bit Azure Functions project and `Deploy to Functions App` using extension
<img width="1299" alt="64_bit_vscode" src="https://user-images.githubusercontent.com/13006107/90841891-e39c6d80-e32b-11ea-8446-e69ee5e0ea79.png">

VSCode extension doesn't update project setting in Azure portal if previously app was in 32-bit mode.
<img width="1257" alt="32_bit_func_portal" src="https://user-images.githubusercontent.com/13006107/90842007-2bbb9000-e32c-11ea-8c66-ae59856eee28.png">

After successfully deploying 64 bit, if we hit any functions, API returns `HTTP 503: Service Unavailable`
<img width="601" alt="64_bit_not_running" src="https://user-images.githubusercontent.com/13006107/90842039-4261e700-e32c-11ea-8665-171ee61e539f.png">

### Expected Outcome
Extension should update Azure Functions app to 64-bit in Azure Portal as well

**Comment by prabh-62** [comment]
@EricJizbaMSFT I saw the `help-wanted` label and created a Pull request for this issue. Looking for feedback on the PR https://github.com/microsoft/vscode-azurefunctions/pull/2429

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-azurefunctions/pull/2429
