### ISSUE TITLE
'Parse Error: Expected HTTP/' when Deploying

### ISSUE THREAD

**Issue by wflemingnz** [microsoft/vscode-azurefunctions#2327]
Does this occur consistently? Yes

**Repro steps:**

1. Deploy .NET core function to newly created Function App via VS Code or Visual Studio

**Expected Result:**

Deploy is successful, no errors occur

**Actual Result:**

Using VS Code, it gives 'Parse Error: Expected HTTP/' immediately after it has finished building and attempts to deploy.
Using Visual Studio, it gives no errors but when I go to the App Service in the Portal, it has no functions.

Note, deploy to existing function app is successful.

Action: azureFunctions.deploy
Error type: HPE_INVALID_CONSTANT
Error Message: Parse Error: Expected HTTP/

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
Socket.socketOnData _http_client.js:449:22
Socket.emit events.js:203:13
Socket.Readable.read _stream_readable.js:515:10
flow _stream_readable.js:984:34
resume_ _stream_readable.js:965:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Are you by chance behind a corporate proxy that may be messing with our requests? If so, double check the network settings [here](https://code.visualstudio.com/docs/setup/network)

Also - how did you create the function app? Directly in VS Code? If so - can you let me know what you selected, including the .net core version and functions runtime version

**Comment by wflemingnz** [comment]
Hi, yes the problem went away when I turned off the corporate VPN.

Thanks
