### ISSUE TITLE
algo va mal

### ISSUE THREAD

**Issue by carlosnp** [microsoft/vscode-azurefunctions#2330]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.23.0
OS: linux
OS Release: 4.15.0-112-generic
Product: Visual Studio Code
Product Version: 1.48.0
Language: es

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:1:575977
fulfilled extension.bundle.js:1:569926
```

</details>

**Comment by EricJizbaMSFT** [comment]
@carlosnp please add detailed repro steps
