### ISSUE TITLE
Action: azureFunctions.createNewProject

### ISSUE THREAD

**Issue by lordtang** [microsoft/vscode-azurefunctions#2333]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: 无法写入工作区设置。请打开工作区设置并清除错误或警告，然后重试。

Version: 0.23.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.48.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
D.reject workbench.desktop.main.js:5544:245
file:/workbench.desktop.main.js:5548:267
async D.doWriteConfiguration workbench.desktop.main.js:5541:403
```

</details>

**Comment by EricJizbaMSFT** [comment]
@lordtang please add detailed repro steps
