### ISSUE TITLE
Fail to swap the slot with the production for the first time

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2335]
**OS:** Win10
**Build Version:** 20200822.1

**Repro Steps:**
1. Create a new Windows Function App with .NET and app service plan/premium hosting plan --> Deploy a .NET project to it.
2. Create a slot for it.
3. Swap the slot with the production.
4. Check the result.

**Expect:**
Succeed to swap the slot with production.

**Actual:**
Fail to swap the slot with the production for the first time.
![image](https://user-images.githubusercontent.com/57662131/91012035-f65abf00-e617-11ea-8345-a1c6fedf5a04.png)
Details in Output:
```
2:37:43 PM: Swapping "nicole-net3-app-win-production" with "nicole-net3-app-win-slot2"...
2:39:51 PM: Error: Failed with code "400".
```
**More Info:**
1. This issue doesn't reproduce for Linux Function App.
2. This issue doesn't reproduce when swapping the slot again.
3. This issue doesn't reproduce on Mac and Ubuntu 18.04 OS.

**Comment by EricJizbaMSFT** [comment]
Unlikely we can do anything here. The fact that it works if you try again and works on different _local_ OS's means it's probably just an intermittent error from Azure
