### ISSUE TITLE
Python version not found

### ISSUE THREAD

**Issue by himan2411** [microsoft/vscode-azurefunctions#2338]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.initProjectForVSCode
Error type: Error
Error Message: Failed to run "python3" command. Check output window for more details.

Version: 0.23.0
OS: linux
OS Release: 5.4.0-42-generic
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134212
fulfilled extension.bundle.js:1:133095
```

</details>

**Comment by EricJizbaMSFT** [comment]
@himan2411 please check the output window. If that doesn't help, copy the output here and add repro steps
