### ISSUE TITLE
Failed to retrieve templates from the Azure Functions Portal

### ISSUE THREAD

**Issue by lyceus** [Microsoft/vscode-azurefunctions#234]
Following this guide to get started with VS Code & Azure Functions with JS: [https://code.visualstudio.com/tutorials/functions-extension/create-function](https://code.visualstudio.com/tutorials/functions-extension/create-function) in a new VS Code install in a Win10 VM. Dependencies installed OK, Azure Functions extension v0.6.0 installed, and I'm logged into Azure. When trying to create a new Function I choose a project directory, but then get an error: "Failed to retrieve templates from the Azure Functions Portal."

Using `func templates list` in the VS Code terminal lists 4 C# and 4 JS templates.

Is there some additional information I can capture for you to help?

**Comment by EricJizbaMSFT** [comment]
We're dynamically retrieving the templates from the functions portal (we're not using the functions cli directly for this). Can you navigate to this url on your machine and see if it works?
https://functions.azure.com/api/templates?runtime=~2

**Comment by EricJizbaMSFT** [comment]
Thanks for reporting the issue @lyceus. The issue has been identified and fixed in the functions portal api. It should work for you now.

In addition, I've filed a separate issue to make sure this doesn't happen again in the future: https://github.com/Microsoft/vscode-azurefunctions/issues/236
