### ISSUE TITLE
Error on function deploy through extenstion

### ISSUE THREAD

**Issue by tejashshrestha** [microsoft/vscode-azurefunctions#2341]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.23.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:41330
extension.js:393:35925
extension.js:243:74625
extension.js:243:73483
B._callback extension.js:16:228415
B.t._callback.t.callback.t.callback extension.js:202:5500
B.emit events.js:203:13
B.EventEmitter.emit domain.js:476:20
B.<anonymous> extension.js:202:18360
B.emit events.js:203:13
B.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.js:202:17192
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
