### ISSUE TITLE
Function Creation Issue

### ISSUE THREAD

**Issue by sumirchawla** [microsoft/vscode-azurefunctions#2343]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionAppAdvanced
Error type: AuthorizationFailed
Error Message: The client '---' with object id '---' does not have authorization to perform action 'Microsoft.Web/sites/write' over scope '/subscriptions/---/resourceGroups/---/providers/Microsoft.Web/sites/---' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.24.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
extension.bundle.js:33:1087204extension.bundle.js:33:1087204
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sumirchawla please add repro steps

Could be related to https://github.com/microsoft/vscode-azurefunctions/issues/2186
