### ISSUE TITLE
DISCUSSION: Exposing stubbing for input bindings for functions while debugging on VS Code

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2346]
Currently, there is a way to quickly stub input bindings as well as trigger functions when debugging locally but that visibility is very low.  Not a lot of people are aware this is a new feature.  What are some ways we can expose this feature to customers?

**Comment by EricJizbaMSFT** [comment]
We're open to any suggestions you have. Users can right click in the "functions.json" file, on a function in the "Local Project" tree view, or use the command palette. Those are our most common entry points for a feature like this, and I don't think it's worth something as in-your-face as a button in the ribbon

**Comment by ejizba** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2641
