### ISSUE TITLE
Language Worker Debug Arguments need to be appended

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/vscode-azurefunctions#2350]
Debug args for non-dotnet processes are set in the environment variable: `langaugeWorkers:{language}:arguments`

For example node debug args are set here:

https://github.com/microsoft/vscode-azurefunctions/blob/d1318cad6809dbe65029dfe2012c76a1b17d0df5/src/debug/NodeDebugProvider.ts#L27

Debug port info needs to be appended to `languageWorkers__node__arguments` if the env variable exists

cc @paulbatum

**Comment by EricJizbaMSFT** [comment]
Can you describe the scenario here? Not entirely sure what you're asking for

**Comment by pragnagopa** [comment]
Here is an example, users can customize node process start up arguments by setting env variable: `languageWorkers__node__arguments` - functions host appends value of `anguageWorkers__node__arguments` env variable as command line arguments when launching node process.

Users need to be able to provide custom input arguments when debugging from VSCode. As of now, env var `languageWorkers__node__arguments` set by user is overridden when debugging from VSCode.

**Comment by EricJizbaMSFT** [comment]
So the value specified in a user's tasks.json takes precedence. If I manually edit my tasks.json to do this:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "npm install",
      "options": {
        "env": {
          "languageWorkers__node__arguments": "notGonnaWork"
        }
      }
    },
```

I see this in my logs when I debug:
> [9/4/2020 12:12:04 AM] Starting worker process with FileName:node WorkingDirectory:/Users/erijiz/TestRepos/js2 Arguments: notGonnaWork "/Users/erijiz/.nvm/versions/node/v12.16.3/lib/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 52965 --workerId 58d94ba4-be43-47a2-961a-013d432e69fe --requestId 77fc07e3-23c8-47e1-90a7-59d10ca5a105 --grpcMaxMessageLength 2147483647
[9/4/2020 12:12:04 AM] node process with Id=51711 started

I'm trying to understand _why_ a user would append to that environment variable to understand if that's sufficient or if we need to do something else. Do you have an example scenario _why_ a user would do this?

**Comment by pragnagopa** [comment]
> Do you have an example scenario why a user would do this?

Please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#memory-utilization-considerations

In the above example users have the ability to to increase this fixed memory limit by setting setting `languageWorkers__node__arguments`

Another example:
Please see here: https://github.com/Azure/azure-functions-java-worker/wiki/Customize-JRE-used-by-Azure-Functions on how users can customize JVM options for Java process.

In the output you pasted above where is the port being set `--port 52965` ?

**Comment by EricJizbaMSFT** [comment]
I have no idea how `--port 52965` is set (or most of the other arguments for that matter) - I thought that was handled within the func cli. 

I think I prefer overwrite instead of append. We're doing a bit of black-box-magic here with the environment variable and I want to allow users to completely override what we're doing if necessary. I worry append could make it even more magic-y.

Assuming we agree on that, I think my only action item is to make sure we defer to the environment variable regardless of how it's set (aka we already defer if it's set in tasks.json, but probably need to fix if it's set in the process itself).

**Comment by pragnagopa** [comment]
I agree exposing this setting so that user can override is a better option.
