### ISSUE TITLE
Entry not found in cache

### ISSUE THREAD

**Issue by Amany-Si** [microsoft/vscode-azurefunctions#2353]
Does this occur consistently?  yes
Repro steps:

1. Create a local project that takes HTTP request and return a json/application response 
2. Deploy it to function app from virtual studio code 
3. All the deployed functions give the same error 
Note: The only thing that I did just installing the power shell command service 

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.24.0
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:41330
extension.js:393:35925extension.js:393:35925
extension.js:243:74572extension.js:243:74572
extension.js:243:72553extension.js:243:72553
extension.js:243:72173extension.js:243:72173
i.find extension.js:243:106705
extension.js:243:53427extension.js:243:53427
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
