### ISSUE TITLE
Cannot create function app in Japan East with Japanese language pack

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode-azurefunctions#2356]
Does this occur consistently? Yes
Repro steps:
1. Install and enable Japanese language pack in VScode
1. Create Function App in Azure
![image](https://user-images.githubusercontent.com/4566555/92103055-64726380-ee1a-11ea-8829-ce314d212f6b.png)
1. Input any name, function runtime and select Windows as OS
1. Select "東日本" meaning `japaneast`
![image](https://user-images.githubusercontent.com/4566555/92103274-aa2f2c00-ee1a-11ea-9fa4-4baf5dbacdbe.png)

After selecting the parameters, this extension created a storage account in `japaneast` correctly but the extension tried to create an appinsights resource in `japanwest`.
![image](https://user-images.githubusercontent.com/4566555/92103702-46593300-ee1b-11ea-886a-25fd872e4f5a.png)
Then this deployment was failed because appinsights is not supported in `japanwest`.

Action: azureFunctions.createFunctionApp
Error type: LocationNotAvailableForResourceType
Error Message: 指定された場所 'japanwest' は、リソースの種類 'microsoft.insights/components' には使用できません。そのリソースの種類に使用可能なリージョンの一覧は 'eastus,southcentralus,northeurope,westeurope,southeastasia,westus2,uksouth,canadacentral,centralindia,japaneast,australiaeast,koreacentral,francecentral,centralus,eastus2,eastasia,westus,southafricanorth,northcentralus,brazilsouth,switzerlandnorth,australiasoutheast' です。

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.49.0-insider
Language: ja

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:1300:439742
extension.bundle.js:1300:467643extension.bundle.js:1300:467643
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by horihiro** [comment]
As long as I investigate, it seems that this issue is caused by following code in [vscode-azuretools@0.66.1](https://github.com/microsoft/vscode-azuretools) which vscode-azurefunctions depends on.
https://github.com/microsoft/vscode-azurefunctions/blob/9dfc22ddeca837b4e19d113ce5bc96a3745debaa/package.json#L1075

https://github.com/microsoft/vscode-azuretools/blob/main/appservice/src/createAppService/AppInsightsCreateStep.ts#L66
![image](https://user-images.githubusercontent.com/4566555/92105512-e87a1a80-ee1d-11ea-8970-6dbd50fa8a14.png)

When this issue is reproduced, each element of variable `locations` in L66 are location names in English, for example `Japan East`, `Japan West` and so on.
But a process goes to `else` block because variable `location.displayName` is `東日本` in same line.

In `else` block, `japanwest` is retrieved as a paired region of variable `locationName`, which value is `japaneast`, by `getPairedRegions` and `locationName` in L71, then the process tries to deploy the appinsights resource in Japan West and the deployment is failed.

**Comment by horihiro** [comment]
@EricJizbaMSFT Could you please give me any comments about this?

**Comment by EricJizbaMSFT** [comment]
We'll look into it - for now I recommend picking a different location or using the portal as a workaround
