### ISSUE TITLE
Support comments in "local.settings.json"

### ISSUE THREAD

**Issue by wdy0719** [microsoft/vscode-azurefunctions#2359]
Cannot build/create azure function when local.settings.json contains comment lines (which works in vs2019).

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to parse "local.settings.json": Unexpected token / in JSON at position 287.

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:33:862999extension.bundle.js:33:862999
fulfilled extension.bundle.js:33:862293
```

</details>

![image](https://user-images.githubusercontent.com/11709227/92162968-d41b2b00-ede7-11ea-94ae-eafd96bcd0ec.png)

**Comment by martinhenrysson** [comment]
I would also like support for comments. It is sometimes useful when switching between environments and using code that was checked-in from Visual Studio 2019.

**Comment by acds** [comment]
I'd suggest just changing value name (like append an `X`) such that it different than the code expects so the parameter is config is not found via the json, but defers Environment others other configured source.

JSON does not support comments as standard. if you want to actually add comments just use a element labels:
```JSON
{
    "_comment":  "Comments with // or /**/ are NEVER used in a JSON file!!!",
    "regulardata": "stuff",
    "mySettingX": "my setting with X appended so code does not pick it up from json config"
}
```
