### ISSUE TITLE
Invalid EndpointSuffix in the provided Connection String

### ISSUE THREAD

**Issue by ljtill** [microsoft/vscode-azurefunctions#2360]
Does this occur consistently? Yes

Repro steps:

1. Click the deploy button within the VS Code Az Function extension

```
9:39:04 PM: Error: Invalid EndpointSuffix in the provided Connection String
9:43:19 PM <func-name>: Starting deployment...
9:43:21 PM: Error: Invalid EndpointSuffix in the provided Connection String
9:43:57 PM <func-name>: Starting deployment...
9:43:59 PM: Error: Invalid EndpointSuffix in the provided Connection String
9:48:15 PM <func-name>: Starting deployment...
9:48:15 PM: Error: Invalid EndpointSuffix in the provided Connection String
```

Issue seems to only happen with the extension, when attempting to deploy with the Azure Function Core Tools there aren't any issues reported.

`func azure functionapp publish <func-name>` 

Action: azureFunctions.deploy
Error type: Error
Error Message: Invalid EndpointSuffix in the provided Connection String

Version: 0.24.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
extractConnectionStringParts extension.bundle.js:1300:131399
Function.BlobServiceClient.fromConnectionString extension.bundle.js:1300:295725
extension.bundle.js:1009:46824
fulfilled extension.bundle.js:1009:46043
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by Jonatan-V** [comment]
same issue here

**Comment by EricJizbaMSFT** [comment]
Can you guys add more detailed repro steps? For example - what type of project are you deploying? Python/JavaScript/etc.? And how did you create the function app in Azure? Through VS Code or the portal?

**Comment by Jonatan-V** [comment]
I have an existing function app with functions that has been working fine until recently. Azure resources are deployed with arm template. Os linux, function version 3, runtime node, node verison 12. I write the code in vscode and publish with the vscode functions extension. I use eventgrid and cosmosdb bindings.
Let me know if you need more info, i can also do a screen share if that is of interest.

Regards Jonatan

**Comment by EricJizbaMSFT** [comment]
Can you double check your app setting "AzureWebJobsStorage" for "EndPointSuffix"? Don't copy the whole setting here (for security reasons), but for example mine has this at the end: `EndpointSuffix=core.windows.net`. I'm curious if yours is either missing the EndpointSuffix or has something different (maybe a period at the beginning?)

<img width="436" alt="Screen Shot 2020-09-08 at 12 56 14 PM" src="https://user-images.githubusercontent.com/11282622/92521797-b4627900-f1d2-11ea-9fce-cc3eab978a44.png">

**Comment by Jonatan-V** [comment]
You are correct. Its missing on some of my functions (the ones that gets the error), ie one looks like this: DefaultEndpointsProtocol=https;AccountName=myname;AccountKey=mykey
Do you know if there has been a change in behaviour regarding the requirement for EndpointSuffix lately?
Either way, i can confirm that adding "EndpointSuffix=core.windows.net" to the end of the "AzureWebJobsStorage" app setting solves the problem.
PS the error message has some potential for improvement. Would be great if it stated which connection string/app setting its referring to.

Regards Jonatan

**Comment by EricJizbaMSFT** [comment]
> Do you know if there has been a change in behaviour regarding the requirement for EndpointSuffix lately?

Seems like this is the case. We'll change it back to being optional
