### ISSUE TITLE
azureFunctions.createNewProject Error type: ETIMEDOUT

### ISSUE THREAD

**Issue by dcguerrac** [microsoft/vscode-azurefunctions#2361]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/fe04196d-a862-412e-8346-3bbb88a80b32/resourceGroups/RG_EU2_C001_HUBD_DEV_01/providers/Microsoft.Storage/storageAccounts/staeu2c001hubddev01/listKeys?api-version=2019-06-01 failed, reason: connect ETIMEDOUT 191.233.205.17:443

Version: 0.24.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:208:15
TLSSocket.socketErrorListener _http_client.js:399:9
TLSSocket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```
d
</details>
ds  sds

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
