### ISSUE TITLE
Issue when deploying azure functions

### ISSUE THREAD

**Issue by sylwiaboguska** [microsoft/vscode-azurefunctions#2367]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.24.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
extension.bundle.js:33:1087204extension.bundle.js:33:1087204
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sylwiaboguska try deploying again after a little while or add repro steps
