### ISSUE TITLE
[Suggestion] Remove the region which doesn't allow Subscription

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2368]
**OS:** Win10
**Build Version:** 20200903.19

**Repro Steps:**
1. Create a Function App with the "App Service Plan" hosting plan and "Switzerland North" location.

**Actual:**
Fail to create the Function App.
![image](https://user-images.githubusercontent.com/57662131/92368064-ccca8900-f129-11ea-8ffe-7c4793fcd9a8.png)

**Suggestion:**
Remove the region which doesn't allow to use Subscription.

**More Info:**
This issue also reproduces when creating a Function App(basic) with the above location.

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2258
