### ISSUE TITLE
cannot install azure functions

### ISSUE THREAD

**Issue by majo1313** [microsoft/vscode-azurefunctions#2370]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.installOrUpdateFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 0.24.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:33:51462
fulfilled extension.bundle.js:33:50345
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@majo1313 there should be more logs in the output window (which should automatically become visible when this error occurs). If you still need help after looking at those, please copy the logs here and add repro steps
