### ISSUE TITLE
test

### ISSUE THREAD

**Issue by y-yamamoto-github** [microsoft/vscode-azurefunctions#2373]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: LocationNotAvailableForResourceType
Error Message: 指定された場所 'japanwest' は、リソースの種類 'microsoft.insights/components' には使用できません。そのリソースの種類に使用可能なリージョンの一覧は 'eastus,southcentralus,northeurope,westeurope,southeastasia,westus2,uksouth,canadacentral,centralindia,japaneast,australiaeast,koreacentral,francecentral,centralus,eastus2,eastasia,westus,southafricanorth,northcentralus,brazilsouth,switzerlandnorth,australiasoutheast' です。

Version: 0.24.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: ja

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:1300:439742
extension.bundle.js:1300:467643
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2356
