### ISSUE TITLE
Debugging multiple Function Apps at the same time

### ISSUE THREAD

**Issue by daniaghazal** [microsoft/vscode-azurefunctions#2374]
Is it possible to run and debug multiple activity function apps at once in VS Code? In other words, is it possible to attach 1 debugger to all (4) function apps? I haven’t seen details on this in Microsoft documentation.

Is the only way to do this is by opening (4) VS Code windows to run each function app individually? Which is not ideal..

**Comment by EricJizbaMSFT** [comment]
I've never tried 4 at once, but 2 at once should definitely work. See these docs:
https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

**Comment by EricJizbaMSFT** [comment]
Let us know if you need any more help with this
