### ISSUE TITLE
Error 500 when deploying Azure Durable Function to Azure in VSCode

### ISSUE THREAD

**Issue by MlleMargauxLedieu** [microsoft/vscode-azurefunctions#2376]
Does this occur consistently? Yes
Repro steps:
1. Try to deploy Azure Durable Functions app to Azure using the VSCode extension
2. It manages to create the zip package apparently and then stops. 

Used to deploy the app without problem. Impossible to do so in the last week. 

Action: azureFunctions.deploy
Error type: 500
Error Message: Failed with code "500".

Version: 0.24.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
extension.bundle.js:33:1087204
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by MlleMargauxLedieu** [comment]
OK, if I try to deploy it to a new app instance instead of the one that was working before I get this error : 
```
1:19:32 PM pa-deploy-test0909: A local file header is corrupt.
1:19:34 PM pa-deploy-test0909: Deployment failed.
```

No indication whatsoever on which file is corrupted..

**Comment by EricJizbaMSFT** [comment]
Is your project by chance open source on GitHub so I can take a look? I've never run into this issue before. I also don't have any more information than you do in terms of what file is corrupt. However, you might want to try Azure support (should be a help link in the portal). I'm guessing they have access to more detailed logs
