### ISSUE TITLE
Create new function app in VSCode

### ISSUE THREAD

**Issue by navidarry** [microsoft/vscode-azurefunctions#2377]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.0
OS: linux
OS Release: 5.3.18-lp152.36-default
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
extension.bundle.js:33:1087204
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@navidarry please add repro steps
