### ISSUE TITLE
Azure function deployment error from VS CODE

### ISSUE THREAD

**Issue by shawon017** [microsoft/vscode-azurefunctions#2381]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: Deployment '47d7a8359e11443db5fa49dc3ab4de8a' not found.

Version: 0.24.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
extension.bundle.js:33:1087204extension.bundle.js:33:1087204
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@shawon017 please add repro steps
