### ISSUE TITLE
Can't view function.json of QueueTrigger on Azure 

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurefunctions#2382]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.openFile
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "feedback2",
      "connection": "AzureWebJobsStorage"
    }
  ]
}.

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:74423
errorHandler extension.bundle.js:33:1085485
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
