### ISSUE TITLE
Should Typescript setup include dist folder in the .gitignore?

### ISSUE THREAD

**Issue by seed-of-apricot** [microsoft/vscode-azurefunctions#2383]
Because of this, 

https://github.com/microsoft/vscode-azurefunctions/blob/d1318cad6809dbe65029dfe2012c76a1b17d0df5/src/commands/createNewProject/ProjectCreateStep/JavaScriptProjectCreateStep.ts#L145-L147

The dist folder is not pushed to Git and thus the CD does not bring any files into Azure.

https://github.com/microsoft/vscode-azurefunctions/blob/d1318cad6809dbe65029dfe2012c76a1b17d0df5/src/commands/createFunction/scriptSteps/TypeScriptFunctionCreateStep.ts#L25

This `index.js` would not exist on Git repository. Shouldn't we remove this?

**Comment by EricJizbaMSFT** [comment]
@seed-of-apricot how are you doing CD? Typically CD is used in conjunction with CI - meaning you would build the project (creating the dist folder) on the remote build machine instead of committing it to git

**Comment by seed-of-apricot** [comment]
Indeed I was not using CI. I just set the deployment source from the VSCode extension and thought it's done.
My bad for an easy mistake.
