### ISSUE TITLE
 ENOTFOUND management.azure.com

### ISSUE THREAD

**Issue by tinydata01** [microsoft/vscode-azurefunctions#2384]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.23.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@tinydata01 please add repro steps - also check out the docs on [proxy support](https://code.visualstudio.com/docs/setup/network) in VS Code if you're behind a corporate proxy
