### ISSUE TITLE
Add Node 14

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2385]
* Allow creating an app in Azure with Node 14
* Publish an app to Azure with Node 14

Please use the latest version of Core Tools that should unblock Node 14: https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2996

 /cc @mhoeger

**Comment by fiveisprime** [comment]
This should be available on the platform soon and we'll have a plan within the next week on when this should show up as a preview language in the extension.

**Comment by anthonychu** [comment]
@fiveisprime Can we enable this during the week of Nov 2?

**Comment by anthonychu** [comment]
Available in Windows and Linux now. This is unblocked and ready to enable. Is it possible to get this out by Nov 9? @fiveisprime

**Comment by anthonychu** [comment]
@fiveisprime @EricJizbaMSFT Updated initial comment with more details. Thanks!
