### ISSUE TITLE
Constant ESOCKETTIMEDOUT exceptions in VS Code while debugging Azure functions

### ISSUE THREAD

**Issue by rgg-amahajan** [microsoft/vscode-azurefunctions#2386]
Does this occur consistently? Yes
Repro steps:
1. Start Debugging an Azure function in VS Code.

2. Within a few second, this exception pops up in right bottom.

Action: azureFunctions.executeFunction
Error type: ESOCKETTIMEDOUT
Error Message: ESOCKETTIMEDOUT

Version: 0.23.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RequestError extension.bundle.js:225:1105296
Request.callback extension.bundle.js:225:1103937
Request.RP$callback [as _callback] extension.bundle.js:225:1103383
n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
ClientRequest.<anonymous> extension.bundle.js:201:12972
Object.onceWrapper events.js:291:20
ClientRequest.emit events.js:203:13
ClientRequest.EventEmitter.emit domain.js:476:20
Socket.emitRequestTimeout _http_client.js:680:40
Object.onceWrapper events.js:291:20
Socket.emit events.js:203:13
Socket.EventEmitter.emit domain.js:476:20
Socket._onTimeout net.js:434:8
listOnTimeout timers.js:531:17
processTimers timers.js:475:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rgg-amahajan we provide an "Execute Function" command, but it should never be happening automatically. Are you doing the command from the command palette or in the tree?
![Screen Shot 2020-09-15 at 12 46 09 PM](https://user-images.githubusercontent.com/11282622/93257280-7379df80-f751-11ea-9697-ee95c45eb8e9.png)

In terms of _why_ it's failing, that depends on your local project. What language is it? And why type of function (http/blob/timer) are you trying to execute? Can you copy the logs here?

**Comment by rgg-amahajan** [comment]
I am clicking Execute function now exactly as you have shown.

It's a node js Azure function, and it has an http trigger.

Logs - can you check if Call Stack above in original issue has any info you need? Else please let me know where should I get the logs from.

new RequestError extension.bundle.js:225:1105296
Request.callback extension.bundle.js:225:1103937
Request.RP$callback [as _callback] extension.bundle.js:225:1103383
n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
ClientRequest.<anonymous> extension.bundle.js:201:12972
Object.onceWrapper events.js:291:20
ClientRequest.emit events.js:203:13
ClientRequest.EventEmitter.emit domain.js:476:20
Socket.emitRequestTimeout _http_client.js:680:40
Object.onceWrapper events.js:291:20
Socket.emit events.js:203:13
Socket.EventEmitter.emit domain.js:476:20
Socket._onTimeout net.js:434:8
listOnTimeout timers.js:531:17
processTimers timers.js:475:7

**Comment by EricJizbaMSFT** [comment]
A "terminal" pane should pop up on the bottom of your screen when you start debugging. For example, I see these logs:
```
> Executing task: npm install <

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN js4@1.0.0 No description
npm WARN js4@1.0.0 No repository field.
npm WARN js4@1.0.0 No license field.

up to date in 0.165s
found 0 vulnerabilities


Terminal will be reused by tasks, press any key to close it.

> Executing task: func host start <

Azure Functions Core Tools (3.0.2881 Commit hash: fa9641ad925588192888bc977ff51d8a63536267)
Function Runtime Version: 3.0.14287.0
Worker process started and initialized.
Hosting environment: Production
Content root path: /Users/erijiz/TestRepos/js4
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Functions:

        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1

For detailed output, run func with --verbose flag.
Host lock lease acquired by instance ID '00000000000000000000000000DB1A83'.
```
