### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by noelbr** [microsoft/vscode-azurefunctions#2388]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.24.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:39:9189
fulfilled extension.bundle.js:39:3146
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
