### ISSUE TITLE
Download Remote Settings prompts to overwrite AzureWebJobsStorage setting

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurefunctions#2389]
I don't have a `local.settings.json` file, but I'm still getting this prompt when I download remote settings.

![image](https://user-images.githubusercontent.com/5290572/93381011-e5ffc380-f814-11ea-8996-6fd47f72a761.png)

If I say yes, I get a value for `AzureWebJobsStorage`, but if I say no, it's an empty string.

I can confirm that this file did not exist prior to downloading.

![image](https://user-images.githubusercontent.com/5290572/93381141-0cbdfa00-f815-11ea-994b-65a03685d036.png)

**Comment by nturinski** [comment]
Never mind, this seems intentional based on `getLocalSettingsJson`.  Still seems like kind of a weird prompt though.

**Comment by EricJizbaMSFT** [comment]
Was not intentional. The `getLocalSettingsJson` stuff you saw was probably there for other code paths, not this one
