### ISSUE TITLE
failed, reason: read ECONNRESET - Deploy to Function App

### ISSUE THREAD

**Issue by ashokkrishna94** [microsoft/vscode-azurefunctions#2390]
Does this occur consistently?  Yes
Repro steps:
1. Create an azure function in VS Code
2. Make the required changed in __init__.py
3. Deploy to Function App from VS Code.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://kalinkaiaudiolowessdev.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.24.0
OS: linux
OS Release: 4.15.0-1095-azure
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by afmsavage** [comment]
I am getting this same error with a basic HTTP NodeJS function.  No matter what I try, this continues to fail.  I have tried to publish it to two different directories/subscriptions (not sure what is the difference with Azure tbh).  
WSL2 Windows 10
VSCode: 1.49.2
Node 12.14.1
Azure Functions Extension: v0.24.1

```10:03:33 PM: Creating resource group "findalltdts" in location "eastus"...
10:03:33 PM: Successfully created resource group "findalltdts".
10:03:33 PM: Creating storage account "findalltdts" in location "eastus" with sku "Standard_LRS"...
10:03:45 PM: Deleting function app "findTdts"...
10:03:49 PM: Successfully deleted function app "findTdts".
10:04:05 PM: Successfully created storage account "findalltdts".
10:04:05 PM: Verifying that Application Insights is available for this location...
10:04:06 PM: Creating Application Insights resource "findalltdts"...
10:04:09 PM: Successfully created Application Insights resource "findalltdts".
10:04:09 PM: Creating new function app "findalltdts"...
10:04:55 PM: Successfully created function app "findalltdts": https://findalltdts.azurewebsites.net
10:04:59 PM findalltdts: Starting deployment...
10:04:59 PM findalltdts: Creating zip package...
10:07:07 PM: Error: request to https://findalltdts.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
```

**Comment by Servot** [comment]
any update on this?

**Comment by shammelburg** [comment]
I was using Windows when creating my Node.js Azure Function and couldn't debug 
_"Error processing attach: Error: Could not connect to debug target at http://localhost:9229: Promise was cancelled"_

I switch to WSL2 and found that everything worked fine when it came to debugging. 

Come to deploy in WSL2 and I came across this same issue 
_Error: request to https://xxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET_

So... switched back to Windows and I was able to deploy.

It's not a great but it works if you need to deploy you Azure Function.

**Comment by ejizba** [comment]
Still trying to get a consistent repro on this. I tried on WSL2 since that seemed like a common theme, but it was working for me. Are you guys behind a corporate proxy by chance? Anything else you can think of that might be unique to your setup?

**Comment by g0josh** [comment]
This looks like a hit or a miss issue, I have experienced this a couple of times. Can't think of anything special in my setup.

**Comment by shammelburg** [comment]
> Still trying to get a consistent repro on this. I tried on WSL2 since that seemed like a common theme, but it was working for me. Are you guys behind a corporate proxy by chance? Anything else you can think of that might be unique to your setup?

Just a home setup.

Let me know what you need.

Windows 10 Pro
Version: 20H2
OS Build: 19042.630

WSL2 Ubuntu 20.04 LTS

VS Code - Azure Functions Extension - 1.0.1 - 2020-11-11

**Comment by teddyorkie** [comment]
I can't deploy azure function using VSCode either. Same error at trying to create zip package
```
2:03:26 AM monex-cloud-functions: Starting deployment...
2:03:27 AM monex-cloud-functions: Creating zip package...
2:05:32 AM: Error: request to https://monex-cloud-functions.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
```

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://monex-cloud-functions.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 1.0.1
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by wissamz** [comment]
Experiencing same issue. Cannot deploy Azure Functions using VSCode in WSL2.

1:41:15 PM useCaseOrchestrator: Stopping app...
1:41:18 PM useCaseOrchestrator: Starting deployment...
1:41:18 PM useCaseOrchestrator: Creating zip package...
1:43:26 PM useCaseOrchestrator: Starting app...
1:43:29 PM: Error: request to https://<removed>.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

**Comment by v-mengwe** [comment]
Experiencing same issue. Cannot deploy Azure Python Functions using VS Code in GitHub Codespaces.

![image](https://user-images.githubusercontent.com/62053665/102439218-d2086f80-4058-11eb-8736-6c681a762521.png)
```
3:04:18 AM elsa-bas-py36: Starting deployment...
3:04:19 AM elsa-bas-py36: Creating zip package...
3:06:24 AM: Error: request to https://elsa-bas-py36.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
```

**Comment by alenagruba** [comment]
Same here trying to deploy http-trigger Python 3 Function. 

WSL2 Ubuntu 20.04 LTS
VS Code - Azure Functions Extension - v1.1.0 - 2020-12-11

FA Configuration : 
FUNCTIONS_EXTENSION_VERSION : ~3
FUNCTIONS_WORKER_RUNTIME : python

**Comment by xwing316** [comment]
Same issue

WSL2 Ubuntu 20.04 LTS
VS Code - Azure Functions Extension - v1.1.0 - 2020-12-11

FA Configuration :
FUNCTIONS_EXTENSION_VERSION : ~3
FUNCTIONS_WORKER_RUNTIME : python

**Comment by lvovanms** [comment]
Same issue here, on Ubuntu (not WSL).
![image](https://user-images.githubusercontent.com/59864672/103403569-e4060a00-4b50-11eb-8342-2c69058af509.png)

**Comment by ikteru** [comment]
I had the same issue with VSCode in WSL2. However, I tried shutting down WSL2 using Powershell : 
`wsl --shutdown`
Then re-opened the vscode project from a new WSL2 terminal, then tried deploying. And it worked.

**Comment by pierfreeman** [comment]
> I had the same issue with VSCode in WSL2. However, I tried shutting down WSL2 using Powershell :
> `wsl --shutdown`
> Then re-opened the vscode project from a new WSL2 terminal, then tried deploying. And it worked.

Tried this workaround and it works!

**Comment by CircleMan** [comment]
I'm facing the same problem.

Environment:
remote development with VSCode (Windows10 -> Ubuntu 20.04)

If the deployment fails, try restarting VSCode. If you are lucky, it may work. It is strange.

**Comment by tjtoll** [comment]
Signing out and back in of Azure worked in my case.
