### ISSUE TITLE
ZIP Deploy Azure Function returns "Certificate has expired"

### ISSUE THREAD

**Issue by choellergit** [microsoft/vscode-azurefunctions#2391]
Does this occur consistently? Yes
Repro steps:

1. Deploy to already existing Azure Function

Action: azureFunctions.deploy
Error type: CERT_HAS_EXPIRED
Error Message: request to https://[our project].scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: certificate has expired

Version: 0.24.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

Not sure which cert is the issue. Tried with and without Proxy and in different networks.

**Comment by EricJizbaMSFT** [comment]
Did you already take a look at VS Code's proxy docs: https://code.visualstudio.com/docs/setup/network

I can't repro with those steps alone - I would need more detail to investigate
