### ISSUE TITLE
The Node version is inconsistent between the Windows and Linux Function Apps

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2397]
**OS:** All
**Build Version:** 20200916.1

**Repro Steps:**

1. Create a Node.js project with a basic Http Trigger.
2. Modify the index.js to be something like this:
   ```
   module.exports = async function (context, req) {
         context.log('JavaScript HTTP trigger function processed a request.');
         context.res = {
	       body: `Node Version: ${process.version}`
         };
   };
   ```	
3. Deploy the project to a Linux and Windows Node.js 10 Function App.
4. Expand the Function App -> Functions Node -> Copy the URL of the function. 
5. Verify the runtime version.

**Expect:**
The Node version is consistent between the Windows and Linux Function Apps.

**Actual:**
The Node version is inconsistent between the Windows and Linux Function Apps.
![image](https://user-images.githubusercontent.com/62053665/93550742-a5cc4c80-f99e-11ea-9ace-394cc6018c0d.png)

**More info:**
This issue also reproduces for a Linux/Windows Node.js 12 Function App.
Runtime | Linux | Windows
-- | -- | --
Node.js   10 | 10.22.0 | 10.19.0
Node.js   12 | 12.18.3 | 12.18.0

**Comment by EricJizbaMSFT** [comment]
The platform team controls the exact versions and slight discrepancies are okay. It's only a bug from our side if the major version doesn't match what the user selected
