### ISSUE TITLE
unable to deploy azure function

### ISSUE THREAD

**Issue by Sourav692** [microsoft/vscode-azurefunctions#2398]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/4d234c66-2a75-4356-b6f6-bafda6246dc9/locations?api-version=2016-06-01 failed, reason: connect ETIMEDOUT 20.38.128.32:443

Version: 0.24.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
