### ISSUE TITLE
I am facing this error while deploying azure function code from visual studio code

### ISSUE THREAD

**Issue by AbhiRathore** [microsoft/vscode-azurefunctions#2399]
Does this occur consistently? Yes
Repro steps:

1. Create a function in visual studio code
2. deploy that to some azure function

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://audiollessentia-trial.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.24.0
OS: linux
OS Release: 4.15.0-1082-azure
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.

**Comment by abhijitnathwani** [comment]
Even I'm facing issues with this extension. The function app does not populate while executing the command `Azure Functions: Deploy to Function App`. It takes forever to load and still does not populate the list to select the function. I can confirm the internet is working fine and the Azure IoT Hub extension is able to get the device list.

**Comment by nturinski** [comment]
@abhijitnathwani Are you using the command palette for making these calls?  If you go into the Azure view, it should load up the resources ahead of time.  Between activating the extension and making the API calls to Azure to retrieve the resources, it can definitely be quite the wait depending on your connection.

I think if you just go into the Azure view and try to deploy from there, your experience might be better.

**Comment by abhijitnathwani** [comment]
@nturinski Thank you for the update. Yep,  I can now view my functions from Azure view. However, when deploying, it throws socket hang up error while deploying the zip. Any ideas there?

**Comment by alexweininger** [comment]
Consolidating issues with deployments here https://github.com/microsoft/vscode-azurefunctions/issues/2844
