### ISSUE TITLE
Cannot create a new function app

### ISSUE THREAD

**Issue by Darko-git** [microsoft/vscode-azurefunctions#2403]
Does this occur consistently? 100% of the time (tried once)
Repro steps:
Deploy to a new function app (advanced) using Visual Studio Code.

Looks like the whole cloud explorer is broken, refresh does nothing and I do not see how to sign out - all subs look like this.
![image](https://user-images.githubusercontent.com/5216705/93720858-c59b7600-fb40-11ea-9174-0cc16fecbdce.png)

Restarting VS Code fixes this.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:74686extension.js:243:74686
extension.js:243:72667extension.js:243:72667
extension.js:243:72287extension.js:243:72287
i.find extension.js:243:106819
extension.js:243:53526extension.js:243:53526
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by Darko-git** [comment]
Just a note that I deployed to an existing app successfully, broke it somehow, removed the app in Portal and tried to deploy from VS Code to a new app.

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
