### ISSUE TITLE
Adding target platform does not change publish profile

### ISSUE THREAD

**Issue by Darko-git** [microsoft/vscode-azurefunctions#2404]
Does this occur consistently? Yes
Repro steps:
1. Create new function app
2. Deploy to Azure
3. Change target platform to x64 (Add Platform element to .csproj file)
4. Try to deploy - no changes are deployed
5. Clean bin directory
6. Try to deploy

Build is in x64, but publishing profile is still somehow pointing to the default location.
I do not know what needs to be done to tell VS Code which build to deploy, I thought that would be automatic.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: d:\Dev\Projects\local\Functions\bin\Release\netcoreapp3.1\publish

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1009:26730
fulfilled extension.bundle.js:1009:26222
```

</details>

**Comment by Darko-git** [comment]
Workaround is - clean manually (delete obj/bin), deploy, fail, copy Release from bin/x64/ into bin/, deploy again

There must be a better way.

**Comment by EricJizbaMSFT** [comment]
@Darko-git This is  controlled by the "azureFunctions.deploySubpath" setting in `.vscode/settings.json`

**Comment by Darko-git** [comment]
Thank you - I think that the extension should update the target platform at destination as well. I found the setting in Azure Functions General Settings.
