### ISSUE TITLE
Region issues

### ISSUE THREAD

**Issue by chimerashashi** [microsoft/vscode-azurefunctions#2406]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.24.1
OS: linux
OS Release: 5.4.0-47-generic
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please try creating your function app in a different region.  If this still doesn't work, please provide detailed repro steps.
