### ISSUE TITLE
Unable to publish azure function

### ISSUE THREAD

**Issue by ramesh586** [microsoft/vscode-azurefunctions#2407]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: PARSE_ERROR
Error Message:  500 - The request timed out.
The web server failed to respond within the specified time.

Version: 0.24.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
errorHandler extension.bundle.js:48:1289404
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
