### ISSUE TITLE
Fail to create a function app which created with Premium hosting plan and name contains two hyphens in a row

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2408]
**OS:** Win10
**Build Version:** 202009.23.3

**Repro Steps:**

1. Create an advanced Premium Function App with name contains two hyphens in a row, e.g. "test--test".
2. Check the result.

**Expect:**
Succeed to create the function app without any error.

**Actual:**
Fail to create the function app with an error.
![image](https://user-images.githubusercontent.com/62053665/93991969-8a5aaa80-fdbf-11ea-9baf-d328c1a21bab.png)

**More Info:**
This issue doesn't reproduce when creating a Consumption/App Service Function app with name contains two hyphens in a row.

**Details of Output:**
Action: azureFunctions.createFunctionAppAdvanced
Error type: BadRequest
Error Message: There was a conflict. The remote server returned an error: (400) Bad Request.

Version: 0.24.2-alpha
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.50.0-insider
Language: en

**Comment by v-ruizh** [comment]
This issue also reproduces on the functions extension build 20200924.1.
