### ISSUE TITLE
500 Error on deploying

### ISSUE THREAD

**Issue by nogorilla** [microsoft/vscode-azurefunctions#2409]
Does this occur consistently? Yes
Repro steps:

1. Click Deploy to Function app in the Azure explorer pane
2. Select the targeted function
3. Click "Deploy" on the dialog box

Action: azureFunctions.deploy
Error type: 500
Error Message: Failed with code "500".

Version: 0.24.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
We can't repro with those steps alone - please add more detail for your specific situation

**Comment by nogorilla** [comment]
I think this is actually due to account permissions in Azure. I will close this, thanks.
