### ISSUE TITLE
C# tutorial function does not run locally on Mac

### ISSUE THREAD

**Issue by moczkowski** [microsoft/vscode-azurefunctions#2413]
Following the instructions to create from scratch the example function in the README using C# with VSC on Mac with latest .NET SDK, Azure Functions Core Tools, C# extension, and Azure Functions extension installed fails to run the function locally. Running the same example works on Windows.

Everything is created as expected but when hitting run in the functions extension window (or F5) this occurs:
execvp(3) failed.: No such file or directory
The terminal process "dotnet 'clean', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1).

Interestingly, if I drop into a Terminal window and do "func host start" the function runs properly but I cannot debug it (breakpoints aren't hit). Also in the Functions extension window in the folder it doesn't show the URL even though it is running, instead it says "Run build task to update this list".

**Comment by EricJizbaMSFT** [comment]
Seems like the dotnet build/clean tasks are failing. Is `dotnet` on your path? What version? Try running `dotnet --version` and `dotnet build` in a terminal window

**Comment by moczkowski** [comment]
.NET version: 3.1.402
PATH includes :/usr/local/share/dotnet:~/.dotnet/tools
I can clean/build/run function tasks from the terminal window

**Comment by EricJizbaMSFT** [comment]
Please copy the full clean/build/run logs if your still having problems with this

**Comment by moczkowski** [comment]
The issue arose from a VSCode Setting:
`"terminal.integrated.inheritEnv": false`
as discovered from this issue: [https://github.com/OmniSharp/omnisharp-vscode/issues/3447](url)
changing the above setting to true fixed the problem
