### ISSUE TITLE
C# FunctionStartup - Debugging - Breakpoint warning: No executable code of the debugger’s target code type is associated with this line.

### ISSUE THREAD

**Issue by acds** [microsoft/vscode-azurefunctions#2414]
When debugging a C# Azure Function, with a FunctionStartup in Visual Code on MacOS with the 

VS Code
```log
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Visual code - AzureFunction `0.24.1` add-in
Azure Functions Core Tools - `3.0.2912`
Function Runtime: `3.0.14287.0`

I'm unable to debug my `FunctionsStartup:Configure` override

```C#
[assembly: FunctionsStartup(typeof(MyAssembly.Startup))]

namespace MyAssembly.Startup
{
    public class Startup : FunctionsStartup
    {
        public Startup()
        {
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
...   // <-- Break points in here.
       }
   }
}
```

On startup I get the following warnings:
```log
Breakpoint warning: No executable code of the debugger’s target code type is associated with this line.
Possible causes include: conditional compilation, compiler optimizations, or the target architecture of this line is not supported by the current debugger code type. - /<Path to my code>/<MyAssembly>/Startup.cs:41
```

My `launch.json` look like this:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}",
            "requireExactSource": false,
            "stopAtEntry": true
        }
    ]
}
```
However the `"stopAtEntry": true` is underlined to say `property is not allowed`.

**Comment by EricJizbaMSFT** [comment]
Just to be clear - this is only an issue for the Configure/Startup stuff, right? You can get breakpoints for something simple like an Http Trigger?

Is this project on GitHub? Could I see how you're using the Configure method in context?

**Comment by acds** [comment]
@EricJizbaMSFT - Hi Eric - yes this is just with the [FunctionStartup](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection). I get the Breakpoints to work fine elsewhere.

My use cases here is to connect to an Azure KeyVault but the code here should not matter...I was just trying to debug it.

I assume creating a template project and adding in a FunctionStartup method with the requisite assembly Reference should be a re-create-able use case.

My guess its that it's released to the Assembly Reference and VS Code's understanding of that ?
```C#
[assembly: FunctionsStartup(typeof(MyAssembly.Startup))]
```

**Comment by chunliu** [comment]
I hit the similar issue with VS Code, but I didn't see the breakpoint warning. The breakpoint in the Startup simply doesn't work. I am using VS Code with WSL2. 

The breakpoint works in Visual Studio with the same code.

The function code is here if you want to have a quick try: https://github.com/chunliu/azfunc-snowflake

**Comment by johndowns** [comment]
Tagging @stefanushinardi for visibility.
