### ISSUE TITLE
Not able to deploy azure function from visual code

### ISSUE THREAD

**Issue by nimishmehta8779** [microsoft/vscode-azurefunctions#2416]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://keyvault1979.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.24.1
OS: linux
OS Release: 4.4.0-19041-Microsoft
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
ClientRequest.EventEmitter.emit domain.js:475:20
TLSSocket.socketOnEnd _http_client.js:440:9
TLSSocket.emit events.js:228:7
TLSSocket.EventEmitter.emit domain.js:475:20
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2390#issuecomment-699746354
