### ISSUE TITLE
unable to create function app from visual studio code

### ISSUE THREAD

**Issue by ChiranjeeviKandukuri** [microsoft/vscode-azurefunctions#2417]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.24.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:54:9191
fulfilled extension.bundle.js:54:3146
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
