### ISSUE TITLE
Fail to create a Premium Linux Function App with "Brazil South" location

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2418]
**OS:** Win10/Mac
**Build Version:** 20200925.5

**Repro Steps:**

1. Create a Premium Linux Function App with the "Brazil South" location.
2. Check the result.

**Expect:**
Succeed to create the function app.

**Actual:**
Fail to create the function app.
![image](https://user-images.githubusercontent.com/57662131/94356986-7072dd80-00c7-11eb-919b-1dc77b0e64a2.png)
Details in Output:
```
10:38:59 AM: Creating resource group "nicole0023" in location "brazilsouth"...
10:39:02 AM: Successfully created resource group "nicole0023".
10:39:02 AM: Ensuring App Service plan "nicole0023" exists...
10:39:03 AM: Creating App Service plan "nicole0023"...
10:39:14 AM: Error: The pricing tier 'ElasticPremium' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764
```

**More Info:**
1. This issue doesn't reproduce when creating a Premium Windows Function App with "Brazil South" location.
2. This issue doesn't reproduce when creating a Consumption/App Service Plan Function App with "Brazil South" location.

**Comment by EricJizbaMSFT** [comment]
There's some known limitations regarding premium plans - see the link mentioned in the error:
https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group

The error message should be enough in this case - it would be difficult for us to prevent this ahead of time
