### ISSUE TITLE
[Suggestion] Change the "," of the python version to "." in the Output window

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2419]
**OS:** All
**Build Version:** 20200925.5

**Repro Steps:**
1. Create a new Python project.
2. Modify the __init_.py_ file like below.
`import logging`
	`import sys`
	`import azure.functions as func`
	
	`def main(req: func.HttpRequest) -> func.HttpResponse:`
	`logging.info('Python HTTP trigger function processed a request.')`
	`return func.HttpResponse(`
	`f"Python Version: {sys.version_info[0]}.{sys.version_info[1]}",`
	status_code=400
	`)`
3. Deploy this project to a function app.
4. Query the http trigger after finishing deployment.
5. Verify the result. 

**Actual:**
Display the python version 3,7 in the Output window.
![image](https://user-images.githubusercontent.com/57662131/94360608-2c8cd200-00e1-11eb-90cc-fa25a7787be0.png)

**Suggestion:**
Change the "," of the python version to "." in the Output window. Such as Node version:
![image](https://user-images.githubusercontent.com/57662131/94361192-141eb680-00e5-11eb-9cb0-52a7ad7291cc.png)

**Comment by EricJizbaMSFT** [comment]
This line of code controls what is output:
`f"Python Version: {sys.version_info[0]}.{sys.version_info[1]}",`

If you use a period there, it should have a period when you hit the trigger. Maybe you typed a comma on accident? Either way, this is probably a bug with the code itself, not the extension
