### ISSUE TITLE
[Feature Request] Adding "Easy Create" flow to add Binding/Trigger experience

### ISSUE THREAD

**Issue by stefanushinardi** [microsoft/vscode-azurefunctions#2420]
Based on our usability study, we found that Day-0 Azure Functions users face significant issues in trying out Triggers and Bindings that require other resources to be created first(i.e. CosmosDB) . To remove this pain point, it would be great to have the option to create resources with default configuration.

Currently, users could already create/provision azure storage resources through VS Code experience, however, other trigger and binding types support is currently missing. 

The flow that we are thinking is something along this line:
![Proposed flow](https://user-images.githubusercontent.com/5436734/94466891-fd28a480-0176-11eb-9a05-82b382b948e0.png)

The Easy Create flow would allow users to create the resources that are needed with only providing as little information/configuration as possible. 

 In order of the popularity as well as complexity, it would be great to start rolling out support for:
•	CosmosDb
•	ServiceBus
•	EventHub
•	SignalR
•	EventGrid

**Comment by fiveisprime** [comment]
In short, this should walk through the setup and creates the files then creates the resources asynchronously in the background while the customer is able to view the files.

Inline creation of Cosmos DB will be the first iteration. Once we get some insights on how many customers create inline, we can determine how much we should invest in additional resource providers.

The only step that changes is the selection of the binding resource and the following should be considered

* Once the binding creation flow is complete, launch a long-running notification
    * >"Creating {resource, name,} do not close or reload VS Code until creation completes."
* Create placeholder connection information in the config files that signals when a resource creation didn't complete so this can be picked back up when relaunched
