### ISSUE TITLE
Issue Create Function

### ISSUE THREAD

**Issue by rquirogagUcentral** [microsoft/vscode-azurefunctions#2421]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3" command. Check output window for more details.

Version: 0.24.1
OS: linux
OS Release: 4.19.0-10-amd64
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:48:71496
fulfilled extension.bundle.js:48:70379
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please check the output window and add repro steps if that doesn't help
