### ISSUE TITLE
Publish successful but not reflected in portal init.py file

### ISSUE THREAD

**Issue by afelthe** [microsoft/vscode-azurefunctions#2426]
Hello,
I have created an Azure Function and successfully deployed it from VS Code.  But when I view it in the Azure Portal, my code is not reflected.  The dummy template code is there.  How do I get the portal to pick up the code I am deploying to it from VS Code?
Regards,
Amy

**Comment by EricJizbaMSFT** [comment]
Please add more repro steps, including what language your project is, what triggers you used, and how you created the function app
