### ISSUE TITLE
Problem deploying function app from VsCode

### ISSUE THREAD

**Issue by Elham-N** [microsoft/vscode-azurefunctions#2427]
Does this occur consistently? Yes
Repro steps:

Deploying Python function app from VsCode throws ServiceUnavailable error for the previous couple of days. Have tried different app service plans as well as different function apps. It was working before.
The deployment stops at Synching Triggers step

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.24.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123extension.bundle.js:48:1291123
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Is your project open source by chance? Can you send a GitHub link? It may be related to something in your project...

Otherwise, here are some troubleshooting tips: https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503

**Comment by Elham-N** [comment]
> Is your project open source by chance? Can you send a GitHub link? It may be related to something in your project...
> 
> Otherwise, here are some troubleshooting tips: https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503

Thanks,
It got resolved after a few days.
