### ISSUE TITLE
python3 not recognizing in visual code for azure function as runtime environment

### ISSUE THREAD

**Issue by nimishmehta8779** [microsoft/vscode-azurefunctions#2437]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "/usr/bin/python3" command. Check output window for more details.

Version: 0.23.0
OS: linux
OS Release: 5.3.0-64-generic
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:134212
fulfilled extension.bundle.js:1:133095
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps, including the output mentioned in the error message

**Comment by v-mengwe** [comment]
**OS:** Linux
**Build Version:** 20201015.3
**Python Version:** 3.8.6

**Repro Steps:**

1. F1 -> Type and select "Create New Project..." -> Select a blank folder -> Select "Python" language -> Select “python3.8” to create a project.
2. Check the result.

**Expect:**
Succeed to create a python project.

**Actual:**
Fail to create a python project.
![image](https://user-images.githubusercontent.com/62053665/96449013-cf4ef100-1246-11eb-95c0-74131cdc38c1.png)
