### ISSUE TITLE
deployment azure function

### ISSUE THREAD

**Issue by mvignoli** [microsoft/vscode-azurefunctions#2438]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://readinfotable.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.24.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketOnEnd _http_client.js:440:9
TLSSocket.emit events.js:228:7
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2390
