### ISSUE TITLE
Run azure function in visual code subsystem linux

### ISSUE THREAD

**Issue by EugeneRodolphe** [microsoft/vscode-azurefunctions#2446]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python3" command. Check output window for more details.

Version: 0.24.1
OS: linux
OS Release: 4.4.0-19041-Microsoft
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:48:71496
fulfilled extension.bundle.js:48:70379
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps and the logs mentioned in the output window
