### ISSUE TITLE
Error during function deployment

### ISSUE THREAD

**Issue by sroy0101** [microsoft/vscode-azurefunctions#2447]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://management.azure.com/subscriptions/c8aecba6-27f9-4df2-a8d0-5c9bae6da66b/providers/Microsoft.Storage/locations/eastus/asyncoperations/3f62c4ab-4cbd-4e9f-a2bf-890adf7e4aef?monitor=true&api-version=2019-06-01 failed, reason: read ECONNRESET

Version: 0.24.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by sroy0101** [comment]
Happened only once.

**Comment by EricJizbaMSFT** [comment]
If this happens more often, let us know the repro steps and we can investigate at that point

Related to https://github.com/microsoft/vscode-azurefunctions/issues/2390
