### ISSUE TITLE
Application setting value does not support several Double Chinese characters

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2449]
**OS:** Win10
**Build Version:** 20201009.2
**Language for GB18030:** Double Chinese

**Repro Steps:**
1. Add a new application setting, copy the below Double Chinese character as the app setting value. (GB18030 code: 0xFEA0)
![image](https://user-images.githubusercontent.com/45614674/95567597-bc256f80-0a55-11eb-9397-a3941dfaf47f.png)
2. Check the value.

**Expect:**
The value shows well.

**Actual:**
The value shows as a "".
![image](https://user-images.githubusercontent.com/45614674/95568008-4968c400-0a56-11eb-9053-b7a30c317576.png)

**More Info:**
This issue does not reproduce for other Double Chinese characters "丂丄龞龥㑳䶮".

**Comment by v-xinda** [comment]
1. This issue reproduces when adding a new application setting for the function app.
2. The Dianbei Miao "𖼁𖼤𖼬𖼶𖼵𖼇" shows "[][][][][][]" after pasting in input box.

![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/2b149aa4-746f-4f9c-b089-58648306c979)
