### ISSUE TITLE
Deployment on azure function failed with message-->Failed with code "400".

### ISSUE THREAD

**Issue by sh1kh4r** [microsoft/vscode-azurefunctions#2450]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 400
Error Message: Failed with code "400".

Version: 0.24.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123extension.bundle.js:48:1291123
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
