### ISSUE TITLE
An error "No such file or directory" occurs after clicking "Install" during creating the Python project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2459]
**OS:** Windows 10
**Build:** 20201011.1

**Repro Steps:**
1.  Click "Create New Project..." --> Select a folder --> Select the Python language --> Select a Python interpreter --> Select "HTTP Trigger" template --> Enter a function name --> Select "Anonymous" --> Open in current window.
2.  Click "Install" when prompting a dialog.
3. Check the result.

**Expect:**
There is no error.

**Actual:**
An error "No such file or directory" occurs.
![image](https://user-images.githubusercontent.com/57662131/95727150-6565a300-0cac-11eb-90f0-cadf39814b0c.png)
Details in Terminal:
```
vxinda005+AzureTest@vxinda005 MINGW64 ~/Desktop/python (master)
$ c:/Users/AzureTest/Desktop/python/.venv/Scripts/python.exe c:\Users\AzureTest\.vscode-insiders\extensions\ms-python.pytho
n-2020.9.114305\pythonFiles\pyvsc-run-isolated.py pip install -U pylint
C:\Users\AzureTest\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'c:UsersAzureTest.vscode-insidersextensionsms-python.python-2020.9.114305pythonFilespyvsc-run-isolated.py': [Errno 2] No such file or directory
(.venv) 
```
**More Info:**
This file is existent.
![image](https://user-images.githubusercontent.com/57662131/95727945-7367f380-0cad-11eb-8d00-01a41acac8c1.png)

**Comment by EricJizbaMSFT** [comment]
@v-xinda what are you using for your terminal? It doesn't look like PowerShell or Command Prompt in the screenshots

**Comment by v-xinda** [comment]
I'm sorry to submit a confusing issue. Verified this issue on latest build with Command Prompt, it doesn't reproduce. So close it.
