### ISSUE TITLE
Disconnect the debugger automatically when debugging the PowerShell project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2460]
**OS:** Windows 10
**Build:** 20201011.1

**Repro Steps:**
1.  Create a PowerShell project and open in VS Code.
2.  Set a breakpoint and debug it.
3. Check the result.

**Expect:**
The debugger doesn't disconnect automatically.

**Actual:**
Disconnect the debugger automatically.

**More Info:**
This issue doesn't reproduce for JavaScript/TypeScript/C# project.

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/Azure/azure-functions-powershell-worker/issues/538
