### ISSUE TITLE
Just deploy from VSCode

### ISSUE THREAD

**Issue by SuperKMan** [microsoft/vscode-azurefunctions#2463]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.24.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:74686extension.js:243:74686
extension.js:243:72667extension.js:243:72667
extension.js:243:72287extension.js:243:72287
i.find extension.js:243:106819
extension.js:243:53526extension.js:243:53526
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
