### ISSUE TITLE
Just debugging my app. No idea why it happened. 

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/vscode-azurefunctions#2466]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.24.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1000:129850extension.bundle.js:1000:129850
fulfilled extension.bundle.js:1000:127272
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
