### ISSUE TITLE
Functions using Event Grid based template fail to get created in VS Code

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/vscode-azurefunctions#2467]
Does this occur consistently? YES
Repro steps:

1. Choose to create a new C# function using the Event Grid template
2. This error pops up

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\amang\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.24.1\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\amang\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\amang\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~2.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name "EventGridFunc" --arg:AzureFunctionsVersion v2" failed with exit code "2147614729":
{
  "Message": "Error while processing file /content/ProjectTemplate-CSharp/_gitignore\r\nCould not find file 'c:\\Users\\amang\\Documents\\Visual Studio 2019\\Projects\\EventGridFunc\\.gitignore'.",
  "Status": -2147352567,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}

Version: 0.24.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:48:71616
fulfilled extension.bundle.js:48:70379
processTicksAndRejections task_queues.js:94:5
```

**Comment by EricJizbaMSFT** [comment]
I've never run into an error like this myself. It's a bit odd to me that it's looking in the "Visual Studio 2019" folder in the error message. Do you switch between VS and VS Code when working on Functions? Have you installed the Azure Functions templates manually using the `dotnet` cli? I feel like this is related to some sort of compatibility matrix on your machine. We could double check we work when VS functions tooling is installed, but any more info you have would be helpful

**Comment by iamalexmang** [comment]
Might as well be - I just tried it from a different machine and first step was to update the tooling to ensure I'm using the latest and the greatest.
Interestingly though, the Event Grid template seems to no longer be part of the templates available OOBE. Is this just me?
Here's a screen recording of what I'm seeing - despite the 'All' filter, Event Grid seems to be missing entirely now.
I'll take another screen record of the experience I'm seeing on other machines for debugging purposes. Hopefully this helps.
![Presentation1](https://user-images.githubusercontent.com/5773281/96516519-fe2d8d00-126f-11eb-9434-1337c82b7e51.gif)

**Comment by iamalexmang** [comment]
To clarify, this is about VS Code - the function can be successfully create via the func CLI.

**Comment by EricJizbaMSFT** [comment]
There's a known issue for the EventGrid template if you're running func v2 https://github.com/Azure/azure-functions-templates/issues/915

It should show up under the "All" filter for func v3

**Comment by iamalexmang** [comment]
(should be up under the "All" filter for func v3) --> Which would explain why I'm seeing it on other machines - those have func v3 installed. Let me get func v3 installed on this machine too and get back to you with results.
