### ISSUE TITLE
Misnamed Variable in Python Event Hub template

### ISSUE THREAD

**Issue by adiazulay** [microsoft/vscode-azurefunctions#2468]
When creating a new function in VS Code the function.json and __init__.py files have a mismatched variable.

The name ("event") in the json should match the argument (events) in ```def main```

```json
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "event"
```
```python
def main(events: List[func.EventHubEvent]):
    for event in events:
        logging.info('Python EventHub trigger processed an event: %s',
                        event.get_body().decode('utf-8'))
```

**Comment by EricJizbaMSFT** [comment]
This is tracked in https://github.com/Azure/azure-functions-templates/issues/971, and appears there's even an open PR https://github.com/Azure/azure-functions-templates/pull/972
