### ISSUE TITLE
Error when opening function.json in VS Code

### ISSUE THREAD

**Issue by TJ-Dev** [microsoft/vscode-azurefunctions#2469]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.openFile
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    }
  ]
}.

Version: 0.24.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
errorHandler extension.bundle.js:48:1289404
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
