### ISSUE TITLE
Deploying a Node function silently fails

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode-azurefunctions#247]
When trying to deploy my function for the first time from VS Code, the process successfully starts but at some point silently fails without outputting any useful information:

```
01:48:20 project-name: Creating zip package...
01:48:36 project-name: Starting deployment...
>>>>>> Deployment to "project-name" completed. <<<<<<
```

Afterwards, the Azure Portal shows no sign of the Function.
Trying to use the CLI yields a similar result, this time at least with an error message:
```
$ func azure functionapp publish project-name
Publish /Users/lukas/Dev/project-name contents to an Azure Function App. Locally deleted files are not removed from destination.
Getting site publishing info...
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
Retry: 1 of 2
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
Retry: 2 of 2
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
```

**Comment by EricJizbaMSFT** [comment]
@lumaxis any chance you could give us a simple project that reproduces this? How did you create your function?

**Comment by EricJizbaMSFT** [comment]
We just released an update that has much more detailed deployment logs. See [this PR](https://github.com/Microsoft/vscode-azuretools/pull/106) for more info. Closing this, but feel free to re-open if it doesn't help your scenario.
