### ISSUE TITLE
While deploying the project. 

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/vscode-azurefunctions#2470]
Does this occur consistently? No

Repro steps:
I just deployed a project (Azure Function) that I've deployed multiple times before. 

Action: azureFunctions.deploy
Error type: REQUEST_SEND_ERROR
Error Message: request to https://sdrstoreleveltransactions.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: getaddrinfo ENOTFOUND sdrstoreleveltransactions.scm.azurewebsites.net

Version: 0.24.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
NodeFetchHttpClient.<anonymous> extension.bundle.js:1000:417447
step extension.bundle.js:16:1925
Object.throw extension.bundle.js:16:2030
rejected extension.bundle.js:16:755
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Let us know if you get consistent repro steps. Otherwise, it'll be difficult for us to investigate this - probably an intermittent error related to Azure or your internet
