### ISSUE TITLE
No dialog pops up to confirm deployment after configuring deployment source with "LocalGit"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2474]
**OS:** All
**Build Version:** 20201015.3

**Repro Steps:**
1. Create a new Function App.
2. Right click the function app --> Select "Configure Deployment Source..." --> Select "LocalGit".
3. Deploy a project which Initialized the LocalGit repository to it.
4. Check the result.

**Expect:**
Pop up a dialog to confirm deployment.

**Actual:**
No dialog pops up to confirm deployment.

**Comment by EricJizbaMSFT** [comment]
This is by design. Local Git keeps a history of your previous deployments/commits, so you can easily switch back to them if you want. We only use a confirmation prompt if you can't undo something
