### ISSUE TITLE
The result about the setting which can't be a slot setting is different after executing "Delete Setting..." command

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2476]
**OS:** All
**Build Version:** 20201015.3

**Repro Steps:**
1. Expand a Function App --> Expand the "Application Settings" node.
2. Right click the "WEBSITE_CONTENTSHARE" and "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" setting --> Toggle as Slot Setting.
3. Pop up a error message "'xxx' cannot be a slot setting".
4. Right click the "WEBSITE_CONTENTSHARE" and "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" setting --> Click "Delete Setting...".
5. Check the result.

**Expect:**
Keep the result consistently.

**Actual:**
The "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" setting can't be deleted, but the "WEBSITE_CONTENTSHARE" setting can be deleted successfully.

**Comment by EricJizbaMSFT** [comment]
The error you mentioned in step 3 is coming directly from Azure, not us. We will leave it to them to keep their error messages consistent regarding these settings
