### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by widadistt** [microsoft/vscode-azurefunctions#2483]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ServerTimeout
Error Message: The request timed out. Diagnostic information: timestamp '20201019T213333Z', subscription id '', tracking id 'ade73edc-986c-425a-8c94-3e119d4a434a', request correlation id 'ade73edc-986c-425a-8c94-3e119d4a434a'.

Version: 0.24.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new t extension.js:16:40769
extension.js:166:90140extension.js:166:90140
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
