### ISSUE TITLE
How to deploy Node.js using the plugin with Webpack (or similar)

### ISSUE THREAD

**Issue by chearmstrong** [microsoft/vscode-azurefunctions#2486]
Hi. I'm pretty new to Azure, so apologies if there is an obvious answer to this question...

If I want to use Webpack (or similar) to create a single file bundle (with tree-shaking and minification, etc), how can I deploy using this plugin.

Also, I have read about _run from package_ - does using something like Webpack still work with this? If so, is there a way to set this option in my code/config or can I only set this manually after deploying?

Thanks in advance.

**Comment by EricJizbaMSFT** [comment]
The Functions team had this [old tool](https://github.com/Azure/azure-functions-pack) that was replaced with the "Run from Package" stuff you were talking about. Check out this issue for more discussion: https://github.com/Azure/azure-functions-pack/issues/84

In terms of our VS Code extension, you can definitely customize it, but I don't have any examples for webpack. There's a few settings to be aware of, all in the `.vscode/settings.json` file. The "azureFunctions.deploySubpath" setting controls what we deploy, defaulted to the root of the repo for JavaScript. The "azureFunctions.preDeployTask" controls what task to run before deploying, which you can configure to be whatever you want (for example, maybe a webpack task).

**Comment by chearmstrong** [comment]
@EricJizbaMSFT Thanks for the info - that's really useful.
