### ISSUE TITLE
Can not deploy a function

### ISSUE THREAD

**Issue by juanferrs** [microsoft/vscode-azurefunctions#2487]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN management.azure.com

Version: 0.23.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
