### ISSUE TITLE
issues opening function.json in vs code

### ISSUE THREAD

**Issue by RyanVoigt** [microsoft/vscode-azurefunctions#2490]
Does this occur consistently? 
Repro steps:

1. Create new HTML Function
2. Open in VS code and go to Files -> FunctionName -> function.json

you will get an error, I believe the default function they supply has a weird invisible character at the start but i can't seem to find it or remove it

Action: azureFunctions.openFile
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿{
  "bindings": [
    {
      "authLevel": "function",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ]
}.

Version: 1.0.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
errorHandler extension.bundle.js:48:165914
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
This should be fixed by https://github.com/microsoft/vscode-azuretools/pull/845
