### ISSUE TITLE
Not able to create a new azure function with python in VS code  

### ISSUE THREAD

**Issue by Farhana2909** [microsoft/vscode-azurefunctions#2496]
Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "python" command. Check output window for more details.

Version: 1.50.1
OS: win64
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

Error : C:\\fff\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 101. 
Error: **Failed to run "python" command. Check output window for more details.**

```
Object.<anonymous> extension.bundle.js:46:75013
fulfilled extension.bundle.js:46:73879
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Farhana2909 please check the output window for more info - you can even try running the command listed there manually and see if you hit the same problem. If none of that works, add more detailed repros steps and the full logs here

**Comment by Farhana2909** [comment]
Thanks so much
Got my issue resolved
