### ISSUE TITLE
Cannot create a new function app project in visual studio code using Python

### ISSUE THREAD

**Issue by NvHeijningen** [microsoft/vscode-azurefunctions#2501]
I cant make a new project anymore. I could before but now not anymore.

1. create a new function app project clicking on the "create new project" icon
2.

Action: azureFunctions.createNewProject
Error type: EPERM
Error Message: EPERM: operation not permitted, open 'c:\Program Files (x86)\Python38-32\host.json'

Version: 1.0.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

**Comment by NvHeijningen** [comment]
Cant select any interpreter 
![image](https://user-images.githubusercontent.com/65290512/97688320-45025a80-1a9a-11eb-99f1-a75141800d83.png)

**Comment by NvHeijningen** [comment]
And when i manage to make a project I can only see a few of the triggers not all of them 
![image](https://user-images.githubusercontent.com/65290512/97689776-5ea4a180-1a9c-11eb-8d51-0e989855f071.png)

**Comment by EricJizbaMSFT** [comment]
It looks like you're trying to create a project in "c:\Program Files (x86)\". I would select a different folder and try again since that folder usually has restricted permissions
