### ISSUE TITLE
I face this issue while deploying the function app. Can anyone explain why?

### ISSUE THREAD

**Issue by Syadvas** [microsoft/vscode-azurefunctions#2505]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: Deployment '6c5190b3d1664e21add69a524a4fec6e' not found.

Version: 1.0.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
