### ISSUE TITLE
Unable to write to Folder Settings because no resource is provided

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-azurefunctions#2506]
Does this occur consistently? Yes
Repro steps:

1. Open a workspace with multiple workspace folders
2. Try to create a TypeScript project in one of the folders
3. See the error
4. Notice and click the "Initialize Project for Use with VS Code"
5. See the error again

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Unable to write to Folder Settings because no resource is provided.

Version: 1.0.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.51.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
k.reject workbench.desktop.main.js:5789:245
k.resolveAndValidate workbench.desktop.main.js:5792:716
k.doWriteConfiguration workbench.desktop.main.js:5786:275
Object.factory workbench.desktop.main.js:5786:51
u.consume workbench.desktop.main.js:132:75
file:/workbench.desktop.main.js:131:886
u.queue workbench.desktop.main.js:131:810
k.writeConfiguration workbench.desktop.main.js:5786:36
k.writeConfigurationValue workbench.desktop.main.js:5812:588
file:/workbench.desktop.main.js:5802:594
```

</details>

**Comment by ejizba** [comment]
This was an insiders-only bug that was fixed shortly after the issue was filed. I guess I never closed it because I couldn't find the commit in VS Code that fixed it, but it definitely happened to [other extensions](https://github.com/microsoft/vscode-python/issues/14671) and doesn't repro anymore.
