### ISSUE TITLE
why

### ISSUE THREAD

**Issue by mlianghua** [microsoft/vscode-azurefunctions#2509]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to get latest templates: Failed to detect Azure Functions maven plugin version.

Version: 1.0.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:451:428378
fulfilled extension.bundle.js:451:424812
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2508
