### ISSUE TITLE
spawn C:\Windows\system32\cmd.exe ENOENT while trying to create a durableorchestrationfunction in VS Code. 

### ISSUE THREAD

**Issue by JediNikita** [microsoft/vscode-azurefunctions#2510]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: ENOENT
Error Message: spawn C:\Windows\system32\cmd.exe ENOENT

Version: 1.0.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit child_process.js:264:19
onErrorNT child_process.js:456:16
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
