### ISSUE TITLE
azure function app deployment error

### ISSUE THREAD

**Issue by JigarDX** [microsoft/vscode-azurefunctions#2514]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Cannot update the site 'test121' because it uses x64 worker process which is not allowed in the target compute mode.

Version: 1.0.0
OS: linux
OS Release: 5.4.0-52-generic
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
