### ISSUE TITLE
AzureFunctionApp

### ISSUE THREAD

**Issue by weiyunshu1994** [microsoft/vscode-azurefunctions#2515]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionAppAdvanced
Error type: TypeError
Error Message: Cannot read property 'resourceManagerEndpointUrl' of undefined

Version: 1.0.0
OS: linux
OS Release: 4.15.0-88-generic
Product: Visual Studio Code
Product Version: 1.50.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.createAzureClient extension.bundle.js:84:116639
Object.<anonymous> extension.bundle.js:46:220248
fulfilled extension.bundle.js:46:219824
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
