### ISSUE TITLE
Internal error: Expected value to be neither null nor undefined: workspaceFolder

### ISSUE THREAD

**Issue by sujathabhee** [microsoft/vscode-azurefunctions#2518]
Internal error: Expected value to be neither null nor undefined: workspaceFolder.
Source: Azure Functions (Extensions)

I am creating azure function(language: powershell). Project creation without Azure Storage is successful. I am seeing this error at "Add Binding" step. When I open function.json and right click on it for "Add Binding", I am seeing this error.

Please let me know.

**Comment by Algorithmism** [comment]
Did you end up figuring out the issue? I'm having the same problem.

**Comment by ejizba** [comment]
Will track this with https://github.com/microsoft/vscode-azurefunctions/issues/2562
