### ISSUE TITLE
azureFunctions.preDeployTask not pruning correctly

### ISSUE THREAD

**Issue by FrimJo** [microsoft/vscode-azurefunctions#2520]
This is a continuation of issue #1528 Node modules prune during deployment.

When deploying using Azure extension in VS Code, the default behaviour for `azureFunctions.preDeployTask` is to run task `npm prune` (which runs `npm prune --production`), but according to closed issue [#10442](https://github.com/npm/npm/issues/10442) on `npm` repository, `prune` is bugged, and even using `npm prune --production` doesn't provide correct result.

Best result is achieved by removing `node_modules` and the run `npm install --only=production` which only installs modules under `dependencies`. Then on `azureFunctions.postDeployTask` we run `npm install` as usual.

But updating task `npm prun` in `tasks.json` to `rm -rf node_modules && npm install --only=production` and deploy through Azure extension gives me an error that `node_modules/azure-functions-core-tools` can't be found (because we just emoved it with `rm -rf node_modules` which was the whole point, do not need `azure-functions-core-tools` in my zip-file when deploying).

**Comment by ejizba** [comment]
I took a look at the npm issue and it's several years old and seems to be only related to `peerDependencies`, which I don't think is very common. Can you give an example where it's not working correctly with the latest version of npm?

For the last paragraph, I think I'd have to see your specific launch/task config to understand what's going on - also the package.json.
