### ISSUE TITLE
There is an invalid function under the "Functions" node after creating a slot for a Linux function app created with "Consumption" hosting plan

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2524]
**OS:** Win10/Mac
**Build Version:** 20201110.1

**Repro Steps:**

1. Create a Linux function app with "Consumption" hosting plan.
2. Deploy a JavaScript project to this function app.
3. Create a slot for this function app -> Expand the "Functions" node.
4. Check the result.

**Expect:**
There is no functions under the "Functions" node.

**Actual:**

1. Windows:
  There is a function under the "Functions" node.
  ![image](https://user-images.githubusercontent.com/62053665/98650049-50dffd80-2373-11eb-8c5c-e691ccfc4ee9.png)

4. Mac:
  There is an invalid function under the "Functions" node. 
   ![Screen Shot 2020-11-10 at 3 43 43 PM](https://user-images.githubusercontent.com/62053665/98645922-98638b00-236d-11eb-955e-9034c8be623c.png)

**More Info:**

1. This issue doesn't reproduce for the Linux function app created with "Premium/App Service Plan" hosting plan.
2. This issue doesn't reproduce on Linux.

**Comment by ejizba** [comment]
Linux Consumption slots are not the most reliable on the platform. The fact that you got it working fine once implies this is not a problem in VS Code. Therefore, I'll close as external
