### ISSUE TITLE
The "Application Settings" node isn't alphabetically sorted after renaming one application setting

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2525]
**OS:** All
**Build Version:** 20201110.1

**Repro Steps:**
1. Add a new application setting for a Function App.
2. Rename this application setting and check if the "Application Settings" node is alphabetically sorted.

**Expect:**
The "Application Settings" node is alphabetically sorted after renaming one application setting.
![image](https://user-images.githubusercontent.com/45614674/98659072-ba193e00-237e-11eb-993f-3bdf920baeca.png)

**Actual:**
The "Application Settings" node isn't alphabetically sorted after renaming one application setting.
![image](https://user-images.githubusercontent.com/45614674/98658936-93f39e00-237e-11eb-8759-726241f9435a.png)

**More Info:**
Refresh can fix this issue.

**Comment by ejizba** [comment]
The most important piece is to keep focus on the item so it doesn't get lost for the user. As long as a refresh will re-sort the items, we think that's sufficient
