### ISSUE TITLE
Fail to create a python project on Linux

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2527]
**OS:** Linux
**Build Version:** 20201110.1
**Python Version:** 3.8.6

**Repro Steps:**

1. F1 -> Type and select "Create New Project..." -> Select a blank folder -> Select "Python" language -> Select “python3.8” to create a project.
2. Check the result.

**Expect:**
Succeed to create a python project.

**Actual:**
Fail to create a python project.
![image](https://user-images.githubusercontent.com/62053665/98658846-77effc80-237e-11eb-93f5-705a5b3f5e0b.png)

**More Info:**
This issue doesn't reproduce on Win10/Mac.

**Comment by EricJizbaMSFT** [comment]
This is an issue with how Python is setup on that machine. Here's an example result I found where people try to fix the problem: https://github.com/pypa/virtualenv/issues/1059
