### ISSUE TITLE
[Suggestion] It would be better if the notification message is displayed completely when typing {"name":"Azure test"} for request body

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2528]
**OS:** Mac
**Build Version:** 20201110.1

**Repro Steps:**

1. Create a project in VS Code -> Debug -> Select "Execute Function Now" in the local project tree view after debugging successfully -> Type `{"name":"Azure test"}` for request body.
2. Check the notification message.

**Actual:**
The notification message is not displayed completely([notification.zip](https://github.com/microsoft/vscode-azurefunctions/files/5516523/notification.zip)).
![image](https://user-images.githubusercontent.com/62053665/98658333-e54f5d80-237d-11eb-95aa-9a1a4959b46c.png)

**Suggestion:**
It would be better if the notification message is displayed completely.

**More Info:**

1. This issue doesn't reproduce when typing `{"name":"Azure Test"}`.
  ![image](https://user-images.githubusercontent.com/62053665/98658387-ef715c00-237d-11eb-9cf9-0d32ac1c353f.png)
3. This issue doesn't reproduce on Linux/Win10.

**Comment by EricJizbaMSFT** [comment]
This is controlled by VS Code, not our extension.
