### ISSUE TITLE
Unable to see azure functions log in VS code

### ISSUE THREAD

**Issue by Hari-c4** [microsoft/vscode-azurefunctions#2533]
I have a python function app project which is fine while working in azure, but when try to run it in local using `func start` command, logs inside the functions which are written using `logging.info('sample log')` are not showing in the terminal, this used to show previously when I was debugging using vs code.

Repro Steps:

1. Create azure function app project 
2. Add logging.info on any of the functions
3. Execute function 

I have installed azure function core tools 2.7.2936 and using python 3.75.

**Comment by ejizba** [comment]
Seems to be working for me, but I'm on func v3.0.2996. Are you getting any logs at all? Maybe post a screenshot of the terminal?

**Comment by Hari-c4** [comment]
Hi,
 I'm using func v2.7.2936, here is the screenshot of terminal

![FunctionLog](https://user-images.githubusercontent.com/56388643/99961998-6c0c2d80-2db5-11eb-9084-060d83aef9ed.JPG)

Here is my code, this http triggered function is working as expected when I tried a GET request, but the logs are not coming in the terminal.

```
import logging

import azure.functions as func


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    logging.info('sample log')
    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
    else:
        return func.HttpResponse(
             "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
             status_code=200
        )
```

**Comment by ejizba** [comment]
I don't know what to tell ya - I switched to the same func version and I'm seeing the logs:
<img width="945" alt="Screen Shot 2020-11-23 at 11 30 07 AM" src="https://user-images.githubusercontent.com/11282622/100006441-5714a780-2d7f-11eb-9412-73501decdf79.png">

How are you executing the GET request on the HTTP trigger?
