### ISSUE TITLE
DevOps Problem

### ISSUE THREAD

**Issue by CodingSta** [microsoft/vscode-azurefunctions#2534]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.

Version: 1.0.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
errorHandler extension.bundle.js:48:165914
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Could be related to https://github.com/microsoft/vscode-azurefunctions/issues/2464

Are you creating a ServiceBusTopicTrigger by chance?  Or a corporate proxy?
