### ISSUE TITLE
Error: Failed to run "py" command.

### ISSUE THREAD

**Issue by korkridake** [microsoft/vscode-azurefunctions#2535]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.initProjectForVSCode
Error type: Error
Error Message: Failed to run "py" command. Check output window for more details.

Version: 1.0.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:46:74963
fulfilled extension.bundle.js:46:73829
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
