### ISSUE TITLE
Remote server error while deploying az function

### ISSUE THREAD

**Issue by zippoobbiz** [microsoft/vscode-azurefunctions#2536]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: There was a conflict. The remote server returned an error: (403) Forbidden.

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
