### ISSUE TITLE
Failed to deploy python azure function in VS code

### ISSUE THREAD

**Issue by leni-msft** [microsoft/vscode-azurefunctions#2537]
Does this occur consistently? 
Repro steps:

1. Create python Azure Function in VS Code with storage blob trigger
2. Debug it, works well
3. Press F1, "Azure Functions: Deploy to Function App..."
4. Then the error occurred, with error log:
```
8:51:37 PM func-name: Starting deployment...
8:51:39 PM func-name: Creating zip package...
8:53:44 PM: Error: request to https://func-name.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
```

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://func-name.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 1.0.1
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps

**Comment by leni-msft** [comment]
Hi @EricJizbaMSFT , repro steps added.

**Comment by ejizba** [comment]
I can't repro when I try those steps. Does this happen consistently? Only other difference I see is OS as I'm on mac and you're on linux
