### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BahriNipun** [microsoft/vscode-azurefunctions#2538]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: REQUEST_SEND_ERROR
Error Message: read ECONNRESET

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:706:754016
AxiosHttpClient.<anonymous> extension.bundle.js:706:764930
step extension.bundle.js:16:1925
Object.throw extension.bundle.js:16:2030
rejected extension.bundle.js:16:755
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please add detailed repro steps.
