### ISSUE TITLE
Failed to run "npm" command. Check output window for more details.

### ISSUE THREAD

**Issue by sunithamenni** [microsoft/vscode-azurefunctions#2539]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.uninstallFuncCoreTools
Error type: Error
Error Message: Failed to run "npm" command. Check output window for more details.

Version: 1.0.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:46:74963
fulfilled extension.bundle.js:46:73829
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Do you know how you installed the Func Core tools originally?  Was it through the extension or manually?
