### ISSUE TITLE
ENOTFOUND while Publishing from VS Code

### ISSUE THREAD

**Issue by yogendran-aux** [microsoft/vscode-azurefunctions#2540]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: REQUEST_SEND_ERROR
Error Message: request to https://triggertnaevent.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: getaddrinfo ENOTFOUND triggertnaevent.scm.azurewebsites.net

Version: 1.0.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
NodeFetchHttpClient.<anonymous> extension.bundle.js:706:822902
step extension.bundle.js:16:1925
Object.throw extension.bundle.js:16:2030
rejected extension.bundle.js:16:755
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
