### ISSUE TITLE
Create new project fails due to error around .NET Core installation

### ISSUE THREAD

**Issue by jsacapdev** [microsoft/vscode-azurefunctions#2541]
Attempting to create a new project in VS Code for an Azure Function does not work. The following error message is displayed:

`You must have the .NET Core SDK installed to perform this operation. See here for supported versions.`

The approach being used is:

1. Open VS Code (also happens in VS Code Insiders)
2. Click on Azure icon extension
3. Navigate to Azure Function section
4. Click Create new project
5. Choose folder
6. Select C# language

But the SDK is installed:

```
dotnet --list-sdks
5.0.100 [C:\Program Files\dotnet\sdk
```

Has this regressed since the .NET Core 5 installation?

```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by jsacapdev** [comment]
```
Azure Functions Core Tools
Core Tools Version:       3.0.2996 Commit hash: c54cdc36323e9543ba11fb61dd107616e9022bba
Function Runtime Version: 3.0.14916.0
```

**Comment by ejizba** [comment]
Azure Functions doesn't support .NET 5 yet. I would try again with .NET Core 3.1 installed

**Comment by jsacapdev** [comment]
that makes sense, but i didn't remove the previous installations of .net core (i.e. previous to 5), the installation vehicle did (in this case visual studio). which means this development experience is less that ideal for those developing azure functions. i will raise an issue with .NET core 5, maybe track it here for others and then probably close this one down.
