### ISSUE TITLE
Service Unavailable when deploying to linux python|3.8 functionapp

### ISSUE THREAD

**Issue by rolinge** [microsoft/vscode-azurefunctions#2543]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 1.0.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633
Promise.propagateAslWrapper async-listener/index.js:504:23
Promise.__asl_wrapper async-listener/glue.js:188:31
proxyWrapper async-listener/index.js:529:23
async-listener/index.js:541:70
async-listener/glue.js:188:31
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
