### ISSUE TITLE
Improve Python debugger handling of multiple function apps in the workspace

### ISSUE THREAD

**Issue by adiazulay** [microsoft/vscode-azurefunctions#2544]
The Python debugger can also handle one function app in each workspace. If more than one function app is present it will only launch the last function app listed in *tasks.json*. In the example below only function-app-2 will be opened in the debugger, unless the json objects associated with are deleted.

The desired behavior would be an option to choose which function should attach to the debugger.

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"command": "host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"dependsOn": "pipInstall",
			"options": {
				"cwd": "${workspaceFolder}/function-app-1"
			}
		},
                { 
			"type": "func",
			"command": "host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"dependsOn": "pipInstall",
			"options": {
				"cwd": "${workspaceFolder}/function-app-2"
			}
		}

```

**Comment by ejizba** [comment]
@adiazulay does this help you: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

**Comment by adiazulay** [comment]
@ejizba looks like option 2 should work, I'll test it and let you if it works for my use case.

**Comment by adiazulay** [comment]
@ejizba That worked when I followed the example, but I wasn't able to get it to work with a project I already created.
