### ISSUE TITLE
Facing error while deploying python function on Azure

### ISSUE THREAD

**Issue by manish-shegokar** [microsoft/vscode-azurefunctions#2545]
Repro steps:

1. Install npm, azure core tools, and .NET
2. Create a Linux based Python function and try to run it
3. On a successful run, deploy it and you will see the error.

Action: azureFunctions.deploy
Error type: EPERM

![azure](https://user-images.githubusercontent.com/65758231/100000907-4ba99680-2de8-11eb-843f-55d149b4be73.PNG)

Error Message: EPERM: operation not permitted, scandir 'c:\Users\Manish\Application Data'

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

**Comment by ejizba** [comment]
@manish-shegokar you may want to try putting your project in a different folder. The "Application Data" folder might have limited permissions

**Comment by manish-shegokar** [comment]
It worked! Thanks a lot :)
