### ISSUE TITLE
The PowerShell version in the status bar changes from 7.1 to 7.0 during debugging a PowerShell project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2546]
**OS:** Win10/Mac
**Build Version:** 20201123.1
**PowerShell Version:** 7.1.0.0

**Repro Steps:**
1. Create a new PowerShell project and open it in VS Code.
2. Set a breakpoint in run.ps1 file --> Debug it.
3. Check the PowerShell version in the status bar. 

**Expect:**
The PowerShell version is always 7.1.
![image](https://user-images.githubusercontent.com/57662131/100055816-72ef7a80-2e5f-11eb-8700-63c135624e2f.png)

**Actual:**
The PowerShell version changes from 7.1 to 7.0.
![powershell](https://user-images.githubusercontent.com/57662131/100055340-a41b7b00-2e5e-11eb-842b-86842ae54a0a.gif)

**Comment by ejizba** [comment]
The func cli controls that behavior. It's entirely possible they don't support 7.1 yet, hence we it changes to 7.0. Either way, closing as external
