### ISSUE TITLE
Templates do not update after changing bundles version

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2547]
1. Create new JS function app, skip function creation.
1. Update host.json to use Bundles 2.x
1. Create new function - Durable entities templates are not available
1. Reload window
1. Create new function - Durable entities templates are there

**Comment by ejizba** [comment]
So far it hasn't been worth listening for changes to host.json or anything else. We only update when a user re-loads VS Code. Not entirely sure it's worth listening, given how rarely a user would change major bundle versions. Another options is to add some sort of "Reload Templates" command, which could be accessed from the command palette or at the bottom of the template list (if we want it extra-discoverable)

**Comment by nturinski** [comment]
I think with the `Reload templates` option, we can go ahead and close this issue.
