### ISSUE TITLE
Failed create function app in VS code using HTTP triggers from  openAPI V2/V3 specification

### ISSUE THREAD

**Issue by govindagoud** [microsoft/vscode-azurefunctions#2548]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "autorest" command. Check output window for more details.

Version: 1.0.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:46:74963
fulfilled extension.bundle.js:46:73829
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps and copy the output logs mentioned in the error
