### ISSUE TITLE
Deployment not found?

### ISSUE THREAD

**Issue by yasseralhayali** [microsoft/vscode-azurefunctions#2549]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 404
Error Message: Deployment '696e0315e46f4fdbb520055f46ad6c20' not found.

Version: 1.0.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
