### ISSUE TITLE
Run-From-Zip is set to a remote URL using WEBSITE_USE_ZIP app setting.

### ISSUE THREAD

**Issue by PaulDederer** [microsoft/vscode-azurefunctions#2553]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: Run-From-Zip is set to a remote URL using WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps

**Comment by PaulDederer** [comment]
I found a way, thanks for the swift response!
