### ISSUE TITLE
Entry not found in app

### ISSUE THREAD

**Issue by peterskurt** [microsoft/vscode-azurefunctions#2554]
Does this occur consistently?  Yes 
Repro steps:
1. Try to deploy a  TimerRequest function
2. Click on the deploy to function app

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 1.0.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:75486extension.js:243:75486
extension.js:243:73467extension.js:243:73467
extension.js:243:73087extension.js:243:73087
i.find extension.js:243:107619
extension.js:243:53535extension.js:243:53535
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
