### ISSUE TITLE
complication to run function to v studio 

### ISSUE THREAD

**Issue by bbiayi10** [microsoft/vscode-azurefunctions#2555]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: The remote runtime "powershell" for function app "Weslin" does not match your local runtime "node".

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:451:397799extension.bundle.js:451:397799
extension.bundle.js:451:397297extension.bundle.js:451:397297
a extension.bundle.js:451:396983
verifyVersionAndLanguage extension.bundle.js:451:397515
Object.<anonymous> extension.bundle.js:451:398520
fulfilled extension.bundle.js:451:397051
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @bbiayi10 

What runtime is your function project?  The remote and local runtimes don't match.  If your project is node, you should create a node.js function app.  If your project is powershell, then in your VS Code settings, you should change your `projectLanguage` setting to powershell.
