### ISSUE TITLE
error trying to create function app from VSC

### ISSUE THREAD

**Issue by t0dd2000** [microsoft/vscode-azurefunctions#2561]
Does this occur consistently? yes
Repro steps:

1. created http triggers in VSC and tested in local and work fine
2. try to deploy to AZ with first create new project and select python 3.8 and submit and got this error

Action: azureFunctions.deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 1.0.1
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599
extension.js:243:75486
extension.js:243:73467
extension.js:243:73087
i.find extension.js:243:107619
extension.js:243:53535
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
