### ISSUE TITLE
Hi @MLopesSousa, thanks for contributing.

### ISSUE THREAD

**Issue by Algorithmism** [microsoft/vscode-azurefunctions#2563]
Hi @MLopesSousa, thanks for contributing.

Could you copy the output from the Output Channel when this creation fails?  I haven't been able to reproduce this, but I'd like to know which step is failing.

Also, does this issue occur every deploy/creation or is it just every once and a while?  Can you think of anything other configurations in your workspace that might be different from mine? Do you happen to not have full access to the subscription that you are creating this app in?

_Originally posted by @nturinski in https://github.com/microsoft/vscode-azurefunctions/issues/1342#issuecomment-503668220_

**Comment by Algorithmism** [comment]
I'm getting this error now, not in the advanced creation. Azure Functions extension is the culprit, according to my error message. Any solutions?

**Comment by ejizba** [comment]
@Algorithmism please post your own repro steps, the version of your extension, and the exact error message
