### ISSUE TITLE
An error occurs when swapping the slot with production for a PowerShell function app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2564]
**OS:** Win10/Mac
**Build Version:** 20201202.1
**PowerShell Version:** 7.1.0.0

**Repro Steps:**
1. Create a function app with PowerShell runtime and Consumption hosting plan.
2. Deploy the PowerShell project to the function app. 
3. Create a new slot for the function app.
4. Swap the new slot with production.
5. Check whether swap the slot with production successfully.

**Expect:**
Swap the new slot with production successfully.

**Actual:**
An error occurs when swapping the slot with production.
![image](https://user-images.githubusercontent.com/57662131/100836991-4664df80-34ab-11eb-9252-7f17b6e7ca20.png)
Details in Output:
```
9:50:46 AM: Swapping "nicole-ps-win-con-production" with "nicole-ps-win-con-slot1"...
9:54:22 AM: Error: Failed with code "400".
```

**More Info:**
This issue doesn't reproduce for function app created with App Service Plan/Premium hosting plan.

**Comment by v-mengwe** [comment]
Verified on the latest build 20201210.11, this issue also reproduces when swapping a slot with production for a basic node 12 function app.

> Create a basic function app with Node 12 -> Deploy -> Create a slot -> Swap the slot with production.

**Comment by v-xinda** [comment]
This issue also reproduces on the latest build 20210329.1 when swapping a slot with the production for a Consumption/basic .NET function app.

**Comment by v-mengwe** [comment]
Verified on the latest build 20211009.3, this issue also reproduces when swapping a slot with production for a basic Java 8 function app.

> Create a basic function app with Java 8 -> Deploy a Java project to the function app -> Create a slot to it -> Swap the slot with production.
