### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by riteshakumar** [microsoft/vscode-azurefunctions#2566]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 1.0.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @riteshakumar Does this happen consistently? If so, please provide detailed repro steps.
