### ISSUE TITLE
Getting unbound breakpoints issue when trying to run the latest Azure Functions Extension code locally

### ISSUE THREAD

**Issue by shimedh** [microsoft/vscode-azurefunctions#2569]
![image](https://user-images.githubusercontent.com/14221995/101216261-109f3280-3634-11eb-97b5-63af51eb874c.png)

@ejizba FYI

**Comment by ejizba** [comment]
Is the extension activated? The breakpoint will be "unbound" until you actually try to use the extension

**Comment by shimedh** [comment]
> Is the extension activated? The breakpoint will be "unbound" until you actually try to use the extension

Yes, I triggered it using vscode://ms-azuretools.vscode-azurefunctions. I get the pop-up to open vscode and nothing after

**Comment by ejizba** [comment]
You probably need to add an activationEvent here: https://github.com/microsoft/vscode-azurefunctions/blob/main/package.json#L31

https://code.visualstudio.com/api/references/activation-events

**Comment by shimedh** [comment]
> You probably need to add an activationEvent here: https://github.com/microsoft/vscode-azurefunctions/blob/main/package.json#L31
> 
> https://code.visualstudio.com/api/references/activation-events

Oh that's right. I will look into them. I think I need "onUri" and "onDebugInitialConfigurations"

**Comment by shimedh** [comment]
> > You probably need to add an activationEvent here: https://github.com/microsoft/vscode-azurefunctions/blob/main/package.json#L31
> > https://code.visualstudio.com/api/references/activation-events
> 
> Oh that's right. I will look into them. I think I need "onUri" and "onDebugInitialConfigurations". I will try this out and update this thread in a bit.

Thanks @ejizba that worked. I was missing the "onUri" activation event in package.json
