### ISSUE TITLE
Host start fails

### ISSUE THREAD

**Issue by Arash-Sabet** [microsoft/vscode-azurefunctions#2577]
Does this occur consistently? 
Repro steps:

1.Simply run two functions running in two different ports in the same workspace

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to find "func: host start" task.

Version: 1.0.1
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:706:111813
fulfilled extension.bundle.js:706:110686
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @Arash-Sabet 

In order to run two function projects simultaneously, you have to make sure of multi-root workspaces.
https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

Does this help resolve your issue?

**Comment by Arash-Sabet** [comment]
@nturinski I exactly followed those steps but no luck on MacOS. The workspace on a windows machine does not exhibit this problem but it causes VS code to freeze! It's worse on MacOS BigSur. Please see [this post on Stackoverflow](https://stackoverflow.com/questions/65175097/unable-to-run-azure-queue-triggered-function-on-macos-bigsur-in-visual-studio-co?noredirect=1#comment115256397_65175097).

**Comment by Arash-Sabet** [comment]
@nturinski are durable tasks causing this issue?!

**Comment by nturinski** [comment]
@Arash-Sabet Could I see your `launch.json` and your `.code-workspace` files?  What language are your function projects?  And what type of triggers do they have?

**Comment by Arash-Sabet** [comment]
@nturinski could you please share an email address to send you some info? There's some proprietary info that I'd rather not share online.

**Comment by nturinski** [comment]
Sure, I completely understand.  Please send to nathan.turinski@microsoft.com

**Comment by Arash-Sabet** [comment]
@nturinski I sent you an email pointing to a few github gists. Hope that helps.

**Comment by nturinski** [comment]
@Arash-Sabet I got them.  I've been looking at your configurations and haven't been able to find anything incorrect about them.  You said that you were trying to debug durable triggers?  Does this configuration work with just HTTP triggers by chance?

**Comment by Arash-Sabet** [comment]
@nturinski This configuration works for http-triggered and queue-triggered functions well. Not sure what contributes when durable tasks come to the context!

**Comment by nturinski** [comment]
@Arash-Sabet I see, thanks for the extra information.  I'll dig into this a bit more.  Have you ever tried durable tasks in a single function host task?

**Comment by Arash-Sabet** [comment]
@nturinski I will schedule some time early next week to give it a try.

**Comment by alexweininger** [comment]
Closing as stale, please reopen if you're still experiencing this issue.
