### ISSUE TITLE
VS Code Azure upload function error

### ISSUE THREAD

**Issue by lmattiso** [microsoft/vscode-azurefunctions#2582]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Requested feature is not available in resource group AZR-ADU-LABX. Please try using a different resource group or create a new one.

Version: 1.0.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
