### ISSUE TITLE
Error while deploying previously working Az-function

### ISSUE THREAD

**Issue by arpalani** [microsoft/vscode-azurefunctions#2595]
Does this occur consistently? <Yes>
Repro steps:

1. Choose publish from vscode
2. Choose subcription
3. Choose the existing function (trying to overwrite)
<Deployment starts>

Action: azureFunctions.deploy
Error type: 400
Error Message: Failed with code "400".
![image](https://user-images.githubusercontent.com/64439952/101854064-9b40cf80-3b15-11eb-81d3-ccc740205077.png)

Version: 1.0.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add more detail to your steps, including what type of project you had, how you created the function app in Azure, and if this happens consistently
