### ISSUE TITLE
when i am trying to create function app using VS code and Azure function extensions i am getting this error

### ISSUE THREAD

**Issue by amarmanchalagithub** [microsoft/vscode-azurefunctions#2596]
11:27:55 PM: Error: Command "dotnet "c:\Users\aam5268\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.0.1\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "sfsfswewe" --arg:AzureFunctionsVersion v3" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null

**Comment by amarmanchalagithub** [comment]
multiple people are getting the similar error

**Comment by ejizba** [comment]
@amarmanchalagithub what version of `dotnet` do you have installed? And please add repro steps

**Comment by amarmanchalagithub** [comment]
.NET Core SDK (3.1.401)

Microsoft.NETCore.App 3.1.7

**Comment by amarmanchalagithub** [comment]
on Dec-8 I see Azure core function tools automictically updated and after that  we are started facing this issue.

I have delete the EXTENSIONs from .VSCode folder and re installed all required extensions, but still facing the same problem.

**Comment by amarmanchalagithub** [comment]
Repro Stpes
1) Open Visual Studio Code

2) Select Azure subscription

3) Under Azure function app

4) create A new project

5) Select Folder

6)  Select  Timer trigger

7) Use Local Emulator

  Getting Error:

9:23:12 AM: Error: Command "dotnet "c:\Users\aam5268\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.1.0\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "LogicAppPreviwSamples" --arg:AzureFunctionsVersion v3" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}

**Comment by ksaye** [comment]
I am getting the same trying to create an Event Grid trigger:

```
11:58:26 AM: Error: Command "dotnet "c:\Users\kevinsay\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.2.0\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\kevinsay\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\kevinsay\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~2.nupkg" --operation create --identity Azure.Function.CSharp.EventGridTrigger.2.x --arg:name "EventGridTriggerCSharp1" --arg:namespace "Company.Function"" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "EventGridTrigger",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}
```

I have deleted:
1. c:\Users\kevinsay\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions
2. c:\Users\kevinsay\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.2.0

and reinstalled with with no success.

I had to switch to a Python module.

Info:

C:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ejizba** [comment]
@ksaye what version of the func cli are you using? It looks like you are using v2, but the Event Grid template shouldn't even show up in VS Code in that case because of https://github.com/microsoft/vscode-azurefunctions/issues/2467. I would suggest trying on v3.

**Comment by ksaye** [comment]
@ejizba thanks for the comment and you were right.  changing to version 3 resolved the issue.

For others, go into settings and select the Project Runtime:

![image](https://user-images.githubusercontent.com/15837044/109172940-ec418680-7748-11eb-8eab-d4be5b7d933f.png)
