### ISSUE TITLE
Getting error "unable to get local issuer certificate" whle deploying azure python function from vs code to azure

### ISSUE THREAD

**Issue by anshumankaku** [microsoft/vscode-azurefunctions#2597]
Does this occur consistently? YES
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to https://aka.ms/AAa5ia0?api-version=2020-10-01&removeHiddenStacks=true&removeDeprecatedStacks=true failed, reason: unable to get local issuer certificate

Version: 1.0.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by ejizba** [comment]
Double check these proxy settings if you're behind a corporate proxy: https://code.visualstudio.com/docs/setup/network

Otherwise, please add repro steps
