### ISSUE TITLE
[Suggestion] It will be better to keep the notification message consistently when adding or uploading an existing setting

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2598]
**OS:** All
**Build Version:** 20201211.5

**Repro Steps:**
1. Drill down a function app --> Expand the "Application Settings" node --> Add a new setting named "app" like below.
![image](https://user-images.githubusercontent.com/57662131/101880391-cab31300-3bcd-11eb-919b-714ac07c5522.png)
2. Add a new setting named "APP" again --> Check the notification.
3. Right Click the "Application Settings" node --> Click "Upload Local Settings..." --> Upload the "APP" setting --> Check the notification.

**Actual:**
The notification message is inconsistent between step2 and step3.
![image](https://user-images.githubusercontent.com/57662131/101881216-0ef2e300-3bcf-11eb-896f-ba9c47630d95.png)

**Suggestion:**
It will be better to keep the notification message consistently when adding or uploading an existing setting

**Comment by ejizba** [comment]
The bottom error message is coming from Azure and we don't like it as much. The only one we can change is the top message, and we want to keep that as-is.
