### ISSUE TITLE
Got this error using the extension on osx, installed python using pyenv and used the pyenv link for pyhton

### ISSUE THREAD

**Issue by wiebew** [microsoft/vscode-azurefunctions#2599]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 1.0.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItemWithProjects.<anonymous> extension.bundle.js:54:9223
fulfilled extension.bundle.js:54:3146
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
