### ISSUE TITLE
Only host.json displays after creating a C# function successfully

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/vscode-azurefunctions#261]
## Steps to reproduce
1. Create a new project using C#.
2. Create a new function and add Httptrigger.
3. Select 'Function' and click 'Enter'. 
4. After creating function successfully, verify whether all of function.json, host.json, and proxies.json display under the new created project.

## Expected  behavior
All of function.json, host.json, and proxies.json display under the new created project.

## Actual behavior
Only host.json displays under the new created project. No function.json and proxies.json.

![json](https://user-images.githubusercontent.com/12556995/37141722-dc74b17a-22ad-11e8-9eea-59167455f87a.PNG)

More Info:
1. This issue also reproduces on Mac and Linux.
2. For JS, only host.json and function.json display under the new created project. No proxies.json.

![jsjson](https://user-images.githubusercontent.com/12556995/37141845-43c0bbf8-22ae-11e8-8e4a-c4ed657c7079.PNG)

**Comment by EricJizbaMSFT** [comment]
Thanks - the important files to look for are `host.json` and `local.settings.json`. The project is _not_ expected to have a `proxies.json` file by default.

We also expect there to be a `function.json` file for every function you create, but C# is a little bit different. Unlike JavaScript (which doesn't need to be compiled), you have to run the build task for C# and the `function.json` file will be generated for you:
<img width="251" alt="screen shot 2018-03-08 at 8 40 34 am" src="https://user-images.githubusercontent.com/11282622/37163542-ec3bffb0-22ac-11e8-97e0-782945db5e94.png">

Closing this as by-design
