### ISSUE TITLE
Fail to debug a C# project with two functions named "HttpTrigger_CSharp1" and "HttpTrigger-CSharp1"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2615]
**OS:** Win10
**Build Version:** 20201215.1

**Repro Steps:**

1. Create a C# project with two functions named "HttpTrigger_CSharp1" and "HttpTrigger-CSharp1" -> F5.
2. Check whether debug successfully.

**Expect:**
Debug the project successfully without any error.

**Actual:**
Fail to debug the project with an error.
![image](https://user-images.githubusercontent.com/62053665/103741336-d3afcc80-5033-11eb-9449-520e459bb161.png)
```
C:\Users\AzureTest\Desktop\function\cs\HttpTrigger_CSharp1.cs(13,25): error CS0101: The namespace 'Company.Function' already contains a definition for 'HttpTrigger_CSharp1' [C:\Users\AzureTest\Desktop\function\cs\cs.csproj]
C:\Users\AzureTest\Desktop\function\cs\HttpTrigger_CSharp1.cs(16,49): error CS0111: Type 'HttpTrigger_CSharp1' already defines a member called 'Run' with the same parameter types [C:\Users\AzureTest\Desktop\function\cs\cs.csproj]
The terminal process "C:\Program Files\dotnet\dotnet.exe 'build', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" terminated with exit code: 1.
```

**More Info:**

1. This issue doesn't reproduce for JavaScript/TypeScript/Python/PowerShell project.
2. Create a C# project with function named "HttpTrigger-CSharp1"  -> F5 -> Check the function under the local project tree view.
    ![image](https://user-images.githubusercontent.com/62053665/103742434-c3005600-5035-11eb-8af2-44ed4ab61325.png)

**Comment by ejizba** [comment]
Wow that's an interesting find! Haha that being said, I don't think someone would name their functions the same except a switched hyphen/underscore. Also, the name was converted by the dotnet cli, not us, making this harder to fix if we wanted to
