### ISSUE TITLE
There is an error under the "Functions" node when creating a .NET 3.1 Linux function app with App Service hosting plan

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2616]
**OS:** Win10
**Build Version:** 20210105.3

**Repro Steps:**

1. Create an advanced Linux function app with App Service hosting plan and .NET 3.1 runtime -> Expand the "Functions" node.
2. Check the "Functions" node.

**Expect:**
There is no error under the "Functions" node.

**Actual:**
There is an error under the "Functions" node.
![image](https://user-images.githubusercontent.com/62053665/103870174-530dd080-5106-11eb-9ba0-5be7c38f56a5.png)

**More Info:**

1. This issue doesn't reproduce when creating a .NET 3.1 basic function app.
2. This issue doesn't reproduce when creating an advanced function app with Consumption and Premium hosting plan and .NET 3.1 runtime.
3. Refresh can fix this issue.

**Comment by ejizba** [comment]
The fact that a refresh fixes the issue and it works in all the other scenarios you mentioned implies to me this is an intermittent error. InternalServerError is a very generic error that happens from time to time due to the platform and there's not much we can do about it
