### ISSUE TITLE
Include "--publish-local-settings" feature on VSCode Azure Functions Extension

### ISSUE THREAD

**Issue by joshuaquek** [microsoft/vscode-azurefunctions#2626]
Currently this is available when doing a command line deploy: https://stackoverflow.com/questions/54557804/how-to-run-publish-local-settings-when-doing-a-right-click-deploy

Can we make this feature available when doing a deploy in the extension?

**Comment by ejizba** [comment]
Are you aware we have the "Upload Settings" button on the notification after a deploy completes?
<img width="464" alt="Screen Shot 2021-01-19 at 11 27 53 AM" src="https://user-images.githubusercontent.com/11282622/105083164-65163a00-5a49-11eb-82e3-5720cb01c7d1.png">

If that is not sufficient - what would you like different from that experience?

**Comment by joshuaquek** [comment]
oh! was not aware of this. Thanks for highlighting!

Question: Will it do a merge of the the local and online environment variables, or a full overwrite (removing variables that are not present locally)?

**Comment by ejizba** [comment]
It should prompt to overwrite any existing variables and it will _not_ remove anything

**Comment by joshuaquek** [comment]
Awesome, thank you!
