### ISSUE TITLE
How to change TargetFramework in VSCode?

### ISSUE THREAD

**Issue by MeLight** [microsoft/vscode-azurefunctions#2627]
It's well documented how to change the target framework in Visual Studio (via .cproj), but how do we change it in VS Code?
![image](https://user-images.githubusercontent.com/704484/105050142-25b21280-5a76-11eb-9127-aff50779278a.png)

**Comment by ejizba** [comment]
The csproj file should exist in VS Code as well. Maybe post a screenshot of your workspace in VS Code?

**Comment by MeLight** [comment]
There you go
![image](https://user-images.githubusercontent.com/704484/105088584-c3bcd180-5aa4-11eb-9468-367f73d06895.png)

**Comment by ejizba** [comment]
Looks like that is a PowerShell project, not a C# project. How did you create this project? If it was through VS Code, we should prompt you for language up front
