### ISSUE TITLE
There are no docs around creation of specific service triggered functions on VSCode (i.e. timer, eventhub, etc.)

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2638]
Currently, there is no documentation around creation of any other triggered function besides HTTP triggered.  Each of the creation paths contain important steps that might not be immediately obvious to users and so better documentation in the short description below or dedicated documentation page might be useful to have (even if it's a reference style page with each of the steps laid out with more explanations).  

However, I'd like to examine what exactly needs to take place in order to fill this gap.  For the time being, we can take a look at some of the telemetry around how many people exit out of a function creation process in order to see how relevant this is.  

An example around this is during some customer interviews, NCRONTAB is not super obvious and so they exited out to look it up and could be a point where users churn.

![image](https://user-images.githubusercontent.com/6217333/105883246-3f9aaa80-5fcc-11eb-8c3a-4e3a8233a812.png)

**Comment by ejizba** [comment]
See comments elsewhere https://github.com/microsoft/vscode-azurefunctions/issues/2644#issuecomment-767781767 https://github.com/microsoft/vscode-azurefunctions/issues/2646#issuecomment-767810833. My team generally does not own the documents or templates.
