### ISSUE TITLE
Visibility of "Execute Function Now" within VSCode

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2639]
![image](https://user-images.githubusercontent.com/6217333/105883357-60630000-5fcc-11eb-8f41-498a0730ca8d.png)

Currently, debugging functions in vscode has never been easier but not a lot of customers/users know about this "execute function now" button nor is there any documentation around what is actually required to execute a function now (i.e. for an event triggered function, you need to provide an event).  

There are two ways I can think of that we can do to raise the visibility around this:
1. Change the quickstart (QS) docs to reference the execute function now as either an additional step or as a replacement for the current steps
2. Do  A/B testing around displaying an extra step at the end of function creation (especially when it's something other than HTTP) that outlines the use of this or debugging steps.

I'm open to more ideas but currently Glenn Gailey is working on the docs point of view.

**Comment by nturinski** [comment]
Is there any update on this?
