### ISSUE TITLE
[Linux]Display as JavaScript function type when creating it with C#

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#264]
Repro Steps:
1. Create a new project using C#.
2. Create a new function and add Httptrigger.
3. Select 'Function'. 
4. Check the created function type and the opened file.

Expect:
Display as C# function type and the 'HttpTrigger.cs' file is opened.

Actual:
Display as JavaScript function type and the 'index.js' file is opened.
![aa](https://user-images.githubusercontent.com/34729022/37145211-3772ec72-22b8-11e8-8a2c-49c48032e4ed.png)

**Comment by EricJizbaMSFT** [comment]
This is because you have vscode settings at multiple levels of your workspace. Only the top level settings in '.vscode' are used. VSCode ignores settings in subfolders
