### ISSUE TITLE
No way to look up or create Event Hubs via an extension on VS Code

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2640]
Currently, there are extensions for IOT Hub, Event Grid, and Service Bus, and a third party extension for Event Hub.  There isn't a first party extension for Event Hub and so the flow of working in VSCode is broken a bit by this. 

This is okay as I've talked to Matt Hernandez and the point of VSC isn't to remove the portal but to draw people in with popular/frequently used service extensions.  However, we're going to be doing some research to see how many people who actively use Event Hub in conjunction with Functions and VSCode to see if there would be a market for it.  

Viewing Events in eventhub is difficult enough as it is, this would significantly improve the quality of a user that doesn't have to look for the events being sent in portal when all they have to do is look at it on VSC.

**Comment by ejizba** [comment]
This is out of scope for an issue on the Functions repo. Creating/owning an entirely new extension is a _lot_ of work and should be discussed offline, potentially with multiple teams to see who wants to own it.
