### ISSUE TITLE
Code samples in documentation don't match up with the template provided by VSC's Function Creation

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2644]
Documentation:
![image](https://user-images.githubusercontent.com/6217333/105886318-e2085d00-5fcf-11eb-9d52-22701a7c437d.png)

Function creation:
![image](https://user-images.githubusercontent.com/6217333/105886325-e59be400-5fcf-11eb-8cc6-437e1cb36d52.png)

Currently, the connection where any changes made to the code in the template should be reproduced in the docs is broken and these will be updated but that connection needs to be rebuilt/retained.

**Comment by ejizba** [comment]
The templates used by VS Code come from here:
https://github.com/Azure/azure-functions-templates

And if you look at the doc site, it usually has a link to a GitHub repo at the bottom for filing an issue. Something like this:
https://github.com/MicrosoftDocs/azure-docs

I'm not sure which template is right or even if they need to be the same, but I would suggest filing an issue in one of those repos if you want them to match.

**Comment by ijoosong** [comment]
Thanks @ejizba I'll let the docs team know but right now a lot of the code samples are mismatched for https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python and the output/input bindings, and triggers.  Thanks!
