### ISSUE TITLE
VSCode created triggered functions use extensionBundle while docs reference individual extensions

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2645]
Currently, the host.json from VSC templates look like this:
![image](https://user-images.githubusercontent.com/6217333/105886660-462b2100-5fd0-11eb-925e-e4ca333ce5f6.png)

whereas the docs for something like eventhub extension looks like this:
![image](https://user-images.githubusercontent.com/6217333/105886691-504d1f80-5fd0-11eb-8c31-1944b80d4600.png)

There will be a push for an extensionBundle vs 2 which may change this but for the time being, users do not have direct access to to specific parameters that are set to default (i.e. for maxBatchSize or prefetchCount etc.)

What do you think will be the best way to move forward with this besides just adding documentation around it in the reference docs?

**Comment by ejizba** [comment]
It sounds like you want the docs to change, not VS Code. In that case, please file an issue using the github link at the bottom of the article. My team does not own the docs :)

**Comment by ijoosong** [comment]
I think the further question I wanted to ask was do you think that we should have any discussions around adding comments or README updates around Functions trigger templates.  I think that adding a README.md with an explanation of those things might also be helpful.  Lastly, If extensionBundle vs 2 is going to be different from vs 1, how will users on extensionbundle v1 and those using just extensions know the difference? @ejizba @fiveisprime
