### ISSUE TITLE
[Codespace] It is better to remove the default file name "local.setting.json" when downloading the remote settings to the browse file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2650]
**OS:** Remote Codespaces
**Build Version:** 20210131.1

**Repro Steps:**

1. Expand a function app -> Right click "Application Settings" node -> Select "Download Remote Settings..." -> Select "Browse...".
2. Check the default file name.

**Expect:**
There is no default file name.

**Actual:**
There is a default file name "local.setting.json".
![image](https://user-images.githubusercontent.com/62053665/106437780-957dbf80-64b0-11eb-9ae5-0a8962ac5f96.png)

**More Info:**
There is no default file name in regular test.
  ![image](https://user-images.githubusercontent.com/62053665/106441525-1b9c0500-64b5-11eb-9105-9abfe4384a3c.png)

**Comment by ejizba** [comment]
We actually like the default better in Codespace where it has "local.settings.json". I wish Windows could do the same thing, but it seems like they can't.
