### ISSUE TITLE
Comment on issue #1345, can't reopen it

### ISSUE THREAD

**Issue by bessgeor** [microsoft/vscode-azurefunctions#2655]
I'd like to comment issue #1345, but I've got no rights to reopen it myself.
I've met the similar issue using Visual Studio Community while trying to add more packages.
The error there (`error NU1101: Unable to find package Microsoft.NET.Sdk.Functions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages`) is pretty self-describing: no package `Microsoft.NET.Sdk.Functions` in source `Microsoft Visual Studio Offline Packages`. Using Visual Studio Community package manager interface I've disabled every package source except nuget.org (which one is selected doesn't matter), [screenshot here](https://i.imgur.com/l94ANUO.png). This solved the issue for me.
So it seems to be a problem in some kind of global configuration or nuget client itself (I never wanted blurred package sources to be added automatically to every project), does't seem to be related to VSCode.

Feel free to close this issue, as it's actually a comment on another issue and not an issue itself.

**Comment by ejizba** [comment]
Yeah we only work on VS Code, not Visual Studio Community. Please follow up with the functions extension for Visual Studio Community instead of here
