### ISSUE TITLE
Improve startup performance related to workspaceContains activation event

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#2659]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2654, we have to search the whole workspace or debugging could fail. As the VS Code team [put it](https://github.com/microsoft/vscode/issues/110510#issuecomment-770133700):
> Using workspaceContains:**/... will start a search across the user's full workspace which may use a lot of CPU. And, if this search takes longer than 5s, the search will be canceled and your extension will be activated anyway.

Ideally we find a better way to activate. Some new activation events that could help from VS Code:
- An event based on a VS Code setting (probably "azureFunctions.projectSubpath") - already tracked in https://github.com/microsoft/vscode/issues/55299
- An event based on the task provider, in our case "func"

**Comment by heaths** [comment]
Alternatively, could the depth be limited? We use this technique for VSIX extensions in Visual Studio for manifest discovery. IIRC, the max depth is 3 which made a huge difference. Perhaps the max depth could be specified by the extension, with a user-specified/default max.

**Comment by ejizba** [comment]
@heaths I think maybe you meant to comment on a _VS Code_ issue? This repo is for an _extension_ for VS Code, not VS Code itself. Our issues and the Rust issue are definitely related, but we can't fix it for y'all haha

Fwiw, you might be able to replicate a depth-limit yourself by listing multiple activation events like:
```
workspaceContains:*/example.txt
workspaceContains:*/*/example.txt
workspaceContains:*/*/*/example.txt
```

**Comment by heaths** [comment]
You're right. 🤦‍♂️ I saw microsoft/vscode and failed to read the rest. But, yes, that might be a good workaround.
