### ISSUE TITLE
Unable to find func: host start when task exists

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/vscode-azurefunctions#2661]
Issue Type: <b>Bug</b>

I have a project that is fairly advanced (has some functions and web apps).  I have configured the launch.json and tasks.json to have the right folder.  However, when I start a new session of VS Code and try to launch the debugger it gives me an error that "func: host start" task cannot be found.  I can see it in tasks.json - but it doesn't like it for some reason.

What's weird is if I say "Initialize project for us with VS Code", it starts to work, but my files are still the same.  When I switch to another machine I'll have to repeat the same thing.

I have a GitHub Codespace that can repro this with my project if interested.  Send me an email and can share

Extension version: 1.2.0
VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:13:57.826Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (28.69GB free)|
|Process Argv|. --crash-reporter-id 6d902a21-4e78-43ea-9df3-2855bc1c55bd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: React+Express and PostgreSQL|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|Memory (System)|50.14GB (34.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by jeffhollan** [comment]
![image](https://user-images.githubusercontent.com/7132626/107278685-f22a2e80-6a0a-11eb-83af-ab323e84b291.png)

**Comment by ejizba** [comment]
Workin on it. See https://github.com/microsoft/vscode-azurefunctions/issues/2654#issuecomment-774317213
