### ISSUE TITLE
Azure Functions from VSCode with a Linux Consumption Plan not adding Remote build App Settings on Linux

### ISSUE THREAD

**Issue by kfolkes** [microsoft/vscode-azurefunctions#2663]
Azure Functions from VSCode with a Linux Consumption Plan and deploy the code, it does not create those settings automatically. It only create these:

 
![image](https://user-images.githubusercontent.com/9865836/107558291-3438a900-6ba0-11eb-8144-064b52789f05.png)

 When I perform the same operations with a Premium Consumption Plan It creates those settings automatically and everything works great.

----

Ensure the when using  Linux Consumption Plan adds the App Settings during deployment. 

•	ENABLE_ORYX_BUILD=true
•	SCM_DO_BUILD_DURING_DEPLOYMENT=true

**Comment by ejizba** [comment]
I'm pretty sure remote build is the default for Linux Consumption, meaning we don't need those settings. Does it actually fail to build? If I create a consumption app from VS Code, I only see these settings:

![Screen Shot 2021-02-10 at 11 23 34 AM](https://user-images.githubusercontent.com/11282622/107560865-b91cc600-6b92-11eb-8914-eb250c85e7df.png)

But when I deploy, I see logs like "Running oryx build..." and "Running pip install..." implying it is doing a build.

**Comment by kfolkes** [comment]
For a internal MSFT they were experiencing this issue the build failed to load binaries during the deployment. 

**From my research :**

I would verify if you have these app settings in your function app. 
[Deployment technologies in Azure Functions | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-functions%2Ffunctions-deployment-technologies%23remote-build-on-linux&data=04%7C01%7CKrystal.Folkes%40microsoft.com%7C19947f40e0f349fc58e208d8cdf8419d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637485814210535031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d8jbX1xQNxytUu%2FGa0tUZ1Afp0WnBetI190P%2BN5KNdI%3D&reserved=0) - 
Remote build on Linux
To enable remote build on Linux, the following application settings must be set:
•	ENABLE_ORYX_BUILD=true
•	SCM_DO_BUILD_DURING_DEPLOYMENT=true
By default, both Azure Functions Core Tools and the Azure Functions Extension for Visual Studio Code perform remote builds when deploying to Linux. Because of this, both tools automatically create these settings for you in Azure.
When apps are built remotely on Linux, they run from the deployment package.
 


**Their findings Notes:**
We’re performing the deployment from Visual Studio Code with this configuration:
 
{
  "azureFunctions.deploySubpath": ".",
  "azureFunctions.projectLanguage": "JavaScript",
  "azureFunctions.projectRuntime": "~3",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "npm prune",
  "azureFunctions.scmDoBuildDuringDeployment": true
}
 
 
It works with Premium Consumption Plan (EP1) but It doesn’t with Linux Consumption Plan (Y1)
I tried with GitHub Actions and a linux runner and It works for a Linux Consumption Plan. So, I assume it’s a bug in Visual Studio Code/Azure Function tools… 


**Another MSFT Feedback:**
I don't believe VS Code does remote build by default. It does, however, initialize a settings.json file with a default scmDoBuildDuringDeployment value based on language. I think Python is automatically configured for remote build. For Node, you need to opt in.

Try removing the pre/post deployment tasks in settings.json and ensure node_modules is in .funcignore.

Take a look at this sample: functions-headless-chromium/puppeteer at main · anthonychu/functions-headless-chromium (github.com) The remote build from VS Code worked for me, and the resulting app does not have the SCM do build setting.

 
Now not sure if it supposed to be by default or not.

**Comment by ejizba** [comment]
Can you show logs of where the build failed?
