### ISSUE TITLE
Auto-detect project logic won't work if you clone a project from Github

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#267]
We look for the existence of 'host.json' _and_ 'local.settings.json' to identify a project as an Azure Functions project, but 'local.settings.json' is included in the gitignore (it could have connection strings, which people should not be commiting), so it will never exist if you're cloning a repo.

**Comment by nturinski** [comment]
I tried with this repo:
https://github.com/Azure-Samples/functions-js-spa

If you manually run the command through the palette, it works like a charm though 👍
