### ISSUE TITLE
VS Code Unable to deploy Azure Function zip

### ISSUE THREAD

**Issue by umakamuni13** [microsoft/vscode-azurefunctions#2686]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\uma.kamuni\Desktop\Poc_working\Banking Solution\APIs_FunctionApp\bankingSA\bankingSA.zip

Version: 0.13.1
OS: win32

**Comment by ejizba** [comment]
Please add repro steps

Also, you might want to try updating your extension, because v013.1 is a few years old at this point. To get the latest (v1.2.1), you may need to update your version of VS Code, too.
