### ISSUE TITLE
A11y_Azure Tools for VS Code [BM]_Debug_Screen Reader: NVDA/Narrator is not reading about the breakpoint if it is inserted anywhere in program

### ISSUE THREAD

**Issue by Accessibility56** [microsoft/vscode-azurefunctions#2699]
[Check out Accessibility Insights!](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**
#Azure Tools for VS Code; #A11ySev2; #A11yTCS; #BM-Azure Tools for VS Code-Win-Feb2021; #DesktopApp; #Narrator; #NVDA; #WCAG1.3.1; #Win10; #Scree Reader; Element:BreakPoint;

**OS Details:**
Windows 10 Version 20H2 (OS Build 19042.685)

**Environment Details:**
Application Name: Azure Tools for VS Code
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0

OS: Windows_NT x64 10.0.19042
Azure Function Version: 1.2.1

**NOTE:**
Same issue is observed for "Expand/Collapse" button as well.

**Repro Steps:**

1. Turn on NVDA/Narrator
2. Open Visual studio code
3. Tab till extension button and press enter on it.
4. Search for "Azure Functions" and select it.
5. Tab till "Install" button and press enter on it.
6. Tab till "Azure" button from left side pane and press enter on it.
7. Default screen will get open.
8. Create any project and insert breakpoint
9. Verify Screen reader is reading about breakpoint or not while navigating in code.

**Actual Result:**
NVDA/Narrator is not reading about the breakpoint if it is inserted anywhere in program

**Expected Result:**
NVDA/Narrator should read about the breakpoint if it is inserted anywhere in program

**User Impact:**
Screen Reader users will not get complete information available on screen if screen reader is not reading it.

**Attachment for Reference:**
[2699_NVDA is not reading about breakpoint.zip](https://github.com/microsoft/vscode-azurefunctions/files/6019806/2699_NVDA.is.not.reading.about.breakpoint.zip)
![2699_Narrator issue](https://user-images.githubusercontent.com/38523250/108669316-c9259580-7502-11eb-863f-bcf68aecd574.png)

**Comment by ejizba** [comment]
This is controlled by VS Code. Tracking bug here: https://github.com/microsoft/vscode/issues/90842
