### ISSUE TITLE
Open In Portal command doesn't work

### ISSUE THREAD

**Issue by cmatskas** [Microsoft/vscode-azurefunctions#27]
Hi team,
When I use the command pallette to run the "Open in Portal" command from the Azure Functions extension, nothing happens. I'm already logged in to my Azure Subscription and I have successfully published a Function but I'm unable to use the command to Open the Azure Portal.
Is this still not feature-complete?

**Comment by EricJizbaMSFT** [comment]
Thanks for the issue! For now, 'Open in Portal' only works when you right click on a Function App in the Functions explorer. I'll fix the command palette scenario for our next release
