### ISSUE TITLE
Deployment Failing - Checkin Message and Commit Author not consistent to other deployments

### ISSUE THREAD

**Issue by michaeltheyeti** [microsoft/vscode-azurefunctions#2700]
Originally I thought this was a fluke thing, but now deployments are consistently failing in my VS Code environment (having changed nothing since this morning)

As you can see the Check-in Message changed as well as the Commit Author

![image](https://user-images.githubusercontent.com/14824657/108777208-13ba0880-7529-11eb-95a8-731d00c62f85.png)

Not that this helps but here are two status.xml files from Kudu.

Working Deployment:
```
<?xml version="1.0" encoding="utf-8"?>
<deployment>
    <id>ee365c2e17cb4e26ae0dcb54c8e0b852</id>
    <author>VS Code</author>
    <deployer>ZipDeploy</deployer>
    <authorEmail>N/A</authorEmail>
    <message>Created via a push deployment</message>
    <progress></progress>
    <status>Success</status>
    <statusText></statusText>
    <lastSuccessEndTime>2021-02-19T19:37:02.1512625Z</lastSuccessEndTime>
    <receivedTime>2021-02-19T19:37:01.0418934Z</receivedTime>
    <startTime>2021-02-19T19:37:01.1669891Z</startTime>
    <endTime>2021-02-19T19:37:02.1512625Z</endTime>
    <complete>True</complete>
    <is_temp>False</is_temp>
    <is_readonly>True</is_readonly>
</deployment>
```
Consistently Failing Deployment (I can delete the deployment in Kudu and it just creates another one with the 'temp' prefix)
```
<?xml version="1.0" encoding="utf-8"?>
<deployment>
    <id>temp-94a71c25</id>
    <author>N/A</author>
    <deployer>ZipDeploy</deployer>
    <authorEmail>N/A</authorEmail>
    <message>Deploying from pushed zip file</message>
    <progress></progress>
    <status>Failed</status>
    <statusText></statusText>
    <lastSuccessEndTime />
    <receivedTime>2021-02-22T22:10:09.1093566Z</receivedTime>
    <startTime>2021-02-22T22:10:09.1093566Z</startTime>
    <endTime>2021-02-22T22:10:09.3124794Z</endTime>
    <complete>True</complete>
    <is_temp>True</is_temp>
    <is_readonly>False</is_readonly>
</deployment>
```
I've closed everything and restarted VS Code.  I'm hesitant to remove the Azure Functions Extension however.

**Comment by ejizba** [comment]
I'm not surprised to see a temp deployment in particular - they happen with every deploy, but go away when they succeed. The weird part is just that this temp deploy failed. Can you deploy again and copy the logs from when it fails? It should be in the "Azure Functions" output pane in VS Code

**Comment by michaeltheyeti** [comment]
Definitely not as helpful as I would have liked.  Here are the logs:

```
12:22:22 PM pos-dev-autocy-fun: Starting deployment...
12:22:23 PM pos-dev-autocy-fun: Creating zip package...
12:22:30 PM pos-dev-autocy-fun: Zip package size: 2.34 MB
12:22:30 PM pos-dev-autocy-fun: Fetching changes.
12:22:34 PM pos-dev-autocy-fun: Deployment failed.
```

**Comment by ejizba** [comment]
Rough - yeah that's not helpful. Can you give more information about your project (what langauge?) and how you created the function app in Azure (portal, VS Code, etc.). You could also try deploying this project to a brand new app - that would help us figure out if the app in azure or the project is the problem

**Comment by michaeltheyeti** [comment]
Certainly. I'm trying to avoid deploying to a new app as it is quite a bit of leg work to do this within the organization I'm part of.

Is there any additional logging that can be activated for the deployment process that I'm missing here?

I'm finishing up and ADO pipeline for the project as well to see if perhaps ZipDeploy is just broken as well.  I'll try to remember to let you know.

**Comment by ejizba** [comment]
Late reply, but yeah I'm not sure there's much we can do from VS Code's side. The logs you already see are pretty much all we can get. If you can't create a new app, then Azure support is likely the best avenue going forward because they might have access to a lot more internal logs for your existing app
