### ISSUE TITLE
The result is inconsistent when adding a setting "test-1" between the Windows function app and Linux function app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2705]
**OS:** All
**Build Version:** 20210225.3

**Repro Steps:**

1. Create a Windows function app -> Add a new setting with name "test-1" -> Check the result.
2. Create a Linux function app -> Add a new setting with name "test-1" -> Check the result.
3. Check whether the result is consistent between the Windows function app and Linux function app.

**Expect:**
The result is consistent between the Windows function app and Linux function app.

**Actual:**
The result is inconsistent between the Windows function app and Linux function app.

1. **Windows function app**: Succeed to add the setting "test-1".
2. **Linux function app**: There is an error when entering the setting name "test-1".
    ![image](https://user-images.githubusercontent.com/62053665/109132970-68f75380-778f-11eb-89a9-3a1a7ee655dd.png)

**Comment by ejizba** [comment]
This is by design. There are inherent differences between Windows and Linux that we can't control

Related to https://github.com/microsoft/vscode-azuretools/pull/592 and https://github.com/microsoft/vscode-azureappservice/issues/646

**Comment by v-mengwe** [comment]
Got it, thanks for your share!
