### ISSUE TITLE
[Unstable] There is an unstable error after swapping the slot with production for the Python Linux function app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2706]
**OS:** All
**Build Version:** 20210225.3

**Repro Steps:**

1. Create a Linux function app with Python.
2. Create a Python project with two "Http trigger" functions.
3. Deploy the project to the Linux function app -> Create a slot for the Linux function app -> Swap the slot with production.
4. Check whether swap the slot with production successfully.

**Expect:**
Succeed to swap the slot with production without any error.

**Actual:**
There is an unstable error after swapping the slot with production.
![image](https://user-images.githubusercontent.com/62053665/109283676-0b7c0900-785a-11eb-92ea-c47e52c42dee.png)

**More Info:**
This issue doesn't reproduce for Node.js/C# project.

**Comment by ejizba** [comment]
Since you said this is "unstable", it's likely a problem in the platform and not on our side. Linux slots are not the most reliable, so I'll close this as upstream/wont-fix
