### ISSUE TITLE
[Linux] Pop up an error dialog when debugging a function project with C#

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#272]
Repro Steps:
1. Create a new project using C#.
2. Create a new function and add Httptrigger.
3. Select 'Function'.
4. Set a break point in the opened HttpTrigger.cs file.
5. Debug.

Expect:
No error dialog pops up.

Actual:
Pop up an error dialog.
![error](https://user-images.githubusercontent.com/34729022/37276109-c7e47e2e-25d8-11e8-9446-2ae8f2210368.png)

**Comment by EricJizbaMSFT** [comment]
This doesn't repro for me. What version of the func cli are you on? Does it happen consistently?

**Comment by EricJizbaMSFT** [comment]
Closing this - feel free to re-open if you can get a consistent repro.
