### ISSUE TITLE
There is an error after creating a Linux Function App with .NET 5 and Premium/App Service Plan hosting plan

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2722]
**OS:** All
**Build Version:** 20210304.14

**Repro Steps:**

1. Create a Linux Function App with .NET 5 and App Service Plan hosting plan.
2. Expand the "Functions" node.
3. Check whether there is an error or not.

**Expect:**
There is no error under the "Functions" node.

**Actual:**
There is an error under the "Functions" node.
![image](https://user-images.githubusercontent.com/57662131/109934778-d95e2180-7d07-11eb-8feb-4e32187aae85.png)

**More Info:**
1. This issue doesn't reproduce for Windows function app.
2. This issue also reproduces for the Linux Function App with .NET 5 and Premium hosting plan.

**Comment by ejizba** [comment]
Apparently the Linux images are still rolling out to all regions. I was able to get this to work if I used "West US 2".

**Comment by ejizba** [comment]
This has since rolled out to other regions and no longer repros for me

**Comment by v-xinda** [comment]
@ejizba Hi Eric, an error still exists after creating a Linux Function App with .NET core3/5 and Premium/App Service Plan hosting plan. But the issue can be fixed by refreshing.
![image](https://user-images.githubusercontent.com/57662131/113110984-48ad2f80-923a-11eb-9da2-ade0915dae71.png)

**Comment by v-xinda** [comment]
This issue reproduces on the latest build 20210525.7, more details as below:
**Repro Steps:**
1. Create a Linux function app with .NET 5/.NET Core 3.1 runtime.
2. Expand the function app -> Expand the "Functions" node.
3. Check whether there is an error under the "Functions" node or not.

**Expect:**
There is no error under the "Functions" node.

**Actual:**
There is an error under the "Functions" node.
![image](https://user-images.githubusercontent.com/57662131/119625102-6b278780-be3c-11eb-8ff7-af303b91f4cf.png)

**More Info:**
1. This issue doesn't reproduce for other runtime function apps.
2. Tis issue doesn't reproduce for Windows  .NET function app.
3. This issue can be fixed by refreshing the "Functions" node.

**Comment by ejizba** [comment]
Please do not re-open or add comments to locked issues. "ServiceUnavailable" is a common error code and it's probably a different issue.

**Comment by v-xinda** [comment]
Got it, I open a new bug [2829](https://github.com/microsoft/vscode-azurefunctions/issues/2829) to track it.
