### ISSUE TITLE
The webpage displays "404 Not Found" after deploying a .NET 5 project to a Linux Function App created with .NET 5 and Consumption hosting plan

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2724]
**OS:** All
**Build Version:** 20210304.14

**Repro Steps:**

1. Create a Linux Function App with .NET 5 and Consumption hosting plan.
2. Deploy a .NET 5 project to the Linux Function App -> Expand the function app -> Right click the function "HttpTriggerCSharp1" -> Select "Copy Function Url".
3. Add `&name=friend` to the end of the URL and paste it in browser.
4. Check whether open the webpage successfully.

**Expect:**
Open the webpage successfully.

**Actual:**
The webpage diaplays "404 Not Found".
![Screen Shot 2021-03-04 at 5 38 24 PM](https://user-images.githubusercontent.com/62053665/109944237-fd723080-7d10-11eb-9f48-9d4d0a2584f9.png)

**More Info:**
The webpage diaplays "Function host is not running" after deploying a .NET 3.1 project to the Linux Function App.

**Comment by ejizba** [comment]
Apparently linux images are still rolling out to all regions. You can ignore this scenario for now and I'll update this thread when I have a region that works

**Comment by ejizba** [comment]
This has since rolled out to other regions and no longer repros for me
