### ISSUE TITLE
Executing "BlobTrigger" fails if blob path does not exist

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2731]
**OS:** All
**Build Version:** 20210304.27

**Repro Steps:**

1. Create a project with "BlobTrigger" function -> Open it in VS Code -> Restore.
2. Debug -> Select "Execute Function Now" for the function in the local project tree view
3. Check the logs of Terminal.

**Expect:**
There is no error in the Terminal.

**Actual:**
There is an error in the Terminal.
![Screen Shot 2021-03-05 at 4 41 33 PM](https://user-images.githubusercontent.com/62053665/110092868-0b898500-7dd5-11eb-89f9-26a8b25092b4.png)

**Comment by ejizba** [comment]
When you execute a blob trigger, you are prompted for the request body like this:
<img width="382" alt="Screen Shot 2021-03-05 at 10 59 00 AM" src="https://user-images.githubusercontent.com/11282622/110161166-da439180-7da1-11eb-85ad-e5f75d8ee957.png">

If the path you enter does not exist in your connected blob container, you will see this error. If the blob exists, it should work. We can discuss during triage if the error is self-explanatory enough or if we need to enhance this experience. In any case, this is _not_ related to the upcoming 1.3.0 release.

**Comment by ejizba** [comment]
Let's investigate if the "Execute Function" request has an error status code. If so, we can make sure that gets displayed as a VS Code notification. Otherwise, we'll probably close as won't fix.

**Comment by ejizba** [comment]
Response from "execute function" is a 2xx status code, so not much else we can do here. The error in the terminal is probably good enough
