### ISSUE TITLE
Fail to debug C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2733]
**OS:** Linux
**Build Version:** 20210304.27
**.NET:** 5.0.200 and .NET Core 3.1

**Repro Steps:**
Create a C# project with HttpTrigger template and .NET 5, then debug it.

**Expect:**
Debug this C# project successfully.

**Actual:**
An error occurs when debugging this C# project.
![image](https://user-images.githubusercontent.com/45614674/110099977-e00a9880-7ddc-11eb-9ae9-4baa7d736314.png)

**More Info:**
1. Stop debugging and debug again, another error occurs.
![image](https://user-images.githubusercontent.com/45614674/110100054-f1ec3b80-7ddc-11eb-96ca-567a9904b8bc.png)
2. This issue does not reproduce on Windows and Mac.

**Comment by ejizba** [comment]
I can repro this on Mac and Windows, with v1.2.1 of our extension using .NET Core 3.1. It seems to be a regression in VS Code as of v1.54. Importantly, it only happens the _first_ time I debug a C# project for that session of VS Code. If I stop the original `func host start` task and try to debug again it will work.

Filed this bug on VS Code: https://github.com/microsoft/vscode/issues/118256

**Comment by ejizba** [comment]
Actually going to track this in https://github.com/microsoft/vscode-azurefunctions/issues/2656
