### ISSUE TITLE
Fail to debug PowerShell project with only .NET 5 installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2735]
**OS:** Linux
**Build Version:** 20210304.27
**.NET:** 5.0.200

**Repro Steps:**
Create a PowerShell project with HttpTrigger template, then debug it.

**Expect:**
Succeed to debug PowerShell project with only .NET 5 installed.

**Actual:**
Fail to debug PowerShell project with only .NET 5 installed.
![image](https://user-images.githubusercontent.com/45614674/110101898-15b08100-7ddf-11eb-8007-0c41ef750d4d.png)
![image](https://user-images.githubusercontent.com/45614674/110101908-19440800-7ddf-11eb-8714-4469278cc092.png)

**More Info:**
This issue does not reproduce after installing .NET Core 3.1 SDK on this machine.

**Comment by ejizba** [comment]
This is expected - PowerShell still requires users to install .NET Core 3.1 and is not supported with just .NET 5.0. 

https://docs.microsoft.com/azure/azure-functions/functions-reference-powershell?tabs=portal#powershell-versions
