### ISSUE TITLE
Unable to debug locally azure function python3.9 with latest core tools

### ISSUE THREAD

**Issue by erharvey** [microsoft/vscode-azurefunctions#2739]
Hi,

I am unable to debug/run locally an azure function using python3.9 with the latest azure function extensions(1.2.1). However, deploying the function to Azure and running it there works as intended. It is unclear based on the change logs if debugging is suppose to work at this point. Please see the error below.

![image](https://user-images.githubusercontent.com/17800696/110480439-7f1ce200-80b4-11eb-9bfe-971292075bda.png)

![image](https://user-images.githubusercontent.com/17800696/110480231-43821800-80b4-11eb-8314-d3a4f4d4b98d.png)

![image](https://user-images.githubusercontent.com/17800696/110480266-4da41680-80b4-11eb-8b8d-8d55a11f624a.png)

**Comment by ejizba** [comment]
What version of azure-functions-core-tools do you have installed? You can check by running. `func --version`.  Python 3.9 was added recently, so you need to make sure you're on the latest. If you go to the output pane and switch to "Azure Functions", it should show a warning with the exact version needed

<img width="603" alt="Screen Shot 2021-03-15 at 1 19 29 PM" src="https://user-images.githubusercontent.com/11282622/111201764-1be9ee80-8591-11eb-87d6-86316585e6f6.png">
