### ISSUE TITLE
Deployment error logs

### ISSUE THREAD

**Issue by Prithvi103** [microsoft/vscode-azurefunctions#2740]
I am facing some deployment errors but how do I access more logs to find out the exact cause of this error? I am using VS code to publish a python azure function app

![image](https://user-images.githubusercontent.com/12830451/110485783-02b8ec00-8112-11eb-9177-e03563ec65a9.png)

**Comment by ejizba** [comment]
You can check the Deployment log in the tree, but it's probably the exact same as the logs you show in your screenshot
![Screen Shot 2021-03-22 at 5 35 57 PM](https://user-images.githubusercontent.com/11282622/112075144-28dc8400-8b35-11eb-9968-96108b63b3c5.png)

If those logs don't have an error, your best bet might be to contact Azure support or try with a brand new function app
