### ISSUE TITLE
Azure Function Templates not Loading

### ISSUE THREAD

**Issue by lesharris** [microsoft/vscode-azurefunctions#2741]
## Description

When creating a new Azure Function from within VS Code the 'Select a template for your function' prompt never loads the templates.  It will spin forever:

![templates](https://user-images.githubusercontent.com/1480883/110547112-54e31880-80e4-11eb-8153-04bc49a17172.png)

I get the same behavior across multiple environments and different installations of VS Code (all at the latest versions of VS Code and the Azure Functions Extension)

## Desired Behavior
The templates should load or at least allow manual entry of the template type without waiting for the fetch to finish.

## Environments
* Mac OS 11
* Windows 10
* WSL

## Versions
* VS Code - 1.54.1
* Azure Functions Extension - 1.2.1

## Current Workaround
I create new functions using `func` via the CLI which works fine.

**Comment by ejizba** [comment]
Can you try again with v1.3.0 of our extension? This may have been improved by https://github.com/microsoft/vscode-azurefunctions/pull/2703 and a few other PRs. Also what language did you select? C#/JavaScript/etc.?

**Comment by lesharris** [comment]
@ejizba Looks like it's still happening for me in VS Code 1.54.3 and Azure Functions 1.3.0.  I am using Typescript as the language.

If I can provide any kind of diagnostic log please let me know. For what it is worth, all the other functionality works fine like deployments.

**Comment by ejizba** [comment]
Yeah you can check the "Azure Functions" pane of the output channel:
<img width="594" alt="Screen Shot 2021-03-16 at 12 00 52 PM" src="https://user-images.githubusercontent.com/11282622/111349639-4dc18a80-864f-11eb-8d0a-187ffbe71f94.png">

Also if you wouldn't mind, just open up a separate window and let it run for a while (at least 10-15 minutes?) before you check the logs. I've seen bugs where it just takes minutes as opposed to actually "forever"

Are you by chance behind a corporate proxy? That could be messing with things, although we're supposed to at least give up after 15-ish seconds (controlled by the `azureFunctions.requestTimeout` setting

**Comment by lesharris** [comment]
@ejizba Sorry for the delay - I was up against a hard deadline and had to focus on just that.  I have left it running in its own window for a couple hours at this point and I'm not seeing anything in the output log and it is still just spinning.

I am not behind a corporate proxy or any kind of VPN while this is happening.

![hang](https://user-images.githubusercontent.com/1480883/112546463-b0650580-8d76-11eb-8ea6-537aa97907f2.png)

**Comment by rajmsft** [comment]
I have a similar issue - Version 1.55.2; Aure Function 1.3. No Template dropdowns - window keeps spinning

**Comment by AndresNamm** [comment]
![image](https://user-images.githubusercontent.com/21141607/122649877-bcbfeb00-d138-11eb-8140-f2e9d0c0ad8f.png)
I am facing the same issue right now. It would be great if this bug would be solved as I think having this capability in vscode could help direct a lot of new users towards Azure functions.

**Comment by AndresNamm** [comment]
This suddenly works today. Yesterday I restarted vscode and my dev container and that did not help but starting vscode today  I see the available templates. @rajmsft, @lesharris does it work for you know?

**Comment by rajmsft** [comment]
no luck. Still spinning and not able to create a project.

[cid:5a87e32c-4c8c-44a7-9dc8-9479e01d18a8]

________________________________

**Comment by ejizba** [comment]
Can you guys double check the "Azure Functions" output channel mentioned earlier in the issue? Also maybe try "Help -> Toggle Developer Tools" and go to the "Console" tab to check for errors
![Screen Shot 2021-06-25 at 11 29 32 AM](https://user-images.githubusercontent.com/11282622/123470010-aa1a3b80-d5a8-11eb-9bb8-eef0cd0f9cde.png)
