### ISSUE TITLE
C# Debugging fails when setting LocalHttpPort in local.settings.json

### ISSUE THREAD

**Issue by lwoollett-smudge** [microsoft/vscode-azurefunctions#2744]
Hi guys, with #2738 not fixing my issues with the debugger I kept looking for solutions.

Turns out it was inside my local.settings.json
This local.settings will fail to attach the debugger:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
  },
  "Host": {
    "LocalHttpPort": 9003,
    "CORS": "*",
    "CORSCredentials": false
  }
}
```
Whereas this will succeed:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
  },
  "Host": {
    "CORS": "*",
    "CORSCredentials": false
  }
}
```

`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.406
 Commit:    f42e6b201a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.16
 OS Platform: Darwin
 RID:         osx.10.16-x64
 Base Path:   /Users/luke/Development/Runtimes/dotnet-sdk-3.1.406-osx-x64/sdk/3.1.406/

Host (useful for support):
  Version: 3.1.12
  Commit:  0267ad09c6

.NET Core SDKs installed:
  3.1.406 [/Users/luke/Development/Runtimes/dotnet-sdk-3.1.406-osx-x64/sdk]
  ```

VSCode version 1.54.1

Asked @danielwhyte-smudge to replicate and he was also able to get this behaviour

**Comment by ejizba** [comment]
Yeah we do not take `LocalHttpPort` into account. We'll look into fixing.

In the meantime, any particular reason you need to use "9003"? It should work if you use the default, "7071". As a workaround, I think you can replicate the same behavior if you search for all instances of `host start` in your `.vscode` folder and replace it with `host start --port 9003`

**Comment by lwoollett-smudge** [comment]
Yeah have been switching over to `host start --port x` while we've been waiting for a fix, the bonus is it gets committed into version control as well so postman scripts are easier to share 🍾 

For the current project i'm working on we're using 90xx as a port for when we're running multiple functions locally.
