### ISSUE TITLE
Improve Core Tools install experience in Linux

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2745]
This is primarily feedback from running in a Codespace but might apply to Linux in general.

Currently customers are sent to the GitHub readme which has a [list of commands](https://github.com/Azure/azure-functions-core-tools#linux):

![image](https://user-images.githubusercontent.com/3982077/110828819-4c0d5680-824c-11eb-816e-cbbe58e6f4fa.png)

Some ideas for improvement:

* In the prompt, can we tell the customer what distro and version they're running?
* Can we detect the distro and version, and send them to a dedicated page/location with very specific instructions? (Functions team can maintain this)
* If npm is available, as is the case of the Codespaces kitchen sink container, can we provide a new default option, which is to install via npm? If the install fails, then send them to the docs (or tell them to try rerunning the command using sudo).

**Comment by alexweininger** [comment]
Just ran into this while doing some testing, and yeah I agree the experience for installing func core tools on Linux is not great and the suggestions Anthony has made would be great.

**Comment by nturinski** [comment]
> - In the prompt, can we tell the customer what distro and version they're running?
> 
> - If npm is available, as is the case of the Codespaces kitchen sink container, can we provide a new default option, which is to install via npm? If the install fails, then send them to the docs (or tell them to try rerunning the command using sudo).

Seems like cheap, reasonable enhancements.
