### ISSUE TITLE
Respect `python.pythonPath` when debugging

### ISSUE THREAD

**Issue by sethjuarez** [microsoft/vscode-azurefunctions#2750]
Hitting F5 in VSCode for a Python Azure Function executes `func host start` in the default conda environment even though the `python.pythonPath` has been set in `settings.json` to point to the correct conda envrionment. Is there a way to have that environment be respected when debugging the Function?

**Comment by ejizba** [comment]
Take a look at the `azureFunctions.pythonVenv` setting, which should already exist in your workspace's settings.json. Also what is your python version and func cli version? Some python versions aren't supported on older versions of the func cli

**Comment by sethjuarez** [comment]
Thanks! I didn't know about that setting. I added it (maybe incorrectly?) but am getting a weird error:
```
> Executing task: C:\Users\sethj\.conda\envs\torch\Scripts\activate && func host start <

'C:\Users\sethj\.conda\envs\torch\Scripts\activate' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\Windows\System32\cmd.exe /d /c C:\Users\sethj\.conda\envs\torch\Scripts\activate && func host start" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```
Here is my `settings.json`:
```
{
  "azureFunctions.deploySubpath": ".",
  "azureFunctions.scmDoBuildDuringDeployment": true,
  "azureFunctions.projectLanguage": "Python",
  "azureFunctions.projectRuntime": "~3",
  "azureFunctions.pythonVenv": "C:\\Users\\sethj\\.conda\\envs\\torch",
  "debug.internalConsoleOptions": "neverOpen",
  "python.pythonPath": "C:\\Users\\sethj\\.conda\\envs\\torch\\python.exe"
}
```

**Comment by ejizba** [comment]
Sorry yeah that setting is only relevant if you're using a virtual environment. For example, when creating a new Python project you should be prompted to select a Python interpreter. Your conda environment might be listed or you could manually enter the path:

<img width="387" alt="Screen Shot 2021-03-24 at 10 55 52 AM" src="https://user-images.githubusercontent.com/11282622/112360417-884ea700-8c8f-11eb-80a4-1503ef876e93.png">

Once the project is created, the "pythonVenv" setting corresponds to the name of the virtual environment, `.venv`. A virtual environment is the best way to ensure it uses a specific python version. If that doesn't work let me know and I can look into alternative solutions without a virtual environment.

**Comment by sethjuarez** [comment]
I am using `conda` environments - is that supported?

**Comment by ejizba** [comment]
No, we don't have specific support for conda or the `python.pythonPath` setting. If the conda environment is in your PATH environment variable it'll be used, but that's about it. We'll put this in our backlog to somehow respect the `python.pythonPath` setting

Related to https://github.com/microsoft/vscode-azurefunctions/issues/1393
