### ISSUE TITLE
The default function name is incorrect if clicking "Back” button to reselect another function

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2754]
**OS:** Win 10
**Build Version:** 20210323.1

**Repro Steps:**

1. Open a project in VS Code -> Click "Create Function..." button -> Select "Timer trigger" -> Press Enter with default function name "TimerTigger[Number]" -> Click "Back" button when entering a cron expression -> Click "Back" button -> Select "HTTP trigger".
2. Check whether the default function name is correct.

**Expect:**
The default function name is correct.

**Actual:**
The default function name is incorrect.
![fun](https://user-images.githubusercontent.com/62053665/112131209-462c5380-8c04-11eb-8dfc-c9cfa9930a01.gif)

**More Info:**
This issue doesn't reproduce when clicking "Back" button without entering a cron expression step.
![fun1](https://user-images.githubusercontent.com/62053665/112131597-a9b68100-8c04-11eb-8718-7b62bdf43538.gif)

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azureappservice/issues/1609
