### ISSUE TITLE
Cannot sign into azure

### ISSUE THREAD

**Issue by estradanic** [microsoft/vscode-azurefunctions#2757]
Does this occur consistently? Yes
Repro steps:

1. Make sure Azure Functions and Azure CLI Tools are installed
2. Go to the Azure functions tab
3. Click Sign in to Azure ...

Expected Results: I will be able to sign into Azure

Actual Results: My browser opens up to localhost:[some varying port]/signin?nonce=[some random string token] and then hangs there forever.

Version: 1.3.0
OS: linux
OS Release: 5.4.0-66-generic
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

**Comment by ejizba** [comment]
Could be a duplicate of https://github.com/microsoft/vscode-azure-account/issues/179

In that issue, they recommend `Azure: Sign In with Device Code` as a workaround
