### ISSUE TITLE
Raise binding.context failure information

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-azurefunctions#276]
Environment:
macOS
VS Code 1.21
latest Azure CLI tools
Azure Functions 0.7.0

I'm not sure if this is related to the extension. But I've used it to create a function that has an output binding to a CosmosDB document db. I've deployed the function to the portal and when I test it from there, passing in a json document, the document does get stored into the db. But when I run it in vscode and then call it from postman and pass in the same doc, the document does not get stored.

I can debug into the function and see the document coming in via req.body.

There are no errors. I have debugged into context when I'm at the closing brace and can't find any kind of error code. I've also tried using application insights and a few other ways to monitor the db to see if there's any indication of an attempt to create a document but am not seeing anything.

If I could see what is or isn't happening, then I might be able to fix the problem. Is there something more that the extension could be helping me with?

Here is the function code:
```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
   
    try {
        context.bindings.outputDocument=req.body;
      }
      catch(error) {
        context.log(error);
         }
    context.done();
};
```

Here is the function.json:

```
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "documentDB",
      "name": "outputDocument",
      "databaseName": "Ninjas",
      "collectionName": "Ninjas",
      "createIfNotExists": true,
       "connection": "datapointscosmosdb",
       "direction": "out"
    }
  ]
}
```

localsettings.json:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=functionsample;AccountKey=***",
    "datapointscosmosdb": "AccountEndpoint=https://***.documents.azure.com:443/;AccountKey=***"
      }
    }
```

**Comment by rachelappel** [comment]
@christopheranderson Can you help?

**Comment by fiveisprime** [comment]
Do you see any errors from the functions host? If you ran using F5 from VS Code, switch to the `terminal` tab in the output pane to see the Functions host output. See if there are any hints in there as to why it's not raising the output binding.

The other thing to check is your local functions tooling versus what you're deploying to. It looks like you are running the older functions tooling and you may be deploying to the beta v2. Check the `FUNCTIONS_EXTENSION_VERSION` app setting in the Functions portal, `~1` is the older tooling, `beta` is the newer stuff.

If you are targeting `beta` try updating to the @core tag of  the tools

```sh
$ npm i -g azure-functions-core-tools@core
```

**Comment by julielerman** [comment]
Thanks. There were no indications of a problem in the terminal output for fictions extension. (By the way I love the details of that feature). When I get back home I’ll try the other suggestions and report back

Sent from my *** Phone

On Mar 13, 2018, at 1:07 PM, Matt Hernandez <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you see any errors from the functions host? If you ran using F5 from VS Code, switch to the terminal tab in the output pane to see the Functions host output. See if there are any hints in there as to why it's not raising the output binding.

The other thing to check is your local functions tooling versus what you're deploying to. It looks like you are running the older functions tooling and you may be deploying to the beta v2. Check the FUNCTIONS_EXTENSION_VERSION app setting in the Functions portal, ~1 is the older tooling, beta is the newer stuff.

If you are targeting beta try updating to the @core<https://github.com/core> tag of the tools

$ npm i -g azure-functions-core-tools@core

**Comment by julielerman** [comment]
update: portal says that the function extension version is latest. I recall running that npm to update the tools recently when VS Code prompted me to do it.  But I've just run it again and there is still no difference...the data is not reaching my db and I'm getting no errors. Also, FWIW, I have the cosmosdb extension and it has no problem reaching the database. I'll try creating a function to read.

**Comment by julielerman** [comment]
also:
in workspace settings: "azureFunctions.projectRuntime": "~1",
which seems to indicate "latest"

**Comment by EricJizbaMSFT** [comment]
@julielerman yes "~1" matches "latest". However, that's mostly used to determine which templates to display when you create a new function and doesn't necessarily match the version of the func cli installed on your machine. In fact, I _know_ it doesn't match the verison installed on your local machine since v1 is Windows-only and you're on a mac. The only reason we default to "~1" is because it has many more templates available and we haven't run into too many differences between v1 and beta for JavaScript (until now 🙃). I recommend changing that to "beta", publishing again (it should prompt you to update your remote runtime version), and testing again on the remote. Then you should get more consistent results between your local machine and the remote published app, which might help us diagnose the problem.

I tested your code on Windows with v1 of the functions runtime and it worked. (If you want to try on windows, just remove the `@core` tag when installing the func cli and you'll get v1 instead of beta)

**Comment by julielerman** [comment]
ok thanks on that setting. That helps me grok things better.
But still, the function succeeds from the portal ..inputing a new document to the db.
When I debug the local function from vscode, it runs with no errors but there is no new doc in the db.
I even edited the key value for the cosmosdb in settings and it didn't complain. Seems like it's not even trying to store the doc in the cosmosdb. I'll keep looking for differences. But I'm worried that I'm going to give up and go find something else to play with. :(

**Comment by julielerman** [comment]
good news ...sorta LOL. The deployment hadn't deployed all the functions before (I need to find the pattern for that) so now I did do the redeploy and saw the message about updating the portal version of the function app to beta. And now the import function is failing too. (haha .."good news"). But this is what I'm getting for an error in the log:
```
2018-03-13T20:32:09.000 Exception while executing function: Functions.ImportNinjaJson. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 4224 exited with code 1) (Worker process with pid 7008 exited with code 1) (Worker process with pid 6036 exited with code 1). Worker process with pid 4224 exited with code 1.
2018-03-13T20:32:09.509 Function completed (Failure, Id=5bd5feec-550b-4ff3-94d3-4e0392a08ed5, Duration=724ms)
```
output:
```
AggregateException: One or more errors occurred. (Worker process with pid 4224 exited with code 1) (Worker process with pid 7008 exited with code 1) (Worker process with pid 6036 exited with code 1)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker+<InvokeCore>d__6.MoveNext() in WorkerLanguageInvoker.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase+<Invoke>d__30.MoveNext() in FunctionInvokerBase.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator+<Coerce>d__3.MoveNext() in FunctionGenerator.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker+<InvokeAsync>d__9.MoveNext() in FunctionInvoker.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__24.MoveNext() in FunctionExecutor.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__23.MoveNext() in FunctionExecutor.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__22.MoveNext() in FunctionExecutor.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__16.MoveNext() in FunctionExecutor.cs
```

**Comment by julielerman** [comment]
Should the javascript code in index.js be different now with the beta?

**Comment by julielerman** [comment]
I'm going to create a whole new function app on the portal targeting linux preview and see what might be different...

**Comment by julielerman** [comment]
aha! perhaps cosmosdb isn't supported yet. It's not here as an output ...
![image](https://user-images.githubusercontent.com/5007120/37369021-44e3591c-26de-11e8-8fb4-64d4cb8fea5a.png)

**Comment by julielerman** [comment]
confirmed via https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-runtime-2.0-known-issues

I had no idea. Whoops. My goal wasn't the new runtime but exploring the azure functions extension and I just happened to be using the mac. Oh well.  :)

> The runtime does not register 1.0 built in bindings and triggers by default. the following bindings are registered: (additional bindings may be registered using the new extensibility model)
> 
> - [ ] HTTP Trigger
> - [ ] Timer trigger
> - [ ] Blob storage trigger, input and output bindings
> - [ ] Table storage input and output bindings
> - [ ] Storage Queue trigger and output bindings
> 

However, there's still an issue about not getting any type of error message which is what sent me on the goose chase...

**Comment by jeffhollan** [comment]
Ok the trick is a few things. That wiki page is out of date, we actually have all of those bindings and triggers in v2 now.  I'll fix that.  However in v2 (.NET Core runtime) most of the triggers and bindings are now extensions that have to be installed manually.  We are doing some work this month so that the funciton.json you had above (or a variant of it) would automatically install extensions when you ran it for you, but while it's in progress here's how to get your function working:

1. In the project root, run the following Azure Functions CLI command: `func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDb -v 3.0.0-beta6`
 * This installs the CosmosDb triggers and bindings into your project. You'll likely see an `functions-extensions` folder popup in your project and a `bin` folder that has the bits it needs
1. There are some changes to the function.json for CosmosDb in v2, so you'll need to update to look like this:

```json
{
"type": "cosmosDb",
"name": "outputDocument",
"databaseName": "Ninjas",
"collectionName": "Ninjas",
"createIfNotExists": true,
"connectionStringSetting": "datapointscomsosdb",
"direction": "out"
}
```

That's it! That should now run and execute as you wrote.  The only other note is that if your Azure Functions CLI version (you can see by running the command `func`) is 2.0.1-beta.23 there is a bug in the extension install experience. We're releasing a fix for it *right now* but in the meantime can mitigate by manually installing an older version like: `npm i -g azure-functions-core-tools@2.0.1-beta.22`

**Comment by julielerman** [comment]
func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDb -v 3.0.0-beta6
returns
Value cannot be null.
Parameter name: stream
I'll go look it up

**Comment by jeffhollan** [comment]
Yeah that's the beta.23 bug. If you do `npm i -g azure-functions-core-tools@core` it should grab latest version that has fix

**Comment by julielerman** [comment]
haha look what I found when looking for a solution: https://medium.com/@jeffhollan/serverless-doorbell-ring-com-and-azure-functions-part-2-98bc8fb43e3c :)

**Comment by julielerman** [comment]
silly me... I had installed that earlier but with all of my attempts to fix, I think I overwrote it with another version again. installing now.

**Comment by EricJizbaMSFT** [comment]
I don't think there's anything we need to do from the extension's point of view right now.

We will reevaluate after this: 
> We are doing some work this month so that the funciton.json you had above (or a variant of it) would automatically install extensions when you ran it for you

@julielerman @jeffhollan do you agree?

**Comment by EricJizbaMSFT** [comment]
Closing this since the extensions experience has changed quite a bit since last March
