### ISSUE TITLE
How to bypass  .NET3 | .NET5 in showQuickPick UI

### ISSUE THREAD

**Issue by dmitriklem** [microsoft/vscode-azurefunctions#2760]
I am following code in [this example](https://github.com/microsoft/vscode-azurestaticwebapps/blob/d2816e900a75841abff6a8dcd171de877ca9d9ab/src/commands/createHttpFunction.ts#L27).  Is there any way to provide .NET3 | .NET5 as the parameters/functional settings, so they are not shown in the UI (by showQuickPick) during "funcApi.createFunction" call?

**Comment by nturinski** [comment]
Related: https://github.com/microsoft/vscode-azurestaticwebapps/issues/323
