### ISSUE TITLE
An error pops up when debugging the PowerShell project for the first time

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2763]
**OS:** Win10
**Build Version:** 20210329.1

**Repro Steps:**

1. Create a PowerShell project and open it in VS Code.
2. Set a breakpoint for `run.ps` file and debug.
3. Check whether pop up an error or not.

**Expect:**
No error pops up after pressing F5.

**Actual:**
An error pops up after pressing F5.
![image](https://user-images.githubusercontent.com/57662131/113101617-86588b00-922f-11eb-9555-58eb79e346b8.png)

**More Info:**
1. This issue reproduces when debugging the PowerShell project for the first time.
2. This issue doesn't reproduce when debugging the PowerShell project again.

**Comment by ejizba** [comment]
It appears https://github.com/PowerShell/PowerShellEditorServices/issues/1295 may be the root cause. Will track in https://github.com/microsoft/vscode-azurefunctions/issues/2734
