### ISSUE TITLE
VS code to use ARM api endpoint for getting stacks info

### ISSUE THREAD

**Issue by stefanushinardi** [microsoft/vscode-azurefunctions#2765]
Hello, 

I believe VS code is already querying Functions' stack API ([code](https://github.com/microsoft/vscode-azurefunctions/blob/bed62df359111873a266ad82097abd6b432b7efb/src/commands/createFunctionApp/stacks/getStackPicks.ts#L73)). We recently launched the ARM endpoint for the same API. The baseUrl is `https://management.azure.com/providers/Microsoft.Web/webappstack`

The ask here is to query this endpoint instead of the current one. 

cc: @pragnagopa for more details

**Comment by pragnagopa** [comment]
Correction - Please use `https://management.azure.com/providers/Microsoft.Web/functionappstacks?api-version=2020-10-01`  for function apps
