### ISSUE TITLE
Version 1.3.0 - Bug - Breakpoint not hit in debug mode

### ISSUE THREAD

**Issue by jams4code** [microsoft/vscode-azurefunctions#2771]
Hi there,

So I've posted a similar thread in the past: _https://github.com/microsoft/vscode-azurefunctions/issues/2609_

As explained there, we have some issues with the new versions of Azure functions since > 1.0.1 (last working correctly).

I've just run into the same issue again and now I know from where the issue is coming from:
If you try to run an azure function in a different port than the default one which is 7071, you will not be able to hit a breakpoint in the code.
So basically, we are working in a micro-services architecture, in order to debug we try to run for example two services in local: one having the port:7071 and the other one having the port:7076. On the one having 7071, the is no problem but in the other one (7076), it's impossible to debug.

And the solution, I've found is to run with the 1.0.1 version of the Azure Functions and everything is running smoothly.
So I just wanted to share this with you. Maybe we did something wrong on our side or there is something to investigate in the lib.

### Situation:
**OS Name:** Microsoft Windows 10 Enterprise
**Version:** 10.0.17763 Build 17763
**Language:** .Net/C#
**IDE:** Azure VS Code
**Azure CLI:** V2.10.1
**No error in the screen, not being able to hit a breakpoint in debug mode.**

Kind regards,

Jamal

**Comment by ejizba** [comment]
- How did you change the second app to use port 7076? We have a known issue if you change it in local.settings.json. See more info including a workaround here: https://github.com/microsoft/vscode-azurefunctions/issues/2744
- How are you running both apps? For example, do you have multiple windows of VS Code open or are you using a multi-root workspace in one window
