### ISSUE TITLE
The log "Disconnected from log-streaming service" doesn't display in a new line after executing "Stop Streaming Logs" action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2778]
**OS:** Windows
**Build Version:** 20210422.2

**Repro Steps:**
1. Create a new Windows Function App.
2. Right click this Function App and execute "Start Streaming Logs" action.
3. Execute "Stop Streaming Logs" action.
4. Check if the log "Disconnected from log-streaming service" displays in a new line.

**Expect:**
The log "Disconnected from log-streaming service" displays in a new line.
![image](https://user-images.githubusercontent.com/45614674/115827953-9a169c00-a43f-11eb-8185-7dcd3327e9c9.png)

**Actual:**
The log "Disconnected from log-streaming service" doesn't display in a new line, it will follow to the previous log.
![image](https://user-images.githubusercontent.com/45614674/115827747-4efc8900-a43f-11eb-86ff-5025ad016044.png)

**Comment by ejizba** [comment]
https://github.com/microsoft/vscode-azureappservice/issues/2054#issuecomment-861020982
