### ISSUE TITLE
There is no icons for the "Files" and "Logs" nodes after creating a new Function App

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2779]
**OS:** All
**Build Version:** 20210422.2

**Repro Steps:**

1. Create a new Function App and expand it.
2. Check the nodes of the Function App.

**Expect:**
The icons of the all nodes show well.

**Actual:**
There is no icons for the "Files" and "Logs" nodes.
![image](https://user-images.githubusercontent.com/62053665/115984417-91f26400-a5d9-11eb-9c19-888f66e5427b.png)

**More Info:**
This issue also reproduces for App Service extension.([2023](https://github.com/microsoft/vscode-azureappservice/issues/2023))

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/pull/2766, these icons are now pulled from your theme. You can change it through the command palette:
<img width="271" alt="Screen Shot 2021-04-26 at 10 50 17 AM" src="https://user-images.githubusercontent.com/11282622/116128059-65902380-a67d-11eb-87af-77527e18ed1e.png">

Depending on the theme, it may or may not have icons for folders. Here is one with icons:
<img width="82" alt="Screen Shot 2021-04-26 at 10 55 21 AM" src="https://user-images.githubusercontent.com/11282622/116128549-eb13d380-a67d-11eb-909c-c935ca1bd190.png">
