### ISSUE TITLE
An extra window pops up when F5ing with a Httptrigger.json file opened in the editor

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2780]
**OS:** Win10
**Build Version:** 20210425.1

**Repro Steps:**

1. Create a new JavaScript project -> Open the project in VS Code -> Deploy the project to a Function App.
2. Expand the Function App -> Functions -> Click the function -> Open a .json file in the editor.
3. F5 -> Check whether debug the project successfully.

**Expect:**
Succeed to debug the project without any extra behavior.

**Actual:**
Succeed to debug the project with an extra window pops up.
![fun](https://user-images.githubusercontent.com/62053665/116044827-f4179b80-a6a3-11eb-957f-8b83e20ad8f5.gif)

**More Info:**
This issue also reproduces for other language projects.

**Comment by ejizba** [comment]
I can repro this. The key point is that it happens if you have the _remote_ function.json open, not the local one. Definitely a weird experience, but probably not a super common occurence

**Comment by ejizba** [comment]
Users can workaround this with the following setting if they want:
```
"debug.saveBeforeStart": "none"
```

Because there's a workaround, the behavior is controlled by VS Code (not us), and we think it's somewhat rare - going to close as won't-fix
