### ISSUE TITLE
No overwrite dialog pops up when uploading a setting with empty value to the "Application Settings" node which contained the same one

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2781]
**OS:** Win10
**Build Version:** 20210425.1

**Repro Steps:**

1. Right click "Application Settings" node and select "Add New Setting..." -> Create a setting `test=123`.
2. Right click "Application Settings" node and select "Upload Local Settings..." -> Select a file with the setting `"test": ""`
3. Check whether pop up a dialog to ask for overwriting.

**Expect:**
Pop up a dialog to ask for overwriting.
![image](https://user-images.githubusercontent.com/62053665/116201061-acf4dd80-a76b-11eb-8d11-5ca5c35adcbb.png)

**Actual:**
There is no dialog to ask for overwriting.

**Comment by ejizba** [comment]
If a local app setting is empty, we ignore it and do not change the remote value. See https://github.com/microsoft/vscode-azurefunctions/issues/1523 for more info
