### ISSUE TITLE
unable to debug azure functions powershell locally on macOs

### ISSUE THREAD

**Issue by Suseelraj** [microsoft/vscode-azurefunctions#2783]
I am trying to debug the azure function written in PowerShell locally but the debugger is not hitting with the breakpoints. Any suggestions? I am pasting my launch.json configuration below
` {
            "name": "Attach to PowerShell Functions",
            "type": "PowerShell",
            "request": "attach",
            "customPipeName": "AzureFunctionsPSWorker",
            "runspaceId": 1,
            "preLaunchTask": "func: host start"
        }`

**Comment by ejizba** [comment]
It appears https://github.com/PowerShell/PowerShellEditorServices/issues/1295 may be the root cause. Will track in https://github.com/microsoft/vscode-azurefunctions/issues/2734
