### ISSUE TITLE
Visual Code - Function project creation error

### ISSUE THREAD

**Issue by guruskumar** [microsoft/vscode-azurefunctions#2788]
1.	In Visual Code
2.	Created new workspace, File new window
3.	Selected the Function, Create NEW function Project 
4.	Selected local folder  language as C#  .net core 3
5.	Below error to create functions in VS code, 
Failed to find "autorest" | Extension needs AutoRest to generate a function app from an OpenAPI specification. Click "Learn more" for more details on installation steps.

**Comment by guruskumar** [comment]
[ViscualCode Function Issue.docx](https://github.com/microsoft/vscode-azurefunctions/files/6399012/ViscualCode.Function.Issue.docx)

**Comment by ejizba** [comment]
That error is expected if you select the "HTTP trigger(s) from OpenAPI" template - you can install autorest from the "Learn more" link in the error. If you're not trying to do OpenAPI, please add repro steps for the template you're actually trying to use. Also add the following info:
- Version of the Functions extension
- Version of VS Code
- OS
- Versions of .NET sdk installed on your machine
- Any logs you see from the "Azure Functions" output window

**Comment by guruskumar** [comment]
Please find below details and attached error logs while creating the azure function in VS code.
•	Version of the Functions extension : v1.3.0
•	Version of VS Code                         :1.52.1
•	OS                                                     : Windows 10
•	Versions of .NET sdk installed on your machine: 5.0.101
•	Any logs you see from the "Azure Functions" output window : attached logs 
you can install autorest from the "Learn more" link in the error : we can’t install software’s from  open source.
[functionError.docx](https://github.com/microsoft/vscode-azurefunctions/files/6479003/functionError.docx)
[Functionerror_log.txt](https://github.com/microsoft/vscode-azurefunctions/files/6479004/Functionerror_log.txt)
