### ISSUE TITLE
Code change while debugging results in loss of debug bar

### ISSUE THREAD

**Issue by reks-scripts** [Microsoft/vscode-azurefunctions#279]
I have my function app running locally in debug, make a change to a file, save it and the app restarts properly but the debug toolbar (with step over, step out etc.) disappears even though the app is still running.

**Comment by EricJizbaMSFT** [comment]
What language (e.g. JavaScript, C#, etc.) are you using?

**Comment by fiveisprime** [comment]
I can repro this on Windows with JavaScript.

Saving a file while debugging keeps the host running and does correctly update the code, the debugger is detached. Hitting F5 reattaches to the exisitng process with everything running correctly.

**Comment by EricJizbaMSFT** [comment]
That is expected behavior based on the function cli. See the log:
```
[3/21/18 6:18:08 PM] Job host stopped
info: Worker.Node.b0f63cea-c0c4-4f0d-81bd-5e11b11184ae[0]
      Start Process: node  --inspect=5858 "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 54706 --workerId b0f63cea-c0c4-4f0d-81bd-5e11b11184ae --requestId 453bfa15-30cd-4dc0-a9f1-246aa6200be0
[3/21/18 6:18:08 PM] Generating 1 job function(s)
[3/21/18 6:18:08 PM] Starting Host (HostId=ericsmbp-948613980, Version=2.0.11587.0, ProcessId=56119, Debug=False, ConsecutiveErrors=0, StartupCount=2, FunctionsExtensionVersion=)
[3/21/18 6:18:08 PM] Found the following functions:
[3/21/18 6:18:08 PM] Host.Functions.HttpTriggerJS
[3/21/18 6:18:08 PM]
[3/21/18 6:18:08 PM] Job host started
```

It stops and restarts the node process. If you're looking for support for editing and debugging without stopping the debugger, please file an issue on the function cli to have them keep the job host running throughout https://github.com/Azure/azure-functions-core-tools
