### ISSUE TITLE
[GitHub Codespaces] Fail to debug the Python project with an error

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2791]
**Environment:** GitHub Codespaces (Remote/Local)
**Build Version:** 20210506.4

**Repro Steps:**
1. Create a new Python project with HttpTrigger template.
2. Set a breakpoint and debug it.
3. Check whether debug the project successfully or not.

**Expect:**
Debug the Python project successfully without any error.

**Actual:**
Fail to debug the Python project with an error.
![image](https://user-images.githubusercontent.com/45614674/117414614-ebe41980-af49-11eb-8801-9adad6fc7482.png)
**Terminal log:**
```
> Executing task: .venv/bin/python -m pip install -r requirements.txt <

Requirement already satisfied: azure-functions in ./.venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.7.0)

Terminal will be reused by tasks, press any key to close it.

> Executing task: . .venv/bin/activate && func host start <

Found Python version 3.8.5 (python3).

Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0


Functions:

        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1

For detailed output, run func with --verbose flag.
[2021-05-07T06:34:25.427Z] Worker process started and initialized.
[2021-05-07T06:34:29.498Z] Host lock lease acquired by instance ID '000000000000000000000000BCEC4447'.
```

**More Info:**
This issue does not reproduce on Non-Codespaces environment.

**Comment by ejizba** [comment]
It's possible pylint is just slow to read your dependencies. Does the error go away if you reload the window and try to debug again?

**Comment by v-ruizh** [comment]
@ejizba Sorry for the late reply. Reloading the windows can't fix this issue. The error still exists after reloading the window and debug again.

**Comment by ejizba** [comment]
I don't think this is something we can fix, but I should try it on Codespaces myself
