### ISSUE TITLE
failed, reason: read ECONNRESET - Deploy to Function App 

### ISSUE THREAD

**Issue by blomm** [microsoft/vscode-azurefunctions#2795]
(Please don't mark as duplicate, this is on a Mac)

Does this occur consistently? Yes
Repro steps:

Create an azure function in VS Code
Deploy to Function App from VS Code.
Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: **request to https:/blahblahblah.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET**

Version of azure-functions-core-tools : 3 (brew install azure-functions-core-tools@3)
OS: **Mac**
OS Release: Big Sur and Catalina

Tried with multiple versions of VS code, below is March 2021 (tried to rollback), was initially using April 2021:
Version: 1.54.3 
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (1 mo ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

I've tried switching between Node 8 - 10 - 12 - 14, but no luck

This was working on my laptop (Big Sur), then it stopped. I'm not sure what changed.

Publishing azure functions was still working on my desktop (Catalina), so I used this.  Then I restarted VS code, and now it doesn't work here either.

I've tried:

- Signing in and out of Azure
- Rolling back versions of VS code
- All acceptable versions of Node
- Using Yarn commands in settings.json (instead of npm)

I'm totally stuck, I've read and tried everything on the internet, but no luck.

**Comment by ejizba** [comment]
"ECONNRESET" is an error code coming from Azure, so it's unlikely to be affected by your local setup like Node.js version, VS Code version, or OS. It _may_ be related to the Azure Functions extension version, but I have not heard of any widespread problems with v1.3.0 and it's been out a decent while. We've tried to reduce the number of "ECONNRESET" errors (usually just retrying the request does the trick), but it's virtually impossible to eliminate them completely.

The most likely cause of the error is the function app in Azure itself, so a few questions about that:
- How did you create it - though VS Code, the portal, etc.?
- Is it using a consumption plan?
- Is it using Windows or Linux?

Another source of this error could be your project itself. Is it by chance a particularly large project? Do you see the error if you deploy a simple project with just an Http trigger?

**Comment by blomm** [comment]
thanks for replying @ejizba 

- I created the functions through the vs code azure functions extension
- I'm not sure what you mean by consumption plan
- I'm using a mac

This was definitely working on two different Macs.  One Mac upgraded and deployment stopped working, then when the 2nd machine upgraded, it also stopped working.

Both now work fine once rolled back, sorry I can't help more.

**Comment by ejizba** [comment]
This issue is not usually related to local machine setup like OS or extension version. It's a transient issue related to our connection to Azure. In any case, closing in favor of https://github.com/microsoft/vscode-azurefunctions/issues/2844
