### ISSUE TITLE
[Functions][Stacks] Support hidden stacks

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/vscode-azurefunctions#2805]
This is a follow up for https://github.com/microsoft/vscode-azurefunctions/pull/2803

Please note that Powershell stack on Linux is marked as `Hidden` - https://github.com/Azure/azure-functions-ux/blob/42fba774382c6f72b76e65f428a36189f46abbdc/server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts#L40

This is a feature request to allow creating stacks marked as `Hidden`  only if user requests by passing an explicit flag. We intend to mark stacks as `Hidden` while the backend changes are rolling out. Having support for hidden flag gives ability for the product team to test E2E while backend changes are rolling out.
 
cc @ejizba @stefanushinardi @Francisco-Gamino

**Comment by ejizba** [comment]
This is already supported by the VS Code setting `azureFunctions.showHiddenStacks`

**Comment by pragnagopa** [comment]
@ejizba  - Can you point to instructions how to set  `azureFunctions.showHiddenStacks`  ?

**Comment by ejizba** [comment]
It's a standard VS Code setting, so these docs should apply: https://code.visualstudio.com/docs/getstarted/settings
