### ISSUE TITLE
There is no warning "Only plans in the region 'xxx' are shown" in the Command list when creating a premium function app with Southeast Asia location 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2806]
**OS:** Windows
**Build Version:** 20210514.8

**Repro Steps:**
1. Create an advanced function app with Southeast Asia location and premium hosting plan.
2. Check whether show a warning "Only plans in the region 'xxx' are shown" when asking to select a App Service Plan.

**Expect:**
Show a warning "Only plans in the region 'xxx' are shown" when asking to select a App Service Plan, like below:
![image](https://user-images.githubusercontent.com/57662131/118790760-a66c0880-b8c8-11eb-8bde-74f5603995b2.png)

**Actual:**
There is no warning "Only plans in the region 'Southeast Asia' are shown" when asking to select a App Service Plan.
![image](https://user-images.githubusercontent.com/57662131/118791091-f77bfc80-b8c8-11eb-8550-b22a8870531b.png)

**More Info:**
 This issue doesn't reproduce for App Service plan and Consumption hosting plan.

**Comment by ejizba** [comment]
We only show that warning if we are hiding plans that otherwise would've been shown. My guess is that you don't have any other Linux Premium plans, so that's why we don't show the warning.

**Comment by v-xinda** [comment]
@ejizba It still doesn't show warning after creating a Linux Premium plans.
![image](https://user-images.githubusercontent.com/57662131/118909438-9817fe00-b955-11eb-8b12-e7dfde024ba6.png)

**Comment by v-xinda** [comment]
Got it, Thanks for your sharing.
