### ISSUE TITLE
Re: How to call from AL or C/SIDE the Windows Print Dialog Window - Print Report, Excel or Word or PDF local files.

### ISSUE THREAD

**Issue by dennisaubrey** [Microsoft/vscode-azurefunctions#281]
Re: How to call from AL or C/SIDE the Windows Print Dialog Window - Print Report, Excel or Word or PDF local files.
Hello,
.NET is no longer supported in Dynamics NAV 2018 on AZURE. D365.
The AZURE functions allow a C# .NET program through create function.
Looking for sample AZURE code unit for a Function callable from AL and C/SIDE to Prompt the Operator for the Local Print Dialog Window displaying a list of available printers from the desktop client. The solution would print either; a) Excel file b) Word Document or c) PDF document or d) a NAV 2018 Report from the Desktop NAV Windows Client or from the Web Client.
Thank you
Dennis Aubrey

**Comment by EricJizbaMSFT** [comment]
Here is the repo for Azure Function templates: https://github.com/Azure/azure-functions-templates

Please file an issue in that repo if you want a template for AL or C/SIDE
