### ISSUE TITLE
The warning dialog is confused if debug the outside C# project without detected dialog

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2810]
**OS:** All
**Build Version:** 20210521.1

**Repro Steps:**
1. Make sure install C# extension in VS Code.
2. Create a C# project from func cli -> Open it in VS Code.
3. Ignore the below detected dialog and debug the project directly.
![image](https://user-images.githubusercontent.com/57662131/119095798-51093600-ba45-11eb-95d0-6ae7e32e1134.png)
4. Check whether the warning dialog is clear or not.

**Expect:**
The warning dialog is clear.

**Actual:**
The warning dialog is confused.
![image](https://user-images.githubusercontent.com/57662131/119089795-4c408400-ba3d-11eb-9377-2385b997e92a.png)

**More Info:**
This issue doesn't reproduce for Python and Nodejs projects.

**Comment by ejizba** [comment]
The screenshot in "Actual" is coming from VS Code not us. We may or may not be able to listen in to the debug process, but since we have no way of knowing for sure if this is a functions project we don't want to interrupt the users debugging.
