### ISSUE TITLE
[Suggestion] Add a "output window" link in the notification when creating a Function App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2811]
**OS:** All
**Build Version:** 20210521.1

**Repro Steps:**
1. Create a new function app.
2. Check the popped up notification.

**Actual:**
There is no "output window" link in the notification.
![image](https://user-images.githubusercontent.com/57662131/119097952-e73e5b80-ba47-11eb-97f0-802fc17541a3.png)

**Suggestion:**
Add a "output window" link in the notification when creating a Function App, like below:
![image](https://user-images.githubusercontent.com/57662131/119098045-00dfa300-ba48-11eb-8b45-42128b7fa7e7.png)

**Comment by ejizba** [comment]
We don't think the link is necessary since in this case we show the logs directly in the notification as they happen
