### ISSUE TITLE
Pop up an error "Authentication failed" when creating a new function app with Azure China/Germany account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2812]
**OS:** All
**Build Version:** 20210521.1

**Repro Steps:**
1. Sign in with Azure China/Germany account.
2. Create a new function app.
3. Check whether the web app is created successfully or not.

**Expect:**
The function app is created successfully without any error.

**Actual:**
Pop up an error "Authentication failed" when creating a new function app.
![image](https://user-images.githubusercontent.com/57662131/118762163-4bc2b480-b8a8-11eb-9e85-9623378640ed.png)

**Comment by ejizba** [comment]
Can you give more details about when you are seeing that issue? For example, what is the last prompt you were able to see? If it's failing after the prompts, please copy the output logs here

Related to https://github.com/microsoft/vscode-azureappservice/issues/2058

**Comment by v-xinda** [comment]
@ejizba 
Advanced create: Pop up this issue when asking to select a runtime, and display `10:27:53 AM: Error: Authentication failed.` in output window. 
Basic create: Pop up this issue after entering the name, the output message is same with the advanced.
More details as below:
![function](https://user-images.githubusercontent.com/57662131/119288728-b8103000-bc7b-11eb-8321-779723fef683.gif)
