### ISSUE TITLE
Fail to debug the Java project on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2813]
**OS:** Mac
**Build Version:** 20210521.1

**Repro Steps:**

1. Create a Java project -> Debug.
2. Check whether debug successfully or not.

**Expect:**
Succeed to debug the Java project.

**Actual:**
Fail to debug the Java project.
![Screen Shot 2021-05-21 at 10 47 47 AM](https://user-images.githubusercontent.com/62053665/119107661-05a95480-ba52-11eb-8347-005d3cd39731.png)
![Screen Shot 2021-05-21 at 2 28 07 PM](https://user-images.githubusercontent.com/62053665/119107652-03df9100-ba52-11eb-985d-ba15544a7c7a.png)

**More Info:**
This issue doesn't reproduce on Windows.

**Comment by ejizba** [comment]
I see the "shared memory usage" warning, but otherwise it's working for me on my mac. Can you confirm your JAVA_HOME is set and that the path specified in the red error exists? It might be an issue with the Java setup on your machine.

**Comment by v-mengwe** [comment]
I execute the command `vim ~/.bash_profile`, and set the JAVA_HOME as below:
![Screen Shot 2021-06-01 at 4 40 25 PM](https://user-images.githubusercontent.com/62053665/120294398-bb00c580-c2f8-11eb-90f2-dcc898d7192d.png)

**Comment by ejizba** [comment]
And does the path exist? The error in the screenshot seems to imply it does not

Also try opening up a terminal in VS Code and do `echo $JAVA_HOME` just to make sure your bash_profile is taking effect

**Comment by v-mengwe** [comment]
The added path exists, but execute `echo $JAVA_HOME` in the terminal of VS Code:
![Screen Shot 2021-06-04 at 10 12 34 AM](https://user-images.githubusercontent.com/62053665/120735737-bbc67100-c51d-11eb-841a-f1bcd8fb7986.png)
Does bash_profile not take effect? Could you help to give me some guidance?

**Comment by ejizba** [comment]
I don't know what's going on there. You could try setting it in a `.bashrc` file instead of `.bash_profile`. Regardless, since your JAVA_HOME isn't set this sounds like a machine configuration issue rather than an issue with the extension. I'll go ahead and close this issue
