### ISSUE TITLE
support.md is missing

### ISSUE THREAD

**Issue by zowazHC5** [microsoft/vscode-azurefunctions#2814]
Microsoft open-source projects need to have a support.md file in the repo explaining the support policy for the project.

**Comment by ejizba** [comment]
I'm not aware of that requirement and I don't couldn't find a "support.md" file in any repos I commonly use from Microsoft (e.g. repos related to VS Code, Azure Functions, or .NET). Please point us to docs and/or other repos that have a "support.md" file
