### ISSUE TITLE
Resources don't displayed.

### ISSUE THREAD

**Issue by Hakuroda** [microsoft/vscode-azurefunctions#2818]
Does this occur consistently? / Yes
Repro steps:
1. To open App Service resources with Azure extensions - APP SERVICE or FUNCTIONS tab on VSCode.

Even if some app service resources are deployed in my subscription but any resource doesn't see.
![image](https://user-images.githubusercontent.com/67581008/119304276-ffa9b280-bca1-11eb-99bd-04f5f90ca08d.png)

I repeated log-out and log-in from Azure but this behavior didn't change. And I can see all STORAGEs under my subscription.
![image](https://user-images.githubusercontent.com/67581008/119304467-3ed80380-bca2-11eb-9030-3115366818d4.png)

Next I opened VS and I can see app service resources under my subscription.
![image](https://user-images.githubusercontent.com/67581008/119304618-7941a080-bca2-11eb-88f9-da67badedbdc.png)

So I think this problem comes from extension App Service or Functions.

Version: 1.3.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.56.2
Language: ja

**Comment by ejizba** [comment]
A few questions

- Can you give more information about your function apps? For example - how did you create them and what options did you choose when creating?
- Is there anything you can think of that may be unique about your subscription?
- I assume you can see these function apps listed in the portal?

**Comment by Hakuroda** [comment]
Hi @ejizba 

Thank you for your help.

**ANSWER**
> Can you give more information about your function apps? For example - how did you create them and what options did you choose when creating?

I created functions on Azure portal not from Azure CLI or something. And SKUs are different, Consumption, EP or App Service. I think all resource is healthy and stable.

> Is there anything you can think of that may be unique about your subscription?

I don't think my subscription is unique. 

> I assume you can see these function apps listed in the portal?

Yes. All functions can see on Azure portal.


**UPDATE**
I deleted some resources then it started to display FUNCTIONS on my VSCode. I'm not sure which resource affected. I think some resource returned error then VSCode can't display resources...
![image](https://user-images.githubusercontent.com/67581008/119422067-1ea85300-bd3b-11eb-9222-2070c38a9638.png)

I'll try to find out the cause. If you have findings please give comment.

**Comment by ejizba** [comment]
> I deleted some resources then it started to display FUNCTIONS on my VSCode. I'm not sure which resource affected. I think some resource returned error then VSCode can't display resources...

Interesting - yeah let us know if you figure out which type of resource may have been causing an error. 

Note to self: This may be fixed if we use a Resource Graph query to get sites instead of the Microsoft.Web list api

**Comment by Hakuroda** [comment]
Asked MS support desk. We can't resolve this issue by ourselves.
