### ISSUE TITLE
ECONNRESET error - deploying Azure functions from VS code

### ISSUE THREAD

**Issue by HarRashi** [microsoft/vscode-azurefunctions#2827]
Hi,

I'm experiencing ECONNRESET error while trying to deploy Azure functions (with C#) from VS code to Azure cloud. It is noted that the Python version has no deployment error. Any help would be appreciated with C# version deployment from VS code.

Thanks!

[
![VSCode_Error_ECONNRESET](https://user-images.githubusercontent.com/79232155/119730945-551dc500-be44-11eb-936e-db610e3b3d01.png)
](url)

**Comment by ejizba** [comment]
These errors are a bit difficult for us to debug - a lot of times it'll just work if you try again. Do you have any more specific repro steps that might help us narrow down the issue?

**Comment by ejizba** [comment]
Closing in favor of https://github.com/microsoft/vscode-azurefunctions/issues/2844
