### ISSUE TITLE
There is an error under the "Functions" node after creating a Linux .NET function app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2829]
**OS:** Win10
**Build:** 20210525.7

**Repro Steps:**
1. Create a Linux function app with .NET 5/.NET Core 3.1 runtime.
2. Expand the function app -> Expand the "Functions" node.
3. Check whether there is an error under the "Functions" node or not.

**Expect:**
There is no error under the "Functions" node.

**Actual:**
There is an error under the "Functions" node.
![image](https://user-images.githubusercontent.com/57662131/119625102-6b278780-be3c-11eb-8ff7-af303b91f4cf.png)

**More Info:**
1. This issue doesn't reproduce for other runtime function apps.
2. This issue doesn't reproduce for Windows  .NET function app.
3. This issue can be fixed by refreshing the "Functions" node.

**Comment by ejizba** [comment]
There's not much we can do about ServiceUnavailable errors coming from Azure. Since it's fixed by a refresh, we'll go ahead and close as external
