### ISSUE TITLE
Extension truncates list of Github repos

### ISSUE THREAD

**Issue by burkeholland** [Microsoft/vscode-azurefunctions#283]
When configuring deployment from Github, the extension is truncating the full list of repos for any Github account.

### Environment
MacOS: 10.13.3
Extension: 0.7.0
VS Code: 1.21.1

## Steps to reproduce

* Right-click and select "Configure deployment source"
* Select "Github"
* Select a Github account from the list

### Expected Behaviour
All repos for the account are shown

### Actual Behaviour
Only the first 30 repos for the account are shown. Any other repos are not shown and are impossible to select.

Video: https://www.screencast.com/t/iIXgHdYHGk7

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azuretools/pull/170
Package updated in https://github.com/Microsoft/vscode-azurefunctions/pull/345
