### ISSUE TITLE
Azure Function not able to debug anymore with vscode

### ISSUE THREAD

**Issue by Ymarion345** [microsoft/vscode-azurefunctions#2831]
When a start the debug with F5 normally you can see debugging in the first line but this what I got and none of my break point works 
![image](https://user-images.githubusercontent.com/60008767/119701356-3dcde000-be22-11eb-9bd7-43be441dc58b.png)

I have read to debug you have to be in 64 but its my case and i have not change nothing in my setting since the last time (about two weeks or a little bit more) i run this function locally 

Normally its suppose to start like this right ? 
![image](https://user-images.githubusercontent.com/60008767/119701971-eda34d80-be22-11eb-9fc4-96f291d8bb3f.png)

Everything was working fine 2-3 weeks ago, I have not change anything since the last time I ran my debug on the function

**Comment by ejizba** [comment]
Can you give more details about your project? What language is it and perhaps show a screenshot of your workspace?

You will only see a url like the second screenshot if your trigger is an 'http' trigger. It appears like instead you have a timer trigger

**Comment by Ymarion345** [comment]
My points was that the debugger listening on ... was not there for my first screenshot sorry, I was thinking it's not normal if I compare with the official doc (second screenshot) .

Here's more info 

I code in c# 
here is my csproj
![image](https://user-images.githubusercontent.com/60008767/119877738-65db4300-bef7-11eb-8d8f-35cf6dd5713d.png)
here my host 
![image](https://user-images.githubusercontent.com/60008767/119877899-91f6c400-bef7-11eb-91f4-7d350d649c69.png)
extension.json
![image](https://user-images.githubusercontent.com/60008767/119877956-a20ea380-bef7-11eb-8db6-08193fca5e10.png)
launch
![image](https://user-images.githubusercontent.com/60008767/119878030-b0f55600-bef7-11eb-90c7-eac5af3518a6.png)
setting 
![image](https://user-images.githubusercontent.com/60008767/119878077-bce11800-bef7-11eb-9ff4-8b86eacbf99b.png)
task 
![image](https://user-images.githubusercontent.com/60008767/119878316-fca7ff80-bef7-11eb-92bd-1c5557d1e067.png)

If you need more just tell me if the first time that my azure function can't debug i don't know what send you that's not important information from the code

**Comment by ejizba** [comment]
Ah yeah it's normal that you don't see "Debugger listening on" for a C# project. That log is only relevant for a Node.js project.

What version of the Functions extension in VS Code are you using?

**Comment by Ymarion345** [comment]
v1.4.0
![image](https://user-images.githubusercontent.com/60008767/119879970-c8354300-bef9-11eb-9755-49b3a94b0361.png)

**Comment by ejizba** [comment]
Okay debugging _should_ work on that version. A few more questions

- What OS are you on?
- How did you install the func cli (npm, choco, brew, apt-get, etc.)?
- Are you seeing any errors, either in the terminal output or as a notification? Or is it silently failing without letting you hit a breakpoint
- Is VS Code actually attaching to something? You can tell based on the icons for the debug menu at the top - just make sure to wait a while (like a minute?) to see if it's just slow:
    - Before we attach
    ![Screen Shot 2021-05-27 at 11 59 58 AM](https://user-images.githubusercontent.com/11282622/119882287-1d198f00-bee3-11eb-9854-57608c07c718.png)
    - After we've attached:
    ![Screen Shot 2021-05-27 at 11 58 44 AM](https://user-images.githubusercontent.com/11282622/119882188-fb200c80-bee2-11eb-938e-b35923db68bb.png)

**Comment by Ymarion345** [comment]
- I'm on Microsoft OS 
- we try with npm, func-cli-x64 and choco
- No it's in silently all breakpoint are ignore
- it's attached but fail and kick me out instantly

**Comment by ejizba** [comment]
Okay as a workaround, you can try changing your `.vscode/launch.json` to this:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to .NET Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:pickProcess}",
      "preLaunchTask": "func: host start"
    }
  ]
}
```

Rather than us picking the right process to attach to, it will prompt you and you will have to pick the process yourself. For me, it's the very first 'dotnet' process which also mentions my project name "cs3"
![Screen Shot 2021-06-03 at 6 01 50 PM](https://user-images.githubusercontent.com/11282622/120730262-f71d5d00-c495-11eb-80a3-0582426833b9.png)

You can try a few different processes to see if maybe a different one works for you. If one of those processes works, let us know which one and we may need to update our automatic detection logic.
