### ISSUE TITLE
Azure Core Functions Extension Update Failed in VS Code

### ISSUE THREAD

**Issue by kathleenwest** [microsoft/vscode-azurefunctions#2832]
I have previously installed and used the Azure Core Functions extension in VS Code with my Azure Services. This extension did not successfully update. 

I have previously installed unzipper. Here is my version:
`> npm unzipper -v
7.10.0`

The error log is shown below since there is not an option to attach it.

`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'azure-functions-core-tools@3'
0 verbose cli ]
1 info using npm@7.10.0
2 info using node@v16.0.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\kathl\AppData\Local\Temp\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\kathl\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\kathl\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 9ms
18 timing npm:load:configload Completed in 9ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 16ms
25 timing config:load:flatten Completed in 3ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 9ms
28 timing idealTree:userRequests Completed in 5ms
29 silly idealTree buildDeps
30 silly fetch manifest azure-functions-core-tools@3
31 http fetch GET 304 https://registry.npmjs.org/azure-functions-core-tools 538ms (from cache)
32 silly placeDep ROOT azure-functions-core-tools@3.0.3568 OK for:  want: 3
33 silly fetch manifest chalk@3.0.0
34 silly fetch manifest command-exists@1.2.8
35 silly fetch manifest glob@7.1.6
36 silly fetch manifest https-proxy-agent@5.0.0
37 silly fetch manifest progress@2.0.3
38 silly fetch manifest rimraf@3.0.2
39 silly fetch manifest tmp@0.1.0
40 silly fetch manifest unzipper@0.10.10
41 http fetch GET 304 https://registry.npmjs.org/command-exists 64ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/chalk 191ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/rimraf 183ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/progress 191ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 194ms (from cache)
46 http fetch GET 304 https://registry.npmjs.org/glob 195ms (from cache)
47 http fetch GET 304 https://registry.npmjs.org/tmp 188ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/unzipper 192ms (from cache)
49 timing idealTree:#root Completed in 764ms
50 timing idealTree:buildDeps Completed in 764ms
51 timing idealTree:fixDepFlags Completed in 1ms
52 timing idealTree Completed in 780ms
53 timing reify:loadTrees Completed in 824ms
54 silly reify mark deleted [
54 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\balanced-match'
54 silly reify ]
55 silly reify mark deleted [
55 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\ansi-styles'
55 silly reify ]
56 silly reify mark deleted [
56 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\agent-base'
56 silly reify ]
57 silly reify mark deleted [
57 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\big-integer'
57 silly reify ]
58 silly reify mark deleted [
58 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\binary'
58 silly reify ]
59 silly reify mark deleted [
59 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\bluebird'
59 silly reify ]
60 silly reify mark deleted [
60 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\brace-expansion'
60 silly reify ]
61 silly reify mark deleted [
61 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\chainsaw'
61 silly reify ]
62 silly reify mark deleted [
62 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\chalk'
62 silly reify ]
63 silly reify mark deleted [
63 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\buffers'
63 silly reify ]
64 silly reify mark deleted [
64 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\buffer-indexof-polyfill'
64 silly reify ]
65 silly reify mark deleted [
65 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\color-convert'
65 silly reify ]
66 silly reify mark deleted [
66 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\color-name'
66 silly reify ]
67 silly reify mark deleted [
67 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\concat-map'
67 silly reify ]
68 silly reify mark deleted [
68 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\command-exists'
68 silly reify ]
69 silly reify mark deleted [
69 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\duplexer2'
69 silly reify ]
70 silly reify mark deleted [
70 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\debug'
70 silly reify ]
71 silly reify mark deleted [
71 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\core-util-is'
71 silly reify ]
72 silly reify mark deleted [
72 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream'
72 silly reify ]
73 silly reify mark deleted [
73 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\glob'
73 silly reify ]
74 silly reify mark deleted [
74 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fs.realpath'
74 silly reify ]
75 silly reify mark deleted [
75 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\has-flag'
75 silly reify ]
76 silly reify mark deleted [
76 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\graceful-fs'
76 silly reify ]
77 silly reify mark deleted [
77 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\https-proxy-agent'
77 silly reify ]
78 silly reify mark deleted [
78 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\inflight'
78 silly reify ]
79 silly reify mark deleted [
79 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\isarray'
79 silly reify ]
80 silly reify mark deleted [
80 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\minimatch'
80 silly reify ]
81 silly reify mark deleted [
81 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\inherits'
81 silly reify ]
82 silly reify mark deleted [
82 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\listenercount'
82 silly reify ]
83 silly reify mark deleted [
83 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\minimist'
83 silly reify ]
84 silly reify mark deleted [
84 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\mkdirp',
84 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp',
84 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp.cmd',
84 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp.ps1'
84 silly reify ]
85 silly reify mark deleted [
85 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\ms'
85 silly reify ]
86 silly reify mark deleted [
86 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\once'
86 silly reify ]
87 silly reify mark deleted [
87 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\process-nextick-args'
87 silly reify ]
88 silly reify mark deleted [
88 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\path-is-absolute'
88 silly reify ]
89 silly reify mark deleted [
89 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\readable-stream'
89 silly reify ]
90 silly reify mark deleted [
90 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\setimmediate'
90 silly reify ]
91 silly reify mark deleted [
91 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\rimraf',
91 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf',
91 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf.cmd',
91 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf.ps1'
91 silly reify ]
92 silly reify mark deleted [
92 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\safe-buffer'
92 silly reify ]
93 silly reify mark deleted [
93 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\progress'
93 silly reify ]
94 silly reify mark deleted [
94 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\supports-color'
94 silly reify ]
95 silly reify mark deleted [
95 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\string_decoder'
95 silly reify ]
96 silly reify mark deleted [
96 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp'
96 silly reify ]
97 silly reify mark deleted [
97 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\unzipper'
97 silly reify ]
98 silly reify mark deleted [
98 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\traverse'
98 silly reify ]
99 silly reify mark deleted [
99 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\wrappy'
99 silly reify ]
100 silly reify mark deleted [
100 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\util-deprecate'
100 silly reify ]
101 silly reify mark deleted [
101 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\@types\\color-name'
101 silly reify ]
102 silly reify mark deleted [
102 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\rimraf',
102 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf',
102 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf.cmd',
102 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf.ps1'
102 silly reify ]
103 silly reify mark deleted [
103 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\rimraf',
103 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf',
103 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf.cmd',
103 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf.ps1'
103 silly reify ]
104 timing reify:diffTrees Completed in 6ms
105 silly reify mark retired [
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func.cmd',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func.ps1',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun.cmd',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun.ps1',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions.cmd',
105 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions.ps1'
105 silly reify ]
106 silly reify moves {
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\.azure-functions-core-tools-ibuLndha',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.func-qA1NmGWp',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func.cmd': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.func.cmd-GRNctt0g',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\func.ps1': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.func.ps1-cCmBKth4',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azfun-YJdOx8OA',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun.cmd': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azfun.cmd-h6Gl4pPO',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azfun.ps1': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azfun.ps1-tO3dM17C',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azurefunctions-slcBZAHy',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions.cmd': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azurefunctions.cmd-08dOgOWx',
106 silly reify   'C:\\Users\\kathl\\AppData\\Roaming\\npm\\azurefunctions.ps1': 'C:\\Users\\kathl\\AppData\\Roaming\\npm\\.azurefunctions.ps1-71Kzn8G0'
106 silly reify }
107 timing reify:retireShallow Completed in 12ms
108 timing reify:createSparse Completed in 0ms
109 timing reify:loadBundles Completed in 0ms
110 timing reifyNode:node_modules/azure-functions-core-tools Completed in 23ms
111 timing reify:unpack Completed in 24ms
112 timing reify:unretire Completed in 0ms
113 timing build:queue Completed in 3ms
114 timing build:link:node_modules/azure-functions-core-tools Completed in 11ms
115 timing build:link Completed in 11ms
116 info run azure-functions-core-tools@3.0.3568 postinstall node_modules/azure-functions-core-tools node lib/install.js
117 info run azure-functions-core-tools@3.0.3568 postinstall { code: 1, signal: null }
118 timing reify:rollback:createSparse Completed in 5ms
119 timing reify:rollback:retireShallow Completed in 8ms
120 timing command:install Completed in 991ms
121 verbose stack Error: command failed
121 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
121 verbose stack     at ChildProcess.emit (node:events:365:28)
121 verbose stack     at maybeClose (node:internal/child_process:1067:16)
121 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
122 verbose pkgid azure-functions-core-tools@3.0.3568
123 verbose cwd C:\Users\kathl\AppData\Local\Temp
124 verbose Windows_NT 10.0.19043
125 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "azure-functions-core-tools@3"
126 verbose node v16.0.0
127 verbose npm  v7.10.0
128 error code 1
129 error path C:\Users\kathl\AppData\Roaming\npm\node_modules\azure-functions-core-tools
130 error command failed
131 error command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
132 error node:internal/modules/cjs/loader:943
132 error   throw err;
132 error   ^
132 error
132 error Error: Cannot find module 'unzipper'
132 error Require stack:
132 error - C:\Users\kathl\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
132 error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
132 error     at Function.Module._load (node:internal/modules/cjs/loader:773:27)
132 error     at Module.require (node:internal/modules/cjs/loader:1012:19)
132 error     at require (node:internal/modules/cjs/helpers:93:18)
132 error     at Object.<anonymous> (C:\Users\kathl\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
132 error     at Module._compile (node:internal/modules/cjs/loader:1108:14)
132 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
132 error     at Module.load (node:internal/modules/cjs/loader:988:32)
132 error     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
132 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
132 error   code: 'MODULE_NOT_FOUND',
132 error   requireStack: [
132 error     'C:\\Users\\kathl\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
132 error   ]
132 error }
133 verbose exit 1
`

**Comment by ejizba** [comment]
Looks like this may be a common issue on the func cli. I would encourage you to try the suggestions mentioned over in https://github.com/Azure/azure-functions-core-tools/issues/2526 and track that issue instead
