### ISSUE TITLE
[Codespaces] There is an error in the TERMINAL after debugging a Java project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2833]
**Environment:** Local Codespcaces
**Build:** 20210527.1

**Repro Steps:**

1. Create a Java project -> Debug.
2. Check the TERMINAL.

**Expect:**
There is no error in the TERMINAL.

**Actual:**
There is an error in the TERMINAL.
![image](https://user-images.githubusercontent.com/62053665/120299464-9824e000-c2fd-11eb-88e2-69453db8e099.png)

**More Info:**
This issue doesn't reproduce on Windows.

**Comment by jinglouMSFT** [comment]
We haven't modified the code for debugging Java project recently.  Has this just happened recently or it has been there for awhile?  Also, it's pretty hard to setup the Java dev environment in Codespaces. Was it setup the way it used to be set?  Thanks.

**Comment by v-mengwe** [comment]
Verified on the Functions extension latest release build 1.4.0, this issue also reproduces. This error does not affect the debugging and breakpoints of the Java project. 
Copy the function url from "Local Project" -> Execute **`curl [the copied url]`** command:
![image](https://user-images.githubusercontent.com/62053665/120599738-76049c80-c47a-11eb-92fa-6a2e20882691.png)
There is no need to set up a Java development environment in Codespaces, it can be used directly by default.

**Comment by ejizba** [comment]
The error is coming from the func cli and/or the java worker within the func cli. It could be a problem with the CodeSpaces environment, but even if it's a bug we unfortunately do not control that part of it
