### ISSUE TITLE
Unit 3 Instructions in Microsoft Learn "Enable automatic updates in a web application using Azure Functions and SignalR Service"

### ISSUE THREAD

**Issue by svenssj** [microsoft/vscode-azurefunctions#2834]
So in the module "Enable automatic updates in a web application using Azure Functions and SignalR Service" at Microsoft Learn there is a issue with the instructions in Unit 3.

The instructions says : "Run the following command in Azure Cloud Shell from the portal to clone the app from GitHub." 

This will not work since the rest of the exercise requires that the code is cloned to your local machine.

The instructions should be something along the lines of: "Run the following command a Visual Studio Code Terminal to clone the app from GitHub."

![image](https://user-images.githubusercontent.com/17668267/120463063-d1139200-c39b-11eb-91eb-f808f3720a01.png)

**Comment by ejizba** [comment]
My team does not directly own the content of the learn module - please use the "Reporting an issue" link at the bottom of the learn module page and it will direct you to a better place to file an issue. 

It's possible the docs are correct. If you do `code start` in the cloud shell as they describe, it will open up a nifty little version of VS Code in your browser, so you may be able to do the whole learn module in the browser against the remote environment. Of course, you can also clone it locally if you would prefer your local environment with a full VS Code. I'm not sure what the authors of that article intended (using the browser VS Code or using a local VS Code), but as mentioned you're welcome to file an issue directly on the module if you still think something needs updating
