### ISSUE TITLE
App Insights APM 2.1 Enablement and Representation

### ISSUE THREAD

**Issue by apawast** [microsoft/vscode-azurefunctions#2835]
**Problem**

App Insights has introduced APM 2.1 which integrates log analytics and application insights logs into a workspace so a user can view all their logs in one place. Currently, when VSCode creates an application insights resource during a function creation, a 2.1 workspace is used by default. Portal has created a new experience to be able to change/create a workspace within the Function create blade. The logic behind when a user is allowed to create a new workspace is complicated in Portal. The ask is for VSCode to be on par with Portal’s capabilities around APM 2.1.  

**Background** 

This is how Portal works today: 

<img width="1174" alt="Screen Shot 2021-05-27 at 9 07 22 PM" src="https://user-images.githubusercontent.com/47400341/120552883-ce2d9700-c3c5-11eb-831d-e239e404042c.png">

When you go to the monitoring tab of Function creation blade, Portal always automatically autofills with a new application insights resource. The user can also choose to select an existing resource from the drop down. If the user wants to, they can go forward with no more configuration.  

The third option is to click “create new” and see the default options AI created and change them.  

 <img width="1175" alt="Screen Shot 2021-05-27 at 9 07 39 PM" src="https://user-images.githubusercontent.com/47400341/120552914-da195900-c3c5-11eb-9162-8ae6a11a259c.png">

However, Portal uses complicated logic to determine when to allow the user to create a default workspace or an existing workspace.  

This is how it works in VSCode today: 

In VSCode if the user chooses simple function app creation, then an app insights resource is created by default when published. If the user chooses advanced function app creation, then they get the choice to use an existing AI resource or create a new one. 

 
<img width="602" alt="Screen Shot 2021-05-27 at 9 08 26 PM" src="https://user-images.githubusercontent.com/47400341/120553167-2f556a80-c3c6-11eb-84cb-3dbf2c814012.png">

If the user chooses to create a new one, similarly to Portal, VSCode autofills a name for the resource in the same region. There is no choice for further configuration. 

<img width="607" alt="Screen Shot 2021-05-27 at 9 50 08 PM" src="https://user-images.githubusercontent.com/47400341/120553222-3b412c80-c3c6-11eb-83b1-d50164388b2e.png">

**Requirements** 

- VSCode is on par for APM 2.1 support with Portal. The logic can be found in the [Antares UX OneNote](https://microsoft.sharepoint.com/teams/Antares/_layouts/15/Doc.aspx?sourcedoc={8931556f-5e09-45af-9259-4585eb3b3bb2}&action=edit&wd=target%28Features.one%7Cfb091e2e-b416-4585-9e57-57ef36249fea%2FApp%20Insights%20%E2%80%93%20APIM2.1%7Ce102253f-6464-4455-9e84-cfa85e16c040%2F%29&wdorigin=703)
- Add a new step to the Functions creation process to allow users to choose a location 
- Add a new step to the Functions creation process to allow users to create/choose a workspace. Follow the diagram in this OneNote for the logic of when this extra step should even be an option for users. This extra step should only be necessary when using “advanced” creation flow.  
- Validate that both the basic and advanced flows are using workspace based by default when creating default AI resources.

**Comment by fiveisprime** [comment]
Basic create:
* Create a new 2.1 instance with a new workspace in the same resource group as the app

Advanced create:
* Prompt to create or select existing AI instance
* If creating new and a workspace exists in the resource group, prompt to choose a new workspace or select existing
* If no workspaces exist in the resource group, create a new workspace (still open question on whether this is done automatically when creating a new AI instance)

Open questions
* What does the SDK/RP handle for us?
* Does creating a new 2.1 instance automatically create a workspace?

**Comment by Phuurl** [comment]
Worth noting as well that currently when deploying a new Function and creating the associated new app insights resource via the VSCode extension, upon visiting that resource in the Portal users are warned that the resource is deprecated as well as a few features being unavailable until it is migrated to the new type:

eg 1 (on the main overview panel):
![image](https://user-images.githubusercontent.com/1835431/163824523-c96e5975-1eca-4c06-b925-65c7ece40750.png)

eg 2:
![image](https://user-images.githubusercontent.com/1835431/163824596-cdd0113b-fc2d-4247-b30e-f672a623bdc7.png)
