### ISSUE TITLE
New function shows lots of linting errors

### ISSUE THREAD

**Issue by bduff9** [microsoft/vscode-azurefunctions#2836]
Hello!  I installed this extension yesterday as I have a need to create a bunch of Azure functions to deploy to an existing Azure environment for a client.

I have 2 questions about this.  First, when we use this extension to generate a new TS function, it generates all the files as expected.  However, the function file (index.ts) shows a lot of lint errors.  I click "Fix all" and it updates the file to match the local eslint, however, the errors do not go away.  This is happening in multiple teammates VS Codes, so unsure what is happening or how to fix it, but it makes developing much harder since there's so much red in the file (for the record, running eslint in the command line doesn't show any errors so this seems specific to this extension as copying the file to another VSCode project does not show errors).

Similarly, is this possible to create and develop functions within an existing project?  For one of our use cases, we have a ton of DB code (using TypeORM) and we would like to use parts of that, by putting the function in that project and just building it separately than our other code.  However, we have not been able to successfully build/run this locally yet so unsure if this is a limitation of this extension or something we are doing wrong.  For instance, is it possible to customize which npm scripts are used (instead of the default ones, like `build` for instance) or customize where the functions are (i.e. in a nested folder instead of directly off the root).  Thanks in advance!

**Comment by ejizba** [comment]
Our function templates generally do not do anything related to linting, but you're welcome to add linting and customize to fit your needs. If you want to show the screenshots of the specific errors you're hitting I might be able to help you customize your project, but again the errors should not be coming from our extension.

Yes, it is possible to customize the npm scripts and put it in a nested folder. The only thing that needs to be at the root of your workspace is the `.vscode` folder, and that's where you will make all of your customizations. To use a subfolder, we will automatically handle that if you browse to a subfolder of your current workspace when you create the project. To customize your build scripts you will need to manually update your `.vscode` config yourself. If your project is open source on GitHub we can take a look and help you accomplish that

**Comment by bduff9** [comment]
Thanks for the reply.  I agree I don't see any linting in the generated files but there is something in there that is conflicting with our existing linting since it is happening across multiple projects and multiple computers, so was hoping there was something that was known.  I'm unsure what to screenshot since every single line has an error,  both after initially generating the function (which I can use fix all on to make the styling fit our rules) and then after the initial fix all.  For instance, every line with a semi-colon says: `Delete ´␍´eslint(prettierx/options)`  But we don't have any rules about this and choosing Fix all again in VS Code doesn't further fix anything so unsure how to proceed.  Also, the given import seems to be wrong as that actually does fail linting on "no such import" for `import { AzureFunction, Context } from '@azure/functions';`

It seems this last one is known as reported here (to which the solution does seem to work for me): https://stackoverflow.com/a/66606475/1150878

As far as the structure, do you have any documentation on updating this?  I see the scripts in .vscode to update the build scripts, which works well, but I don't see any way to indicate that my functions are not in the root.  And the extension does not see my function at all after moving it to a nested folder (it has a project root that matches my project, and the function is now one folder deep, i.e. ./azure/function).  Unfortunately, my project for this is not public so cannot provide a link, but can provide code snippets if needed.  Just trying to find some docs currently to explain how to customize this as I love the idea of the extension, just struggling currently since we have not written azure functions before (been primarily lambdas) and are trying to incorporate this into an existing project instead of a new one.  Thanks!

**Comment by bduff9** [comment]
Just a quick follow up to the linting issue:

I didn't realize before that every single lint error was the same one I put above.  I searched this error and found that you can set a prettier option of `endOfLine: 'auto'` to resolve, which did seem to resolve.  Never had this issue before so unsure if the templates are being created with windows line breaks or what, but wanted to at least update that the linting error seems resolved.  So just looking for any documentation around customizing the functions to be in a nested location.

**Comment by bduff9** [comment]
Wanted to clarify what I have and what I'm looking for as I do see some documentation around script locations that is not exactly what we're looking for, but if its the only option, then I guess we'll have to make do.

Our current project structure looks like:
```
Root
 | - src
 | - ...
 | - package.json
 | - tsconfig.json
```

Ideally, we'd like to have:
```
Root
 | - azure
 | | - TimerTrigger
 | | | - function.json
 | | | - index.ts
 | | - host.json
 | | - tsconfig.json
 | - src
 | - ...
 | - package.json
 | - tsconfig.json
```
..but this doesn't work (the function is not seen by Azure Functions extension and running `npm run start:azure` (which is a script that is just `func start`) says the host.json is missing.  Moving all the config files (host.json, local settings, etc.) allows `npm run start:azure` to start, but it says no functions are found, and the Azure function still does not found the function.

I do see on the Azure function docs that you can have your function.json point to a script file outside of the directory:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#using-scriptfile
To me, this seems like we need to have a structure more like:
```
Root
 | - src
 | | azure
 | | | - timerTrigger.ts
 | - TimerTrigger
 | | - function.json
 | - ...
 | - host.json
 | - package.json
 | - tsconfig.json
```
..but this would not be ideal for us for a couple reasons, including not centrally locating the majority of azure code, plus making it slightly harder to compile just azure functions for their deployment separately from the rest of our code.

I still have not found a way to indicate a sub-folder location in .vscode, which I know you said was possible.  So if that is possible, and I can use it to get our desired project structure, that would be terrific!  Just unsure how to accomplish that currently.  Hope this helps clarify where we are still stuck!

**Comment by ejizba** [comment]
Here are some exact steps to get a project in a sub folder
1. Open your root folder in VS Code
2. Create new project 
3. When asked for a folder, click "Browse..." and choose your subfolder "azure"
4. Select TypeScript and whatever other options you want

It'll result in a structure like this:
![Screen Shot 2021-06-08 at 10 43 06 AM](https://user-images.githubusercontent.com/11282622/121232484-82a43e80-c846-11eb-9c54-d200f4336f77.png)

The main difference is in `.vscode/tasks.json` which will have an "options" object on each task:
```json
{
	"type": "func",
	"command": "host start",
	"problemMatcher": "$func-node-watch",
	"isBackground": true,
	"dependsOn": "npm build",
	"options": {
		"cwd": "${workspaceFolder}/azure"
	}
}
```
There might also be a few settings in `.vscode/settings.json` that reference your subfolder "azure".

**Comment by bduff9** [comment]
Thanks, @ejizba.  That is actually what I started with before I opened this issue.  The issue is that it doesn't work for the rest of what is needed in my requirements.  For instance, it seems to require another package.json, so I cannot use the rest of my code that is outside of this without re-including all the dependencies a second time, keeping them all in sync in 2 places, etc.  I do have the options.cwd already in my .vscode/tasks.json folder pointed to the right folder, but this does not help with the current issues of the Azure Functions extension not seeing my function nor the `func start` command not seeing my function.

Specifically, I'd love to have all azure function-related files in the azure folder off the root, and still be able to use files/dependencies from the rest of the project.  Is this not possible?  The tsconfig is totally fine in azure not only cause it can extend the root one, but also cause it makes it easier to use that to just build the azure functions.  But really need the package.json (and related lock and node_modules folders) to not be duplicated again in azure.  I'm sorry that wasn't clear from my explanation, hard to describe since I am unsure what is possible.

So I guess the question then based on your reply is less about having the functions be nested, but more about how to not duplicate package.json and related.  But if you look back at the structure examples I gave, would prefer to keep all azure-specific files in the azure folder, but still be able to leverage the rest of the project's files and dependencies in my azure functions.  So would love to know how to do this if possible, but following your instructions (which is what I did before I opened this issue) is not currently working.  Hope this is clearer, but let me know if not clear still.  If not clear, I can try to create a basic example showing what I need, though it won't be an exact one-to-one with what we actually have in our project.  Thanks!

**Comment by ejizba** [comment]
What do you mean showing up? For example, do you see this local project node in the Azure view:
![Screen Shot 2021-06-08 at 2 27 33 PM](https://user-images.githubusercontent.com/11282622/121260068-b9d61800-c865-11eb-954c-778b022e8cce.png)

Our configuration does not use the npm start script at all. We have a separate "func start" task in the `.vscode` folder that will be used if you start debugging and/or run the task from the command palette, which uses the correct sub folder. If you want to use scripts in your package.json instead of our task config, you'll have to customize that yourself. I expect there should be some guidance online for how to make an npm script run in a separate folder because that does not sound like a unique problem to Functions (maybe just `cd azure && func start` would work?)

**Comment by bduff9** [comment]
Right, that's what I'm saying, it doesn't show up:
<img width="210" alt="Screen Shot 2021-06-08 at 6 38 42 PM" src="https://user-images.githubusercontent.com/7385875/121271230-d6d01280-c888-11eb-856e-847a26b3b13e.png">


So, you're saying the `func start` just has to run in the context of the azure folder?  I'll try that now, but still would like to be able to use the Azure Function extension if possible which isn't currently finding any of our 4 created functions.

**Comment by ejizba** [comment]
Yes, `func start` needs to be run in the azure folder. We have boilerplate start scripts in package.json, but it's definitely something we expect users to customize (if they're not going to use VS Code's built-in tasks/debugging instead).

I'm still not sure why the functions aren't being listed. The most important file we look for is `host.json`, so if you have a few of those files in your repo it might be messing with us. Also, if you add `"azureFunctions.projectSubpath": "azure"` to your `.vscode/settings.json` you can explicitly tell us the root of your project. I honestly thought I already mentioned that, but seems like I didn't. If that setting fixes your problem sorry I didn't mention it earlier haha. If that still doesn't fix your problem, a sample project on GitHub would really help me reproduce the issue on my machine
