### ISSUE TITLE
There is an error after deleting a slot

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2841]
**OS:** Win10
Build Version: 20210603.9

**Repro Steps:**

1. Create a Function app -> Create a slot for it -> Delete the slot.
2. Check whether there is no error.

**Expect:**
There is no error after deleting a slot.

**Actual:**
There is an error after deleting a slot.
![image](https://user-images.githubusercontent.com/62053665/120785925-36b07b80-c560-11eb-8e64-8745500c82f0.png)

**Comment by v-xinda** [comment]
Verified this issue on the latest build 20210624.4, it also reproduces after deleting a function app.
![image](https://user-images.githubusercontent.com/57662131/123780436-c51ce080-d905-11eb-9cf4-93a1b7ee6ec8.png)
