### ISSUE TITLE
Cannot deploy to Azure

### ISSUE THREAD

**Issue by pbakerserenitize** [microsoft/vscode-azurefunctions#2845]
Issue Type: <b>Bug</b>

Starting today, with no updates to VS Code or the Azure Functions extension, I can no longer deploy to Azure using the UI

Extension version: 1.4.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.80GB (50.01GB free)|
|Process Argv|--crash-reporter-id 95388dd9-048a-4a9e-b110-e6aa624a510a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by ejizba** [comment]
Please add repro steps as well as "expected" vs. "actual" behavior (including any error messages)

**Comment by pbakerserenitize** [comment]
Repro:
Click refresh to get entire list of function apps associated with the Azure account
Expected:
List of all function apps is populated
Actual:
One of around 100 function apps is listed
Error Message:
Resource provider 'Microsoft.Web' failed to return collection response for type 'sites'.
![image](https://user-images.githubusercontent.com/64502602/121536694-e8203880-c9c8-11eb-9927-f285ec9a3129.png)

**Comment by aaronhuggins** [comment]
@ejizba I am on the same team as @pbakerserenitize and have opened a support ticket with the Azure team. This is probably more an Azure subscription issue than a VS Code extension problem, as I am able to reproduce with both the Azure CLI and Azure PowerShell commands.

Feel free to close if you concur that this is more an Azure issue than a VS Code extension issue. Thank you for your time.

**Comment by ejizba** [comment]
Yeah I just checked telemetry and this is a very rare issue for us. With that in mind and the fact that the issue repros for you on the Azure CLI as well, I will go ahead and close. However, let us know if this continues to block you and the support ticket goes nowhere
