### ISSUE TITLE
The "WarmUp" function shows under the "Functions" node for a basic Python3.9 function app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2846]
**OS:** Win10
**Build Version:** 20210604.2
	
**Repro Steps:**
1. Create a **basic** function app with **Python 3.9**.
2. Expand the function app -> Expand "Functions" node.
3. Check the "Functions" node.
	
**Expect:**
Nothing shows under the "Functions" node.
	
**Actual:**
The "WarmUp" function shows under the "Functions" node.
![image](https://user-images.githubusercontent.com/57662131/121328882-49072c80-c947-11eb-97f5-b2ebcf787816.png)

**More Info:**
This issue can be fixed by refreshing.

**Comment by ejizba** [comment]
Yeah I see this in the nightly tests sometimes, too
