### ISSUE TITLE
Pop up an error after installing the Azure Function extension in VS Code

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2847]
**OS:** Win10
**Build Version:** 20210609.1

**Repro Steps:**

1. Install the Azure Function extension in VS Code.
2. Check whether pop up an error.

**Expect:**
No error pops up.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/62053665/121485567-dfe4ef00-ca02-11eb-8862-93534434bd62.png)
![image](https://user-images.githubusercontent.com/62053665/121485536-da87a480-ca02-11eb-8160-0f8f1c9d6a20.png)

**Comment by ejizba** [comment]
Can you double check the Functions extension is fully installed and enabled? And give more details about the workspace you have open?

**Comment by v-mengwe** [comment]
Thanks for your update, verified on the latest build 20210623.6, this issue doesn't reproduce for now, so close it.

**Comment by ejizba** [comment]
This is likely a VS Code bug where they don't properly register tasks right after a clean install. It should go away after a user reloads the window. Since we can't fix ourselves and it doesn't happen that often, we'll close as "wont-fix"
