### ISSUE TITLE
Build task does not properly clean output directory

### ISSUE THREAD

**Issue by ethanroday** [Microsoft/vscode-azurefunctions#286]
**Steps to reproduce:**
1. Create a new project and a new function from the HTTP template.
2. F5 to start debugging:
![image](https://user-images.githubusercontent.com/896670/37626620-056f59d4-2b8e-11e8-8542-3bb6b0821b5b.png)
3. Stop the debugger.
4. In `HttpTrigger.cs`, change the name of the function to `HttpTrigger2`.
5. F5 to start debugging.

**Expected result:**
There is a single HTTP function, located at `/api/HttpTrigger2`

**Actual result:**
There are _two_ HTTP functions:
![image](https://user-images.githubusercontent.com/896670/37626716-4d0683a8-2b8e-11e8-8a2e-7f4a0760d21f.png)

There are a number of similar "phantom code" issues that result in confusing behavior and sometimes create runtime errors in the function host (such as deleting a function that previously existed).

**Comment by EricJizbaMSFT** [comment]
We just released an update that has includes this fix. It only affects new projects however. If you want to update your old project, you can copy the `.vscode/tasks.json` file from a new project over to your old project
