### ISSUE TITLE
Warning: "Failed to find Python virtual environment '.venv'" even though there is a '.venv' in a parent folder.

### ISSUE THREAD

**Issue by imbachb** [microsoft/vscode-azurefunctions#2861]
In my repository I have besides an azure functions project also other python code. I'd like to use the same python environment for all projects in the repository. This is the folder structure:
```
.vscode
.venv
poetry.lock
pyproject.toml
some_other_python_project
azurefunctions
|__host.json
|__proxies.json
|__requirements.txt
|__ HttpTrigger1
    |__ __init__.py
    |__function.json
```
The azurefunctions project is thus in a subfolder. 
In the `.vscode/settings.json` file I set among others:
```
{
  "python.pythonPath": "${workspaceFolder}/.venv/Scripts/python.exe",
  "azureFunctions.deploySubpath": "./azurefunctions",
  "azureFunctions.projectSubpath": "./azurefunctions",
  "azureFunctions.pythonVenv": ".venv"
}
```

When I open this project in vscode the azurefunctions extension shows the warning:
"Failed to find Python virtual environment '.venv', which is expected based on the setting 'azureFunctions.pythonVenv'."
![vscode-warning](https://user-images.githubusercontent.com/13905978/122900283-d6d21700-d34c-11eb-88f9-f9cd5a12f4b4.PNG)
It seems that the extension searches for the pythonVenv only in subfolders of the azurefunctions project. But in this case, the pythonVenv is in the parent folder.

I can however debug the azurefunctions application using the "Attach to Python Functions" launch configuration. This uses the correct ".venv."
I made a small repo so you could reproduce this easily:
https://github.com/imbachb/vscode-azurefunctions-issue

Is this approach simply not recommended, i.e. is it better to also have a ".venv" in the "azurefunctions" subfolder too? Or is this a bug in the extension?

**Comment by ejizba** [comment]
This is likely a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/2041. The current workaround is to set "azureFunctions.pythonVenv" to "../.venv" if your venv is in the parent directory - let me know if that works for you

**Comment by imbachb** [comment]
Thanks for the reply, good call. Setting `"azureFunctions.pythonVenv": "../.venv"` does resolve the problem.

I did try setting it to `"azureFunctions.pythonVenv": "${workspaceFolder}/.venv"` before, however it did not resolve the `${workspaceFolder}` variable. But using a relative path seems to be the solution for now.
