### ISSUE TITLE
VS Code directory mapping for functions

### ISSUE THREAD

**Issue by awentzel** [microsoft/vscode-azurefunctions#2863]
When choosing a folder to map functions in code with the Azure Functions extension the extension does not display the "Function" in their folder unless you choose default.  As soon as you select a folder where  your functions resides that is not the default the Functions in the extension no longer show up.  The only way to see them using the Functions extension is to navigate down into the "Files".  This makes it confusing.  Should we be using the Azure Functions Files dir to work with our functions or should we be using VS Code file structure?  I would image both should work just fine.

Notice the highlighed and expanded "Functions" folder of the extension.  Then notice the "Files" structure.
![image](https://user-images.githubusercontent.com/16669785/122976672-7a212d00-d349-11eb-93d3-07eccc19dc31.png)

It seems like a bug or a configuration issue whereby the "Functions" are not showing up.  This makes is confusing on what the best method is to use VSCode Extension for managing Functions in code.  I also, don't know where the configuration file is to manually modify the folder mapping between source and Azure Functions extension.

**Comment by ejizba** [comment]
The most important settings are in the `.vscode` folder at the root of your workspace. You can use other folders, but if so you need to update those settings. One way to update all at once is to run "Azure Functions: Initialize project for use with VS Code..." from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) after you've moved your project. You'll then have to deploy again for the settings to affect the remote app as shown in your screenshot

You can also manually modify your settings. For example in settings.json:
```
// this is the folder we deploy
"azureFunctions.deploySubpath": "subfolder"
// this setting isn't required, but can be used to explicitly tell us where your project is
"azureFunctions.projectSubpath": "subfolder",
```

And in your tasks.json, you can adjust the folder like this:
```
{
	"type": "shell",
	"label": "npm install",
	"command": "npm install",
	"options": {
		"cwd": "${workspaceFolder}/subfolder"
	}
},
```
