### ISSUE TITLE
The deployment source changes from "LocalGit" to "None" when canceling the action that changed the deployment source from " LocalGit" to "GitHub"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2878]
**OS:** Win10
**Build Version:** 20210713.10

**Repro Steps:**

1. Right click a function app -> Select "Configure Deployment Source..." -> Select "LocalGit" -> Deployment source for the function app has been updated to "LocalGit".
2. Right click this function app again -> Select "Configure Deployment Source..." -> Select "GitHub" -> Press "ESC" when asking to choose organization.
3. Refresh -> Check whether the deployment source of the function app remains "LocalGit".

**Expect:**
The deployment source of the function app remains "LocalGit".

**Actual:**
The deployment source of the function app changes from "LocalGit" to "None".

**Comment by ejizba** [comment]
Looks like the repros for me on v1.4.0 as well. Likely related to this code: https://github.com/microsoft/vscode-azuretools/blob/main/appservice/src/editScmType.ts#L25
