### ISSUE TITLE
Error: Cannot find module durable-functions

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/vscode-azurefunctions#2883]
Using the latest version of vscode and the extensions.

* Create a brand new Azure Functions JavaScript project.
* Create a Durable HTTP Starter function
* Create a Durable Orchestrator Function
* Create a Durable Activity Function called `Hello` (to match the orchestrator Function)
* Press F5 to debug.

**Expected result:** Azure Function running and waiting for an HTTP request
**Actual Result:**
![Screenshot](https://user-images.githubusercontent.com/209384/125675368-98d9dc57-7103-466d-89fb-7e4f151e641f.png)

**Root cause:**
While creating the different durable functions, no dependencies for `durable-functions` were ever added in `package.json`.

**Possible fix:**
When creating Durable Functions, ensure that the dependency has been added before/after the creation of the Function.

**Comment by MicroFish91** [comment]
Fixed by the PR above
