### ISSUE TITLE
Help: Is there any way i can edit deployed azure functions

### ISSUE THREAD

**Issue by zycon** [microsoft/vscode-azurefunctions#2886]
I'm trying to edit an existing azure functions on javascript using this plugin, but not sure why am getting readonly mode. I tried changing the env value in the portal func configurations , but it's already in readwrite.

Any help is highly appreciated  
 
![image](https://user-images.githubusercontent.com/36449874/125762269-b2156db6-ebba-45ab-920c-2dd2083d8d04.png)

**Comment by ejizba** [comment]
We currently do not support editing deployed function apps. The only way to change the app from our extension is to deploy again

**Comment by zycon** [comment]
Thanks @ejizba , was bit confused it's my config isz.
