### ISSUE TITLE
Running Function Tools with HTTPS Fails to Pick Process for Debug

### ISSUE THREAD

**Issue by nerddtvg** [microsoft/vscode-azurefunctions#2887]
Sometimes we need to run the function apps with HTTPS locally to test OAuth which requires an encrypted URL scheme. However, the extension is hard-coded to look for the status page with the url `http://localhost:${funcPort}/admin/host/status` which will fail. Since the function core tools do not support both HTTP and HTTPS simultaneously, this causes issues. It would be best if the extension either (a) detected HTTPs via the configs/command line and used it or (b) tried both. This also means supporting self-signed certificates with no chain of trust.

A workaround is to use `pickProcess` instead of `azureFunctions.pickProcess` in `launch.json`, manually restart the function app on changes, and choose the PID from the provided list.

https://github.com/microsoft/vscode-azurefunctions/blob/4e7b9a52b465046e53ab1fa886bf8bf349a6452d/src/commands/pickFuncProcess.ts#L87

Error received when trying with HTTPS:

```
Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.
```

**Comment by ejizba** [comment]
Thanks for the detailed bug report, we'll look into it. In the meantime, the workaround you described is the best one I'm aware of
