### ISSUE TITLE
Customize default request body when executing function

### ISSUE THREAD

**Issue by ChrisSmith2** [microsoft/vscode-azurefunctions#2888]
When clicking "Execute Function Now", the request body is set to `{ "name": "Azure" }` by default.

![image](https://user-images.githubusercontent.com/9710782/125979060-0be5613c-7bc3-4e4e-96ba-bd0ec587ae31.png)

Is it possible to customize this default value?

**Comment by ejizba** [comment]
No that is not possible today. Any thoughts on how you would prefer to customize it? Also what language are you using? For example
1. We could add a VS Code setting, but that might get complex
2. We could read the contents of "sample.dat" (depending on your language, that file exists by default in the function's folder) or some other file
3. We could remember the last "request body" entered and just use that

**Comment by ChrisSmith2** [comment]
I'm using a Powershell azure function. I think it makes sense to read from the sample.dat file because that file starts out as
```
{
    "name": "Azure"
}
```
Since this matches the default request body, my initial thought was that this file was being used to set it.

However, if not all languages start out with a sample.dat file, maybe it's better to just remember the last request body entered.
Alternatively, a VS Code setting could be added to switch between reading from the sample.dat or just using the last request body.
