### ISSUE TITLE
feat-request: Add support for publishing profiles

### ISSUE THREAD

**Issue by mtycholaz** [microsoft/vscode-azurefunctions#2901]
Is it possible to add support for publishing profiles downloaded from Azure, or multiple Azure accounts in the extension?

I maintain/develop a nodejs Azure function with my personal Azure account. But to deploy the code for the client, I have to sign out of Azure and then sign in to the client's Azure account.

Similar to how Visual Studio has support for publishing profiles.

**Comment by ejizba** [comment]
Signing into multiple accounts is being tracked here: https://github.com/microsoft/vscode-azure-account/issues/42

**Comment by ejizba** [comment]
@mtycholaz can you elaborate on what you want from a publishing profile? We have several VS Code settings that provide similar functionality to VS publishing profiles, so there might not be much work here. Please comment on the azure account extension's repo for anything about signing into multiple accounts

**Comment by mtycholaz** [comment]
@ejizba Here's an example of publishing profiles in Visual Studio. I can download the profile from the Azure portal, and each profile can point to a different account/subscription. 

So I downloaded one .pubxml from my personal Azure account for development, and also downloaded one from the client's Azure portal.

![image](https://user-images.githubusercontent.com/3585379/130519937-e9bbbdca-b5b9-4186-bed5-cf3b4245fb11.png)
