### ISSUE TITLE
create function options not used when a new project needs to be created

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-azurefunctions#2909]
we leverage the API exposed by this api and noticed that when no project is currently available a new project will be created, this is ok, but the options we passed in will be ignored.

**Comment by ejizba** [comment]
We'll look into it - to speed up the process, though, what options are you passing in that are ignored?

**Comment by alanrenmsft** [comment]
for now, we are passing in: language and templateId.

**Comment by nturinski** [comment]
Hi @alanrenmsft 

Sorry it's taken us a while to look into this. I was just investigating though, and both `language` and `templateId` were respected when I created a new function, but didn't have a project, so created a new project instead.

I used `JavaScript` as the `language` and `HttpTrigger` as the `templateId`. The only prompts I got were for HTTP trigger name and the Authorization level.  

Could you confirm that this is still an issue?

**Comment by alanrenmsft** [comment]
Thanks @nturinski I am no longer working on this feature. 
@VasuBhog @chlafreniere , is this still an issue for us?

**Comment by VasuBhog** [comment]
@nturinski, Yes I believe this has been fixed already. As we pass in templateID and other settings to the createFunction itself. Can close.

**Comment by nturinski** [comment]
Thanks for following up!
