### ISSUE TITLE
Azure function error when running locally - modulenotfounderror

### ISSUE THREAD

**Issue by miladToolabi** [microsoft/vscode-azurefunctions#2910]
## Environment data

-   VS Code version: 1.58.2 (user setup)
-   Extension version (available under the Extensions sidebar): Python Extension v2021.7.1060902895
-   OS and version: Windows_NT x64 10.0.19042
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4 64-bit Anaconda3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting:  Pylance???

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

I am running a httptrigger azure function locally. Previously it worked fine but it has stopped working recently.
    import logging

    import azure.functions as func
    import pandas

    def main(req: func.HttpRequest) -> func.HttpResponse:
        logging.info('Python HTTP trigger function processed a request.')

        name = req.params.get('name')
        if not name:
            try:
                req_body = req.get_json()
            except ValueError:
                pass
            else:
                name = req_body.get('name')
    
        if name:
            return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
        else:
            return func.HttpResponse(
                 "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a     personalized response.",
                 status_code=200
            )

## Logs

<details>

[2021-08-05T19:37:29.961Z] Worker process started and initialized.
[2021-08-05T19:37:30.163Z] Worker failed to function id 5da60409-71d3-4953-aabd-6d50940ae685.
[2021-08-05T19:37:30.165Z] Result: Failure
Exception: ModuleNotFoundError: No module named 'pandas'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 302, in _handle__function_load_request
    func = loader.load_function(
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 42, in call
    raise extend_exception_message(e, message)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 40, in call
    return func(*args, **kwargs)

</details>

**Comment by ejizba** [comment]
Did you add `pandas` to your requirements.txt file?

**Comment by miladToolabi** [comment]
@ejizba Yes I did. I found the problem. There were two Pythons installed on my machine and it was somehow clashing
