### ISSUE TITLE
Debugger shut down after finishing spawned node process

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode-azurefunctions#2925]
\# I'm not sure if this issue is caused by this extension. So please transfer this to the appropriate repository if this is caused by other components (functions core tools, azure-function-nodejs-worker, or etc).

On Windows, the VSCode debugger shut down suddenly after finishing the Node.js process which is spawned in a function as the following code.

I expected that the debugger keeps launching but actually it shut down.

```
const { exec } = require('child_process');

module.exports = async function (context, req) {
  context.log('JavaScript HTTP trigger function processed a request.');
  const result = await new Promise((resolve, reject) => {
    const p = exec(
      `"${process.execPath}" test.js`,
      (error, stdout, stderr) => {
        if (error) return reject(error);
        resolve({ stdout, stderr });
      }
    );
  });
  context.res = {
    // status: 200, /* Defaults to 200 */
    body: {
      stdout: result.stdout.toString(),
      stderr: result.stderr.toString()
    }
  };
}
```

This issue appears in about 0:25 of the following video.

https://user-images.githubusercontent.com/4566555/129997624-3d1a1cb4-e04d-4b67-a842-30bdbccb3b92.mp4

The project in the video is https://github.com/horihiro/child_process_test_js and the environment is:
  - Windows 10 (21H1, 19043.1165)
  - Node.js 14.15.4
  - Functions core tools v3.0.3568
  - VScode v1.59.0
  - Azure Functions extension for VSCode (azuretools.vscode-azurefunctions) v1.4.1

On the other hand, the debugger works normally in the second video. 
The difference between these videos is `preLaunchTask` in each launch settings in `launch.json`

1. In the first video, `func start` is specified directly as `preLaunchTask`
https://github.com/horihiro/child_process_test_js/blob/main/.vscode/launch.json#L9
2. But the second, `npm start` is specified as `preLaunchTask` and `npm start` calls `func start` in `package.json`
https://github.com/horihiro/child_process_test_js/blob/main/.vscode/launch.json#L16

https://user-images.githubusercontent.com/4566555/129997784-9deaa327-b02f-4981-aaaa-e0003db6e145.mp4

Could you please look into what happened when `func start` is used as `preLaunchTask`?
I would appreciate your help.

**Comment by ejizba** [comment]
Is there any particular reason you need to use `npm start`? We have to set an environment variable for debugging to work and we don't control the npm tasks, just the func tasks. If you need to use `npm start` you can set `languageWorkers__node__arguments` to `--inspect=9229` manually

**Comment by horihiro** [comment]
Thank you for your reply!

The reason why I use `npm start` task is that the debugger started by `func` task shuts down suddenly after finishing a function which spawns another node.js process, though I'm not sure why `npm start` can avoid this issue.
Actually I want to use `func` task if I could avoid this issue.

Could you please let me know if any more information is needed?

**Comment by horihiro** [comment]
This issue can be reproduced on not only Windows 10 native but also Remote-WSL and Remote-Container even though the extension is updated to 1.5.0.

**Comment by horihiro** [comment]
As long as I investigated with https://github.com/horihiro/child_process_test_js, `func` task with spawning another process in a function cannot work properly on some environments.

|platform|`func`|`npm start`|
|:---------|:-----:|:-----------:|
|VS code (Windows native)| ❌ | ✔ |
|VS code (Remote-WSL)| ❌ | ✔ |
|VS code (Remote-Container)| ❌ | ✔ |
|GitHub Codespaces| ❌ | ✔ |
|VS code Insider (Windows native)| ✔ | ✔ |
|VS code Insider (Remote-WSL)| ❌ | ✔ |
|VS code Insider (Remote-Container)| ❌ | ✔ |

❌: The debugger shuts down after spawning another process
✔: The debugger can keep even after spawning another process

**Comment by StenPetrov** [comment]
I'm having this issue and it makes it very difficult to debug a function that runs some automation

**Comment by ejizba** [comment]
As a workaround, you can add this to your VS Code settings (in `.vscode/settings.json`):
```
"azureFunctions.stopFuncTaskPostDebug": false
```
