### ISSUE TITLE
Fail to debug the JavaScript project created with "Timer Trigger" template

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2926]
**OS:** Win10/Mac
**Build Version:** 20210819.3
**Regression:** Regression

**Repro Steps:**

1. Open an empty folder in VS Code -> Click "Create New Project..." -> Select the opened folder -> Select "JavaScript" -> Select "Timer Trigger" template -> Press Enter -> Press Enter.
2. F5.
3. Check whether succeed to debug this project.

**Expect:**
Succeed to debug this project.

**Actual:**
Fail to debug this project with an error.
![image](https://user-images.githubusercontent.com/62053665/130206317-72306525-4b9d-43c6-b218-6726644068b1.png)

**More Info:**

1. This issue doesn't reproduce on the latest release build.
2. This issue also reproduces for other language projects if clicking "Skip for now" when asking to select a storage account for creating a project with "Timer Trigger" template.
    ![image](https://user-images.githubusercontent.com/62053665/130207914-a745d771-e499-492c-9a20-ff6bc0f6b470.png)

**Comment by ejizba** [comment]
You don't see the "skip for now" dialog for JavaScript?

**Comment by ejizba** [comment]
Yeah when I try to debug a JavaScript project with a timer trigger, I see this:
<img width="274" alt="Screen Shot 2021-08-23 at 4 10 24 PM" src="https://user-images.githubusercontent.com/11282622/130530901-ffb63181-d3b1-442d-a0a6-2f8cbe87d208.png">

**Comment by v-mengwe** [comment]
Verified on the latest build 20210907.1, this is an unstable issue, the error displays when there is no dialog. Could you try it more times?
![llll](https://user-images.githubusercontent.com/62053665/132488762-f46b1982-16c8-41a1-8aca-701f0f9d7bc4.gif)

Open a new bug about the dialog of different projects are inconsistent([2955](https://github.com/microsoft/vscode-azurefunctions/issues/2955)).
