### ISSUE TITLE
[Suggestion] It would be better to remove the "first" word from the help information in the text box when asking to select a template

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2954]
**OS:** All
**Build Version:** 20210905.1
**Regression:** Not a regression

**Repro Steps:**

1. Open an empty folder in VS Code insider-> Create a new project -> Check the help information in the text box when asking to select a template. 
2. Click "Create New Project" to create the project again using the opened folder.
3. Check the help information in the text box again when asking to select a template.

**Actual:**
The help information in the text box remains "Select a template for your project's **first** function".
![image](https://user-images.githubusercontent.com/62053665/132463820-b1706ece-0e28-4532-9efb-4fad5fa2ef99.png)

**Suggestion:**
It would be better to remove the `first` word from the help information in the text box.

**Comment by ejizba** [comment]
Why do you suggest we remove "first"?

**Comment by v-mengwe** [comment]
It has always been the “first” when creating multiple functions for the same project. If the "first" is by design, when the project is created again with "HttpTrigger2" in the step 2, the help information here should be "Select a template for your project's `second `function". The function "HttpTrigger2" created at the step 2 is already the second function of this project, not the first.

**Comment by ejizba** [comment]
When creating a second function in my project, I see this prompt which does not say "first":
![Screen Shot 2021-09-09 at 10 27 51 AM](https://user-images.githubusercontent.com/11282622/132733786-e49d537b-e364-454b-a139-acdcfba6090f.png)

**Comment by v-mengwe** [comment]
Create the second function with click on the "Create New Project" button, the default function name is automatically changed from "HttpTrigger1" to "HttpTrigger2", but the help information in the text box remains "Select a template for your project's first function".

**Comment by ejizba** [comment]
If users want to create a second function, they should use the "create function" option, not "create new project". We will keep the wording the same for "create new project" because it makes sense for the most common scenario
