### ISSUE TITLE
The dialogs of different projects are inconsistent when asking to select a storage account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2955]
**OS:** All
**Build Version:** 20210905.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a C# project with "Timer Trigger" template -> Check the dialog.
   ![image](https://user-images.githubusercontent.com/62053665/132489691-b8acb40f-2e19-461e-9b65-30571691fa01.png)
2. Create a JavaSript/Python/Powe project with "Timer Trigger" template -> F5.
3. Check the dialog.

**Expect:**
The dialogs of different projects are consistent.

**Actual:**
The dialogs of different projects are inconsistent.
![image](https://user-images.githubusercontent.com/62053665/132489585-df6e45c6-1e1f-44a6-818c-a4b363dc33b1.png)

**Comment by ejizba** [comment]
This is by design. We prefer to prompt right before debugging (like in JavaScript, Python, etc.), but we can't do that for C# and Java because they are compiled languages and the function.json files don't exist until after a build.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
