### ISSUE TITLE
Visual Studio Code: Wrong separator being used after changing default terminal

### ISSUE THREAD

**Issue by avaTMO** [microsoft/vscode-azurefunctions#2958]
In Visual Studio Code I changed the Default Terminal to Command Prompt.
When I want to debug my Azure Function the following command is executed:

`Executing task: .venv\Scripts\activate ; func host start <`

However, I think it should put the cmd separator "&&" instead of ";".
Otherwise the `func host start` will not execute and therefore I receive a ECONNREFUSED error.

I think the line should look like this:
`Executing task: .venv\Scripts\activate && func host start <`

As far as I know VSC should auto-detect the separator, but in my case it fails to do so.
Is there a way to manually change the separator?

Here is my settings.json:

> 
> {
>     "terminal.integrated.automationShell.windows": "C:\\windows\\System32\\cmd.exe",
>     "terminal.integrated.defaultProfile.windows": "Command Prompt",
>     "terminal.integrated.profiles.windows": {
>         "PowerShell": {
>             "source": "PowerShell",
>             "icon": "terminal-powershell"
>         },
>         "Command Prompt": {
>             "path": [
>                 "${env:windir}\\Sysnative\\cmd.exe",
>                 "${env:windir}\\System32\\cmd.exe"
>             ],
>             "args": [],
>             "icon": "terminal-cmd"
>         },
>         "Git Bash": {
>             "source": "Git Bash"
>         },
>         "C:\\windows\\System32\\cmd.exe": {
>             "path": "C:\\windows\\System32\\cmd.exe",
>             "args": [],
>             "icon": "terminal-cmd"
>         },
>         "JavaScript Debug Terminal": {
>             "extensionIdentifier": "ms-vscode.js-debug",
>             "icon": "debug",
>             "id": "extension.js-debug.debugTerminal",
>             "title": "JavaScript Debug Terminal"
>         }
>     }
> }

Thanks in advance!

**Comment by avaTMO** [comment]
I was able the change the separator by edititng the tasks.json:

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cmd host start",
            "type": "shell",
            "dependsOn": "pip install (functions)",
            "windows": {
              "command": "${config:azureFunctions.pythonVenv}\\Scripts\\activate && func host start"
            },
            "isBackground": true,
            "problemMatcher": "$func-python-watch",
          },
        {
            "label": "pip install (functions)",
            "type": "shell",
            "osx": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "windows": {
                "command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
            },
            "linux": {
                "command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
            },
            "problemMatcher": []
        }
    ]
}

Afterwards in the launch.json, I set the preLaunchTask to "cmd host start".

**Comment by ejizba** [comment]
The root cause of this issue is in VS Code. See https://github.com/microsoft/vscode/issues/132150 and https://github.com/microsoft/vscode/issues/132787. Hopefully they get fixed and released soon.
