### ISSUE TITLE
A11y_Azure Tools for VS Code [BM]_Debug_Screen Reader: Voice Over is not reading about the breakpoint if it is inserted anywhere in program

### ISSUE THREAD

**Issue by Latha2564** [microsoft/vscode-azurefunctions#2988]
### GitHubTags:
#Azure Tools for VS Code; #A11ySev2; #A11yTCS; #BM-AzureToolforVSCode-MAC-Oct2021; #DesktopApp; #VoiceOver; #WCAG1.3.1; #ScreenReader;#Element:BreakPoint;#AINotInScope;#MAC;#A11yMAS;#FirstParty:Bug90842

### OS Details:
Mac OS Big Sur

### Environment Details:
Application Name: Azure Tools for VS Code

### Repro Steps:

1.Turn on Voiceover.
2.Open Visual studio code
3.Tab till extension button and press enter on it.
4.Search for "Azure Functions" and select it.
5.Tab till "Install" button and press enter on it.
6.Tab till "Azure" button from left side pane and press enter on it.
7.Default screen will get open.
8.Create any project and insert breakpoint
9.Verify Screen reader is reading about breakpoint or not while navigating in code.
### Actual Result:
Voiceover is not reading about the breakpoint if it is inserted anywhere in program

### Expected Result:
Voiceover should read about the breakpoint if it is inserted anywhere in program

### User Impact:
Screen Reader users will not get complete information available on screen if screen reader is not reading it.
### ![debug breakpoint](https://user-images.githubusercontent.com/89508906/138436774-949fea2d-7449-4863-ac6f-807c4e9f2b3d.gif)

**Comment by nturinski** [comment]
This seems to be the same bug as this one: https://github.com/microsoft/vscode-azurefunctions/issues/2699 which is being tracked externally here: https://github.com/microsoft/vscode/issues/90842

**Comment by Gayathri1501** [comment]
![2988_A11y_Azure Tools for VS code BM _Debug_Screen reader_](https://user-images.githubusercontent.com/99962579/169244247-4c4a85ed-2722-4caf-88d2-f546a2e85d4b.gif)
Bug is Fixed. Please refer the attachment.
