### ISSUE TITLE
Extension defaulted runtime to version ~2 when ~3 was expected

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/vscode-azurefunctions#2994]
Hi folks. I recently created a TypeScript function using the VSCode Azure Functions Extension and when I got the "select Node runtime" prompt it limited me to only Node 8 (docs state I should be able to select Node 10 as well).

I created it anyways and investigated. It seems like the extension defaulted my functions runtime to ~2 (when I expected it to default to ~3). Once I changed the function runtime, I was then able to select between Node v12 and v14. 

I manually set the extension settings to default the function runtime to ~3, but I'd think that would've been the default? 

Let me know if theres anything else I can provide to help reproduce

**Comment by ejizba** [comment]
Hi @Ethan-Arrowood we've had a number of people say the logic to pick the function runtime is not obvious, so we recently made some improvements in https://github.com/microsoft/vscode-azurefunctions/pull/2987. Basically, when picking the Node version it'll show which function runtime we used and let you change it

Fwiw, Node 10 is still available - it's just deprecated. You can use the VS Code setting `azureFunctions.showDeprecatedStacks` to view it. Node 8 should also be deprecated, not sure why it isn't. But yes using ~3 is recommended anyways

**Comment by Ethan-Arrowood** [comment]
Awesome, looking forward to that. I also had the core tools installed locally at version 2 so thats most likely what caused it. 

Furthermore, if both Node 8 and 10 are deprecated now, is functions runtime 2 incompatible with 12, 14 or 16? Maybe the UI showed me version 8 since it couldn't show any other version?

**Comment by ejizba** [comment]
> Awesome, looking forward to that. I also had the core tools installed locally at version 2 so thats most likely what caused it.

Yes that would cause it

> Furthermore, if both Node 8 and 10 are deprecated now, is functions runtime 2 incompatible with 12, 14 or 16?

Correct, runtime 2 does _not_ support 12/14/16. I believe these are the official docs on the support policy, you'll notice they call out specific dates for node 8/10:
https://docs.microsoft.com/en-us/azure/azure-functions/language-support-policy

In general there were very few differences between runtime 2 and 3 for Node.js users and we strongly recommend people upgrade off of runtime 2.

**Comment by Ethan-Arrowood** [comment]
Sounds good! Thank you for the info and I'm glad to see this flow is improving 😁
