### ISSUE TITLE
VSCode, first installation of Azure Function - EPERM error on a folder

### ISSUE THREAD

**Issue by Treawlony** [microsoft/vscode-azurefunctions#2995]
Does this occur consistently?  yes
Repro steps:

1.Install Azure Function
2.Try to create a project

Action: azureFunctions.createFunction
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'C:\Documents and Settings'

Version: 1.5.2
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.61.2
Language: en

**Comment by nturinski** [comment]
Could you try creating the project in a different folder?  Your user folder (C:\Users\Username) would be a better location since this seems to be related to the fact that VS Code doesn't have permission to write directories to your C:\Documents and Settings folder.

**Comment by Treawlony** [comment]
I would love to… but I do not know/find how to 😊

**Comment by nturinski** [comment]
Could you try going into File > Open Folder and then selecting a folder that is not directly in the root of your C: drive?

![image](https://user-images.githubusercontent.com/5290572/141008956-643979e9-1361-4f27-8e37-537e98cecff9.png)
