### ISSUE TITLE
There is only one  .NET 6 runtime stack in the list when creating a  .NET 6 Function App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2996]
**OS:** Win10
**Build Version:** 20211103.2
**.NET 6 Version:** 6.0
**Function Core Tools:** v4

**Repro Steps:**
1.  F1 -> Azure Functions: Create New Project... -> Select a folder -> Select C# language -> There are two .NET 6 runtimes in the list.
![image](https://user-images.githubusercontent.com/57662131/140295267-ef70e902-d3b7-4e3e-b9f8-11f243152869.png)
2. F1 -> Azure Functions: Create Function App in Azure... -> Enter a name.
3. Check Whether there are two .NET runtimes stack in the list.

**Expect:**
There are two .NET runtimes stack in the list.

**Actual:**
There is one  .NET runtime stack in the list.
![image](https://user-images.githubusercontent.com/57662131/140294671-b524df10-358e-4fda-8298-bb772d933469.png)

**More Info:**
Fail to deploy the **.NET 6 isolated** project to **.NET 6** function app.
![image](https://user-images.githubusercontent.com/57662131/140287998-e4de5271-a88f-4c1b-8343-488935d18f2d.png)

**Comment by nturinski** [comment]
This should not be the case anymore.  Could you test this off of the release or off main?

**Comment by v-xinda** [comment]
Verified this issue on the latest build 20211111.1, it doesn't reproduce. So I close it.
