### ISSUE TITLE
Unrecognized target framework netcoreapp3.1

### ISSUE THREAD

**Issue by OzBob** [microsoft/vscode-azurefunctions#3002]
The VS Code Azure Functions (Extension v1.6.0 - 2021-11-04) ["add API to static web app instructions" ](https://docs.microsoft.com/en-au/azure/static-web-apps/add-api?tabs=vanilla-javascript#prerequisites) say to use VSCode F1: "Azure Static Web Apps: Create HTTP Function" instruction.

The error message on vscode at the end of the wizard is:

```
Unrecognized target framework "netcoreapp3.1". Available frameworks: "net6.0", "net6.0".
Source: Azure Functions (Extension)
```

My ```dotnet --list-sdks``` shows a 3.1.415 and ```dotnet --lsit-runteims``` shows  3.1.21.

Also, if relevant:
```
>npm list --global --depth=0
+-- @azure/static-web-apps-cli@0.8.1
```

How do I specify the runtime?

**Comment by nturinski** [comment]
Hi @OzBob

Could you run `func --version` for me and tell me what version of the Function Core Tools that you have installed?  I think you may have a version that is no longer compatible with .NET 3.1.
