### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Adoleyine** [microsoft/vscode-azurefunctions#3011]
- Issue Type: `Performance`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\adole\AppData\Local\Temp\ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nturinski** [comment]
Please attach the file from the directory `c:\Users\adole\AppData\Local\Temp\ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt`  We need that to investigate this performance issue.
