### ISSUE TITLE
Unable to fully set up C# Azure functions project

### ISSUE THREAD

**Issue by TheGreatJakester** [microsoft/vscode-azurefunctions#3019]
Followed all the steps in this [guide: Quickstart: Create a C# function in Azure using Visual Studio Code; Configure your environment](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?tabs=in-process#configure-your-environment).

I have installed
- VS Code (1.62.3) on Windows 11
- Azure Functions Extension: 1.6.0
- Azure Tools Extension Installed
- .NET 6.0.100
- Azure Functions Core Tools 4.0.3971
- C# Extension: 1.23.17

Steps to reproduce:
Open VS Code
Create new folder and open it with VS Code
Open Azure Tools Extension in VS code
Under Functions, hit "Create New Project" Icon
Follow prompts to create new project with .NET 6 (non-isolated), with HTTP endpoint
Result: Some files are generated, including [cwd]/[cwd].csproj; I get a notification that says 'Failed to find csproj file in folder "[cwd]."'
In the Azure Extension, hit Functions > Local Project > "Initialize Project for Use  with VS Code..."
Select C#
Result: I get a notification that says 'Failed to find csproj file in folder "[cwd]."'

Steps to reproduce:
Create new folder
Open prompt inside
`func init`
select `dotnet`
`code .`
Verify some files were generated, including [cwd]/[cwd].csproj
In the Azure Extension, hit Functions > Local Project > "Initialize Project for Use  with VS Code..."
Select C#
Result: I get a notification that says 'Failed to find csproj file in folder "[cwd]."'

**Comment by TheGreatJakester** [comment]
Looks really similar to this [issue](https://github.com/microsoft/vscode-azurefunctions/issues/2933).

**Comment by TheGreatJakester** [comment]
Hmm globby is returning 0 files inside the `findFiles` function.
The pattern globby is looking for `c:/Users/First Last (Work)/repos/project/*.csproj`
Where `First` is my first name.... And so on.
I wonder if part of my profile's name is goofing globby.

**Comment by TheGreatJakester** [comment]
I'm not sure why this [test is timing out](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=41559&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=0aa9f1b3-1821-5d60-e12b-72e36367656d&l=7186)...

**Comment by alexweininger** [comment]
> I'm not sure why this [test is timing out](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=41559&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=0aa9f1b3-1821-5d60-e12b-72e36367656d&l=7186)...

That test has been timing out on Windows for a while, don't worry it wasn't you.
