### ISSUE TITLE
Runtime v2 function apps not listed in extension

### ISSUE THREAD

**Issue by unwitting** [Microsoft/vscode-azurefunctions#302]
I have three function apps: two of them use the v1 Node runtime and appear in the list of functions in my sidebar for VSCode. Another uses v2 runtime and doesn't, even after a refresh.

I've installed .NET Core 2.0 and azure-functions-core-tools via Homebrew.

**Comment by EricJizbaMSFT** [comment]
I'm not sure why this is happening and would need more information - do all three show up in the Portal? Are they all under the same subscription? Does the missing one show up in the [app service extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureappservice)?

**Comment by auchenberg** [comment]
Just debugged this. The issue seem to be this line https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/tree/FunctionAppProvider.ts#L42

The check should be `.filter((site: Site) => site.kind && site.kind.startsWith('functionapp'))`

**Comment by EricJizbaMSFT** [comment]
Never mind - I repro'ed this by creating a linux function app in the portal
