### ISSUE TITLE
Failed to find "maven", please ensure that the maven bin directory is in your system path.

### ISSUE THREAD

**Issue by Kathir-N** [microsoft/vscode-azurefunctions#3025]
After running "java -version"in  VS Code's terminal and also in cmd prompt -windows 7 machine 
PS C:\Users\Admin> java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

After running "mvn -v"

PS C:\Users\Admin> mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: C:\Program Files\apache-maven-3.8.4
Java version: 11.0.13, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.13
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

When I create a new Java Function I get this issue, maven and JDK are installed, can anyone please help me out of this.
"Failed to find "maven", please ensure that the maven bin directory is in your system path."

 Note ; I tried to close the VS Code windows and restarted it,still not working

[image](https://user-images.githubusercontent.com/45091461/146231871-333b6c50-e2a9-4892-9ea8-eeda5c32393d.png)

**Comment by nturinski** [comment]
Do you know if your PATH environment is the same for Shell and PowerShell?  I have a feeling that we are looking for maven through a normal shell terminal and are unable to find it.  Maybe try reinstalling Maven?

**Comment by Kathir-N** [comment]
Yes. It worked after reinstalling maven

**Comment by nturinski** [comment]
Great to hear!  I'll go ahead and close this then.
