### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by teddarr** [microsoft/vscode-azurefunctions#3026]
When I try to install the extention in VSCode eiter from the extention marketplace or from the vsix file I get the Corrupt ZIP: end of central directory record signature not found error.  Windows 10

**Comment by nturinski** [comment]
Are you able to install other VS Code extensions?  This is a very strange error that I don't think is specific to our extension.  Someone was having the same issue here: https://github.com/microsoft/vscode/issues/71610

The marketplace may not be finishing the download, so maybe you can try again.  If that doesn't work, you could try updating or uninstall/reinstalling VS Code.
