### ISSUE TITLE
The execution of "Execute function now..." is failed with an error when entering blank request body for .NET 3.1 C# project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3027]
**OS:** Win10
**Build Version:** 20211206.2
**Regression:** Not a regression

**Repro Steps:**

1. Open an empty folder in VS Code -> Create a new **.NET 3.1 C#** project with HTTPTrigger template.
2. Debug -> Navigate to Azure view -> Expand the Functions node of "Local Project" -> Right click the function and execute "Execute Function Now..." -> Enter blank when asked to enter request body.
    ![image](https://user-images.githubusercontent.com/62053665/146503630-1e933386-40a8-47c1-b4a8-2039093a5199.png)
3. Check whether the execution of "Execute Function Now..." is successful without any error.

**Expect:**
The execution of "Execute function now..." is successful without any error.
![image](https://user-images.githubusercontent.com/62053665/146505132-3f5ad23e-0352-4143-b698-0336f2c8a928.png)

**Actual:**
The execution of "Execute function now..." is failed with an error.
![image](https://user-images.githubusercontent.com/62053665/146505113-0c05a360-4ea0-42fb-97ea-1bf40e8a25e2.png)

**More Info:**

1. This issue doesn't reproduce for **JavaScript/TypeScript/PowerShell/.NET 5/Java** project.
2. This issue also reproduces for **Python/.NET 6** project.

**Comment by nturinski** [comment]
@motm32 Investigated this. Because this only reproduces when the value is completely empty, it is okay to not fix this.
