### ISSUE TITLE
[Suggestion] It would be better if adding the information about project runtime v4 in the opened webpage

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3028]
**OS:** Win10
**Build Version:** 20211206.2
**Regression:** Not a regression
**Func Version:** 4.0.3971

**Repro Steps:**

1. Open an empty folder in VS Code -> Create a new project.
2. Create a function app with Azure Function v3.
3. Deploy the project to the function app -> Click "Learn more" when popping up the dialog.
    ![image](https://user-images.githubusercontent.com/62053665/146515876-a20aa510-0581-493f-893a-75dfece93ff1.png)
4. Check whether there is any information about project runtime v4 in the opened webpage.

**Actual:**
There is no information about project runtime v4 in the opened webpage. 
https://github.com/Microsoft/vscode-azurefunctions/wiki/Project-Runtime

**Suggestion:**
It would be better if adding the information about project runtime v4 in the opened webpage.

**Comment by ejizba** [comment]
Fixed it
