### ISSUE TITLE
Durable functions section in VS code not showing subscription account

### ISSUE THREAD

**Issue by prerna-tesser** [microsoft/vscode-azurefunctions#3029]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.6.0
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

**Comment by nturinski** [comment]
Please provide repro steps.

**Comment by prerna-tesser** [comment]
Issue was resolved with the help of the Durable Functions team
