### ISSUE TITLE
Debugging not working

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/vscode-azurefunctions#3030]
When developing an Azure Function in Visual Studio Code debugging is not working as expected. When setting a breakpoint in a default example c# http triggered Function it does not stop at the set breakpoint.

See below screenshot.
![image](https://user-images.githubusercontent.com/2125385/147211290-ac284bbf-de8b-4dbd-8179-1f5e85f67108.png)

Workaround:

![image](https://user-images.githubusercontent.com/2125385/147211388-b394a7ee-eae1-4c57-80bc-50430d546308.png)

**Environment:**

- Visual Studio Code version: 1.63.1 (64bits)
- Azure Function Core Tools version: 3.0.3785 (64bits)

Regards,
Stefan Stranger

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/3009

**Comment by nturinski** [comment]
@stefanstranger Sorry there hasn't been much traction on this issue. 

But I wanted to ask if this is still reproducing. Sometimes the VS Code or Function Core Tools are the root cause for debugging issues, so hopefully it's resolved,

If this is still an issue, do you know what OS the screenshots were taken in?

**Comment by alexweininger** [comment]
> If this is still an issue, do you know what OS the screenshots were taken in?

From the screenshots it's a Windows machine.

**Comment by nturinski** [comment]
I'm unable to reproduce this with the current build. Hits the breakpoint-- I'm wondering if there are some environments where the process ID doesn't match what we expect? Might have been a bug in the core tools as well.

![image](https://user-images.githubusercontent.com/5290572/209020661-d4234c46-e859-4440-a14b-822b2c79db81.png)

![image](https://user-images.githubusercontent.com/5290572/209020640-ad5f13b1-d13a-4863-8ddb-516a13dc187c.png)

![image](https://user-images.githubusercontent.com/5290572/209020702-2bc04c88-304f-4c09-ad74-94f57b4a7e87.png)

`Function Core Tools Version: 4.0.4915`
