### ISSUE TITLE
Configuration dependency on Microsoft.AspNetCore.Authentication.Core, only when starting with debugger

### ISSUE THREAD

**Issue by superman-lopez** [microsoft/vscode-azurefunctions#3033]
In a netcoreapp3.1 V3 Azure Function, I use the `IdentityModel.AspNetCore` nuget to manage the authentication of the HttpClient that is used in the function.  When I run the process locally with `func start` from terminal, the function works as expected.  However when I start the function through the `vscode-azurefunctions` debugger the connection to the function process fails with the following error on some unmet dependency in configuration.  The actual function does run in the background without issue.

>An unhandled host error has occurred. Microsoft.AspNetCore.Authentication.Core: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("ArmToken",...)?.

When I start the function with `func start` and then connect to the process manually with the debugger, the debugger and function work as expected (by using `processId`:`${command:pickProcess}` in launch.json).

VS Code: Version: 1.63.2
Azure Functions extension: 1.6.0
Azure Functions Core Tools: 3.0.3904

**Comment by nturinski** [comment]
@ superman-lopez Sorry that you're having these issues. Could you tell me what version of VS Code and the Azure Functions Extension that you are using?

**Comment by superman-lopez** [comment]
My apologies, should have included those from the start:
VS Code: Version: 1.63.2
Azure Functions extension: 1.6.0

**Comment by superman-lopez** [comment]
It seems the AspNetCore Authentication dependencies in Identity cause an issue for me during the deployment of the function as well.  I decided to just remove the dependencies, and move to MSAL.net and managing the tokens for the authentication of HttpClient through this.  It's a bit more code in my application, but clearly including `IdentityModel.AspNetCore` in my function was just not the way to do it.  I'll close the issue as the issue of the dependency is not isolated to the Azure Function extension.

https://stackoverflow.com/a/70086957/10340388
