### ISSUE TITLE
Automatically run npm install after initializing TypeScript project

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#3034]
Is it possible to run `npm i` after initializing a TS project (maybe do it for JS too for consistency)?

**Comment by wwlorey** [comment]
As of right now we do this for the user on debug. What is the reason you'd like to see `npm i` run for this case?

@fiveisprime what are your thoughts on this?

**Comment by ejizba** [comment]
We already do something similar for Python (pip install), so js/ts could be modeled after that. A few reasons I like this:
1. Users will get a 'clean' project as opposed to immediately seeing build errors from missing dependencies
2. Users might want to do some coding (with intellisense) before they debug, hence why they need `npm i` earlier

Only downside might be a delay while `npm i` runs, but with the right order of operations I think it could be tastefully done. Besides, they'll have to run `npm i` eventually no matter what.

**Comment by fiveisprime** [comment]
I love the idea of running it immediately after creating the project. It always bugs me that I have errors in the `index.ts` that opens from not having run npm install.
