### ISSUE TITLE
Azure function created with always on = off

### ISSUE THREAD

**Issue by ihorbond** [microsoft/vscode-azurefunctions#3037]
- VS Code Version: latest
- Azure Account Extension Version:
- OS Version: win 10

Steps to Reproduce:

1. Create an azure function via VS Code extension.
2. Deploy.
3. Login into Azure Portal and find the created function.
4. Go to Configuration -> General Settings.

Result: Always on = off
![image](https://user-images.githubusercontent.com/15573624/150407663-be00b06e-ea92-406f-8fad-6ee7fe245e1c.png)

**Comment by wwlorey** [comment]
More context on this:

From https://docs.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-general-settings:
> **Always On**: Keeps the app loaded even when there's no traffic. When Always On is not turned on (default), the app is unloaded after 20 minutes without any incoming requests. The unloaded app can cause high latency for new requests because of its warm-up time. When Always On is turned on, the front-end load balancer sends a GET request to the application root every five minutes. The continuous ping prevents the app from being unloaded.
Always On is required for continuous WebJobs or for WebJobs that are triggered using a CRON expression.

**Comment by ejizba** [comment]
Fyi @wwlorey I think this is only for app service plans (not consumption or premium) https://docs.microsoft.com/en-us/azure/azure-functions/dedicated-plan#always-on

@ihorbond can you confirm you chose a dedicated app service plan?

**Comment by ihorbond** [comment]
Yes, I did have an app service selected and it is HTTP triggered. so that means it should be off by default then and will wake on HTTP request and will take a some time to warm up correct ?
