### ISSUE TITLE
no longer able to debug azure functions on OSX

### ISSUE THREAD

**Issue by pkamphuis** [microsoft/vscode-azurefunctions#3040]
I can no longer debug C# azure functions in vscode.
On F5 it starts nicely. and the httpTriggers works normally. but any breakpoints are never hit.

Any suggestions on where to look?

**Comment by alexweininger** [comment]
Could you provide the following details? These will help us investigate.

- Operating system
- .NET SDK version
- Azure Functions extension version
- C# extension version
- VS Code version

If you happen to be using macOS, there is a recent issue with [debugging .NET Azure Functions on macOS](https://github.com/OmniSharp/omnisharp-vscode/issues/4903). There is also a [workaround](https://github.com/OmniSharp/omnisharp-vscode/issues/4903#issuecomment-993015843) that I have verified myself.

**Comment by pkamphuis** [comment]
I am not sure if it is same error. In my case it seems not to attach at all. Ending with a timeout notification about not being able to attach.
MacOs - Montery
.net SDK - 
3.1.301 [/usr/local/share/dotnet/sdk]
3.1.413 [/usr/local/share/dotnet/sdk]
5.0.401 [/usr/local/share/dotnet/sdk]
6.0.100 [/usr/local/share/dotnet/sdk]
Functions core tools - 4.0.3971
Vscode - 1.63.2 universal
Azure functions extension. - 1.6.0
C# extension - 1.24.0

I tried both 3.1 and 6.0 functions. Both fail to attach the debugger.

**Comment by pkamphuis** [comment]
Ok, although it looked different. I have the same issue. Using the described workaround resolved it.
Thanks
