### ISSUE TITLE
Azure function build fails after Visual Studio Update

### ISSUE THREAD

**Issue by anderson9149** [microsoft/vscode-azurefunctions#3048]
My azure functions were working fine from in visual studio code.  I updated my visual studio and now they give an error when trying to build.  The error given say "Source: Azure Function (extension).  Is anyone else having this issue?

**Comment by nturinski** [comment]
Wait, just want to be sure, but you wrote 
> updated my visual studio

Do you mean VS Code or actual Visual Studio?  Also what version did you upgrade from and what version are you on now?
