### ISSUE TITLE
createFunction returns before function is created

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode-azurefunctions#3052]
I have been using the createFunction API and found that after the call is made and the user completes the flow. The promise is immediately completed but the function file is not made and therefore any following commands/logic that requires to access the project file, for example, would not work and return undefined. 

The createFunction should ensure that the function file is made prior to completing the promise. 

The current workaround is to create a watcher to see when a project file or host.json is created from the createFunction.

**Comment by alexweininger** [comment]
Could you check this is related to #2908? It seems like a very similar scenario (and both from vscode-mssql irrc).

**Comment by VasuBhog** [comment]
It is similar, however, this seems to be a core issue with how the function returns the promise faster than the function file is actually created. I have been able to repro this many times.

**Comment by wwlorey** [comment]
This is likely a problem with the VS Code workspace not being updated by the time they attempt to read host.json. We should use `workspace` to write the json file instead of `fs-extra`.

**Comment by VasuBhog** [comment]
@wwlorey and @alexweininger any updates on if this is planned on being fixed / improved?

**Comment by nturinski** [comment]
Fixed by #3268
