### ISSUE TITLE
Debugging Azure Function with vscode

### ISSUE THREAD

**Issue by RaphaelSilv** [microsoft/vscode-azurefunctions#3053]
I've been struggling to debug an `HttpTrigger` type azure function with vscode. 

My assumption is that the issue might be related to the config files within `.vscode/` or at worst, my own environment.

As of now, when I try to debug a recently created function (func init) I get the following error from vscode:

```sh
> Executing task: dotnet clean /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

execvp(3) failed.: Permission denied

The terminal process "dotnet 'clean', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1)
```

Inside `.vscode/` there 4 files:

<pre>

    ├── extensions.json
    ├── launch.json
    ├── settings.json
    └── tasks.json

</pre>

and inside task.json there are a few dotnet related commands that are causing the error above.

Despite these files being automatically generated by core tools (func) I removed the dotnet lines from task.json and hit Debug.

After a few seconds I get:

```sh
Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting. 
```

Is there any command to automatically generate the debug configuration? e.g. `".NET generate assets for build and debug"`

Have you faced anything similar to it?

<hr>

My env settings:

```sh
OS: Ubuntu 20.04.4 LTS
Code:1.64.2 x64
Azure Functions Extension: v1.6.0
Core Tools Version: 3.0.3904
```

**Comment by nturinski** [comment]
[RaphaelSilv](https://github.com/RaphaelSilv)  Thanks for reporting!  It looks like the `dotnet clean` command isn't able to run in its current directory due to user permissions.

The tasks.json is necessary to debug because we are looking for that task to attach to the process, so deleting it will cause some issues.

**Comment by RaphaelSilv** [comment]
Replace the type from `process` to `shell` inside `tasks.json` solved it.

FWIW:
- [omnisharp-vscode #4556](https://github.com/OmniSharp/omnisharp-vscode/issues/4556)

**Comment by nturinski** [comment]
Thanks for bringing this issue to our attention.  Seems like this might be an upstream issue that we can't do anything about.  Changing it to shell seems like it has some negative performance impacts, but it's worth to use this workaround until it can get resolved.
