### ISSUE TITLE
No error validation prompts when creating a new function app with an existing name

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3056]
**OS:** All
**Build Version:** 20220228.3
**Regression:** Previous Release

**Repro Steps:**

1. F1 -> Azure Functions: Create Function App in Azure... -> Enter an existing name.
2. Check whether an error validation prompts.

**Expect:**
An error validation prompts.
![image](https://user-images.githubusercontent.com/57662131/156142471-f7fd980f-7a20-4df8-8828-b957c5f62693.png)

**Actual:**
No error validation prompts.
![image](https://user-images.githubusercontent.com/57662131/156142801-d9a4c1ed-0673-4e61-81f9-d55b84141264.png)

**More Info:**
This issue also reproduces when creating a new slot with an existing name.

**Comment by alexweininger** [comment]
Should get fixed by https://github.com/microsoft/vscode-azuretools/pull/1093
