### ISSUE TITLE
There is an error in the Files -> bin node of .NET 6 Function App after deploying a .NET project to this Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3057]
**OS:** All
**Build Version:** 20220228.3
**Regression:** Not a Regression

**Repro Steps:**
1. Create a .NET 6 C# project.
2. Create a .NET 6 Function App.
3. Deploy the C# project to the Function App.
4. Expand "Files" node of the Function App -> "bin" after deploying.
5. Check whether there is no error in this "bin" node.

**Expect:**
There is no error in the Files -> bin node.

**Actual:**
There is an error in the Files -> bin node.
![image](https://user-images.githubusercontent.com/45614674/156150790-06c40468-38db-488e-a8df-b23c26531cae.png)

**More Info:**
This issue also reproduced on the previous released Function extension.

**Comment by nturinski** [comment]
Does this prevent the Function app from working?

**Comment by v-ruizh** [comment]
@nturinski This doesn't prevent the Function app from working.

**Comment by nturinski** [comment]
Hi @v-ruizh

I just tested this with a .NET 6 app and it doesn't seem to be reproducing anymore.  Could you verify that this is still an issue?
