### ISSUE TITLE
The debugging disconnects automatically for a C# project on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3058]
**OS:** Mac(M1 Pro & Inter)
**Build Version:** 20220228.3
**.NET Version:** 6.0.200

**Repro Steps:**

1. Open a new folder in the VS Code -> Click "Create New Project..." button -> Select the opened folder -> C# -> .NET 6 -> HTTP trigger -> Type a function name -> Type a namespace -> Function.
2. Debug with "Attach to .NET Functions“.
3. Check whether succeeds to debug.

**Expect:**
Succeed to debug.

**Actual:**
The debugging disconnects automatically.

**More Info:**
This issue only reproduces on Mac.

**Comment by nturinski** [comment]
Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3009
