### ISSUE TITLE
The debugging disconnects automatically for JavaScript/TypeScript project on Linux

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3062]
**OS:** Ubuntu18.04
**Build Version:** 20220228.3
**Regression:** Not a Regression

**Repro Steps:**

1. Create a JavaScript project in VSCode.
2. Debug with "Attach to Node Functions“.
3. Check whether succeeds to debug.

**Expect:**
Succeed to debug.

**Actual:**
The debugging disconnects automatically.
![actual](https://user-images.githubusercontent.com/57662131/156330377-84069d63-4b46-4071-843b-d2fe2c6fc9a1.gif)

**More Info:**
1. This issue also reproduces for TypeScript project.
2. This issue doesn't reproduce for Python, PowerShell and .NET projects.
3. This issue doesn't reproduce on Windows and Mac.

**Comment by nturinski** [comment]
What version of node are you running on that Linux machine?  Based off the gif, it looks like it might be v10.  Could you try upgrading node and trying again?

**Comment by v-xinda** [comment]
The debugging doesn't disconnect automatically after upgrading nodejs to v16.14.0. So I close this issue.
