### ISSUE TITLE
The notification message is `Executed function "HttpTriggerJava1". Response: "Hello, {"name":"Azure"}"` when executing function for a Java project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3067]
**OS:** All
**Build Version:** 20220303.2
**Regression:** Not a regression

**Repro Steps:**
1. Create a new Java project with "HTTP trigger" function.
2. Debug -> Expand the Local Project tree view and right click on the function -> Select "Execute Function Now..." -> Press Enter with default value `{ "name": "Azure" }`.
3. Check whether the notification message is `Executed function "HttpTriggerJava1". Response: "Hello, Azure"`.

**Expect:**
The notification message is `Executed function "HttpTriggerJava1". Response: "Hello, Azure"`.

**Actual:**
The notification message is `Executed function "HttpTriggerJava1". Response: "Hello, {"name":"Azure"}"`.
![image](https://user-images.githubusercontent.com/62053665/156534289-e1966159-3b91-4742-87c4-b142ff0d7513.png)

**Comment by nturinski** [comment]
This is the response from the Java template trigger, so I don't think we should automatically parse it since we don't know what the user wants to do with the trigger response.
