### ISSUE TITLE
CustomLocations not showing when using Create Function (Advanced) in VSCode when user wants to create a new Function on Kubernetes with Azure Arc

### ISSUE THREAD

**Issue by apwestgarth** [microsoft/vscode-azurefunctions#3073]
Similar to an issue identified in the App Service extension (https://github.com/microsoft/vscode-azureappservice/issues/2172), when using the advanced create function workflow the customlocations are no longer being listed.

I have tested with the following Functions extension versions:
1.4.0
1.4.1
1.5.0
1.5.1
1.5.2
1.6.0

Issue persists with all.

**Comment by nturinski** [comment]
I currently still see it, but it only works for Linux function apps.
![image](https://user-images.githubusercontent.com/5290572/205184764-a4961a0b-05d1-4139-a033-66a6c78e3245.png)

Based off the portal, I believe that is the intended behavior.

![image](https://user-images.githubusercontent.com/5290572/205184944-761cdc19-7c2a-4fcf-80de-a6282dfb819a.png)

![image](https://user-images.githubusercontent.com/5290572/205184910-5482fabc-9780-40d6-9966-5d343e326058.png)
