### ISSUE TITLE
"make sure your project is running locally" link points to the wrong site

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-azurefunctions#3074]
![image](https://user-images.githubusercontent.com/15258962/157485803-cb08d82a-b21f-4bdf-9c8e-2362c0e0aa69.png)

goes to
https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/azure-function-cosmos-db-mongo-api

**Comment by wwlorey** [comment]
Good find, @JustinGrote. We'll update that URL.

**Comment by nturinski** [comment]
Updated the link with something more relevant. Thanks for bringing it to our attention!
