### ISSUE TITLE
An error "ServiceUnavailable" shows under "Functions" node of one Linux PowerShell 7.2 Function App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3076]
**OS:** Win10
**Build Version:** 20220310.1
**PowerShell Version:** 7.2.1.0
**Regression:** Not a regression

**Repro Steps:**
1. Create a **Linux PowerShell 7.2** Function App.
2. Expand the "Functions" node of above Function App.
3. Check whether there is no error under "Functions" node.

**Expect:**
There is no error under "Functions" node.

**Actual:**
An error "ServiceUnavailable" shows under "Functions" node.
![image](https://user-images.githubusercontent.com/57662131/157835880-043e9c83-0e1d-427d-80a2-91cada5510d6.png)

**More Info:**
1. This issue does not reproduce for a **Windows PowerShell 7.2** Function App.
2. This issue does not reproduce for a **Linux PowerShell 7.0** Function App.
3. Refreshing can't fix this issue.

**Comment by wwlorey** [comment]
This may just not be supported at this time. Or it could be a temporary outage.

@v-xinda, can you please try this again and see if it still reproduces?

**Comment by v-xinda** [comment]
Verified this issue with the latest build 20220318.1, it doesn't reproduce. So I close it.

**Comment by v-xinda** [comment]
1. This issue still reproduces for the Linux PowerShell 7.2 Function App created with app service and premium host plan. 
![image](https://user-images.githubusercontent.com/57662131/159400716-7508e622-c78f-4701-a493-a26db4509ce3.png)
2. This issue doesn't reproduce for the Linux PowerShell 7.2 Function App created with consumption host plan. 
3. Fail to deploy powershell project to the Linux PowerShell 7.2 Function App with the same error.
![image](https://user-images.githubusercontent.com/57662131/159417339-d3a70a77-9500-4485-89ab-fd684007a293.png)

**Comment by nturinski** [comment]
If this isn't happening consistently, it seems like it might just be a timing issue.  How often is this happening?

Could you try again and make sure that it's not immediately after creation?  Sometimes the function apps can take a while to start up and you'll run into errors like this.

**Comment by v-xinda** [comment]
@nturinski  This issue is happening consistently now. Wait for a while, the error still exists after refreshing.
Pop up the same error immediately because syncing triggers is not successful after deployment.
![image](https://user-images.githubusercontent.com/57662131/160071016-2be338e1-697c-449b-b1b0-1917a2826fc9.png)
