### ISSUE TITLE
Issue with createFunction API SQL Input/Output Template

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode-azurefunctions#3082]
While utilizing the createFunction API I found that it opens the AzureWebJobsStorage wizard shown here:
![image](https://user-images.githubusercontent.com/23587151/159390351-18442a8a-5626-4873-87e9-24f7153b8970.png)

If the templateID is something other than HTTPTrigger (code: https://github.com/microsoft/vscode-azurefunctions/blob/main/src/debug/validatePreDebug.ts#L123)

As a result, the workaround for SQL Input and Output Templates which are for HTTP Triggers would also prompt the user of this even though they would not needed it for there azure function. 

I wanted to see if there was a better way we could pass in the suppress dialog parameter from createFunction API in order to solve this. 

Issue also tracked here: https://github.com/microsoft/azuredatastudio/issues/18780

**Comment by nturinski** [comment]
Hopefully this is something that we can discern by consuming the template feed, but we'll have to investigate this.

**Comment by VasuBhog** [comment]
https://github.com/microsoft/vscode-azurefunctions/pull/3185 fixed this.
