### ISSUE TITLE
There are confused logs in output window when deploying a Java project to Java Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3083]
**OS:** All
**Build Version:** 20220315.4
**Function Core Tools:** v4
**Regression:** Not a Regression

**Repro Steps:**
1. Create a Java project.
2. Create a Java Function App.
3. Deploy the Java project to Java Function App.
4. Check whether there is no confused log in output window during deployment.

**Expect:**
There is no confused log in output window during deployment.

**Actual:**
There are confused logs in output window during deployment.
![image](https://user-images.githubusercontent.com/45614674/159445948-a0c0d3ad-3f70-451f-a428-298ebea2e97d.png)

**More Info:**
1. The log "Stopping app..." still exists when deploying a Java project to a **stopped** Java Function App.
2. This issue does not reproduce when deploying other projects (C#/JavaScript/TypeScript/Python/PowerShell).
3. This issue also reproduces on the previous released Function extension.

**Comment by alexweininger** [comment]
Java Function Apps are required to be stopped before deploying, so we start the app after deploying. We don't check if the Function App is already stopped before deploying. And we always start the App after deploying to make sure the Triggers are synced.
