### ISSUE TITLE
There is an error in the subscription node after signing in with Azure Germany account

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3084]
**OS:** All
**Build Version:** 20220315.4
**Function Core Tools:** v4

**Repro Steps:**
1. Sign in with Azure Germany account.
2. Expand the subscription node in Azure view.
3. Check whether there is no error in the subscription node.

**Expect:**
There is no error in the subscription node.

**Actual:**
There is an error in the subscription node.
![image](https://user-images.githubusercontent.com/45614674/159451632-9c41ea56-76ea-47ed-b18a-176519ec6d50.png)

**More Info:**
This issue does not reproduce when signing in Azure China account.

**Comment by alexweininger** [comment]
Can you try logging into the Azure Germany account again? Can you access https://portal.microsoftazure.de/? Azure Germany has been nearing its end of service life and I'm not able to access it anymore.

**Comment by nturinski** [comment]
Since Azure Germany is considered deprecated and decommissioned, there is nothing we can do to support AzureGermany cloud so I'll close this issue.
