### ISSUE TITLE
Fail to create a basic Python function app with any location after signing in the Azure China account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3085]
**OS:** All
**Build Version:** 20220315.4
**Function Core Tools:** v4

**Repro Steps:**

1. Sign in with Azure China account -> Create a basic Python function app with any location.
2. Check whether succeeds to create a basic Python function app.

**Expect:**
Succeed to create a basic Python function app with any location.

**Actual:**
Fail to create a basic Python function app with any location.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62053665/159464143-e16a6a91-88b3-498a-b387-c7cfdab1bcd4.png)

**More Info:**

1. This issue also reproduces for a Linux function app created with other runtimes and "Consumption" hosting plan. 
2. This issue doesn't reproduce for a Windows function app created with other runtimes and "Consumption" hosting plan. 
3. This issue doesn't reproduce for a Linux function app created with **all runtimes** and "App Service Plan/Premium" hosting plan.

**Comment by alexweininger** [comment]
Linux Consumption plans are not supported on Azure China.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/12476526/159807840-0bb78fd3-9345-4860-9e54-261882ac3e18.png">

**Comment by v-mengwe** [comment]
Thanks for your update. As above, it would be better if the error meaasge is "Linux Consumption plans are not supported on Azure China.".
![image](https://user-images.githubusercontent.com/62053665/159834366-a8700c75-fd77-4fba-92d9-7721e20f643e.png)
