### ISSUE TITLE
InvalidJsonError when provisioning storage account within resource array of ARM template

### ISSUE THREAD

**Issue by LinardsLiepins** [microsoft/vscode-azurefunctions#3086]
I am hitting the following error:

OperationStopped: /workspace/1/s/<some file>.ps1:167
Line |
 167 |              throw $_.Exception
     |              ~~~~~~~~~~~~~~~~~~
     | 12:40:50 - The deployment
     | '...' failed with error(s).
     | Showing 1 out of 1 error(s). Status Message: The request
     | cannot be interpreted as valid Json:
     | {"sku":{"name":"Standard_RAGRS","tier":"Standard"},"kind":"StorageV2","location":"westeurope","tags":{"suite-version":"0.0.6","profile-name":"...","infraVersion":"0.0.6","component-name":"...","utilVersion":"0.0.6","cost":"AI","deployment-datetime":"22-03-2022 12:40:00 Z+00","suite-name":"subscription_layer","APMID":"...","CreatedOnDate":"2022-03-22T12:40:45.6416576Z","Environment":"DEV"},"properties":{"minimumTlsVersion":"TLS1_2","networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[{"id":"/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/.../subnets/...","action":"Allow"},{"id":"/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/...","action":"Allow"}],"ipRules":[{},{},..],"defaultAction":"Deny","resourceAccessRules":"[]"},"supportsHttpsTrafficOnly":true,"encryption":{"services":{"file":{"enabled":true},"blob":{"enabled":true}},"keySource":"Microsoft.Storage"},"accessTier":"Hot"}}. (Code:RequestIsNotValidJson)

I have ensured that the ARM template is valid JSON, there are no comments or anything, and the values within networkAcls object, passed from Powershell into ARM template properties, are also valid. Now, I am running out of the ideas...

**Comment by nturinski** [comment]
Hi @LinardsLiepins 

Sorry that you're having issues.  How are you trying to deploy this though?  This doesn't appear to be a function app and this is the Azure Functions Extension repo.

I think you might have better luck posting an issue here https://github.com/microsoft/vscode-azurearmtools.
