### ISSUE TITLE
[Codespaces] Fail to debug a C# project again with an error "Failed to detect running Functions host within "60" seconds..."

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3091]
**Environment:** Local Codespaces
**Azure Function Core Tools:** v4
**Build Version:** 20220325.1

**Repro Steps:**
1. Create a .NET 6 C# project.
2.  Set a breakpoint.
3. Debug this C# project.
4. Stop debugging and debug this project again.
5. Check whether succeeds to debug the C# project again.

**Expect:**
Succeed to debug the C# project without any error.

**Actual:**
Fail to debug the C# project with an error.
![image](https://user-images.githubusercontent.com/45614674/160096309-83855f1a-38be-4865-a71e-7de382c631db.png)

**More Info:**
1. No task starts in the second debugging.
2. Kill the "host start task" and then debug the C# project again, this issue does not reproduce.
3. This issue does not reproduce in the non-codespaces environment.
4. This issue also reproduces with the previous released Function extension installed - Local Codespaces.

**Comment by nturinski** [comment]
Thanks for filing this issue.  

While it's a good find, it's a bit of an edge case scenario.  We probably don't have the time to fix this, but if it escalates to an issue that a lot of users start running into, we'll revisit this.
