### ISSUE TITLE
Support Func CLI installation for Linux

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurefunctions#311]
Due to the need for "sudo" cmds, the extension cannot install the Azure Func CLI for Linux users.

**Comment by EricJizbaMSFT** [comment]
Looks like VS Code uses `https://www.npmjs.com/package/sudo-prompt`. We could probably do the same

**Comment by ejizba** [comment]
Will close this in favor of https://github.com/microsoft/vscode-azurefunctions/issues/2745
