### ISSUE TITLE
Worker Failed to function error during debug

### ISSUE THREAD

**Issue by mcolellajensen** [microsoft/vscode-azurefunctions#3117]
Im running into an issue when trying to test a Durable function locally. 
Thought it might be an enviornment issue but not sure where the issue might be. 
Thanks! 

Currently using VS Code to Debug an Azure durable function. 
Using Python version 3.9
VS Code version 1.66
 Repro steps: 
activate conda base in terminal 
launch azurite 
f5 to run and debug 

produces this error 
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2022-04-15T23:24:37.764Z] Worker process started and initialized.
[2022-04-15T23:24:39.687Z] Worker failed to function id c3087825-eb13-44a5-8314-490a9609ee6f.
[2022-04-15T23:24:39.689Z] Result: Failure
Exception: SyntaxError: invalid syntax (__init__.py, line 71)

the details reference a number of files in my Anaconda path that use File "<frozen importlib._bootstrap>" l

**Comment by nturinski** [comment]
Hi @mcolellajensen 

It looks like a syntax error is coming from your `init.py` file.  I think that's causing your functions project to fail when trying to start.  Could you try fixing that issue and trying again?

**Comment by mcolellajensen** [comment]
thanks @nturinski 
I did change one of the import statements in init.py file. 
Now getting this error? 
Worker process started and initialized.
[2022-04-22T23:08:29.152Z] General error: Failed to create the task hub: DurableTask.AzureStorage.Storage.DurableTaskStorageException: No connection could be made because the target machine actively refused it.

**Comment by mcolellajensen** [comment]
@nturinski 
I corrected an error on a module import, And re-installed storage-emulator and that fixed the problem. Thank you so much for the help!

**Comment by nturinski** [comment]
Glad to hear it!  You did all the heavy lifting though 😊 I'll go ahead and close this then.  Thanks for using the extension!
