### ISSUE TITLE
It navigates to select a resource group when executing "Deploy to Function App..." action for a Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3128]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a Regression

**Repro Steps:**
1. Create and open a project in VS Code.
2. Create a Function App.
3. Right click this Function App and select "Deploy to Function App...".
4. Check whether a confirmation dialog pops up or not.

**Expect:**
A confirmation dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/164613008-0ba03f8e-efaa-4cdd-9649-38d7591fa76a.png)

**Actual:**
It navigates to select a resource group.
![image](https://user-images.githubusercontent.com/45614674/164613148-428facc6-bd3b-4930-a048-5061eac1d4bf.png)

**Comment by alexweininger** [comment]
Fixed by #3154
