### ISSUE TITLE
Succeed to add a new application setting with an error when executing "Add New Setting..." command by command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3130]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Previous Build

**Repro Steps:**
1. Create a Function App.
2. F1 -> Azure Functions: Add New Setting... -> Select the resource group -> Select the Function App -> Enter an application setting name -> Enter a value to finish this creation.
3. Check whether succeeds to add a new setting without any error.

**Expect:**
Succeed to add a new application setting without any error.

**Actual:**
Succeed to add a new application setting with an error.
![image](https://user-images.githubusercontent.com/45614674/164616453-bb2d4d77-ac98-460e-998a-2f6925b991df.png)

**More Info:**
1. This issue does not reproduce when adding a new setting by context menu.
2. This issue does not reproduce on the previous Azure Function unified build 20220421.1.

**Comment by alexweininger** [comment]
Fixed by #3141
