### ISSUE TITLE
There is no application setting in the "Select App Setting" list when executing "Edit Setting..." command by command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3131]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Previous Build

**Repro Steps:**
1. Create a Function App.
2. F1 -> Azure Functions: Edit Setting... -> Select a resource group -> Select a Function App.
3. Check whether all application settings show in the "Select App Setting" list or not.

**Expect:**
All application settings show in the "Select App Setting" list.
![image](https://user-images.githubusercontent.com/45614674/164618717-3ea3b908-f007-429d-ab0b-88a7d002045e.png)

**Actual:**
There is no application setting in the "Select App Setting" list, only "+Create new App Setting..." shows in the list.
![image](https://user-images.githubusercontent.com/45614674/164618677-656e1ec9-7104-46c5-88da-766a2c84ba99.png)

**More Info:**
This issue does not reproduce on the previous Azure Function unified build 20220421.1.

**Comment by alexweininger** [comment]
Fixed by #3141
