### ISSUE TITLE
No "Open file" dialog pops up when executing "Download Remote Settings..." command from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3133]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Previous Build

**Repro Steps:**
1. Create a Function App.
2. F1 -> Azure Functions: Download Remote Settings... -> Select a resource group -> Select a Function App.
3. Check whether the "Open file" dialog pops up or not.

**Expect:**
The "Open file" dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/164622110-b7ee7d92-50b3-4139-9792-b9d4cba24a3c.png)

**Actual:**
No "Open file" dialog pops up, it will navigate to "Select App Setting" option.
![image](https://user-images.githubusercontent.com/45614674/164623077-91ba3e6b-e9ba-4b55-9f79-71c053069f1c.png)

**More Info:**
1. This issue also reproduces for "Azure Functions: Upload Local Settings..." command.
2. This issue does not reproduce on the previous Azure Function unified build 20220421.1.

**Comment by alexweininger** [comment]
Fixed by #3141
