### ISSUE TITLE
Fail to execute command "Azure Function: Upload Local Settings..." with an error from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3137]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a Regression

**Repro Steps:**

1. Open a project in VS Code -> Make sure a local.setting.json file in the opened project.
2. F1 -> Azure Function: Upload Local Settings... -> Select a subscription -> Select Function App -> Select a function web app.
3. Check whether succeeds to execute command "Azure Function: Upload Local Setting..." directly.

**Expect:**
Succeed to execute command "Azure Function: Upload Local Settings..." directly.

**Actual:**
Continue to perform the next step and fail to execute command "Azure Function: Upload Local Settings..." with an error.
<img width="445" alt="Screen Shot 2022-04-22 at 15 52 10" src="https://user-images.githubusercontent.com/62053665/164643880-d53eb637-8de4-4afe-8865-c79c09c2f73c.png">

**More Info:**
This issue also reproduces for the command "Azure Function: Download Remote Settings...".

**Comment by v-mengwe** [comment]
This issue also reproduces for the command "Azure Function: Toggle as Slot Settings...".

**Comment by alexweininger** [comment]
Fixed by #3141
