### ISSUE TITLE
There is an extra step “+ Create new App Setting" when executing "Azure Functions: Add New Setting..." from command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3138]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a Regression

**Repro Steps:**

1. F1 -> Azure Functions: Add New Setting... -> Select a resource group -> Select a Function App.
2. Check whether the next step is "enter a new app setting name" or not.

**Expect:**
The next step is "enter a new app setting name".
<img width="504" alt="Screen Shot 2022-04-22 at 17 51 08" src="https://user-images.githubusercontent.com/62053665/164682758-5b354af9-2c16-47ce-ad62-a0b6b8ebe4bc.png">

**Actual:**
There is an extra step “+ Create new App Setting".
<img width="611" alt="Screen Shot 2022-04-22 at 17 51 44" src="https://user-images.githubusercontent.com/62053665/164682839-312b1af3-7e11-4e9f-a88c-565b09ce8591.png">

**Comment by alexweininger** [comment]
Fixed by #3141
