### ISSUE TITLE
There is a duplicate "Refresh" action in "Files/Logs/Deployments" context menu after installing App Service extension unified build

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3139]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Expand a Function App node in Azure Resources view.
2. Right click the "Files" node to open its context menu.
3. Check whether there is no duplicate action in the context menu.

**Expect:**
There is no duplicate action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/164960369-6faa690b-c672-43c5-833c-47857168d8c2.png)

**Actual:**
There is a duplicate "Refresh" action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/164960377-481aee22-faf2-4730-b05d-9474ba37554a.png)

**More Info:**
This issue also reproduces for "Logs" and "Deployments" nodes.

**Comment by alexweininger** [comment]
Closed by #3141
