### ISSUE TITLE
Expand Remote Debug Feature to App Services extension and support more languages

### ISSUE THREAD

**Issue by mrcrane** [microsoft/vscode-azurefunctions#314]
Remote debugging support was added behind a feature flag in #222 #238 . This current implementation is specific to Java Functions.

@rramachand21 has added a new tunneling endpoint in Kudu that will allow for a more generic approach. Kudu will expose the /AppServiceTunnel/Tunnel.ashx endpoint which will tunnel to whatever port is configured with the APPSVC_TUNNEL_PORT app setting. The process will also have to be started with remote debugging enabled on that port. This is language-specific, but if you are using an azure blessed container we will standardize on a setting called "remoteDebuggingEnabled" which will launch the process and set the APPSVC_TUNNEL_PORT setting appropriately.

This functionality will be enabled across both App Services and Functions and should be implemented in a shared library. Looking at the code, it seems like the vscode-azureappservice npm package is a good place for this: https://github.com/Microsoft/vscode-azuretools/tree/master/appservice

I can implement (or help), but want to first verify that this plan makes sense.

Suggested plan would be to:
* Add a debugRemoteApp.ts to the vscode-azureappservice npm package
  * It will verify that either "remoteDebbuggingEnabled" is set or "APPSVC_TUNNEL_PORT" is set on app
  * Setup debug proxy to the new Kudu tunnel endpoint
  * Launch the debugger
    * Open question: How will we know which language debugger to launch? Options:
      * Try to detect from app settings
      * Detect from code that is currently opened in VS Code
      * Functions team may provide an API for this
      * If all else fails, allow user to choose from menu
* Attach this command to the context menus in both the App Services and Functions extensions
  * Use same menu text: "Attach debugger"
  * Use a feature flag, current flag still makes sense: "azureFunctions.enableRemoteDebugging". Also add "appService.enableRemoteDebugging".
  * Open question: What do we do with the older Java Functions remote debug command. Options:
    * Give it a different context menu option like "Attach Java debugger".
    * Use a different feature flag (still need to give it a different name in the context menu in case both feature flags are enabled)
    * Remove it when we are convinced that it is fully obsolete (not quite yet)

**Comment by EricJizbaMSFT** [comment]
Sounds great to me! And yes that shared npm package is definitely the place for most of the code.

One questions though - are you aware that @auchenberg has been working on a prototype for remote debugging in the app service extension? That work is being tracked here: https://github.com/Microsoft/vscode-azureappservice/issues/384 and hopefully it leverages the generic approach you described?

Open questions:
1. Language: For Functions - we have a VS Code setting (`azureFunctions.projectLanguage`) that will tell you the language. We might have to be more creative for the app service extension. For example, I assume people debug locally before they try debugging the remote, which means you could check their `.vscode/launch.json` file to see if it's setup for node/.net core, etc.
1. Java: I would vote for one context menu item that just special-cases the Java case until the generic approach makes the Java-specific approach obsolete

**Comment by auchenberg** [comment]
You should factor in the recent changes for the Node App Service image in https://github.com/Azure-App-Service/node/pull/37/files

**Language detection**
It's my understanding that the Functions team will add an environment variable reflecting what language that's used/deployed for the given function instance.  @rramachand21 might be able to provide some details.

You are also able to debug (at least Node functions) without having the local Function code open in the VS Code workspace I doubt trying to detect the local language will be a working solution.

**Launch.json**
You can't rely on persisted configurations in the `launch.json` as those can be provided dynamically be extensions.  One thing to consider here could be to provide a new Debug Adaptor for VS Code so a user can have a specific debug configuration for an instance for quick access as a alternative to the tree-view experience. Think `type: 'azure-cloud-function`

**Java and non-Node langauges**
To me there doesn't seem to be any specific requirements for the Java integration other than setting a `JAVA_OPS` environment variable, so I would aim to merge the scenarios to have a consistent experience.

For other languages then Node please be aware that the user need to install the specific Debug Adaptor (Python, Go, etc) before the launch config will work. This should be factored into the experience. Maybe prompt users for an install?
