### ISSUE TITLE
There are two extra actions in "Deployments" context menu after installing App Service extension unified build

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3140]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Expand a Function App node in Azure Resources view.
2. Configure deployment source is None.
3. Right click the "Deployments" node to open its context menu.
4. Check whether there is no extra action in the context menu.

**Expect:**
There is no extra action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/164960827-d2f9e1e4-c7a6-4b38-8415-1ce345a21053.png)

**Actual:**
There are two extra actions in the context menu.
![image](https://user-images.githubusercontent.com/57662131/164960787-80218cdb-ff03-4a8b-a3eb-6eb6f4c60f37.png)

**Comment by alexweininger** [comment]
Closed by #3141
