### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.cosmos' 

### ISSUE THREAD

**Issue by Mepau** [microsoft/vscode-azurefunctions#3151]
I've been trying to incorporate azure.cosmos into a azure function without using binding since the scenario isn't beneficial for it.

The problem every time i try to import it i get ModuleNotFoundError as follow:

`[2022-05-04T03:00:41.809Z] Worker failed to load function: 'HttpTrigger1' with function id: '8b8c7e22-7d68-4531-93b0-f43dcc2e7f6c'.
[2022-05-04T03:00:41.809Z] Result: Failure
Exception: ModuleNotFoundError: No module named 'azure.cosmos'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 305, in _handle__function_load_request
    func = loader.load_function(
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 42, in call
    raise extend_exception_message(e, message)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 40, in call
    return func(*args, **kwargs)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\loader.py", line 85, in load_function
    mod = importlib.import_module(fullmodname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\micha\Desktop\azure durable test\HttpTrigger1\__init__.py", line 4, in <module>
    import azure.cosmoss`

I've double check the requirements.txt and it is as follows:

`azure-functions
azure-cosmos`

I've also double check the .env file for the module and its there

![image](https://user-images.githubusercontent.com/25083076/166618627-ba9402dc-b45c-43df-ae4d-6d18625126d2.png)

I'm using Azure Function Core tools 4.0.4483 along with Python 3.9 from Microsoft Store.

Lastly, i can in fact run the script with the venv python interpreter without issues but like mentioned unable to do so when debugging from local function simulation via F5 command which throws the mentioned error.

I'm also having the same issue with azure durable functions module so I'm really are at loss here since the current workaround isn't the most optimal for my use case.

**Comment by alexweininger** [comment]
Have you gone through the [Module Not Found error troubleshooting guide](https://aka.ms/functions-modulenotfound)?

> Lastly, i can in fact run the script with the venv python interpreter without issues but like mentioned unable to do so when debugging from local function simulation via F5 command which throws the mentioned error.

Since the error only happens when debugging with VS Code, it seems like VS Code is not setup to use the same venv as what's used when you run it outside of VS Code. 

Can you share what value you have for the `Azure Functions: Python Venv` setting?

![image](https://user-images.githubusercontent.com/12476526/175430717-e45e5110-92a5-44b0-a522-67729351620a.png)

**Comment by Shopnet** [comment]
Could you please share the vscode debug traces
