### ISSUE TITLE
[Suggestion] Don't show Logic Apps in Functions Extension

### ISSUE THREAD

**Issue by anthonywhite** [microsoft/vscode-azurefunctions#3165]
Or if you think you must, show them with a Logic App icon.

After all, there are Logic Apps extensions...

**Comment by nturinski** [comment]
The payload includes `functionapp` in its kind.  We should filter `workflowapp` out of what we display

![image](https://user-images.githubusercontent.com/5290572/175430527-8b0f555f-4a14-42d6-a023-bf8cb56afdee.png)

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/332
