### ISSUE TITLE
It navigates to select a resource when executing "Deploy to Function App..." action by context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3169]
**OS:** All
**Azure Resource Extension Build Version:** 20220515.1
**Azure Function Extension build Version:** 20220513.15

**Repro Steps:**
1. Create and open a project in VS Code.
2. Create a Function App.
3. Right click this Function App and select "Deploy to Function App...".
4. Check whether a confirmation dialog pops up or not.

**Expect:**
A confirmation dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/168560992-bf725a07-8043-4a1e-ae37-4993b7c85bd7.png)

**Actual:**
It navigates to select a resource.
![image](https://user-images.githubusercontent.com/45614674/168561064-4239885c-ec99-4626-90dd-6b505a339d6c.png)

**Comment by joshtransient** [comment]
This issue still occurs for me, on a fresh install of VSCode (v1.67.2), with fresh installs of extensions on latest versions.
