### ISSUE TITLE
There are no "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions in "Function App" context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3171]
**OS:** All
**Azure Resource Extension Build Version:** 20220515.1
**Azure Function Extension build Version:** 20220513.15

**Repro Steps:**
1. Make sure the resources group by "Resource Type".
2. Right click the "Function App" node.
3. Check whether there are "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions in context menu or not.

**Expect:**
There are "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions in context menu.

**Actual:**
There are no "Create Function App in Azure..." and "Create Function App in Azure... (Advanced)" actions in context menu.
![image](https://user-images.githubusercontent.com/45614674/168564951-51185fda-38d3-4a2a-875f-5ba8b9dea335.png)

**More Info:**
There are creation actions for Static Web Apps.
![image](https://user-images.githubusercontent.com/45614674/168565190-b7ba24d6-524b-4495-a16a-33b4969c7eda.png)

**Comment by v-ruizh** [comment]
@nturinski @joshtransient I can reproduce this issue "Create function app in Azure (advanced) is still missing". You can get the details from below.

**Repro Steps:**
1. Make sure **there is no Function App** in your subscription.
2. Right click the "Function App" node, there is only a basic creation action, see below screen.
![image](https://user-images.githubusercontent.com/45614674/172338408-26905522-abd3-4302-bd35-ba321eb27d4e.png)

**Notice:**
This issue does not reproduce if there is Function App in your subscription.
![image](https://user-images.githubusercontent.com/45614674/172338841-7f7c5cdc-9e59-4ca6-99fe-92c2361b4b6e.png)

**Comment by joshtransient** [comment]
Hi @v-ruizh, I can repro that exactly. "Create Function App in Azure... (Advanced)" appears when my tenant has at least one deployed function app. Azure Functions extension version is 1.7.3.

**Comment by alexweininger** [comment]
> Hi v-ruizh, I can repro that exactly. "Create Function App in Azure... (Advanced)" appears when my tenant has at least one deployed function app. Azure Functions extension version is 1.7.3.

Thanks for the info @v-ruizh and @joshtransient.

**Comment by joshtransient** [comment]
Looks like I can do advanced create from the extensions section. Still a shame that I can't just "Deploy to Function app..." and have that take care of both the creation (of the resource group, function app, etc), then immediately deploy.
