### ISSUE TITLE
An incorrect error "Encountered an error (BadGateway) from host runtime." pops up when executing function for a basic Node.js function app from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3179]
**OS:** Win10
**Azure Resource Extension Build Version:** 20220518.13
**Azure Function Extension build Version:** 20220517.4

**Repro Steps:**

1. Create a new basic Node.js function app.
2. F1 -> Azure Function: Execute Function Now... -> Select a subscription -> Select the created Node.js function app.
3. Check whether an error "No functions found." pops up.

**Expect:**
An error "No functions found." pops up.
![image](https://user-images.githubusercontent.com/62053665/168976374-32cf633f-4776-44d7-8b4b-eadb68d86664.png)

**Actual:**
An incorrect error "Encountered an error (BadGateway) from host runtime." pops up.
![image](https://user-images.githubusercontent.com/62053665/168976362-cf004845-7db0-4e1f-a55d-4f88905b45d9.png)

**More Info:**

1. This issue also reproduces for a new basic **PowerShell/Java** function app.
2. This issue **does not** reproduce for a new basic **C#/Python** function app.

**Comment by v-mengwe** [comment]
Expand the new created function -> There is an error under the "Functions" node.
![image](https://user-images.githubusercontent.com/62053665/168992630-3742e02c-35a7-4ba4-a561-6dc0efa19c97.png)
Refresh the function app -> The error disappears -> Execute "Azure Function: Execute Function Now..." command again -> The error is correct.
![image](https://user-images.githubusercontent.com/62053665/168993261-3f03aa69-172e-48e3-90a8-9e33ab618d44.png)

**Comment by alexweininger** [comment]
Does this only happen if the app has just been created?

**Comment by MicroFish91** [comment]
Similar - it seems to happen mostly when the function app has no added user content to pull.
