### ISSUE TITLE
Azure function Extension Taking long time to Load (VS Code)

### ISSUE THREAD

**Issue by Kynsai007** [microsoft/vscode-azurefunctions#3182]
- Issue Type: `Bug`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `1.6.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.64.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by nturinski** [comment]
Please provide us with more information.  

> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

Could you please paste this data?
