### ISSUE TITLE
An error "ServiceUnavailable" occurs in Files node and Logs node of a Windows Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3188]
**OS:** Win10/M1
**Azure Resource Extension Build Version:** 20220523.7
**Azure Function Extension build Version:** 20220523.6

**Repro Steps:**
1. Create a **Windows** Function app.
2. Expand this web app -> Files node and Logs node.
3. Check whether there is no error in Files node and Logs node.

**Expect:**
There is no error in Files node and Logs node.

**Actual:**
An error "ServiceUnavailable" occurs in Files node and Logs node.
![image](https://user-images.githubusercontent.com/45614674/169979092-0e886a21-15e6-4618-89b4-670ba5a1c830.png)

**More Info:**
This issue does not reproduce for a Linux Function App.

**Comment by bwateratmsft** [comment]
This might have been a service issue.

**Comment by nturinski** [comment]
@v-ruizh Could you confirm that this is always reproducing? As @bwateratmsft mentioned, seems like it was a service issue that usually ends up resolving itself.

**Comment by v-ruizh** [comment]
@nturinski This issue can be reproduced consistently. But the error will disappear after deployment.
