### ISSUE TITLE
Error when picking Create new local app setting from local.settings.json when creating blob trigger (Error getSubscriptionPromptStep)

### ISSUE THREAD

**Issue by eamonoreilly** [microsoft/vscode-azurefunctions#3191]
Repro steps:
1. Create new Function from the workspace
2. Create new project when prompted
3. Select JavaScript (happens on any language)
4. Select Azure Blob Storage trigger
5. Select "BlobTrigger1" as function name
6. On "Select setting from "local.settings.json" ", choose +Create new local app setting

Expected:
New value created and written to local.settings.json upon creation

Actual:
Error appears with "Cannot read properties of undefined (reading 'getSubscriptionPromptStep')

**Comment by alexweininger** [comment]
Thanks for reporting the issue, I'm able to reproduce this. 

Notes:

Issue is with this line https://github.com/microsoft/vscode-azurefunctions/blob/411ece5f9453af075c1ff48c70aec349f5942a47/src/commands/addBinding/settingSteps/LocalAppSettingListStep.ts#L75

> On "Select setting from "local.settings.json" ", choose +Create new local app setting

Doesn't reproduce if you pick an existing setting on this step.

**Comment by ivctr** [comment]
@alexweininger thank you very much. Please how do one pick an existing setting on this step?
 I am having the same issue

**Comment by ivctr** [comment]
> Repro steps:
> 
> 1. Create new Function from the workspace
> 2. Create new project when prompted
> 3. Select JavaScript (happens on any language)
> 4. Select Azure Blob Storage trigger
> 5. Select "BlobTrigger1" as function name
> 6. On "Select setting from "local.settings.json" ", choose +Create new local app setting
> 
> Expected: New value created and written to local.settings.json upon creation
> 
> Actual: Error appears with "Cannot read properties of undefined (reading 'getSubscriptionPromptStep')

Please have you found a fix around this?

**Comment by dwoldo** [comment]
I downgraded the Azure Function extension to v1.6.2 as a work-around.

**Comment by alexweininger** [comment]
Until we release a fix for this issue, as dwoldo mentioned above, a valid workaround is to install the previous version of the extension.

To do this, go to the Azure Functions page in the Extensions explorer and using the dropdown on the "Uninstall" button, select "Install another version..."

<img width="610" alt="Screen Shot 2022-05-26 at 10 16 02 AM" src="https://user-images.githubusercontent.com/12476526/170540461-4e93b4b4-aad4-4500-9922-48b497ebf7fa.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/12476526/170540268-80e90d33-82e9-4aeb-a23b-b2a1847d85de.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/12476526/170540512-29e3bfb2-82f0-4e89-8f1f-87e35b777382.png">
