### ISSUE TITLE
Not able to publish the App from Visual Studio

### ISSUE THREAD

**Issue by TapanKumarBarik** [microsoft/vscode-azurefunctions#3194]
[

Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.7.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

**Comment by TapanKumarBarik** [comment]
The UI and the way we deploy the azure function seem to be changed. I am able to deploy it by clicking the function app. the old Ui, functionality was easier than this but it will be efficient

**Comment by alexweininger** [comment]
Fix has been released in version 1.7.1 of the extension.
