### ISSUE TITLE
Bug Azure Functions Mac OS

### ISSUE THREAD

**Issue by elberaguilar** [microsoft/vscode-azurefunctions#3203]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet '/Users/<user>/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.13.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/<user>/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.13.1/resources/dotnetTemplates/itemTemplates-~2.nupkg' --require '/Users/<user>/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.13.1/resources/dotnetTemplates/projectTemplates-~2.nupkg' --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name 'Functions' --arg:AzureFunctionsVersion v2" failed with exit code "6":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "AzureFunctions",
  "ResultInfo": null,
  "OutputBaseDirectory": null
}

Version: 0.13.1
OS: darwin

**Comment by alexweininger** [comment]
Could you update the Azure Functions extension to a newer version and try again? 

I've verified that this bug doesn't reproduce in the latest version (`1.7.3`).
