### ISSUE TITLE
Errors when trying to create a function in a sub folder

### ISSUE THREAD

**Issue by EnenDaveyBoy** [microsoft/vscode-azurefunctions#3204]
Does this occur consistently? Yes
Repro steps:

I am using a using multi-root workspace

In the last version of the extension, when creating a new function there was a browse button which allowed me to navigate to the scr folder in my workspace folder, this has been removed in the current version, so i looked in the settings and have added '/src' Project Subfolder setting

I then click add azure function, when i has a popup asking to initial project to work with vs code (which seems odd since thats exactly what the button is supposed to do) so i click yes, and the error Failed to find csproj file in folder "src" is displayed in the bottom right.

If i add my own csproj it on adds the Function.css file none of the other stuff

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to find csproj file in folder "src".

Version: 1.7.2
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.62.3
Language: en

<details>
<summary>Call Stack</summary>

```
DotnetInitVSCodeStep.<anonymous> extension.bundle.js:2:4227981
fulfilled extension.bundle.js:2:4226731
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by alexweininger** [comment]
Could you try removing the Project subpath setting and then try to run the Create Function command from the command palette or the Workspace title.

Workspace title:

<img width="690" alt="Screen Shot 2022-06-09 at 3 37 51 PM" src="https://user-images.githubusercontent.com/12476526/172956791-6f9bae97-3d4b-4131-83b6-98306b52c4f8.png">

**Comment by EnenDaveyBoy** [comment]
I have the same issue, I get the create Function link, but when I click it, it no longer offers the browse option so I can't create a function in the src folder, only in the root, if I change the workspace folder to the src then the vs code folder is in the wrong folder and i don't want the src to be the root.

**Comment by alexweininger** [comment]
Ok, thanks for the information.

**Comment by nturinski** [comment]
Hi @EnenDaveyBoy

I tried using the old Functions version to see the command that you were referring to. I'm not seeing the `Browse...` option here either.

![image](https://user-images.githubusercontent.com/5290572/183505357-cdd84ce6-1d2a-4c2b-ba6b-cd3cbb668add.png)
![image](https://user-images.githubusercontent.com/5290572/183505386-f1a53d55-4f09-4883-8248-5377c1cb9edf.png)
I think the command that you were using was `Create New Project...`. The button for that unfortunately isn't on the ribbon anymore, but you can use that entry point by pressing F1 and searching for `Azure Functions: Create New Project`
![image](https://user-images.githubusercontent.com/5290572/183506994-c05dc8e0-8b39-421e-947e-e3081d10e928.png)
You can see the `Browse...` option is available for this command.
![image](https://user-images.githubusercontent.com/5290572/183506384-a4bb1bff-bf3f-4287-b417-a243d5f90c28.png)

And projectSubpath seems to be working:
![image](https://user-images.githubusercontent.com/5290572/183507167-b0993ea0-d77b-45da-9f30-df8b4938878f.png)
![image](https://user-images.githubusercontent.com/5290572/183507205-70a86c3b-3dc7-48e7-8da6-ac1e4522c2a8.png)
![image](https://user-images.githubusercontent.com/5290572/183507270-ff0f0c09-07f1-4759-8790-c4fc5991e6a6.png)

Let me know if that resolves your issue!

**Comment by EnenDaveyBoy** [comment]
i am using the pallete option so alls good, but its hidden so less user friendly IMO

**Comment by nturinski** [comment]
Agreed. We are working on a way to increase the discoverability of the command, but please use this in the meantime.

**Comment by EnenDaveyBoy** [comment]
on the azure panel > workspace area > create function > then in the drop down add a browse option at present it on offers the workspace folders (multiple folder project) (its where it was before although it wasn't called the workspace area at the time)
