### ISSUE TITLE
There is no error "No matching resources found" when executing "Deploy to Function APP" command without any Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3210]
**OS:** All
**Build Version:** 20220602.3

**Repro Steps:**
1. Make sure there is no Function App in the subscription.
2. F1 -> Azure Functions: Deploy to Function App.
3. Check whether there is an error "No matching resources found" or not.

**Expect:**
There is an error "No matching resources found".
![image](https://user-images.githubusercontent.com/45614674/171608172-9bcbd658-6ece-4c85-8f94-34ddc60b03d8.png)

**Actual:**
There is no error, and it keeps in empty "select a resource" option.
![image](https://user-images.githubusercontent.com/45614674/171608345-ce503da4-5caf-44a6-ad1a-a58e640fd1cf.png)

**More Info:**
This issue also reproduces when executing other commands, such as "Add New Setting/Start Streaming Logs...".

**Comment by joshtransient** [comment]
This issue also occurs for me, on a fresh install of VSCode (v1.67.2), with fresh installs of extensions on latest versions. I do not, however, get the "no matching resource found" notification.

**Comment by v-ruizh** [comment]
This issue is no longer reproduce on resource group extension 20220807.1.
