### ISSUE TITLE
Response from service 'Microsoft.ContainerInstance' does not contain sufficient information to enforce access control policy.

### ISSUE THREAD

**Issue by ibracadabra-java** [microsoft/vscode-azurefunctions#3221]
trying Get the list of cached images on specific OS type for a subscription in a region.

I got 
{
  "error": {
    "code": "BadGateway",
    "message": "Response from service 'Microsoft.ContainerInstance' does not contain sufficient information to enforce access control policy."
  }
}

**Comment by alexweininger** [comment]
Please add repro sets
