### ISSUE TITLE
Debugging multiple Azure Functions under same solution

### ISSUE THREAD

**Issue by vpetit-reimagine** [microsoft/vscode-azurefunctions#3222]
Hi, on a project my team and I are working on, we are currently facing some issues concerning the possibility to debug multiple Azure Functions at the same time under vscode.

Currently, the project structure is like the following:
```
/ProjectName.sln
|_ /AzureFunction1
|  |_ AzureFunction1.csproj
|_ /AzureFunction1
|  |_ AzureFunction2.csproj
|_ /AzureFunction3
|  |_ AzureFunction3.csproj
|_ /CommonProject
   |_ CommonProject.csproj
```

All the Azure Functions are under the same Solution, but in different Projects. They all share some code through the CommonProject, and this is why they are required to be under the same Solution (much easier to deal with it that way).

I saw there is a workaround on the wiki that uses the « multi-root workspace » approach, but this seems quite not scalable and requires to basically recreate the same concept as the Solution.

Would it be possible to support debugging multiple Azure Functions in different projects but under the same solution ?

Kr,
V.P.

**Comment by alexweininger** [comment]
Currently the multi-root workspace approach outlined in the wiki is the best approach. We are currently limited to one Function project per workspace.

Related to https://github.com/microsoft/vscode-azurefunctions/issues/2521

**Comment by vpetit-reimagine** [comment]
Thanks for the answer. 

Hopefully, this will become a new feature later on. 

Kr,
V.P.
