### ISSUE TITLE
The function still exists under the slot after swapping it with another one for a Windows Java Function App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3224]
**OS:** Win10
**Build Version:** 20220614.1
**Regression:** Previous release

**Repro Steps:**
1. Create a Windows Java Function App with App Service Plan host plan -> Create two slots (slot1 and slot2) to it.
2. Deploy a Java project to the slot1.
3. Swap slot1 with slot2.
4. Check whether there is no function under the Functions node of the slot1 after swapping slots.

**Expect:**
There is no function under the Functions node of the slot1.

**Actual:**
The function still exists under the slot1.
![image](https://user-images.githubusercontent.com/57662131/174270850-de762e7b-7b1f-44e5-99c5-65ec6da540ad.png)

**Comment by nturinski** [comment]
Hi @v-xinda

Could you confirm that this isn't a timing issue? As in, if you wait a few minutes and refresh slot1, does that resolve the issue?

If that doesn't resolve it, could you try re-loading VS Code and see if that resolves it?

**Comment by v-xinda** [comment]
@nturinski   Verified this issue on the latest build 20220714.4, it doesn't reproduce now. So close it.
