### ISSUE TITLE
unable to create New project 

### ISSUE THREAD

**Issue by maheshreddy32825** [microsoft/vscode-azurefunctions#3226]
Does this occur consistently?  yes
Repro steps:

1. Try to create a new Function project under workspace local - on Mac
2. after selecting the folder in local --> then language( c#).
3. Then we don't see any other option to select  .NET runtime:

Version: 1.7.3
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

**Comment by alexweininger** [comment]
Just to be clear, did the select .NET runtime prompt appear, but have no available options? Or did it not appear at all?

Can you share the output of running `dotnet --list-runtimes` in your terminal?
