### ISSUE TITLE
Function detection does not work anymore after moving the repo path

### ISSUE THREAD

**Issue by Xat59** [microsoft/vscode-azurefunctions#3227]
Hi guys

I am using this extension with the version `v1.7.3`.
When I had initiated the extension, it had automatically detected my functions from the repo located in `~/mycode/` . 

Since I have moved the repo to `~/git/mycode/` , the extension does not detect functions anymore.
If I move back the repo to the `~/mycode/` path, then it detects functions back.

The extension is stuck on the `~/mycode/` to detect Local Projects. 
I've tried to configure the path but I am not able to find how to do it.

Here is what I am speaking about (path in picture is different but the explaination is the same) : 

![image](https://user-images.githubusercontent.com/1276192/175384164-8b89f029-f791-4be3-bde3-511a443b3e19.png)

Regards,

**Comment by alexweininger** [comment]
What is the value of your Azure Functions Project Subpath setting? (`azureFunctions.projectSubpath`)

<img width="800" alt="image" src="https://user-images.githubusercontent.com/12476526/175386630-bb40f1e2-d040-4a8b-bddc-c4a516437119.png">

If you have a value set, try resetting it (leaving it blank) and see if that fixes the issue. You can also try updating the setting  based on where you have moved your repo.

**Comment by Xat59** [comment]
Ok so I have tried both solutions, unsuccessfully.

## By configuring `azureFunctions.projectSubpath`

This setting was configured to a blank value. I've set it to `~/git/` but the "Local Projects" path is still stucked with the old path.

## By running the "Azure Functions: Initialize Project for Use with VS Code..."

I did it, but same result.

For both solutions, I've tried to restart my vscode app, unsuccessfully.

**Comment by nturinski** [comment]
Could you please take a screen shot of your directory and your `.vscode/.settings` file? Maybe if we see it, we can help figure out where the setting is getting stuck.

**Comment by Xat59** [comment]
What do you mean by taking a screenshot of my directory ? Which one ?

Plus, I don't have `~/.vscode/.settings` file : 

```bash
➜  ls -al ~/.vscode/
total 8
drwxr-xr-x   4 jeremydescamps  staff   128 23 jui 21:26 .
drwxr-xr-x+ 66 jeremydescamps  staff  2112 28 jui 14:28 ..
-rw-r--r--   1 jeremydescamps  staff   984 28 sep  2021 argv.json
drwxr-xr-x  28 jeremydescamps  staff   896 23 jui 11:24 extensions
```

**Comment by Xat59** [comment]
By the way, is it possible to have multiple projects in the local workspace ?
I am not able to update the project path, but also not able to add new path.

**Comment by nturinski** [comment]
Sorry, when I said `.vscode/settings.json`, I meant in your Function project workspace.  A screenshot like this would be perfect:

![image](https://user-images.githubusercontent.com/5290572/176751255-b0297c60-1ddb-4eda-a563-7b5e28faefdb.png)
![image](https://user-images.githubusercontent.com/5290572/176751392-9faebf36-eeb9-4cc1-bd5a-cefd9d5185a0.png)

You would have to add another folder to the workspace and make it multi-root.  That is currently the only way the extension can handle multiple projects.

![image](https://user-images.githubusercontent.com/5290572/176751524-20d32857-52de-4ffc-a9ab-30f01ba7ee4c.png)

**Comment by Xat59** [comment]
Ok so I can note I have several `.vscode` folders : 
- at the top of the screenshot in which I actually have `settings.json`
- a little bit lower in `BackupNetworkDevices` folder (that's where I have my 1st functions). In this folder I only have `extension.json` file.

Here's the screenshot :

![image](https://user-images.githubusercontent.com/1276192/177325489-808fa600-a31f-4b53-87a3-6652188e9c4d.png)

Here is the content of the `settings.json` that are located in my root vscode directory : 
```json
{
    "azureFunctions.deploySubpath": "path/to/BackupNetworkDevices",
    "azureFunctions.projectLanguage": "PowerShell",
    "azureFunctions.projectRuntime": "~4",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.projectSubpath": "path/to/BackupNetworkDevices",
    "azureFunctions.templateFilter": "All"
}
```

Note I have to import additional functions that are located somewhere else than `path/to/BackupNetworkDevices` .

Thanks a lot

**Comment by nturinski** [comment]
Hi @Xat59

Sorry for taking so long to get back with you.

I have been experimenting with the `projectSubpath` setting, and I'm able to nest a project over 4 folders deep with the detection logic working:

![image](https://user-images.githubusercontent.com/5290572/182260047-9c099c4d-8e63-43b7-b964-e9857cf968d1.png)

If there are no other functions projects in your workspace, maybe you could delete the `projectSubpath` and the auto-detection will work as expected? That is how it currently is working for me.

What exactly are you seeing in the Workspace view? Is there any local project node, but just the function triggers don't appear underneath the Functions node?
