### ISSUE TITLE
Error when trying to add a function to Azure Functions created in java environment.

### ISSUE THREAD

**Issue by 0907NHattori** [microsoft/vscode-azurefunctions#3228]
I created an Azure Functions in java environment with Visual Studio Code and when I tried to add a trigger, I got the following error.
-----------------------
Failed to get backup templates: ENOENT: no such file or directory, open 'c:\Users\nayu.hattori\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.6.2\resources\backupTemplates\java\~3\resources\Resources.ja-JP.json'
-----------------------

I solved the problem by changing the language setting from Japanese to English. I believe the error was probably due to a missing resource file.
Could you please correct the above?

**Comment by nturinski** [comment]
@0907NHattori

Sorry you ran into this issue. 

The error message that you are receiving means we are trying to use the backup templates. Typically, we try to retrieve the templates from the template feed, so you would only see this message if we couldn't retrieve the templates. Is it possible that you didn't have an internet connection at that time?

We do have backup templates for the English language so it makes sense that changing the language setting resolved your issue.
