### ISSUE TITLE
error while deploying a function to a existing functionapp

### ISSUE THREAD

**Issue by heyAyushh** [Microsoft/vscode-azurefunctions#323]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: {"body":"","headers":{"cache-control":"no-cache","pragma":"no-cache","expires":"-1","server":"Microsoft-IIS/10.0","x-powered-by":"ASP.NET","date":"Fri, 13 Apr 2018 10:37:00 GMT","connection":"close","content-length":"0"},"statusCode":404}

Version: 0.8.0
OS: darwin

**Comment by heyAyushh** [comment]
The function core tools was installed using brew and not npm and maybe that's it raised this error.

**Comment by heyAyushh** [comment]
initialising that function folder with the vscode function app extension it raised an error 

{"body":"","headers":{"server":"Kestrel","x-powered-by":"ASP.NET","date":"Fri, 13 Apr 2018 10:53:18 GMT","connection":"close","content-length":"0"},"statusCode":404}

**Comment by EricJizbaMSFT** [comment]
A few questions:
1. What type of functions were you deploying when this happened? Http, Timer, Blob, etc.?
1. Can you describe what you mean by "changing the remote function version to beta". What exactly did you change and how did you change it?
1. Is this a new function app? If not, have you successfully deployed to this function app before?

**Comment by heyAyushh** [comment]
i am as I tried deploying today and It worked. 
PS. idk how.
