### ISSUE TITLE
Functions - Java 17 Support

### ISSUE THREAD

**Issue by apawast** [microsoft/vscode-azurefunctions#3245]
- Functions runtime V3
- OS (Linux and Windows) all hosting plans

We are releasing Java 17 for preview this semester. Users need to be able to create Functions and select "Java 17 (preview)" in VSCode. 

Configuration: set `javaVersion` to `17` for Windows and `LinuxFxVersion` to ` java|17 ` for Linux

**Comment by akaroml** [comment]
@Flanker32 please help send a PR to enable Java 17 runtime.

**Comment by Flanker32** [comment]
@apawast Thanks for your message, currently vscode leverage [Get Function App Stacks](https://docs.microsoft.com/en-us/rest/api/appservice/provider/get-function-app-stacks) API to get the Java runtimes, [here](https://github.com/microsoft/vscode-azurefunctions/blob/main/src/commands/createFunctionApp/stacks/getStackPicks.ts#L112-L139) is the related codes, once the API is updated, java 17 could be shown and create in VSCode extensions.

**Comment by fiveisprime** [comment]
@Flanker32 has the stacks API been updated for this yet?

**Comment by MadhuraBharadwaj-MSFT** [comment]
@fiveisprime @Flanker32 

Currently Java 17 (preview) is updated on StacksAPI with the isHidden flag set to true. https://github.com/Azure/azure-functions-ux/pull/6729.

The final PR with isHidden=false has been merged and will be available for customers to use by September 16: https://github.com/Azure/azure-functions-ux/pull/6855.

Could you please ensure VSCode supports Java 17 (preview) for Azure Functions Runtime v4?

cc @amamounelsayed @apawast @shreyas-gopalakrishna @kaibocai

**Comment by alexweininger** [comment]
To test a hidden stack, enable to “Azure Functions: Show Hidden Stacks” setting in VS Code.
 
![image](https://user-images.githubusercontent.com/12476526/187802280-185d7721-61d6-42ac-8eac-7354cfe22a30.png)
 
With this setting enabled, “Java 17 (Preview)” appears.
 
![image](https://user-images.githubusercontent.com/12476526/187802272-00531b9e-da07-4356-9712-9c41a9c1ace6.png)
