### ISSUE TITLE
Update templates for dynamic concurrency

### ISSUE THREAD

**Issue by cachai2** [microsoft/vscode-azurefunctions#3248]
Dynamic concurrency is a performance feature that went GA for functions end of May.

We want to enable the feature by default for new apps, and it requires updating host.json settings for the app.

**Comment by nturinski** [comment]
Hi @cachai2

I created a Function App through the Portal and looking at the `host.json`, I'm not seeing the setting that you're referring to.

![image](https://user-images.githubusercontent.com/5290572/183185342-d5ec94a8-617d-40a7-be7e-657432ae6017.png)

According to this [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-concurrency), the default is to have dynamic concurrency disabled.

> By default, dynamic concurrency is disabled. With dynamic concurrency enabled, concurrency starts at 1 for each function, and is adjusted up to an optimal value, which is determined by the host.

Furthermore, it only seems like dynamic concurrency is supported for Azure Blob, Azure Queue, and Service Bus triggers so I'm not sure that it is something that we should turn on by default for all users.

**Comment by cachai2** [comment]
Hi @nturinski,

Currently, the default is to have dynamic concurrency disabled for Function apps on create. However, the Functions team is trying to get more usage of the feature as it will help simplify concurrency settings for customers in order to get performance improvements.

The portal creates an empty Function app by default. This experience can/should be mimicked in VS Code. However, when creating a non-empty app with Azure Blob, Azure Queue, and Service Bus Triggers, we want the template generated to default the settings for dynamic concurrency in host.json.
