### ISSUE TITLE
Cannot edit in read-only editor

### ISSUE THREAD

**Issue by CuetoA** [microsoft/vscode-azurefunctions#3249]
Does this occur consistently? Yes
Repro steps:
I am using ubuntu 22.04 LTS, I installed Visual Studio Code, then I installed the extension of Azure Tools, sing into my account, and started using it. When trying to write in a file it says "Cannot edit in read-only editor" then I checked the documentation and followed [this page](https://docs.microsoft.com/es-mx/azure/azure-functions/functions-run-local?tabs=v4%2Clinux%2Cpython%2Cportal%2Cbash#install-the-azure-functions-core-tools) no matter what I do it keeps saying the same and I cannot create or modify anything locally.

Version: 1.7.4
OS: linux
OS Release: 5.15.0-41-generic
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

**Comment by nturinski** [comment]
Hi @CuetoA, sorry that you're running into this issue.

Which file are you trying to edit? if you are trying to edit a function trigger remotely, some of them are marked as Read-only.
![image](https://user-images.githubusercontent.com/5290572/180325550-0d477f47-f80f-4ba2-812d-eff9872cbda9.png)

Could I see a screenshot of your editor? Or could you provide more detailed reproduction steps?
