### ISSUE TITLE
Show "No templates found" in the list if setting the  "Azure Functions: Template Source" setting with "Staging" when creating a .NET 6.0 LTS project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3250]
**OS:** All
**Build Version:** 20220715.7

**Repro Steps:**
1. Set the "Azure Functions: Template Source" setting with "Staging".
2. F1 -> Click "Azure Functions: Create New Project..." -> Select a folder -> Select C# -> Select .NET 6.0 LTS.
3. Check whether there are many templates in the list.

**Expect:**
There are many templates in the list.
![image](https://user-images.githubusercontent.com/57662131/179478806-7dfafe7e-9dd5-4841-9e1c-f042e1bc9b85.png)

**Actual:**
Show "No templates found" in the list.
![image](https://user-images.githubusercontent.com/57662131/179479310-4dc8dd12-da6d-4a06-afa6-144974e71166.png)

**More Info:**

1. An error occurs after selecting "Skip for now" to create project.
![image](https://user-images.githubusercontent.com/57662131/179479624-ddd20a48-e4f0-4af7-a888-96684a6a6c8e.png)
2. This issue doesn't reproduce for other .NET runtimes.
3. This issue doesn't reproduce when setting the "Azure Functions: Template Source" setting with "Default"

**Comment by ejizba** [comment]
@nturinski I tried these steps and couldn't reproduce. Hopefully it's not a real issue because they're in the process of moving these templates out of prerelease this afternoon: https://github.com/Azure/azure-functions-tooling-feed/pull/369

**Comment by nturinski** [comment]
@v-xinda I also can't reproduce this issue.  Could you try this again with either the current release version or the current main build?

**Comment by v-xinda** [comment]
@nturinski  Verified this issue with the current release version and the latest main build, and set the "Azure Functions: Template Source" setting with "Default" or "Staging". It doesn't reproduce, so close it.
