### ISSUE TITLE
"Create new Function app in Azure" replaces dashes with ''

### ISSUE THREAD

**Issue by enriqueayala** [microsoft/vscode-azurefunctions#3252]
I need to follow an Azure policy naming convention which requires dashes under name. Steps to reproduce: 

1. Follow getting started https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp
2. Select " Create Function App in Azure option."
3. Enter a globally unique name for the function app: `some-example-with-dashes`
4. Name is formatted to : `someexamplewithdashes`

**Comment by nturinski** [comment]
Hi @enriqueayala 

I'm unable to reproduce this.  See below; I have created many Function Apps using dashes.
![image](https://user-images.githubusercontent.com/5290572/180323694-85c8b852-a102-41ac-87a8-4690a4f945e9.png)

Could you provide me more detailed information about how you are encountering this issue?

I noticed that the storage account name removes all the dashes though.
