### ISSUE TITLE
Linux Consumption Python blob trigger doesnt work in US Gov Virginia

### ISSUE THREAD

**Issue by yeahsicy** [microsoft/vscode-azurefunctions#3256]
Functions Language: Python
SKU Mode: Consumption(Dynamic)
Functions Platform: (Linux)
Bindings\Triggers: Blob Trigger
Deployment method: VS code
Region: US Gov Virginia

Repro steps: 
1. create a Python Linux Consumption function app in Gov cloud usgovvirginia.
2. add / deploy a blob trigger via VS code.

Expected behavior: 
The function works without issues. 

Actual behavior: 
- you would see the function under Functions tab but it's with a banner "Runtime is unreachable"; 
- the blob trigger wouldnt work.

Workaround: 
- Use Elastic premium plan instead; 
- Or deploy from another client, such as Azure CLI.

**Comment by yeahsicy** [comment]
The issue seemed related to VS code as other deployment tools work. 

Thanks,
@yeahsicy

**Comment by nturinski** [comment]
Hi @yeahsicy

When do you see the error "Runtime is unreachable"? 

Is that happening when you deploy or is it happening when you expand the `Functions` node on the tree view?

Is the elastic premium plan also in the US Gov Virginia Azure Cloud?

**Comment by yeahsicy** [comment]
> Hi @yeahsicy
> 
> When do you see the error "Runtime is unreachable"?
> 
> Is that happening when you deploy or is it happening when you expand the `Functions` node on the tree view? If it happens here, does it take about 2 minutes for the error to appear?
> 
> Is the elastic premium plan also in the US Gov Virginia Azure Cloud?

Hi @nturinski , the issue is still happening - you would see it when going to the app > Functions blade in Azure portal, after the deployment was successful. It appeared constantly and didnt take a period of time to pop up. 

Yes, using Elastic premium plan doesnt have this problem in the US Gov Virginia.

**Comment by nturinski** [comment]
> Hi @nturinski , the issue is still happening - you would see it when going to the app > Functions blade in Azure portal, after the deployment was successful. It appeared constantly and didnt take a period of time to pop up.

Sorry, could you clarify then that the error "Runtime is unreachable" is showing up in the Portal, not the VS Code extension? But you are deploying from VS Code?

And if you deploy with another deployment tool, then the Functions are available to view in the Azure Portal? Are you able to view them in the VS Code extension?

**Comment by yeahsicy** [comment]
> Sorry, could you clarify then that the error "Runtime is unreachable" is showing up in the Portal, not the VS Code extension? But you are deploying from VS Code?

Yes, correct. 

> And if you deploy with another deployment tool, then the Functions are available to view in the Azure Portal? 

Yes, and the functions work fine without "Runtime is unreachable" error. Just to clarify, deploying from VS Code would also make the functions available to view via portal, but they wouldnt work as expected with "Runtime is unreachable" error. 

> Are you able to view them in the VS Code extension?

Didnt try and not very sure about the question.

**Comment by yeahsicy** [comment]
the issue was addressed by https://github.com/Azure/azure-functions-host/issues/8788
