### ISSUE TITLE
`conda` environment support when debugging

### ISSUE THREAD

**Issue by YaroslavKormushyn** [microsoft/vscode-azurefunctions#3263]
Hello!

I have an Azure Function in Python using a conda environment.
Unfortunately, the environment doesn't get activated when running the run/debug task. I've tried adding the activation to the run task, but in that way the debugger doesn't attach to the process:

![image](https://user-images.githubusercontent.com/11539004/181480803-19df97c3-c9a6-4a52-924a-910685955622.png)

<details>

<summary>
My `launch.json`:
</summary>

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9091,
            "preLaunchTask": "run"
        }
    ]
}
```
</details>

<details>
<summary>
My `tasks.json`:
</summary>

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "run",
			"type": "shell",
			"command": "conda activate ifcconverter && func host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true
		}
	]
}
```

</details>
<details>
<summary>
My `settings.json`:
</summary>

```json
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.scmDoBuildDuringDeployment": true,
    // "azureFunctions.pythonVenv": ".venv",
    "azureFunctions.createPythonVenv": false,
    "azureFunctions.projectLanguage": "Python",
    "azureFunctions.projectRuntime": "~4",
    "debug.internalConsoleOptions": "neverOpen"
}
```
</details>

When using the venv the venv gets activated automatically on run (I guess this is from the `azureFunctions.pythonVenv` setting.
1. How can I get the environment to activate on run automatically?
2. Why doesn't the debugger attach to the running process? The run task starts fine, it's the debugger that cannot connect.

**Comment by YaroslavKormushyn** [comment]
For anyone interested, I've managed to set up a workaround. If you want to use your conda environment to run local python Azure Functions:
1. See my `settings.json` setup above and copy
2. See my `tasks.json` setup above and set the task `run` command to `conda activate <your env name here>; func host start --port 7071 --language-worker -- '-m ptvsd --host 127.0.0.1 --port 9091'`

I have set powershell as the default shell in `terminal.integrated.shell.windows` in my workspace.
Make sure you have the `ptvsd` module in your environment.

Seems like the reason is the custom behind-the-scenes logic when running the `func: host start` built-in task. It must start with the language worker implicitly, otherwise, I don't understand what's the difference.

**Comment by nturinski** [comment]
Hi @YaroslavKormushyn 

Thanks for filing this issue.  The workaround here seems pretty reasonable as this seems like more specialized custom setup.

For now, if anybody else runs into this issue, we'll direct them to this workaround since it seems pretty straightforward.
