### ISSUE TITLE
View properties doesn't display site config

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#3264]
Does this occur consistently? Yeah
Repro steps:
1. Right click on a function app
2. View properties

### Expected

It'll show a ton of properties from the site config. This used to work (https://github.com/microsoft/vscode-azurefunctions/pull/2164) and I'm guessing it broke with the new unified view

### Actual

This is what it displays:
```
{
    "id": "/subscriptions/...",
    "name": "...",
    "type": "Microsoft.Web/sites",
    "kind": "functionapp",
    "location": "centraluseuap",
    "tags": {}
}
```
Which unfortunately does not have very much information at all. 

Version: 1.7.4
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by nturinski** [comment]
Yep, you are correct.  The data doesn't get set when the func app loads, it got set when `viewProperties` is called in the Functions extension.  But since it's using RG's `viewProperties` command, it just has the old, basic data.

Sorry about that 🙇🏻🦖
