### ISSUE TITLE
Make it easier to create a brand new project from the workspace UI

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#3265]
I find that with the new unified view, it's much more difficult to create a new functions project. Here are two things that I think could help

# Make the button more visible

![Screen Shot 2022-07-28 at 4 48 13 PM](https://user-images.githubusercontent.com/11282622/181656268-a1612530-ca83-425f-bcc2-97c75b1e249f.png)

Can we move "Create function" out of the submenu and into a top-level button on the workspace view? I was a big fan of the lightning bolt button because I thought it was very recognizable as Functions. I think putting the action in a submenu is less discoverable and more annoying because it requires an extra click. If a user has the Functions extension installed, I think it's fair to assume they will use this action and it deserves a top-level button.

# Reduce the number of prompts

If I'm starting without a project I get one of these prompts when I do "Create function" based on if I have a folder open:

![Screen Shot 2022-07-28 at 4 47 55 PM](https://user-images.githubusercontent.com/11282622/181656288-bd066d0d-b659-4fd0-b949-a6a7ec179e40.png)![Screen Shot 2022-07-28 at 4 50 14 PM](https://user-images.githubusercontent.com/11282622/181656294-4b90fbae-1824-44d5-9766-fab4fd39f1e3.png)

This is pretty much the quintessential "new user" getting started experience, and I don't think immediately showing them a warning is a good look. Can we either
1. Add the explicit "Create new project" button back to the UI (Right now it's possible in the command palette, but I feel like plenty of people never use the command palette)
2. Keep it to just one button, but add some auto-magic functionality that skips the above prompts and just goes right into the 'create project' wizard if it doesn't think you have a project already. I'm pretty sure SWA already does something like this.

Note: The other problem with the first warning shown above is it doesn't let me pick a new folder to create a project in - aka it forces me to create the project in my open folder which may already have stuff.

**Comment by nturinski** [comment]
We have something in the works...
![SpongebobSpongebobSquarepantsGIF](https://user-images.githubusercontent.com/5290572/181671886-dd0a7058-3c5c-4668-a16b-f45b8f963ba5.gif)

**Comment by alexweininger** [comment]
Related to https://github.com/microsoft/vscode-azureresourcegroups/issues/316

**Comment by nturinski** [comment]
> Keep it to just one button, but add some auto-magic functionality that skips the above prompts and just goes right into the 'create project' wizard if it doesn't think you have a project already. I'm pretty sure SWA already does something like this.

Will implement this until we are ready to migrate buttons lost to time.
