### ISSUE TITLE
Cant see functions app

### ISSUE THREAD

**Issue by Charizard13** [microsoft/vscode-azurefunctions#3270]
Does this occur consistently? Yes
Repro steps:

1.Cant find my function app name
2.

Version: 1.7.4
OS: win32
OS Release: 10.0.22622
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by nturinski** [comment]
Can you give more information to repro this? What type of Azure Account are you using? Could I see a screenshot of your Azure view?
