### ISSUE TITLE
Fallback to default language if current language pack is not available in backup templates

### ISSUE THREAD

**Issue by impepc** [microsoft/vscode-azurefunctions#3279]
For create function from functions template, but I got follow message, and failed.

it appears pop up with 'Failed to get latest templates: CloseBraceExpected near line "328", column "4"'
and output of Azure Functions is below

> 9:01:50: Failed to get latest templates: Retrieving templates timed out. Modify setting "azureFunctions.requestTimeout" if you want to extend the timeout.
> 9:01:50: Failed to get backup templates: ENOENT: no such file or directory, open '/Users/billy_k/.vscode/extensions/ms-azuretools.vscode-azurefunctions-1.7.4/resources/backupTemplates/java/~4/resources/Resources.ja-JP.json'
> 9:01:50: Error: Failed to get latest templates: Retrieving templates timed out. Modify setting "azureFunctions.requestTimeout" if you want to extend the timeout.

### Steps.
0. (install Japanese Language Pack for VisualStudio Code(ms-ceintl.vscode-language-pack-ja))
1. create workspace from workspace menu of azure functions 
2. select "Create Function" from add button of workspace menu

### Temporary Measure
Uninstall language pack, and restart VSCode

### Versions
VSCode: 1.70.0
Azure Functions Extension: 1.7.4

**Comment by nturinski** [comment]
Seems to be related to https://github.com/microsoft/vscode-azurefunctions/issues/3228

Considering both are trying to load (and failing) the backup templates, I'm assuming that the logic for getting the Japanese templates from the feed isn't working

**Comment by nturinski** [comment]
@Flanker32 Do you know if we are getting other language packs for the Java templates?

**Comment by impepc** [comment]
Oh, sorry for i didn't check #3228 .

for any help.

/Users/billy_k/.vscode/extensions/ms-azuretools.vscode-azurefunctions-1.7.4/resources/backupTemplates/java/~4/resources
-> Resources.json only

/Users/billy_k/.vscode/extensions/ms-azuretools.vscode-azurefunctions-1.7.4/resources/backupTemplates/script/~4/resources
-> Resources.json and much language json files


and, I tried with Chinese language pack, and seemsly same
<img width="713" alt="image" src="https://user-images.githubusercontent.com/10953621/183571203-7a748174-9b66-4e3f-8515-b49d31dee18e.png">

**Comment by Flanker32** [comment]
> @Flanker32 Do you know if we are getting other language packs for the Java templates?

@nturinski Thanks for your message and sorry for the late response, sorry I don't know whether we have templates for other language. @amamounelsayed Do you have any input for this issue?

@nturinski It seems that we do only have one [backup template](https://github.com/microsoft/vscode-azurefunctions/tree/main/resources/backupTemplates/java/~4/resources) for java, so can we fallback to the default once if target language is missing?
