### ISSUE TITLE
Add Function functionality is missing in Azure functions extension of VS Code

### ISSUE THREAD

**Issue by SwethaKandikonda-MT** [microsoft/vscode-azurefunctions#3280]
This is from the StackOverflow user and after reproducing from our end we faced the same issue after installing the latest update.
https://stackoverflow.com/questions/73271028/not-able-to-add-new-azure-function-in-vscode

**Steps:**
1. Install/Update the latest VS Code release [July 2022 (version 1.70)](https://code.visualstudio.com/updates/v1_70).
2. Navigate to Azure Extension.
3. Hover to Workspace.

We cannot able find the Add new function (+ icon) after installing or updating to the latest July 2022 (version 1.70) in VS Code.

![5L9KBKX 1](https://user-images.githubusercontent.com/85123660/183400520-4e7bee6e-9730-4112-b4c2-7b69a9188097.png)

**Comment by nturinski** [comment]
Hi @SwethaKandikonda-MT 

Thanks for filing this issue. We have the same issue filed here: https://github.com/microsoft/vscode-azureresourcegroups/issues/330

Unfortunately, the only current workarounds is to downgrade VS Code or uninstall either the Azure App Service or Functions extension as having both is what is causing this issue.

**Comment by coopmal** [comment]
Having the same issue on my side, uninstalling Azure App Service did the trick as work around for now.
It's acceptable since I don't need that now but I hope they can fix this bug soon and release an general update for vscode.

**Comment by alexweininger** [comment]
Fixed in https://github.com/microsoft/vscode/releases/tag/1.70.2
