### ISSUE TITLE
azureFunctions.projectSubpath not honored

### ISSUE THREAD

**Issue by Jonatan-V** [microsoft/vscode-azurefunctions#3286]
Hi
I have a project containing a js function app and some other stuff. To make the repo easier to navigate i want to move the function app to /src folder. To make debugging and launching the the function app work from the root of the project i followed option one in the [wiki](https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects). However "func start" is not able to find the function app and just errors with Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.
Leaving the func app in the root of the project and changing the path for azureFunctions.projectSubpath doesnt make any difference either, func start is able to launch no matter what i set the projectSubpath to so it seems the property is not honored.

**Comment by Jonatan-V** [comment]
btw it seems this [wiki](https://github.com/microsoft/vscode-azurefunctions/wiki/Project-Structure) is outdated and doesnt contain all the supported settings.

**Comment by nturinski** [comment]
Hi @Jonatan-V

Sorry you're running into this problem.  Could I see the error output that you are getting when you try to debug as well as your `settings.json` for this project? This will make it a lot easier for me to help debug the issue.

**Comment by Jonatan-V** [comment]
Hi @nturinski 
Thanks for reaching out
Sure thing
Starting debugging actually fails with error "Could not find task 'func: host start'"
Looking at tasks.json it seems i have it though.
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-node-watch",
      "isBackground": true,
      "dependsOn": "npm install (functions)"
    },
    {
      "type": "shell",
      "label": "npm install (functions)",
      "command": "npm install"
    },
    {
      "type": "shell",
      "label": "npm prune (functions)",
      "command": "npm prune --production",
      "problemMatcher": []
    }
  ]
}
```

And here is settings.json
```
{
  "azureFunctions.projectSubpath": "src",
  "azureFunctions.deploySubpath": "src",
  "azureFunctions.postDeployTask": "npm install (functions)",
  "azureFunctions.projectLanguage": "JavaScript",
  "azureFunctions.projectRuntime": "~4",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "npm prune (functions)",
  "azureFunctions.templateFilter": "All",
  "jest.autoRun": "off"
}
```

**Comment by nturinski** [comment]
Hi @Jonatan-V, thanks for getting back to me!

Okay, I think I see the issue here. The `tasks.json` is still pointed towards the root of the project, but it needs to be running `func host start` from `src`.  If you set up the task like so:

```
{
	"type": "func",
	"command": "host start",
	"problemMatcher": "$func-node-watch",
	"isBackground": true,
	"options": {
	"cwd": "${workspaceFolder}/src"
}
```

It should work. Alternatively, if you press F1, you can run the command `Azure Functions: Initialize Project for Use with VS Code` and it should respect your settings and re-create your `task.json` for you!

Hope that helps.

![image](https://user-images.githubusercontent.com/5290572/185682461-eab5eff9-287a-407f-8aed-a05df3e5ba7b.png)

**Comment by Jonatan-V** [comment]
Hello again
Thanks! That solved the debugging issue. However im still not able to run "func start" from the root of the project, it just fails with Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.

**Comment by nturinski** [comment]
If you're running `func start` from the terminal, it won't be able to use the VS Code configurations that we set.  If you want to only run `func start` from your project root, could you try `func start --script-root src`

**Comment by Jonatan-V** [comment]
Aha understood. Thanks that works.
