### ISSUE TITLE
Clarify the specific file that need to change for these settings

### ISSUE THREAD

**Issue by cicorias** [microsoft/vscode-azurefunctions#3289]
can the wiki page be updated to be more specific as to which "files" these modifications go?

https://github.com/microsoft/vscode-azurefunctions/wiki/Remote-Debug-Java-functions

eg. "settings.json", "local.settings.json" ?

**Comment by Flanker32** [comment]
@cicorias Thanks for your feedback and sorry for the confuse. When you start remote debugging for Java Azure Functions in VSCode, we will update the configuration of your remote FunctionApp (will not modify your local files), which includes
- Set `use32BitWorkerProcess` to `false`
- Set `webSocketsEnabled ` to `true`
- Update related application settings
  - Set `JAVA_OPTS` to `-Djava.net.preferIPv4Stack=true -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=127.0.0.1:8898`
  - Set `HTTP_PLATFORM_DEBUG_PORT` to `8898`

**Comment by nturinski** [comment]
I changed the wording on the Wiki page to explicitly explain that the changes are automatic and nothing is required from the user.
