### ISSUE TITLE
Create your first serverless app - Step 2 No longer available?

### ISSUE THREAD

**Issue by iheartmedia-matt** [microsoft/vscode-azurefunctions#3291]
Using Azure Functions v1.7.4 and Visual Studio Code v1.70.2, I'm no longer prompted or able to do Step 2 in the Create your first serverless app (https://github.com/Microsoft/vscode-azurefunctions):

"2. Select a new, empty folder to contain your project"

Was this option removed and no longer part of the Create your first serverless app creation process?

I'd like to be able to select a folder to create the Function App, thanks!

**Comment by Wahzammo** [comment]
I had issues with this step also

**Comment by alexweininger** [comment]
If VS Code already has a workspace folder opened, this step will be skipped automatically. Were you able to successfully create a Functions Project?

**Comment by iheartmedia-matt** [comment]
I was able to successfully create a Functions Project, thanks!

Previously, I did have a workspace folder opened to the root of my project directory and wanted to create a new Functions Project in a sub-directory of my root.

Thanks again for the clarification on when the prompt for selecting a folder will appear!
