### ISSUE TITLE
There is no web page opening when clicking "Learn more" button

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3294]
**OS:** Ubuntu 22.04
**Build Version:** 20220819.8
**VS Code Version-insiders:** 1.71.0-insider

**Repro Steps:**
1. Create and open a function project.
2. Debug this project.
3. Click the "Learn more" button in the prompt dialog.
![image](https://user-images.githubusercontent.com/45614674/186145289-effcf1bf-4129-4fc3-9627-a124c24b9a10.png)
5. Check whether there is a web page opening.

**Expect:**
There is a web page opening.

**Actual:**
There is no web page opening.

**More Info:**
Executing "Azure Functions: Install or Update Azure Functions Core Tools" command, click "these instructions" link, there is a web page opening.
![image](https://user-images.githubusercontent.com/45614674/186145160-e314a534-eb0d-4420-bc2f-54897a9fb022.png)

**Comment by philliphoff** [comment]
I can repro this with the alpha Functions extension on VS Code Insiders 1.71, but not on VS Code 1.70 (Released) or VS Code 1.69 (Released). Perhaps an issue with the Insiders release?

**Comment by alexweininger** [comment]
> I can repro this with the alpha Functions extension on VS Code Insiders 1.71, but not on VS Code 1.70 (Released) or VS Code 1.69 (Released). Perhaps an issue with the Insiders release?

@philliphoff were you also testing on Ubuntu 22.04?

**Comment by philliphoff** [comment]
Yes, 22.04.

**Comment by philliphoff** [comment]
Also, I see the same behavior with the latest released version of the extension, so it's not related to any changes in the alpha version.

**Comment by nturinski** [comment]
@v-ruizh Could you please verify that this is still producing on current VS Code Stable & VS Code Insiders after updating? This definitely seems like something is wrong with their `openUrl` command for Ubuntu 22.04.

**Comment by v-ruizh** [comment]
Verified this issue on current VS Code Stable 1.71.2 and VS Code Insiders 1.72.0 with the latest Function extension 20220922.1 installed, this issue has fixed, close it.
