### ISSUE TITLE
Cannot release function unless local settings points at a live resource

### ISSUE THREAD

**Issue by SaksunBindy** [microsoft/vscode-azurefunctions#3298]
We're trying to release a queue-triggered function in Azure 

The local.settings.json file needs to have an AzureWebJobStorage connection string which is a live resource (instead of the recommended "UseDevelopmentStorage=true;") for the release to work.

If the AzureWebJobsStorage connection string is "UseDevelopmentStorage=true;", the function deployment attempts to connect to a local resource, even though this value is overridden in the function app's config in the portal. This leads to an error 
```Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (An attempt was made to access a socket in a way forbidden by its access permissions. (127.0.0.1:10001))```

Curiously, if the AzureWebJobStorage is updated to point at a storage account, the release will succeed and the AzureWebJobStorage value from the portal configuration will be used thereafter.

Relates to [this](https://github.com/microsoft/vscode-azurefunctions/issues/1523)

**Comment by nturinski** [comment]
We should probably not set the `AzureWebJobsStorage` app setting if we detect that is either `"UseDevelopmentStorage=true;"` or `""`

**Comment by nturinski** [comment]
Hi @SaksunBindy 

Quick question: is uploading your `local.settings.json` part of your workflow when you release? I believe that is the only time the `AzureWebJobsStorage` setting would be overwritten.
