### ISSUE TITLE
There is no response when executing "Start Streaming Logs" action for a Linux Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3299]
**OS:** Ubuntu 22.04
**Build Version:** 20220819.8

**Repro Steps:**
1. Create a Linux Function App.
2. Right click this Linux Function App and execute "Start Streaming Logs" action.
3. Check whether it opens the live metrics stream in the portal or not.

**Expect:**
It opens the live metrics stream in the portal.

**Actual:**
There is no response when executing "Start Streaming Logs" action.

**More Info:**
1. This issue does not reproduce for a Windows Function App.
2. This issue does not reproduce on Windows OS.

**Comment by philliphoff** [comment]
I'm seeing similar behavior as with #3294, where it works with the existing Functions extension with VS Code but not with VS Code Insiders, and on Ubuntu but not Windows.  I'm going to say it's likely the same underlying issue.

**Comment by v-ruizh** [comment]
Verified this issue on current VS Code Stable 1.71.2 and VS Code Insiders 1.72.0 with the latest Function extension 20220922.1 installed, this issue has fixed, close it.
