### ISSUE TITLE
DotnetTemplateProvider.getLatestTemplates causes "options object is required" in Azure Logic Apps (Standard) vscode extension

### ISSUE THREAD

**Issue by TonnyWildeman** [microsoft/vscode-azurefunctions#3302]
see https://github.com/Azure/logicapps/issues/608#issuecomment-1231780096 for a bit more info.

The latest template version retrieved was 3.41.0 from the production Azure cli templates feed. https://functionscdn.azureedge.net/public/cli-feed-v4.json

**Comment by alexweininger** [comment]
@ccastrotrejo I think this is a Logic Apps only issue. Since it's already tracked in https://github.com/Azure/logicapps/issues/608, I will go ahead and close this.
