### ISSUE TITLE
Allow creating a function app with Linux

### ISSUE THREAD

**Issue by hanhossain** [microsoft/vscode-azurefunctions#3321]
Creating a function app with a custom handler (following the [custom handler tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other?tabs=rust)) by default sets the OS as windows (therefore the tutorial above fails). It would be nice if the flow had a step where we could choose the runtime OS for the azure function.

**Comment by nturinski** [comment]
Hi @hanhossain

We purposely pick defaults for create to not inundate new users with a bunch of prompts that they probably don't know what they need.  However, for cases where you do need to set the OS, you can use the advanced create which offers more flexibility to the create experience.

You can find it by either right-clicking the `Functions` tree item:
![image](https://user-images.githubusercontent.com/5290572/189237173-2638f3a7-100f-4802-ba20-403290ba1111.png)
 
Or by using the command palette (F1):
![image](https://user-images.githubusercontent.com/5290572/189237036-82924c73-931d-4702-b992-b91dcf4ac382.png)

Please let me know if that resolves your issue.

**Comment by hanhossain** [comment]
That makes sense. I never knew about the advanced create so this resolves my issue, thanks!

**Comment by nturinski** [comment]
Sorry that it's not in a very obvious location. We are working on resolving that in the future!

Thanks for using the extension :) I'll go ahead and close this issue then.
