### ISSUE TITLE
An error occurs when executing "Connect to a GitHub Repository..." command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3325]
**OS:** All
**Build Version:** 20220906.4

**Repro Steps:**
1. F1 -> Azure Functions: Connect to a GitHub Repository... -> Select a Function App.
2. Check whether the next step is "Choose organization" or not.

**Expect:**
The next step is "Choose organization".

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/189150823-d0d6a9ad-6293-4777-987d-f3e9f0efb407.png)

**More Info:**
This issue does not reproduce when executing the action from Function App Deployments node.

**Comment by philliphoff** [comment]
Reproduced on existing 1.7.4 release, so not specific to the 1.8.0 version under test.  Looking at the `connectToGitHub()` command handler, if no slot tree item was selected when invoked (e.g. via the command palette), it is *supposed* to prompt the user to pick one.  However, the picker actually only prompts for the function app (and not deeper), which causes the execution logic to fail.
