### ISSUE TITLE
An error occurs when executing "Disconnect from Repo" command from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3326]
**OS:** All
**Build Version:** 20220906.4

**Repro Steps:**
1. F1 -> Azure Functions: Disconnect from Repo... -> Select a Function App which has connected to a GitHub repository -> Select Deployments node.
2. Check whether a confirmation dialog pops up or not.

**Expect:**
A confirmation dialog pops up.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/189156242-90be0322-f307-47f0-a3d9-f360f275e2e4.png)
 
**More Info:**
This issue does not reproduce when executing this action for Deployments node in Azure view.

**Comment by philliphoff** [comment]
Verified in current 1.7.4 release, so not specific to 1.8.0 version under test.  Looking at the `disconnectRepo()` command handler, if no node was selected (e.g. being invoked from the command palette), the user should be prompted to select a deployment node.  The picker, however, seems to fail after the Deployments node is chosen, despite there being sub-nodes available.

**Comment by MicroFish91** [comment]
So I found the way to get rid of this error would be to convert the `expectedContextValue` to a `RegExp`.

Problem is that if we leave the command code as-is, we end up always selecting the top level `DeploymentsTreeItem` and give no chance for the user to select any number of nested deployment nodes under the `SlotsTreeItem`.  I'm not sure/please let me know if you can think of any elegant way to handle a situation like this using the current `pickAppResource` or `showTreeItemPicker` implementations.

I was originally going to try refactoring the code to match my other [PR](https://github.com/microsoft/vscode-azurefunctions/pull/3320) that ran into a similar issue, however, it doesn't really make as much sense/work in the same context here... is this something that would be better solved when v2 of tree picker is released?  Better yet does the current v2 of the tree picker allow for an elegant way to handle something like this?  @bwateratmsft @alexweininger

**Comment by philliphoff** [comment]
Given it's only an issue when invoked via the command palette, and with the assumption that that's a far less common scenario, I'd be fine deferring a fix until the RG V2 API is in, where we can use its new picker logic and see if we have the same problem.

**Comment by MicroFish91** [comment]
Based on discussion with Nathan, we don't need to search past the `SlotsTreeItem` for `command palette` so the fix is much easier now, PR shown above.
