### ISSUE TITLE
[Suggestion] Remove "+ Create new App Setting…" from list when executing "Edit/Rename Setting…" command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3340]
**OS:** All
**Build Version:** 20220919.3

**Repro Steps:**

1. F1->Azure Functions: Edit Setting.../Azure Functions: Rename Setting... -> Select a function app.
2. Check the "Select App Setting" list.

**Actual:**
"+ Create new App Setting..." command shows in the "Select App Setting" list.
![image](https://user-images.githubusercontent.com/45614674/191006173-e3bb15b6-38e9-4e37-b872-aa5f195b1263.png)

**Suggestion:**
Remove "+ Create new App Setting..." command from the "Select App Setting" list when executing "Edit/Rename Setting…" command.

**Comment by alexweininger** [comment]
Good suggestion, but we'll leave it for now since it's not hurting anything
