### ISSUE TITLE
Auto-Args to main in Azure function App are not generated at new bindings

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode-azurefunctions#3342]
Routed from: https://github.com/Azure/azure-functions-python-library/issues/60

**Comment by nturinski** [comment]
According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-add-output-binding-storage-queue-vs-code?pivots=programming-language-python&tabs=in-process), we don't support auto-args. I'm not sure that we ever did, so I think that the documentation may have been incorrect.

From the documentation: 

> After the binding is defined, you can use the name of the binding to access it as an attribute in the function signature. By using an output binding, you don't have to use the Azure Storage SDK code for authentication, getting a queue reference, or writing data. The Functions runtime and queue output binding do those tasks for you.
>
> Update HttpExample\__init__.py to match the following code, add the msg parameter to the function definition and msg.set(name) under the if name: statement:
