### ISSUE TITLE
Show warning when a stack is selected that has an upcoming or is past its end of life (EOL) 

### ISSUE THREAD

**Issue by nzthiago** [microsoft/vscode-azurefunctions#3353]
The Azure Functions Stacks API [has been updated to include End of Life dates](https://github.com/Azure/azure-functions-ux/pull/6862/files) based on our [Azure Functions language runtime support policy table](https://docs.microsoft.com/en-us/azure/azure-functions/language-support-policy#retirement-policy-exceptions).

We now would like to have the Azure Functions extension for VS Code to show warnings when a stack is selected and has an EOL date within **6 months** (or if EOL already passed).

Verbiage for the warning can be based on the Important note on the [Azure Functions runtime versions overview](https://learn.microsoft.com/azure/azure-functions/functions-versions) documentation:
"After the deadline, function apps can be created and deployed, and existing apps continue to run. However, your apps won't be eligible for new features, security patches, performance optimizations, and support until you upgrade them".

This extension already uses the Stacks API.

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/3348

**Comment by motm32** [comment]
Hi @nzthiago I noticed in the Azure Functions Stacks API that [Powershell 7.0 and 7.2 ](https://github.com/Azure/azure-functions-ux/blob/cbe5338623e0a32f2b7ec20d6dc0ca44cd9a1e0e/server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts)do not have an associated End of Life date. Is that something that will be added?

**Comment by nzthiago** [comment]
> Hi @nzthiago I noticed in the Azure Functions Stacks API that [Powershell 7.0 and 7.2 ](https://github.com/Azure/azure-functions-ux/blob/cbe5338623e0a32f2b7ec20d6dc0ca44cd9a1e0e/server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts)do not have an associated End of Life date. Is that something that will be added?

It looks like the dates were added by @Francisco-Gamino with [this PR](https://github.com/Azure/azure-functions-ux/pull/6923) five days ago to address this. They should start showing up when a future deployment includes this PR.
