### ISSUE TITLE
Casing of 'Add new setting...' is wrong in context menu

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/vscode-azurefunctions#336]
## Environment data
OS version: Win 64
Azure Function version: 0.8.2-alpha

## Steps to reproduce
1. Expand a function app and right click the 'Application Settings'.
2. Verify whether the context menu 'Add New Setting...' displays well.

## Expected  behavior
The context menu 'Add **New Setting**...' displays well. First letters are uppercase in the context menu.

## Actual behavior
The context menu 'Add New Setting...' displays as 'Add **new setting**...'.
![image](https://user-images.githubusercontent.com/12556995/39169543-d69caa04-47ca-11e8-949c-4e9b9b2362cc.png)

## More Info
1. This issue reproduces on all the context menus under 'Application Settings' node.

![image](https://user-images.githubusercontent.com/12556995/39169513-b4459f88-47ca-11e8-9889-5800f91a3654.png)

![image](https://user-images.githubusercontent.com/12556995/39169518-b8047838-47ca-11e8-8425-9904e510dad9.png)

**Comment by EricJizbaMSFT** [comment]
This was fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/430
