### ISSUE TITLE
How can I set azureFunctions.requestTimeout?

### ISSUE THREAD

**Issue by thomassligon** [microsoft/vscode-azurefunctions#3372]
I have an Azure Function that is getting the error
Request timed out. Modify setting "azureFunctions.requestTimeout" if you want to extend the timeout.
when invoked locally.
My problem: How do I set this?
I found
https://github.com/microsoft/vscode-azurefunctions/blob/main/package.nls.json
and
https://github.com/microsoft/vscode-azurefunctions
but I still don't know how to set the timeout value.
In my host.json I have
"functionTimeout": "01:00:00",
but that doesn't seem to be what I need.
Is this a stupid question, or is something missing in the documentation?

**Comment by nturinski** [comment]
To change this timeout, you need to change your `vscode/settings.json`. The easiest way to do this is to either edit the json directly.

Alternatively, you can press F1 to open the command palette:
![image](https://user-images.githubusercontent.com/5290572/196253361-08460f09-21d1-4807-9022-d9ba2cf8d679.png)
Search for the `azureFunctions.requestTimeout` setting
![image](https://user-images.githubusercontent.com/5290572/196253460-5202805d-3a0d-4d83-af3b-e00229bb4999.png)

**Comment by thomassligon** [comment]
Thanks! This did exactly what I needed, at least locally. I modified .vscode/settings.json, changing the default of 15 to 30, and the function ran successfully on my PC. 
Does the same setting exist in the cloud? If so, it's probably not in .vscode.

**Comment by nturinski** [comment]
I believe there is a setting called `functionTimeout` in the `host.json`. I haven't tried it myself, but [here](https://build5nines.com/azure-functions-extend-execution-timeout-past-5-minutes/#:~:text=In%20a%20recent%20update%2C%20the,timespan%20duration%20of%2010%20minutes.) is the post  discussing it.

**Comment by thomassligon** [comment]
Yes, I was aware of functionTimeout and that its possible values depend on the service plan. This is an important setting for me. However, there is a big difference between request timeout and function timeout, and I need both.
Now, even though azureFunctions.requestTimeout is set locally, in .vscode/settings.json, I have the impression that it is being replicated to some place on the host as well. In any case, I am no longer getting these errors
Request timed out. Modify setting "azureFunctions.requestTimeout" if you want to extend the timeout.
locally, and not on the host, either so the problem is solved for me.
Thanks again. I will close this issue.
