### ISSUE TITLE
Pop up a notification to install the .NET Core SDK when creating a .NET 7 project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3374]
**OS:** M1 & Win10
**Build Version:** 20221015.2
**.NET Version:** 7.0.100-rc.2.22477.23
**Regression:** Not a regression

**Repro Steps:**
1. Make sure only .NET 7 installed.
2. F1 -> Azure Function: Create New Project... -> Select a folder ->Select C#.
3. Check whether continue to select .NET runtime.

**Expect:**
Continue to select .NET runtime.

**Actual:**
Pop up a notification to install the .NET Core SDK.
![image](https://user-images.githubusercontent.com/57662131/196144119-2b17dadd-0945-4a1a-935d-a3d8590a008f.png)

**More Info:**
1. More details as below after running `dotnet --list-runtimes` and `dotnet --list-sdks` in the terminal.
![image](https://user-images.githubusercontent.com/57662131/196156557-cff84733-86fd-42c6-8add-584e31646b05.png)
2. This issue doesn't reproduce when installing the .NET 6 at the same time.

**Comment by nturinski** [comment]
I think I forgot to include .NET 7.0 to this array:
https://github.com/microsoft/vscode-azurefunctions/blob/main/src/templates/dotnet/executeDotnetTemplateCommand.ts#L64
