### ISSUE TITLE
over Remote SSH / when coming to "Executing task: func host start" Function host does not actually start

### ISSUE THREAD

**Issue by KaiWalter** [microsoft/vscode-azurefunctions#3383]
In a reproducible clean setup of an Azure VM like [this](https://community.ops.io/kaiwalter/create-a-disposable-azure-vm-based-on-cbl-mariner-2ic6) which I use to VS Code Remote SSH develop on from my Windows machine.

1. I installed these extensions:

```
code --install-extension ms-dotnettools.csharp
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension Azurite.azurite
code --install-extension Trottero.dotnetwatchattach
```

2. did a from scratch project creation (dotnet non-isolated, C#, HttpTrigger) with `func init` and `func new`

3. initialized the project with **Azure Functions: Initialize Project for Use with VS Code...**

4. started **Azurite Blob Service**

5. then started debugging with **Attach to .NET Functions**

the "func host start" does not actually start and drops into the shell

![2022-10-20 10_43_22-Clipboard](https://user-images.githubusercontent.com/7418323/196901219-ded19d8f-f0fa-4052-bf46-64f6700cb029.png)

after a while _pickProcess_ pops up with

```
Failed to detect running Functions host within "180" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.
```

submitting a `func host start` right from the shell where it dropped off connects the debugger

I had the same problem with Ubuntu 22.04 and hence decided to try it with another Linux distro.

Does anyone have any ideas or indications where I can look into?

**Comment by KaiWalter** [comment]
Same behavior with Ubuntu 20.04 / gen2 image

```
#cloud-config
package_upgrade: true
packages:
- apt-transport-https
- nodejs
- npm
runcmd:
- npm i -g azure-functions-core-tools@4 --unsafe-perm true

- wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
- dpkg -i packages-microsoft-prod.deb
- rm packages-microsoft-prod.deb

- apt-get update
- apt-get install -y dotnet-sdk-6.0
```

**Comment by KaiWalter** [comment]
same with WSL 2 / Ubuntu 20.04

**Comment by KaiWalter** [comment]
It is working when running natively on Ubuntu 20.04 - here on a VM. Hence seems to be a Remote SSH/WSL issue.

![2022-10-22 14_12_27-Ubuntu 20 04 LTS on GHOST - Virtual Machine Connection](https://user-images.githubusercontent.com/7418323/197338498-70a95a9e-fd61-45c0-80c7-b4c75544180f.png)

**Comment by nturinski** [comment]
Hi @KaiWalter

Thank you for the very detailed issue and investigation. 

Since it sounds like this may be an issue with the Remote extension, would you mind posting the issue on this [repo](https://github.com/microsoft/vscode-remote-release/issues) as well?

**Comment by KaiWalter** [comment]
@nturinski thanks for the hint - you are right, it seems to be a general issue: <https://github.com/microsoft/vscode-remote-release/issues/7458>
