### ISSUE TITLE
Functions Item does not show in Azuire Area

### ISSUE THREAD

**Issue by eliassal** [microsoft/vscode-azurefunctions#3409]
I have installed all prerequisite for VSC to start creating Azure Functions. When I click on azure icon, I see only
-Api Management
-Resources
-Workplace
-Help and support

![AzureArea](https://user-images.githubusercontent.com/8447864/171989768-38761459-30b0-483b-84d4-9d55bc625095.jpg)

Creating a function project, I see the function in workspaces area which I can run and execute **but not publish**

![AzureArea_002](https://user-images.githubusercontent.com/8447864/171989778-11723bc2-17a8-4252-be0f-23e29143fd49.jpg)

no "Functions Area" as indicated in the learn chapter at  https://docs.microsoft.com/en-us/learn/modules/develop-azure-functions/5-create-function-visual-studio-code
![AzureArea_003](https://user-images.githubusercontent.com/8447864/171989780-c30b964a-5dc5-42b2-9429-d97ce9aa7d47.jpg)

**Comment by nturinski** [comment]
@eliassal Sorry for the delay in response. That screenshot is from an older version of the Azure Functions extension.  Now, you should see a cloud button that says `Deploy...` on the `Workspace` ribbon.

![image](https://user-images.githubusercontent.com/5290572/213584514-fe5adf45-b072-4164-b83f-55c405f4bc9b.png)
