### ISSUE TITLE
There is an error after creating a "Python (Programming Model V2)" project in VS Code Insider 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3416]
**OS:** Win10
**Build Version:** 20221106.1
**Version:** 1.74.0-insider (user setup)
**Python Version:** 3.9.13

**Repro Steps:**
1. Create a new python project with "**Python (Programming Model V2)**" language -> Open in **VS Code insiders**.
2. Check whether there is no error.

**Expect:**
There is no error.

**Actual:**
There is an error.
![image](https://user-images.githubusercontent.com/57662131/199945837-03be9476-a34b-400b-afda-43b02f6becc9.png)

**More Info:**
This issue doesn't reproduce in **VS Code**.

**Comment by nturinski** [comment]
Closing as wont fix as we don't control the template contents.
