### ISSUE TITLE
The error message is not clear when creating an advanced windows Node.js Function App with "South Central US" location

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3424]
**OS:** Win10
**Build Version:** 20221109.16

**Repro Steps:**
1. Create an advanced windows Node.js Function App with "South Central US" location.
2. Check whether the error message is clear when creating this Function App.

**Expect:**
The error message is clear when creating this Function App.

**Actual:**
The error message is not clear.
![image](https://user-images.githubusercontent.com/45614674/201044123-67c47177-f57e-406c-abef-500f2dacdb0e.png)

**More Info:**
Succeed to create an advanced windows Node.js Function App with "East US" location.

**Comment by nturinski** [comment]
Could you tell me what location for `sereneadvwinnode18` App service plan?

**Comment by nturinski** [comment]
Are you able to create an app service plan in South Central US on the Azure Portal?

**Comment by v-ruizh** [comment]
@nturinski Fail to create an app service plan in South Central US on the Azure Portal. The error shows as below.
![image](https://user-images.githubusercontent.com/45614674/201254380-3d76bf2f-7e1e-4f4a-9cab-1db643adac60.png)

It would be better to show a clear error in VS Code, such as "Error: Requested features are not supported in region. Please try another region".

**Comment by nturinski** [comment]
I agree that this would be better, however this is an upstream error that we don't control so I'll go ahead and close this.
