### ISSUE TITLE
No dialog about 'Initialize for optimal use with VS Code' pops up after opening an outside project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3425]
**Build Version:** 20221109.16
**OS:** Window 10

**Repro Steps:**
1. Create a project from func cli.
2. Open it in VS Code Insiders.
3. Check whether there is a dialog pops up.

**Expect:**
The below dialog pops up after waiting a few seconds.
![image](https://user-images.githubusercontent.com/45614674/201070554-3818fcf5-9c10-49d0-ba5d-d0e5c2e7525b.png)

**Actual:**
No dialog about 'Initialize for optimal use with VS Code' pops up.

**More Info:**
1. This issue reproduces for C#/JavaScript/Python projects.
2. Navigate to Azure view, the dialog 'Initialize for optimal use with VS Code' pops up.

**Comment by nturinski** [comment]
Are you creating the project while the folder is opened in VS Code?

We can only activate the extension when the folder is first opened. We are looking for a `host.json` file. If you create that file _after_ VS Code activates, VS Code will not check for that file again.  This is not behavior that we can change.

If you reload the window after creating the project from with `func new`, I believe that the prompt will appear. Alternatively, as you mentioned, if you open the Azure view, the extension will activate, and will show the prompt as well.
