### ISSUE TITLE
Local Git deployment fails for a Linux Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3429]
**OS:** Win10
**Build Version:** 20221111.7

**Repro Steps:**
1. Open the node.js project in VS Code -> Initialize the local Git repository by "git init".
2. Make sure your changes are committed in git.
3. Create a Linux function app with Node16/18 runtime and App Service Plan -> Change deployment source to local git.
4. Deploy the project to the above function app.
5. Check whether deploy the project to the function app successfully.

**Expect:**
Deploy the project to the Linux function app successfully.

**Actual:**
Fail to deploy the project to the Linux function app.
![image](https://user-images.githubusercontent.com/45614674/201304483-576fe9c4-7fb9-4593-8635-1e4be1d79b17.png)

**More Info:**
Succeed to deploy the project to a Windows function app, but there is no HTTP triggers found.
![image](https://user-images.githubusercontent.com/45614674/201306687-8aa620d0-ff23-44ef-91fc-9309645e20b6.png)

**Comment by nturinski** [comment]
I'm not sure if local git is supported on Linux or not. Local git is pretty unpopular on functions and actually [not recommended](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#local-git).
