### ISSUE TITLE
[Unstable] There are two "Workspace" views after collapsing and expanding the "Workspace" view on Linux

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3436]
**OS:** Ubuntu 22.04
**Build Version:** 20221112.5

**Repro Steps:**
1. Install Azure Function extension.
2. Navigate to Azure View then collapse and expand the "Workspace" view.
3. Check whether there is only one "Workspace" view.

**Expect:**
There is only one "Workspace" view.

**Actual:**
There are two "Workspace" views.
![image](https://user-images.githubusercontent.com/45614674/201897597-96a765b7-c2c0-49af-981d-b3c2c1febd3e.png)

**More Info:**
1. This is only one "Workspace" view after single clicking in it.
2. This issue only reproduces on Ubuntu, it does not reproduce on Windows and Mac.
3. This issue is unstable, it is easy to reproduce if the network is a bit slow.

**Comment by nturinski** [comment]
Is there anyway to get rid of the extra Workspace view? Either by refreshing or reloading VS Code? Does it only happen when you first install the Azure Functions extension?

**Comment by nturinski** [comment]
Closing as wont fix since it seems to be unstable.
