### ISSUE TITLE
Error occurs when opening the files from a Windows Node.js Function App Files node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3450]
**OS:** All
**Build Version:** 20221124.7

**Repro Steps:**
1. Create a Windows Node.js Function App.
2. Expand "Files" node of the Function App -> Open the files of Files node.
![image](https://user-images.githubusercontent.com/45614674/203943253-0666cf8f-dbd2-434f-8e9f-fbfbd3667b11.png)
4. Check whether succeeds to open the files without any error.

**Expect:**
Succeed to open the files without any error.

**Actual:**
Error occurs when opening the files of the Files node.
1. The below error occurs when opening the web.config file.
![image](https://user-images.githubusercontent.com/45614674/203943461-7fab46a1-f21f-4e7d-982b-fc1b3b6fc837.png)
2. Another error occurs when opening the "FAILED TO INITIALIZE RUN FROM PACKAGE.txt" file.
![image](https://user-images.githubusercontent.com/45614674/203943697-3410dd6b-27ca-4719-b1cd-8063bfb6e4ae.png)

**More Info:**
There is only a host.json file in Files node of a Linux Function App, it can be opened successfully without any error.

**Comment by nturinski** [comment]
It seems like we may not be sending the GET request properly for these two particular files. Looking at the portal's GET request, it may need an extra `/` in the file path.

**Comment by v-ruizh** [comment]
This issue is no longer reproduce on the extension build 20230821.4, close it.
