### ISSUE TITLE
[Question]: Download remote settings for multiple functions in a workspace

### ISSUE THREAD

**Issue by simplecommerce** [microsoft/vscode-azurefunctions#3452]
Hi,

I had a question in regards to downloading remote settings for a function app.

My workspace contains multiple function apps.
I am able to deploy, test it, it all seems to work fine.

But when I try to download remote settings, it will prompt if `local.settings.json` doesn't exist for my first function app.
But if I try to select another function app and download it, I no longer have the prompt to select the target folder/app to download it to. It always overwrites the first one.

How do I force it to ask me every time what app to download the remote settings for?

Hope you can help, thanks!

Here is a screenshot of what I mean:

![image](https://user-images.githubusercontent.com/31987945/204798792-3d93a6c4-f4e8-40ff-90d4-3e19ee85bf0e.png)

**Comment by nturinski** [comment]
Hi @simplecommerce

Thanks for reporting this issue. This is a limitation of download remote settings right now. Rather than prompting the user for which workspace folder or using the default app setting, it is automatically selecting the first workspace.

I think the only workaround would be to open the workspace in its own VS Code editor. Thanks for bringing this to our attention; we'll fix this so that it prompts the user if there is more than one workspace.

**Comment by simplecommerce** [comment]
@nturinski I think I spoke too soon, is it possible that it currently also doesn't support multiple `local.settings.json` for a workspace containing multiple functions?

See attached screenshots:

In this image, I have 3 functions and the `local.settings.json` is in the one I want to test.
![image](https://user-images.githubusercontent.com/31987945/205928525-c983cd2f-acc7-40ed-961a-a351975c0e2d.png)

When I select that function and try to run it, I get this error.
![image](https://user-images.githubusercontent.com/31987945/205928540-5712b40a-28cb-454a-83d3-19749d17a252.png)

It works if I copy/paste the `local.settings.json` in the first one.

I assume this is the same issue but with the test/run feature.

If you confirm, should I create a separate issue for this?

**Comment by nturinski** [comment]
I believe it's related. We currently only grab the `local.settings.json` from the first workspace folder. I think the solution would be the same. I think we can just fix it all in this one issue, but thanks for bringing it to our attention 😊

**Comment by MicroFish91** [comment]
@simplecommerce Great find, working on a fix for this!

In response to your comment regarding the debugging scenario - does this workflow solve your issue?

1) On the left sidebar, select the `Run and Debug` tab
![image](https://user-images.githubusercontent.com/40250218/209710148-b1796f67-3a6b-4958-87bb-cdedbdc53dc3.png)

2) Use the header dropdown to change attachment
![image](https://user-images.githubusercontent.com/40250218/209710317-feee5dd5-48c4-4a9f-918f-a94fe04469fe.png)
![image](https://user-images.githubusercontent.com/40250218/209710329-3a6cb7f4-39bd-49d0-bc9b-aeece80adb56.png)

**Comment by simplecommerce** [comment]
> @simplecommerce Great find, working on a fix for this!
> 
> In response to your comment regarding the debugging scenario - does this workflow solve your issue?
> 
> 1. On the left sidebar, select the `Run and Debug` tab
>    ![image](https://user-images.githubusercontent.com/40250218/209710148-b1796f67-3a6b-4958-87bb-cdedbdc53dc3.png)
> 2. Use the header dropdown to change attachment
>    ![image](https://user-images.githubusercontent.com/40250218/209710317-feee5dd5-48c4-4a9f-918f-a94fe04469fe.png)
>    ![image](https://user-images.githubusercontent.com/40250218/209710329-3a6cb7f4-39bd-49d0-bc9b-aeece80adb56.png)

In my workspace I have 3 function apps, I am able to select the one I want to run and debug no issues.
The issue is only with the `local.settings.json`, it only seems to look for/pick the `local.settings.json` file of the first function app in the list.

If I delete the file and try to run any function app, it gives me that error. But if I download the settings remotely it will create the file in the very first function and then allow me to test any of the selected functions within my workspace with that file.

Sorry if I am not clear.

**Comment by MicroFish91** [comment]
> The issue is only with the `local.settings.json`, it only seems to look for/pick the `local.settings.json` file of the first function app in the list.

Oh I think I see what's happening, thank you for clarifying for me 😊

**Comment by MicroFish91** [comment]
We've merged in a fix for this issue.  It should be available in the next release.  If you'd like to test it out before then, here is a link to download the vsix:  https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=56394&view=artifacts&pathAsName=false&type=publishedArtifacts

Thank you for helping us improve our product!
