### ISSUE TITLE
Refresh local workspace when creating a function project

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurefunctions#3454]
It seems like you have to manually refresh the local workspace for a project to show up after creating a function project.

**Comment by MicroFish91** [comment]
Are you still able to repro this? I have not been able to.

I have tried both creating new projects and functions from both empty workspaces and existing workspaces and all have immediately shown up in the local workspace project section.

**Comment by motm32** [comment]
I am able to repro this. I always have to click the refresh button to see the local project show up in the workspace.
