### ISSUE TITLE
Create New Project defaults to Python

### ISSUE THREAD

**Issue by mnbf9rca** [microsoft/vscode-azurefunctions#3455]
Whenever i select the `Azure Functions: Create New Project` option in VS Code, it always defaults to Python - i don't get asked what language to use. Then when i select `Create New Function` it's in Python.

I've tried setting `"azureFunctions.projectLanguage": "JavaScript"` in `.vscode/settings.json` and although the boilerplate is created for a JS function, the `FUNCTIONS_WORKER_RUNTIME` value in `local.settings.json` is still `Python`, and it creates a `requirements.txt` not `package.json` file, and the `.gitignore` is for Python not JS.

**Comment by nturinski** [comment]
Hi @mnbf9rca

Have you started in a brand new/empty folder when you tried creating a new project?

Is it possible that you have set `azureFunctions.projectLanguage` as a User or Global setting? If this is the case, I believe that it is being used preferentially over the workspace setting.

Could you please check your user settings for me?

![image](https://user-images.githubusercontent.com/5290572/205181236-184adc54-e7a9-44aa-93b1-4ddbf3336ec1.png)

![image](https://user-images.githubusercontent.com/5290572/205181069-43981401-0934-43be-a565-de5f9cf9c685.png)

**Comment by mnbf9rca** [comment]
Yes, this is the problem. I don't recall setting it though if i did it was years ago! It would probably help to include a reference somewhere in the [startup tutorials](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-node)? I tried googling but all i could find was [this question which doesnt say how to fix it](https://social.msdn.microsoft.com/Forums/azure/en-US/61658bea-b195-4a52-9fa2-1e086cbbea70/how-to-change-programming-language-for-functions-in-visual-studio-code?forum=AzureFunctions) (despite being marked as answered)!
