### ISSUE TITLE
Doesn't recognise .net core sdk install through brew.sh

### ISSUE THREAD

**Issue by sangiliarumugam** [microsoft/vscode-azurefunctions#3457]
Hi,
     I installed the .net core SDK using brew.sh in macOS Ventura. The dotnet-cli works without any issues. However, the azure functions extension doesn't recognise the SDK and keeps prompting me with this message.

"You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions."

I tried with adding symlink to /usr/local/bin but no joy yet.

Details:

dotnet-sdk: 7.0
architecture: arm-64
OS: MacOS Ventura

**Comment by nturinski** [comment]
Hi @sangiliarumugam 

Sorry that you're encountering this problem. 

I think that the .NET core SDK installation is fine, but the extension currently does not support the .NET 7 SDK. The easiest workaround is to install .NET 6 for now. You should still be able to create .NET 7 function projects with .NET 6 installed.

Here is a relevant issue: https://github.com/microsoft/vscode-azurefunctions/issues/3374

**Comment by sangiliarumugam** [comment]
Thanks! The extension works with dotnet version 6.
