### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/vscode-azurefunctions#3462]
Hi,

I'm trying to deploy an Azure Functions app through VSCode and I'm getting the following error: (seen here https://github.com/microsoft/vscode-azurefunctions/issues/2597)

```
request to https://azdermscosmosfunctiondev.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=ms-azuretools-vscode&deployer=ms-azuretools-vscode&trackDeploymentId=true failed, reason: unable to get local issuer certificate
```

I'm on a corporate VPN, is there a fix for this?

**Comment by nturinski** [comment]
Hi @stevenhurwitt

Could you verify your proxy settings? There's more information on how to configure your proxy here: https://code.visualstudio.com/docs/setup/network
