### ISSUE TITLE
Revisit `shouldPrompt` methods to ensure they do not have extra effects.

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurefunctions#3465]
Should revisit `shouldPrompt` methods and especially the connection prompt-based steps to ensure they no longer have side-effects once this is implemented: 
 https://github.com/microsoft/vscode-azuretools/issues/1279

**Comment by alexweininger** [comment]
What sort of side effects are we trying to prevent? We could probably enforce that the context isn't updated by using `Object.freeze` or something

**Comment by MicroFish91** [comment]
Yeah, we're just trying to handle those effects in other methods :)

**Comment by MicroFish91** [comment]
I believe this was handled by: #3468

**Comment by nturinski** [comment]
There are probably other instances of async validation methods, but we can handle those on a case by case basis.
