### ISSUE TITLE
Confusing prompt to overwrite tasks upon workspace open results in non-runnable app

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-azurefunctions#3469]
## Environment
VS Code 1.74.0
Mac OS Ventura 13.0.1
Functions extension v1.9.0

## Repro steps
1. Install prerequisites for Azure Dev CLI-enabled application "ToDo App with CSharp Functions and Azure SQL": https://github.com/Azure-Samples/todo-csharp-sql-swa-func#prerequisites
2. Create new empty folder and run `azd init -t todo-csharp-sql-swa-func` there
3. Open the folder in VS Code.

## Expected
Apart from the prompt to restore the .NET API (middle tier) project, there should be no prompts/warnings.

## Actual
There is a prompt that says
> Detected an Azure Functions Project in folder 'blah' that may have been created outside of VS Code. 
Initialize for optimal use with VS Code?

Who doesn't want optimal use? You say yes and see another prompt

> This will overwrite the following tasks in your tasks.json: "func: host start"

This is confusing: there is no task "func: host start" in `tasks.json`. What the extension refers to is a task that is part of the template, which is labeled ["API Functions Run"](https://github.com/Azure-Samples/todo-csharp-sql-swa-func/blob/main/.vscode/tasks.json#L43). If a task to be overwritten has a label, the extension should use the label for prompting.

If the user says yes, the task will be overwritten. Unfortunately this task is used by other tasks, and the end result is that the user loses ability to run the app locally.

## What I really want
An ability for this template to "tell" Azure Functions extension that it is complete with regards to  Azure Functions-related tasks, and that it should not offer to update/overwrite `tasks.json` file. Is there such a mechanism?

**Comment by karolz-ms** [comment]
OK I think I found what I want: I need to put

```json
{
"azureFunctions.showProjectWarning": false
}
```

in workspace settings.

So my only gripe now is that the second prompt should use task label if available.

**Comment by karolz-ms** [comment]
With the above setting as a workaround the template can be made to work smoothly, but I am still wondering if the extension should offer to generate Functions-related tasks (and overwrite existing task) in this case. Should not the presence of a task of a `func` type be a clue that the workspace is already configured to work with Functions?

**Comment by nturinski** [comment]
Hi @karolz-ms 

When we determine a project needs to be re-initialized, we're looking for two specific vscode settings: `azureFunctions.projectLanguage` and `azureFunctions.projectRuntime`.

We need these settings to select which templates to display to users when creating function triggers. I think if you included these settings with your template, we won't prompt the warning and you won't have to suppress it.

Here's an example of the `settings.json` that we generate for the project.
```
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.postDeployTask": "npm install (functions)",
    "azureFunctions.projectLanguage": "JavaScript",
    "azureFunctions.projectRuntime": "~4",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.preDeployTask": "npm prune (functions)"
```

**Comment by karolz-ms** [comment]
@nturinski thank you. Will try `projectRuntime` and `projectLanguage` settings.

**Comment by karolz-ms** [comment]
The suggestion works ☺️ PR submitted https://github.com/Azure/azure-dev/pull/1280 That said, for the Functions ext, you still might want to consider whether to improve the project detection logic, and as a minimum, use the task label when prompting the user to update tasks.

**Comment by nturinski** [comment]
I agree-- we will leave this issue opened for those suggestions!

**Comment by alexweininger** [comment]
In this case, when we see they have a `func` task with a label different from `"func: host start"` we should just add a new task instead of overwriting the existing task.
