### ISSUE TITLE
quick pick input goes away when creating new resource group using keyboard

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurefunctions#347]
* use the mouse to click on the "deploy" button on the extension explorer header

![image](https://user-images.githubusercontent.com/1487073/39558962-d632ab08-4e60-11e8-9b10-ec66163980a8.png)

* use the keyboard to answer the following questions

![image](https://user-images.githubusercontent.com/1487073/39558969-df7209c0-4e60-11e8-9973-6fe3dad665c9.png)

* an existing subscription

![image](https://user-images.githubusercontent.com/1487073/39558974-ea7ead1e-4e60-11e8-85e2-76e8763f2cde.png)

* create new function app

![image](https://user-images.githubusercontent.com/1487073/39558983-f2c1b0d4-4e60-11e8-83ad-629dfef18e06.png)

* functionapp name

![image](https://user-images.githubusercontent.com/1487073/39558992-fff28828-4e60-11e8-80bd-52cd9abb1189.png)

* create new resource group

![image](https://user-images.githubusercontent.com/1487073/39558997-0822b612-4e61-11e8-9b4e-79c01afd86cc.png)

result: you dont get the next prompt where you can enter the name of the resource group.

*  then, eventually, after clikcing around for a bit, then you get prompted. not exactly sure what causes it to happen or if its like a long time and i just keep missing it

![image](https://user-images.githubusercontent.com/1487073/39559023-30fbe054-4e61-11e8-8c51-a7ba69f4a7a1.png)

happens in stable and in insiders...

**Comment by fiveisprime** [comment]
I'm unable to repro this on both stable and insiders using the extension from the market.

**Comment by chrisdias** [comment]
@fiveisprime  I wonder if it has something to do with timing.  i'm on a slow hotel connection when this happens.  maybe try tethering your phone and see if you can repro?

**Comment by fiveisprime** [comment]
I was able to repro by using a similar name: `aaaa-aaaa-aaaa-aaaa`. Something about that format makes it slow to suggest a resource group name.

**Comment by EricJizbaMSFT** [comment]
@chrisdias I sent out a PR with a fix for this. Should be included in the next release.

The problem occurs because you have multiple hyphens in your function app name (it breaks our 'related name' generation for resource groups, which don't support hyphens). As a workaround, use a name without multiple hyphens
