### ISSUE TITLE
Template version should match local func cli version

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#348]
Today we always download the latest version of the templates, but ideally it should match what they have installed locally

**Comment by nturinski** [comment]
As this was the intended behavior, wanted to get rid of the bug label 😁

**Comment by EricJizbaMSFT** [comment]
Discussed this in triage. We already give users the ability to change their version of the templates to an old version with the "azureFunctions.templateVersion" setting. Since we want to encourage people to use the latest and they already have the workaround, we'll close this as won't-fix for now.
