### ISSUE TITLE
How to add a PowerShell function to existing DEV Slot 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/vscode-azurefunctions#3488]
The original (production) function was edited on the portal but when Slot were added, I can only use the VS code option.
I do not see an option to add a run.ps1 to the dev slot.

I can only create new function but I need to use an existing one.
Please help

**Comment by nturinski** [comment]
Hi @Ofer-Gal

When you say you need to use an existing function, do you mean the function app or the function trigger?  The triggers are listed in the VS Code extension. 

If you deploy to the slot with the edits to the function trigger, then your changes should be picked up by the dev slot.

**Comment by Ofer-Gal** [comment]
The function app. There should be an option to have different code for different slots right?
In the portal, I see functions for each slot and now there is no function in DEV slot. 
How do I add code with the VS Code extension?

**Comment by nturinski** [comment]
You can deploy your project to the slot directly from the extension.

If you expand into your function app, there is a slots node. Expand that, and you should see your slot. Right-click that and click "Deploy to Slot...". It will prompt you to deploy your project to the dev slot.

Hope that helps to resolve your problem!

![image](https://user-images.githubusercontent.com/5290572/211396023-dd3b140f-a997-4913-95f6-e3c5945a23f4.png)

**Comment by Ofer-Gal** [comment]
I did not have that before. Now I do.

When I choose it, I get prompted for the folder and I choose where the run.ps1 is. But then I get an error:
`Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage`
Do I  need to first download something to have the entire function app on my local disk like in VS 2022?
Thanks

**Comment by nturinski** [comment]
Yes, you will have to deploy the entire function project, not just the trigger.

**Comment by Ofer-Gal** [comment]
So how do I get the existing "entire function project" to a folder on my disk?

**Comment by nturinski** [comment]
If you have access to the function app on the [Azure Portal](https://ms.portal.azure.com/), there is a button to `Download app content`.

![image](https://user-images.githubusercontent.com/5290572/211902625-33352854-be9f-4feb-814f-56711eda4fc9.png)

**Comment by nturinski** [comment]
Hopefully everything is resolved now. If not, please feel free to re-open!
