### ISSUE TITLE
Fail to execute command "Azure Functions: Delete Function App..." from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3497]
**OS:** Win10
**Build Version:** Azure Function v1.9.1-alpha.0 + Azure Resources v0.5.7-alpha.0

**Repro Steps:**

1. F1 -> Azure Functions: Delete Function App... -> Select a subscription -> Select a resource.
2. Check whether succeeds to execute command "Azure Functions: Delete Function App..." directly.

**Expect:**
Succeed to execute command "Azure Functions: Delete Function App..." directly.

**Actual:**
Continue to perform the next step and fail to execute command "Azure Functions: Delete Function App...".
![image](https://user-images.githubusercontent.com/107091828/209296296-c648dd59-24d8-4057-a259-109a460797b4.png)

**More Info:**
This issue also reproduces when executing command "Azure Functions: Configure Deployment Source..." from command palette.

**Comment by alexweininger** [comment]
Note: to fix this, we need to stop passing an expected child context value when we call pick app resource.

**Comment by alexweininger** [comment]
Fixed in https://github.com/microsoft/vscode-azurefunctions/pull/3507
