### ISSUE TITLE
An error occurs when debugging a .NET 6 LTS C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3501]
**OS:** Win10
**Build Version:** Azure Function v1.9.1-alpha.0 + Azure Resources v0.5.7-alpha.0

**Repro Steps:**
1. Create a **.NET 6 LTS** C# project with HttpTrigger Function.
2. Set a breakpoint.
3. Debug this project.
4. Navigate to Workspace view -> Expand Local Project/Functions node -> Right click the function and select "Execute Function Now..." to execute.
5. Click "Continue" button to continue debugging after the breakpoint hit.
6. Check whether succeeds to debug the project or not.

**Expect:**
Succeed to debug this .NET 6 LTS C# project.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/209318568-e90deb15-800a-4169-88fc-b46710ddc24a.png)
![image](https://user-images.githubusercontent.com/45614674/209318918-20380fdf-71ce-40e3-8825-c15ae6fed0b6.png)

**More Info:**
This issue does not reproduce for .NET 6 isolated LTS and .NET 7 isolated projects.

**Comment by alexweininger** [comment]
This is probably unrelated to v2, so I will remove the label.

**Comment by nturinski** [comment]
Could you test this again? I believe we submitted a change that should fix this behavior.

**Comment by alexweininger** [comment]
Does the breakpoint get hit if you access the Function endpoint via the browser?

**Comment by nturinski** [comment]
@v-ruizh Could you verify this bug when you are doing the release testing? We think we have a fix for this.

**Comment by v-ruizh** [comment]
@nturinski Sorry for the late reply. Verified this issue on RC build 20230127.31, it is no longer reproduce, close it.
