### ISSUE TITLE
Node v4 model should list local functions

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#3513]
Right now this list is always empty in the new node.js model:

<img width="313" alt="Screen Shot 2023-01-09 at 2 35 36 PM" src="https://user-images.githubusercontent.com/11282622/211421995-a22d40f8-dbbb-412b-959e-ac30ea52ccc9.png">

.NET and Python v2 already have logic to show functions without function.json files. I'm hoping the fix is as simple as adding Node.js v4 to that list, probably here: https://github.com/microsoft/vscode-azurefunctions/blob/main/src/tree/localProject/LocalFunctionsTreeItem.ts#L39

**Comment by nturinski** [comment]
I love it when you're right.
