### ISSUE TITLE
Clearer exception message - Azure functions .NET and VS Code extension

### ISSUE THREAD

**Issue by cloudmelon** [microsoft/vscode-azurefunctions#3517]
For Azure functions v4 .NET. 6 in-process, we have .NET 6 dependencies. For .NET 6 isolated and .NET 7 isolated, it requires respective .NET SDK installed when using VS Code extension working with .NET Azure functions.

Request changes in the current exception message ( as indicated in the following screenshot )

Replace the text '.NET Core SDK' with 

1. Use case 1  Azure functions .NET 6 in proc - > '.NET 6 SDK'  or / and '.NET 7 SDK' ( depending on what's missing in users local machine )
2. Use case 2: Azure functions .NET 6 isolated -> '.NET 6 SDK'
3. Use case 3 : Azure functions .NET 7 isolated -> '.NET 7 SDK'

Thanks and let me know if any further clarification is needed. 

![image](https://user-images.githubusercontent.com/4621560/211897516-764c3ea3-7bc5-4153-aaa8-143525ca9857.png)

**Comment by nturinski** [comment]
What about in the case of in-process .NET 7? I know that doesn't exist as a runtime for Function Apps right now, but does that require .NET 7+ or would .NET 6 also be a valid SDK?

**Comment by cloudmelon** [comment]
> What about in the case of in-process .NET 7? I know that doesn't exist as a runtime for Function Apps right now, but does that require .NET 7+ or would .NET 6 also be a valid SDK?

There's no .NET in-processs. But the host still needs .NET 6 SDK.
