### ISSUE TITLE
Workspace (local) Not Visible

### ISSUE THREAD

**Issue by pawlowski6132** [microsoft/vscode-azurefunctions#3522]
VSCode v1.68.1
Azure Function Extension v1.9.0

I'm experiencing a basic issue here and am having trouble root causing this. Any guidance would be greatly appreciated.

I don't seem to have the Workspace are visible. I've tried to rewind to previous versions of the extension ( I know my VS Code is older but, need to stay at v1.68 for now), reinstalls, etc. 

![image](https://user-images.githubusercontent.com/58073788/212943617-5df27fe9-a5c2-4331-ab5d-f2b4b686ab5f.png)

I was expecting this Workspace option.

![image](https://user-images.githubusercontent.com/58073788/212943806-1ba7a33c-3c78-404c-81c3-73ef1458effb.png)

**Comment by nturinski** [comment]
Hi @pawlowski6132 

Is it possible that you accidentally hid the workspace view? If you right-click anywhere in the Azure view panel, this context menu should appear.

![image](https://user-images.githubusercontent.com/5290572/212984191-1ab0c3d2-50fb-4dd0-966a-71508765a3a7.png)

**Comment by pawlowski6132** [comment]
Thank you so much for taking the time to try to help. Unfortunately, that's not it.
![image](https://user-images.githubusercontent.com/58073788/212985784-9ee83cbd-55ab-4cb0-aa95-23efb82911e9.png)

**Comment by alexweininger** [comment]
@pawlowski6132 

It's possible that the view was moved outside the Azure panel. 

Could you try running the "Azure: Focus on Workspace view" command from the command palette? (Access this by pressing F1)

<img width="604" alt="image" src="https://user-images.githubusercontent.com/12476526/213018421-62b2314f-c317-4102-851b-ceeded7553c0.png">

**Comment by pawlowski6132** [comment]
Rats. No luck. Thank you though.

![image](https://user-images.githubusercontent.com/58073788/213022448-67d64339-ef25-4139-853a-f1b9cc59d77a.png)

**Comment by alexweininger** [comment]
What version of the Resource Groups extension do you have installed?

**Comment by pawlowski6132** [comment]
So, did you mean this extension?

![image](https://user-images.githubusercontent.com/58073788/213027682-22bc0bea-50ed-4426-aa03-de0b59547f14.png)

**Comment by nturinski** [comment]
Yes, that is the extension he was referring to. Could you try updating to the latest version?

**Comment by pawlowski6132** [comment]
Wow. That never occurred to me. You did it. Thank you so much.
You can go home early today.
seriously, thanx

![image](https://user-images.githubusercontent.com/58073788/213033979-4fe100b1-2de8-4964-854a-80c6f1f425ab.png)
