### ISSUE TITLE
Azure Functions: Create New Project doesn't show option for Python 3.10.x when choosing V2 Model

### ISSUE THREAD

**Issue by kjaymiller** [microsoft/vscode-azurefunctions#3525]
---
Extension Version: Azure Functions v1.9.0
Platform and Operating System: MacOS Ventura 13.1
VS Code Version: 1.74.3 
---

When I try to create a new project to use the Python Programming Model v2, the versions to select from are 3.6 - 3.9

<img width="943" alt="CleanShot 2023-01-25 at 08 13 22@2x" src="https://user-images.githubusercontent.com/8632637/214617307-ab0b91e6-78c1-47d1-85a7-2258e289a108.png">

## Steps to Recreate:

1. Activate Command Palette
2. Select Azure Functions: Create New Project
3. Select Browse: Choose Test Folder
4. Python (Programming Model V2) 
5. Select `Manually Enter Python Interpreter or Full Path`
6. Paste the path to your `Python 3.10.4` environment

**Comment by nturinski** [comment]
This will ship with our next release. It was added in this PR (thanks for the contribution!) https://github.com/microsoft/vscode-azurefunctions/pull/3511
