### ISSUE TITLE
An error occurs when debugging MSSQL project

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3535]
**OS:** Win 10/Mac
**Build Version:** 20230128.2

**Repro Steps:**

1. Create and open a project with "Durable Function orchestrator" function and select "MSSQL" durable storage type.
2. Create functions with "Durable Functions activity" and "Durable Functions HTTP Starter" templates.
3. F5 -> Select "Connect Custom SQL Database" -> Copy a SQL connection string -> Select "Connect Storage Account".
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/215316304-636ba99b-d58e-4514-8d28-09f4c2b3f40f.png)

**More Info:**
This issue also reproduces when selecting "Use Local Emulator".

**Comment by MicroFish91** [comment]
For `Custom`, I would just test that what you enter is matching what is being uploaded to `local.settings.json` (if debugging) or the Function App's `application settings` (if deploying).  It is currently out of scope to verify that the custom connection string entries are valid before debug or deploy.

There is currently no local emulator support for `MSSQL` as well, that may change in the future though as there are some cool features in preview coming down the line 🙂

Closing this one as not planned.  If you find that the `Custom` connection strings are not copying properly, please open a new issue, thanks!
