### ISSUE TITLE
No overwrite prompt pops up when deploying a project which debugged with "Use Local Emulator"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3536]
**OS:** Win 10
**Build Version:** 20230128.2

**Repro Steps:**

1. Create and open a Python/JavaScript project with "Durable Function orchestrator" function and select "Azure Storage/Netherite" durable storage type.
2. Create functions with "Durable Functions activity" and "Durable Functions HTTP Starter" templates.
3. F1 -> Azurite: Start.
4. F5 -> Select "Use Local Emulator".
5. Right click a function -> Click "Deploy to Function App...".
6. Check whether pop up a overwrite prompt.

**Expect:**
Pop up a overwrite prompt.
![image](https://user-images.githubusercontent.com/57662131/215324627-276d0684-8a8b-42f6-9e29-fe2896bae167.png)

**Actual:**
No overwrite prompt pops up.

**More Info:**
1. This issue doesn't reproduce for the project which debugged with "Connect Storage Account/Connect Event Hubs Namespace".
2. The application settings 'azureWebJobsStorage' and 'eventHubsConnection' are not overwritten.

**Comment by MicroFish91** [comment]
This one is by-design.  The functions extension does some smart detection where it will check if the `local.settings.json` is using an emulator for the connection string.  If it is an emulator string, it won't prompt for overwrite.
