### ISSUE TITLE
The output value is null after doing a GET request on the url of the " statusQueryGetUri"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3537]
**OS:** Win 10
**Build Version:** 20230128.2

**Repro Steps:**

1. Create and open a JavaScript project with "Durable Function orchestrator" function and select "Netherite" durable storage type.
2. Create functions with "Durable Functions activity" and "Durable Functions HTTP Starter" templates.
3. F1 -> Azurite: Start.
4. F5 -> Select "Use Local Emulator".
5. Create a new file` request.http` in the project -> Type `GET Url` -> Click "Send Request" -> Copy` statusQueryGetUri` in the `Response` file -> Type` GET statusQueryGetUri `-> Click "Send Request".
6. Check the output value.

**Expect:**
The output value should display as below.
![image](https://user-images.githubusercontent.com/57662131/215326766-df9699f2-cf57-4f3a-a2dc-2f2da7e3c419.png)

**Actual:**
The output value is null.
![image](https://user-images.githubusercontent.com/57662131/215326711-2d2900bc-c879-4510-a210-8df30d6d4006.png)

**Comment by MicroFish91** [comment]
Oh I had a thought, this sometimes happens when your filenames do not match the calls being made inside the `index.js` files.

**Comment by v-xinda** [comment]
@MicroFish91  This issue does not reproduce after changing the filename to match inside the index.js files.
