### ISSUE TITLE
Node v4 model: Clarify what "Learn more" is about

### ISSUE THREAD

**Issue by lilyjma** [microsoft/vscode-azurefunctions#3547]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/25314976/216682314-5198b386-4eae-40f6-9f23-460bd5174e9f.png">

**Request:** Change to "Learn more about Model V4"

**Comment by nturinski** [comment]
Hi @lilyjma

Thanks for all the feedback! This is helpful and insightful.

Could I request that you break up all of these into separate issues though? It will be difficult for us to track what we have completed and what remains to be done if it's all in one issue. It also makes it more difficult for us to triage the issues.

**Comment by alexweininger** [comment]
Really like this suggestion. Having a label more specific than "Learn more..." is a lot more inviting. I think this will increase usage of the learn more button quite a bit. 

We should do this wherever we already use the learn more button if we aren't.
