### ISSUE TITLE
Deployments never load

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurefunctions#3549]
Expanding the deployments tree item never loads the deployments. Just spins forever. Noticed this yesterday and it's still reproducing today.

Extension version: 1.10.0 (also repros on 1.9.0)

<img width="310" alt="image" src="https://user-images.githubusercontent.com/12476526/216724781-1deecf39-529e-4761-8185-3f2512c8d402.png">

Note: Also just tried to load the deployments in the portal and that's not working either. So it may be a service issue.

**Comment by alexweininger** [comment]
Update:

Got some service errors:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/12476526/216730151-e6d0deab-ba3f-452a-9bd1-8c9a03a734c9.png">


```
Error: Service Unavailable

----------------------------------------

HTTP Error 503. The service is unavailable
```

```
Error: Server Error in '/' Application.

----------------------------------------

The network path was not found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.IOException: The network path was not found.


Source Error:



An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.


Stack Trace:





[IOException: The network path was not found.
```

This second one was so long it got cut off.

**Comment by nturinski** [comment]
Looks like a you problem:

![image](https://user-images.githubusercontent.com/5290572/217678276-28346ad8-f11e-4411-ad2c-0e7bc6221192.png)
