### ISSUE TITLE
Node v4 model: Connection info not populated correctly for Cosmos and Service Bus triggers

### ISSUE THREAD

**Issue by lilyjma** [microsoft/vscode-azurefunctions#3550]
Cosmos trigger: `connectionStringSetting` is undefined, though user is prompted to create local app setting. 

**Request:** 
1. ~~Should _not_ prompt user about this if can't fill in the info correctly - simply use empty string as value for the property.~~ Guide user to create resource if doesn't already exist, just like Storage today. 
2. **OR** - if we can't do the above now, change the "skip for now" (2nd screenshot) to "skip for now because no resource is found" 

Current experience:
1. Choosing to create new local app setting 
  <img width="360" alt="image" src="https://user-images.githubusercontent.com/25314976/216683250-1b15eb6b-7c5e-4b74-a86f-1ff11d70bb81.png">
2. After logging into Azure, only option is to skip
  <img width="360" alt="image" src="https://user-images.githubusercontent.com/25314976/216683445-cfcbe57d-1622-4975-bf63-e7bf5a32cf97.png">

**Similar observation as above for Service Bus Queue and Topic trigger.** 

```[tasklist]
### Tasks
- [ ] Allow creating EventHub Namespaces
- [ ] Allow creating Service Bus Queues
```

**Comment by kulkarnisonia16** [comment]
Request #2 is potentially doable if the "Skip for now" control is not being used across other extensions OR Add message below that says "No resource found". Either behavior is acceptable for public preview.

**Comment by nturinski** [comment]
https://github.com/microsoft/vscode-azurefunctions/pull/3611 partially fixes this issue. I'm going to reopen it so we can revisit if we want to enable creating the resource directly from this quickpick prompt.
