### ISSUE TITLE
Node v4 model: Connection and event hub name not populated correctly 

### ISSUE THREAD

**Issue by lilyjma** [microsoft/vscode-azurefunctions#3551]
Event Hubs trigger: `connection` set to `%connection%` (user not prompted about local app setting in this case, unlike other triggers). User provided Event Hub namespace not used. Currently get the following code:

  ```
  connection: %connection%
  eventHubName: %eventHubName
  ```
**Request:** Leave connection as empty string if can't populate it correctly. Populate `eventHubName` correctly.

**Comment by ejizba** [comment]
This one is a bug in the templates. I'll take care of it
