### ISSUE TITLE
Deployment from VSC 1.10 to Azure functions failed: 'func' is not recognized

### ISSUE THREAD

**Issue by PauloNLopes** [microsoft/vscode-azurefunctions#3556]
Deployment from VSCode v1.09 to Azure functions was working well until VSCode was updated automatically to v1.10 a few days ago (Feb 2, 2023). Now deployment yields an error: 

Error: Command "func --version" failed with exit code "1": 'func' is not recognized as an internal or external command, operable program or batch file.

I reverted back to VSCode v1.09 and deployment is working again. Could you pls advise if and when this is fixed?

Many thanks

**Comment by PauloNLopes** [comment]
Sorry, in my message above I was referring to the v1.9.0 and v1.10.0 Azure Functions extension for VSCode. I'm using VSCode v 1.74.3. Repeating below with this correction:

Deployment from VSCode to Azure functions using Azure Functions extension v1.9.0 was working well until the VSCode Azure Functions extension was updated automatically to v1.10.0 a few days ago (Feb 2, 2023). Now deployment yields an error:

Error: Command "func --version" failed with exit code "1": 'func' is not recognized as an internal or external command, operable program or batch file.

I reverted back to VSCode Azure Functions extension v1.9.0 and deployment is working again. Could you pls advise if and when this is fixed?

Many thanks

**Comment by BarendDS** [comment]
I have the same issue

**Comment by mbbcardoso01** [comment]
Same issue here

**Comment by nturinski** [comment]
Thanks for bringing this to our attention. We've identified the cause of the bug and are currently working on a fix for it. 🙂

**Comment by nturinski** [comment]
This should be fixed! Please update to `v1.10.1` and try it out. If you're still running into issues, let us know!

**Comment by m-scipione** [comment]
Worked for me, thanks for jumping on it!
