### ISSUE TITLE
Deploy to Function App not working on Mac after January release of VScode

### ISSUE THREAD

**Issue by MateRadz** [microsoft/vscode-azurefunctions#3557]
I get this error:

Failed to get backup templates: You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.

Installing dotnet 6 does not help....

**Comment by nturinski** [comment]
Could you run `dotnet --list-sdks` and show me the output, please?

**Comment by MateRadz** [comment]
matnikr@MBP14inch2021 ~ % dotnet --list-sdks
3.1.302 [/usr/local/share/dotnet/sdk]
matnikr@MBP14inch2021 ~ %

**Comment by nturinski** [comment]
We removed .NET 3.1 SDK from the list of supported SDKs because it is EOL. You will need to install a newer .NET SDK, not just the runtime.

You can install .NET 6 [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).

**Comment by MateRadz** [comment]
Installed. The current output:

dotnet --list-sdks
3.1.302 [/usr/local/share/dotnet/sdk]
6.0.405 [/usr/local/share/dotnet/sdk]
matnikr@MBP14inch2021 ~ % 

Different error:

21:23:13: Error: Command "func --version" failed with exit code "127":
/bin/sh: func: command not found

**Comment by nturinski** [comment]
We currently have a fix for that issue in PR: https://github.com/microsoft/vscode-azurefunctions/pull/3558#pullrequestreview-1285908144

If you'd like to workaround this error now, you can install the Function Core Tools. You can install it by pressing `F1` > `Install or Update Azure Function Core Tools`

![image](https://user-images.githubusercontent.com/5290572/217078647-6ed3e554-e10a-47fd-baca-23c74ed84181.png)

**Comment by MateRadz** [comment]
Thanks. Working now with workaround. Supreme support.
