### ISSUE TITLE
Python V2 Model - New template schema support

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode-azurefunctions#3568]
To bring the v2 programming model for Python to GA, we are requesting the new templates schema support & removal of hard coding of templates.

**Comment by kulkarnisonia16** [comment]
1. @shreyabatra4 to create 1 as a different item and update it - •	Dependency on Functions templates team for GA Need to confirm ETA and VS Code team needs at least 2 weeks after that. Work is currently not blocked - experimentation can be started at this time.

3. Split programming model version as a next step in quick pick for Create. 

Trying to align desired GA data (Apr) with VS Code, Core Tools and Portal experiences

**Comment by shreyabatra4** [comment]
I have kept this work item for template schema and created another for general enhancements [here](https://github.com/microsoft/vscode-azurefunctions/issues/3570)
