### ISSUE TITLE
Azure Functions v2 Programming Model for Python - GA enhancements

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode-azurefunctions#3570]
- Support for creating functions in new files (as blueprints)
- Create experience enhancements

Details are given in the doc shared via email

**Comment by kulkarnisonia16** [comment]
#2 - Split programming model version as a next step in quick pick for Create.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/3692
