### ISSUE TITLE
Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by ATX-christophraidl** [microsoft/vscode-azurefunctions#3572]
Since about a few days I can't deploy anything to my functionapps anymore as I am always getting an error, that does not help me to pinpoint the problem.

`8:10:28 AM: Error: Unexpected token ﻿ in JSON at position 0`

![image](https://user-images.githubusercontent.com/123449127/219297194-d99bfd85-7233-496f-9d42-da994e9366ac.png)

I tried to reinstall everything related to the extension, but it still did not resolve the issue. 
Also I checked all the JSON's in my project and couldn't find any errors here.

Has anyone seen this already and knows how to fix this, or maybe get more info out of this message?

**Comment by alexweininger** [comment]
At what point in the deploy process does this error occur? Could you provide detailed steps to reproduce the issue?

**Comment by ATX-christophraidl** [comment]
Thanks for the reply.
I also had the chance to check with my coworker and he experience the same.

So there are different ways to reproduce this issue:
So the first one is:
- Open the Azure function extension
- Navigate to the Azure Function App using the "Resources" tab
- Right click on the Function app and select "Deploy to function app" 
- After a few seconds without any other output the error pops up in the Azure Function Output and as a pop up in the corner

The second way is:

- Run the function build task
- then select a function from the local workspace in the "Workspace" tab
- Click the upload button
- Select a function app
- Then the error pops up in the output and as a pop up in the corner

Thanks!

**Comment by alexweininger** [comment]
I think I was able to reproduce the exact issue you're running into.

There's an invalid character at the beginning of your host.json file. The extension fails to parse this file as JSON and throws this error.

I copied and pasted the error message you pasted in the original issue description and pasted into my host.json file and VS Code showed me an invalid character.

How I copied the character from your error message:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/12476526/219774996-10c6077b-dc5d-4be8-8174-b9d937f1e2ca.png">

How my VS Code presents this character (may vary depending on your setup):
<img width="48" alt="image" src="https://user-images.githubusercontent.com/12476526/219775377-b0cb4787-e329-422c-ba53-c7489dd92c6c.png">

When I try to deploy to a Function App via either of the two methods you listed in your above comment, the extension gives the exact same error that you encountered. I'm using a macOS based machine btw.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/12476526/219773837-b407f6fc-6995-4129-a031-0601aa84243d.png">

### Fix

To fix this, I recommend looking in your host.json file for a weird character at the beginning of the file. If you don't see anything out of the ordinary, I suggest erasing and retyping the first opening bracket `{`, to see if somehow that's causing it.

If the issue persists after trying these things, please let us know.

### Potential extension improvements

In the future, it'd be better if the extension had a better error message letting users know that it failed to parse the host.json file.

**Comment by ATX-christophraidl** [comment]
So I used your method to search for such a character and found it in two of our files, but not in the host.json or any other JSON file. 
I then also went into the host.json file and deleted the complete first line and then added the bracket again, but this also did not help. I added you the host file in the zip, maybe you find something....

Thanks for your help and the valuable input!
[host.zip](https://github.com/microsoft/vscode-azurefunctions/files/10782232/host.zip)

**Comment by alexweininger** [comment]
Hmm, the host.json looks fine. It must be another json file being parsed during deploy. Double check those for any weird characters.

There are a few VS Code settings that may help find these characters.

* `editor.unicodeHighlight.ambiguousCharacters`
* `editor.unicodeHighlight.invisibleCharacters`
* `editor.unicodeHighlight.nonBasicASCII`

<img width="862" alt="image" src="https://user-images.githubusercontent.com/12476526/220449335-a5d78e74-8497-493d-a6ee-d17ac55f8d0c.png">

Configure these settings like the screenshot above, and weird characters will be highlighted in your editor. Hope this helps.

**Comment by ATX-christophraidl** [comment]
Thanks for the settings, but I also had those turned on and used the global search to find this token in the repository and found it in two files that did not belong to the functions though. I replaced the token even in those files but the extension still shows me the same error...
Apparently without a better error description I am not able to pinpoint the issue...

**Comment by alexweininger** [comment]
Some updates:
* As a workaround, try reverting to extension version 1.9.0.
* In our investigation, we found that we're also parsing the projects package.json file upon deploy. If you have a package.json file in your project, please check that for the invalid token.
* We're working on providing a better error message.

**Comment by motm32** [comment]
Hi @ATX-christophraidl 😄,

We have updated the error message to include the file path it should look something like this: 

![image](https://user-images.githubusercontent.com/59709511/221066962-c38c4587-949d-49ad-ae41-60c55efd8c35.png)

You can use this custom vsix: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/58784/artifacts?artifactName=vsix&api-version=7.0&%24format=zip
To locally install the updated version of Azure Functions through the command palette (Press F1) and search for the below command.
![image](https://user-images.githubusercontent.com/59709511/221067796-5e8612a9-d5fc-4637-9708-8da4856d39e1.png)

Hope that helps 😊

**Comment by ATX-christophraidl** [comment]
Hey @motm32,
thanks for the update and for including the path!
This pointed to the host.json file @alexweininger mentioned in the beginning of this thread.
I completely deleted that file and wrote it new without copying anything. 
Afterwards the deploy worked again!

Thank you for your help and all the input!
