### ISSUE TITLE
Prompts for storage account and creates AzureWebJobsStorage in application settings

### ISSUE THREAD

**Issue by spaelling** [microsoft/vscode-azurefunctions#3575]
I have not used the extension in a while, but when deploying to a function app it prompts for a storage account, and proceeds to create `AzureWebJobsStorage` in application settings. This breaks my function app every single time as I use a managed identity and have access keys disabled on the storage account.

Is there some way to turn this off, or that the extension can check that `AzureWebJobsStorage__accountName` exists and it should not create `AzureWebJobsStorage`.

**Comment by ejizba** [comment]
I'm seeing something similar, where it's now prompting me to overwrite "AzureWebJobsStorage" with my local value every time I deploy

![Screenshot 2023-02-17 at 9 49 52 AM](https://user-images.githubusercontent.com/11282622/219735254-af5d47b5-a7fa-4c6d-a684-3769702ea652.png)

I think the main difference is I'm not using managed identity, but still I would never want to overwrite the remote setting

**Comment by MicroFish91** [comment]
We have an official patch release coming soon that fixes this issue.  

If you'd like a copy to install with the fix before then, please use this link:  https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/58839/artifacts?artifactName=vsix&api-version=7.0&%24format=zip

You can follow the instructions [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) to install the vsix.

Sorry for an inconvenience and thank you for helping us improve the product 😊
