### ISSUE TITLE
The input box doesn't disappear before the slot is created successfully

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3581]
**OS:** All
**Azure Resources extension:** 20230219.1
**Azure Functions Extension Version:** v1.10.2
**Regression:** Previous Release

**Repro Steps:**

1.  F1 -> Azure Functions: Deploy to Slot... -> Select subscription -> Select a resource group -> Select a function app -> Click "+ Create new Slot" -> Enter a name. 
2. Check whether the input box disappears.

 **Expect:**
The input box disappears.

**Actual:**
The input box doesn't disappear before the slot is created successfully.
![image](https://user-images.githubusercontent.com/57662131/220046328-4dba3634-abce-456b-a28e-28f47e7f8c2a.png)

**Comment by alexweininger** [comment]
This is by design.
