### ISSUE TITLE
No overwrite prompt pops up when deploying a project which debugged with "Azure Storage/Connect Event Hubs Namespace/Connect Azure SQL Database"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3608]
**OS:** Win 10
**Build Version:** 20230303.1
**Regression:** Previous release 

**Repro Steps:**

1. Create and open a JavaScript project with "Durable Function orchestrator" function and select "Azure Storage" durable storage type.
2. Create functions with "Durable Functions activity" and "Durable Functions HTTP Starter" templates.
3. F5 -> Select "Connect Storage Account".
4. Right click a function -> Click "Deploy to Function App...".
5. Check whether pops up a overwrite prompt.

**Expect:**
Pop up an overwrite prompt.
![image](https://user-images.githubusercontent.com/57662131/215324627-276d0684-8a8b-42f6-9e29-fe2896bae167.png)

**Actual:**
No overwrite prompt pops up.

**More Info:**
1. This issue also reproduces for the project which debugged with "Connect Event Hubs Namespace/Connect Azure SQL Database".
2. The issue also reproduces for the project created with "Durable Function orchestrator" function and select "Netherite/MSSQL" durable storage type.

**Comment by MicroFish91** [comment]
We decided to remove this feature in this [PR](https://github.com/microsoft/vscode-azurefunctions/pull/3593)

Closing as by-design
