### ISSUE TITLE
The deleted setting doesn't auto disappear from the application setting list

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3617]
**OS:** Win10
**Build Version:** 20230304.7

**Repro Steps:**

1. F1 -> Azure Functions: Delete Setting...
2. Check whether the deleted setting auto disappears from the application setting list.

**Expect:**
The deleted setting auto disappears from the application setting list.
![image](https://user-images.githubusercontent.com/107091828/223602952-fc61716c-0b0d-45ae-b9a9-ff20fedab911.png)

**Actual:**
The deleted setting doesn't auto disappear from the application setting list.

**More Info:**

1. This issue doesn't reproduce when executing "Delete Setting..." from context menu of the Application Settings node.
2. This issue also reproduces when executing "Azure Functions: Edit/Rename/Toggle as Slot Setting..." and then selecting "+ Create new App Settings... "command from command palette.
3. Refresh can fix this issue.

**Comment by MicroFish91** [comment]
What version of the Resource Group extension are you using?

**Comment by v-chenzha** [comment]
@MicroFish91  The version of the Resource Group extension is v0.6.1

**Comment by v-ruizh** [comment]
This issue is no longer reproduce on the extension build 20230821.4, close it.
