### ISSUE TITLE
You must have the Azure Functions Core Tools installed to debug your local functions although it's installed globally

### ISSUE THREAD

**Issue by MelihCelik00** [microsoft/vscode-azurefunctions#3619]
Hi, 

In this closed issue [#1750](https://github.com/microsoft/vscode-azurefunctions/issues/1750), it's stated that we have to install core-tools package **globally**. Actually, it was working before but after I just change between branches, this error occurred again:

![image](https://user-images.githubusercontent.com/45492251/223689858-04dde0af-0c0f-4307-ac07-9cd856a25660.png)

Since we use v3 version of the tools, I installed it with **`npm i -g azure-functions-core-tools@3 --unsafe-perm true`** but it still occurs. If I launch code from terminal it works no problem, but although my json files configured, debug mode is not working at all. I tried those below but unfortunately I still can't launch in debug mode;
- Reinstalling the package
- Closing and reopening vscode
- Checking out my launch file configurations

I know it's a simple issue but all suggestions are welcomed 😅. Thanks in advance!

**Comment by MicroFish91** [comment]
Does the problem reoccur when you completely close out and restart VS Code? If the command works in the terminal, I'm wondering if the path just hasn't been picked up yet by the VS Code terminal

**Comment by MelihCelik00** [comment]
> Does the problem reoccur when you completely close out and restart VS Code? If the command works in the terminal, I'm wondering if the path just hasn't been picked up yet by the VS Code terminal

Thanks for the reply! The command to start "func start" works out well in the terminal but debugger still does not responding at all. I tried completely shutting down and restarting either vscode and my device. But still not working :(

**Comment by MelihCelik00** [comment]
Hello again, I literally changed nothing since I opened this issue. But today, it just wanted to work and now, fortunately my debugger works well. Thanks for the help Matthew! I can only guess, since I configured json files right, it just needed some days-time to run 😄
