### ISSUE TITLE
Auto Detect .code-workspace to prevent multiple function apps detected toast

### ISSUE THREAD

**Issue by karlrissland** [microsoft/vscode-azurefunctions#3626]
I have a workspace file setup to show the root of the project so I can easily access my documents and .github workflows.  I also my logicApp project setup and an infrastructure project setup.

![image](https://user-images.githubusercontent.com/9871029/224434676-41eaac8a-ca15-489d-9752-f4d18c06d305.png)

It seems to pop up if I opened the folder instead of the workspace, but I think I have seen it even after opening the workspace.

![image](https://user-images.githubusercontent.com/9871029/224433980-a569bf78-9b6a-44c9-aed7-5da709a3a21e.png)

Clicking on the "Set Default" messes up the configuration.  You can take a look at the repo here; https://github.com/karlrissland/Logic-App-Standard-Deployment

**Comment by alexweininger** [comment]
The Functions extension is detecting that you have multiple Functions projects because you have two host.json files. 

* src/LogicAppsStandardDemo/host.json
* src/LogicAppsStandardDemo/workflow-designtime/host.json

> Clicking on the "Set Default" messes up the configuration. You can take a look at the repo here;

Can you elaborate on how clicking "Set Default" messes up the configuration?
