### ISSUE TITLE
No 'HttpTrigger' function displays under deployed function app after deploying a C# project without debugging

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#363]
Repro Steps:
1. Create a new project using C#.
2. Create a new function and add Httptrigger.
3. Deploy this project directly without debugging.

Expect:
'HttpTrigger' function displays under deployed function app.

Actual:
No 'HttpTrigger' function displays under deployed function app.

More info:
1. Deploying this project after debugging successfully.
2. This issue doesn't reproduce for Java/JavaScript.

**Comment by EricJizbaMSFT** [comment]
This is a known issue. Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/223
