### ISSUE TITLE
AzureWebJobsStorage configuration setting is created on deployment, even when AzureWebJobsStorage__accountName already exists

### ISSUE THREAD

**Issue by obesser** [microsoft/vscode-azurefunctions#3638]
It seems I have the same issue described in #3575 , even though I use v1.10.4, that according to the last comment in the issue should fix it.

**Comment by MicroFish91** [comment]
Is your remote app setting being overwritten by a local setting?  If so, is it doing so with or without prompting?

**Comment by obesser** [comment]
@MicroFish91 Exactly, when AzureWebJobsStorage__accountName exists and AzureWebJobsStorage not, the extension prompts to select a storage account and creates, in addition, the AzureWebJobsStorage setting (without touching the AzureWebJobsStorage__accountName setting).

**Comment by MicroFish91** [comment]
Hi @obesser, we just released a new version of Azure Functions (1.10.5) that includes this fix.  You can upgrade to the newest version of the extension by using VS Code's "Extensions" tab.  Thank you for your feedback and helping us improve the product 😊

**Comment by obesser** [comment]
Hey, I deleted the `AzureWebJobsStorage` setting (now there's only `AzureWebJobsStorage__acountName`) and now on deployment I get the error message `"AzureWebJobsStorage" app setting is required for Run From Package deployment.`

**Comment by MicroFish91** [comment]
Hi @obesser,

Yes, please create a new issue and we will investigate this further, thank you
