### ISSUE TITLE
Where can I see the output of Write-Host or Write-Debug

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/vscode-azurefunctions#3639]
Created a new PowerShell Azure Function project using the extension.
I am able to hit F5 after every change and call the function from a REST tool. 
break points work fine. and I can watch variables.

only I do not see the output of  Write-Debug or Write-Host anywhere 
Anyone has a clue? :-)

Thank you

**Comment by MicroFish91** [comment]
Are you able to see the Azure Functions Core Tools output in the terminal when you run the application?

**Comment by motm32** [comment]
Hi @Ofer-Gal you should be able to see output of Write-Host in the terminal under func: host start. I've included a screenshot of some code and where it should show up in the terminal. Hope this helps and please let us know if you are unable to see this information. 

![image](https://user-images.githubusercontent.com/59709511/230504593-da8c42f0-bfe6-402a-a851-b0545190ce76.png)

**Comment by Ofer-Gal** [comment]
No I do not see Write-Host in output. Maybe there is a setting  I missed?
![image](https://user-images.githubusercontent.com/5054931/230713175-8662fb0a-6f3f-47c8-b435-55df682330d7.png)

**Comment by motm32** [comment]
I did a little investigating and it seems like Write-Host won't show up in the output if a breakpoint is put on or before a Write-Host statement. Could you try removing any breakpoints before or on your Write-Host statement and see if that fixes things? This doesn't seem like something our extension handles so not exactly sure why this happens.

> But when I added a variable it did not show.

Referring to this, without any breakpoints I was able to see Write-Host with a variable if I had no breakpoints. Hope this helps and additional information on logging in Powershell is available [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell?tabs=portal#:~:text=Get%2DOutputBinding.-,Logging,-Logging%20in%20PowerShell) if you need it!
