### ISSUE TITLE
Warning when running the Durable Functions Orchestration C# template code.

### ISSUE THREAD

**Issue by hhubik** [microsoft/vscode-azurefunctions#3641]
I am upgrading a functions app project from V3 runtime to V4 using isolated worker process and .NET 7. I have created a new durable orchestration using the Azure Functions extension C# template.  When I build the project in VS Code, the project starts up with the following warning:
```
C:\Users\...\V4DurableFunctionsOrchestrationCSharp.cs(41,29): warning DF0203: DurableClient attribute is ap 
plied to a 'DurableTaskClient' but must be used with either an IDurableClient, IDurableEntityClient, or an IDurableOrchestrationClient. [C:\...\<my_azure_functions_project_name>.csproj]
```
The relevant code from the template looks like this
```csharp
        [Function("V4DurableFunctionsOrchestrationCSharp_HttpStart")]
        public static async Task<HttpResponseData> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            [DurableClient] DurableTaskClient client,
            FunctionContext executionContext)
        {
            ILogger logger = executionContext.GetLogger("V4DurableFunctionsOrchestrationCSharp_HttpStart");
...
```

Is the template not correct or do I have a problem in my upgraded project's settings?

**Comment by TheMidgardWatcher** [comment]
I've got same question.

**Comment by MicroFish91** [comment]
Oh interesting, in the process of looking over this issue, I found that in some cases we may be incorrectly adding an additional `DurableTask` package..

@hhubik Could you please check the package references in the `.csproj` file and let me know which packages have `DurableTask` included in the name?

For .NET 7 Isolated, if you see these two packages showing up:
`Microsoft.Azure.Functions.Worker.Extensions.DurableTask`
`Microsoft.Azure.WebJobs.Extensions.DurableTask`

try removing this one and re-running:
`Microsoft.Azure.WebJobs.Extensions.DurableTask`

**Comment by hhubik** [comment]
@MicroFish91 I don't have `Microsoft.Azure.WebJobs.Extensions.DurableTask` package.  These are the packages in my `.csproj` file:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0"  OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Azure.Data.Tables" Version="12.2.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.9.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.7.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.20.1" />
    <PackageReference Include="Microsoft.Azure.Search" Version="10.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.31" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.SendGrid" Version="3.0.2" />
    <PackageReference Include="Crc32.NET" Version="1.2.0" />
  </ItemGroup>
```
Could `Microsoft.Azure.WebJobs` be the problem?

**Comment by hhubik** [comment]
@MicroFish91 yeah, that was it. I have removed the ` Microsoft.Azure.WebJobs` package, and the `DF0203` warning is gone. Thanks for your help! @TheMidgardWatcher does that solve the problem for you too?

**Comment by TheMidgardWatcher** [comment]
@hhubik seems so, I don't see this warning anymore.
