### ISSUE TITLE
Azure function extension Icon dissapeared from left hand menu in Visual studio code. Azure functions extension is installed

### ISSUE THREAD

**Issue by Oleski1** [microsoft/vscode-azurefunctions#3648]
The Azure function extension Icon disappeared from left-hand menu in Visual studio code. Azure functions extension is installed
![Screenshot_4](https://user-images.githubusercontent.com/29855545/233113059-61036fc0-0ac2-4d88-a7db-823d372c6c4e.png)

**Comment by nturinski** [comment]
Could you right-click the primary-side bar? If you see `Azure`, try clicking on that.



![Image](https://user-images.githubusercontent.com/5290572/235004565-e33253d1-1110-4551-ab87-0a17bfe89c9f.png)



If it's not there, did you happen to open a new workspace? If your workspace isn't trusted, sometimes it'll just hide all of your Azure views without telling you.

You can check your workspace trust settings by pressing F1 and then typing manage workspace


![Image](https://user-images.githubusercontent.com/5290572/235004807-85739e90-48d8-4274-be5f-ca0d2ef4e894.png)
