### ISSUE TITLE
VSCode unable to find installed Azure Function Core Tools

### ISSUE THREAD

**Issue by pfuerste** [microsoft/vscode-azurefunctions#3651]
I am trying to debug my Azure Function locally on Pop OS 22.04, VSCode is installed via Flatpak.
While "func start" in Terminal works like a charm, the task Attach to Python Functions task throws this error:

![image](https://user-images.githubusercontent.com/26963125/233655139-e149ac0f-9745-4b82-a2e4-66a2c245e503.png)

Func --version returns 4.0.5095.  I followed the standard guides to install core tools. 
Trying to install or update from the command palette throws this error: 
`4:04:07 PM: Error: Failed to install or update. Follow [these instructions](https://aka.ms/AAb9zn8) to install manually.`

**Comment by nturinski** [comment]
I'm not sure where VS Code is checking for the func cli tools on Pop OS. But, if you go into your VS Code settings, you should be able to manually set where the extension checks for the cli.

![image](https://user-images.githubusercontent.com/5290572/233717242-213f31ca-577d-4280-abd7-79444cf18201.png)

Could you try copying and pasting the bin/func path into here? I believe it will accept both relative and absolute paths.

**Comment by pfuerste** [comment]
It seems like it was looking...somewhere else for the cli.
Thanks for your help, setting the path to usr/bin/func resolved it!
