### ISSUE TITLE
'~\.swa\core-tools\v4\func.exe is not compatible with the version of Windows you're running'

### ISSUE THREAD

**Issue by utmostgames** [microsoft/vscode-azurefunctions#3655]
Sorry to come directly here, but I'm having difficulty getting the API to start `swa start src --api-location api`

VS Code on x64, Win 10; is there a different version I should grab than v4?

The API sample deploys and runs, I just cannot start locally to develop.

**Comment by Pahvi67** [comment]
I had the exact same issue just now, I tried the fix [here](https://github.com/Azure/azure-functions-core-tools/issues/1804#issuecomment-594990804) to no avail.

I had to manually download and extract the zip file from: `https://functionscdn.azureedge.net/public/4.0.5095/Azure.Functions.Cli.win-x64.4.0.5095.zip`
after that I could use Azure Functions properly.

**Comment by utmostgames** [comment]
Ah, thank you, I was beginning to think I was only person in the world! I may now try to see if this works in VSCode/JS-only; I ended up rebuilding within community VS2022/C# and it works there fine.
