### ISSUE TITLE
Azure Functions from VSCode not listed correctly

### ISSUE THREAD

**Issue by dfberry** [microsoft/vscode-azurefunctions#3658]
On a mac/m1.

I don't know if this is a general Azure extension issue or just Azure Functions extension issue. I created an Azure Function and deployed from GitHub Actions. I can use it/see it in the portal and from postman. I can't see it from VSCode's Azure Functions extension. 

I refreshed the Azure functions list in VScode as well as the subscription in VScode - neither updated. Not sure where the caching is happening.

![image](https://user-images.githubusercontent.com/1517008/234288605-24e8ecbf-0055-41d6-b816-5dbb2a2ebe81.png)

**Comment by nturinski** [comment]
Does reloading the entire VS Code window help? We have some funky behavior on our refresh right now.

**Comment by nturinski** [comment]
If that doesn't resolve the issue, could we see the JSON properties of the function app created via GitHub Actions? There may be some metadata that's causing us not to see it when we list the function apps.
