### ISSUE TITLE
"No HTTP triggers found" displays in Output after finishing the deployment of a v4 NodeJS app

### ISSUE THREAD

**Issue by uluhonolulu** [microsoft/vscode-azurefunctions#3659]
I'm deploying a v4 NodeJS function app using VSCode. No matter what I did, I couldn't get my HttpTrigger to show up. I was getting `No HTTP triggers found` in the deployment log with no error messages.

After removing lines from my .js file one by one, I realized that there was an error in my code that prevented it from reaching the `app.http(..)` line so the trigger was never added.

I would expect the error to show up in the log under the `Querying triggers...` line so that we could fix it quickly.

**Comment by ejizba** [comment]
> After removing lines from my .js file one by one, I realized that there was an error in my code that prevented it from reaching the app.http(..) line so the trigger was never added.

We do want to make these errors more obvious in v4, see https://github.com/Azure/azure-functions-nodejs-library/issues/85

> I would expect the error to show up in the log under the Querying triggers... line so that we could fix it quickly.

This would be slightly separate from my above linked issue and is not unique to NodeJS or v4. There's a difference between a failure during deploy and a failure when your app is running. I think VS Code only surfaces the former.

**Comment by uluhonolulu** [comment]
Agreed. So, ideally, we'd need both. Just seeing the error output of the entry point in the deployment log would be a huge time saver.

**Comment by pauld-msft** [comment]
@ejizba - The Oryx team is getting quite a bit of traction on an issue raised about this error message "No HTTP triggers found", which seems to originate from VSCode Azure Fn deployments, according to the issue description here: https://github.com/microsoft/Oryx/issues/1774

If this is an Azure Functions issue, not VSCode Azure Fn specific, could you point me in the right direction for where I could have the community open issues to get it addressed?

**Comment by ivaaan** [comment]
Experiencing the same issue. A NodeJS function was deployed and working perfectly for over a week, just made a small update (one line, changing a timestamp). Runs locally OK, but trying to redeploy (using the interface in VSCode), getting this: 

```
19:30:19 XCEED-API-NODE-2: Starting deployment...
19:30:19 XCEED-API-NODE-2: Creating zip package...
19:30:19 XCEED-API-NODE-2: Zip package size: 29 kB
19:30:24 XCEED-API-NODE-2: Updating submodules.
19:30:24 XCEED-API-NODE-2: Preparing deployment for commit id 'eab35c2a2f'.
19:30:25 XCEED-API-NODE-2: Skipping build. Project type: Run-From-Zip
19:30:25 XCEED-API-NODE-2: Skipping post build. Project type: Run-From-Zip
19:30:25 XCEED-API-NODE-2: Triggering recycle (preview mode disabled).
19:30:25 XCEED-API-NODE-2: Deployment successful.
19:30:37 XCEED-API-NODE-2: Started postDeployTask "npm install (functions)".
19:30:48 XCEED-API-NODE-2: Syncing triggers...
19:30:56 XCEED-API-NODE-2: Querying triggers...
19:30:59 XCEED-API-NODE-2: No HTTP triggers found.
```

**Comment by alexweininger** [comment]
@ivaaan

If I understand correctly, there's an error happening during startup (a runtime error) that is preventing the triggers from being registered. Currently this error message isn't being displayed, all we get is "No HTTP triggers found". https://github.com/Azure/azure-functions-nodejs-library/issues/85 should make it so the underlying error is displayed.

https://github.com/Azure/azure-functions-nodejs-library/issues/85 is merged and should be rolling out soon.

cc @ejizba

**Comment by ejizba** [comment]
Alex is correct with a few caveats. In this case the deploy technically succeeded, so VS Code won't show an error. The problem happens while your app is actually running, so the primary place to see the error will be in app insights.

VS Code could maybe show the error if they did something like @nturinski's detector work for web apps (https://github.com/microsoft/vscode-azureappservice/pull/1122). The platform team provided the detector api and I'm not sure it exists for function apps, though.

@alexweininger if I were you I would close and lock this issue. "No HTTP triggers found" is a very generic error and this issue could easily balloon out of control. I would suggest people file a new issue with their own repro steps. Here are some good repos to use:
- Node.js: https://github.com/Azure/azure-functions-nodejs-library/issues
- Python: https://github.com/Azure/azure-functions-python-worker/issues

**Comment by dzoba** [comment]
I am also encountering this issue with a v4 js app in VS Code.  Unfortunately this makes Azure functions unusable for me.

**Comment by Krucial92** [comment]
I am also encountering this issue all of a sudden as of the last 24 hours... my function apps including dev & prod now all of a sudden are not displaying any functions in the function app!!! My CI/CD pipelines are successfully running and deploying the application, however no functions are found. Yes I have the worker indexing feature flag set, etc.

Actually my prod function app stopped working a day ago and now it contains no functions when I did not touch it at all, no deployment was made, nothing. And I can see when looking at the function apps memory usage it all of a sudden dropped off randomly 24hrs ago. What on earth is going on here, did the runtime version have a minor version bump and this is causing an issue all of a sudden? Can we please get some eyes on this issue asap cc @ejizba @dzoba

**Comment by alexweininger** [comment]
@dzoba and @Krucial92, please file new issues and provide detailed information about your specific project and configurations. 

I'm closing and locking this issue to encourage other users to file new issues instead of commenting here.
