### ISSUE TITLE
ECONNREFUSED 127.0.0.1:9091 when debugging Python Azure Functions with storage queue triggers in VS Code

### ISSUE THREAD

**Issue by networthdata** [microsoft/vscode-azurefunctions#3660]
Does this occur consistently? Yes
Repro steps:

1. Open a Python Azure Function with VS Code. Function must have at least one storage queue trigger.
2. Hit the F5 button to attach to Python functions & debug.
3. ECONNREFUSED 127.0.0.1:9091 popup appears.

We have uninstalled and reinstalled VS Code.
We have downloaded and installed latest version of core tools 3.*.

We have not made any recent changes to our Azure infrastructure. 
This error occurs in functions in different resource groups. 
All functions are on linux consumption plans.
The error only occurs if the function has a storage queue trigger.

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.17134
Sandboxed: No
Core Tools Version:       3.0.4899 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.17.0.0

**Comment by alexweininger** [comment]
1. It seems like the `func: host start` task is not successfully launching. Are there any errors in the task output?

<img width="747" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/12476526/ce3c3dc9-59e7-46c9-a030-a401cb20b7da">

**Comment by alexweininger** [comment]
I was able to reproduce this error, but it's unlikely the issue I was having is the same as the original issue.

Anytime the `func: host start` task failed to execute, I got the "ECONNREFUSED 127.0.0.1:9091" error message. I fixed this by making sure the requirements were installed properly, and that my Storage Queue was able to connect.
