### ISSUE TITLE
`Internal error: No .NET worker runtimes found` when creating C# functions project

### ISSUE THREAD

**Issue by rwilliams3088** [microsoft/vscode-azurefunctions#3662]
I would like to create a local C# Function App via VSCode. Unfortunately, when I attempt to do so I get the error `You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.`

I am attempting to create the function in a WSL2 environment. I have used the scripted install of dotnet (https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) and setup the two environment variables via my .bashrc file (https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#set-environment-variables-system-wide). 

```
dotnet --list-sdks
6.0.408 [/home/rwilliams/.dotnet/sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.16 [/home/rwilliams/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.16 [/home/rwilliams/.dotnet/shared/Microsoft.NETCore.App]
```

**Comment by rwilliams3088** [comment]
Update: I changed how I installed the dotnet stuff. I used `sudo apt install dotnet-sdk-6.0` and `sudo apt install dotnet-runtime-6.0`. Now I get a different error when I attempt to create the project: `Internal error: No .NET worker runtimes found.`

**Comment by alexweininger** [comment]
Do you have attached to the same WSL2 environment that you installed .NET in? If you have VS Code open in Windows, not attached to WSL, then it will not find any .NET installations in WSL.

**Comment by kdubau** [comment]
I have the same problem, not using WSL at all. Just regular dotnet installed on Windows, VS Code insiders, and when I go create a a .NET function I get `Internal error: No .NET worker runtimes found.` ... are there any other logs I can grab for you?

**Comment by alexweininger** [comment]
The error `Internal error: No .NET worker runtimes found.` actually has nothing to do with local installations of .NET. I can reproduce this if I configure the "Azure Functions: Project Runtime" setting to `~3` in my global VS Code settings. It works if I leave the setting as the default value (blank) or set it to `~4`.

### How to update your project runtime to v4

1. Check your "Azure Functions: Project Runtime" setting. If set to `~3` by mistake, set it to blank (default) or `~4`.

<img width="717" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/12476526/b11a1a6b-146d-40bc-b756-17fd7726e9b7">

2. If the "Azure Functions: Project Runtime" setting isn't set, we'll check the installed version of [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools) and use the corresponding runtime. If your core tools is v3, upgrade to v4.

<img width="449" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/12476526/8cc3961c-8cbf-477a-85dc-69c3ae6e13cf">

### More info and context: 

We fetch the latest function templates from a feed based on the project runtime (`~1`, `~2`, `~3`, `~4`). For some reason the latest v3 .NET templates (3.47.1) do not have .NET runtimes associated with them (there are two but they are both hidden). It is recommended to change your project runtime to v4, and use the v4 templates.

<img width="853" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/12476526/73f5fa60-4e98-4001-877e-22cbc9f5a20f">

https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?pivots=programming-language-csharp&tabs=v4#languages

---

### Potential improvements

1. We could make the error message a lot friendlier here, especially considering a lot of people are running into this.
2. We should tell the user which project runtime we found and where came it from (workspace setting, global setting, cli, or default version).
3. It doesn't look like we ever respect the workspace project runtime setting. This is probably a bug.
4. If all the runtimes are marked as hidden, maybe we should just show them anyway?
