### ISSUE TITLE
Cannot deploy v4 function app

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-azurefunctions#3663]
Type: <b>Bug</b>

1. Open an empty folder in VS Code
2. Use the extension command: "Create function..." to create an HttpTrigger function using v4 (preview)
3. Use "Create function app in Azure..." to create a new app in azure to deploy the created function
4. In the azure view in the side bar, right click the function app and deploy

:bug: => It will say it completed successfully but "No HTTP triggers found"

Repeating the exact steps but choosing v3 works as expected.

Extension version: 1.10.5
VS Code version: Code - Insiders 1.78.0-insider (657bb89984f37b810b250955570593cde0cd62eb, 2023-05-02T11:21:33.752Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.71GB free)|
|Process Argv|--crash-reporter-id 6da3720d-fb86-47a1-91f3-ebd9f5fa64fd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ejizba** [comment]
Did you set the app setting `AzureWebJobsFeatureFlags` to `EnableWorkerIndexing`? It's [required](https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-upgrade-v4?tabs=azure-cli-set-indexing-flag%2Cv4#considerations) during preview.

The VS Code extension has a fix to automatically add it for v4 apps during deploy, which has been merged but not released yet: https://github.com/microsoft/vscode-azurefunctions/issues/3559

**Comment by MicroFish91** [comment]
We will notify you when we release the update, closing unless you have any further related issues, thank you
