### ISSUE TITLE
Unable to debug dotnet functions on latest vscode

### ISSUE THREAD

**Issue by sanchez** [microsoft/vscode-azurefunctions#3664]
Hi my vscode just updated to latest stable and now I can no longer debug my Azure Function.

I am using in-process on dotnet 6.

I get an error message of `Failed to find dependency "windows-process-tree"` however the application has started successfully and continues to run, it just looks like the debugging session doesn't attach.

Cheers,
Daniel

**Comment by tridoann** [comment]
Hi Daniel

I just got this issue and I downgraded VS Code to version 1.77.0, now it works.

Thanks,
Tri Doan.

**Comment by emeraldleaf** [comment]
I am having this issue also.

**Comment by MicroFish91** [comment]
Some additional context: https://github.com/microsoft/vscode-azurefunctions/issues/2747

**Comment by stumpykilo** [comment]
I have same issue (getting `Failed to find dependency "windows-process-tree"` and not attaching). Azure Function plugin v1.10.5 and VS Code 1.78.0 running on Windows 11.

**Comment by hhubik** [comment]
Downgrade to version 1.77.3 of VS Code fixed it for me.

https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode

There are mulitple download files for Windows for this VS Code version.  Check `VS Code Help > About` and pick the one that matches your current installation.

**Comment by nickidw** [comment]
> Hi my vscode just updated to latest stable and now I can no longer debug my Azure Function.
> 
> I am using in-process on dotnet 6.
> 
> I get an error message of `Failed to find dependency "windows-process-tree"` however the application has started successfully and continues to run, it just looks like the debugging session doesn't attach.
> 
> Cheers, Daniel

Get this exact same error and experience.

**Comment by adamrybak** [comment]
Downgrading to 1.77.3 has fixed the issue for me. There are no major features in 1.78.* that I am missing so I can live with this workaround for the time being.

**Comment by alexweininger** [comment]
Glad that downgrading to 1.77.* is working. We are actively working on a fix for this issue.

**Comment by nturinski** [comment]
The fix for this should be released as v1.10.6!
