### ISSUE TITLE
Error during startup operation

### ISSUE THREAD

**Issue by DomenicoFasano** [microsoft/vscode-azurefunctions#3665]
Hi, I have the following issue when tryng to launch locally a set of python functions:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/54447259/236243828-f406d397-36a2-4f4a-b663-f4d415083221.png">

What can I do? Thanks in advance

**Comment by DomenicoFasano** [comment]
I've solved it reinstalling the core tools

**Comment by alexweininger** [comment]
Closing since the issue has been resolved. Thank you.
