### ISSUE TITLE
The streaming log hangs on "Connecting to log stream..." for a Windows function app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3675]
**OS:** All
**Build Version:** 20230514.1

**Repro Steps:**
1. Create and open a JavaScript project.
2. Create a Node Windows function app.
4. Deploy the project to the Node function app.
5. Right click the above function app -> Click "Start Streaming Logs".
6. Check whether the streaming log doesn't hang on "Connecting to log stream...".

**Expect:**
The streaming log doesn't hang on "Connecting to log stream...".

**Actual:**
The streaming log hangs on "Connecting to log stream...".
<img width="943" alt="Screenshot 2023-05-15 at 17 33 06" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/e1b0b4c3-5eb6-44b2-8a0f-7a02ee1bc045">

**More Info:**

1. This issue doesn't reproduce for the Node16 Windows function app deployed a Javascript V3 project.
2. This issue also reproduces for a Windows function deployed C#/PowerShell project.

**Comment by DmitriyKhirniy** [comment]
Have the save issue right now. 
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azuretools/pull/1548
