### ISSUE TITLE
Show warning that host v3 is EOL when creating an app

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#3676]
If you create an app with "azureFunctions.projectRuntime" set to "~3" in your VS Code settings, this is what you see when you create an app (at least for Node.js):
<img width="696" alt="Screenshot 2023-05-15 at 11 00 03 AM" src="https://github.com/microsoft/vscode-azurefunctions/assets/11282622/78e68b82-ebc7-41a3-98b9-f3ea232e0ea9">

And if you change the runtime this is what you see:
<img width="634" alt="Screenshot 2023-05-15 at 11 00 09 AM" src="https://github.com/microsoft/vscode-azurefunctions/assets/11282622/964a69d7-7679-474a-90de-794ef45c29d4">

A few things:
1. The first prompt should maybe show a warning that their host version is EOL, especially since we will probably remove Node 14 from the stacks api at some undecided point in the future. Aka you might want to check `if (stacks.length === 0) <show warning that you have to update your runtime version>`
2. The second prompt should show `EOL` on v2 and v3 and maybe just hide them altogether like v1 idk

**Comment by alexweininger** [comment]
Similar issue for C#: https://github.com/microsoft/vscode-azurefunctions/issues/3662

**Comment by MadhuraBharadwaj-MSFT** [comment]
@nturinski - can we have the "Learn More" link for the host v2/v3 warnings point to this upgrade doc? https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4

Thanks!
