### ISSUE TITLE
An error occurs when selecting the "Preview template"

### ISSUE THREAD

**Issue by v-jennazheng** [microsoft/vscode-azurefunctions#3682]
**OS:** All
**Build Version:** [20230517.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=62029&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Repro Steps:**

1. Create and open a Python (Programming Model V2) project in VS Code.
2. F1 -> "Azure Functions: Create Function..." -> Select a template -> Select "Preview template".
3. Check whether no error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/124032089/2d204a8a-ad44-4781-bc7a-dfce3ff946b2)

**Expect:**
No error occurs.

**Comment by v-xinda** [comment]
Verified this issue on the build 20230523.2, it doesn't reproduce for now. So close it.
