### ISSUE TITLE
An error occurs when debugging a Python V2 project created with Azure Service Bus Topic trigger template

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3689]
**OS:** All
**Build Version:** 20230518.5

**Repro Steps:**
1. Create a Python V2 Programming Model project with Azure Service Bus Topic trigger template function.
2. Type the "TOPIC_NAME" to the property `topic_name` -> F5.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error `Exception: TypeError: service_bus_topic_trigger() missing 1 required positional argument: 'subscription_name'` occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/56efef1e-6834-4c22-b622-bdb534561869)

**More Info:**
This issue can be fixed after adding `subscription_name="SUBSCRIPTION_NAME"` in the `function_app.py` file.

**Comment by v-xinda** [comment]
Verified this issue on the build 20230523.2. 
An error occurs after creating a Python V2 Programming Model project with Azure Service Bus Topic trigger template function.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/11557d71-729d-469c-915f-3a4b98bbb4ba)

**Comment by v-xinda** [comment]
Verified this issue on the latest main branch build, it still reproduces. So reopen it.

**Comment by alexweininger** [comment]
@v-xinda Can you share your host.json file?

**Comment by v-xinda** [comment]
@alexweininger  The details in the `host.json` file as below:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
```
