### ISSUE TITLE
There are four warnings in function_app.py file after creating a Python V2 Programming Model project with Azure Cosmos DB trigger template function

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3690]
**OS:** All
**Build Version:** 20230518.5

**Repro Steps:**

1. Create and open a Python V2 Programming Model project with Azure Cosmos DB trigger template function in VS Code.
2. Check PROBLEMS view.

**Expect:**
No error occurs.

**Actual:**
There are four warnings in function_app.py file.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/1c180545-2ae9-4d03-9bd1-77cda9c3d71a)

**More Info:**
Fail to debug the project after editing the function_app.py file with following code.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/7feecef1-2d47-4c00-99c7-a47646adc557)

Error:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/bca9cdf6-1bb2-4e4b-b13c-9dc7a0a784cc)

**Comment by v-xinda** [comment]
Verified this issue on the build 20230523.2, it doesn't reproduce for now. So close it.
