### ISSUE TITLE
[Suggestion] It would be better to keep "Authorization level" consistently when creating python and python v2 projects

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3695]
**OS:** All
**Build Version:** 20230523.2

**Repro Steps:**

1. F1 -> Click "Azure Functions: Create New Project..." -> Select a new folder -> Select "Python (Programming Model V2)" language -> Select an existing Python interpreter -> Select "HTTP trigger" template -> Enter the default function name.
2. Check the Authorization level view.

**Actual:**
The authorization levels are capitalized words.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/5ff0f947-66bb-4b5f-8ddf-55f591c82044)

**Suggestion:**
It would be better to keep "Authorization level" consistently when creating python and python v2 projects.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/eafce943-944c-4c0d-95a9-23135bd73db4)

**More Info:**
The authorization levels are lowercase words when creating another language projects.

**Comment by alexweininger** [comment]
This is by design. Controlled upstream.
