### ISSUE TITLE
Failed to deploy function app through Azure Functions Extension in vs code

### ISSUE THREAD

**Issue by sjagadee** [microsoft/vscode-azurefunctions#3703]
Does this occur consistently? No, it started happening from a day
Repro steps:

1. Deploy function app from vs code's Azure functions extension, by right clicking on the project folder and clicked on deploy to Function App.. 
2. Then here is what I got 

7:44:58 AM azfn-eus2-dev-cmsnj-ConversionPipeline: Starting deployment...
7:44:58 AM azfn-eus2-dev-cmsnj-ConversionPipeline: Creating zip package...
7:50:23 AM: Error: request to https://<url>.appserviceenvironment.net/api/zipdeploy?author=ms-azuretools-vscode&deployer=ms-azuretools-vscode&isAsync=true&trackDeploymentId=true failed, reason: read ECONNRESET

 Azure functions extension version: v1.11.0

Tried by downgrading the above version 1.10.5 still not working
Used to deploy Node.js function apps
Version: 1.11.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

**Comment by MicroFish91** [comment]
Sometimes the Azure services will go down temporarily.  Could you confirm if this still reproducing?
