### ISSUE TITLE
Investigate why TypeScript Azure Cosmos DB trigger is missing from 4.4.0 templates

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurefunctions#3711]
Upstream issue: https://github.com/Azure/azure-functions-templates/issues/1391

**Comment by nturinski** [comment]
Tracking https://github.com/Azure/azure-functions-templates/pull/1401

**Comment by nturinski** [comment]
Tracked issue is closed and reverting hard-coded template version here: https://github.com/microsoft/vscode-azurefunctions/issues/3711
