### ISSUE TITLE
An error occurs in workspace view when debugging a C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3715]
**OS:** Win 10
**Build Version:** 20230614.3

**Repro Steps:**
1. Create a C# .NET 7 project with "HttpTrigger" template.
2. Debug this project.
3. Navigate to workspace view -> Expand the Functions node.
4. Check whether there is a function "HttpTrigger".

**Expect:**
There is a function "HttpTrigger" in workspace view.

**Actual:**
An error occurs in workspace view.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/1127bea4-3fd4-4da6-ac08-39e5c1b86750)

**More Info:**
The function "HttpTrigger" shows in workspace view when debugging a TypeScript project, but the same error occurs when executing "Execute Function Now..." action for it.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/dc1074d3-a8a8-4208-b1c0-1d2ff8fdbc00)

**Comment by v-ruizh** [comment]
This issue still reproduces on the latest main branch build 20230629.1. It also reproduces when debugging Python V2/Node V4 projects.

**Comment by alexweininger** [comment]
Fixed by #3757
