### ISSUE TITLE
Fail to execute the "Execute Function Now..." action for the deployed function

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3716]
**OS:** Win 10
**Build Version:** 20230614.4

**Repro Steps:**
1. Create a JavaScript project with "HttpTrigger" template.
2. Deploy this project to a Node Function App.
3. Expand the above Function App -> Execute "Execute Function Now..." action for the "HttpTrigger" function with the default value.
4. Check whether succeeds to execute the "Execute Function Now..." action or not.

**Expect:**
Succeed to execute the "Execute Function Now..." action.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/ecc50585-ca5f-43eb-8a0f-4496728cd0f1)

**Actual:**
Fail to execute the "Execute Function Now..." action with an error.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/5d5aae6d-e5c4-4108-bc4f-0f5c1b78f8b2)

**More Info:**
1. This issue also reproduces for other runtime projects.
2. This issue does not reproduce on the current released extension v1.11.0.

**Comment by alexweininger** [comment]
Does this still reproduce? We think #3727 might fix this.

**Comment by v-ruizh** [comment]
This issue still reproduces on the latest main branch build 20230629.1.
