### ISSUE TITLE
The breakpoint is not hit when debugging a C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3717]
**OS:** Win 10
**Build Version:** 20230614.4

**Repro Steps:**
1. Create a C# .NET 7 project with "HttpTrigger" template.
2. Set a breakpoint.
3. Debug this project.
4. Copy the function url -> Execute "curl <function url>" command in a new terminal.
5. Check whether the breakpoint is hit or not.

**Expect:**
The breakpoint is hit.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/6858fd5a-9a11-4df5-93fc-92cc4e8884df)

**Actual:**
The breakpoint is not hit.

**More Info:**
1. An error occurs after waiting for a while during debugging C# project.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/9f608aab-e86f-4b74-b6b2-b274e9b5a2c8)
2. This issue does not reproduce on the current released extension v1.11.0.

**Comment by nturinski** [comment]
Related: https://github.com/microsoft/vscode-azurefunctions/issues/3709
