### ISSUE TITLE
Failed to connect. Make sure your project is [running locally]

### ISSUE THREAD

**Issue by iww9733** [microsoft/vscode-azurefunctions#3722]
Action: azureFunctions.executeFunction
Error type: Error
Error Message: Failed to connect. Make sure your project is [running locally](redacted:url

Version: 1.11.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

I've followed steps on https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-configuration on my work laptop and received this error when running a http triggered function with no changes from myself. 
I've also followed these steps on a personal laptop with no problems.
<summary>Call Stack</summary>

```
extension.bundle.js:2:5466110extension.bundle.js:2:5466110
rejected extension.bundle.js:2:5464211
```

</details>

**Comment by nturinski** [comment]
Hi @iww9733. 

The error seems to indicate that it can't reach your localhost. Since you're able to get it to work on your personal laptop, then maybe your work laptop has a proxy or firewall issue? Do you know if your localhost is blocked?
