### ISSUE TITLE
Slow loading time when listing function apps 

### ISSUE THREAD

**Issue by olegade** [microsoft/vscode-azurefunctions#3723]
Hi all.

We have been experiencing issues with the listing of Azure Functions in vs-code for the last couple of weeks. 

When we attempt to deploy our code to Azure Functions, the process to list all of our function apps from Azure is significantly slow, taking around 45-50 seconds. This is considerably longer than expected and previous experiences. 

Any ideas on what could be wrong?

**Comment by alexweininger** [comment]
Hi @olegade, could you see if this build of the extension mitigates the performance issues you're experiencing?

[vscode-azurefunctions-1.11.1-alpha.0.vsix.zip](https://github.com/microsoft/vscode-azurefunctions/files/11851493/vscode-azurefunctions-1.11.1-alpha.0.vsix.zip)

Steps to install extension development build:
1. Download the linked zip file and extract the extension .VSIX
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

**Comment by olegade** [comment]
Thanks a lot @alexweininger. I haven't been able to test your alpha version, but I can see it has been merged into the main branch.
