### ISSUE TITLE
Internal error: Expected value to be neither null nor undefined

### ISSUE THREAD

**Issue by el-protoman** [microsoft/vscode-azurefunctions#3725]
1. Right  click folder to deploy to function app

Action: azureFunctions.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined

Version: 1.11.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:2:4154216
extension.bundle.js:2:5438530extension.bundle.js:2:5438530
fulfilled extension.bundle.js:2:5437739
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting this! The current workaround would be to use the Azure view and deploy from there, but we'll investigate the fix for this.
