### ISSUE TITLE
azure function cant find local files after updating and deploying to azure

### ISSUE THREAD

**Issue by shizahammad** [microsoft/vscode-azurefunctions#3730]
This issue of mine is similar to the one mentioned here but I couldn't comment on it https://github.com/microsoft/vscode-azurefunctions/issues/1439
I tried the solution given I'm still getting an error I had run the same code before it was working fine a few days ago but today its not running now it runs locally though this is the folder structure in my vscode editor. 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/16020315/fa5021c8-46ea-4675-83eb-9fb711ac8a85)
I'm trying to populate a word document using one of the triggers and for that I added a folder called Automations files which had sub -directories Templates and Drawings. the Templates had 3 word documents and the other one was to remain empty. When I ran the code it was giving this error:

Result: Failure Exception: FileNotFoundError: [Errno 2] No such file or directory: 'Automation_files\\Templates' Stack: File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 752, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/PopulateMicrosoftWord/__init__.py", line 45, in main os.listdir(r"Automation_files\Templates")]

the solution showed that the person moved the csv file inside the function folder so i did that too and the rest but its still giving an error:
Result: Failure Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/site/wwwroot/PopulateMicrosoftWord/Automation_files/Drawings/GMZ-2023-1234-RS-CA-001-01.docx' Stack: File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 752, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/PopulateMicrosoftWord/__init__.py", line 60, in main document.write(fr"{files_path}/Drawings/{f_calc_num}{'.docx'}") File "/home/site/wwwroot/.python_packages/lib/site-packages/mailmerge.py", line 120, in write with ZipFile(file, 'w', ZIP_DEFLATED) as output: File "/usr/local/lib/python3.10/zipfile.py", line 1251, in __init__ self.fp = io.open(file, filemode)
I'm using python language 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/16020315/8301af35-685b-439d-8ce0-9f3eea5ef498)

**Comment by alexweininger** [comment]
It looks like you're deploying to a Linux based Function App, however the filepath is using backslashes (for Windows). Make sure the path you use to lookup the file works on Linux and Windows based operating systems.
