### ISSUE TITLE
An error occurs when creating a function app from workspaces view

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3731]
**OS:** All
**Build Version:** 20230626.10

**Repro Steps:**

1. Sign out.
2. Navigate to "WORKSPACE" view -> Click "Azure Functions" button -> Select "Create Function App in Azure...".
3. Check whether the next step is "Sign in" or not.

**Expect:**
The next step is "Sign in".
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/ca5cf789-d44e-4395-8693-fefc8db35d1d)

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/2942b818-cb19-4f6a-97f5-114a64b69838)

**More Info:**
The next step is "Sign in" when create static web app from workspaces view.

**Comment by alexweininger** [comment]
This also happens when signed in but a workspace item has been selected.
