### ISSUE TITLE
There is no step "Choose organization" when changing deployment source to "GitHub"

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3734]
**OS:** All
**Build Version:** 20230629.1
**Regression:** Previous Release

**Repro Steps:**

1. Right click a function app -> Click "Configure Deployment Source..." -> Click "GitHub".
2. Check whether the next step is "Choose organization".

**Expect:**
The next step is "Choose organization".
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/9d51e9fe-2496-43bc-aa3d-3381d6a0731b)

**Actual:**
Pop up a notification of successful update to "GitHub", but doesn't allow to choose organization.

**More Info:**
1. The "GitHub" label doesn't appear next to "Deployments" node after changing deployment source to "GitHub".
2. The "Current source" is "None" when executing "Configure Deployment Source..." command again.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/f9489196-f223-46ae-89c7-058090aef0a0)

**Comment by alexweininger** [comment]
Related to https://github.com/microsoft/vscode-azuretools/pull/1450
