### ISSUE TITLE
Storage account with ZRS replication not found

### ISSUE THREAD

**Issue by SalvoRusso8** [microsoft/vscode-azurefunctions#3735]
OS: All
Version: 1.11.0

Repro Steps:
I have some storage accounts StorageV2 (general purpose v2) with Standard Performance and different replication

1. Create Function App in Azure... (Advanced)
2. Written unique name for the function app
3. Selected any runtime stack
4. Selected any OS
5. Selected resource group in which my storage account with ZRS replication enabled is
6. Selected any hosting plan
7. My storage accounts with ZRS replication enabled are not present. Only storage accounts with LRS replication and RA-GRS replication are listed.

Expect:
On step 7, I expect to see all my storage accounts, included the ones with ZRS replication 

Actual:
The storage accounts with ZRS replication are not listed by vsc. Doing the procedure through the Azure portal is successful even with the storage account not listed by vsc.

**Comment by alexweininger** [comment]
Interesting, thank you for the detailed repro steps. Do you know if you've been able to see the storage accounts with ZRS replication enabled in VS Code before?

**Comment by SalvoRusso8** [comment]
> Interesting, thank you for the detailed repro steps. Do you know if you've been able to see the storage accounts with ZRS replication enabled in VS Code before?

Hi.
It's the first time I'm using this extension, so I can't answer to your question.

**Comment by alexweininger** [comment]
> Hi. It's the first time I'm using this extension, so I can't answer to your question.

No worries. Thanks for bringing this to our attention. I hope to get this fixed and released soon.

**Comment by alexweininger** [comment]
@SalvoRusso8 ZRS support has been released in version 1.12.0 of the extension. 🎉 

https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.12.0
