### ISSUE TITLE
An error occurs after clicking "Create New Project..." from Workspace view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3744]
**OS:** All
**Build Version:** 20230710.14

**Repro Steps:**
1. Open a project in VSCode.
2. Navigate to Workspace view -> Expand "Local Project".
3. Click "Azure Functions" icon in Workspace view -> Click "Create New Project...".
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
<img width="455" alt="Screenshot 2023-07-11 at 13 57 51" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/7ab577ff-ed76-41f8-a8a6-af8fc1020ec6">

**Comment by nturinski** [comment]
I've been able to reproduce this as well.
