### ISSUE TITLE
[Unstable] An error occurs after deploying to one function app several times

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3751]
**OS:** All
**Build Version:** 20230711.5

**Repro Steps:**
1. Create a function app -> Deploy project to it several times.
2. Check whether succeeds to deploy project to function app.

**Expect:**
Succeed to deploy project to function app.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/ea9b4d92-eb09-488f-a975-19e6c2addae7)

**More Info:**
This issue is **unstable** and it reproduces after deploying to one function app **several times**.

**Comment by MicroFish91** [comment]
This is fairly edge-case with low impact, so will mark this as a won't fix.
