### ISSUE TITLE
Executing a local service bus topic trigger gives "Unexpected status code: 400" error with JSON request body

### ISSUE THREAD

**Issue by TechTrailblazerX** [microsoft/vscode-azurefunctions#3762]
## Issue
Passing in valid JSON into the request body of a service bus topic trigger results in a "Unexpected status code: 400" error, and the function does not execute.
This regression appeared in version `v1.12.0`. When downgrading to `v1.11.0`, it does work as expected.

## Expected Behavior
When valid a valid JSON payload is entered in the service bus message payload prompt, the payload should be passed as a deserialized object to the service bus message trigger function argument. 
Note that passing the object in single or double quotes (for example `'{"key":"value"}'` instead of `{"key":"value"}` does work, but the json is then not parsed.

## Steps to Reproduce
1. Create function
2. Select "Azure Service Bus Topic trigger"
3. Select defaults for remaining prompts
4. Run func start
5. Execute function
6. Select created function
7. Enter valid JSON in request body prompt (`{"key":"value"}`)
8. Receive error

**Comment by alexweininger** [comment]
Thank you for bringing this to our attention. Looks like this was caused by #3758.

**Comment by alexweininger** [comment]
@TechTrailblazerX fix has been released in v1.12.1
