### ISSUE TITLE
Turn ON full monitoring experience for Java Function Apps by default

### ISSUE THREAD

**Issue by MadhuraBharadwaj-MSFT** [microsoft/vscode-azurefunctions#3766]
We recently did a GA release for [Application Insights Distributed tracing support for Java Function Apps](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fupdates%2Fga-application-insights-distributed-tracing-support-for-java-function-apps%2F&data=05%7C01%7CMadhura.Bharadwaj%40microsoft.com%7C7e30b1c572f54702c57b08db88a09ad5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253995602086306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rDpE%2FhyKemL929BYEuhVEWEdNkzSyjHN9dIuwuP15wA%3D&reserved=0). Currently this is an opt-in feature for users. We’d like to turn this feature On-by-default for all new Java Function Apps that get created.
 
Business Impact: This will make it very easy for customers to observe their Functions and can benefit from day zero observability. Customers already have basic monitoring provided by the function host. With the Java agent they will gain full APM visibility with auto-collection and correlation of dependencies, logs, and metrics from popular libraries and Azure SDKs. We would like to have Java worker monitoring to be "on by default" for non-consumption SKUs as there is no cold start time implications for these SKUs. We need Java worker monitoring to be enabled regardless of how the function is created (i.e., AZ CLI, VSCode, portal, etc.).

Status: Azure portal will have this feature on-by-default in the next sprint.

Ask: We need this feature to be on-by-default on VSCode as well.

**Comment by MadhuraBharadwaj-MSFT** [comment]
cc @abinetabate @ahmelsayed @nturinski

**Comment by abinetabate** [comment]
[like]  Abinet Abate reacted to your message:
________________________________

**Comment by alexweininger** [comment]
This has been released in [v1.13.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.13.2) of the extension.
