### ISSUE TITLE
Creating Function App from VS Code not working "Failed to get latest templates: "net472" is not supported for Azure Functions version "~1".

### ISSUE THREAD

**Issue by hivyas** [microsoft/vscode-azurefunctions#3772]
Hi there, 

I am trying to set up local development for my Azure Function on VS Code but I am getting the following error: 
Failed to get latest templates: "net472" is not supported for Azure Functions version "~1".

I am running v1.12.1 for the Azure Functions extension on VS Code. I also tried v1.12.0.

**Comment by alexweininger** [comment]
It looks like you need to update "Azure Functions: Project Runtime" setting. The setting id is `azureFunctions.projectRuntime`. `~4` is the recommended runtime version for functions in all languages. 

https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions

**Comment by hivyas** [comment]
Hey there, thanks for the response. Looks like I am running on Runtime version 4.23.0.20886 and still running into this issue

**Comment by hivyas** [comment]
Hi there,

Sorry for late response.

I verified that my project runtime setting is ~4:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/61890270/923e5be9-0a76-4aa8-910c-4a3586fc3e18)

However, I am still seeing the same error:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/61890270/bd99fb4c-5c10-45bc-b85e-ebe74e25d276)

I'm not sure why VS Code is not picking up the v4 runtime version even though I set it to that.
