### ISSUE TITLE
Inside VS-Code -> AzureTab -> Workspace -> Local Project showing Error: Unable to detect project file.

### ISSUE THREAD

**Issue by sharma-shiv** [microsoft/vscode-azurefunctions#3773]
Does this occur consistently? Yes
Repro steps: 

1. Started Local Emulator Blob Container
2. run "func start" command
3. function seems to run in terminal but in Local Project area Error is coming "Error: Unable to detect project file."

![image](https://github.com/microsoft/vscode-azurefunctions/assets/20300177/f9d3f2ea-99a2-4542-bc3b-33f5104b3777)

Version: 1.12.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

**Comment by alexweininger** [comment]
Try opening a workspace with only a single Functions project in it. Currently this error is thrown when the Functions extension sees two `.csproj` files.

**Comment by sharma-shiv** [comment]
Thanks. It worked for me.
