### ISSUE TITLE
The deployed project doesn't show under the 'Files' node after deploying a project to function app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3774]
**OS:** Win10
**Build Version:** 20230720.10
**Regression:** Preview Release

**Repro Steps:**

1. Create a Linux function app with Consumption Plan. 
2. Deploy a project to it.
3. Expand the 'Files' node.
4. Check whether the deployed project shows under the 'Files' node.

**Expect:**
The deployed project shows under the 'Files' node.

**Actual:**
The deployed project doesn't show under the 'Files' node.

**More Info:**
This issue also reproduces when deploying to a basic Function App.

**Comment by alexweininger** [comment]
Should be fixed by https://github.com/microsoft/vscode-azuretools/pull/1547
