### ISSUE TITLE
Visual studio code is not loading the azure resources for subscription

### ISSUE THREAD

**Issue by Sagarthore11** [microsoft/vscode-azurefunctions#3776]
Hello Team,

We have Visual Studio code, and from that, when we are trying to load the Azure resources, it keeps loading and nothing is showing over here. Also, we noticed that the certificate has expired.

I have attached the screen shot for reference.

![image](https://github.com/microsoft/vscode-azurefunctions/assets/118530325/77971d13-d5bd-481b-ab24-8fba3631b9e2)

Also, please note that it was working fine until January 2023.
We tried reinstalling the Visual Studio code, upgrading and degrading the Azure account and Azure Resources version, but still had the same issue.

We don't have any VPN, and another team member also tried the same thing, but he is also having the same issue.

VS CODE version: 1.80.1

Thank you for the help in advance

**Comment by nturinski** [comment]
I noticed that subscription says that it is a sandbox subscription. Are you able to create a new sandbox and try to sign in with that?

**Comment by Sagarthore11** [comment]
Hello @nturinski ,

Thank you so much for your response.

We added "http.systemCertificates": false in the VS Code settings.json file, and following that, we reloaded the VS Code, and it started working fine now.

Regards,
Sagar
