### ISSUE TITLE
Function is not deploying from VS code  with Functions and App files

### ISSUE THREAD

**Issue by DharshiniThil** [microsoft/vscode-azurefunctions#3777]
While deploying the Function app with some modification to already deployed  Function app, It is deploying but in output logs it shows
`11:30:22 AM xxxxxx: Syncing triggers...`
`11:30:29 AM xxxxxx: Querying triggers...`
`11:30:36 AM xxxxxx: No HTTP triggers found.`

 And also Function is erased from the console and not updating it. But it is visible in Workspace(local) of VS code. 

But If I create new function app and deploy it there it is deploying well.   

Kindly guide me where the issue is. whether the storage account or in visual studio code or in Function app.

**Comment by nturinski** [comment]
Hi there, sorry you're running into issues.

Are there any more logs during the deployment from the output channel that you could share with us?

**Comment by DharshiniThil** [comment]
Hi,

Thanks for your response. This issue is resolved now. I was using CONTAINER_NAME variable in app setting. Since it is reserved setting, I cannot add that manually. Because of that the function is not deploying. I resolved it by renaming that variable.
