### ISSUE TITLE
An error message shows in "Azure Functions" output panel when creating a C#/Node.js V3/Python/PowerShell Function project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3778]
**OS:** Win10
**Build Version:** 20230730.1

**Repro Steps:**
1. Create a C# .NET 7 project with HttpTrigger template.
2. Navigate to "Azure Functions" output panel.
3. Check whether no error message shows in "Azure Functions" output panel.

**Expect:**
No error message shows in "Azure Functions" output panel.

**Actual:**
An error message "Failed to get latest templates: Cannot read properties of undefined (reading 'resources')" shows in "Azure Functions" output panel.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/ce59b9c3-4472-451b-8640-13e724cd2fe0)

**More Info:**
1. This issue also reproduces when creating Node.js V3/Python/PowerShell projects.
2. This issue does not reproduce when creating Node.js V4/Python V2 projects.

**Comment by nturinski** [comment]
This is due to an external issue. I filed an issue on the templates repository [here](https://github.com/Azure/azure-functions-templates/issues/1434).

**Comment by nturinski** [comment]
It was fixed by the feed, but we also added our own logic to not completely rely on the template version from the bundle feed.
