### ISSUE TITLE
Unexpected status code: 401 when executing azure functions from vscode

### ISSUE THREAD

**Issue by MVRingsted** [microsoft/vscode-azurefunctions#3787]
Does this occur consistently? Yes
Repro steps:

1. When I manually try to invoke my deployed azure functions via vscode Azure extension, I simply gets this error and the function in not invoked. The error occurs instantly and happens for all of my azure functions

Action: azureFunctions.executeFunction
Error type: 401
Error Message: Unexpected status code: 401

Version: 1.12.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.80.2
Language: en

<details>
<summary>Call Stack</summary>

```
StatusCodePolicy.<anonymous> extension.bundle.js:2:3698275
fulfilled extension.bundle.js:2:3693254
```

</details>

**Comment by alexweininger** [comment]
What type of Azure Functions are they? HTTP Triggers?

**Comment by MVRingsted** [comment]
Its timer triggered azure functions. The Error happens when i right click the function i want to trigger in the azure extension resource overview in vscode and click “execute function now”.

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Alex Weininger ***@***.***>
Sendt: Friday, August 4, 2023 7:52:31 PM
Til: microsoft/vscode-azurefunctions ***@***.***>
Cc: Mads Vibe Ringsted ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode-azurefunctions] Unexpected status code: 401 when executing azure functions from vscode (Issue #3787)


What type of Azure Functions are they? HTTP Triggers?

**Comment by alexweininger** [comment]
Thanks for that info. If it's easy to test, does this reproduce for locally running functions as well?

**Comment by MVRingsted** [comment]
No its specific to that method of invocation for deployed functions. When i do it for my locally running function it works. And for the deployed functions the “run/tests” http call via the portal also works

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Alex Weininger ***@***.***>
Sendt: Friday, August 4, 2023 8:19:45 PM
Til: microsoft/vscode-azurefunctions ***@***.***>
Cc: Mads Vibe Ringsted ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode-azurefunctions] Unexpected status code: 401 when executing azure functions from vscode (Issue #3787)


Thanks for that info. If it's easy to test, does this reproduce for locally running functions as well?
