### ISSUE TITLE
No error validation prompts when creating a new slot with an existing name

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3792]
**OS:** All
**Build Version:** 20230808.1
**Regression:** previous release (0.11.0)

**Repro Steps:**

1. Create a slot named "test1" for one function app.
2. F1 -> Azure Functions: Create Slot... -> Select the above function app -> Enter "test1".
3. Check whether an error validation prompts.

**Expect:**
An error validation prompts.
<img width="443" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/107091828/06bcee86-fdd5-41eb-9464-4a5c4b7d4071">

**Actual:**
1. No error verification prompts  
2. Pop up "Successful created slot" notification.
<img width="343" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/107091828/f0cfd309-b0bc-4271-b4f7-82653bb2d8fb">

**More Info:**
1. This issue doesn't reproduce when creating a new slot with an existing name on the portal.
<img width="166" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/107091828/b483823d-e20e-44d0-ba0a-781bd6b2ba50">

2. This issue doesn't reproduce on the released Functions extension v1.11.0.

**Comment by alexweininger** [comment]
Fixed by #3800
