### ISSUE TITLE
"No log found" error occurs when deploying

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3793]
**OS:** All
**Build Version:** 20230808.1

**Repro Steps:**

1. Create a Premium Linux function app.
2. Create a JavaScript project with HttpTrigger function of Node V4 Programming Model.
3. Deploy the JavaScript project to the Premium Linux function app.
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
<img width="458" alt="Screenshot 2023-08-09 at 17 12 17" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/7d28347a-9a2a-4c5c-8471-69956bef2d20">

**More Info:**

1. This issue doesn't reproduce for the Linux function app created with Consumption and App Service Plan hosting plan.
2. This issue doesn't reproduce for the Windows function app.
3. This issue doesn't reproduce for the JavaScript project with HttpTrigger function of Node V3 Programming Model.
4. The JavaScript V4 Model project can deploy to the Premium Linux function app successfully after trying to deploy several times.
5. There are two unstable error during deploying the other projects to function apps.
<img width="452" alt="Screenshot 2023-08-09 at 10 03 07" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/9989f6de-ad4e-4065-8d4e-ace1854f84d0">
<img width="452" alt="Screenshot 2023-08-09 at 17 39 48" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/70a7f225-9bbb-4ec3-991c-e0431780f909">

**Comment by alexweininger** [comment]
I don't think this is an issue with v4. I got the same error with v3.

**Comment by alexweininger** [comment]
This is caused by the new status code policy throwing errors that break our retry logic that ignores 404 errors.

**Comment by v-xinda** [comment]
This issue also reproduces when deploying the Python and Java Project to the Premium Linux function app, but it is unstable.
