### ISSUE TITLE
The setting "FUNCTIONS_WORKER_RUNTIME" is "dotnet-isolated" after creating a C# project with .NET 6.0 LTS runtime

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3795]
**OS:** Win10/M1
**Build Version:** 20230808.1
**.NET Version:** 7.0.306 & 6.0.412 

**Repro Steps:**

1. Create a C# project with .NET 6.0 LTS runtime.
2. Check the `local.setting.json` file.

**Expect:**
The setting "FUNCTIONS_WORKER_RUNTIME" is "dotnet".
<img width="621" alt="Screenshot 2023-08-10 at 15 59 29" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/6cae82c2-2ab4-40c4-ac7b-263a5d9f02a0">

**Actual:**
The setting "FUNCTIONS_WORKER_RUNTIME" is "dotnet-isolated".
<img width="527" alt="Screenshot 2023-08-10 at 15 06 51" src="https://github.com/microsoft/vscode-azurefunctions/assets/57662131/c2d513c6-1710-45e3-896e-88c10d6778ac">

**Comment by nturinski** [comment]
Could you verify this again please? I tried to reproduce it, but the `FUNCTIONS_WORKER_RUNTIME` setting is `dotnet` for my project.

![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/6b265b54-b447-4964-aac2-e2d43d88addd)

**Comment by v-xinda** [comment]
@nturinski Verified this issue on the latest main branch build 20230816.1, I can not reproduce it for now.

**Comment by nturinski** [comment]
Thanks for verifying. I'll close this for now then.
