### ISSUE TITLE
Connecting to log stream

### ISSUE THREAD

**Issue by Agazoth** [microsoft/vscode-azurefunctions#3796]
Strat Streaming Logs on Azure functions get stuck on Connecting to log stream. This pr might solve it: https://github.com/microsoft/vscode-azuretools/pull/1548 but wen is the new build available in vs code?

**Comment by alexweininger** [comment]
Fix has been released in version 1.12.3 https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.12.3
