### ISSUE TITLE
"No HTTP triggers found" randomly occurring without deployment

### ISSUE THREAD

**Issue by Krucial92** [microsoft/vscode-azurefunctions#3815]
As of about 24 hours ago I have 2 function apps dev & prod which all of a sudden do not display any functions in the function apps. I am using the new v4 programming model, and have the worker indexing feature flag enabled, etc.

My CI/CD pipeline can successfully build & deploy the application to the dev environment, however no functions are found.

The interesting thing here is my prod function app stopped working a day ago also, and now it contains no functions when I did not touch it at all, no deployment was made to this environment, nothing changed although now it does not display any functions! And I can see when looking at the function apps memory usage it all of a sudden dropped off randomly 24hrs ago.

<img width="265" alt="Screenshot 2023-08-25 at 10 52 04 am" src="https://github.com/microsoft/vscode-azurefunctions/assets/24580689/89f1b329-3a33-4111-9378-ad99f09a8717">

What on earth is going on here, did the runtime version have a minor version bump and this is causing an issue all of a sudden? Can we please get some eyes on this issue asap cc @ejizba @alexweininger @dzoba

**Comment by nturinski** [comment]
@Krucial92 This sounds like a service issue/outage that abruptly happened considering the fact that your production environment was altered and has no memory usage without your intervention.

I recommend that you file a support ticket with Azure [here](https://azure.microsoft.com/en-us/support/create-ticket). We're only the extension team for VS Code, so there isn't really a way for us to support you with Azure outages unfortunately ☹️

**Comment by Krucial92** [comment]
All good thanks @nturinski, was opening this issue based off this thread: https://github.com/microsoft/vscode-azurefunctions/issues/3659

I'll open in a more relevant repo.

**Comment by ejizba** [comment]
@Krucial92 I can help you with this as I'm on the Azure side of things, not VS Code. Please file an issue in our repo here: https://github.com/Azure/azure-functions-nodejs-library/issues

(You can also follow Nathan's suggestion to do a support ticket)

When you create the issue, please share your app name or follow these instructions to share it privately: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by Krucial92** [comment]
Thanks @ejizba I have just filed an issue, and will also go through these instructions now to share the name of my repo.
