### ISSUE TITLE
Missing Drop-Down Option for Deploying Local Functions to Azure

### ISSUE THREAD

**Issue by multispark** [microsoft/vscode-azurefunctions#3816]
Does this occur consistently? 
Yes

Reproduction steps:

1. Follow the steps in this [Microsoft Learn Module](https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal).
2. At this section of the [module](https://learn.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=python#republish-project-files), look at step 2 of the section.
3. The "Deploy to Function App..." option does not exist, there is only a dropdown option for uploading to Container Apps. 
4. A workaround for this missing feature is to right click on the function app you created in the cloud (has an option to upload there), but this is not explicitly stated in the learn module.

<img width="307" alt="AzureToolsBug" src="https://github.com/microsoft/vscode-azurefunctions/assets/65065560/8c19b147-6ac3-4eab-9683-eb00b5323480">

Version: 1.12.4
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.82.0-insider
Language: en

**Comment by nturinski** [comment]
Sorry for the confusion! The option to deploy should be under that Functions button.

We are currently migrating our extensions actions into their own specific icons, but some of our extensions haven't been released with the changes quite yet.
