### ISSUE TITLE
There is no command "Azure Functions: Validate" in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3822]
**OS:** Win10
**Build Version:** 20230829.4
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Search command "Azure Functions: Validate".
2. Check whether there is a command "Azure Functions: Validate" in Command Palette.

**Expect:**
There is a command "Azure Functions: Validate" in Command Palette.

**Actual:**
There is no command "Azure Functions: Validate" in Command Palette.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/3a82f6e7-e736-4ede-a7c1-9e3266f80c1d)

**More Info:**
1. This issue also reproduces for **App Service**.
2. There is an action "Validation" in context menu of service connector.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/4bed69c3-2902-4693-8612-c2e78994a9c6)

**Comment by alexweininger** [comment]
This is by design.
