### ISSUE TITLE
An error occurs after clicking "Connect to Log Stream..." under Logs node during refresh

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3824]
**OS:** Win10
**Build Version:** 20230829.4
**Regression:** Not a Regression

**Repro Steps:**
1. Expand one Function App -> Logs node.
2. Click refresh button in "Azure Resources" view.
3. Click "Connect to Log Stream..." under Logs node during refresh.
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/c0e89e66-be15-4725-95ba-ad0a9a55dd72)

**More Info:**
1. This issue does not reproduce if clicking "Connect to Log Stream..." after finishing refresh.
2. This issue also reproduces for "Connect to a GitHub Repository...".
3. This issue also reproduces for App Service.

**Comment by nturinski** [comment]
This is a good find, but this seems like an edge case that would users would rarely encounter.  We will close as wontfix unless we receive customer feedback that indicates otherwise.
