### ISSUE TITLE
Unable to publish the Azure function from vscode to Azure

### ISSUE THREAD

**Issue by dummyCloudUser** [microsoft/vscode-azurefunctions#3827]
trying to publish function as below code

func azure functionapp publish funclogicabcd

While execute above command, Following error occurs.
**Azure Functions Core Tools does not support this deployment path. Please configure the app to deploy from a remote package using the steps here: https://aka.ms/deployfromurl**
```[tasklist]
### Tasks
```

**Comment by alexweininger** [comment]
What tool are you using to publish? From the description it seems like you're using the Azure CLI, is that correct?
