### ISSUE TITLE
AuthorizationFailed - Deploying Azure function using VS code extension of Azure Function

### ISSUE THREAD

**Issue by Ankit-Sharma-ggn** [microsoft/vscode-azurefunctions#3830]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: AuthorizationFailed
Error Message: The client redacted:email with object id 'redacted:id' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/redacted:id/resourceGroups/arm_test/providers/Microsoft.Web/sites/eventstosplunk/config/appsettings' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 1.12.4
OS: darwin
OS Release: 22.6.0
Product: Visual Studio Code
Product Version: 1.81.0
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:3016205
deserializeResponseBody extension.bundle.js:2:3016932
```

</details>

**Comment by nturinski** [comment]
Could you please provide repro steps?
