### ISSUE TITLE
No error/prompting pops up after deleting an application setting being renamed

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#384]
Repro Steps:
1. Add a new application setting
2. Right click it and select 'Rename setting…'
3. Delete this application setting during being renamed.
4. Press 'Enter' to continue.
5. Check whether pop up an error or not.

Expect;
Pop up an error or prompt that the application setting is not found.

Actual:
No error/prompting pops up.

More Info:
This issue also reproduces when editing the application setting value.

**Comment by EricJizbaMSFT** [comment]
Unlikely that users will run into this scenario

**Comment by v-dantch** [comment]
Thanks a lot for your update.
