### ISSUE TITLE
Why does the extension say "Multiple function projects"?

### ISSUE THREAD

**Issue by mathieubergouniouxcab** [microsoft/vscode-azurefunctions#3840]
In my solution there's only one project that relies on Microsoft.Azure.Functions.Extensions and/or Microsoft.NET.Sdk.Functions.
Granted, that project has a dependency to a nuget package that probably uses Functions too, but it's still inside one project of my solution.

Yet when I use the extension (command palette : Create Function) I get the error "Multiple function projects" from https://github.com/Microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

Why?

**Comment by mathieubergouniouxcab** [comment]
EDIT: It turns out it works when I don't open the whole solution folder in VSCode but instead only the subfolder containing the Functions project.

So... Was that by design?

**Comment by alexweininger** [comment]
Could you provide a more detailed layout of the solution so we can see if there's something we can improve on our end here? Can you look into that dependency and verify what it used?

I'd like to know more so I can determine why we detected two Functions projects. Maybe we can fix it.
