### ISSUE TITLE
Fail to execute "Execute Function Now..." action for "DurableFunctionsHttpsStart" function

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3846]
**OS:** All
**Build Version:** 20230913.2
**Regression:** Not a regression

**Repro Steps:**

1. Create and open a project with "Durable Function orchestrator" function.
2. Create functions with "Durable Functions activity" and "Durable Functions HTTP Starter" templates.
3. Deploy the project to function app.
4. Expand the function app -> Expand "Functions" node -> Right click "DurableFunctionsHttpsStart" function -> Clcik "Execute Function Now..." -> Enter.
5. Check whether succeeds to execute action.

**Expect:**
Succeed to execute action.

**Actual:**
Fail to execute action.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/9bbe1e90-6228-46d8-8b1e-7bef0c8fbe01)

**Comment by nturinski** [comment]
Could you tell me what the runtime of the project and the function app is?

Also, did this work when you tried debugging it locally?

**Comment by v-chenzha** [comment]
@nturinski 
This issue doesn't reproduce for c# project.

This issue reproduces when using JavaScript/TypeScript project and deploying to Node.js 16/18/20 runtime.
This issue reproduces when using Python project and deploying to Python 3.8/3.9/3.10/3.11 runtime.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/cb6de3c2-f089-4dcf-8ba7-0441be3bec4c)

This issue still reproduces when debugging project locally.

This issue reproduces when the project is Azure Storage/Netherite/MSSQL durable storage type.

**Comment by v-chenzha** [comment]
Verified on the latest build 20230927.3, this issue still reproduces for now. So, reopen it.
