### ISSUE TITLE
Deploy function

### ISSUE THREAD

**Issue by Vunda** [Microsoft/vscode-azurefunctions#385]
Repro steps:
open submenu from function (azure)
click Deploy to Function App
select folder with function.

Output:
Error: An error has occurred.
01:31:10 *name_of_function*: Creating zip package...
01:31:25 *name_of_function*: Starting deployment...
01:31:43 *name_of_function*: Fetching changes.
Error: An error has occurred.

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
Can you give any more details on this?

1. Was this a new function app?
1. Does this happen consistently?
1. What language are you deploying?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
