### ISSUE TITLE
VS Code Network requirements

### ISSUE THREAD

**Issue by yudai-yazawa** [microsoft/vscode-azurefunctions#3850]
I'm trying to use VS Code on my corporate network.
I would like to check the communication requirements for Azure Account in order to pass through Firewall and Proxy. Could you please tell me?

**Comment by danielniccoli** [comment]
Communication is via HTTPS

**Comment by alexweininger** [comment]
Closing this in favor of https://github.com/microsoft/vscode-azure-account/issues/857
