### ISSUE TITLE
AZURE extension does not recognise the .NET SDK

### ISSUE THREAD

**Issue by wgrs** [microsoft/vscode-azurefunctions#3856]
Does this occur consistently? Yes
Repro steps:

1. Brand new install of .NET SDK and Runtime
2. Confirm install with dotnet --info and dotnet --list-sdks
3. Brand new install of vscode
4. Add Azure Tools extension
5. Sign into Azure account
6. Try and create a local Functions app
7. Step fails saying the SDK is missing

Version: 1.12.4
OS: linux
OS Release: 6.2.0-33-generic
Product: Visual Studio Code
Product Version: 1.82.2
Language: en

**Comment by alexweininger** [comment]
How did you install .NET SDK and Runtime?

Can you provide a screenshot of the error message and/or the error logs from the output channel?

**Comment by wgrs** [comment]
The issue was caused because the MS repo and Ubuntu repo put the runtime in different file paths

**Comment by alexweininger** [comment]
Ok, thanks for the update.
