### ISSUE TITLE
Creating Function App from VS Code not working "Failed to get latest templates: "net472" is not supported for Azure Functions version "~1". 

### ISSUE THREAD

**Issue by hivyas** [microsoft/vscode-azurefunctions#3857]
Hi there,

Opening a new issue related to #3772 since that one got closed and this is a high priority issue now for our team. 

I have verified that I am running the ~4 runtime version of the Azure Function extension on VS Code but for some reason it keeps picking up the ~1 version. 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/61890270/c6cf39cc-57b9-400b-966b-810faad4ebee)

**Comment by alexweininger** [comment]
Check your `.vscode/settings.json` file for the project runtime setting. It might be set to `~1` and be overriding the setting in the screenshot.
