### ISSUE TITLE
Refresh function works, but with a huge delay

### ISSUE THREAD

**Issue by wojtekmaj** [microsoft/vscode-azurefunctions#3859]
Refresh function in the extension simply doesn't work. It's been 10+ minutes since my 3rd Azure Function has been created, and I still see two Azure Functions on the list.

Does this occur consistently? Yes
Repro steps:

1. Add Function App
2. Wait for 10 minutes
3. Hit Refresh

Version: 1.12.4
OS: darwin
OS Release: 22.6.0
Product: Visual Studio Code
Product Version: 1.82.2
Language: pl

**Comment by wojtekmaj** [comment]
Update: took half an hour to get the list updated.

**Comment by alexweininger** [comment]
You put that this occurs consistently. I'm not able to reproduce this. Can you try this again and see if it's still happening?
