### ISSUE TITLE
Make Event Grid Cloud Event templates verified

### ISSUE THREAD

**Issue by hossam-nasr** [microsoft/vscode-azurefunctions#3877]
Recently, we released a new template for Event Grid functions, the "Event Grid Cloud Event" trigger, specifically for C#. This template is now released. Currently, it only shows up if you switch the filter to "All", but it doesn't show up under "Verified" templates. We should make this template verified as well

**Comment by alexweininger** [comment]
![image](https://github.com/microsoft/vscode-azurefunctions/assets/12476526/5c2fe414-09fb-498f-862c-f4025931519e)

**Comment by hossam-nasr** [comment]
Completed by #3916
