### ISSUE TITLE
Fail to deploy a project to a function app with an error

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3878]
**OS:** Win10
**Azure Resource Extension Build Version:** 20231006.1
**Azure Functions Extension Build Version:** 20231006.12
**Regression:** Previous release (1.13.1)

**Repro Steps:**

1. Install Azure Resource build in VS Code.
2. Create and open a JavaScript project in VS Code.
3. Create a node function app.
4. Deploy the project to the function app.
5. Check whether succeeds to deploy the project to the function app.

**Expect:**
Succeeds to deploy the project to the function app.

**Actual:**
Fail to deploy the project to the function app with an error.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/9767c841-3d95-4509-b708-320bd5bb372d)

**More Info:**
1. This issue also reproduces for Java/.NET/Python/PowerShell language.
2. This issue does not reproduce if the latest main build of the Azure Resource Extension is not installed.

**Comment by v-ruizh** [comment]
Install the latest Azure Resources build and Azure App Service build. This issue also reproduces when deploying a project to web app.

**Comment by v-chenzha** [comment]
Verified this issue on the latest azure resource build 20231109.3 and current release of Azure Functions build, it still reproduces for now. 

This issue doesn't reproduce when deploying project to Node/NET/Java/Powershell function app with Linux os and Consumption hosting plan.

**Comment by alexweininger** [comment]
@v-chenzha can you retry this now that https://github.com/microsoft/vscode-azureresourcegroups/pull/758 is merged? It should be fixed, thanks.

**Comment by v-chenzha** [comment]
Verified this issue on the latest Azure Resource build 20231114.1 and current release of Azure Functions build, this issue has been fixed for now. So close it.
