### ISSUE TITLE
functions includes functionc in other projects.

### ISSUE THREAD

**Issue by Gamecock** [microsoft/vscode-azurefunctions#3879]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/3840

I have a workspace with a single function.

I was trying to use common files with a different project, there are a number of .cs files that include data models.

Project1.csproj
<ProjectReference Include="..\..\Project2\Project2.csproj" />

In addition to the data models there is a function app in Project2

In the Project1 workspace, starting or deploying the functionapp starts or deploys Project2 also.

A warning or something to indicate you were importing additional functions would be helpful.

**Comment by nturinski** [comment]
Could you attach some screenshots of the local workspace tree view and the structure of your workspace?

**Comment by Gamecock** [comment]
I had  included packages from a separate project that also had functions in it. I was trying to use those data models, I created a separate project for common code to resolve.
