### ISSUE TITLE
prompt to upgrade to 2.0.1-beta.26 doesn't install 26

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurefunctions#388]
When the extension activates I get this message:

![image](https://user-images.githubusercontent.com/1487073/40281477-46caad84-5c17-11e8-960e-9d0bd02c4158.png)

I click `Update` and then it runs `brew tap azure/function`, but it seems like it is trying to install .25.  This is the 2nd time I tried it, so there is less output. The first time did a little more work:

```
Running command: "brew tap azure/functions"...
Finished running command: "brew tap azure/functions".
Running command: "brew install azure-functions-core-tools"...
Warning: azure/functions/azure-functions-core-tools 2.0.1-beta.25 is already installed and up-to-date
To reinstall 2.0.1-beta.25, run `brew reinstall azure-functions-core-tools`
Finished running command: "brew install azure-functions-core-tools".
```

**Comment by EricJizbaMSFT** [comment]
We're querying npm to get the latest released version, but I guess the functions team released an update for npm and not brew. We should probably de-couple that logic and use brew-specific logic. FYI @nturinski 

In the meantime, @ahmelsayed @fabiocav is there any reason you haven't released 2.0.1-beta.26 for brew?

**Comment by fabiocav** [comment]
The release is scheduled. They usually go out at the same time.

@watashiSHUN , we should expect to see brew updated today, correct?

**Comment by davidparker** [comment]
it is available.   whats wrong here is that the command is to brew install, not brew update.   this causes a silent error unless your watching the output window.    The command should be update, when the call is to update.
