### ISSUE TITLE
.git is being deployed from VScode

### ISSUE THREAD

**Issue by iobear** [microsoft/vscode-azurefunctions#3882]
When creating a function via VScode, it generates a `.functionignore` where `.git` should be ignored via the first line ".git*" - This is not the case.
After deployment of a function to Azure `.git` is also deployed, when I change `.functionignore` from ".git*" to ".git" - `.git` is not being deployed.
The Zip package size is greatly reduced by changing `.functionignore`

Looking at the main branch It seems the ".git*" filter is still active. 
Source:
`src/commands/createNewProject/ProjectCreateStep/ScriptProjectCreateStep.ts`

Azure Functions 1.13.1
VScode 1.83.0
Windows 11 Enterprise Version 10.0.22621 Build 22621
WSL2 - Ubuntu 22.04.3 LTS

**Comment by JohnLBevan** [comment]
QQ: Are you using `.functionignore` or `.funcignore`?  FYI: I've only seen the latter in [documentation](https://learn.microsoft.com/azure/azure-functions/functions-run-local?tabs=windows%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-csharp#project-file-deployment).

**Comment by iobear** [comment]
I just checked I'm using `.funcignore`, I think my my spellchecker "helped" me.

**Comment by alexweininger** [comment]
Hi, @iobear a fix for this has been released in [v1.13.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.13.2) of the extension.
