### ISSUE TITLE
Cannot create Azure Function

### ISSUE THREAD

**Issue by JaclynFox** [microsoft/vscode-azurefunctions#3893]
Does this occur consistently? Yes
Repro steps:
1. try to create new function
2. error pops up after runtime is selected.

Action: azureFunctions.createFunctionApp
Error type: ProviderResourceTypeNotFoundError
Error Message: Provider "/subscriptions/redacted:id/providers/Microsoft.Resources" does not have resource type "resourceGroups".

Version: 1.13.1
OS: linux
OS Release: 6.2.0-36-generic
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3716430
fulfilled extension.bundle.js:2:3714514
```

</details>

**Comment by nturinski** [comment]
There may be something weird about your subscription.  Could you try unregistering the namespace `Microsoft.Resources` and then re-registering it?

You can do so in the portal by following these steps: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider-1

Or you can use the az CLI and type these commands

```
az provider unregister --namespace Microsoft.Resources
az provider register --namespace Microsoft.Resources
```

Related: https://github.com/microsoft/vscode-azurefunctions/issues/3620

**Comment by JaclynFox** [comment]
That was one of the first things I tried. I may just have something weird going on with my account since I had to open a ticket with Azure due to my account getting locked any time I sign in using the Azure CLI in VSCode.
________________________________

**Comment by nturinski** [comment]
Ah, alright. Let us know if the support team is able to help you out!

**Comment by JaclynFox** [comment]
Well, so far they've been of no help. So when I said I already unregistered and reregistered my microsoft.resources subscription I must have just clicked Reregister because when I try to unregister I get the following error:

> The resource namespace 'microsoft.resources' is invalid

**Comment by markuslewin** [comment]
I'm encountering the same problem and error messages on a fresh subscription from last week. 

The JSON in the resource provider details is still empty after I re-register the provider:

```json
{
  "resourceType": "",
  "locations": [],
  "defaultApiVersion": "",
  "apiProfiles": [],
  "capabilities": "",
  "apiVersions": [],
  "zoneMappings": []
}
```

I'm guessing it should be populated with some default values?

I don't know if it's relevant, but I can create resource groups with the Azure CLI. This works: `az group create -n az-rg-test -l westus`.

**Comment by nturinski** [comment]
> I don't know if it's relevant, but I can create resource groups with the Azure CLI. This works: `az group create -n az-rg-test -l westus`.

Thanks for this tidbit. That's interesting-- I wonder if the SDK that we are using is outdated.

**Comment by markuslewin** [comment]
This works for me now! I don't remember doing anything, but the Microsoft.Resources provider is no longer empty and I can create resources from vscode.
