### ISSUE TITLE
Cannot create local functions or projects

### ISSUE THREAD

**Issue by naseemhaq** [microsoft/vscode-azurefunctions#3903]
Does this occur consistently? 
Repro steps:

1. Open Visual Studio Code
2. click on azure function icon in workspace (local) (options are greyed out)

Version: 1.13.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

**Comment by nturinski** [comment]
Are you working in a virtual workspace by chance? Such as using the GitHub Repositories extension?

**Comment by naseemhaq** [comment]
Found the problem.

I initially logged into Azure and opened a storage account location/blob
and the function extension only allowed creating functions on azure, not
locally.

Someone suggested closing the folder from file menu and re-opening a local
folder instead.

Now I can create functions locally to test and connect to blob storage with
my python code.

**Comment by nturinski** [comment]
Glad that you were able to resolve the issue! I'm going to close this, but feel free to reopen if you start experiencing other problems.
