### ISSUE TITLE
Inability to run Azure Function locally

### ISSUE THREAD

**Issue by SebascnG** [microsoft/vscode-azurefunctions#3904]
Hello,

I have a problem with running Azure Function locally either through cmd or VS Code. The error raised after running "func host start --verbose"  is :
![image](https://github.com/microsoft/vscode-azurefunctions/assets/113029523/8f068f5c-73c0-44d2-8a7b-1e114e7b7821)

Versions of specific applications on my laptop

Python --> 3.10.8

Azure CLI --> 2.48.1

Azure Functions --> 4.0.5198

I also tried to install the most recent Azure CLI version, but the problem wasn't solved. Thank you in advance everyone.

**Comment by nturinski** [comment]
@SebascnG Hi there. It looks like the functions host is looking for `dotnet` when it's starting. You listed your Python version, but is this a Python project or C#?  Do you have .NET installed at all?

**Comment by SebascnG** [comment]
Here is my version : 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/113029523/0abc06a2-065f-4951-8e81-b7a7bf5b8e48)

Just to mention again, I am unable to run Azure Functions from neither cmd nor vs code.

**Comment by SebascnG** [comment]
> @SebascnG Hi there. It looks like the functions host is looking for `dotnet` when it's starting. You listed your Python version, but is this a Python project or C#? Do you have .NET installed at all?

Hi, it is a Python project and I am not aware of any .NET installation.

**Comment by SebascnG** [comment]
> @SebascnG Can you share the version of Azure Functions extension like below?
> 
> ![image](https://user-images.githubusercontent.com/95652148/284320594-ff0bfa7b-cf32-4306-a9bd-97c1c023165d.png)

Here is my version : 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/113029523/0abc06a2-065f-4951-8e81-b7a7bf5b8e48)

Just to mention again, I am unable to run Azure Functions from neither cmd nor vs code.

**Comment by nturinski** [comment]
Could you try to install the [.NET SDK](https://dotnet.microsoft.com/en-us/download)?

I think that may be the issue due to the following error in your logs: 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/02fa189c-f8cc-4498-b51e-f8e378ed6c96)

**Comment by SebascnG** [comment]
> Could you try to install the [.NET SDK](https://dotnet.microsoft.com/en-us/download)?
> 
> I think that may be the issue due to the following error in your logs: ![image](https://user-images.githubusercontent.com/5290572/284678420-02fa189c-f8cc-4498-b51e-f8e378ed6c96.png)

Hello, sadly, it didn't help. Do you have any other ideas that might solve this issue ? Thank you in advance.

**Comment by MicroFish91** [comment]
Can you please run `dotnet --info` and paste the output here? Thank you
