### ISSUE TITLE
Fail to deploy the JavaScript project to the Node.js function app with Azure China account

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3913]
**OS:** All
**Azure Resources extension:** 20231123.1
**Azure Functions Extension:** 20231123.5

**Repro Steps:**

1. Sign in with Azure China account.
2. Create and open a JavaScript project with HttpTrigger function in VS Code.
3. Create a Node.js function app.
4. Deploy the JavaScript project to the above function app.
5. Check whether succeeds to deploy the JavaScript project to the Node.js function app.

**Expect:**
Succeed to deploy the JavaScript project to the Node.js function app.

**Actual:**
Fail to deploy the JavaScript project to the Node.js function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/07d66a89-f4f9-4498-ba3c-3ae4004882ca)

**More Info:**
1. This issue also reproduces for Java/.NET/Python/PowerShell function app.
2. This issue also reproduces for Azure App Service Extension.

**Comment by alexweininger** [comment]
@v-chenza, does this issue reproduce with Azure Resources v0.8.0?

**Comment by v-chenzha** [comment]
@alexweininger  The Azure Resources v0.8.0 does not support sign in with Azure China account. 

Issue link: https://github.com/microsoft/vscode-azureresourcegroups/issues/768
