### ISSUE TITLE
Resources not visible after selecting subscription.

### ISSUE THREAD

**Issue by RRanks** [microsoft/vscode-azurefunctions#3914]
Hello,

I am trying to deploy changes and a new function to my function app however I am unable to get the resource group to show in order to select the app. I can find my subscription, but after selecting that. There are no resource groups returned at all.

**Comment by alexweininger** [comment]
Could you share a screenshot?

Also, try using the grouping options to get it to show up.
<img width="287" alt="image" src="https://github.com/microsoft/vscode-azurefunctions/assets/12476526/8c41405b-379a-4cbc-85dc-fbe257f5e0ac">

**Comment by nturinski** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureresourcegroups/issues/780
