### ISSUE TITLE
Can run AutoGen in Azure Functions App locally, but not after deploying to Azure

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/vscode-azurefunctions#3915]
Hello.  I built an app locally using AutoGen, a framework released by Microsoft.  I am able to run it perfectly fine as a local functions app, but when I deploy it the app does not work.  Here is the error message I am getting:

line 625, in generate_oai_reply response = client.create( File "/home/site/wwwroot/.python_packages/lib/site-packages/autogen/oai/client.py", line 232, in create with diskcache.Cache(f"{self.cache_path_root}/{cache_seed}") as cache: File "/home/site/wwwroot/.python_packages/lib/site-packages/diskcache/core.py", line 478, in init self.reset(key, value, update=False) File "/home/site/wwwroot/.python_packages/lib/site-packages/diskcache/core.py", line 2431, in reset ((old_value,),) = sql(

Note, I have no code in my program that queries a SQL database.

**Comment by MicroFish91** [comment]
Could you please try checking to see if you have this setting set in your `local.settings.json`: `scmDoBuildDuringDeployment`

Also, what tools did you use to create the function app?

**Comment by tyler-suard-parker** [comment]
@MicroFish91 I was able to solve the issue by setting cache_seed as None in the llm_config.
