### ISSUE TITLE
First time user of Azure Tools > Create Function App fails when creating new project

### ISSUE THREAD

**Issue by paulbackhouse** [microsoft/vscode-azurefunctions#3920]
Does this occur consistently? yes
Repro steps:

1. open vs code
2. install azure tools
3. sign in to azure subscription/account
4. create function app
5. prompted to create new project or open existing
6. select create new project
7. select C#
8. Errors

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to get latest templates: options.uri is a required argument

Version: 0.23.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:357604
fulfilled extension.bundle.js:164:354071
```

</details>

**Comment by MicroFish91** [comment]
Strange, can you try re-running this in a fresh workspace folder and let us know if it repros?  Thank you
