### ISSUE TITLE
No location is listed when creating a python function app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3922]
**OS:** All
**Azure Resources Build Link:** [vscode-azuresourcegroups-0.8.1-alpha.2 1.vsix](https://microsoft-my.sharepoint.com/personal/v-ruizh_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv%2Druizh%5Fmicrosoft%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2Fvscode%2Dazureresourcegroups%2D0%2E8%2E1%2Dalpha%2E2%201%2Evsix&parent=%2Fpersonal%2Fv%2Druizh%5Fmicrosoft%5Fcom%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files&ga=1)
**Azure Functions Version:** v1.13.1

**Repro Steps:**

1. Sign in with Azure China account.
2. F1 -> Azure Function: Create Function App in Azure... -> Enter a name -> Select a python runtime.
3. Check whether the locations are listed.

Expect: 
The locations are listed.

**Actual:**
No location is listed.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/3a3a3505-7e34-4df7-b55b-35dfe61f1119)

**Comment by v-chenzha** [comment]
@alexweininger  Yes, we can reproduce it consistently.

**Comment by nturinski** [comment]
What subscription are you using to reproduce this?

Is this a regression or were you never able to see the list of locations? (if you use Resource extension v0.7.5)

**Comment by v-chenzha** [comment]
@nturinski  The subscription is "Azure Tools Mooncake Automation Gerneral".

This issue also reproduces for Resource extension v0.7.5.
