### ISSUE TITLE
Configured Uri (http://127.0.0.1:20124/) does not match actual Uri (http://127.0.0.1:20055/) 

### ISSUE THREAD

**Issue by ba31** [microsoft/vscode-azurefunctions#3925]
Trying to run simple HTTP_trigger function by following the steps https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions but seeing error message of Configured Uri (http://127.0.0.1:20124/) does not match actual Uri (http://127.0.0.1:20055/) 
Py : 3.10
OS : Windows 2016
VS Code : 1.85 ( System Installer )

**Comment by nturinski** [comment]
Hi @ba31

It looks like your port number doesn't match what's expected. Could you verify where this error is coming from? If you expand the error notification, you should be able to see the source of the error:

![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/ab949db8-4c36-4f32-9fb2-78886bd0a3dd)

I have a feeling that this may be coming from the Python extension.
