### ISSUE TITLE
Deploying Azure Function has started failing with "Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory."

### ISSUE THREAD

**Issue by mscherotter** [microsoft/vscode-azurefunctions#3926]
Azure Functions version 1.13.1 on Windows 11:

After working fine for over a year, deploying a function to a slot or production fails in VS Code with this error.  I have done nothing in the code to change the number of files in the app.

Starting deployment...
9:32:11 AM gallerybuilder-staging: Creating zip package...
9:33:37 AM gallerybuilder-staging: Zip package size: 33.5 MB
9:33:38 AM gallerybuilder-staging: Fetching changes.
9:33:38 AM gallerybuilder-staging: **Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.**
9:33:43 AM gallerybuilder-staging: Deployment failed.

Any Suggestion?

**Comment by alexweininger** [comment]
Hi, please update to Azure Resources v0.8.3 to fix this issue.

**Comment by e14mattc** [comment]
> update to Azure Resources v0.8.3

I've just hit this issue today too. I wondered what you meant, then realised it's one of the VSC extensions :)

**Comment by alexweininger** [comment]
> > update to Azure Resources v0.8.3
> 
> I've just hit this issue today too. I wondered what you meant, then realised it's one of the VSC extensions :)

Sorry about that! I edited my comment to clarify.

**Comment by nturinski** [comment]
Hi @mscherotter, could you confirm if upgrading the [Azure Resources extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups) resolves this issue?

**Comment by mscherotter** [comment]
It did

Michael S. Scherotter
***@***.***
________________________________

**Comment by mscherotter** [comment]
It did.

Michael S. Scherotter
***@***.***
________________________________

**Comment by alexweininger** [comment]
Thanks!
