### ISSUE TITLE
Trying to create a new Azure Functions app from Visual Studio Code on Mac, this is what I get

### ISSUE THREAD

**Issue by SiavoshZarrasvand** [Microsoft/vscode-azurefunctions#393]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet new --list" failed with exit code "null":
Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates

Version: 0.8.1
OS: darwin

**Comment by SiavoshZarrasvand** [comment]
For the record I do have dotnet installed. I ran dotnet in the terminal and this is what I got: 

# dotnet new --list
Template Instantiation Commands for .NET Core CLI.

Usage: dotnet new [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         List templates containing the specified name.
  -lang|--language  Specifies the language of the template to create
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates


Templates                 Short Name      Language      Tags          
----------------------------------------------------------------------
Console Application       console         [C#], F#      Common/Console
Class library             classlib        [C#], F#      Common/Library
Unit Test Project         mstest          [C#], F#      Test/MSTest   
xUnit Test Project        xunit           [C#], F#      Test/xUnit    
ASP.NET Core Empty        web             [C#]          Web/Empty     
ASP.NET Core Web App      mvc             [C#], F#      Web/MVC       
ASP.NET Core Web API      webapi          [C#]          Web/WebAPI    
Solution File             sln                           Solution

**Comment by EricJizbaMSFT** [comment]
@SiavoshZarrasvand what version of the dotnet cli are you on?

**Comment by SiavoshZarrasvand** [comment]
Hey! It was solved by changing dotnet version, from 1 to 2. Thank you. This is resolved.
