### ISSUE TITLE
Typos and issues in blueprint template for python (HttpTrigger-python) 

### ISSUE THREAD

**Issue by prise6** [microsoft/vscode-azurefunctions#3932]
Version of extension: v1.13.1

Step to reproduce (for example):
1. Create Functions
2. HTTP Trigger
3. Create New Blueprint file 
4. Name: `name_of_file.py`
5. Name of function: `name_of_function`
6. Authorization: FUNCTION 

This will generate somethin wrong : 

```python
# Register this blueprint by adding the following line of code 
# to your entry point file.  
# app.register_functions(name_of_file) 
# 
# Please refer to https://aka.ms/azure-functions-python-blueprints


import azure.functions as func
import logging

name_of_file = func.Blueprint()


@name_of_file.route(route="name_of_file, auth_level=func.AuthLevel.FUNCTION")
def name_of_file(req: func.HttpRequest) -> func.HttpResponse:
# ...
```

[Looking at the template](https://github.com/microsoft/vscode-azurefunctions/blob/c30d8cecafc2968c7c6b19b594eee98d73f7a0bd/resources/backupTemplates/pystein/templates-v2/templates.json#L965C1-L966C1), in key `blueprint_body.py`:

* `$(BLUEPRINT_FILENAME)` is used as definition of function instead of `$(FUNCTION_NAME_INPUT)`
* final quote for `route` argument is placed after `auth_level` argument resulting in a error like above example.

Final result should be, i guess:

```python
# Register this blueprint by adding the following line of code 
# to your entry point file.  
# app.register_functions(name_of_file) 
# 
# Please refer to https://aka.ms/azure-functions-python-blueprints


import azure.functions as func
import logging

name_of_file = func.Blueprint()


@name_of_file.route(route="name_of_function", auth_level=func.AuthLevel.FUNCTION)
def name_of_function(req: func.HttpRequest) -> func.HttpResponse:
# ...
```
 
So template could be replaced by:
```json
"blueprint_body.py": "\r\n@$(BLUEPRINT_FILENAME).route(route=\"$(FUNCTION_NAME_INPUT)\", auth_level=func.AuthLevel.$(AUTHLEVEL_INPUT))\r\ndef $(FUNCTION_NAME_INPUT)(req: func.HttpRequest) -> func.HttpResponse:\r\n    logging.info('Python HTTP trigger function processed a request.')\r\n\r\n    name = req.params.get('name')\r\n    if not name:\r\n        try:\r\n            req_body = req.get_json()\r\n        except ValueError:\r\n            pass\r\n        else:\r\n            name = req_body.get('name')\r\n\r\n    if name:\r\n        return func.HttpResponse(f\"Hello, {name}. This HTTP triggered function executed successfully.\")\r\n    else:\r\n        return func.HttpResponse(\r\n             \"This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.\",\r\n             status_code=200\r\n        )",
```

Am i wrong ? (new in azure function v2)

**Comment by alexweininger** [comment]
https://github.com/Azure/azure-functions-templates/issues/1450

**Comment by nturinski** [comment]
Thanks for your contribution! As mentioned in your PR, we will update the backup templates through another means. The fix for the blueprints should be live from the template feed, but you may need to do the following:

1. Change your `host.json` file to have an extensionBundle property like so:
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
```
2. Enable `Show Reload Templates`
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/07ce54ad-0f97-4be8-b5e3-682f13b2554f)

3. Select Reload Templates
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/30f1a420-bbd1-4a9f-88a9-8852f4486142)

**Comment by nturinski** [comment]
Closing due to being resolved, but please feel free to comment/re-open if you're still experiencing issues.
