### ISSUE TITLE
Error: Response from service 'Microsoft.Web' does not contain sufficient information to enforce access control policy

### ISSUE THREAD

**Issue by KorawichSCG** [microsoft/vscode-azurefunctions#3937]
I got the error from the Azure Functions extension that was installed on the Virtual Studio code.

* Azure Functions extension version: `v1.13.1`
* Azure Account extension version: `v0.11.6`

First, I got this error when I tried to get Azure Functions resources.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/88130047/0731fe85-c471-4c2f-add0-6fc315bbe21b)

If I wait a minute, it will show another error statement.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/88130047/a7824292-73c0-4c7b-9482-132e0cc4475e)

Note that I can list my Azure Functions resources normally from the Azure Portal.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/88130047/b67e59a9-9229-40a3-aea3-802741f1cb93)

**Comment by alexweininger** [comment]
Is this your first time trying to access these resources in VS Code? And if not, has it worked in the past?

Both errors indicate that you don't have sufficient rights to get the data about those resources. Can you make sure you have valid permissions to view/edit those Function Apps?

**Comment by KorawichSCG** [comment]
I used to deploy my local code to Azure Functions with this extension. Now that I have come back to use it again, it raises this error statement for me.

I can get and edit configurations on any Azure Function Apps in the Azure Portal.
This is my permission that I have on the Azure Function:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/88130047/39ba88d3-48bc-4488-8ae9-fab83afebdba)
