### ISSUE TITLE
Azure Function APP Deployment

### ISSUE THREAD

**Issue by Mohanraj27v** [microsoft/vscode-azurefunctions#3939]
Type: <b>Bug</b>

I developed the code locally and tested. when I try to deploy it to the Function APP portal, I got stuck with this extension problem.

Extension version: 0.11.6
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (17.88GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/MohanrajVijayan/Documents/Dev/Goldzone_Rollout_Testing --crash-reporter-id 6d83d70c-bd11-48fa-aef7-3a5994ba090c|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>
when I ran the diagnostic for extension, I got this extension issue as an result
![image](https://github.com/microsoft/vscode-azure-account/assets/147384183/7205a1b0-c4db-41dc-9178-c4409f767f9c)

![image](https://github.com/microsoft/vscode-azure-account/assets/147384183/86fb1df8-4ae9-4b47-88bf-8561321fec81)

**Comment by nturinski** [comment]
Could you please provide us with the error that the extension is throwing? Could you explain what the steps that you take to encounter this problem?
