### ISSUE TITLE
Azure Function Deployment - Does not get reflected on the Portal

### ISSUE THREAD

**Issue by Mohanraj27v** [microsoft/vscode-azurefunctions#3944]
I was working with the Azure Function APP, I have deployed the code few times earlier, but when I try to deploy it after the code change done by myself, I got the deployment successful message in the vs code, but turns out in the console it does not get reflected.

![image](https://github.com/microsoft/vscode-azurefunctions/assets/147384183/ba3b6a19-caed-461e-8aaf-bff180bdcf1f)

After that, when I saw it in the console - Azure Portal 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/147384183/840cbe39-fd22-4c8e-89b5-684c300c11c9)

I could there see the function app name and trigger does not get reflected.

**Details regarding the Function APP:**

Trigger : Queue Trigger
Runtime : Python 3.11
Machine: linux

**Comment by nturinski** [comment]
Hi @Mohanraj27v 

Could you share more of your logs from the deployment? It may not be zipping up the directory with your project correctly.  If your project nested in another folder of your workspace?
