### ISSUE TITLE
Bulid Errors with Permission Denied

### ISSUE THREAD

**Issue by uc-cjdavis** [microsoft/vscode-azurefunctions#3949]
Does this occur consistently?  Yes
Repro steps:
From the Create a C# function in Azure using Visual Studio Code in the section Run the code locally (link: [https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp in ](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp#run-the-function-locally))
1.  With the Core Tools running, go to the Azure: Functions area. Under Functions, expand Local Project > Functions. Right-click (Windows) or Ctrl - click (macOS) the HttpExample function and choose Execute Function Now....
  - Function does not appear, instead only a Start debugging to update this list... message 
     ![image](https://github.com/microsoft/vscode-azurefunctions/assets/24594750/b83992cb-b116-4b84-9451-0ff4bc2b8d6d)
2.  Clicking on the  Start debugging to update this list starts the debug in the terminal window, which does not complete (see below screenshot
![image](https://github.com/microsoft/vscode-azurefunctions/assets/24594750/e1572dfe-7cdf-463f-9f8d-e8ed02daa3a2)

It appears as though the debug build process does not mark the binary as executable prior to run.

Version: 1.13.1
OS: darwin
OS Release: 22.6.0
Product: Visual Studio Code
Product Version: 1.85.2
Language: en

**Comment by MicroFish91** [comment]
Are you able to run `func host start` in the terminal?
