### ISSUE TITLE
There are two HTTP trigger templates in the list when creating a .NET 7.0 project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3954]
**OS:** All
**Build Version:** 20240126.14
**Regression:** Previous release (1.13.1)

**Repro Steps:**

1. F1 -> Azure Functions: Create New Project... -> Select a folder -> C# -> .NET 7.0 Isolate.
2. Check whether there is one HTTP trigger template in the list.

**Expect:**
There is one HTTP trigger template in the list.

**Actual:**
There are two HTTP trigger templates in the list.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/7a9f4f20-3a25-46db-863b-5a01851246c5)

**More Info:**
This issue doesn't reproduce for the .NET 6.0/8.0.

**Comment by nturinski** [comment]
I don't believe that this is a regression. The template feed got updated so now I think you are seeing double. If you "Reload Templates", it should resolve this.

I'll put a fix out for this issue, but it won't help any existing customers already seeing double. If they "Reload Templates" and delete their cache, it should resolve it for them.
