### ISSUE TITLE
Failed to attach remote debugee VM.

### ISSUE THREAD

**Issue by mathursharp** [Microsoft/vscode-azurefunctions#396]
Unable to debug java azure functions with vs code.
Always getting the following error.
![image](https://user-images.githubusercontent.com/5322858/40553415-38745012-6060-11e8-98c9-8a6e58701c2b.png)

**Comment by jdneo** [comment]
Could you please provide your version of Azure Functions Core Tools?

**Comment by mathursharp** [comment]
version is 2.0.1-beta.26
OS is windows 10

**Comment by jdneo** [comment]
Please run rpm i -g azure-functions-core-tools@core to install the latest version. Beta.26 is out of date

**Comment by EricJizbaMSFT** [comment]
Yes this was a bug specifically in version beta.26 of the func cli. The latest version is currently beta.28

Closing as fixed, but re-open if you still have problems after updating.

**Comment by mathursharp** [comment]
What is the latest version of core tools for ubuntu 16.04.
I am not able to run azure java functions locally after updating the pom for latest beta runtime.

**Comment by jdneo** [comment]
@mathursharp Recently java function has a breaking change. Could you please try to install the latest version of function cli and try again. The latest version should be 2.0.1-beta.29

Reference: https://github.com/Azure/azure-functions-core-tools#linux

**Comment by mathursharp** [comment]
@jdneo  Thanks for the info.
But the problem is "sudo apt-get install azure-functions-core-tools" is always installing **2.0.1~beta.25-1 of core tools.**

**Comment by jdneo** [comment]
@mathursharp Did you follow the steps in the installation tutorial? 

If apt-get still cannot help. Maybe you can try install it through npm:
```
npm i -g azure-functions-core-tools@core --unsafe-perm true
```
