### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error)

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/vscode-azurefunctions#397]
Hi,

I just started a new project with a new Javascript function. After hitting F5 I have this error message: 

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error).`

By doing the same handlings with a C# function, it works perfectly.

Here is the content of my launch.json file 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to JavaScript Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "protocol": "inspector",
      "preLaunchTask": "runFunctionsHost"
    }
  ]
}
```
Does anyone have an idea of where this error could come from ?

Thanks!

**Comment by JulienDecottignies** [comment]
It's ok I created a new javascript project with a new function.
Differences:

**OLD**
launch.json:

`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to JavaScript Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "protocol": "inspector",
      "preLaunchTask": "runFunctionsHost"
    }
  ]
}
`

local.settings.json

`{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard ":"UseDevelopmentStorage=true"
  }
}
`

**NEW**
launch.json

`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to JavaScript Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "protocol": "legacy",
      "preLaunchTask": "runFunctionsHost"
    }
  ]
}
`

local.settings.json

`{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
`

**Comment by EricJizbaMSFT** [comment]
@JulienDecottignies so has this been fixed for you? 

If not, what version of the func cli do you have installed?

**Comment by JulienDecottignies** [comment]
@EricJizbaMSFT  

Yes it's ok for me!
