### ISSUE TITLE
error while publishing function

### ISSUE THREAD

**Issue by MajorSingh** [Microsoft/vscode-azurefunctions#399]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy 
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@MajorSingh can you give more detail on how you got into this situation:
1. Does this happen consistently for you?
1. Was this the first time deploying to that function app?
1. What language were you using (JavaScript, C#, etc.)?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
