### ISSUE TITLE
Access restricted storage accounts should be hidden in "Create Function App in Azure (Advanced)"

### ISSUE THREAD

**Issue by im-samz** [microsoft/vscode-azurefunctions#3990]
Repro:
- Attempt to create a Function app via "Create Function App in Azure (Advanced)"
- In Step 7/9, select "Consumption" for the hosting plan
- In Step 8/9, notice that all storage accounts in the selected Region (from Step 6) are displayed, even those with network restrictions. Select a restricted storage account.
- Attempt to create; it will fail with the message: "Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible."

Expected outcome:
- In Step 8/9, incompatible restricted storage accounts should be hidden.

An ARG query can be run to return storage accounts of a sub > region that are not access restricted. That can be applied as a filter.

Specifically:
![CleanShot 2024-02-26 at 16 46 20@2x](https://github.com/microsoft/vscode-azurefunctions/assets/38818012/5c430e81-85a3-4e14-95ad-a0c862bcc14d)

**Comment by nturinski** [comment]
@im-samz, what is this supposed to be?

> Specifically: ![CleanShot 2024-02-26 at 16 46 20@2x](https://private-user-images.githubusercontent.com/38818012/307997602-5c430e81-85a3-4e14-95ad-a0c862bcc14d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTg0MzksIm5iZiI6MTcwOTA1ODEzOSwicGF0aCI6Ii8zODgxODAxMi8zMDc5OTc2MDItNWM0MzBlODEtODVhMy00ZTE0LTk1YWQtYTBjODYyYmNjMTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE4MjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNmM5MTE3YjU2M2EyYWJkZTMwZTY1YjEzY2UyNmZlMDUxNDA1YTQ0MjA1NmIzMjk5YzJlNTllYTUxMzQ0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OJOiUwSjHK79sY5_-fzagG_VGCuXytN7wj3twbDKlgU)

I'm assuming it was a screenshot, but I can't see what it is. Could you reattach it?
