### ISSUE TITLE
"Azure Container Apps" extension is not installed directly after clicking "Install" button in the prompt notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3998]
**OS:** All
**Build Version:** 20240229.2
**Regression:** Not a Regression

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Right click on the Function App tree item and click on the command "Create Function App in Azure…".
3. Click "Container Image" button in the prompt dialog.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/f1087720-93b1-410d-b129-e6110babf50b)
4. Click "Install" button in the prompt notification.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/b76bc603-e3fc-481d-b776-fa6d192fb5b9)
5. Check whether the "Azure Container Apps" extension is installed directly or not.

**Expect:**
"Azure Container Apps" extension is installed directly after clicking "Install" button.

**Actual:**
"Azure Container Apps" extension is not installed directly after clicking "Install" button. Only open the "Azure Container Apps" extension installation page.

**Comment by motm32** [comment]
Thanks for filing this issue! This is the expected behavior. We don't want to directly install the extension for the user just open up the extension marketplace page.
