### ISSUE TITLE
can't deploy from vscode

### ISSUE THREAD

**Issue by richarda** [Microsoft/vscode-azurefunctions#400]
Repro steps:
deploy JavaScript function app from vs code

Action: azureFunctions.deploy
Error type: Error
Error Message: Deployment to "<function app name>" failed. See output channel for more details.

Version: 0.9.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@richarda does this happen consistently for you? It says "See output channel for more details" - can you copy the logs from the output channel here?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
