### ISSUE TITLE
Fail to create an advanced function app with "App Service Plan/Premium" hosting plan when a containerized function project opened in VS Code

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#4002]
**OS:** All
**Build Version:** 20240229.2
**Regression:** Not a Regression

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Right click on the Function App tree item and click on the command "Create Function App in Azure…(Advanced)" -> Click "Container Image" -> Enter a name -> Select a resource group -> Select a location -> Click "Premium/App Service Plan" hosting plan.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/695b7b32-f939-4488-81dc-f44a323327b2)

**Comment by motm32** [comment]
> Verified this issue on the latest build 20240318.1, it still reproduces, so reopen it.

Hi @v-xinda, could you verify this is fixed? We had a fix out for it last week that hadn't been merged yet.

**Comment by v-xinda** [comment]
@motm32 Verified this issue with latest main build, there is no step to select the hosting plan (Consumption/App Service Plan/Premium). is it expect?

**Comment by motm32** [comment]
@v-xinda yes! Containerized function projects do not utilize and Consumption/App Service/Premium plan so this step should not appear.
