### ISSUE TITLE
The durable function name is inconsistent between C# project and other projects

### ISSUE THREAD

**Issue by Amar-QA** [microsoft/vscode-azurefunctions#4016]
**OS**: All
**Build Version**: 20240301.18
**Regression**: Not a Regression. 

**Repro Steps**: 

1. Create new C# project. 
2. Open Command Palette > Type and Select "Azure Functions: Create Functions." > Type "Durable Functions".
3. Check whether the durable function name is "Durable Functions Orchestrator" in the dropdown list.

**Expected**: 
The durable function name is "Durable Functions **Orchestrator**".
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/41231ccf-63e9-43c9-8c86-a3be8b732954)

**Actual**: 
The durable function name is "Durable Functions **Orchestration**".
![image](https://github.com/microsoft/vscode-azurefunctions/assets/156269329/c572c6c8-4af2-4632-9c4b-25201d665023)

**More Info**: 

1. This issue only reproduces in C# related projects.

**Comment by MicroFish91** [comment]
This is taken from the feed and we do not control this naming, closing as won't fix.
