### ISSUE TITLE
Workspace (local)   not visible.  

### ISSUE THREAD

**Issue by cechrisha** [microsoft/vscode-azurefunctions#4031]
Hello all, 

Currently I'm unable to see My local Workspace. 

![image](https://github.com/microsoft/vscode-azureappservice/assets/119649072/77f62eb4-de59-497c-b306-fcc687787754)

I have tried to see if it's hidden, That is not the case. 

![image](https://github.com/microsoft/vscode-azureappservice/assets/119649072/a73a9bc1-81ab-4b14-8f00-e3cef83c7bc4)

I have also tried to follow this issue.  

https://github.com/microsoft/vscode-azurefunctions/issues/3522

.... 

After trying to reinstall core tools, resources -- >   The error still remains.

**Comment by motm32** [comment]
Hi! Could you try pressing F1 and typing in this command `View: Reset View Locations`? It's possible the workspace location was moved.

**Comment by cechrisha** [comment]
> Hi! Could you try pressing F1 and typing in this command `View: Reset View Locations`? It's possible the workspace location was moved.

Thank you so much!!!

**Comment by nturinski** [comment]
Closing as resolved. Glad that helped 🙂
