### ISSUE TITLE
After logging out, the account is still connected.

### ISSUE THREAD

**Issue by RafaelMatthes** [microsoft/vscode-azurefunctions#4037]
It's impossible to log out Microsoft account... I'm trying to change accounts, but the old account never log out.

**Comment by alexweininger** [comment]
Hi, our authentication methods have changed, there is a new way to sign out. Learn more about the change [here](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0).

![image](https://github.com/microsoft/vscode-azurefunctions/assets/12476526/7e6b86e7-383a-4c2e-9dd0-05050446dc42)
