### ISSUE TITLE
Function apps aren't displayed in VSCode extension

### ISSUE THREAD

**Issue by LauraBeatris** [microsoft/vscode-azurefunctions#4039]
### Description 

I've created a function app on my subscription:

![CleanShot 2024-03-14 at 13 53 44](https://github.com/microsoft/vscode-azurefunctions/assets/48022589/edf15343-74cb-422e-ba97-9ba3c17ba933)

However, it doesn't get reflected on my VSCode extension, even tho I've already performed the following steps:
- Refreshed the subscription on VSCode
- Sign out from Azure on VSCode + Sign in 
- Cleared VSCode cache 

Furthermore, when trying to deploy my function to the function app, it doesn't get displayed ("No matching resources"):

![CleanShot 2024-03-14 at 13 55 25](https://github.com/microsoft/vscode-azurefunctions/assets/48022589/cfce791d-1334-4219-9a3c-a21aa52aa8cc)

**Comment by nturinski** [comment]
Hi @LauraBeatris

Really sorry about the late response. Are any subscriptions showing up on your VS Code tree view? Are you able to create a new Function App from VS Code?
