### ISSUE TITLE
Subscription about client's tenant has disappeared from Visual Studio code

### ISSUE THREAD

**Issue by GaijinFizz** [microsoft/vscode-azurefunctions#4043]
Does this occur consistently? Yes
Repro steps:
1. Open Visual Studio code
2. Click on the Azure "A" icon on the left
3. Notice the subscription from my company's tenant is there
4. Notice the subscription of my client's tenant (for which my Azure account is a guest) is not there
5. Perform  "az login -Tenant the_client_tenant_id"
6. Perform "azd auth login"
7. Notice nothing is resolved

I used to be able to publish to the Azure function app, but the subscription won't appear anymore.

Edit: I would like to add that I am able to view this subscription within Azure Storage explorer and able to connect to the client's Azure portal.

Thank you.

Version: 1.87.2
OS: Windows 11 Pro, 23H2
OS Build: 22631.3296
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

**Comment by nturinski** [comment]
Hi @GaijjinFizz

It seems like you may need to run `Azure: Sign in to Directory...` if the subscription you are looking for isn't appearing.

You can run the command by pressing F1 and then `Azure: Sign in to Directory...`
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/03eb0c66-5100-4432-b040-82be9037e72c)

Please let me know if this resolves your issue.

**Comment by GaijinFizz** [comment]
Thank you, that worked!

I was using "Azure: Sign In" instead of "Azure: Sign in to Directory"
