### ISSUE TITLE
[Suggestion] It would be better to add more information about the created container resources in output log when creating a containerized function app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4059]
**OS:** All
**Build Version:** 20240325.1
**Regression:** Not a Regression

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Create a containerized function app with above project opening.
3. Navigate to the "Azure Functions" output window.
4. Check whether the log about created container resources is clear or not.

**Actual:**
The log about created container resources is not clear.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/ddf14bbc-d97c-48a2-bf04-6d331e1d9c29)

**Suggestion:**
It would be better to add more information about the created container resources in output log, such as the container app name and the related resources.

**Comment by nturinski** [comment]
This was by design because we didn't want our Functions users to be to familiar with what components are being created in the Container App extension.

If they really want to know that information, they can go to the output for container apps and see all of the components that were created.
