### ISSUE TITLE
Fail to create a Java/Node.js/.NET Function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#4064]
**OS:** All
**Build Version:** v1.14.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a Java 17 Function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.
2. Check whether succeeds to create a Java 17 Function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.

**Expect:**
Succeed to create a Java 17 Function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.

**Actual:**
Fail to create a Java 17 Function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/a58426be-d8c5-4c0e-be03-7bb04cf8e142)

**More Info:**
1. This issue also reproduces for the Node.js 20 LTS, .NET 8 Isolated and Java 11 runtime stacks.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/036271d9-26fc-4861-aabd-fc366a640fc9)
3. This issue does not reproduce for the Python 3.11, Python 3.10 and PowerShell runtime stacks.
4. **No step "Select OS"** during creating a Flex Consumption (Preview) function app.

**Comment by nturinski** [comment]
This should be all be fixed. These were errors on the service-- I just conducted a test for all 3 runtimes creating in East Asia. Could you confirm this bug?

**Comment by v-xinda** [comment]
@nturinski  Succeed to All runtimes Flex Consumption function app using East Asia location. 
Is the East US 2 EUAP location not supported to create Flex Consumption function app?

**Comment by nturinski** [comment]
It's a staging location so it may not have been updated. It's not usually offered to customers, so I don't think we need to worry about it. Closing bug 🐛
