### ISSUE TITLE
[Suggestion] It would be better to remove the "Slots" node from the function app which host plan is Flex Consumption (Preview)

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4069]
**OS:** All
**Build Version:** v1.14.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a python function app with Flex Consumption (Preview) hosting plan and East US 2 EUAP location.
2. Expand the above function app -> Right click the "Slots" node and select "Create Slot..." -> Enter a slot name to create it.
3. Check whether succeeds to create a slot.

**Actual:**
Fail to create a slot with an error.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/4e78a782-4eb8-468b-9077-50a0701a233a)

**Suggestion:**
It would be better to remove the "Slots" node from the function app which host plan is Flex Consumption (Preview).

**More Info:**
There is no "Deployment Slot" page for the function app which host plan is Flex Consumption (Preview) in portal.

**Comment by nturinski** [comment]
Fixed in https://github.com/microsoft/vscode-azurefunctions/pull/4078
