### ISSUE TITLE
There is no setting "FUNCTIONS_WORKER_RUNTIME" under the "Application Settings" node

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#4074]
**OS:** All
**Build Version:** v1.14.1-alpha.0
**Regression:** Previous release (1.14.0)

**Repro Steps:**

1. Create a function app.
3. Expand the function app -> Expand the "Application Settings" node. 
5. Check whether there is a setting "FUNCTIONS_WORKER_RUNTIME" under the "Application Settings" node.

**Expect:** 
There is a setting "FUNCTIONS_WORKER_RUNTIME" under the "Application Settings" node.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/4345f109-1c0f-431c-a350-22e271714fc5)

**Actual:** 
There is no setting "FUNCTIONS_WORKER_RUNTIME" under the "Application Settings" node.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/768bdd7b-972d-4496-a568-e820880077e3)

**More Info:** 
There is an error notification after opening a function app in portal.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/902ffca3-f19a-4cdd-8e2f-5e5e07580e81)

**Comment by nturinski** [comment]
Thanks for finding this. This is an external issue with the controller. Will leave open for tracking.

**Comment by nturinski** [comment]
I didn't look closely enough at the screenshot.  The ASP here is actually a normal consumption plan. This should have created with a FUNCTIONS_WORKER_RUNTIME setting so I need to investigate why it's not.
