### ISSUE TITLE
unable to publish

### ISSUE THREAD

**Issue by antobonfiglio** [Microsoft/vscode-azurefunctions#411]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: Deployment  failed. See output channel for more details.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @antobonfiglio 

Sorry to see that your deployment failed.  Do you happen to have the details that are logged in the output channel?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
