### ISSUE TITLE
All function apps show Error. Could not resolve resources <resourceid of function>

### ISSUE THREAD

**Issue by jrudley** [microsoft/vscode-azurefunctions#4111]
This is on any subscription where a function exists. I have uninstalled/installed vscode and extensions. 
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/63196b1b-0d12-42f6-a018-262d47efe8f9)

Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.20348

Azure Functions v1.14.2

This was working fine this morning then around lunch they all started showing the Error above. I am in Azure Government.

I can reproduce this. I built a new azure vm, installed the Azure Tools extension and tried to browse the function. Same issue.

**Comment by alexweininger** [comment]
This seems like a service related issue. Could you try and downgrade to the previous version of the Azure Resources, and Azure Functions extensions?

Also, is the experience on the portal still working as expected?

**Comment by jrudley** [comment]
Yes, the portal development works just fine, just using vs code for
deployment is not. I will try that and see how it goes. I am also opening a
case up. Thanks

**Comment by yashdhanore** [comment]
We are facing the same issue on Mac. Have tried all the steps mentioned by @vdmazahreh 
Got help from Microsoft Support also about this but even he couldnt help much in this case we tried several things.

**Comment by alexweininger** [comment]
@yashdhanore and @vdmazahreh are you also using a sovereign cloud like Azure US Government?

**Comment by yashdhanore** [comment]
> @yashdhanore and @vdmazahreh are you also using a sovereign cloud like Azure US Government?

No we are not using Azure government

**Comment by steven-keller** [comment]
I'm getting the same issue, on Azure US Government.

**Comment by alexweininger** [comment]
Can you try using this VSIX and see if it fixes the issue?
[vscode-azurefunctions-1.14.3-alpha.0.vsix.zip](https://github.com/microsoft/vscode-azurefunctions/files/15167409/vscode-azurefunctions-1.14.3-alpha.0.vsix.zip)

**Comment by jrudley** [comment]
It did not work for me.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/4e623474-84ae-442d-884a-4bb3388263d5)
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/bd8c2db5-a9e0-4162-992f-02fa19621717)
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/6e1c8b81-79d8-4260-abf0-fe0c44c57dcc)

**Comment by alexweininger** [comment]
Thanks for trying that out so quickly. I have another one for you try. Sorry for the back and forth, I just can't reproduce the issue.

[vscode-azurefunctions-1.14.3-alpha.1.vsix.zip](https://github.com/microsoft/vscode-azurefunctions/files/15168222/vscode-azurefunctions-1.14.3-alpha.1.vsix.zip)

**Comment by jrudley** [comment]
That fixed it! Let me do some tests and will report back.

**Comment by jrudley** [comment]
My deployments and tests are passing. Thanks for a quick fix.

**Comment by alexweininger** [comment]
Hi, could you try this one last time. We want to double check before we release. Thanks!

[vscode-azurefunctions-1.14.3-alpha.2.vsix.zip](https://github.com/microsoft/vscode-azurefunctions/files/15169052/vscode-azurefunctions-1.14.3-alpha.2.vsix.zip)

**Comment by jrudley** [comment]
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/f162f603-69cf-4d51-8490-7500674ca911)
Still works for me. Deployments succeeding and can interact with the function within vscode.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/1934411/77412f86-54be-4416-87b4-298d6a71400a)

**Comment by alexweininger** [comment]
Thank you very much for testing these. Sorry that it wasn't working. We are going to release the fix today.

**Comment by zihanfangms** [comment]
Hi @alexweininger , I'm facing the same issue, and I tried to install the vscode-azurefunctions-1.14.3-alpha.2.vsix, but it still doesn't work.
