### ISSUE TITLE
Running multiple Azure Functions Locally

### ISSUE THREAD

**Issue by reggieboyYEAH** [Microsoft/vscode-azurefunctions#413]
I was trying to run multiple function projects at the same time in different vscodes.
using `func host start -n=XXXX`

But when I run the 2nd function project
I am getting a 
`Starting inspector on 127.0.0.1:5858 failed: address already in use` error message

I am using version
`azure-functions-core-tools/2.0.1-beta.25`

Anyone can help?

**Comment by EricJizbaMSFT** [comment]
I don't think the func cli supports running multiple projects at the same time. I get this when I try to run 'func host start' a second time:
![screen shot 2018-06-18 at 11 09 52 am](https://user-images.githubusercontent.com/11282622/41553956-24122f32-72e8-11e8-814d-29fa494dcef5.png)

I would recommend filing an issue on the func cli as I don't think there's anything we can do about it in VS Code: https://github.com/Azure/azure-functions-core-tools
