### ISSUE TITLE
There is no instruction for the step "Enter the maximum instance count"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4132]
**OS:** Windows 10
**Build Version:** 20240514.1
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Azure Functions: Create Function App in Azure... (Advanced) -> Input a function app name -> Select the hosting plan "Flex Consumption (Preview)" -> Select the location "East Asia" -> Select a runtime stack -> Select an instance memory size.
2. Check whether there is an instruction for the next step or not.

**Expect:**
There is an instruction for the next step, such as "Enter the maximum instance count".

**Actual:**
There is no instruction for the step "Enter the maximum instance count".
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/19ecb894-c28b-495d-b258-7602be3c57a0)

**More Info:**
Delete the default count "100", there is a tooltip "Enter the maximum instance count" for this step.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/10fa1828-1df1-430f-ac97-c3cf169000c9)

**Comment by nturinski** [comment]
Add the placeholder to the initial enter confirm prompt.
