### ISSUE TITLE
Fail to create a containerized function app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4136]
**OS:** All
**Build Version:** 1.14.4-alpha.0
**Regression:** Previous Release

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Create a containerized function app.
3. Check whether succeeds to create a containerized function app.

**Expect:**
Succeed to create a containerized function app.

**Actual:**
Fail to create a containerized function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/e22c39fc-df24-4196-bad8-a9ef6f37122d)

**More Info:**
1. This issue reproduces when creating a basic or advanced containerized function app.
2. There is a similar closed bug https://github.com/microsoft/vscode-azurefunctions/issues/4002.

**Comment by nturinski** [comment]
I believe that I fixed that in this commit: https://github.com/microsoft/vscode-azurefunctions/pull/4130/commits/e324d96069869333b5be908faaae08d8b68196ae
