### ISSUE TITLE
Not usable | Dependency Loop

### ISSUE THREAD

**Issue by PlaySkyHD** [microsoft/vscode-azurefunctions#4137]
Hello,
when I start my VS code again, I get the message as shown in the screenshot that there is a dependency loop.
How can I solve this problem?

![image](https://github.com/microsoft/vscode-azurefunctions/assets/57559666/106a5442-8f42-4b72-aef5-901e8bd4dd19)

**Comment by alexweininger** [comment]
You can fix this issue by updating your VS Code to the latest version, and then making sure both the Azure Account and Azure Resource extensions are updated too. See https://github.com/microsoft/vscode-azure-account/issues/966 for more info.
