### ISSUE TITLE
experience

### ISSUE THREAD

**Issue by goarme** [Microsoft/vscode-azurefunctions#414]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.createFunction
Error type: Error
Error Message: Unable to write to Folder Settings because no resource is provided.

Version: 0.9.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@goarme can you detail how you got into this situation?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information

**Comment by Eric-Fang** [comment]
Need to open a workspace to avoid this problem.
