### ISSUE TITLE
[Suggestion] It would be better to remove the containerized function app when executing "Azure Functions: Deploy to Azure..." command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4146]
**OS:** All
**Build Version:** v1.14.4-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a containerized function app.
2. F1 -> Select "Azure Functions: Deploy to Azure...".
3. Check whether containerized function app shows in the function app list.

**Actual:**
The containerized function app shows in the function app list.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/d4fd0cf2-60e5-4f42-935a-e326ffc45f9d)

**Suggestion:**
It would be better to remove the containerized function app when executing "Azure Functions: Deploy to Azure..." command.

**More Info:**
1. Fail to execute "Deploy to Azure..." command for a containerized function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/4e3722ae-7eb7-41c8-b2a5-41a70cfaa3bb)
2. The containerized function app still shows in the list when executing other commands, such as "Deploy to Function App", "Start Streaming Logs", "Start/Restart/Stop", "Configure Deployment Source"...

**Comment by MicroFish91** [comment]
I believe @motm32  has already put in a fix for this.
