### ISSUE TITLE
The function still exists under the slot after swapping it with a clean slot

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#4148]
**OS:** All
**Build Version:** v1.14.4-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a Linux Node Function App with App Service Plan host plan -> Create two slots (slot1 and slot2) to it.
2. Deploy a JavaScript project to the slot1.
3. Swap slot1 with slot2.
4. Check whether there is no function under the Functions node of the slot1 after swapping slots.

**Expect:**
There is no function under the Functions node of the slot1.

**Actual:**
The function still exists under the slot1.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/f5abda90-e517-4e4f-9fb1-47d14004829f)

**Comment by MicroFish91** [comment]
Does refreshing the parent node fix the issue?

**Comment by v-xinda** [comment]
@MicroFish91 verified this issue with the build 1.15.1-alpha.0, it doesn't reproduce for now.
