### ISSUE TITLE
Successful deploy to azure but no working function (v2)

### ISSUE THREAD

**Issue by geertdoornbos** [Microsoft/vscode-azurefunctions#415]
I followed the steps described here, only difference is language (c#): https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions
Function app runs flawless locally.

After successful deploy, the portal does show the app, but does not show my function.
I can see and edit the function with the App Service Editor.

Am I missing bindings? routes?

**Comment by EricJizbaMSFT** [comment]
@geertdoornbos I occasionally have problems if I'm deploying to a brand new function app right after it was created. Was yours a new function app? It usually works if I wait a little bit before deploying or just deploy again.

If it's still not working, could you post the deployment log?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
