### ISSUE TITLE
Deploy to Azure (Function App) fails for a function containerized project

### ISSUE THREAD

**Issue by raorugan** [microsoft/vscode-azurefunctions#4160]
Currently Deploy to Azure operation  takes in user sub details and target function app name and just hangs. It  does not throw any error or anything . this is not a good experience for end customers as it does not provide any guidance /message on next set of actions user is expected to take. It just hangs in there.

**Comment by motm32** [comment]
This command is not supported for containerized function apps. We need to make sure to filter out containerized function apps when users are asked to pick a function app to deploy to.

**Comment by motm32** [comment]
We have decided to just change the error message to say that deploying to containerized function apps is not supported. This also includes a learn more link to how users can deploy. Please refer to https://github.com/microsoft/vscode-azurefunctions/pull/4182 for more info.
