### ISSUE TITLE
not able to test the function locally

### ISSUE THREAD

**Issue by saikumarr95** [microsoft/vscode-azurefunctions#4161]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.executeFunction
Error type: Error
Error Message: Failed to connect. Make sure your project is [running locally](redacted:url

Version: 1.15.0
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:5184209
rejected extension.bundle.js:2:5182865
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
