### ISSUE TITLE
Start Python Function in debug mode from the CLI

### ISSUE THREAD

**Issue by Falven** [microsoft/vscode-azurefunctions#4164]
Is it possible to start the function host in debug mode from the command line (not from a task)?
I've tried:

- `func start --verbose`
- `func start --inspect=9091 --verbose`
- `func host start --verbose --language-worker -- --inspect=9091`
```
Language Worker Process exited. Pid=46434.
python3 exited with code 2 (0x2). .
```

But attempting to attach yields:

`connect ECONNREFUSED 127.0.0.1:9091`

This is not so when starting as a task.

**Comment by nturinski** [comment]
Hi @Falven

I'm not sure if you can start the Functions project from the CLI directly and then attach to it. I'm not sure how but you would have to alter your `launch.json`.

The extension currently has no plans to support this. I know that the extension just runs the `func host start` command though, we don't include any of those flags, for what it's worth.
