### ISSUE TITLE
Unable to find subscription

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-azurefunctions#417]
_From @jleach on June 4, 2018 16:5_

Error: Unable to find Subscription with name `my-subscription-id-here`

I signed up for a free trial over the weekend and I get this error. I'm not using a proxy, I've tried on several different internet connections. VSCode seems to be able to create storage account but can not deploy.

- VSCode 1.23.1
- Latest available extension version.

When I try and deploy a function I see error 51004 in the JSON of the Output window; I also see `"statusCode":404},` in there so something is not found.

I also tried with a Pay-As-You-Go and it still says it can not find my subscription. :(

_Copied from original issue: Microsoft/vscode-azure-account#60_

**Comment by chrmarti** [comment]
_From @jleach on June 7, 2018 18:39_

Still and issue with VSCode 1.24.0.

**Comment by chrmarti** [comment]
@jleach Is there anything in the console? (Help > Developer Tools) /cc @EricJizbaMSFT

**Comment by chrmarti** [comment]
_From @jleach on June 8, 2018 15:38_

Just one INFO message "INFO no standard startup: not just one text editor"; nothing under Verbose, Warnings or Error.  When I switched from Free to Pay-As-You-Go VSCode did update the name of my subscription type internally (I now see Pay-As-You-Go in VSCode).

If I hit the + button beside AZURE: App Service the drop-down does show my Pay-As-You-Go account along with the UUID. Its selected. Selecting / Unselecting has no impact on the message. When I first start VSCode it and expand the subscription like it takes a second - probably to make a network call?

LMK if I can do anything to more aggressively debug.

**Comment by chrmarti** [comment]
_From @jleach on June 8, 2018 16:1_

Ok, So rather than create a function and try to deploy it I created an Azure WebService (App Service) and deployed it. Now that my account is not completely empty - the error is *gone* under both Functions and App Service. I then stopped and deleted the service - no error. Restarted VSCode and created a new Project/Workspace - again no error. Seems to have fixed it.

Looks like VSCode / Azure have a problem with fresh accounts that are completely empty; something must be created/updated when you deploy your first 'thing'. I tried to Deploy a function first and that didn't seem to help although perhaps I did it wrong. In any case deploying a WS seems to fix it.

Hope this helps.

**Comment by chrmarti** [comment]
The only guess I have is that a resource provider should have been registered, but wasn't at the time. We should try to reproduce with a new account.

**Comment by jlyman** [comment]
I can confirm the same experience as @jleach. I have other Azure accounts, but starting a fresh one and running the typical steps to start playing with some Azure functions results in the "Unable to find subscription" error, with nothing in the console.

Creating a Function App (consumption plan) manually in the Azure Portal, unrelated to the project that I'm about to start playing with, solved the subscription locating issue. After creation, refreshing the Azure panel got the subscription and the new temp app to show up, and allowed the deployment of the app created in Code.

**Comment by thetre97** [comment]
Just a note to say I also had this issue, and the above solutions worked.
The Cosmos DB extension also showed the same error message.

**Comment by EricJizbaMSFT** [comment]
This was fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/536 and will be included in the next update

Until then, please use the workarounds listed above - thanks for the help with that

**Comment by thetre97** [comment]
Great, thanks :+1:

**Comment by EricJizbaMSFT** [comment]
@thetre97 that being said, I was only able to repro this in the app service and functions extension. Even with a new subscription, I couldn't repro with Cosmos. Please file an issue here if you can still repro that: https://github.com/Microsoft/vscode-cosmosdb/issues
