### ISSUE TITLE
Unable to Deploy to Function App

### ISSUE THREAD

**Issue by RRanks** [microsoft/vscode-azurefunctions#4176]
Inconsistent results when I try Deploy to Function App.. I am getting stuck on this where it fails to complete the Zipping of the package. Sometimes it works but the majority it is like this... where I have to keep trying till it works.

First attempt

10:05:06 PM FunctionApp-FA: Starting deployment...
10:05:06 PM FunctionApp-FA: Creating zip package...
10:05:09 PM FunctionApp-FA: Zip package size: 771 kB
10:06:07 PM: Error: The operation was aborted.

Next attempt:

10:16:24 PM FunctionApp-FA: Starting deployment...
10:16:25 PM FunctionApp-FA: Creating zip package...
10:16:28 PM FunctionApp-FA: Zip package size: 771 kB
10:17:10 PM FunctionApp-FA: Fetching changes.
10:17:11 PM FunctionApp-FA: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\34r5aisn.zip (0.74 MB) to C:\local\Temp\zipdeploy\extracted
10:17:52 PM: Error: The operation was aborted.

3rd Time Lucky....

1:56:49 AM FunctionApp-FA: Starting deployment...
1:56:49 AM FunctionApp-FA: Creating zip package...
1:56:52 AM FunctionApp-FA: Zip package size: 773 kB
1:57:02 AM FunctionApp-FA: Updating submodules.
1:57:03 AM FunctionApp-FA: Preparing deployment for commit id '368eefeb61'.
1:57:04 AM FunctionApp-FA: Generating deployment script.
1:57:04 AM FunctionApp-FA: Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"').
1:57:05 AM FunctionApp-FA: Running deployment command...
1:57:05 AM FunctionApp-FA: Command: "C:\home\site\deployments\tools\deploy.cmd"
1:57:06 AM FunctionApp-FA: Handling Basic Web Site deployment.
1:57:06 AM FunctionApp-FA: Creating app_offline.htm
1:57:06 AM FunctionApp-FA: KuduSync.NET from: 'C:\local\Temp\zipdeploy\extracted' to: 'C:\home\site\wwwroot'
1:57:06 AM FunctionApp-FA: Deleting app_offline.htm
1:57:06 AM FunctionApp-FA: Finished successfully.
1:57:06 AM FunctionApp-FA: Running post deployment command(s)...
1:57:07 AM FunctionApp-FA: Triggering recycle (preview mode disabled).
1:57:07 AM FunctionApp-FA: Deployment successful.
1:57:35 AM FunctionApp-FA: Syncing triggers...
1:57:39 AM FunctionApp-FA: Querying triggers...
1:57:48 AM FunctionApp-FA: No HTTP triggers found.

**Comment by alexweininger** [comment]
The "Error: The operation was aborted." was also reported by https://github.com/microsoft/vscode-azurefunctions/issues/3805#issuecomment-2122992941

The error is happening after the zip has been created, and sounds like an error from the deploy service itself. It's interesting that the zip size is different when it works. Is it always 773 kB when it works? Have you been able to deploy consistently in the past?
