### ISSUE TITLE
Typo in PowerShell Functions Template Code  ("Porperty" instead of "Property")

### ISSUE THREAD

**Issue by thsparks** [microsoft/vscode-azurefunctions#4181]
The run.ps1 powershell template code for a timer-triggered function has a typo, "porperty" instead of "property":

https://github.com/microsoft/vscode-azurefunctions/blob/aef35edeaac21748bd8e37186aa7c5d2bfb52a4b/resources/backupTemplates/script/~3/templates/templates.json#L3523
https://github.com/microsoft/vscode-azurefunctions/blob/aef35edeaac21748bd8e37186aa7c5d2bfb52a4b/resources/backupTemplates/script/~4/templates/templates.json#L3523

**Comment by nturinski** [comment]
Thanks for reporting this. Could you file the issue here: https://github.com/Azure/azure-functions-templates/

We don't actually control the templates, that's done by this team.

**Comment by thsparks** [comment]
Thanks. Looks like it's already been fixed there: https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/TimerTrigger-PowerShell/run.ps1#L7
