### ISSUE TITLE
Set node version when setting runtime version

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#419]
The Functions runtime takes dependency on node at specific versions. Right now, when updating the runtime on Azure, I believe we are only updating the runtime, but we need to also update the node version using `WEBSITE_NODE_DEFAULT_VERSION`.

When setting functions runtime to **v1**, use node version **6.5.0**
When setting functions runtime to **v2** use node version **8.11.1**

I'm talking with the Functions team to find a flexible way to make sure we always choose the correct node version. I'll keep this issue updated as that conversation progresses.

Edit: Soon, v2 will expect node@10 and the Functions team may incorporate this version requirement into the typical CLI feed.

**Comment by fiveisprime** [comment]
Got a report of this offline. Manifested as a rather cryptic error to the user.

```sh
018-06-15T17:04:00.798 [Information] Executing 'Functions.HelloBuzzJS' (Reason='This function was programmatically called via the host APIs.', Id=12b04676-d8ef-4264-82fc-0704c58658c9)
2018-06-15T17:04:00.806 [Error] System.Private.CoreLib: Exception while executing function: Functions.HelloBuzzJS. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 5400 exited with code 1) (Worker process with pid 4424 exited with code 1) (Worker process with pid 4572 exited with code 1). Worker process with pid 5400 exited with code 1.
2018-06-15T17:04:00.887 [Error] Executed 'Functions.HelloBuzzJS' (Failed, Id=12b04676-d8ef-4264-82fc-0704c58658c9)
```

Updating the node version corrected the issue

**Comment by jeffhollan** [comment]
FYI the feed item is being tracked here https://github.com/Azure/azure-functions-tooling-feed/issues/2

**Comment by fiveisprime** [comment]
Looks like a PR for this is open now https://github.com/Azure/azure-functions-tooling-feed/pull/6

**Comment by fiveisprime** [comment]
This is marked as available in production now.
