### ISSUE TITLE
Deploy to Azure: Subscriptions list is empty

### ISSUE THREAD

**Issue by anthonychu** [Microsoft/vscode-azurefunctions#420]
Repro steps:

* Open an existing Azure Functions project in VS Code.
* Search for and select **Azure Functions: Deploy to Function App**.
* Select current folder.
* The subscriptions list is *empty*.

This seems to happen whether you are already logged into your Azure account or not.

Workaround:

Before initiating deployment to Azure, click on the Azure icon in the Activity Bar. If subscriptions are loaded into the Azure extensions panes, the subscription list will show during deployment.

**Comment by nturinski** [comment]
Thanks for the report @anthonychu.  Definitely appreciate you using the extension.

We have this issue in the azuretools repo here: https://github.com/Microsoft/vscode-azuretools/issues/186 so I'll go ahead and close this as it's an issue for all of our extensions.
