### ISSUE TITLE
Unable to add binding to Nodjs Azure Function Model 4

### ISSUE THREAD

**Issue by AnjanRB** [microsoft/vscode-azurefunctions#4204]
I have created a NodeJS Azure Function using Model 4. I am not able to add binding in VS code, using context menu (right-click & add binding)
I get this error when adding bindings.
"Add binding is not supported for this project type."

![Untitled](https://github.com/microsoft/vscode-azurefunctions/assets/9456407/7116624a-92b1-4cad-9693-9c3d2e6a8d65)

**Comment by MicroFish91** [comment]
You no longer need to keep a `function.json` file for each trigger in the new V4 model as bindings are configured in code!

We will look into improving this error message for users in the future.

**Comment by AnjanRB** [comment]
Thank you for the response. I understand bindings are not maintained in function.json in V4 model.  The option in context menu(right click) suggests developer can add binding (add binding code).

**Comment by AnjanRB** [comment]
Thank you for the response. I understand bindings are not maintained in function.json in V4 model. The option in context menu(right click) suggests developer can add binding (add binding code).
