### ISSUE TITLE
There is an error under the "Functions" node for the PowerShell 7.4 Linux Consumption function app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#4205]
**OS:** Win 10
**Build Version:** 20240704.1
**Regression:** Not a Regression

**Repro Steps:**
1. Create a **PowerShell 7.4 Linux Consumption** function app.
2. Expand the function app -> Expand "Functions" node.
3. Check whether there is no error.

**Expect:**
There is no error.

**Actual:**
There is an error.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/e278f4b0-7dd4-4f9a-88ac-fc124b311401)

**More Info:**
1. Fail to deploy the PowerShell project to the PowerShell 7.4 Linux Consumption function app.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/57662131/ba7c4914-db3d-435f-a181-521892ab6d03)
2. This issue doesn't reproduce for PowerShell 7.4 Windows function app.
3. This issue doesn't reproduce for PowerShell 7.4 Linux function app created with Premium and App Service Plan hosting plans.
4. This issue doesn't reproduce for PowerShell 7.2 function app.

**Comment by MicroFish91** [comment]
This is likely a service side issue that we cannot fix.  We are moving towards flex consumption plans so it is likely users will not run into this problem in the future.
