### ISSUE TITLE
Node Model V4 create HTTP function flow does not prompt for auth level

### ISSUE THREAD

**Issue by hossam-nasr** [microsoft/vscode-azurefunctions#4216]
**Repro:**
1. Create new Node (TypeScript or JavaScript) project
2. When prompted, choose `Model V4`
3. Select HTTP trigger as the template
4. Go through the create project flow

**Expectation:**
User is prompted to choose a function auth level (Anonymous, Function, or Admin), which is plugged into the HTTP template

**Reality:**
No prompt for auth level is made, template defaults to "Anonymous"

**Comment by nturinski** [comment]
Turns out after looking at it again, it was hard-coded to `anonymous` and has no user prompts.

@ejizba Any plans on changing this or was that behavior intentional?

**Comment by ejizba** [comment]
This was on purpose. Fewer prompts and more likely things "just work" for users who are getting started. Plus the resulting function still has authLevel explicitly specified in the code, so it's plenty obvious how to change it for folks that want to

**Comment by hossam-nasr** [comment]
Closing as by design
