### ISSUE TITLE
Azure Extended Function Azure App feature not working properly in Visual Studio Code

### ISSUE THREAD

**Issue by domix1996** [microsoft/vscode-azurefunctions#4220]
I'm trying to upload a project via MS Teams Toolkit, I have the necessary settings set according to the documentation. Not only is your solution misleading (it is version 3.0.0!! or even lower), but version 4.0.0 is recommended!! this is still a project that is supposed to work for MS Teams Toolkit, it is completely incompatible because the Azure App Function functions disappear in the Azure Portal even though they have been implemented!!

![image](https://github.com/user-attachments/assets/18631581-7a40-4e42-91af-f60d26c85157)

And?!??!

**Comment by nturinski** [comment]
@domix1996

This repository is only controlling the Azure Functions extension in VS Code. We don't have any control over what the portal does and what solution the MS Teams Toolkit recommends.

And You may want to file an issue here: https://github.com/OfficeDev/teams-toolkit
