### ISSUE TITLE
No function shows in the Flex Consumption function app after deploying Durable project with "MSSQL/Netherite" durable storage type

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4226]
**OS:** All
**Build Version:** v1.15.2-alpha.0

**Repro Steps:**
1. Create a JavaScript/TypeScript project with Durable function and "MSSQL/Netherite" durable storage type.
2. Create a Node.js Flex Consumption function app.
3. Deploy the project with Durable function to the above Node.js Flex Consumption function app.
4. Expand the Functions node of the Flex Consumption function app.
5. Check whether Durable functions show in the Flex Consumption Functions node.

**Expect:**
Durable functions show in the Flex Consumption function app.

**Actual:**
No function shows in the Flex Consumption function app.
![image](https://github.com/user-attachments/assets/f8c567cb-b7c4-4f7b-a640-2e9f7a7bad03)

**More Info:**
1. The output shows as below after deploying Durable project with "MSSQL/Netherite" durable storage type.
![image](https://github.com/user-attachments/assets/0ddd5f99-e843-43be-8409-02b85f44e88d)
3. This bug does not reproduce after deploying HttpTrigger function or Durable function with Azure Storage durable storage type.

**Comment by alexweininger** [comment]
It seems like the Functions service doesn't support durable which use MSSQL/Netherite on a Flex app.

**Comment by alexweininger** [comment]
Closing as out of scope
