### ISSUE TITLE
Bug Found - 500 Internal Server Error when Changing Azure Function Runtime from VS Code

### ISSUE THREAD

**Issue by wely** [Microsoft/vscode-azurefunctions#423]
I'm not sure if I should raise the issue here or at Function Host, but i've submitted there: https://github.com/Azure/azure-functions-host/issues/3038

**Comment by jeffhollan** [comment]
Correct believe this is a duplicate and fix is here. For mitigation manually update the node version app setting in Azure https://github.com/Microsoft/vscode-azurefunctions/issues/419

**Comment by EricJizbaMSFT** [comment]
Closing as dupe
