### ISSUE TITLE
Ubuntu: 'Create New Project' will make system crash

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azurefunctions#424]
- VSCode Version: 1.24.1
- OS Version: Ubuntu 17.04

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1050213/41833412-cb7faa34-7882-11e8-9963-e9e97554aaa3.png)
1. Click 'Create New Project'
2. Click 'Browse'
3. Folder dialog is opened
4. Then the system crashed (could not do anything on system, system freezes)

Just for your awareness, it is mostly due to https://github.com/Microsoft/vscode/issues/52778

**Comment by EricJizbaMSFT** [comment]
Removing this from tracking. We had a similar issue in our app service extension and we had a workaround to add a small delay: https://github.com/Microsoft/vscode-azureappservice/issues/844

I can see if the issue still repros and try the same workaround

**Comment by EricJizbaMSFT** [comment]
This no longer repros for me - closing
