### ISSUE TITLE
Ability to Suppress Readme tabs

### ISSUE THREAD

**Issue by EvanR-Dev** [microsoft/vscode-azurefunctions#4248]
As of today, creating a function can trigger a readme to be automatically opened as a side tab. For example, creating a Python prog V2 function will do this:
![image](https://github.com/user-attachments/assets/c105c0c7-85da-4355-b545-a916f582194b)

It would be nice to avoid this in some way, either through a VSCode setting or by other means within the Azure Function extension

**Comment by nturinski** [comment]
A couple ideas:

- A setting to turn off all README pop ups upon trigger creation
- Add a code lens that opens the README for the specific trigger type
