### ISSUE TITLE
Standard quickstart python v2.0 deployment from VS code does not work

### ISSUE THREAD

**Issue by bobbytreed** [microsoft/vscode-azurefunctions#4252]
If you just follow the basic instructions for creating a new function and deploying to Azure, the functions never show up. 

Creating placeholder blob for linux consumption function app...
SCM_RUN_FROM_PACKAGE placeholder blob scm-latest-learn-knowledge-service.zip located
Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
Resetting all workers for learn-knowledge-service.azurewebsites.net
Deployment successful. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Remote build succeeded!
[2024-08-29T15:09:52.653Z] Syncing triggers...
Functions in learn-knowledge-service:

![image](https://github.com/user-attachments/assets/d634debf-1a41-4b65-9055-e09c441c4c37)

The same process works just fine if you do it completely through the portal, but in that instance you cannot upload requirements.txt which I need. 

I compared all the files and settings I could see side by side and there were no differences in python/json files.  Further more when I deployed the one created with VS code over top of the one created through the portal, it broke the good AzF deployment, which means the problem is isolated to the VS Code deployment mechanism.

**Comment by MicroFish91** [comment]
Could you please provide a link to the instructions / walkthrough you were following here or could you please provide the exact repro steps?  Thank you
