### ISSUE TITLE
Initialize empty proxies.json when creating app

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#426]
[Proxies work locally in the v2 runtime now](https://blogs.msdn.microsoft.com/appserviceteam/2018/06/26/function-proxies-now-available-in-functions-version-2-x/) so let's give people a good starting point.

Initialize a `proxies.json` along with the app with the schema and empty proxies object.

```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {}
}
```

That will give them intellisense for working with proxies if they choose.

**Comment by EricJizbaMSFT** [comment]
Re-opening this and moving to the next milestone. See https://github.com/Microsoft/vscode-azurefunctions/pull/472 for more info
