### ISSUE TITLE
Azure Blob Storage Trigger (using Event Grid) template not showing for all languages

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-azurefunctions#4308]
The Azure Blob Storage Trigger (using Event Grid) template is not showing for Python v2 projedts. It is also not showing for .NET inproc projects either.
![Image](https://github.com/user-attachments/assets/f9233237-3310-47b0-a6c0-4637e8bc3423)

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/4297. Fix will get released in next release
