### ISSUE TITLE
"Start debugging to update this list..." instead of the function shows in WORKSPACE view when debugging a JavaScript/TypeScript V4 project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4312]
**OS:** All
**Build Version:** v1.15.5-alpha.0
**Regression:** Previous Release

**Repro Steps:**
1. Create a JavaScript/TypeScript V4 project with Http Trigger template in VS Code.
2. Debug this project.
3. Navigate to WORKSPACE view -> Expand the Functions node.
4. Check whether the Http Trigger function shows well in Functions node.

**Expect:**
The Http Trigger function shows well in Functions node.
![Image](https://github.com/user-attachments/assets/86366b8f-eea3-400c-b277-d78449912a9a)

**Actual:**
"Start debugging to update this list..." instead of the function shows in Functions node.
![Image](https://github.com/user-attachments/assets/5c4751f5-9a0f-4142-bb61-397e81efdfec)

**More Info:**
1. This issue still reproduces after clicking "Start debugging to update this list..." to start debugging again.
2. This issue also reproduces for Python V2 project.
3. This issue does not reproduce on the current released Functions extension V1.15.4.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/4320
