### ISSUE TITLE
Fail to debug a C# function project with an error "Failed to detect azFunctions Task"

### ISSUE THREAD

**Issue by v-meilei** [microsoft/vscode-azurefunctions#4313]
**OS:** All
**Build Version:** v1.15.5-alpha.0
**.NET Version:** 8.0.403
**Regression**: Previous release(v1.15.4)

**Repro Steps:**
1. Create and open a .NET 8.0 C# project with "HTTP trigger" function.
2. Debug the above project.
3. Check whether succeeds to debug the C# project or not.

**Expect:**
Succeed to debug the C# project without any error.

**Actual:**
Fail to debug the C# project with an error "Failed to detect AzFunctions Task".
![Image](https://github.com/user-attachments/assets/7f889633-858f-474e-8583-f67358e5217f)

**More Info:**
This issue also reproduces when debugging a .NET 9.0/7.0 C# project.

**Comment by nturinski** [comment]
> This issue also reproduces on the current released Function extension v1.15.4.

This seems to work fine on v1.15.4 for me. I think this was introduced later.

**Comment by v-meilei** [comment]
> > This issue also reproduces on the current released Function extension v1.15.4.
> 
> This seems to work fine on v1.15.4 for me. I think this was introduced later.

Sorry for my mistake, this issue doesn't reproduce on v1.15.4. I‘ve updated the bug content.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/4320
