### ISSUE TITLE
Can I undo an overwrited deployment from VS Code?

### ISSUE THREAD

**Issue by khha** [microsoft/vscode-azurefunctions#4318]
I created before 3 functions in my Azure functions in the browser. Today I tested the Azure Function extension in VS Code and try to deploy to the same Azure Function. It gives me the popup message:

 **_"are you sure you want to deploy to "nameOfMyFunction"? This will overwrite any previous deployment and cannot be undone"._** 

Now my 3 functions are gone. I see just 1 new function which I deployed from VS Code. Can get my 3 functions back?

**Comment by MicroFish91** [comment]
Unfortunately, there is no way for us to have the service reverse the deployment operation.  That is a big part of why we usually display that confirmation window :(

That said, if you have your previous deployment in source control, we recommend going back to the saved commit and redeploying from there if at all possible!

**Comment by khha** [comment]
Thank you.
