### ISSUE TITLE
Default Isolated HTTPWebrequest does not run

### ISSUE THREAD

**Issue by martinpyman** [microsoft/vscode-azurefunctions#4324]
I've been looking into upgrading a number of Azure Functions to use the isolated model with not much success, I thought I would just try and make a brand new one.

I'm using Visual Studio Code.

I have .net sdk 8 installed

I create a function Project using VS Code:
C# - > .NET 8.0 Isolated LTS -> Http Trigger > Default Name > Default Namespace > Anonymous Function

I hit F5 to debug the new function

I receive the following:
```
[2024-11-11T18:23:38.957Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
``` 

![Image](https://github.com/user-attachments/assets/b5cdf964-ae7c-4859-8453-8d1dfa8fbf54)

I cant access the Azure Function and seems to have failed.

Any help would be immensely appreciated!

Martin

**Comment by martinpyman** [comment]
On a third completely fresh PC the code runs without issue. I noticed that the "Azure Functions Core Tools" were at an older version on the broken devices, I wasn't sure on the best way to update these so I installed the the tools from here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local

The azure function now runs, shouldn't there be a check in VS Code on the versions and warn the user to update?

Posting the reply in case this helps someone

**Comment by MicroFish91** [comment]
![Image](https://github.com/user-attachments/assets/b4804e99-c514-4b33-88da-4422b616a92e)
![Image](https://github.com/user-attachments/assets/57a79d26-5ac1-46f8-95d5-0310a713c882)

Hi martinpyman,

We warn users as long as this warning box is checked in user settings.  This should be set to true by default. If you're still able to reproduce, make sure that you did not set this to false by accident (usually by clicking "Don't show again").
