### ISSUE TITLE
Default to Flex Consumption

### ISSUE THREAD

**Issue by nzthiago** [microsoft/vscode-azurefunctions#4335]
Flex Consumption is the new default hosting plan for Azure Functions with new capabilities. In this Visual Studio Code extension we should:

* Have Flex Consumption at the top of the choices and be the default in the Advanced create flow. The order of preference is as per [this doc](https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale) - Flex Consumption, Premium Plan, Dedicated Plan, Container Apps, Consumption
* Have Flex Consumption replace Consumption as the hosting plan used for the simple create flow, using the defaults for Flex Consumption as per the Stacks API and what's already used as the defaults for Flex Consumption in this extension

**Comment by pragnagopa** [comment]
@MicroFish91 - do we have ETA for this?

**Comment by nturinski** [comment]
@pragnagopa We don't currently have a release date for Functions. What time do you need this to be released?

**Comment by nzthiago** [comment]
As soon as possible.
