### ISSUE TITLE
Timed out waiting for authentication provider to register

### ISSUE THREAD

**Issue by selvaonline** [microsoft/vscode-azurefunctions#4345]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.16.1
OS: darwin
OS Release: 24.1.0
Product: Cursor
Product Version: 1.93.1
Language: en

**Comment by alexweininger** [comment]
Hi please see this thread for issues with Cursor https://github.com/microsoft/vscode-azure-account/issues/897
