### ISSUE TITLE
Changes to application settings do not take effect within 3 seconds in a containerized function app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4350]
**OS:** Win 11
**Build Version:** 20241210.1

**Repro Steps:**
1. Create a containerized function app in VS Code.
2. Add an application setting for the above containerized function app.
3. Check whether the new application setting is added within 3s in a containerized function app or not.

**Expect:**
The new application setting is added within 3s.

**Actual:**
The new application setting is added after 10s.

**More Info:**
This issue also reproduces when executing rename/edit/delete application settings commands in a containerized function app.

**Comment by MicroFish91** [comment]
We believe this delay is happening on the service side, and likely there isn't much we can do to improve this.  Closing unless we discover otherwise
