### ISSUE TITLE
Possible debugging regression in beta.31

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#438]
See: https://github.com/Azure/azure-functions-core-tools/issues/557

I had to make the same change (adding `"NODE_OPTIONS": "--inspect=5858"` to local settings) to get debugging working on beta.31 on Windows with node@8.11.3.

May also be the same issue as #436 

//cc @fabiocav @mhoeger

**Comment by jdneo** [comment]
Here is the workaround for those users who cannot debug Java function with Azure-Functions-Core-Tools@2.0.1-beta.31

1. In `loca.settings.json`, add `"FUNCTIONS_WORKER_RUNTIME": "java"`.
2. Add `--language-worker -- \\\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005\\\"` in the `tasks.json` in `.vscode` folder. For example:

```
"windows": {
    "command": "powershell -command \"mvn clean package -B; func host start --language-worker -- \\\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005\\\" --script-root \\\"target/azure-functions/{YOUR FUNCTION NAME}/\\\"\""
},
```

**Comment by rdtiv** [comment]
Similar issue with JavaScript. Any workaround? thx, -dan

![debugerror](https://user-images.githubusercontent.com/39449030/42650995-9d49fad0-85d3-11e8-97f5-e928f63217c6.PNG)

**Comment by EricJizbaMSFT** [comment]
@rdtiv please try adding `"NODE_OPTIONS": "--inspect=5858"` to your local.settings.json file

**Comment by rdtiv** [comment]
@EricJizbaMSFT Thank you!!! Now i see the power of debugging Azure Functions in VSCode.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/478

See [here](https://github.com/Microsoft/vscode-azurefunctions/blob/master/docs/debugConfig.md) for more info
