### ISSUE TITLE
Deploy as Zip is not deploying node_modules

### ISSUE THREAD

**Issue by bertique** [Microsoft/vscode-azurefunctions#44]
When using the deploy as zip feature, it is not deploying the node_modules folder to the destination. As a result, the function is missing the modules. You'd have to manually go into the server through Kudu and run npm i. In comparison, the Function cli copies all folders (including node_modules) when doing publish.

**Steps to reproduce:**
1. Create function app in Code
2. Add node modules, e..g npm install redis
3. Add reference to redis in function code
4. Deploy as zip from Code
5. Check function in Azure: node_modules is not present.

**Comment by EricJizbaMSFT** [comment]
@bertique We actually released some fixes for zipdeploy this morning. Can you try out v0.1.1 of the extension and see if that fixes your issue?

See here for more info:
https://github.com/Microsoft/vscode-azurefunctions/releases/tag/v0.1.1

**Comment by bertique** [comment]
Nice, works great now. Thanks! Closing this
