### ISSUE TITLE
Java templates don't include right .gitignore

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#453]
Realize this may need to move to the Java maven archetype (not sure) but the `.gitignore` included needs the following to be valid:

```
local.settings.json
bin/
obj/
```

Will keep out the local settings which shouldn't be in source control, and any binaries that may be installed as extensions

**Comment by jdneo** [comment]
@jeffhollan Thank for the feedback. Yes you are right this should be a issue related with Java maven archetype. Move it to: https://github.com/Microsoft/azure-maven-archetypes/issues/37
