### ISSUE TITLE
Load more picker panel configuration when assigning deployment repository 

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode-azurefunctions#455]
Nice to have:

Is this possible to rework the pick a repository dialog to:
- change the behavior after clicking the 'load more' option to not close and simply append the new repositories
- provide an option to increase 'per page' fetch size?

On some scenarios user have a lot of repositories, using current pick a repo UX pattern is not very feasible in VSCode, while it works in the Portal UI. Click 'load more' and dialog closes, so open it back, scroll all way down, just to click 'load more' again and repeat entire path.

![load-more-picker](https://user-images.githubusercontent.com/14539/42810715-dfea69f4-89b8-11e8-8c2e-9c8ed5b53fbc.gif)

Thanks!

**Comment by EricJizbaMSFT** [comment]
Adding a setting for the 'per page' fetch size should be easy. @nturinski please investigate for the current milestone

The other behavior might be more time-consuming to implement

**Comment by EricJizbaMSFT** [comment]
Improved in https://github.com/Microsoft/vscode-azuretools/pull/310 and https://github.com/Microsoft/vscode-azuretools/pull/334
