### ISSUE TITLE
The 'Functions' node fails to list uploaded functions from the portal

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode-azurefunctions#456]
I'm unable to list the Functions in the extension panel at all and it always ends with en error. This happens with a function app that was backed by Github repository, now set to 'none' for deployment options. I've used the `func` cli to create and use functions locally.

Repro steps:
- open function app in the VSCode
- open the Azure Functions panel and locate the same function app
- add new function (http trigger)
- use upload to portal to sync with portal (the functions are uploaded successfully)
- try to expand the 'Functions' node

Note that the other function apps (not yet edited), are correctly listed:

![image](https://user-images.githubusercontent.com/14539/42811489-0992c0ec-89bb-11e8-8410-97ca4e5a052b.png)

```
12:06:40 PM blazejewicz-funcs: Deployment successful.
12:06:53 PM blazejewicz-funcs: Waiting for long running command to finish...
>>>>>> Deployment to "blazejewicz-funcs" completed. <<<<<<

Error: An error has occurred.
```

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.1
OS: darwin
Runtime: Node

**Comment by EricJizbaMSFT** [comment]
@peterblazejewicz can you describe how you created the project that you deployed?

For example - if you create a simple, clean project directly from VS Code, add just an HttpTrigger, and deploy - does it work?

Also does the deployment log have something like "Syncing 0 function triggers with payload size 2 bytes successful."? Does it say how many triggers it found? Was it the right amount?

If this only happens in your more complex project and the Github repo is public, I'd be happy to try deploying and seeing if I can repro the issue myself.

**Comment by peterblazejewicz** [comment]
@EricJizbaMSFT 

So it happens only with already existing function app. I've had a local repo with the existing function app (git repositiory) and I've been trying the functions extension with that app. The deployment worked (or seemed to work) correctly, but the refresh never showed the functions.

When I start from scratch using the extension to create function app, deploy and add functions and then refresh, it works OK and I'm seeing the functions after deployment correctly synced:

![image](https://user-images.githubusercontent.com/14539/42911645-29a20154-8aec-11e8-84b6-7fe898fba9f9.png)

I'm also seeing other function app details correctly that was never developed locally:

![image](https://user-images.githubusercontent.com/14539/42911681-4b4778fc-8aec-11e8-9174-3fc71d7111dc.png)

**Comment by EricJizbaMSFT** [comment]
@peterblazejewicz we switched from kudu apis to ARM apis in this PR: https://github.com/Microsoft/vscode-azurefunctions/pull/577. I'm hoping that fixes you, but I couldn't repro your problem to test for sure. You can run "Install from VSIX..." from the command palette with this vsix to try it out: https://azcode.blob.core.windows.net/vscode-azurefunctions/master/1716/vscode-azurefunctions-0.10.3-alpha.vsix or just wait until we release in a few weeks.

Optimistically closing, but re-open if necessary.
