### ISSUE TITLE
Functions doesn't work properly 

### ISSUE THREAD

**Issue by JeffreyGarrett** [Microsoft/vscode-azurefunctions#459]
Repro steps:
Create an azure function and upload it.  use http template. During uplaod the functions created but code is not refreshed and the endpoint doesn't work. 

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.1
OS: darwin

**Comment by peterblazejewicz** [comment]
seems similar to: #456

**Comment by EricJizbaMSFT** [comment]
@JeffreyGarrett was this for a Node or C# project? If C#, it could actually be this issue: https://github.com/Microsoft/vscode-azurefunctions/issues/451

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
