### ISSUE TITLE
VSCode fails to attach to func process locally (macOS)

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode-azurefunctions#460]
This could depend on platform, there is similar topic here: #436 

To reproduce:
- follow officail guide here: https://code.visualstudio.com/tutorials/functions-extension/getting-started
- on the step 'run your app locally': https://code.visualstudio.com/tutorials/functions-extension/run-app the VSCode never attach to the process and always ends with:

> Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858).

This happens when following step-by-step from the docs.

I've tried to modify the VSCode settings according to various threads on the VSCode repo:
https://github.com/Microsoft/vscode/issues/40767
https://github.com/Microsoft/vscode-recipes/issues/113
but no dice.

I've even tried to modify task:

```json
"command": "func",
      "args": [
        "host",
        "start",
        "--debug=VSCode",
        "--inspect=5858"
      ],
```
as this adds a line to output:
```
func host start --debug=VSCode --inspect=5858
```
and:
```
launch.json for VSCode configured.
```

```
Azure Functions Core Tools (2.0.1-beta.31)
Function Runtime Version: 2.0.11888.0
node --version v10.6.0 (ships with macOS updates)
```

**Comment by EricJizbaMSFT** [comment]
@peterblazejewicz There's a known bug in 2.0.1-beta.31 for node functions. Please try adding "NODE_OPTIONS": "--inspect=5858" to your local.settings.json file. See https://github.com/Microsoft/vscode-azurefunctions/issues/459 for more information and let me know if that doesn't work for you

**Comment by peterblazejewicz** [comment]
@EricJizbaMSFT 
Right on the spot. You're correct.
For reference:

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "NODE_OPTIONS": "--inspect=5858"
  },
  "ConnectionStrings": {}
}
```
Sorry for not finding the #438 via search, I've used the error message text. 
Closing this as dup.
Thanks!
