### ISSUE TITLE
Include backup templates with extension

### ISSUE THREAD

**Issue by psanchez1982** [Microsoft/vscode-azurefunctions#462]
Repro steps:
Tried to create and azure function with C# and reported 504 Gateway Timeout. There's a problem with the region, I'm from Chile and when I tried to create with Javascript and installed the npm package reported the same 504 error with azureedge.net, but I have a Linux virtual machine connected to West US, connected via SSH and tried to download the final manualy and was OK. To problem may be with some Internet Providers from Chile and the CDN.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Command "dotnet restore --packages . --source https://www.myget.org/F/azure-appservice/api/v3/index.json --source https://api.nuget.org/v3/index.json" failed with exit code "1":
  Restoring packages for C:\Users\psanchez\AppData\Local\Temp\7a84b73ba0\packages.csproj...
  Failed to download package 'microsoft.azurefunctions.projecttemplates.2.0.0-beta-10167' from 'https://www.myget.org/F/azure-appservice/api/v3/flatcontainer/microsoft.azurefunctions.projecttemplates/2.0.0-beta-10167/microsoft.azurefunctions.projecttemplates.2.0.0-beta-10167.nupkg'.
  Response status code does not indicate success: 504 (Gateway Timeout).
  Failed to download package 'microsoft.azurefunctions.projecttemplates.2.0.0-beta-10167' from 'https://www.myget.org/F/azure-appservice/api/v3/flatcontainer/microsoft.azurefunctions.projecttemplates/2.0.0-beta-10167/microsoft.azurefunctions.projecttemplates.2.0.0-beta-10167.nupkg'.
  Response status code does not indicate success: 504 (Gateway Timeout).
  Failed to download package 'azure.functions.templates.2.0.0-beta-10167' from 'https://www.myget.org/F/azure-appservice/api/v3/flatcontainer/azure.functions.templates/2.0.0-beta-10167/azure.functions.templates.2.0.0-beta-10167.nupkg'.
  Response status code does not indicate success: 504 (Gateway Timeout).
C:\Program Files\dotnet\sdk\2.1.200\NuGet.targets(114,5): error : Failed to download package 'microsoft.azurefunctions.projecttemplates.2.0.0-beta-10167' from 'https://www.myget.org/F/azure-appservi

**Comment by EricJizbaMSFT** [comment]
We don't really control the gateway timeout.  However, we can mitigate this by including backup templates with our extension.
