### ISSUE TITLE
We should automatically create the new folder when the user enter a folder name that doesn't exist yet in project creation dialog

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/vscode-azurefunctions#473]
Repro:
1. Install Azure Functions extension
2. Try to create a new project 
3. Select a parent folder underneath you want to create the new project. eg: at the root directory of the D:\ drive
4. In the "Select Folder" dialog during project creation, type a new name in the Folder: edit box.  What i wanted to do here is to create a subfolder under D:\ for my project.  Click Select.

Expect:
A new folder is created and highlighted.  I don't mind manually click to open that folder as long as it's created

Actual:
Warning: FolderName
               Path does not exist.
               Check the path and try again.  

This doesn't really block any E2E experience, but doesn't really provide me a very good experience at project creation.  I would believe when people try to create new projects, they usually don't project folders already created outside of VS Code. We should make project creation a breeze.

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. Unfortunately this is a windows system dialog that we don't have control over
