### ISSUE TITLE
Subscription picker is empty

### ISSUE THREAD

**Issue by alexjamesbrown** [microsoft/vscode-azurefunctions#476]
VS Code: Version 1.25.1 (1.25.1)
Azure Functions Extension: 0.9.1

---

When I select `Deploy to Function App` it asks me to select a subscription, however this list is empty

![image](https://user-images.githubusercontent.com/437743/43050758-36bbd33e-8e06-11e8-9635-c2771d0bcd41.png)

I am signed in to azure throught vs code
if i do `Azure: Select Subscriptions` I see my subscriptions:

![image](https://user-images.githubusercontent.com/437743/43050767-70bc7a8e-8e06-11e8-8a2f-1d91ea55679c.png)

**Comment by StephenWeatherford** [comment]
@alexjamesbrown Does it work the second time, or after you've opened the view?  I.e. dup of https://github.com/Microsoft/vscode-azuretools/issues/186?

**Comment by StephenWeatherford** [comment]
And more specifically, the new version was released yesterday. If it's a dupe, it should have been fixed with that release.  Please let us know whether that fixed it, thanks.

**Comment by StephenWeatherford** [comment]
Great to hear, thanks for taking the time to report the issue.
