### ISSUE TITLE
Restarting log stream after disconnect results in multiple streams with the same name

### ISSUE THREAD

**Issue by pcnate** [Microsoft/vscode-azurefunctions#483]
while streaming logs, the dropdown selection becomes polluted with old Log Streams.

**Comment by pcnate** [comment]
sometimes the log becomes disconnected, sometimes during a deploy. Start streaming does not check for existing "session?" in the dropdown under output.

![azure-functions-log-screenshot](https://user-images.githubusercontent.com/621940/43330865-ff4645ec-9189-11e8-899b-f40a364ba4bd.png)

**Comment by ubikusss** [comment]
Did a few tests. Normally, when you try to start the log stream and there is a log stream already active, you get an information message. 
Still, if you deploy and start the stream log again you will get a second log stream in the output window.
Thanks!

**Comment by pcnate** [comment]
I can't verify but I think a few times the log stream became disconnected without a deploy and created another log stream in the output window. I think the solution would be to always check for an existing log stream output and either remove the old one and create a new log stream output or reconnect to the old one.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/501
