### ISSUE TITLE
Java: Default unit test for Azure Function doesn't test anything

### ISSUE THREAD

**Issue by hf-kklein** [Microsoft/vscode-azurefunctions#491]
Steps to reproduce:
* create a new Azure Function Project using the [Azure Function VS Code PlugIn](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) . Choose language Java and default values.
* The path `src\test\java\com\function\FunctionTest.java` contains an autogenerated unit test for the Function class in `src\main\java\com\function\Function.java`.
* One would expect the test to fail, if the HTTP status code of the repsonse generated by the Azure Function inside the Function class returns something is different from 200 -- OK. 
* Run original test => passed;
* Modify the Azure Function `HttpTriggerJava` in Function´.java:
replace this part (lines 26-30)
```java
if (name == null) {
     return request.createResponse(400, "Please pass a name on the query string or in the request body");
} else {
     return request.createResponse(200, "Hello, " + name);
}
```
with this:
```java
return request.createResponse(500, "This unit test is pointless");
```
* Run test again => still passes.

By default you're mocking _all_ characteristics of the response. Except for the case when the function returns `null`, the test can never fail.

**Comment by hf-kklein** [comment]
Here's an alternative approach.
Create a class that implements `HttpResponseMessage`:
```java
package com.your.package;

import java.util.HashMap;
import java.util.Map;

import com.microsoft.azure.functions.HttpResponseMessage;

public class MockingHttpResponseMessage implements HttpResponseMessage<String> {

    private int status;
    private Map<String, String> headers;
    private String body;

    public MockingHttpResponseMessage() {
        this(0, null);
    }

    public MockingHttpResponseMessage(int status, String body) {
        this.status = status;
        this.body = body;
        headers = new HashMap<String, String>();
    }

    @Override
    public int getStatus() {
        return status;
    }

    @Override
    public void setStatus(int status) {
        this.status = status;
    }

    @Override
    public void addHeader(String key, String value) {
        headers.put(key, value);
    }

    @Override
    public String getHeader(String key) {
        return headers.get(key);
    }

    @Override
    public String getBody() {
        return body;
    }

    @Override
    public void setBody(String body) {
        this.body = body;
    }
}
```

Replace these lines in the unit test:
```java
final HttpResponseMessage res = mock(HttpResponseMessage.class);
doReturn(res).when(req).createResponse(anyInt(), anyString());
```
with this:
```java
doAnswer(new Answer<MockingHttpResponseMessage>() {
            @Override
            public MockingHttpResponseMessage answer(InvocationOnMock invocation) throws Throwable {
                Integer status = (Integer) invocation.getArguments()[0];
                String body = (String) invocation.getArguments()[1];
                return new MockingHttpResponseMessage(status, body);
            }
        }).when(req).createResponse(anyInt(), anyString());
```
Don't forget to
```java
import static org.mockito.Mockito.doAnswer;
```
Now you can use assertions to test the result of your function.

See [this StackOverflow thread](https://stackoverflow.com/a/2711553/10009545) for mockito details.

**Comment by jdneo** [comment]
@hf-kklein Thanks for the feedback.

Since this is a archetype related issue, Let's tracking it here: https://github.com/Microsoft/azure-maven-archetypes/issues/44
