### ISSUE TITLE
Keep displaying 'connecting to log stream...' more than 10 mins for a stopped function app 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#498]
Repro Steps:
1. Right click one function app -> select 'Stop'.
2. Right click this function app -> select 'Start Streaming Logs'.

Expect:
Succeed to connect to log stream and start streaming logs.

Actual:
Keep displaying 'connecting to log stream...' more than 10 mins. And there is no any error or warning to tell the customer this function app is stopped and prompt the customer to start it. 
![connect](https://user-images.githubusercontent.com/34729092/43825902-79eec922-9ae5-11e8-81b6-7bdabc1f1e34.png)

**Comment by EricJizbaMSFT** [comment]
We refactored log stream in this PR: https://github.com/Microsoft/vscode-azuretools/pull/245

Hopefully that fixed it, but re-open if it didn't
