### ISSUE TITLE
Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

### ISSUE THREAD

**Issue by ranbirpaul** [Microsoft/vscode-azurefunctions#502]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

Version: 0.10.0
OS: win32

**Comment by JohnReeson** [comment]
You need to add your function app folder to workspace first. 

![1](https://user-images.githubusercontent.com/35160013/43973185-5d4ec62a-9d09-11e8-91f5-86a7e51cbfec.png)

**Comment by EricJizbaMSFT** [comment]
Offhand I'm not sure what settings we're trying to write while deploying. As @JohnReeson mentioned you can just open the folder as a workaround. However, we can investigate getting rid of this error completely

**Comment by JohnReeson** [comment]
![12](https://user-images.githubusercontent.com/35160013/44307129-69991d00-a3cf-11e8-9837-e02fa3fe17ee.png)

@EricJizbaMSFT  It seems to write azure-functions-related settings(in ~/.vscode/settings.json), same as when we initialize a new function project. Looks like any function related operation requires this workspace settings and we may get the prompt when no workspace is opened(no settings available).
