### ISSUE TITLE
Support different hosting plan when deploying function app

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azurefunctions#504]
Currently, the default hosting plan of 'Comsumption plan' is used when deployment function app.

Is it possible to support selecting from existing hosting plan during deployment?

**Comment by EricJizbaMSFT** [comment]
Do you mean when creating a function app? When deploying...I believe it just uses the plan associated with the function app you select.

What's your reason for using a non-consumption plan?

**Comment by lirenhe** [comment]
When creating a functions app in portal, we could choose from different hosting plan.
![image](https://user-images.githubusercontent.com/9100546/44182353-7e1da280-a0bb-11e8-9886-fd97b1e8ee47.png)
Some user may require higher service plan for more powerful CPU or larger memory.

**Comment by EricJizbaMSFT** [comment]
Sure there are some edge cases where users might want an App Service Plan, but Consumption Plan is the default and still the best option in most cases. In VS Code we really try to reduce the number of prompts and keep things lightweight. I'm hesitant to add a prompt for this unless we have a specific scenario or user evidence that it's needed. I suspect there aren't many users that need this and they're probably fine using the portal.

**Comment by lirenhe** [comment]
We got some feedback from customers that the functions that created in Consumption plan are not started correctly, so they want to use other service plans which is more stable.  I understand your concern so is there any other workarounds?

**Comment by EricJizbaMSFT** [comment]
I mean the workaround is to create the function app and plan in the portal or through the az cli

Have you discussed the customer feedback with the functions team? Do they have any known issues or plans to fix this?

**Comment by EricJizbaMSFT** [comment]
Closing this. We want to default to consumption plans for all users as it is the recommended pattern. If you're having issues with consumption plans then you should follow up with the functions team to get those addressed
