### ISSUE TITLE
Move parseJavaTemplates to its own file

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#505]
Rather than keeping it in parseScriptTemplates.ts

**Comment by jdneo** [comment]
@EricJizbaMSFT Let's first discuss the design before implementation.

Currently, the template parsers are all function based. Do you think we need to change it to class-based and extend to several different parsers to avoid duplicated code?

**Comment by EricJizbaMSFT** [comment]
I don't see the benefit of a class in this case. I say you just move Java-specific code to parseJavaTemplates and export anything you need from parseScriptTemplates.

**Comment by jdneo** [comment]
I see.
