### ISSUE TITLE
Download appears to hang

### ISSUE THREAD

**Issue by jongio** [Microsoft/vscode-azurefunctions#511]
Ran this:
`npm i -g azure-functions-core-tools@core --unsafe-perm true`

It paused for a good couple of minutes here and I wasn't sure if it failed or not.

![image](https://user-images.githubusercontent.com/2163001/44122066-18f08100-9fd7-11e8-8ad3-3c7cd5dce3a1.png)

Would be good to add a rolling percent downloaded status.

**Comment by EricJizbaMSFT** [comment]
The download logic is controlled directly by npm. I recommend filing an issue here: https://npm.community/c/bugs
