### ISSUE TITLE
Error when create new project by JavaScript language

### ISSUE THREAD

**Issue by tuyetphale993** [Microsoft/vscode-azurefunctions#513]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.createFunction
Error type: Error
Error Message: There was an error in retrieving the templates.  Recheck your internet connection and try again.

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
This will be mitigated by including backup templates with the extension. See https://github.com/Microsoft/vscode-azurefunctions/issues/462

However, we still need to investigate why backup templates are necessary in the first place

**Comment by EricJizbaMSFT** [comment]
Closing this as it's not very common and backup templates are already merged.
