### ISSUE TITLE
Creating new C# QueueTrigger function in VSCode

### ISSUE THREAD

**Issue by kgoderis** [Microsoft/vscode-azurefunctions#514]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.createFunction
Error type: SyntaxError
Error Message: Unexpected token } in JSON at position 1984

Version: 0.10.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@kgoderis can you give us some more information on this? For example:
1. Does it happen consistently for you?
1. Is it only QueueTrigger that has the problem?
1. Did it ever work for you or was this the first time?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of info. Feel free to re-open with more info
