### ISSUE TITLE
Azurefunction extension

### ISSUE THREAD

**Issue by jigarrdesai** [Microsoft/vscode-azurefunctions#515]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@jigarrdesai a few questions:
1. Does this happen consistently for you or does it work if you deploy again?
1. Can you copy the deployment logs?
1. Can you give more detailed repro steps?

Thanks

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of info. Feel free to re-open with more info
