### ISSUE TITLE
Error: "The request cannot be interpreted as valid Json" when creating new storage account

### ISSUE THREAD

**Issue by pjenei** [Microsoft/vscode-azurefunctions#520]
Repro steps:
- Follow the steps in https://code.visualstudio.com/tutorials/functions-extension/deploy-app
- Choose to create a new storage account while deploying.
- You get the error described below when it tries to create the storage account.

Action: azureFunctions.deploy
Error type: RequestIsNotValidJson
Error Message: The request cannot be interpreted as valid Json: {"sku":{"name":"Standard_LRS"},"kind":"Storage","location":"westeurope"}.

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Looks like there was some problem with storage accounts in Azure's westeurope region a few days ago. Here's a few of the related issues I found:
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/1796
* https://github.com/hashicorp/terraform/issues/18715
* https://github.com/SAFE-Stack/SAFE-template/issues/145

I was successfully able to create a storage account in westeurope today and all of those issues have been closed, so I'll go ahead and close this one. Feel free to re-open if it's still a problem for you.
