### ISSUE TITLE
Create PowerShell azure functions

### ISSUE THREAD

**Issue by raymondlittle100** [Microsoft/vscode-azurefunctions#527]
I'm trying to use this but ideally I would like to create a PowerShell function, however this doesn't seem to be an option. I know this is classed as experimental in Azure Functions but wondered if there were plans to support this?

**Comment by EricJizbaMSFT** [comment]
We have limited support for this right now. You can follow these steps:
1. Change the "azureFunctions.projectLanguage" user setting to "PowerShell"
1. Create a new project
1. Create a new function (I believe we only have 3 function templates available and only if you're using v1 of the functions runtime)
1. From the command palette (View -> Command Palette...), select 'Tasks: Run Task' and then 'Run Functions Host'

At this point you should have powershell functions running locally. We currently don't have support for debugging, but you're welcome to explore the [PowerShell extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) to see if you can get a `launch.json` that works.

**Comment by raymondlittle100** [comment]
Great thanks I'll give it a try
