### ISSUE TITLE
C# debugging fails after fixing a build break

### ISSUE THREAD

**Issue by timmyreilly** [Microsoft/vscode-azurefunctions#534]
Repro steps:
<Enter steps to reproduce issue>
Create a new project. 
Introduce an error. 
Start Debugging.
Fix Error.
Start Debugging Again. 

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Does this consistently happen for you? I just refactored this and I'm hoping to get your help testing if you have time (and if you never got this working for yourself).

Please install the following vsix leveraging the "Install from VSIX" command in VS Code's command palette:
![screen shot 2018-09-04 at 10 28 44 am](https://user-images.githubusercontent.com/11282622/45047234-53c16400-b02d-11e8-93d6-514f3ee3f9ad.png)

VSIX:
https://azcode.blob.core.windows.net/vscode-azurefunctions/ej/proc/1627/vscode-azurefunctions-0.10.1-alpha.vsix

**Comment by timmyreilly** [comment]
Shucks just saw this, will give it a shot meow.

**Comment by EricJizbaMSFT** [comment]
Yeah we went ahead and published an update to the vsix a few hours ago. You don't need to install the vsix from above - you can just use the version from the marketplace (0.10.1)

**Comment by EricJizbaMSFT** [comment]
I took a closer look at these repro steps (should've done that before) and even though the underlying code is completely different, your scenario still has issues 😬 Re-opening and I hope to have addressed soon

**Comment by EricJizbaMSFT** [comment]
Just published an update. Thanks for reporting and should be working now
