### ISSUE TITLE
Refactor validateFuncCoreToolsInstalled logic

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurefunctions#535]
`UserCancelledErrors` get suppressed and there's no way to discern whether the user canceled.

**Comment by EricJizbaMSFT** [comment]
So here's where the issue was added: https://github.com/microsoft/vscode-azurefunctions/pull/525/files#diff-e5aae51200151ee2e65bf7e21c8db7aaR51

**Comment by EricJizbaMSFT** [comment]
Imma just close this because it's been a long time and we have no idea what was supposed to happen here
