### ISSUE TITLE
C# function missing AzureFunctionsVersion in .csproj file 

### ISSUE THREAD

**Issue by JohnReeson** [Microsoft/vscode-azurefunctions#537]
When I create new project and choose c#, .csproj is generated automatically. However, it lacks AzureFunctionsVersion. See it in both v1 and v2 function. 

![3](https://user-images.githubusercontent.com/35160013/44851390-bbc12480-ac92-11e8-871f-8a7233615376.png)

Version 0.10.0
VS Code: 1.26.1

**Comment by EricJizbaMSFT** [comment]
@JohnReeson thanks for filing! Looks like that was added in June and I just wasn't aware of it
