### ISSUE TITLE
Run From Package to lower startup times?

### ISSUE THREAD

**Issue by selfup** [Microsoft/vscode-azurefunctions#546]
_(Please check the edit at the bottom, I skipped over the fact that functions core tools use the zip api)_

***

Using npm is great, but apparently all files go to blobs. And many blobs are slow 🐢 

Now that deploying with zips is a thing :rocket: 📦 I am interested in knowing if we can make this an option in the GUI or as some json config?

https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push

I use the azure storage module, and it takes around 1min for the first API call to respond after a fresh deployment (known issue with non-zip deploys), so this could save a lot of people the headache of figuring out what is going on 😄

<img width="1131" alt="screen shot 2018-08-31 at 9 32 13 am" src="https://user-images.githubusercontent.com/9837366/44918530-d4682380-ad00-11e8-86b4-873f6cf4a14f.png">

***

In the `./src/commands/deploy.ts` there is something that says deploying as zip, but unclear if that is using the new zip api or not?

https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/commands/deploy.ts#L37

Not too familiar with TS but if I can track this down maybe I can help 👍 

### Edit

`Azure Functions Core Tools also uses these deployment APIs when publishing a local project to Azure.`

Hmm so if you are using the API why does it still take 1 minute? I know this is starting to escape the scope of this project, but I was under the impression that the zip would help startup times significantly 🤔 

# Conclusion

Turns out what I was really talking about was [Run From Package](Azure/app-service-announcements#84)

Seems to be in the roadmap 🎉

**Comment by selfup** [comment]
Thanks for the detailed reply. Ok so just a bit more time 😄 

Yea I guess I meant `Run from package`. Thanks! 👍 

I'll change the title so it's a bit more clear 🙏

**Comment by EricJizbaMSFT** [comment]
Closing this since we all ready have an issue to track "Run from package"
