### ISSUE TITLE
Python: Support existing virtual environments?

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#550]
This issue is to open the discussion for the scenario where a user would like to use their pre-existing virtual environment for a new Python Functions Project.

We don't quite understand how users use `venv`, especially in the case for Functions.  Futhermore, we don't know if it makes sense for the user to Browse to the root of the `venv` folder or to the `activate` script that is used to enable the `venv`.

**Comment by EricJizbaMSFT** [comment]
Holding off on this until we hear from customers

**Comment by EricJizbaMSFT** [comment]
Closing this as it's been about half a year and we haven't received feedback related to existing venvs since then, plus the experience has changed already.
