### ISSUE TITLE
Can't debug java functions locally

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-azurefunctions#553]
Configuration
```
• VS Code 1.26.1
• JDK 1.8
• Maven 3.5.4
•.Net Core SDK 2.1.401
• Node 8.11.4
• Azure Functions Core Tool 2.0.1-beta.37
• VS Code extensions 
	○ Azure Account  0.4.3
	○ Debugger for Java 0.12.1
	○ Language Support for Java 0.30.0
•  CI build for vscode-azurefunction extension 0.10.1-alpha (Build#189)
```
Reproduce steps:
1. Create a java function project
2. Set a break point and press F5 to debug java function locally

Result:
Debug failed, 
![image](https://user-images.githubusercontent.com/41051257/45007950-a7827c00-b032-11e8-986d-1bc67ec556a7.png)

Expect:
![image](https://user-images.githubusercontent.com/41051257/45007964-c41eb400-b032-11e8-972b-bbe8767d3aab.png)

Investigation:
Firstly, I can debug java function locally using function core tools with 2.0.1-beta.35 version, but after update to the latest version:  2.0.1-beta.37, can't debug locally.

**Comment by Flanker32** [comment]
It may related to some problems in azure functions core tools,(https://github.com/Azure/azure-functions-core-tools/issues/692) and we are trying to fix it.

**Comment by Flanker32** [comment]
The problem was fixed, please update the function core tools to 2.0.1-beta.38

**Comment by ZhengJun003** [comment]
Update the function core tools to 2.0.1-beta.38, can debug java functions locally, so close it.
