### ISSUE TITLE
Can't deploy the third function extension connection string to cloud

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-azurefunctions#555]
Configuration:

```
VS Code 1.26.1
JDK 1.8
Maven 3.5.4
Net Core SDK 2.1.401
Node 8.11.4
Azure Functions Core Tool 2.0.1-beta.37
VS Code extensions
Azure Account 0.4.3
Debugger for Java 0.12.1
Language Support for Java 0.30.0
CI build for vscode-azurefunction extension 0.10.1-alpha (Build#189)

```
Reproduce steps:

1. Create a java function project
2. Add a java function, e.g.ServiceBusQueueTrigger
3. Add the service bus connection string in the pom file shown as below:
![image](https://user-images.githubusercontent.com/41051257/45025467-277a0780-b06e-11e8-8cd8-5e3f341138ab.png)

4. Deploy to a new function app

Result:
The connection string of service bus in pom file can't be deployed to application settings

**Comment by bsaby** [comment]
The connection string can be added to application settings manually, so close it.
![image](https://user-images.githubusercontent.com/22470312/45068560-9ef57880-b0fa-11e8-8bf0-0c46c63a2903.png)
