### ISSUE TITLE
When I try to deploy I get this error, which is really not much help

### ISSUE THREAD

**Issue by DotNetNerd** [Microsoft/vscode-azurefunctions#556]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":2}}

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azuretools/pull/240 and will be included in the next release
