### ISSUE TITLE
Error deleting a function app on Azure.

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#557]
Repro steps:
Created an empty Function app then deleted it shortly after. Never deployed to the app.

Action: azureFunctions.deleteFunctionApp
Error type: TypeError
Error Message: Cannot read property 'numberOfSites' of null

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Fixed by https://github.com/Microsoft/vscode-azuretools/pull/230 and will be included in the next release. See this comment in particular: https://github.com/Microsoft/vscode-azuretools/pull/230#discussion_r207372465
