### ISSUE TITLE
Error "{}" trying to create function app in Azure

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurefunctions#560]
Repro steps:
Right-click on a subscription -> Create Function App in Azure...
!) error

Action: azureFunctions.createFunctionApp
Error type: RangeError
Error Message: {}

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/480
