### ISSUE TITLE
Change runtime version from 'beta' to '~2'

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#562]
For v2 runtime GA, change `beta` to `~2` in the runtime selection dropdown. 

/cc @fiveisprime @jeffhollan

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT

**Comment by EricJizbaMSFT** [comment]
Thanks for the ping @StephenWeatherford - but just FYI to @asavaritayal: We've discussed this process before and the most important thing is that you create an issue _in our repo_. Thank you for doing that in this case :)

I can think of too many times when people missed an email or pinged the wrong person, but I can't think of any instance where an issues filed on GitHub (in the correct repo) was lost. We regularly triage open issues and I much prefer to rely on that process. (Plus I'm subscribed to the repo and get the notification anyways)

**Comment by EricJizbaMSFT** [comment]
@asavaritayal we check the user's remote runtime version when deploying and I vaguely remember we would get "latest" returned sometimes. Is that still a valid version setting? If so - what will it mean going forward? ~1 or ~2?

**Comment by jeffhollan** [comment]
@paulbatum 

I believe `latest` is still a valid setting though one that will go through a bit of a shift.  `latest` today is synonymous with ~1, but once ~2 becomes GA `latest` will then be ~2.  We actually need to alert users of this setting and generally don't recommend any version numbers that aren't more specific.

`beta` is another value that will be very common.  It today is same as ~2.  I suppose in future `beta` may be a version slightly higher than ~2 but should be in the same family from a template standpoint.  However related to this issue I think the only setting that would map to ~1 after GA would be something that starts with 1 or ~1
