### ISSUE TITLE
[Linux]Fail to debug a function project with JavaScript

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#566]
Repro Steps:
1. Create a new project using JavaScript.
2. Create a new function and add Httptrigger.
3. Set a breakpoint in the opened index.js file.
4. Debug.

Expect:
Succeed to debug.

Actual:
Fail to debug the functin project with the below error.
![error](https://user-images.githubusercontent.com/34729022/45152517-c3b42380-b1c0-11e8-9a5a-25deddfe6f5e.png)
[log_message.txt](https://github.com/Microsoft/vscode-azurefunctions/files/2356630/log_message.txt)

**Comment by EricJizbaMSFT** [comment]
Yeah so your error in log_message is very similar to the error here: https://github.com/Azure/azure-functions-core-tools/issues/562

Closing as this was fixed a month or two ago in the func cli. Please re-open if it still repros after updating the func cli (I think you need at least version 2.0.1-beta.34)

**Comment by v-xianya** [comment]
Verified on the Windows/Linux/MacOS with build 20181203.6. This issue reproduces. So we re-open it.

**Comment by EricJizbaMSFT** [comment]
@v-xianya This issue is several months old and was an external bug. Rather than re-opening this, please file a new bug with updated repro steps and new logs. Thanks
