### ISSUE TITLE
`func extensions install` on Windows

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#568]
Before running `func start host`, `func extensions install` is run, but I get this error:

![image](https://user-images.githubusercontent.com/5290572/45186592-e0615300-b1e2-11e8-92f8-1e5481fb44a1.png)

It doesn't seem to affect the function trigger from debugging locally.  This was a JS project.

**Comment by EricJizbaMSFT** [comment]
@nturinski says to close this
