### ISSUE TITLE
Error when trying to create a C# azure functions in vscode

### ISSUE THREAD

**Issue by yvrkarthik** [Microsoft/vscode-azurefunctions#572]
Repro steps:
1. Start and Create a function
2.  Select C# as the prefered language
3. An error pops up as shown below

![image](https://user-images.githubusercontent.com/1669197/45194887-24b72680-b2a9-11e8-8e82-1982b8401bda.png)

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet c:\Users\Rajiv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.0\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll --require c:\Users\Rajiv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.0\resources\dotnetTemplates\itemTemplates-~1.nupkg --require c:\Users\Rajiv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.0\resources\dotnetTemplates\projectTemplates-~1.nupkg --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.1.x --arg:name Tuts1" failed with exit code "4294967295":

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@yvrkarthik we just released an update last Friday. Can you make sure you're up to date (at least v0.9.1) and try again?

If it still happens, can you copy the output from the "Azure Functions" output channel? Hopefully that has more information than just the error code

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
