### ISSUE TITLE
Can not publish Azure Function from VSCode due to certificate issue

### ISSUE THREAD

**Issue by peterbecker** [Microsoft/vscode-azurefunctions#576]
Whenever I try to deploy an Azure Function from Visual Studio Code, I end up with an error "unable to get local issuer certificate". I am reasonably confident this is a result of our corporate network performing man-in-the-middle attacks on itself by using [Forcepoint](https://en.wikipedia.org/wiki/Forcepoint).

My problem is that it is not clear what tool is actually having the problem, and in consequence I don't even know where to look for CA certs to add. The terminal window doesn't seem to show any output relating to this. 

To reproduce:
- set up some SSL meddling tool in your network
- open an Azure Function project
- go to the Azure: Functions section
- use the deploy button at the top

Action: azureFunctions.deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment]
Yeah so this scenario is not supported at the moment. We have an issue on our backlog here to track: https://github.com/Microsoft/vscode-azurefunctions/issues/493

There are some existing VS Code settings that we just need to add support for:
`http.proxy`
`http.proxyStrictSSL`
`http.proxyAuthorization`

Closing this as dupe - but feel free to re-open if you think your scenario is different than the one I linked to.
