### ISSUE TITLE
Python projects need to run `func extensions install` before debugging

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#584]
I see this for blob triggers unless I run `func extensions install`
```
[9/12/18 10:45:53 PM] The following 1 functions are in error:
[9/12/18 10:45:53 PM] BlobTriggerPython: The binding type(s) 'blobTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

@asavaritayal is this right? Should we be running `func extensions install`?

**Comment by asavaritayal** [comment]
Correct, this applies to all function apps running on V2. Any bindings other than HTTP and timer will require a `func extensions install` before debugging.

**Comment by EricJizbaMSFT** [comment]
My understanding was this wasn't required for C# or Java function apps. Only JavaScript - and apparently also Python.

For Python, do we need to run this before debug _and_ deploy? Or will `func pack` take care of the deploy scenario for us?
