### ISSUE TITLE
Add log stream support for linux consumption apps

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#589]
They don't have kudu, so log streaming currently isn't working

**Comment by EricJizbaMSFT** [comment]
Per @asavaritayal:
> Instead of using the Kudu endpoint, launch the **Live Metrics Stream** view in the browser.

**Comment by asavaritayal** [comment]
@EricJizbaMSFT do you have a rough estimate of when this might land?

**Comment by EricJizbaMSFT** [comment]
@asavaritayal should be in our next release, which will probably be end of june-ish

**Comment by jhodges10** [comment]
> @asavaritayal should be in our next release, which will probably be end of june-ish

Really need this for debugging. Currently trying to figure out why my function which runs locally won't work on Azure and it's rather impossible without a log stream :(

**Comment by qalandarov** [comment]
@EricJizbaMSFT any updates on the progress?
