### ISSUE TITLE
Python 3.6 error message is misleading

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#594]
People can use a lot of different aliases and if they're using an unrecognized alias they will see this error:
![image](https://user-images.githubusercontent.com/11282622/45497771-6c1c3780-b72d-11e8-856f-4808ce137584.png)

Which is a little misleading because it makes it seem like the _version_ is the problem, rather than the failure to find the alias on the path.

Additionally, we might want to prompt for the alias or python path

**Comment by asavaritayal** [comment]
By the way, we're doing a double check here. The `func init` command already verifies whether you're running in a python 3.6 virtual environment or not. 

If we still want to go ahead and have a check upfront, IMO it's ok to only validate only `python3` and `python` in that order. We don't need to cater to custom aliases.
