### ISSUE TITLE
Extension says its v 0.8.1 after installing 0.10.2

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-azurefunctions#602]
![2018-09-14_08-26-30](https://user-images.githubusercontent.com/5007120/45550090-e44f2f80-b7f7-11e8-9965-3c93afe7dbd7.png)

I've uninstalled and reinstalled etc. Wondering if this is related to the debugging issues I'm having with node if I'm truly on 0.8.1.

**Comment by EricJizbaMSFT** [comment]
You can try manually removing the extension from the following folder and then re-installing. I believe this is where it's located:
- Windows: `C:\Users\<user name>\.vscode\extensions\`
- Mac: `~/.vscode/extensions/`

You can remove the whole folder named `ms-azuretools.vscode-azurefunctions-<version>`

**Comment by julielerman** [comment]
that dd the trick. Maybe all of the other nonsense that's been happening will disappear. Back to more testing!! (wonders why it was *stuck*)

**Comment by EricJizbaMSFT** [comment]
So I double checked your versions in the other thread and our extension relies on VS Code version "1.24.0" or greater and you were on "1.21.1". "0.8.1" must be the last version that supports "1.21.1".

I'm surprised VS Code doesn't warn you about that in any way. Feel free to file an issue on github to improve that messaging (unfortunately we don't control how we're installed or anything related to the Extension marketplace)

Are you still on "1.21.1" after you got it working or did you update VS Code?

**Comment by julielerman** [comment]
yeah ..just realized it still says 0.8.1 after all that. I've done "check for updates" so many times for vscode and it says "nope". Wow. Off to just unisntall reinstall
