### ISSUE TITLE
error : Expression: [Recursive resource lookup bug]

### ISSUE THREAD

**Issue by kravikiranssdi** [Microsoft/vscode-azurefunctions#608]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.10.2
OS: darwin

**Comment by kravikiranssdi** [comment]
Build FAILED.

/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Assert Failure [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Expression: [Recursive resource lookup bug] [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Stack Trace: [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.InternalGetResourceString(String key) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.GetResourceString(String resourceKey, String defaultString) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ArgumentNullException..ctor(String paramName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.InternalGetResourceString(String key) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.GetResourceString(String resourceKey, String defaultString) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ArgumentNullException..ctor(String paramName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.InternalGetResourceString(String key) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.SR.GetResourceString(String resourceKey, String defaultString) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at MakeFunctionJson.MethodInfoExtensions.HasFunctionNameAttribute(MethodInfo method) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext() [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons() [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun() [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :    at Microsoft.NET.Sdk.Functions.Console.Program.Main(String[] args) [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error :  [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]
/Users/ravikirank/.nuget/packages/microsoft.net.sdk.functions/1.0.21/build/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets(39,5): error : Metadata generation failed. [/Users/ravikirank/Projects/OpenHack/OpenHack.csproj]

**Comment by EricJizbaMSFT** [comment]
Thanks for filing an issue, but our extension doesn't control the build. This may be a problem specific to your project or you could file an issue on this repo: https://github.com/Azure/azure-functions-vs-build-sdk
