### ISSUE TITLE
Display 'Linux Preview' tag next to the new created function app when deploying one python project

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#618]
Repro Steps:
1. Create one function project with Python.
2. Click 'Deploy to Funcrion App...' -> Select 'Create New Function App' -> Enter a unique name for the new function app -> Choose a resource group and storage account.
3. Check the created function app.

Expect:
No tag 'Linux Preview' displays next to the function app name.

Actual:
Display the tag 'Linux Preview' next to the function app name.
![preview](https://user-images.githubusercontent.com/34729022/45813165-655b6a80-bcc1-11e8-91b1-373b7372cb97.png)

**Comment by EricJizbaMSFT** [comment]
This is by-design. Python only works on Linux function apps, which are still in preview.
