### ISSUE TITLE
Show warning if users try to deploy Python to windows

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#619]
Repro Steps:
1. Create a new project with Python and Azure Functions v2-> 'Create functions...' with HTTP trigger.
2. Debug this project ->Deploy to one existing function app.
3. Check the result.

Expect:
Succeed to deploy.

Actual:
Fail to deploy with error 'Cannot read property 'constructor' of undefined'.
![screen shot 2018-09-20 at 11 59 22 am](https://user-images.githubusercontent.com/34729092/45813388-02b69e80-bcc2-11e8-8e8a-2e797b9ff28f.png)

More Info:
Prompt the service is unavailable after deploying to a new created function app.
![new](https://user-images.githubusercontent.com/34729092/45813461-2ed21f80-bcc2-11e8-8dd2-d0020789b6bd.png)

**Comment by EricJizbaMSFT** [comment]
You can't deploy Python to windows. We should check that and show a warning
