### ISSUE TITLE
Pop up an error in 'DEBUG CONSOLE' window after getting the URL for JS

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#634]
Repro Steps:
1. Create a new project with JavaScript language and v2 runtime->'Create New Function' with the new created folder and HTTP trigger template.
2. Debug -> Then check the 'DEBUG CONSOLE' window.

Expect:
No error display.

Actual:
Pop up an error in 'DEBUG CONSOLE' window after getting the URL for JS whatever the nodejs version is v8.12.0 or v10.8.0.
![actual1](https://user-images.githubusercontent.com/34729092/45865878-78784400-bd6e-11e8-846a-92d03b854d55.png)

**Comment by EricJizbaMSFT** [comment]
Closing as won't fix. That warning is expected and shouldn't actually stop you from debugging. Re-open if it blocks you from debugging.
