### ISSUE TITLE
VS Code should not add AzureWebJobsDashboard App Setting

### ISSUE THREAD

**Issue by davidebbo** [Microsoft/vscode-azurefunctions#640]
It's an obsolete setting that we're moving away from. Even though it doesn't technically break things, it can have a perf impact.

**Comment by EricJizbaMSFT** [comment]
This one can be removed from everything? Linux and windows?

**Comment by davidebbo** [comment]
It can be removed in all **v2** scenarios, regardless of platform. But it is still needed in v1 (not sure if you support v1 at all).
