### ISSUE TITLE
Code should filter regions for Consumption Linux scenario

### ISSUE THREAD

**Issue by davidebbo** [Microsoft/vscode-azurefunctions#641]
Initially, it is only available in West US, East US, Southeast Asia and West Europe.

I believe there is an API to get this, but I don't know the details. @bala16 or @ahmelsayed should know more.

**Comment by bala16** [comment]
@EricJizbaMSFT Yes you are right. linuxDynamicWorkersEnabled is what you should be using but that change will not deployed until of end of month. We published the swagger sooner so we can get the sdk built with those changes that some other clients use. Until then please use servicefabriccontainersenabled.
