### ISSUE TITLE
Error Deploying Function App

### ISSUE THREAD

**Issue by sajayram** [Microsoft/vscode-azurefunctions#645]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.2
OS: win32

**Comment by danielcrisp** [comment]
I'm having the exact same error, but as you can see above the error message isn't very helpful.

Are errors logged anywhere else?

**Comment by EricJizbaMSFT** [comment]
@sajayram @danielcrisp we just released v0.11.0 this morning. Although it wasn't intended to directly fix this problem, I believe the error message should have a little more info now. Specifically you might be getting "Service unavailable" - which unfortunately means there might be an outage with Azure Functions

Can you make sure you're on the latest and try again? And let me know what error you get?

**Comment by danielcrisp** [comment]
The same error I'm afraid, except the version number changed. I also tried creating a function through the Portal (last night) and that was also failing with an equally unhelpful error message. I tried again this morning - through the Portal - and I was able to create it no problem, so perhaps as you suggested there was something else going on.

**Comment by EricJizbaMSFT** [comment]
Filed an issue on kudu, which might be where this error is coming from: https://github.com/projectkudu/kudu/issues/2889

Otherwise I'll close this as "needs repro". Feel free to re-open if you can get us a consistent repro
