### ISSUE TITLE
Failed to switch from "Run From Package" to "Local Git"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#653]
Repro steps:
1. Deploy a project with an http trigger to a new function app
1. Change deployment source to local git
1. Change your local project somehow (doesn't really matter how)
1. Deploy again

Expected: The new deployment takes effect
Actual: The function app is still running the old deployment

I think we have to remove `WEBSITE_RUN_FROM_PACKAGE` when a user changes to local git. We might also have to restart the function app.

**Comment by EricJizbaMSFT** [comment]
@ColbyTresness @davidebbo how do we fully change from "Run From Package" to "Local Git"? The change to deployment source doesn't seem to take effect like it did before we introduced `WEBSITE_RUN_FROM_PACKAGE` as the default.

**Comment by davidebbo** [comment]
Removing the `WEBSITE_RUN_FROM_PACKAGE` App Setting should be the correct way of disabling it, after which Local Git should work fine.

**Comment by nturinski** [comment]
Fixed by https://github.com/Microsoft/vscode-azuretools/pull/289
