### ISSUE TITLE
Failed to copy url for non-anonymous http triggers on linux consumption

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#654]
Repro steps:
1. Create a new python project
1. Add an http trigger with 'admin' auth
1. Deploy to a new function app
1. Expand the functions explorer to see list of functions

Expected: Function is listed and I can copy url
Actual: The function is invalid

This happens because our request to get the admin token returns with a web page saying "Your Function App is up and running" instead of actually giving us the admin token.

**Comment by v-dantch** [comment]
Add More Info:
This issue also reproduces with Function auth level.
![function](https://user-images.githubusercontent.com/34729092/46196605-1af87000-c2f7-11e8-889e-1232c93db875.PNG)

**Comment by EricJizbaMSFT** [comment]
Filed an issue on the functions host here: https://github.com/Azure/azure-functions-host/issues/3635

**Comment by amclin** [comment]
This isn't limited to just python functions. It happens for Javascript functions as well.
