### ISSUE TITLE
Add `pip install` step to `tasks.json`

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#666]
## Currently, we only activate the virtual environment

```json
"osx": {
        "command": "func extensions install && . func_env/bin/activate && func host start"
      },
```

## Would be great if we can also install the dependencies when starting the functions host

```json
"osx": {
        "command": "func extensions install && . func_env/bin/activate && pip install -r requirements.txt && func host start"
      },
```

**Comment by asavaritayal** [comment]
@EricJizbaMSFT could you please confirm if this is possible to include? Thanks!

**Comment by EricJizbaMSFT** [comment]
We can definitely do it. Can you describe the experience and current downsides so that I can understand the priority?

Also does this need to be done before deploy or is it handled by 'func pack'?
