### ISSUE TITLE
Error creating Virtual Python environment while creating Azure Functions Project in Visual Studio Code

### ISSUE THREAD

**Issue by RamakantShankar** [Microsoft/vscode-azurefunctions#667]
Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run "func_env\Scripts\activate && pip install ptvsd" command. Check output window for more details.

Version: 0.11.0
OS: win32

Running command: "func_env\Scripts\activate && pip install ptvsd "...
Collecting ptvsd
  Using cached https://files.pythonhosted.org/packages/5e/15/78a8be571d6a450c6ad36a675e4384bb4f33f9e920cfcc74b6e3a9683520/ptvsd-4.1.3-py3-none-win_amd64.whl
Installing collected packages: ptvsd
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '......\\func_env\\Lib\\site-packages\\ptvsd\\_vendored\\pydevd\\pydevd_attach_to_process\\winappdbg\\win32\\__pycache__\\context_amd64.cpython-37.pyc'

You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error: Failed to run "func_env\Scripts\activate && pip install ptvsd" command. Check output window for more details.

**Comment by EricJizbaMSFT** [comment]
Sorry for the delayed response. Does this still repro for you? Can you try running `func_env\Scripts\activate && pip install ptvsd` manually from the command line? That issue is coming from 'pip' so I'm not sure if our extension can fix it directly

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info

Also related to https://github.com/Microsoft/vscode-azurefunctions/issues/821
