### ISSUE TITLE
Precompiled C# Debug experience is not great.  

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/vscode-azurefunctions#670]
Hello, 

I use VSCode to develop C# (Precompiled) and configure the Debug enviornment. I can do it however, I feel it is not good experience. It workaround works. however, it is not good experience. 

Current experience is like this. 

# preparation

```
func init
func new (choose HttpTrigger and give name interactive)
```

# build app

```
dotnet build 
```

# start function

```
cd bin/Debug/netstandard2.0
func host start --debug VSCode
```
It creates `launch.json` however, it is under the `bin/Debug/netstandar2.0/.vscode/launch.json`
then  copy the `launch.json` to the `.vscode/launch.json`

# Start debug

Click the debug button, it requires which process to attach. find `func` then start debugging.

**Comment by TsuyoshiUshio** [comment]
I notice that is we use VSCode Azure Functions Plugin, it works well. Maybe you can explain in a document.

**Comment by EricJizbaMSFT** [comment]
Thanks for filing an issue. The `func host start --debug VSCode` command is out of date and does not create a "launch.json" that works. Created an issue here to address that: https://github.com/Azure/azure-functions-core-tools/issues/394

In terms of documentation, here are a few articles with more info:
https://code.visualstudio.com/tutorials/functions-extension/getting-started

https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-vs-code
