### ISSUE TITLE
task.json points to the wrong path for host start

### ISSUE THREAD

**Issue by ealsur** [Microsoft/vscode-azurefunctions#685]
After migrating the runtime to the latest 2.0 GA version and creating a Function in VS Code through the Extension, the Function fails to start, the terminal shows this:

    > Executing task: func host start <

    The terminal process terminated with exit code: 2

    Terminal will be reused by tasks, press any key to close it.

The root cause is that in the `tasks.json` autogenerated file, the path seems to be wrong:

    {
      "label": "Run Functions Host",
      "identifier": "runFunctionsHost",
      "type": "shell",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netstandard2.0"
      },
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$func-watch"
    }

`cwd` points to `${workspaceFolder}/bin/Debug/netstandard2.0` but the binaries are being generated at `${workspaceFolder}/bin/Hosted/Debug/netstandard2.0`.

Changing the path and adding `Hosted` seems to solve the issue.

`dotnet --version` is `2.1.402`.

**Comment by mhoeger** [comment]
@ealsur - I'm not able to repro on a Mac with `dotnet --version` as `2.1.402` and `func --version` as `2.0.3`. Is there anything apparent that's different about your scenario?

**Comment by ealsur** [comment]
Hi @mhoeger ! I tested it in several environments, and I found that the root cause is that the failing environment has an Environment Variable named **PLATFORM** with a value of **Hosted**, this makes `dotnet build` place the output in `/bin/Hosted/Debug/netstandard2.0`. 

Removing that Env Variable fixes the issue, but I wonder if someone else might hit it if they define the PLATFORM at the Environment level.
