### ISSUE TITLE
Support for IoT Hub or Event Hub Binding Template for JavaScript 

### ISSUE THREAD

**Issue by timmyreilly** [Microsoft/vscode-azurefunctions#688]
![image](https://user-images.githubusercontent.com/8118355/46431539-e9b9de80-c700-11e8-980e-3c1cf94a3cbf.png)

Looking to create a function that is bound to an Event Hub or IoT Hub, but not seeing the option. Curious what the recommended workflow is for creating this binding? 

Going to go from scratch from these docs instead: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#trigger---javascript-example

**Comment by EricJizbaMSFT** [comment]
Looks like there's already an issue in the main templates repo about the missing Event Hub template for v2 JavaScript:
https://github.com/Azure/azure-functions-templates/issues/732

Marking this as external and feel free to vote on that issue. The VS Code extension dynamically retrieves templates and will automatically get the new template once it exists.

**Comment by EricJizbaMSFT** [comment]
Closing as I can see Event Hub template now:
![screen shot 2019-02-20 at 11 16 17 am](https://user-images.githubusercontent.com/11282622/53118003-ffd60900-3500-11e9-8926-dc83e2216a5c.png)

We have a separate issue to add it to the default "Verified" category: https://github.com/Microsoft/vscode-azurefunctions/issues/690
