### ISSUE TITLE
Create Java Project adds extra folder

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#69]
<img width="609" alt="screen shot 2017-11-06 at 6 13 59 pm" src="https://user-images.githubusercontent.com/11282622/32473862-8385ec76-c31e-11e7-94d7-37e59f24c436.png">

I will never put anything else in 'myFunctionProject' folder. There should be no intermediate folder

**Comment by EricJizbaMSFT** [comment]
We should prompt before overwriting. Just use the exisiting 'confirmOverwriteFile': https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/utils/fs.ts#L18

**Comment by jdneo** [comment]
That's good.
