### ISSUE TITLE
Azure Function Deploy Error !

### ISSUE THREAD

**Issue by mobilist** [Microsoft/vscode-azurefunctions#692]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.8.1
OS: darwin

**Comment by StephenWeatherford** [comment]
Well, that's a weird message.  Does this happen consistently?  Can you provide repro steps?  Thx.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
