### ISSUE TITLE
VSCode throws an error "You must have the .NET CLI installed to perform this operation"

### ISSUE THREAD

**Issue by sagimanoj** [Microsoft/vscode-azurefunctions#693]
Repro steps:
1. Install Azure Functions Extension
2. Create new Azure function using C# 

Action: azureFunctions.createNewProject
Error type: Error
Error Message: You must have the .NET CLI installed to perform this operation.

Version: 0.11.0
OS: darwin

**Comment by sagimanoj** [comment]
I was able to fix this issue by relaunching vscode editor. Additionally, ensured the .Net Core and Azure functions extension is properly installed.

**Comment by SachinMali5333** [comment]
Which Extension of  .Net Core  you had install (Title, Owner)?
