### ISSUE TITLE
Must have the .NET CLI installed to perform this operation

### ISSUE THREAD

**Issue by SachinMali5333** [Microsoft/vscode-azurefunctions#700]
Repro steps:
1. In Azure Function extension Tag, I was selected "created New Project"
2.  I selected Repository Where function App is available in text appeared in top of project 
3. When I select Language for Project  i.e. C# then it show me following warning/Error/notification whatever it is.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: You must have the .NET CLI installed to perform this operation.

Version: 0.8.1
OS: win32

**Comment by nturinski** [comment]
Hi @SachinMali5333,

Azure Functions has a dependency on .NET for C# Function projects.  If you do not have it installed, you can download it [here](https://www.microsoft.com/net/download).

If you already have it installed, then there must be another issue. Maybe your `dotnet` alias is configured to another name?

**Comment by SachinMali5333** [comment]
thanks Issue Fixed Just Installed  .Net CLI from given link.
