### ISSUE TITLE
Deploy Python Function to Azure Function App failed

### ISSUE THREAD

**Issue by silvermoong** [Microsoft/vscode-azurefunctions#702]
Repro steps:
I'm using the auto generated Python HTTP triggered function and I'm able to debug and run it locally(with localhost url).

I firstly tried to deploy my function to my existing Function App (It has no function in it) on Azure. The deployment succeeded and I can see the new function be added into the Function App. But I got 404 when I clicked run or enter the function URL in my browser.

I then did the second deployment by creating a new Function App and Storage Account in Central US. This time I'm getting "Requested features are not supported in region." error.

When I browse the resources, I can see the Resource Group and Storage Account are created, but the Function App is not.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Requested features are not supported in region.

Version: 0.11.0
OS: win32

**Comment by silvermoong** [comment]
Hello Eric,

Thanks for the explanation.

The 404 error is happening on a Function App that I create through portal UI. I don't remember how did I set it up, but this is definitely not a Linux Function App. So I guess this could be the issue.

I deployed my python function form VS Code to the Function App. I can see it listed in the Function App. I can't run it nor access from the Function URL.  It is an anonymous http trigger.

![image](https://user-images.githubusercontent.com/17035106/46826014-8c560b00-cd5a-11e8-9e09-c5d63a0f7123.png)

![image](https://user-images.githubusercontent.com/17035106/46826018-90822880-cd5a-11e8-946b-4385115f0c5a.png)

https://yihongfunc1.azurewebsites.net/api/HttpTriggerPython

**Comment by EricJizbaMSFT** [comment]
Here's a wiki on the preview support for Python: https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-on-Linux-Preview

If you deploy through VS Code and create a new web app - make sure to use one of these regions (copied from the doc above):
- West US
- East US
- West Europe
- East Asia

**Comment by silvermoong** [comment]
Hello Eric,

It works after I create the Function App from VS Code and located in East US.

Thanks for the solution

**Comment by EricJizbaMSFT** [comment]
Awesome! I know this isn't the most obvious set of steps, but we already have a few issues to track improvements (https://github.com/Microsoft/vscode-azurefunctions/issues/619 https://github.com/Microsoft/vscode-azurefunctions/issues/641), so I'll go ahead and close this issue.
