### ISSUE TITLE
Azure Functions VSCode extension causes unresponsiveness

### ISSUE THREAD

**Issue by chojrak11** [Microsoft/vscode-azurefunctions#708]
![image](https://user-images.githubusercontent.com/15248889/46837457-b25cc900-cdb5-11e8-88a0-85a87c451215.png)

The three extensions that have potential to cause this are below, with Azure Functions being the leader:
![image](https://user-images.githubusercontent.com/15248889/46837509-e637ee80-cdb5-11e8-8a20-4d556247dada.png)

I have no idea what to check to help troubleshooting this issue and get away of this annoying notification (which is later followed by another one):
![image](https://user-images.githubusercontent.com/15248889/46837544-0bc4f800-cdb6-11e8-85eb-116dee1ff160.png)

- Extension Name: vscode-azurefunctions
- Extension Version: 0.11.0
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 17897,
		"activateCallTime": 50,
		"activateResolvedTime": 0,
		"activationEvent": "workspaceContains:local.settings.json"
	}
}
```

**Comment by EricJizbaMSFT** [comment]
@chojrak11 you're on insiders, correct? That warning is very new and was just removed. Per https://github.com/Microsoft/vscode/issues/60318:
> The notification was a great way to become aware that some extensions keep the extension host busy. However, as is, the notification is not helpful for the general user and it motivates the creation of unhelpful issues. We need to remove the notification until we have a better flow.

I'll leave this issue open to double check our actiavtion times - but hopefully you won't see that warning again anyways

**Comment by chojrak11** [comment]
@EricJizbaMSFT sorry I was AFK for a few days. It was the interim 1.28 release of VSCode that caused these warnings, which were then removed in 1.28.1 if I remember correctly. The warning is one thing, but I'm having hard time understanding what requires 16-17 seconds during initialization of this extension. Hope you'll get it sorted.
