### ISSUE TITLE
Publishing function app fails: Error Message: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by drmiru** [Microsoft/vscode-azurefunctions#719]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: TypeError
Error Message: Cannot read property 'constructor' of undefined

Version: 0.11.0
OS: win32

**Comment by Ariela1127** [comment]
I get the same error when trying to publish a function through VS. I followed the instructions outlined on the official VS pages - [here](https://code.visualstudio.com/tutorials/functions-extension/getting-started).

It happens on Windows 10 and MacOS Mojave. The version of the Azure Functions extension is 0.11.0.

**Comment by EricJizbaMSFT** [comment]
@drmiru @Ariela1127 can you give more information:
1. What language is your function project?
1. What version of the func cli do you have installed?
1. Was this an existing or brand new function app in Azure?
1. If a brand new function app - did you create through the portal or through VS Code?

**Comment by drmiru** [comment]
Mine is c#
func cli version is: 0.11.0
I created a brand new function using VS Code

**Comment by Ariela1127** [comment]
1. C#
2. Version 2
3, The app already existed in Azure but I followed the tutorial y creating a new app, then new function within VS Code.

**Comment by EricJizbaMSFT** [comment]
Would either of you mind trying the latest vsix? It probably won't fix the issue, but it might give me a slightly more helpful error message.

Download the vsix from here:
https://azcode.blob.core.windows.net/vscode-azurefunctions/master/2042/vscode-azurefunctions-0.11.1-alpha.vsix

And install with the "Install from VSIX" command:
![screen shot 2018-10-16 at 11 35 47 am 2](https://user-images.githubusercontent.com/11282622/47039008-b717d900-d137-11e8-9052-f8f586ff6fb9.png)

**Comment by EricJizbaMSFT** [comment]
Also are you using the default zip deploy or have you changed your Deployment Source to "Local Git"?

**Comment by nturinski** [comment]
Hi, @Ariela1127 and @drmiru,

We have found a consistent repro of this bug and should have a fix released on Monday (10/22).  After release, please update and let us know if it resolves your issue!

**Comment by nturinski** [comment]
Fixed by https://github.com/Microsoft/vscode-azurefunctions/pull/732.  Please re-open if the issue persists even after the new release.
