### ISSUE TITLE
Include function URL in logs

### ISSUE THREAD

**Issue by simonaco** [Microsoft/vscode-azurefunctions#72]
Love this extension! Thank you for creating it. 

Right now when publishing a new function to Azure the logs will give you the link to the function app but not for the individual functions. So this means that in order to test that my function has been deployed successfully I still need to go open the portal and copy manually the URL. Would be great to have the function url included in the logs.

**Comment by EricJizbaMSFT** [comment]
@simonaco I assume you're only interested in the url for Http triggers? Or do you find the other urls useful?

**Comment by simonaco** [comment]
@EricJizbaMSFT yes, I can only see use cases for the HttpTriggers urls.
