### ISSUE TITLE
Host unavailable after short time on func start

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-azurefunctions#720]
I had functions that were working a month ago (literally ...I demo'd on Sept 15).
I've now updated:
VS Code to 1.28.1
AF extension to .11
AF CLI to 2.0.3

I'm on macOS.

The function I'm testing has an output binding to CosmosDB so I updated the extensions.csproj to
```<ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDb" Version="3.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Twilio" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />

```
FWIW, I've also done things like re-initialize the function folder. You know me...I've been trying things for hours now. :)

When I run using func start, I get the functions running (though they take a much longer time). I head over to Postman and hit one of the functions (a post). In VS Code host window, I can see the request coming in, but then nothing happens and after a short time, I get an error message about the host being unavailable. (See below)

I've looked at every thing I could find in this repo, the azure functions host repo and the webjobs sdk repo. Nothing is helping. Any ideas?

Also, when I debug, I never even hit any breakpoints.

Possibly related..I cant stop the app. Not even with CTRL-C. I have to quit VS Code.

```
Http Functions:

        Subscribe: http://localhost:7071/api/Subscribe

        AddDatatoCosmosDB: http://localhost:7071/api/AddDatatoCosmosDB

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:7071/api/Subscribe?message=8025785506  0
warn: Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HostAvailabilityCheckMiddleware[2]
      Host unavailable after check. Returning error.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 33308.6531ms 503
```

**Comment by julielerman** [comment]
More data...
I deleted the obj and bin folders which caused an issue with the cosmosdb extension. That issue is when I ran func start, I got a warning that the extension was not installed. However, my simple HttpTrigger function worked in this case (a different function that has no cosmosdb bindings). When I reinstalled cosmosdb extension, not even that simple HttpTrigger function would work. It too, got hung up on the host being unavailable.

**Comment by julielerman** [comment]
also repo: https://github.com/julielerman/ServerlessFall2018

**Comment by julielerman** [comment]
update: I've successfully created a brand new folder, azure function app and cosmosdb trigger that I'm able to debug (only after apply the double underscore fix https://github.com/Microsoft/vscode-azurefunctions/issues/704 )

**Comment by EricJizbaMSFT** [comment]
@julielerman so is this working for you now? In other words did you get your existing project to work or just a brand new app?

**Comment by julielerman** [comment]
p.s. when I have some tme again I will go check the "breaking changes" list.

**Comment by EricJizbaMSFT** [comment]
Closing for now. Feel free to re-open if you can get a consistent repro
