### ISSUE TITLE
Java Functions don't surface exception when Cosmos DB connection string is incorrect

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurefunctions#722]
Java function using a Cosmos DB output binding was failing because the connection string app setting on the app service had an incorrect value. This was really hard to figure out because the exceptions got swallowed up and not reported in the application log

@asavaritayal

**Comment by jdneo** [comment]
@EricJizbaMSFT Do we have any solution for this kind of issue for other languages?

**Comment by EricJizbaMSFT** [comment]
I see a bright red issue in the terminal. This is the same experience for all languages. The error message isn't the most descriptive, but that would be a problem with the func cli. Closing this as either no repro (since there is an error shown contrary to when the issue was originally filed) or external (since the func cli would be responsible for the actual error message)
![Screen Shot 2019-04-18 at 1 51 21 PM](https://user-images.githubusercontent.com/11282622/56390527-15a23a80-61e1-11e9-940b-060af1bd0a07.png)

> [4/18/19 8:50:28 PM] Executing HTTP request: {
> [4/18/19 8:50:28 PM]   "requestId": "c7f91d98-d66e-4f12-a7d9-c63d68511bbe",
> [4/18/19 8:50:28 PM]   "method": "GET",
> [4/18/19 8:50:28 PM]   "uri": "/api/WriteOneDocOutputBinding"
> [4/18/19 8:50:28 PM] }
> [4/18/19 8:50:28 PM] Executing 'Functions.WriteOneDocOutputBinding' (Reason='This function was programmatically called via the host APIs.', Id=c518d0d4-07a0-4902-84a5-0ef1e6d9ea26)
> [4/18/19 8:50:28 PM] Parameters are: {name=abacdef}
> [4/18/19 8:50:28 PM] Document to be saved: {"id":"147524903", "partkey": "null"}
> [4/18/19 8:50:28 PM] Function "WriteOneDocOutputBinding" (Id: c518d0d4-07a0-4902-84a5-0ef1e6d9ea26) invoked by Java Worker
> [4/18/19 8:50:29 PM] Executed 'Functions.WriteOneDocOutputBinding' (Failed, Id=c518d0d4-07a0-4902-84a5-0ef1e6d9ea26)
> [4/18/19 8:50:29 PM] System.Private.CoreLib: Exception while executing function: Functions.WriteOneDocOutputBinding. System.Net.Http: Device not configured. System.Private.CoreLib: Device not configured.
> [4/18/19 8:50:29 PM] Executed HTTP request: {
> [4/18/19 8:50:29 PM]   "requestId": "c7f91d98-d66e-4f12-a7d9-c63d68511bbe",
> [4/18/19 8:50:29 PM]   "method": "GET",
> [4/18/19 8:50:29 PM]   "uri": "/api/WriteOneDocOutputBinding",
> [4/18/19 8:50:29 PM]   "identities": [
> [4/18/19 8:50:29 PM]     {
> [4/18/19 8:50:29 PM]       "type": "WebJobsAuthLevel",
> [4/18/19 8:50:29 PM]       "level": "Admin"
> [4/18/19 8:50:29 PM]     }
> [4/18/19 8:50:29 PM]   ],
> [4/18/19 8:50:29 PM]   "status": 500,
> [4/18/19 8:50:29 PM]   "duration": 945
> [4/18/19 8:50:29 PM] }
