### ISSUE TITLE
Redeploying a function app removing the custom route will not result in an update to functions.json

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurefunctions#723]
Redeploying a function app removing the custom route will not result in an update to functions.json. Use case: write a function, deploy it, change its route name, redeploy it – functions.json is not updated. I needed to go into the Kudu console to manually kill functions.json, otherwise it would not be updated.

@asavaritayal

**Comment by EricJizbaMSFT** [comment]
What language are you deploying? And are you deploying to linux or windows?

VS Code is just sending a zip of all the files so this might be a bug on the Kudu side. Unless we need to restart the app or something

**Comment by asavaritayal** [comment]
I believe this is for Java on Windows.

**Comment by nzthiago** [comment]
We were using VS Code + Java on Windows. The flow:
 
Deploy a Java function with a custom route.
Test it on the portal, verify the route works.
Modify the Java code to remove the “route” parameter from the trigger annotation.
Redeploy the Java function.
Test it on the portal – route still works, function.json does not get updated.
 
The only way was to kill function.json manually using Kudu, then redeploying the function.

**Comment by jdneo** [comment]
@nzthiago Is the function.json generated correctly after you modify the `route` field?

You can find the `function.json` at `./target/azure-functions/<your-function-name>/function.json`

**Comment by nzthiago** [comment]
Are you not able to reproduce it?

**Comment by nzthiago** [comment]
Got it, will ask for the team member that found the issue to help here with more info and hopefully some repro code or extra repro steps

**Comment by jdneo** [comment]
Thanks for the help. 👍

**Comment by daniel-rocha** [comment]
I'm the original reporter. I'm retesting to see if I can still reproduce it; will comment back soon.

**Comment by jdneo** [comment]
@daniel-rocha Thank you for the validation. Closing this issue for now.
