### ISSUE TITLE
Cannot uninstall Azure Functions Core Tools because it is not installed.

### ISSUE THREAD

**Issue by eternalguardian** [Microsoft/vscode-azurefunctions#726]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.uninstallFuncCoreTools
Error type: Error
Error Message: Cannot uninstall Azure Functions Core Tools because it is not installed.

Version: 0.11.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Did you have the func cli installed? This seems by-design based on the message. You can try running `func --version` to see if it's currently installed

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info

**Comment by westandy-dcp** [comment]
Could we reopen this?  I've got /usr/local/bin/func on my Mac, which I got by doing an `npm install -g azure-functions-core-tools`, but later I wanted to uninstall it by `npm uninstall -g func` or `npm uninstall -g azure-functions-core-tools` and neither work.

**Comment by EricJizbaMSFT** [comment]
@westandy-dcp when you said "neither work" can you copy the output from running those commands?

Also what happens if you run `func --version`?

**Comment by westandy-dcp** [comment]
@EricJizbaMSFT Absolutely!  Thanks for replying!

`func --version` shows 2.1.725

`npm uninstall -g func`
`up to date in 0.043s`

`which func`
`/usr/local/bin/func`

**Comment by EricJizbaMSFT** [comment]
Can you run `npm ls -g azure-functions-core-tools` and `brew ls azure-functions-core-tools` and copy the results?

How did you originally install the func cli?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info

**Comment by westandy-dcp** [comment]
Hi!  I apologize, but this thread got lost in a lot of emails.  Here's the answers to your previous questions:

`npm ls -g azure-functions-core-tools` produces 
```
/usr/local/lib
└── (empty)
```

and 

`brew ls azure-functions-core-tools`
```
/usr/local/Cellar/azure-functions-core-tools/2.1.725/Microsoft.AspNetCore.ResponseCaching.dll
/usr/local/Cellar/azure-functions-core-tools/2.1.725/Microsoft.CSharp.dll
/usr/local/Cellar/azure-functions-core-tools/2.1.725/System.Web.dll
/usr/local/Cellar/azure-functions-core-tools/2.1.725/System.Diagnostics.Contracts.dll
...
/usr/local/Cellar/azure-functions-core-tools/2.1.725/workers/powershell/ (691 files)
/usr/local/Cellar/azure-functions-core-tools/2.1.725/workers/python/ (2 files)
/usr/local/Cellar/azure-functions-core-tools/2.1.725/YamlDotNet.dll
```

**Comment by EricJizbaMSFT** [comment]
So earlier you said:
> I wanted to uninstall it by npm uninstall -g func or npm uninstall -g azure-functions-core-tools and neither work.

Based on your response just now it looks like it's actually installed with brew and not npm. Have you tried these steps and you get the same error as the original poster?
1. View -> Command Palette
1. Select "Uninstall Azure Functions Core Tools" (if you start typing "uninstall" it'll filter the results)

That should detect brew vs. npm and call the right command to uninstall. (Or you can just run `brew uninstall azure-functions-core-tools` manually, which is the command for brew).
