### ISSUE TITLE
Failing in VSCode on Mac to deploy DotNet Azure Function

### ISSUE THREAD

**Issue by dmusicant-eagle** [Microsoft/vscode-azurefunctions#729]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: ArgumentError
Error Message: Invalid Object.

Version: 0.11.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
We have done a little work to improve those error messages, but haven't released that yet. 

Does this happen consistently for you? There may have been an outage earlier causing this

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
