### ISSUE TITLE
Show Function App details

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#73]
Show Functions and Proxies for a Functions App on Azure in the tree. We should ignore Slots for now since they require extra setup while in preview. Show the following options for each resource

### Function

- Show (stream) logs
- Copy URL
- Show in Portal

### Proxy

- Show in Portal

**Comment by EricJizbaMSFT** [comment]
Breaking this up into a few separate issues:
Function streaming traces: https://github.com/Microsoft/vscode-azurefunctions/issues/11
Function copy url: https://github.com/Microsoft/vscode-azurefunctions/issues/92
Open In Portal: https://github.com/Microsoft/vscode-azurefunctions/issues/90
Proxy: https://github.com/Microsoft/vscode-azurefunctions/issues/91
