### ISSUE TITLE
Generate a wrong function URI for one deployed function app with Python

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#735]
Version: 1.29.0-insider (user setup)
Node.js: 8.9.3
Architecture: x64
Extension version: ![image](https://user-images.githubusercontent.com/34729022/47144273-b0d15a80-d2f9-11e8-9b4f-6f319610c40c.png)
Repro Steps:
1. Create a project with Python.
2. Create a Function adding an HttpTrigger.
3. Deploy to one Linux function app.
4. Copy the function Uri to terminal after deploying successfully.

Expect:
The generated function uri is right and the modified name displays well.

Actual:
Generate a wrong function URI.
![url](https://user-images.githubusercontent.com/34729022/47147894-cd719080-d301-11e8-8983-0ffe160780f2.png)

**Comment by EricJizbaMSFT** [comment]
Can you give more detail? What did you expect the url to be?

**Comment by v-xuanzh** [comment]
The generated function Uri seems to be missing **'code=...'** 
like https://test10181.azurewebsites.net/api/HttpTrigger?code=SJfrJahW0rOboyVfdkaX9AJ0iZzICqGhb5osH5XqnCp7gSsCFbPnIQ%3D%3D

**Comment by EricJizbaMSFT** [comment]
When you create an Http Trigger you have to specify the authorization level:
![screen shot 2018-10-19 at 10 31 07 am](https://user-images.githubusercontent.com/11282622/47234275-238a1680-d38a-11e8-838a-4f07bf27857d.png)

If you select "anonymous" then there will be no code. You can check this in the "function.json" file that is generated:
![screen shot 2018-10-19 at 10 32 04 am](https://user-images.githubusercontent.com/11282622/47234306-43213f00-d38a-11e8-90bd-dbee56e81ca6.png)

Closing this as by-design, but re-open if it wasn't actually an anonymous function.
