### ISSUE TITLE
'Refresh' works well after right clicking from the context menu for 'Functions' node

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#736]
**Platform/OS Version:** Win10
**Node.js:** 8.9.3
**Extension Version:** [0.12.0](https://azcode.blob.core.windows.net/vscode-azurefunctions/master/2086/vscode-azurefunctions-0.12.0.vsix
)

**Repro Steps:**
1. Drill down from one function app -> Right click 'Functions' node -> Right click 'Refresh' action.
2. Check the result.

**Expect:**
'Refresh' doesn't work.

**Actual:**
'Refresh' works well..

**Comment by EricJizbaMSFT** [comment]
I've seen this as well. The "list functions" api doesn't seem very reliable

**Comment by EricJizbaMSFT** [comment]
I believe this was fixed in https://github.com/Microsoft/vscode-azuretools/pull/383

Let me know if you're still seeing problems with it.
