### ISSUE TITLE
[Linux]Pop up an error dialog when debugging using JavaScript 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#737]
Version: 1.29.0-insider (user setup)
Node.js: 8.9.3
Architecture: x64
Extension Version: ![image](https://user-images.githubusercontent.com/41351993/47153104-298fe100-d311-11e8-9aea-122f748a0ff2.png)

Repro Steps:

1.	Click ‘Create New Project…’ -> Choose JavaScript .
2.	Create Function used the project created in Step1 and select HTTP trigger as function template.
3.	Debug index.js.
4.	Check the ‘TERMINAL’ window.

Expect:
A Url shows in the ‘TERMINAL' window After debugging.

Actual:
Pop up an error dialog:
![untitled picture1](https://user-images.githubusercontent.com/41351993/47152568-a326cf80-d30f-11e8-8983-3f9946983b89.png)
![image](https://user-images.githubusercontent.com/41351993/47153253-a753ec80-d311-11e8-9fd2-c5e0345ed509.png)

**Comment by EricJizbaMSFT** [comment]
Looks like a bug in the dotnet cli: https://github.com/dotnet/cli/issues/9807

Maybe try uninstalling or reinstalling to see if that fixes your issue. You can also try any other workarounds listed in the issue I linked

**Comment by EricJizbaMSFT** [comment]
Closing this as we haven't heard any other users run into it and the bug is in the dotnet cli
