### ISSUE TITLE
The account of file is not consistent between local and VS Code for JS & C#

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#738]
Version: 1.29.0-insider (user setup)
Node.js: 8.9.3
Architecture: x64
Extension version: ![image](https://user-images.githubusercontent.com/41351993/47153126-3ca2b100-d311-11e8-8a6b-e52a37139d21.png)

Repro Steps:

1. Create a project with the func cli using the following command:
    a.	JavaScript: "func init --worker-runtime node"
    b.	C#: "func init --worker-runtime dotnet"
2. Check the account of file is consistent between local and VS Code for JS & C# or not.

Expect:
The account of file is consistent between local and VS Code for JS & C#.

Actual:
The account of file is not consistent between local and VS Code for JS & C#.
![untitled picture2](https://user-images.githubusercontent.com/41351993/47152694-fd279500-d30f-11e8-9d21-706aa9888c2e.png)

**Comment by EricJizbaMSFT** [comment]
That is expected. Files or folders prefixed with `.` are not displayed by default on mac or linux, but they still exist.

For example, `ls` is the command to list files and it only lists two files for me. But if I do `ls -a` I can see all files/folders including "hidden" files/folders:
![screen shot 2018-10-18 at 10 04 39 am](https://user-images.githubusercontent.com/11282622/47171376-68944700-d2bd-11e8-81cf-8528a0e660db.png)
