### ISSUE TITLE
[Linux]Fail to find the HttpTrigger template when adding an HttpTrigger using command

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#739]
Version: 1.29.0-insider (user setup)
Node.js: 8.9.3
Architecture: x64
Extension version: ![image](https://user-images.githubusercontent.com/41351993/47153598-a7082100-d312-11e8-8d00-5bb0b1f2a119.png)

Repro Steps:
1. Open the ‘TERMINAL' window -> Input command "func init --worker-runtime node".
2. Add an HttpTrigger by inputting command "func new --template HttpTrigger --name HttpTrigger1".
3. Check the ‘TERMINAL' window.

Expect:
No error message in the ‘TERMINAL' window.

Actual:
Show an error messages in the ‘TERMINAL' window .
![untitled picture3](https://user-images.githubusercontent.com/41351993/47152900-9060ca80-d310-11e8-99f8-7121fb0fd439.png)

More Info:
This issue also reproduces for C#.

**Comment by EricJizbaMSFT** [comment]
What version of the func cli do you have installed? Run `func --version`

**Comment by v-xianya** [comment]
The func cli version is 2.0.1-beta.31.
![image](https://user-images.githubusercontent.com/41351993/47192310-0dc32400-d37f-11e8-812b-404896bdbe81.png)

**Comment by EricJizbaMSFT** [comment]
That version is about 4 months out of date and is a beta version. The functions team released the first non-beta version ([v2.0.2](https://www.npmjs.com/package/azure-functions-core-tools/v/2.0.2)) about a month and a half ago. Please make sure you're on at least that version when testing in the future, thanks

**Comment by v-xianya** [comment]
Got it, Thanks for your sharing.
