### ISSUE TITLE
Are deployment slots supported?

### ISSUE THREAD

**Issue by MystK** [Microsoft/vscode-azurefunctions#745]
Hello, are deployment slots supported? I can't seem to find a way to deploy to my slot through this extension.

**Comment by nturinski** [comment]
Deployment slots currently are not supported in our extension; however, we are following the issue here:
https://github.com/Microsoft/vscode-azurefunctions/issues/82

I'll close this as a duplicate, but feel free to upvote or comment in the other issue 😃
