### ISSUE TITLE
**/*.resx cannot be found

### ISSUE THREAD

**Issue by Michael-McD** [Microsoft/vscode-azurefunctions#747]
Repro steps:

1. install VS Code Azure Functions extension
2. create a C# function (using above extension)
3. select "Deploy to Function App"

Action: azureFunctions.deploy
Error type: Error
Error Message: Could not zip a non-exist file path.

Terminal output:
Restore completed in 43.08 ms for C:\Users\****\Documents\repos\analyzer\analyzer.csproj.
C:\Program Files\dotnet\sdk\2.1.403\Microsoft.Common.CurrentVersion.targets(3049,5): error MSB3552: Resource file "**/*.resx" cannot be found. [C:\Users\micha\Documents\repos\analyzer\analyzer.csproj]

Version: 0.11.0
OS: win 10 64 bit

**Comment by EricJizbaMSFT** [comment]
Can you successfully run a `dotnet publish` from the command line? The error above is expected if `dotnet publish` failed. If this is an open source project, I can take a look at your repo on Github

**Comment by Michael-McD** [comment]
Hi Eric,  

Just pulled the latest release and shortened the path length (which is know to  cause this issue sometimes) and now everything is working as expected.

Gonna close.
Michael

ps thanks for getting back.
