### ISSUE TITLE
Fail to running 'python3 -m venv_env' when creating Python project on Linux

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#748]
**Platform/OS**: Linux Ubuntu 16.04
**Node.js:** 8.9.3
**Extension Version:** [0.12.0](https://azcode.blob.core.windows.net/vscode-azurefunctions/master/2113/vscode-azurefunctions-0.12.0.vsix)

**Repro Steps:**
1. Run 'python3' and make sure that succeed to install Python.
2. Click 'Create New Project...' -> Select 'Python' language.
3. Check the result.

**Expect:**
Succeed to create Python project.

**Actual:**
Fail to create Python project with error.
![image](https://user-images.githubusercontent.com/34729092/47286012-9d86fd80-d61f-11e8-9ac4-f69610bff76e.png)

**Comment by EricJizbaMSFT** [comment]
Does this happen consistently for you? I can't get a repro. Maybe send info on the VM to me if it still repros

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT Sorry for the late reply. 
Update: This issue doesn't reproduce on my Linux machine for now.
