### ISSUE TITLE
No notification pops up to initialize for optimal use with VS Code after opening the project

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#749]
**Platform/OS**: Windows 10
**Node.js**: 8.9.3
**Extension Version**: [0.12.0](https://azcode.blob.core.windows.net/vscode-azurefunctions/master/2113/vscode-azurefunctions-0.12.0.vsix)

**Repro Steps:**
1. Run below command:
      _python -m venv env1
      env1/Scripts/activate
      func init --worker-runtime python
      func new --template HttpTrigger --name HttpTrigger1_
2. Open VS Code.

**Expect:**
Pop up below notification to initialize for optimal use with VS Code.
![image](https://user-images.githubusercontent.com/34729092/47286479-75000300-d621-11e8-89f1-a0f8e5bdf651.png)

**Actual:**
Nothing happens after opening the HttpTrigger1 in VS Code.

**More Info:**
Prompt to install pylint after running 'Azure Functions: Initializa project for use with VS Code...' manually.
![image](https://user-images.githubusercontent.com/34729092/47286571-cd370500-d621-11e8-8222-dfbfc5c8d2d8.png)

**Comment by EricJizbaMSFT** [comment]
@v-dantch the commands you ran in the screenshot don't match the commands you listed in the repro steps. Specifically you did `cd env1\Scripts`, which isn't in the repro steps. You need to stay in the 'test-env' folder. Feel free to re-open if that doesn't work for you.

**Comment by v-dantch** [comment]
Uh-oh. Thanks for your timely reminder--need to stay in the "test-venv" folder. Sorry for the mistake.
