### ISSUE TITLE
Local Git Deployment Log doesn't update in real time

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#758]
When doing a local git deploy, it hangs on `WARNING: Ignoring preDeployTask...` and then only once it finishes, displays the entire log at once.

![image](https://user-images.githubusercontent.com/5290572/47322871-6d832e80-d60e-11e8-9712-7804a4d1bdaa.png)

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/Microsoft/vscode-azureappservice/issues/754
