### ISSUE TITLE
I've followed the instructions on Microsoft's site, installing all of the listed requisites, and have gotten this far but cannot progress further.

### ISSUE THREAD

**Issue by petegooch** [Microsoft/vscode-azurefunctions#759]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: Error
Error Message: You must have the .NET CLI installed to perform this operation.

Version: 0.12.0
OS: linux

**Comment by EricJizbaMSFT** [comment]
What do you get when you run `dotnet --version` from the command line? Is the `dotnet` cli in your path?
