### ISSUE TITLE
Refactor Python tasks.json away from using terminal-specific separators

### ISSUE THREAD

**Issue by davefrancis** [Microsoft/vscode-azurefunctions#760]
OS: Windows 10 Version 1803
Azure Functions Core Tools (2.1.725 Commit hash: 68f448fe6a60e1cade88c2004bf6491af7e5f1df)
Function Runtime Version: 2.0.12134.0
ms-azuretools.vscode-azurefunctions version: 0.12.0

I'm receiving the same error message as issue #701 and #660 

**Repro Steps:**

- Install Python 3.6.6

- Create a new project with Python -> Create a new function contained in the new created project with HTTP trigger template and Function level.

- Set user setting "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\git-bash.exe" or "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"

- Debug.

**Expect:**
Succeed to debug.

**Actual:**
Fail to debug Python project with an error dialog "Fail to attach (connect ECONNREFUSED 127.0.0.1:9090)".

Note: Debugging works fine with powershell integrated terminal.

**Comment by EricJizbaMSFT** [comment]
@davefrancis the debug configuration is specified in your `tasks.json` and `launch.json` files in the `.vscode` folder. The 'windows' 'command' properties default to a PowerShell separator (`;`), but you're welcome to switch it to a cmd separator (I believe that would just be `&&`)

Let me know if that works for you.

**Comment by davefrancis** [comment]
That solved my issue thanks.

**Comment by EricJizbaMSFT** [comment]
Glad that worked for you. I'll leave the issue open, however, because I think we can potentially refactor the tasks.json so that it doesn't use terminal-specific separators and prevent similar issues in the future
