### ISSUE TITLE
VS Code (Linux) suggests to update to later Core Tools package which does not exist

### ISSUE THREAD

**Issue by polarapfel** [Microsoft/vscode-azurefunctions#761]
Hey there,

I get this annoying little reminder every time I start VS Code (on Linux).

> Update your Azure Functions Core Tools (2.0.1-beta.35) to the latest (2.1.725) for the best experience.

At this time, 2.0.1-beta.35 is the latest version available through the apt repository Microsoft provides.

Can you either disable this warning or nudge the package maintainer of Core Tools to update their package please?

Thanks,

Tobias W.

**Comment by EricJizbaMSFT** [comment]
How did you install func? Did you follow these instructions: https://github.com/Azure/azure-functions-core-tools#linux 

If you have a beta version, you may have installed with old instructions. They released the non-GA version a month-ish ago so hopefully instructions won't change much going forward. We definitely want to make sure you update to at least a non-beta version so let me know if that doesn't work and I'll follow up with the func team.

Also you should see a "Don't warn again" button that lets you disable that warning for your own machine if you really want to ignore it.

**Comment by polarapfel** [comment]
Hey @EricJizbaMSFT,

I am using this repository as documented:

`wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb`

Doing

`sudo apt-get update`

does not render a more recent version than 2.0.1-beta.35 in that repository. If they published a newer package version than that, the update mechanism in that apt repository is broken. Is the documentation wrong and did they maybe rename the package for the stable release branch to something other than azure-functions-core-tools?

**Comment by EricJizbaMSFT** [comment]
I don't have a 18.04 Ubuntu machine ready to test, but in any case I would suggest filing an issue on the func cli itself: https://github.com/Azure/azure-functions-core-tools

It definitely seems like a bug if 2.0.1-beta.35 is the latest version you can get

**Comment by EricJizbaMSFT** [comment]
Closing this as you should be able to install a later version than 2.0.1-beta.35. Please file an issue on this repo if you still can't: https://github.com/Azure/azure-functions-core-tools
