### ISSUE TITLE
Casing of 'Initialize project for use with VS Code' is wrong

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#764]
Platform/OS Version: Win10
Node.is : 8.9.3
Extension Version : [0.12.0](https://azcode.blob.core.windows.net/vscode-azurefunctions/master/2113/vscode-azurefunctions-0.12.0.vsix)

Repro Steps:
1. F1 -> Type 'Azure Functions: Initialize Project for Use with VS Code'.
2. Check the result.

Expect:
Display 'Azure Functions: Initialize Project for Use with VS Code'.

Actual:
Display 'Azure Functions: Initialize project for use with VS Code'.
![image](https://user-images.githubusercontent.com/34729092/47471946-4e1f1800-d83f-11e8-871e-d88a323e58e3.png)

**Comment by StephenWeatherford** [comment]
Should use title case for all command titles
