### ISSUE TITLE
'Microsoft.NETCore.App', version '2.0.0' was not found

### ISSUE THREAD

**Issue by SushilGujar** [Microsoft/vscode-azurefunctions#766]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\sushil.gujar\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.12.0\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\sushil.gujar\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.12.0\resources\dotnetTemplates\itemTemplates-~2.nupkg" --require "c:\Users\sushil.gujar\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.12.0\resources\dotnetTemplates\projectTemplates-~2.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name "azure.ai" --arg:AzureFunctionsVersion v2" failed with exit code "2147516547":
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

  - Check application dependencies and target a framework version installed at:

      C:\Program Files\dotnet\shared\Microsoft.NETCore.App

  - The following versions are installed:

      1.0.3

      1.0.5

      1.1.0

      1.1.2

  - Alternatively, install the framework version '2.0.0'.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@SushilGujar do you have version 2.0.0 of .NET Core installed?

That being said I'm not sure why "self signed certificate in certificate chain" is the title of this issue. Did you also have cert issues?

**Comment by SushilGujar** [comment]
Thanks Eric.
Installing Core 2.0.
Doesn't it update with Visual Code?

**Comment by EricJizbaMSFT** [comment]
No .NET Core is not included with Visual Studio Code

**Comment by EricJizbaMSFT** [comment]
Thanks for filing. Hopefully you're unblocked now - let us know if we can improve this experience somehow.
