### ISSUE TITLE
On 0.12.0, creating a C# HTTP function with AuthorizationLevel.Anonymous will create a function with AuthorizationLevel.Function

### ISSUE THREAD

**Issue by davemurphysf** [Microsoft/vscode-azurefunctions#768]
Hi there,

Pretty straight forward to reproduce.  I use 'Create Function...' button on my project and follow the wizard.  All of my functions are `Anonymous` in terms of auth, but since I've updated to 0.12.0, the template is having them be `Function` auth.

Not sure any of this matters, but for the sake of completeness I'm running on OS X Mojave, the project is .NET Core/C#.

**Comment by EricJizbaMSFT** [comment]
Looks like a change in the templates caused this. Filed https://github.com/Azure/azure-functions-templates/issues/798

A few workarounds:
1. Manually edit the authLevel from 'Function' to 'Anonymous'
1. Change the `azureFunctions.templateVersion` setting in VS Code to `2.8.0`. This will lock your template version to one that doesn't have the bug, but it also means you won't get automatic updates to the templates going forward (until you remove the setting)

**Comment by EricJizbaMSFT** [comment]
Closing as this was fixed externally
