### ISSUE TITLE
Improve experience when "azureFunctions.deploySubPath" is incorrect

### ISSUE THREAD

**Issue by khle** [Microsoft/vscode-azurefunctions#772]
Using The Azure Function extension in code

Repro steps:
Out of the box, just upload to Azure results in the error "Could not zip a non-exist file path"

Action: azureFunctions.deploy
Error type: Error
Error Message: Could not zip a non-exist file path.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@khle can you copy your `.vscode/settings.json` file here? I'm most interested in the following settings: "azureFunctions.projectLanguage", "azureFunctions.preDeployTask", and "azureFunctions.deploySubPath"

Can you also copy the logs in the "Azure Functions" output channel here?

**Comment by mariomeyrelles** [comment]
I had the same problem today. In my case, the project is a .NET project written in F#. After the migration to functions 2.0, it started with this deployment problem. Using VS Code to publish it manually it yields the same error. Let me show the steps I took visually: 

![image](https://user-images.githubusercontent.com/839937/47958375-67476780-dfa9-11e8-8e41-8168bbfbac01.png)


![image](https://user-images.githubusercontent.com/839937/47958379-7cbc9180-dfa9-11e8-916e-2294c0d4716b.png)


![image](https://user-images.githubusercontent.com/839937/47958386-a07fd780-dfa9-11e8-8909-3631defcc784.png)


![image](https://user-images.githubusercontent.com/839937/47958389-a5448b80-dfa9-11e8-9ddc-7bbf568df1d8.png)

.vscode/settings.json

    {
        "azureFunctions.projectRuntime": "~2",
        "azureFunctions.templateFilter": "Verified",
        "azureFunctions.deploySubpath": "bin/Release/netstandard2.0/publish",
        "azureFunctions.preDeployTask": "publish",
        "azureFunctions.projectLanguage": "C#"
    }


Hope this helps investigate it further:

**Comment by khle** [comment]
In my case I had 2.0 as the target framework. Azure must have expected 2.1, because when I switched to 2.1, no more error. Deploying multiple functions requires the right folder hierarchy with function.json file. I shared all of my experiences on medium.com

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mariomeyrelles** [comment]
Hello khle, 

Can you share more details?

**Comment by mariomeyrelles** [comment]
Hello,

I migrated the project to .net core 2.1.403 / sdk 2.1.5.

I can confirm that the issue still happens.

**Comment by EricJizbaMSFT** [comment]
@mariomeyrelles it looks like you need to update your `azureFunctions.deploySubpath` setting as a part of your migration from "netstandard" to "netcoreapp". This warning in one of your screenshots is the important  message:
![screen shot 2018-11-05 at 9 05 41 am](https://user-images.githubusercontent.com/11282622/48013842-269b3b80-e0da-11e8-90cf-dff342c7527c.png)

I can probably fix the original error ("Could not zip a non-exist file path.") to mention that setting. But I'm curious about the original warning - did you ignore that message or was it just confusing? If you have any suggestions for improving it that would be much appreciated.

**Comment by EricJizbaMSFT** [comment]
>  I shared all of my experiences on medium.com

@khle can you share the link to this?

**Comment by mariomeyrelles** [comment]
@EricJizbaMSFT  - I changed the setting and it gives me the same error. I was able to deploy using Azure CLI so this issue didn't block me on the weekend. 

```

{
  "azureFunctions.projectRuntime": "~2",
  "azureFunctions.templateFilter": "Verified",
  "azureFunctions.deploySubpath": "bin/Release/netcoreapp2.1",
  "azureFunctions.preDeployTask": "publish",
  "azureFunctions.projectLanguage": "C#"
}
```

Regarding the message, I accepted the suggestion and it didn't work. When I changed the setting to netcoreapp2.1, the warning gone away. I suspect the issue is related to the fact that I use a .fsproj and not, a .csproj.

**Comment by EricJizbaMSFT** [comment]
@khle cool blog article! cc @fiveisprime 

@mariomeyrelles Ah yeah I haven't spend much time with F# so I'm not sure what issues you'll run into. We have an open issue here to add support: https://github.com/Microsoft/vscode-azurefunctions/issues/315

Anyways based on your screenshots, I would expect one of these paths to work:
```
"azureFunctions.deploySubpath": "bin/Release/netcoreapp2.1/publish",
```

```
"azureFunctions.deploySubpath": "Backend/bin/Release/netcoreapp2.1/publish",
```

**Comment by mariomeyrelles** [comment]
@EricJizbaMSFT 

Thanks for your help! It worked fine :) Now I have an F# precompiled project running .net core 2.1 on Azure Functions. This is great because it has been difficult to find good examples on F#. 


The settings are shown below for sake of completeness:


`
"azureFunctions.deploySubpath": "Backend/bin/Release/netcoreapp2.1/publish",
`

```

4:51:35 PM accendis-commandProcessors: Creating zip package...
4:51:39 PM accendis-commandProcessors: Starting deployment...
4:51:50 PM accendis-commandProcessors: Fetching changes.
4:51:50 PM accendis-commandProcessors: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\yink1car.zip (6.05 MB) to D:\local\Temp\zipdeploy\extracted
4:51:55 PM accendis-commandProcessors: Updating submodules.
4:51:56 PM accendis-commandProcessors: Preparing deployment for commit id 'f083c747e7'.
4:51:58 PM accendis-commandProcessors: Generating deployment script.
4:51:58 PM accendis-commandProcessors: Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
4:51:59 PM accendis-commandProcessors: Running deployment command...
4:51:59 PM accendis-commandProcessors: Command: "D:\home\site\deployments\tools\deploy.cmd"
4:52:00 PM accendis-commandProcessors: Handling Basic Web Site deployment.
4:52:04 PM accendis-commandProcessors: Creating app_offline.htm
4:52:04 PM accendis-commandProcessors: KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
4:52:04 PM accendis-commandProcessors: Copying file: 'Backend.deps.json'
4:52:04 PM accendis-commandProcessors: Copying file: 'host.json'
4:52:04 PM accendis-commandProcessors: Copying file: 'local.settings.json'
4:52:04 PM accendis-commandProcessors: Deleting file: 'bin\DocumentDB.Spatial.Sql.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\Dynamitey.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\FSharp.Interop.Dynamic.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\Microsoft.Azure.Documents.ServiceInterop.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Collections.Immutable.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Diagnostics.DiagnosticSource.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Memory.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Security.Cryptography.Cng.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Security.Cryptography.OpenSsl.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Security.Principal.Windows.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Text.Encoding.CodePages.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Threading.Tasks.Dataflow.dll'
4:52:05 PM accendis-commandProcessors: Deleting file: 'bin\System.Threading.Tasks.Extensions.dll'
4:52:05 PM accendis-commandProcessors: Copying file: 'bin\Backend.dll'
4:52:05 PM accendis-commandProcessors: Copying file: 'bin\Backend.pdb'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\extensions.json'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\FSharp.Core.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Authentication.Abstractions.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Authentication.Core.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Authorization.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Authorization.Policy.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Hosting.Abstractions.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll'
4:52:06 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Http.Abstractions.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Http.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Http.Extensions.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Http.Features.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.JsonPatch.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Mvc.Abstractions.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Mvc.Core.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Routing.Abstractions.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.Routing.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.AspNetCore.WebUtilities.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.DocumentDB.Core.dll'
4:52:07 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.Documents.ChangeFeedProcessor.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.EventGrid.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.Extensions.CosmosDB.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.Extensions.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.Extensions.EventGrid.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.Extensions.Http.dll'
4:52:08 PM accendis-commandProcessors: Copying file: 'bin\Microsoft.Azure.WebJobs.Extensions.SignalRService.dll'
4:52:08 PM accendis-commandProcessors: Omitting next output lines...
4:52:17 PM accendis-commandProcessors: Finished successfully.
4:52:18 PM accendis-commandProcessors: Running post deployment command(s)...
4:52:21 PM accendis-commandProcessors: Syncing 8 function triggers with payload size 1292 bytes successful.
4:52:22 PM accendis-commandProcessors: Deployment successful.
4:52:59 PM accendis-commandProcessors: Waiting for long running command to finish...
Deployment to "accendis-commandProcessors" completed.


```

![image](https://user-images.githubusercontent.com/839937/48020093-2c197580-e11c-11e8-810f-df34279d368f.png)

**Comment by EricJizbaMSFT** [comment]
I think this boils down to the folder structure of your project. I've opened a separate issue to track work to improve that experience:
https://github.com/Microsoft/vscode-azurefunctions/issues/851
