### ISSUE TITLE
Enable to create Azure Function from VS Code

### ISSUE THREAD

**Issue by Himanshu-gachLabs** [Microsoft/vscode-azurefunctions#773]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: Error
Error Message: You must have the .NET CLI installed to perform this operation.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Do you have the .NET CLI installed and on your path? If not you can install it here: https://www.microsoft.com/net/download

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
