### ISSUE TITLE
Error: Response from service 'Microsoft.Web' does not contain sufficient information to enforce access control policy.

### ISSUE THREAD

**Issue by MarkusA380** [Microsoft/vscode-azurefunctions#774]
When attempting to unfold a specific subscription I get the error
```
Error: Response from service 'Microsoft.Web' does not contain sufficient information to enforce access control policy.
```
after waiting for about 3 minutes for the spinner symbol next to the subscription name to disappear.

The developer console does not contain any errors.

**Comment by EricJizbaMSFT** [comment]
@MarkusA380 can you see Microsoft.Web resources in the portal? Does this happen consistently for you?

**Comment by MarkusA380** [comment]
Please define Microsoft.Web resources?

**Comment by EricJizbaMSFT** [comment]
Sorry for the delayed response. A "Microsoft.Web" resource is an "App Service" or "Function App"
![screen shot 2018-11-28 at 11 20 52 am](https://user-images.githubusercontent.com/11282622/49176425-ae521f80-f2ff-11e8-8428-4ca04eb8aa0a.png)

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
