### ISSUE TITLE
Improved Functions binding editing experience

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#775]
Provide some kind of button (similar to the "add configuration" that's visible) to add a binding. Provide some intellisense for bindings; I believe there's a schema that we could leverage.

CC and thanks to @asavaritayal for the spec

**Comment by EricJizbaMSFT** [comment]
VS Code issue to add floating buttons in the the editor: https://github.com/Microsoft/vscode/issues/70813

**Comment by EricJizbaMSFT** [comment]
Closing this as fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/1162

The entry points are not super obvious (see screenshots in PR), but that will be improved in https://github.com/Microsoft/vscode-azurefunctions/issues/1163
