### ISSUE TITLE
Host.json suggestions out of date for functions v2

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/vscode-azurefunctions#784]
Issue Type: <b>Bug</b>

The schema changed, so for v2 projects the schema URL may need to be updated? Not sure where it's pulling from right now.  Should be noted that we do need to fix the v2 schema we have published now too as per issue Azure/azure-functions-host#3733 but assume could do both of these in parallel

Extension version: 0.12.0
VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T12:59:18.833Z)
OS version: Darwin x64 18.2.0

**Comment by EricJizbaMSFT** [comment]
@jeffhollan we pull it from http://json.schemastore.org/host

**Comment by EricJizbaMSFT** [comment]
Closing this as it was an issue on the schema side. As an example, I now see the "extensions" object as a suggestion if and only if I have `"version": "2.0"` in my host.json
