### ISSUE TITLE
Deploy PowerShell function app

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#796]
Enable the following functionality under a hide key for the PowerShell preview: 

Creation: 
- [ ] List PowerShell as one of the supported runtimes i.e. `FUNCTIONS_WORKER_RUNTIME="powershell"` when creating a function app in azure
- [x] List available templates for PowerShell /cc @soninaren 

Deployment: 
~~Create a new app on Linux Dedicated with underlying container set to `"mcr.microsoft.com/azure-functions/powershell:2.0"`~~

**Comment by soninaren** [comment]
@asavaritayal is there an action item on me for this. The templates are already part of the templates from the feed. We can put filter property on it like we did for python.
https://github.com/Azure/azure-functions-tooling-feed/blob/master/cli-feed-v3.json#L454

**Comment by EricJizbaMSFT** [comment]
I can already see these templates for PowerShell so @soninaren I don't think you need to do anything:
![screen shot 2018-11-09 at 11 28 28 am](https://user-images.githubusercontent.com/11282622/48283865-a6930f80-e412-11e8-8597-541c42427d08.png)

**Comment by EricJizbaMSFT** [comment]
@asavaritayal what's the priority of this?:
> Create a new app on Linux Dedicated with underlying container set to "mcr.microsoft.com/azure-functions/powershell:2.0"

I assume Windows Consumption will be the default/most common for PowerShell?

**Comment by asavaritayal** [comment]
@EricJizbaMSFT yes Windows Consumption will be the default for public preview. 

(For context, we experimented with Linux dedicated for private preview but have decided to discontinue on that path for now.)

/cc @eamonoreilly @anirudhgarg

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azuretools/pull/460
