### ISSUE TITLE
PowerShell Functions Debugging

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#797]
Enable F5 experience for PowerShell Functions leveraging the [PS extension for VS Code](https://code.visualstudio.com/docs/languages/powershell#_debugging)

/cc @joeyaiello @TylerLeonhardt

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/1075
