### ISSUE TITLE
Deploy python to linux appservice with error

### ISSUE THREAD

**Issue by javiermarasco** [Microsoft/vscode-azurefunctions#798]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Python projects are not supported on Windows Function apps.  Deploy to a Linux Consumption app.

Version: 0.12.0
OS: win32

The azure function created is a linux one, even using the wizard from vscode extension for azure functions it fails.

**Comment by EricJizbaMSFT** [comment]
@javiermarasco do the apps show as "Linux Preview" like this in VS Code?:
![screen shot 2018-11-08 at 9 46 58 am](https://user-images.githubusercontent.com/11282622/48217066-441b1000-e33b-11e8-9638-7e1a6e0e4d3f.png)

And do they also show as Linux Consumption in the portal?
![screen shot 2018-11-08 at 9 47 38 am](https://user-images.githubusercontent.com/11282622/48217118-66ad2900-e33b-11e8-80df-87ee0a771216.png)
![screen shot 2018-11-08 at 9 47 41 am](https://user-images.githubusercontent.com/11282622/48217120-67de5600-e33b-11e8-8ce6-20ce7942a1c7.png)

**Comment by EricJizbaMSFT** [comment]
It should automatically happen if you create the function app from VS Code _with a python project open_. Specifically, we're looking at your "azureFunctions.projectLanguage" setting in VS Code to determine if it's a Python project.

You can also try following this link: http://aka.ms/functions-consumptionlinux-portal

It will take you to the portal with "Linux Consumption" enabled. When you go to create a function app you should see the "Linux" and "Consumption" options like this:
![screen shot 2018-11-09 at 9 29 18 am](https://user-images.githubusercontent.com/11282622/48278318-0a610c80-e402-11e8-8f58-98af998b5777.png)

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT , thanks for your share. 

From portal, I can succeed to create a Linux consumption function app like below.
![image](https://user-images.githubusercontent.com/34729092/48339604-8ded5880-e6a3-11e8-85e1-494372720353.png)

**Comment by EricJizbaMSFT** [comment]
@carltongibson the error (`This operation is not supported by App Service plans with kind "functionapp,linux" and sku tier "Dynamic"`) is expected. Some scenarios just aren't supported on Linux Consumption apps yet. However, feel free to file an issue on this repo to make sure we address your specific scenario going forward. And yes - I also see 401 errors occasionally. I don't think there's anything the VS Code extension can do about this and I would recommend following the "Questions & Help" section [here](https://github.com/Azure/azure-functions#questions--help) if that error keeps happening.

**Comment by EricJizbaMSFT** [comment]
@javiermarasco it's possible your company subscription doesn't allow preview features. I would talk to your subscription admin or ask for help from the Functions team directly per [these instructions](https://github.com/Azure/Azure-Functions#questions--help). If it's not working in the portal then unfortunately there's probably not much the VS Code extension can do either. Let me know if you figure it out because the one thing we might actually be able to do is show a better error message

**Comment by carltongibson** [comment]
Hi @EricJizbaMSFT. Thanks for the reply. Bar the original issue here, which does seem suboptimal from the extension's POV, I agree the other issues may be out of your control. I would hope for better error messages if you're expecting an issue, but I leave that with you. Other than that I'm just reporting my experience: with these hurdles out the way the extension works well I think. Thanks for your help.

**Comment by JohnReeson** [comment]
@EricJizbaMSFT Is there any reason we can't deploy python function to dedicated app service plan in VSCode? With Cli it succeeds.

**Comment by EricJizbaMSFT** [comment]
This issue has quite a bit going on, so I'm splitting it up into a few new/existing issues.
1. Sometimes VS Code says `Python projects are not supported on Windows Function apps. Deploy to a Linux Consumption app.` even when it _is_ a linux function app #893 
1. Provide an "advancedCreation" setting that allows users to explicitly select their OS #898
1. Address @JohnReeson's comment about dedicated plans. We prioritized consumption plans first, but there's no reason we should block dedicated plans. #906

If there's anything still not addressed feel free to file a new issue. I think the original issue by @javiermarasco may have been specific to his subscription in any case (and would be better followed up directly with the Functions team in Azure https://github.com/Azure/Azure-Functions#questions--help)
