### ISSUE TITLE
Node js create function issue

### ISSUE THREAD

**Issue by archunanswaas** [Microsoft/vscode-azurefunctions#799]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: Error
Error Message: Unable to write to Folder Settings because no resource is provided.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@archunanswaas how did you get this error? Can you detail your repro steps?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
