### ISSUE TITLE
Change default to Node 10

### ISSUE THREAD

**Issue by ColbyTresness** [microsoft/vscode-azurefunctions#805]
Node 10 is now LTS and we're planning on making it the default. 

Tracking issues for addition of 10.13 and core tools default switch:

https://github.com/Azure/azure-functions-nodejs-worker/issues/145
https://github.com/Azure/azure-functions-core-tools/issues/867

**Comment by EricJizbaMSFT** [comment]
I'll double check, but this should happen automatically in VS Code as long as the feed is updated:
https://functionscdn.azureedge.net/public/cli-feed-v3.json

**Comment by ColbyTresness** [comment]
So I checked with @soninaren and it looks like the node version parameter in the feed is a min supported version, not a default. So this might have to be an additional change. We support 10.14.1 now, so would like to default to that if possible.

**Comment by ColbyTresness** [comment]
I've had a longer conversation about this with @soninaren @mhoeger @paulbatum. The language version for a function app is set by an app setting included in the ARM template which creates the app. For the portal and CLI, this is hard coded. The above makes me think that we're populating this setting based on the version coming from the templates feed, is that correct @EricJizbaMSFT ? If so, we need to make this slightly smarter - per above, the node version in the feed is supposed to be a min version. We're planning to augment the feed with more information (detailed in https://github.com/Azure/azure-functions-templates/issues/837) to include desired default in addition to min version, and likely help each tool make more intelligent decisions about what version to set.

**Comment by EricJizbaMSFT** [comment]
@ColbyTresness Yes we're using the feed for this. When do you plan to add the default value to the feed? I'd rather wait for that than hard code "10.something" temporarily

**Comment by ColbyTresness** [comment]
Hopefully this sprint - @soninaren would know more. I agree though, we should wait for the default value in the feed before changing this.

**Comment by ColbyTresness** [comment]
@soninaren when can we expect this in the feed?

**Comment by soninaren** [comment]
@mhoeger is going to make this change. As if now the the target is sprint 45, here is the related issue for it.
https://github.com/Azure/azure-functions-tooling-feed/issues/71

**Comment by mhoeger** [comment]
We've changed the default [in the feed](https://github.com/Azure/azure-functions-tooling-feed/blob/415d731e624dfc7a19e35ba797bea99715056a5f/cli-feed-v3.json#L2447) to `~10`, which targets the latest available major version of Node.js 10 in Azure (on Windows machines). @ColbyTresness - I've double checked this works as expected. You can close this as resolved!
