### ISSUE TITLE
VS Code extension will always exit upon trying to build and debug

### ISSUE THREAD

**Issue by whaakman** [Microsoft/vscode-azurefunctions#810]
Tried different directories, different ways to create and test my function (standard HTTPTrigger). However the result is always te same. Creating the function from command line with the function CLI works fine. 

Repro steps:
Following the exact steps as documented per: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.12.0
OS: win32

**Comment by whaakman** [comment]
It seems like it's an issue where dotnet build is ran from. Running the commands from the tasks.json one by one manually works fine and the Azure executes. Can this be a path issue?

**Comment by EricJizbaMSFT** [comment]
Can you copy the full output of the 'clean' task when it fails?

**Comment by whaakman** [comment]
Sure. 

> Executing task in folder HTTPTrigger: dotnet clean <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.


This is my tasks.json (generated automaticly)

{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "clean",
      "command": "dotnet clean",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "build",
      "command": "dotnet build",
      "type": "shell",
      "dependsOn": "clean",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "clean release",
      "command": "dotnet clean --configuration Release",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "publish",
      "command": "dotnet publish --configuration Release",
      "type": "shell",
      "dependsOn": "clean release",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$msCompile"
    },
    {
      "label": "runFunctionsHost",
      "type": "shell",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netcoreapp2.1"
      },
      "command": "func host start",
      "isBackground": true,
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": "$func-watch"
    }
  ]
}

**Comment by EricJizbaMSFT** [comment]
@whaakman can you post a screenshot of your workspace? Are your *.csproj and *.cs files at the root of the workspace? This may be a path problem, but the task is supposed to use the current workspace root by default

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
