### ISSUE TITLE
Don't install pylint by default in new functions environments

### ISSUE THREAD

**Issue by qubitron** [Microsoft/vscode-azurefunctions#814]
I noticed that pylint is installed as part of initializing your new environment, this was done as a fix to #631, but this isn't the right solution to this problem as we are also planning to move away from pylint when the language server becomes the default.

**Comment by EricJizbaMSFT** [comment]
@qubitron have you already removed the prompt to install pylint from the Python extension? If not - can you link to an issue for us to track? I don't think I'm willing to change this until I know that prompt is gonna haha

**Comment by qubitron** [comment]
We've removed the banner only if you have the language server enabled, so for most users they will still get the prompt until the language server becomes the default. We don't have an issue tracking that default yet, but when we have one I will link it here.

The other option is to explicitly disable pylint for functions apps in these workspaces, by adding the following to a settings.json file:
```
  "python.linting.pylintEnabled": false
```

But then users don't any errors when editing... so I suppose the current state of things is OK.

**Comment by EricJizbaMSFT** [comment]
@qubitron can you link to an issue we can track? When will the python extension ship an update removing that pylint error?

**Comment by qubitron** [comment]
Here's the issue that tracks this:
https://github.com/Microsoft/vscode-python/issues/2722
