### ISSUE TITLE
Creating Azure Functions app failed in Azure China

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azurefunctions#816]
Repro steps:
1. Creating a c# iothub triggered function.
2. Try to create Azure Functions App to Azure China env.
3. Failed with error 'Dynamic pricing tier is not enabled for this subscription.'

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Dynamic pricing tier is not enabled for this subscription.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@lirenhe are you able to create a function app in the portal? The error message seems pretty clear that that subscription doesn't support consumption plans

**Comment by lirenhe** [comment]
I could create it in the portal. But when creating Azure Functions, i have to specify App Service Plan. I guess this is because consumption plans is not supported in Azure China.  https://feedback.azure.com/forums/355860-azure-functions/suggestions/34491388-consumption-plan-china

**Comment by EricJizbaMSFT** [comment]
Yeah I think the portal defaulted to a dedicated plan instead of consumption for linux. Make sure you're trying to get consumption. In any case I think the error is somewhat clear and this feels like an external bug so I'll go ahead and close
