### ISSUE TITLE
Remove package-lock.json from .gitignore

### ISSUE THREAD

**Issue by dpwatrous** [Microsoft/vscode-azurefunctions#819]
First of all, nice work addressing the event-stream issue (https://github.com/dominictarr/event-stream/issues/116) so quickly yesterday! In light of that (and other past & future issues) I'd like to suggest using a package-lock.json (or yarn.lock) file committed to source control.

package-lock.json is currently added to .gitignore with the following comment:

```
# package-lock file since it just causes merge conflicts
package-lock.json
```

It's true they can be a bit of a pain, but in my experience the benefits outweigh the risks here. For example, the VSCode repo itself would have been hit with the event-stream issue if not for using a lock file.

**Comment by dpwatrous** [comment]
Here's a PR: https://github.com/Microsoft/vscode-azurefunctions/pull/820

**Comment by EricJizbaMSFT** [comment]
@dpwatrous thanks for the suggestion. We've gone back and forth on `package-lock.json` and I'm definitely open to either option.

I understand that package-lock.json prevents getting the latest (malicious) packages like the recent event-stream, but doesn't it also slow us down in getting the latest _helpful_ security updates?

**Comment by dpwatrous** [comment]
Yeah, it's a tradeoff for sure - the downside is you have to be much more active in managing the project's dependencies or as you said you'll fall behind. IMO that's the cost of taking on dependencies, which is often under-appreciated in the Node/NPM ecosystem.

That said, the tooling around lock files definitely helps. Running an update command is a lot easier than bumping versions by hand. :)

**Comment by EricJizbaMSFT** [comment]
Sounds fine to me. Although we have several repos and I'd like to keep the process consistent. @StephenWeatherford @nturinski @PrashanthCorp any objections to adding back the `package-lock.json` to our repos?

**Comment by EricJizbaMSFT** [comment]
Discussed offline with team and they're okay with it. Thanks!

**Comment by dpwatrous** [comment]
Awesome, thanks, Eric. I've been digging the extension by the way!
