### ISSUE TITLE
Show slots in explorer

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#82]
Slots (preview)

The user has to set some environment variable to enable slots. We should handle that appropriately (warn the user or something)

**Comment by jameshowe** [comment]
Does this issue cover the ability to be able to deploy from VSCode to a slot? Seems like all that's missing is the ability to target that slot from the list.

**Comment by jameshowe** [comment]
> Are you using slots regularly with Functions? And is it working well for you?

Only just starting to experiment with them, will they effectively work the same as Web App slot settings? i.e. hot swap, slot settings etc.
