### ISSUE TITLE
Reported Backdoor Trojan in 0.12.0 Release

### ISSUE THREAD

**Issue by jeffpignataro** [Microsoft/vscode-azurefunctions#823]
After the most recent update (0.12.0) a file within an associated node module, "flatmap-stream\test\data.js", is reporting an instance of Troj/Bckdoor-AL from the SOPHOS Enterprise Suite. Can anyone confirm if this node module is compromised? Or if perhaps this is just a heuristics issue?

![image](https://user-images.githubusercontent.com/1724466/49169025-1c91e480-f2f6-11e8-8a9e-0bf8f2b62d7b.jpg)

**Comment by EricJizbaMSFT** [comment]
Thanks for checking @jeffpignataro 

We released an update on Monday to address this - please make sure you are on version 0.12.1. See the changelog here: https://github.com/Microsoft/vscode-azurefunctions/blob/master/CHANGELOG.md#0121---2018-11-26

Also see this VS Code blog post for more information about this issue: https://code.visualstudio.com/blogs/2018/11/26/event-stream

**Comment by jeffpignataro** [comment]
That's awesome @EricJizbaMSFT! Thank you so much. I was really panicking. I'm so glad to hear you guys have it under control and even already dealt with it. Thank you for being attentive and responsive!
