### ISSUE TITLE
Enable --build-native-deps for Python

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#826]
Action: azureFunctions.deploy
Error type: ENOENT
Error Message: ENOENT: no such file or directory, stat '/Users/asavaritayal/connect2018-function/recommender.zip'

![image](https://user-images.githubusercontent.com/8435148/49175814-43ecaf80-f2fe-11e8-8dc1-c6f746000411.png)

Version: 0.12.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
I'm guessing the `func pack` task failed. Is that the path you were expecting?

In any case, we can improve the error message to tell you that the `func pack` task failed instead.

**Comment by asavaritayal** [comment]
I was able to resolve the issue by switching over to the CLI to use the following command:

```
func azure functionapp publish <app name> --build-native-deps
```

The command requires the docker host to be installed on the user's machine, in order to build the right binaries for the linux platform.

@EricJizbaMSFT do you think we can catch the exception and automatically retry publishing using the `--build-native-deps` flag? Brainstorming and open to options ...

**Comment by EricJizbaMSFT** [comment]
Can you copy/paste the current output of `func pack` (without build-native-deps)? I'm curious what the error looks like today.

In regards to your suggestion - can that be handled directly in the cli? Ideally the cli detects whether you have native-deps and does a "normal" or "build-native-deps" pack as applicable...without the need for the extra flag

**Comment by asavaritayal** [comment]
Here's an example: 

```
There was an error restoring dependencies.ERROR: cannot install <package name - version> dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to try building the binary dependencies using a Docker container.
```

We don't automatically re-try in the CLI since users need to first ensure that docker is installed. 

The ideal experience would be for Code to catch the exception and check if docker is installed. If not, prompt the user to install docker and re-try publishing, powered by the bottom right hand notification.

Thoughts?

**Comment by EricJizbaMSFT** [comment]
> We don't automatically re-try in the CLI since users need to first ensure that docker is installed.

Can't you just throw an error if docker isn't installed?

**Comment by ashfondu** [comment]
for me i had to use --force at the end of the command along with what asavaritayal recommended
but it eventually error'ed with the following

Error running docker exec -t 68e4cbbca24e5c6e2f6b44d74b29ef97e041451138db7b857c447d218f182c85 /python_docker_build.sh.
output: Collecting azure-functions==1.0.0a5 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/4a/1f/188f1a80410d48b89db35eed44eddfa56c315e307d9533c984f46fe5471b/azure_functions-1.0.0a5-py3-none-any.whl
Collecting azure-functions-worker==1.0.0a6 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/aa/4f/0e2f1a0f232a01cec13cada0d897265deb0a9bea1d9ea98a7ed955c50f5a/azure_functions_worker-1.0.0a6-py3-none-any.whl (41kB)

**Comment by ashfondu** [comment]
was able to finally get a function published after the error above
i had to comment out the pkg-resource from the requirements.txt file

**Comment by EricJizbaMSFT** [comment]
@asavaritayal I still don't think the VS Code extension should do anything here. I think this should be automatically handled by the func cli when we call `func pack` and there should be no need for a `--build-native-deps` flag

We've already got [one review](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions#review-details) saying "Incredibly difficult to get up and running with Python. Requires a lot of additional configuration to work." and I don't want to make docker another configuration requirement

**Comment by asavaritayal** [comment]
@EricJizbaMSFT Docker will to be required for the build if native dependencies are involved. Unfortunately, the CLI won't be able to get around this requirement either.

**Comment by EricJizbaMSFT** [comment]
IMO the cli should do the following:
1. Check if there are native dependencies:
    1. If no, do the simple 'func pack'
    1. If yes, check if docker is installed:
        1. If no, throw an error
        1. If yes, do the more complex 'func pack' including native deps

I don't think any of that logic should be done by the VS Code extension and it makes the `--build-native-deps` flag obsolete since you're automatically doing the checks.

**Comment by fiveisprime** [comment]
I agree with Eric on this one. Keeping this login in the CLI will also improve consistency between the tools. Is there any reason why the CLI couldn't do this?

I'd also like to avoid adding it to the extension because I expect that this functionality will eventually shift out of the tools and into the deployment pipeline. Ultimately, this responsibility _should not_ fall on the user (this isn't a part of the local development loop).

**Comment by asavaritayal** [comment]
> IMO the cli should do the following:
Check if there are native dependencies:
If no, do the simple 'func pack'
If yes, check if docker is installed:
If no, throw an error
If yes, do the more complex 'func pack' including native deps

@ankitkumarr is it feasible to implement this logic in the CLI? perhaps with explicit information about why docker is being used, if so.

> I'd also like to avoid adding it to the extension because I expect that this functionality will eventually shift out of the tools and into the deployment pipeline. Ultimately, this responsibility should not fall on the user (this isn't a part of the local development loop).

@fiveisprime agree with you that this shouldn't be part of the local development loop. Unfortunately, the resolve for this is still months away and the experience is not yet locked down. The docker path is an attempt to provide a stop gap so Python users are still able to succeed in the meantime.

**Comment by ankitkumarr** [comment]
@asavaritayal, yeah, I think it is feasible to implement this logic in the CLI. I thought it was done this way so that the user knows and understands that Docker will be used. But if we explicitly say, it should be fine.

The only other concern I would have is it does take time to collect the wheels and determine if "native dependencies" are present (done by packapp). So, if native dependencies are present, every time the user would try and publish, we would do this additional long step of checking and then take the Docker path. 

If this is necessary for VS Code, then I recommend if we figure out that they need to use the Docker path, we ask them to use `--build-native-deps` in the core-tools next time they publish to avoid this check again. Maybe, VS Code can not display this message if that's possible?

But keep in mind, Docker step already takes very long. Making it this way in VS Code will add on to the publishing time significantly.

**Comment by EricJizbaMSFT** [comment]
Just to summarize offline discussion:
Long term this kind of logic will shift out of local development loop. For now, VS Code will detect the error, show a message, and add the `--build-native-deps` flag for them.

Biggest question remaining is how we detect the error. For example do we just look for `Use the --build-native-deps option to try building the binary dependencies using a Docker container.` or do we have some sort of error code that is less susceptible to change

**Comment by ankitkumarr** [comment]
>Biggest question remaining is how we detect the error. For example do we just look for Use the --build-native-deps option to try building the binary dependencies using a Docker container. or do we have some sort of error code that is less susceptible to change

@EricJizbaMSFT, I can add a specific exit code for that in azure-functions-core-tools. Would that work?

**Comment by EricJizbaMSFT** [comment]
@ankitkumarr yep that would be great
