### ISSUE TITLE
Add slot support for listing functions

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurefunctions#830]

**Comment by EricJizbaMSFT** [comment]
Could be fixed with https://github.com/Azure/azure-functions-host/issues/3994

**Comment by ahmedelnably** [comment]
@EricJizbaMSFT is it possible to get this enabled, the GA is planned for This Friday

**Comment by EricJizbaMSFT** [comment]
@ahmedelnably we can try, but probably a stretch at this point.

cc @fiveisprime @jinglouMSFT

**Comment by ahmedelnably** [comment]
It is fine, if it is in the next release no need to for extraordinary effort to get it sooner
