### ISSUE TITLE
[Suggestion] Add an action to open function apps in Browse 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#836]
**OS:** All
**Node.js:** V8.12.0
**Build Definition:** [20181127.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=923&view=results)

**Repro Step:**
Right click one function app and check the context menu.

**Suggestion:**
Add a action to open function apps in Browse.

**Actual:**
There is no action to open the function app in Browse.
![image](https://user-images.githubusercontent.com/34729092/49205207-37915100-f3e9-11e8-91a4-cbd294d4bede.png)

**Comment by EricJizbaMSFT** [comment]
Function apps don't host websites (unlike web apps) so users likely won't browse to the site. Function apps provide trigger urls and that is the main entry point

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT , thanks for your update.
