### ISSUE TITLE
Refactor the java project creation logic when HTTP API is ready.

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#84]
Currently, since there is no host endpoint that can provide Java Azure Functions templates. To get the Java function metadata, we are leveraging other language's metadata to create a new Java function.

Code [here](https://github.com/jdneo/vscode-azurefunctions/blob/4532fc55343ed8bb8313e7cc4c907af8ea1641c0/src/templates/TemplateData.ts#L71) needs to change when java project creation logic when HTTP API is ready.

**Comment by jdneo** [comment]
Hi @EricJizbaMSFT @akaroml @pragnagopa @brunoborges please take a look at this issue and let me know if you have any feedback about the proposed solution.

Currently the Java function templates is cached in [Maven plugin itself](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/src/main/resources/templates.json). I'm thinking that to extract these templates and move to another new artifact. Then publish it as a jar into Maven Central.

## What will tooling do to resolve the templates:

- For Maven plugin: The templates artifact will become a dependency in pom
- For VS Code extension: We can have a JavaTemplateRetriever that download the Java Functions metadata

## What are the benefits
- We will have a unified place to host all the Java templates.
- We will have a mechanism to manage the Java templates through versions.
- The hack in the VS Code extension can be removed.

## Some questions that I haven't figured out yet
- Which repo do we use to host the templates code?
- When resolve the matedata in VS Code extension, how to figure out which version should be used.

**Comment by jdneo** [comment]
Finally, we addressed this issue by centralizing the templates metadata into the Maven plugin. And by triggering `mvn azure-functions:list`, it will provide all the templates and metadata, which can be consumed by VS Code extension.

@EricJizbaMSFT I think this issue can be closed for now?

**Comment by EricJizbaMSFT** [comment]
Yep. Fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/487
