### ISSUE TITLE
mvn problem with VS Code

### ISSUE THREAD

**Issue by MDCR55** [Microsoft/vscode-azurefunctions#840]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to run "mvn" command. Check output window for more details.

Version: 0.12.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@MDCR55 can you copy the logs from the output window?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info.
