### ISSUE TITLE
The maximum of the slot name isn't 64 characters

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurefunctions#845]
**OS:** All
**Node.js:** V8.12.0
**Build Number:** [20181201.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1165&view=results)

**Repro Steps:**
1. Change the setting “azureFunctions.enableSlots” to true.
2. Right click 'Slots' node -> Select 'Create Slot...' --> Try to enter a unique slot name with multiple characters.
3. Check whether the maximum is 64 characters or not.

**Expect**:
The maximum of the slot name is 64 characters.

**Actual**:
1. The maximum of the slot name is 38 characters for **Windows** function apps.
2. The maximum of the slot name is 49 characters for **Linux** function apps.
![chars](https://user-images.githubusercontent.com/34729022/49363041-8efe2c80-f71b-11e8-92f5-71a896667aac.png)

**Comment by EricJizbaMSFT** [comment]
We can probably just change the message to:
> Combination of site name 'emj1' and slot name must be less than 64 chars...
