### ISSUE TITLE
An error occurs after installing the Azure Function and Azure App Service extensions

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#846]
**OS:** All
**Node.js:** V8.12.0
**Build Number:** [20181201.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1165&view=results)

**Repro Steps:**
1. Install the Azure Function extension [20181201.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1165&view=results).
2. Install the App Service extension which is integrated the new feature 'Deployment' node like [20181130.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1151&view=results)
3. Reload VS Code -> Expand these two installed extensions on Azure Explorer.

**Expect**:
There is no error.

**Actual**:
An error occurs on the bottom.
![error](https://user-images.githubusercontent.com/34729022/49362411-ae945580-f719-11e8-907e-901d07a557ed.png)

**Comment by v-xianya** [comment]
Verified with build 20181203.6. 
1. This issue reproduces on MacOS.
2. This issue doesn't reproduce on Windows/Linux. 
3. Function tool version: 2.2.70.

**Comment by EricJizbaMSFT** [comment]
I can't reproduce this on any OS. @v-xianya sometimes when you install a vsix with the same version, it doesn't actually update. Please try deleting the extension from your extensions folder and re-installing.

Windows `%USERPROFILE%\.vscode\extensions`
macOS `~/.vscode/extensions`
Linux `~/.vscode/extensions`

**Comment by v-xianya** [comment]
Thanks for your updates.  This issue doesn't reproduce according to the way you shared. Could you help to resolve it?
