### ISSUE TITLE
Create Java function takes ~30 seconds

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#85]
Need to check about the maven azure function archetype

**Comment by akaroml** [comment]
This is the nature of Maven. Please put it in backlog and revisit when service team decides to support running Java code without class files.

**Comment by EricJizbaMSFT** [comment]
Median time is 11.195s according to BI team. Closing this issue and opening another one to improve performance in a later release: https://github.com/Microsoft/vscode-azurefunctions/issues/100
