### ISSUE TITLE
Pop up an error dialog when debugging function project with JavaScript

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#850]
**OS:** Windows/Linux
**Node.js:** V10.13.0
**Build Number:** 20181203.6

**Repro Steps:**

1. Create a new project using JavaScript.
2. Create a new function and add Httptrigger.
3. Debug.

**Expect:**
Succeed to debug.

**Actual:**
Prompt an error dialog during debugging.
Windows:
![image](https://user-images.githubusercontent.com/41351993/49486007-f16c3f80-f877-11e8-8262-646680767aa5.png)
Linux:
![image](https://user-images.githubusercontent.com/41351993/49486027-fe892e80-f877-11e8-8bea-648307814fac.png)

**More Info:**
This issue doesn't reproduce on MacOS.

**Comment by EricJizbaMSFT** [comment]
I believe this was due to a bug in VS Code insiders: https://github.com/Microsoft/vscode/issues/54397#issuecomment-443826345

@v-xianya  They just reverted a commit that caused this, so please try this again in the next few days (after Insiders creates a new build with that fix)

**Comment by EricJizbaMSFT** [comment]
Closing this as external bug - shouldn't repro any more.
