### ISSUE TITLE
Enable publishing to 'Premium (preview)' plan

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#854]
The Azure Functions premium plan is a new hosting option for function apps that provides premium features like VNet connectivity, no cold start, and premium hardware, without having to compromise on things like latency or scale. More info here - https://github.com/Azure/Azure-Functions/blob/master/functions-premium-plan/overview.md

Using the Az Func Code extension, a user should be able to pick the premium hosting plan for their Function App.

#### Proposed workflow

If a user picks `+ Create a new Function App` during publishing, ask for a unique name and present with the following options for hosting:

```
Select a hosting plan
     - Consumption Plan
     - Premium Plan (preview)
```

The selection should always default to Consumption.

Corresponding CLI workflow is documented here - https://github.com/Azure/Azure-Functions/blob/master/functions-premium-plan/getting-started.md

More details **TBD**

/cc @jeffhollan

**Comment by EricJizbaMSFT** [comment]
Should probably be done with https://github.com/Microsoft/vscode-azurefunctions/issues/811

**Comment by EricJizbaMSFT** [comment]
https://azure.microsoft.com/en-us/blog/announcing-the-azure-functions-premium-plan-for-enterprise-serverless-workloads/
