### ISSUE TITLE
Signin to Azure not working

### ISSUE THREAD

**Issue by SeanVSpr** [Microsoft/vscode-azurefunctions#856]
I'm not entirely sure this is the right place for this error.
The issue occurs whenever I try to sign in to Azure to deploy my functions.

The steps taken are the following: 
1. Perform Azure sign-in.
2. Receive a code which needs to be filled in to https://microsoft.com/devicelogin
3. Doing this redirects to the login page where I login with my account.
4. Everything seems in order, the browser even gives me a confirmation that the login was successful and that I can close the window.
5. In vscode the sign in goes back to the original state, telling me to sign in.

When I then open the developer tools in vscode and check the console I get the following error:
"AADSTS50097: Device authentication is required.
Trace ID: 80d13cfb-a93b-4634-9a9d-1be1eec93900
Correlation ID: ab2f20a6-61bb-440b-be09-6ba4e93a4620
Timestamp: 2018-12-10 09:45:19Z"

As far as I know the process that I just did, was the device authentication...

**Comment by EricJizbaMSFT** [comment]
Moved to https://github.com/Microsoft/vscode-azure-account/issues/119

Thanks!
