### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by djvibe** [Microsoft/vscode-azurefunctions#865]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: 401
Error Message: Failed with code "401".

Version: 0.13.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@djvibe can you give a little more information?:
1. Does this happen consistently for you?
1. Has deploy ever worked for you?
1. What type of project are you trying to deploy?
1. Was this a branch new function app or an existing one?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
