### ISSUE TITLE
Proxy problem when creating python function

### ISSUE THREAD

**Issue by Bandit253** [Microsoft/vscode-azurefunctions#868]
I am running in a authenticated proxy environment and I get this error, "Connection to pypi.org timed out..." I have the proxy set in the settings but that does not seem to effect this creation script.

I have manually run that command and the subsequent one, "pypi ptvsd"  in a python script that sets the proxy but that seems to break the project structure.  Also noticed a similar issue with "pylint"

Repro steps:
Create python function

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run ".env\Scripts\activate && func init ./ --worker-runtime python" command. Check output window for more details.

Version: 0.13.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@Bandit253 when you say "I have the proxy set in the settings" what are you talking about?  Are you using the new `http.proxySupport` setting as described here?: https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-443850698 If not - can you try setting it to "override" and let me know if it works?

Also you mentioned you got this somewhat working with your own Python script. Can you copy that here (removing any sensitive information first)? We might need to pass in the proxy settings... also I might be able to help you get a script that doesn't "break the project structure"

**Comment by Bandit253** [comment]
I set http.proxy in the user settings, interestingly there does not seem to be a setting for https?

This is what I ran to install failed bits. two lines commented out
`import os

os.environ["http_proxy"]="https://proxysuer:password@proxyserver:8080"
os.environ["https_proxy"]="https://proxysuer:password@proxyserver:8080"

#os.system("func init ./ --worker-runtime python")
#os.system("pip install ptvsd")
os.system("pip install pylint")`

I ran each one as they failed but the structure seemed to be broken.

I did try where these commands were called from to modify but to no avail.  thanks for any assistance you can offer including work-arounds.

**Comment by EricJizbaMSFT** [comment]
Yeah the `http.proxy` setting doesn't work for our extension. Can you try using the `http.proxySupport` setting instead? This was just released in VS Code a few weeks ago and is supposed to work for our extension. If you set it to "override" it should use whatever proxy settings you have in your system. Do you have `https_proxy` already set in your system?

**Comment by Bandit253** [comment]
Alas we have such a locked down desktop that the profile I have to use to run VS Code is unable to traverse  the proxy.  So I would suspect that he Override setting would fail, but here I'll go and try

**Comment by Bandit253** [comment]
Yep as I suspected no good

**Comment by EricJizbaMSFT** [comment]
Hey @Bandit253 I'm not sure if we can do anything here. Like I mentioned above, we try to let VS Code handle all the proxy stuff for us and it's always possible this is unique to your desktop. Closing as won't-fix for now
