### ISSUE TITLE
Add the specific path of destination file after downloading the remote settings

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#871]
**OS:** All
**Node.js:** V10.13.0
**Build Number:** [20181218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1615)

**Repro Steps:**
1. Create one function app then expand it.
2. Right click the 'Application Settings' then select 'Download Remote Settings...'.
3. Check the log message after downloading successfully.

**Expect:**
Show the path of destination file on the log message.

**Actual:**
There is no path of the destination file on the log message.
![destination](https://user-images.githubusercontent.com/34729022/50141808-6b261380-02e3-11e9-96b2-a9ece66411a5.png)

**Comment by EricJizbaMSFT** [comment]
The user will see a notification to open the file as a part of https://github.com/Microsoft/vscode-azurefunctions/pull/908. We think that's enough
