### ISSUE TITLE
There misses three activities after creating a C# project with func cli  

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#872]
**OS:** All
**Node.js:** V10.13.0
**Build Number:** [20181218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1615)

**Repro Steps:**
1. Create a JavaScript project with the following command '**_func init --worker-runtime node_**' -> Check the log message.
2. Create a C# project with the command '**_func init --worker-runtime dotnet'_** -> Check the log message.
3. Compare these two generated log messages.

**Expect:**
The generated log messages are consistent.

**Actual:**
1. The generated log messages are inconsistent.
2. There message misses 3 activities for the created C# project.
![logmessage](https://user-images.githubusercontent.com/34729022/50142944-454e3e00-02e6-11e9-97aa-5420d4dadf43.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh we don't own the func cli. You can file an issue on their repo here if you so desire: https://github.com/Azure/azure-functions-core-tools
