### ISSUE TITLE
Failed to find "maven", please ensure that the maven bin directory is in your system path.

### ISSUE THREAD

**Issue by RebelSyntax** [Microsoft/vscode-azurefunctions#877]
C:\Windows\system32>mvn -v
Apache Maven 3.6.0 (...97c98ec64a1fdfee7767ce5ffb209...; 2018-10-24T14:41:47-04:00)
Maven home: C:\Program Files\Java\apache-maven-3.6.0\bin\..
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_192\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Trying to follow this -> https://code.visualstudio.com/docs/java/java-azurefunctions

Any other information I may provide?  I am going to try different version of "maven" perhaps.  Not sure what to try here since my java and/or maven experience is weak.  Thanks for any feedback!  I'll report back my results with different "maven" versions.

**Comment by jdneo** [comment]
@RebelSyntax 

Will you still see these error message if you close all your VS Code windows and restart it? (Just want to make sure the environment variables get refreshed)
