### ISSUE TITLE
Configuration type must be set to "None" to connect to a GitHub repository.

### ISSUE THREAD

**Issue by AymenMarzouk** [Microsoft/vscode-azurefunctions#879]
Action: azureFunctions.connectToGitHub
Error type: Error
Error Message: Configuration type must be set to "None" to connect to a GitHub repository.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Similar to https://github.com/Microsoft/vscode-azureappservice/issues/761
