### ISSUE TITLE
The dialog doesn't prompt after opening a python project created  by func cli

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#880]
**OS:** MacOS
**Node.js:** v8.11.3
**Build Number:** [20181221.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1671&view=results)

**Repro Steps:**
1.  Open VS Code.
2. Create a project from func cli -> Open the created project in VS Code.
3. Check whether there prompts a dialog or not. 

**Expect:**
Prompt a dialog.
![image](https://user-images.githubusercontent.com/41351993/50418949-2a8d4380-0869-11e9-91ac-0d66ba300416.png)

**Actual:**
No dialog prompts.

**Comment by EricJizbaMSFT** [comment]
I can't repro this. Can you give more information? Try it again? Maybe post screenshots of your workspace folder

**Comment by v-xianya** [comment]
Verified on build [20190112.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2053&view=results). 
1. This issue doesn't reproduce for C# and JavaScript project.
2. This issue reproduces for python project.

**Comment by EricJizbaMSFT** [comment]
I still can't repro for python. This is what I've done:
```
Erics-MacBook-Pro:pycli2 ericjizba$ python -m venv func_env
Erics-MacBook-Pro:pycli2 ericjizba$ . func_env/bin/activate
(func_env) Erics-MacBook-Pro:pycli2 ericjizba$ func --version
2.3.199
(func_env) Erics-MacBook-Pro:pycli2 ericjizba$ func init --worker-runtime python
Installing wheel package
Installing azure-functions==1.0.0a5 package
Installing azure-functions-worker==1.0.0a6 package
Running pip freeze
Writing .funcignore
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing /Users/ericjizba/TestRepos/pycli2/.vscode/extensions.json
(func_env) Erics-MacBook-Pro:pycli2 ericjizba$ func new --template HttpTrigger --name HttpTrigger1
Select a template: HttpTrigger
Function name: [HttpTrigger] Writing /Users/ericjizba/TestRepos/pycli2/HttpTrigger1/sample.dat
Writing /Users/ericjizba/TestRepos/pycli2/HttpTrigger1/__init__.py
Writing /Users/ericjizba/TestRepos/pycli2/HttpTrigger1/function.json
The function "HttpTrigger1" was created successfully from the "HttpTrigger" template.
```

And this is what my folder looks like when I open it in VS Code:
![screen shot 2019-01-17 at 9 56 02 am](https://user-images.githubusercontent.com/11282622/51338261-37ebb700-1a3e-11e9-89eb-77de1620d9c5.png)

Can you post similar logs and screenshot?

**Comment by v-xianya** [comment]
Thanks for your updates. Please get details from the below:

1. This is what I've done:
![image](https://user-images.githubusercontent.com/41351993/51366259-989ef080-1b1f-11e9-86f3-292a42ab3858.png)

2. This is what my folder looks like when I open it in VS Code:
![image](https://user-images.githubusercontent.com/41351993/51366268-a3f21c00-1b1f-11e9-9f8a-3b491eb54da1.png)

3. This is what my folder looks like when I open it in VS Code and run the command: "**Azure Functions: Initialize Project for Use with VS Code**“.
![image](https://user-images.githubusercontent.com/41351993/51366276-abb1c080-1b1f-11e9-9912-1641b0e16ae0.png)

**Comment by EricJizbaMSFT** [comment]
Ah - do you see how your folder structure is different than mine? Your "HttpTrigger" is inside "func_env/bin" and mine isn't.

This works:
```
python -m venv func_env
source func_env/bin/activate
func init --worker-runtime python
```

This doesn't work:
```
python -m venv func_env
cd func_env
cd bin
source activate
func init --worker-runtime python
```

If you want to cd, you have to cd back to the old root folder:
```
python -m venv func_env
cd func_env
cd bin
source activate
cd ..
cd ..
func init --worker-runtime python
```

I added this comment to the test case in OneNote - feel free to modify that comment to make it more clear if you want:
```
NOTE: If you did `cd func_env/bin/` to run the activate script, make sure to `cd ../..` back to the original root directly
```

Re-open if you're still having problems after that.
