### ISSUE TITLE
Fail to debug a python project created by func cli

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#881]
**OS:** MacOS
**Node.js:** v8.11.3
**Build Number:** [20181221.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1671&view=results)

**Repro Steps:**
1. Open VS Code.
2. Create a project from func cli -> Open the created project in VS Code.
3. F1 -> Type and select 'Azure Functions: Initialize Project for Use with VS Code...'.
4. Debug -> Check the result.

**Expect:**
Debug successfully.

**Actual:**
Fail to debug and prompt a dialog.
![image](https://user-images.githubusercontent.com/41351993/50419080-e189bf00-0869-11e9-9946-b329c75d0ab5.png)

**More Info:**
Show an error **Could not open requirements file:[Errno 2] No such file or directory:'requirement'** in TERMINAL but actually the file locates in "<Pythonprojectname>\func_env\bin".

**Comment by EricJizbaMSFT** [comment]
Closing this issue as I believe it is the same problem as https://github.com/Microsoft/vscode-azurefunctions/issues/880#issuecomment-455625845

The file structure has to be correct when creating a Python function app project in order for this feature to work from VS Code
