### ISSUE TITLE
when will Azure Function be supported in Korea region ?

### ISSUE THREAD

**Issue by ggthename** [Microsoft/vscode-azurefunctions#883]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Requested features are not supported in region.

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
I don't know that information - I would recommend following the generic Azure Functions support guidelines as outlined here: https://github.com/Azure/Azure-Functions#questions--help

Those folks work more directly on Functions in Azure as opposed to just the extension in VS Code and may be able to help
