### ISSUE TITLE
Initializing python functions insists on exactly Python 3.6

### ISSUE THREAD

**Issue by gergzk** [Microsoft/vscode-azurefunctions#884]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
Machine with Python 3.7.1 and VSCode installed
Follow steps to create a Python functions app and a first function
When VSCode asks if I'd like to init a project, say yes.

This is the console output, why can't I use a newer Python?:
**Error: Failed to run ".env\Scripts\activate && func init ./ --worker-runtime python" command. Check output window for more details.
Running command: ".env\Scripts\activate && func init ./ --worker-runtime python "...
Python 3.6 is required. Current python version is 'Python 3.7.1**

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run ".env\Scripts\activate && func init ./ --worker-runtime python" command. Check output window for more details.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@gergzk This is a limitation of the func cli. It looks like they have an issue here tracking the work to support 3.7: https://github.com/Azure/azure-functions-core-tools/issues/872 Feel free to upvote or add a comment to that issue. I will go ahead and close this as external.
