### ISSUE TITLE
Error deploying Python Functions from VS Code

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#893]
![image](https://user-images.githubusercontent.com/8435148/50793502-4b986000-127d-11e9-932a-6eac33797fdb.png)

Repro steps:
- I followed the basic workflow to create a Python project and create a function from Http template. 
- Clicked on Publish and picked the 'Create new Function app option'. 

Action: azureFunctions.deploy
Error type: Error
Error Message: Python projects are not supported on Windows Function apps.  Deploy to a Linux Consumption app.

Version: 0.13.1
OS: darwin

**Comment by v-dantch** [comment]
This might help you: https://github.com/Microsoft/vscode-azurefunctions/issues/798

**Comment by EricJizbaMSFT** [comment]
I've run into this occasionally. It seems like there's a small period of time right after it's created where the info returned to us from Azure indicates it's a Windows app. @asavaritayal does this happen consistently for you? If so - does it work if you wait a minute, refresh the tree view, and deploy again?

**Comment by EricJizbaMSFT** [comment]
Could be fixed when we do https://github.com/Microsoft/vscode-azurefunctions/issues/906

**Comment by FlippieCoetser** [comment]
Workaround, using cli: func azure functionapp publish <FuncAppName>

**Comment by EricJizbaMSFT** [comment]
@FlippieCoetser we currently don't support deploying python to dedicated app service plans in VS Code. That is being tracked by https://github.com/Microsoft/vscode-azurefunctions/issues/906 and should be included in the next release
