### ISSUE TITLE
Error  "No process with the specified id is currently running." when trying to debug on macOS

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#894]
I am getting the same error  "No process with the specified id is currently running." when trying to debug on macOS (i.e. when pressing F5, not when restarting debugger).

The steps I take are:
1. Create an empty folder, open it in VS Code.
2. Command: "Azure Functions: Create new project" (C#)
3. Command: "Azure Functions: Create Function" (C#, HttpTrigger).

I don't get this error right away, the first time nothing really happens. But if I reload the VS Code window, then I consistently get this error when trying to debug (F5). The function host is started, and the function is callable. But debugger does not attach. It almost seems like the attach process times out before the function host is finished starting.

The same does not occur if I follow the same steps as above, and select JavaScript instead of C#.

Unclear if this is related to this issue, can open a new issue if needed.

macOS: 10.14.2
VS Code: 1.30.1
Azure Functions extension: 0.13.1
`dotnet --version`: 2.1.500
Azure Functions Core Tools: 2.3.199
Function Runtime Version: 2.0.12246.0

_Originally posted by @cbrevik in https://github.com/Microsoft/vscode-azurefunctions/issues/756#issuecomment-451726776_

**Comment by EricJizbaMSFT** [comment]
@cbrevik how did you install the func cli? `brew`, `npm`, or some other method? When you look at your project, does it have this structure?
![screen shot 2019-01-07 at 3 48 05 pm](https://user-images.githubusercontent.com/11282622/50800128-c53b4880-1293-11e9-9547-d4e185fe4b22.png)

Also you can follow these steps as a workaround or to give me more info:
1. In `.vscode/launch.json` change `"${command:azureFunctions.pickProcess}"` to `"${command:pickProcess}"`
1. Open Command Palette (View -> Command Palette)
1. Select "Run Task"
1. Select "runFunctionsHost"
1. F5

At that point - you should see a lit of processes. I'm curious if anything with 'func' shows up? Mine looks like this:
![screen shot 2019-01-07 at 3 51 51 pm](https://user-images.githubusercontent.com/11282622/50800223-2d8a2a00-1294-11e9-9cb3-83dab27a7114.png)
Selecting the right process should attach the debugger.

**Comment by cbrevik** [comment]
@EricJizbaMSFT installed with Homebrew, and same project structure.

This is the part where I feel sort of silly. I did the workaround, and was able to attach the debugger by picking the process manually. Then I changed `launch.json` back to `"${command:azureFunctions.pickProcess}"`.. and now it's working without having to pick the process manually.

I have no idea why I've experienced this behaviour, as it has been like this for a few days now. 

The only thing I can think of is that I've had some problems with other VS Code extensions and warnings/errors recently, which may have been causing the issues here, and may have updated? I am sorry for wasting your time, and you can close the issue. 😕

**Comment by EricJizbaMSFT** [comment]
Perhaps something changed on your machine. If you have multiple installs of the func cli or if you're even running `func host start` multiple times on the same machine you might see problems. In any case feel free to re-open if you start seeing problems again
