### ISSUE TITLE
Project doesn't run on python > 3.6

### ISSUE THREAD

**Issue by mohovkm** [Microsoft/vscode-azurefunctions#899]
Repro steps:
Install npm azure-ad-functions
Install extension for VS code
Reload VS code
Select "Create new project" -> Python
Type aliias fo Python 3.6: python3

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run ". .env/bin/activate && func init ./ --worker-runtime python" command. Check output window for more details.

Output: Running command: "python3 -m venv .env"...
Finished running command: "python3 -m venv .env".
Running command: ". .env/bin/activate && func init ./ --worker-runtime python "...
Python 3.6 is required. Current python version is 'Python 3.7.2

Version: 0.13.1
OS: MAC OS Mojave 10.14.2

**Comment by EricJizbaMSFT** [comment]
@mohovkm This is a limitation of the func cli. It looks like they have an issue here tracking the work to support 3.7: https://github.com/Azure/azure-functions-core-tools/issues/872 Feel free to upvote or add a comment to that issue. I will go ahead and close this as external.
