### ISSUE TITLE
v1 JS project uses v2 template 

### ISSUE THREAD

**Issue by JohnReeson** [Microsoft/vscode-azurefunctions#904]
host.json contains `"version": "2.0"` and local.settings.json contains `"FUNCTIONS_WORKER_RUNTIME": "node"` so I assume it consumes v2 template somehow.

![capture](https://user-images.githubusercontent.com/35160013/50958396-90c9c580-14fb-11e9-8f3a-aa36a8f5a857.JPG)

Extension Version: 0.13.1
CLI version 1.0.17
Node v6

**Comment by EricJizbaMSFT** [comment]
`FUNCTIONS_WORKER_RUNTIME` shouldn't hurt anything on v1 and could be helpful if people ever upgrade to v2. The host.json probably shouldn't say 2.0, though. 

If you create a new function - what runtime is listed?
![screen shot 2019-01-11 at 1 39 00 pm](https://user-images.githubusercontent.com/11282622/51060956-5e28d700-15a6-11e9-8e88-8658337e7029.png)

If it says "~1" then that means you're still getting the v1 templates.

**Comment by JohnReeson** [comment]
Thanks for the explanation, it's ~1 as expected. By template, I mean the project template i.e. `host.json` and `local.settings.json`.   `"version": "2.0"` is exactly what I am worrying about. Even though the v1 format configuration does work anyway, we can see the misleading prompt according to v2 schema. 

![12](https://user-images.githubusercontent.com/35160013/51069117-c8538180-1663-11e9-9fed-d90306cb899c.png)
