### ISSUE TITLE
There is a offset for the URL text-decoration when hovering over it on Mac

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#905]
OS: Mac
Node.js: V10.14.2
Func: V2.3.1999
Build Version: [20190108.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1893&view=results)

Repro Steps:
1. Create a project -> Create a function.
2. Debug the project.
3. Hover over the URL in 'OUTPUT' window and check the result.

Expect:
The URL decoration matches the URL.

Actual:
There is a offset for the URL decoration.
![image](https://user-images.githubusercontent.com/34729092/50960329-1a7b9200-1500-11e9-94cd-d57e938ee340.png)

**Comment by EricJizbaMSFT** [comment]
Filed an issue on VS Code: https://github.com/Microsoft/vscode/issues/66632

**Comment by EricJizbaMSFT** [comment]
Closing as this was fixed on VS Code insiders
