### ISSUE TITLE
Failed to deploy path that does not exist

### ISSUE THREAD

**Issue by MareArts** [Microsoft/vscode-azurefunctions#907]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/leon/DWF/Dev/azure/LeonTestAzureProj/LeonTestAzureProj.zip

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@MareArts did the `func pack` task succeed? That creates the zip and it's required for deploying a python project

**Comment by AlverezYari** [comment]
Also getting this after a botched deployment. Where does func pack store the var for where the .zip is stored? I think I just need to clear that out and re-run it from the correct location but I can't find it anywhere.

**Comment by AlverezYari** [comment]
Within your function root directory, open up .vscode/settings.json then look in workplace settings and clear our whatever you have set for **"azureFunctions.deploySubpath":**

**Comment by EricJizbaMSFT** [comment]
@AlverezYari are you also deploying a Python project? You can certainly customize the `azureFunctions.deploySubpath` setting to work for your project, but I'm not sure clearing it out will work for Python projects. Does your function app work after you deploy?

**Comment by EricJizbaMSFT** [comment]
So it's not quite the "already zipped version". The `deploySubpath` setting goes hand-in-hand with the `preDeployTask` setting (which should be set to `funcPack` by default). If specified, the `preDeployTask` will be run before every deploy and in this case `funcPack` creates the zip file. Here is my output from that task:
```
> Executing task: . .env/bin/activate && func pack <

Deleting the old package /Users/ericjizba/TestRepos/oldpy1/oldpy1.zip
Deleting the old .python_packages directory
pip download -r /Users/ericjizba/TestRepos/oldpy1/requirements.txt --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworkermxjw2uj_
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa setuptools==40.7.0
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa protobuf==3.6.1
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa azure_functions==1.0.0a5
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa grpcio_tools==1.14.2
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa azure_functions_worker==1.0.0a6
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa grpcio==1.14.2
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/kr/kdg_ggqn32zbqlv_5tj4kj880000gn/T/azureworker_4ipqjxa six==1.12.0

Creating a new package /Users/ericjizba/TestRepos/oldpy1/oldpy1.zip

Terminal will be reused by tasks, press any key to close it.
```

You'll notice its deleting the old zip and creating a new zip every single time (at least on my machine). Do you still have the `preDeployTask` setting? And do you see similar output? If you remove `deploySubPath`, it's zipping up your entire workspace as-is, which probably includes extra files that aren't needed and _may_ not include dependencies correctly depending on how complex your project is (I know `func pack` does stuff in the background related to dependencies, but not 100% clear on the details).

**Comment by AlverezYari** [comment]
Ah, well that is interesting, so just changed that var to the corrected location if you mess it up the first time? Do you know if you can enable git on that Python functions yet or do you have to keep the deployment running via this method at the moment.

**Comment by EricJizbaMSFT** [comment]
> so just changed that var to the corrected location if you mess it up the first time? 

Yes. Although if you give us more detailed repro steps, we might be able to improve that experience.

> Do you know if you can enable git on that Python functions yet

Not supported if you use a consumption plan (the default).  If you want more info on this you can reach out to the platform team based on this guidance: https://github.com/Azure/Azure-Functions#questions--help

I believe it _is_ supported if you select a dedicated app service plan when creating your function app, but that has other implications on pricing/performance and you'd have to create it in the portal. We're working on improving the "dedicated plan" experience here https://github.com/Microsoft/vscode-azurefunctions/issues/906 and here https://github.com/Microsoft/vscode-azurefunctions/issues/854

**Comment by AlverezYari** [comment]
@EricJizbaMSFT 

Thanks for the info, we are just dipping our toes in so far and just have some small stuff running through it. I appreciate the links and once I get some time I'll make some post over there with more details on what we are running into that might be consider confusing. 

Thanks!

**Comment by EricJizbaMSFT** [comment]
@MareArts closing this issue due to lack of response. Feel free to re-open with more info or try messing with the "azureFunctions.deploySubpath" or "azureFunctions.preDeployTask" settings as discussed above
