### ISSUE TITLE
Failed to detect running Functions host within "60" seconds

### ISSUE THREAD

**Issue by isimosanchez** [microsoft/vscode-azurefunctions#912]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@isimosanchez can you give repro steps and more information? For example
1. What version of the func cli do you have?
1. Did your project succeed in building?
1. When you started debugging, it should've opened the terminal and run `func host start`. Do you see any output and can you copy that here?
