### ISSUE TITLE
'Encountered an error (InternalServerError) from host runtime' on function publish

### ISSUE THREAD

**Issue by jochenvanwylick** [Microsoft/vscode-azurefunctions#914]
Repro steps:
1. I created an azure function `func init` - `func new` - eventhub trigger
2. No code changes - so here's the code:
```
module.exports = async function (context, eventHubMessages) {
    context.log(`JavaScript eventhub trigger function called for message array ${eventHubMessages}`);
    
    eventHubMessages.forEach((message, index) => {
        context.log(`Processed message ${message}`);
    });
};
```
3. bindings as follows:
```
{
  "disabled": false,
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "eventHubName": "insights-operational-logs",
      "connection": "SbConnectionString",
      "cardinality": "one",
      "consumerGroup": "$Default"
    }
  ]
}
```
4. Use VS code extension to publish - and get error below:

```
Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.13.1
OS: win32
```

And I found this in the logging window for Azure Functions:

```
9:16:31 PM jvw[removed]functionname: Creating zip package...
9:16:33 PM jvw[removed]functionname: Starting deployment...
9:16:34 PM jvw[removed]functionname: Uploading zip package to storage container...
9:16:39 PM jvw[removed]functionname: Syncing triggers...
Error: Encountered an error (InternalServerError) from host runtime.
9:23:43 PM jvw[removed]functionname: Creating zip package...
9:23:45 PM jvw[removed]functionname: Starting deployment...
9:23:46 PM jvw[removed]functionname: Uploading zip package to storage container...
9:23:53 PM jvw[removed]functionname: Syncing triggers...
Error: Encountered an error (InternalServerError) from host runtime.
```

**Comment by EricJizbaMSFT** [comment]
@jochenvanwylick if you deploy, wait maybe 5 or 10 minutes, and then try to view functions for that function app (either in the VS Code Functions explorer or in the portal) - does that function show up? There's some known performance issues with linux consumption and it's possible the deployment succeeded and it's just taking too long for us to sync the triggers right away

**Comment by EricJizbaMSFT** [comment]
@jochenvanwylick it turns out there is a bug in the functions runtime. As a workaround you can delete the proxies.json file in your project (assuming you don't have any proxies). See https://github.com/Azure/azure-functions-host/issues/3978 for more info

We're doing more improvements in this area in our extension as well. Mainly this: https://github.com/Microsoft/vscode-azuretools/pull/372

Closing since this is tracked in a few other places.
