### ISSUE TITLE
How to use the `MultipartHttpServletRequest` class from the default `run()` method?

### ISSUE THREAD

**Issue by babychaos** [Microsoft/vscode-azurefunctions#916]
```
    public HttpResponseMessage run(
            @HttpTrigger(name = "req", methods = {HttpMethod.GET, HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
```

There's only `HttpRequestMessage` parameter on the `run()` method.
I need to declare and use `MultipartHttpServletRequest` to fetch a file from the multipart/data request.

Please give me some advice.

**Comment by EricJizbaMSFT** [comment]
Hi @babychaos not sure if you've figured out your problem already, but I would suggest following the guidance here to get a better/faster response: https://github.com/Azure/Azure-Functions#questions--help Specifically it sounds like the MSDN forum or stackoverflow might be a better place for this question. The functions platform team (as opposed to the VS Code extension) has more expertise in this area.
