### ISSUE TITLE
Creating function from VS code is throwing error

### ISSUE THREAD

**Issue by abhinavbom** [Microsoft/vscode-azurefunctions#919]
Repro steps:
Create new function > Select Language > Python 

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run ". .env/bin/activate && func init ./ --worker-runtime python" command. Check output window for more details.

Version: 0.13.1
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@abhinavbom please copy the logs from the output window here

**Comment by abhinavbom** [comment]
Thanks for the response. The issue was with python wheels. I had to reinstall it and it worked. Closing it for now.
