### ISSUE TITLE
Deploy Issue

### ISSUE THREAD

**Issue by BSJAIN92** [Microsoft/vscode-azurefunctions#920]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: ESOCKETTIMEDOUT
Error Message: ESOCKETTIMEDOUT

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/890
