### ISSUE TITLE
cannot build  (\microsoft.net.sdk.functions\1.0.24\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : It was not possible to find any compatible framework version)

### ISSUE THREAD

**Issue by jayanath007** [Microsoft/vscode-azurefunctions#922]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@jayanath007 can you copy the full output of the build task?
