### ISSUE TITLE
Display 'Function host is not running' after deploying JavaScript projects

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#926]
**OS:** Windows/ Mac
**Node.js:** V10.14.0
**Build Version:** [20190122.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2313)
**Azure Functions Core Tools:** V2.4.290

**Repro Steps:**
1. Create a JavaScript project.
2. Create a new function with 'HTTP trigger' template and 'Function' level.
3. Deploy this JavaScript project to Azure Function app.
4. Copy the Function URL to terminal and check the result.

**Expect:**
Succeed to run the command.

**Actual:**
Display 'Function host is not running'.
![image](https://user-images.githubusercontent.com/34729092/51588528-5cf68480-1e99-11e9-9bc6-4fbacdd6dc6c.png)

**More Info:**
This issue doesn't reproduce for C#  project.
![image](https://user-images.githubusercontent.com/34729092/51588602-916a4080-1e99-11e9-95e2-f402e466b03c.png)

**Comment by EricJizbaMSFT** [comment]
Similar to https://github.com/Microsoft/vscode-azurefunctions/issues/1022#issuecomment-468060484 and https://github.com/Microsoft/vscode-azurefunctions/issues/952#issuecomment-468062410

If this still repros, please let me know what OS you were deploying to. If you were deploying to Windows, you can try streaming logs to get more info
