### ISSUE TITLE
Project.assets.json cannot be found. Please do a dotnet restore

### ISSUE THREAD

**Issue by jjgriff93** [Microsoft/vscode-azurefunctions#927]
I've created a functions app and function within VSCode, and am getting this error whenever trying to debug ad stock cosmos db trigger app. Running a `dotnet restore` does nothing

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "build" failed with exit code "1".

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@jjgriff93 I can't repro this. A few questions:
1. Does this still happen for you?
1. What version of dotnet do you have?
1. Can you copy the full output of the build task?
1. This was a brand new project, right? If not - is the project open source on Github so that I could take a look?

**Comment by jjgriff93** [comment]
Hi Eric, I believe it was a problem in the csproj file when copying between projects. I created a new function app from scratch which resolved the issue
