### ISSUE TITLE
Missing value for AzureWebJobsStorage in local.settings.json

### ISSUE THREAD

**Issue by dev4678** [Microsoft/vscode-azurefunctions#928]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Get "Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than HTTP. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json." in local.settings.json.&gt;

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@dev4678 see here for more info on local.settings.json and AzureWebJobsStorage: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file

That value is required to run locally. You can either set it to a storage account connection string or `UseDevelopmentStorage=true` if you have the storage emulator installed and running on your machine.
