### ISSUE TITLE
Adding new function to Java project doesn't respond

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#930]
Issue Type: <b>Bug</b>

When I click to add a new function in a Java project I created on Mac either via Maven or via VS Code when I click "add function" nothing happens.

Extension version: 0.13.1
VS Code version: Code - Insiders 1.31.0-insider (2d79ffe0cd84515a4c771fcbd7294c2448d97826, 2019-01-23T06:13:04.232Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_1712546|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by EricJizbaMSFT** [comment]
"nothing happens" could just be performance issues, which I've definitely seen with maven in the past https://github.com/Microsoft/vscode-azurefunctions/issues/100

**Comment by jdneo** [comment]
This issue has been resolved., though it will take a few seconds for waiting for the `mvn` command to tell the extension of all the supported templates and their metadata. Adding a progress bar might be better here.

![demo](https://user-images.githubusercontent.com/6193897/53773107-ffd40100-3f23-11e9-985a-afc79917a25c.gif)
