### ISSUE TITLE
Azure function post error from vs code

### ISSUE THREAD

**Issue by HarshitShukla** [Microsoft/vscode-azurefunctions#931]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: Encountered an error (Forbidden) from extensions API.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@HarshitShukla can you give more info?
1. What project language are you using?
1. Does this happen consistently?
1. Is this a new function app or existing one?

**Comment by HarshitShukla** [comment]
I found the bug and fixed.
