### ISSUE TITLE
Error message for not having Maven installed not user friendly

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#94]
If Maven is not installed when attempting to create a Java Project, the error message looks like this

![image](https://user-images.githubusercontent.com/5290572/33404757-6046748e-d51a-11e7-8fad-f65cb4b143c8.png)

We should make the message more user-legible.

**Comment by EricJizbaMSFT** [comment]
@jdneo I put this in 0.3.0 in case you have time to fix it - but not a big deal if we have to punt it to the next release

**Comment by EricJizbaMSFT** [comment]
In the interest of locking down for the release, I'm moving this to 0.4.0
