### ISSUE TITLE
Error while creating function from VS Code - Azure Function Extention  

### ISSUE THREAD

**Issue by abhishekmishragithub** [Microsoft/vscode-azurefunctions#942]
![error_vscode_python](https://user-images.githubusercontent.com/38150419/52027359-2a9bf580-2531-11e9-8aad-a06ffc7824d1.JPG)

Repro steps:

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run "py -3.6" command. Check output window for more details.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@abhishekmishragithub does that command work if you run it manually in a command prompt or powershell window? `py -3.6 -m venv .env`

**Comment by abhishekmishragithub** [comment]
@EricJizbaMSFT it seems my environment is making issue, because same command (`py -3.6 -m venv .env`) is not working locally as well. so installed "virtualenv" module and created virtual env manually rather than going through mentioned command.  i am closing the issue.
Thanks !!
