### ISSUE TITLE
"Extensions command requires dotnet on your path.  Please make sure to install dotnet (.NET Core SDK) for your system from https:...

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azurefunctions#948]
![image](https://user-images.githubusercontent.com/5290572/52095349-796c7e00-2577-11e9-87dc-fff98e724a80.png)

Just kidding.  The bug is that it keeps deploying anyway.  Should we deploy on failure?

**Comment by EricJizbaMSFT** [comment]
ping @nturinski would like an answer on this so that I know if it's a regression before we release
