### ISSUE TITLE
Fail to deploy Python project on Linux

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#953]
**OS:** Linux
**Node.js:** V 10.15.0
**Build Version**:[20190201.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2674)

**Repro Steps:**
1. Create a Python project with HTTP trigger template.
2. Debug --> Deploy.
3. Check the result.

**Expect:**
Succeed to deploy Python project.

**Actual:**
Fail to deploy Python project with error 'Pre-deploy task "pack" failed with exit code "1"'.
![image](https://user-images.githubusercontent.com/34729092/52162289-60062780-2686-11e9-8974-30bcca3ede73.png)
![image](https://user-images.githubusercontent.com/34729092/52162290-64324500-2686-11e9-894d-73d8d7be554e.png)

**More Info:**
This issue only reproduces on Linux.

**Comment by EricJizbaMSFT** [comment]
@v-dantch if this still repros, can you copy the output of running `pip install -r requirements.txt` and `func pack` manually in the terminal. This could be a problem with python or pip on your machine
