### ISSUE TITLE
Debugger can't attach to Python project

### ISSUE THREAD

**Issue by hongyiqin** [Microsoft/vscode-azurefunctions#960]
Python Extention: 2019.1.0
Azure Functions: 0.13.1
CLI: 2.4.317

I just created a new azure function project (HttpTrigger) and then tried to debug it, I then got the error _Failed to attach (connect ECONNREFUSED 127.0.0.1:9091)_ 

From what I've gathered so far, it seems to indicate that python debugger tried to attach before function host had fully started. I've tried various suggested tweaks in launch.json and tasks.json but none have worked for me.

launch.json
``` 
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9091,
      "host": "localhost",
      "preLaunchTask": "runFunctionsHost"
    }
  ]
} 
```

tasks.json
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "runFunctionsHost",
      "type": "shell",
      "osx": {
        "command": ". ${config:azureFunctions.pythonVenv}\\bin\\activate && func extensions install && pip install -r requirements.txt && func host start"
      },
      "windows": {
        "command": "${config:azureFunctions.pythonVenv}\\Scripts\\activate ; func extensions install ; pip install -r requirements.txt ; func host start"
      },
      "linux": {
        "command": ". ${config:azureFunctions.pythonVenv}\\bin\\activate && func extensions install && pip install -r requirements.txt && func host start"
      },
      "isBackground": true,
       "options": {
        "env": {
          "languageWorkers__python__arguments": "-m ptvsd --host 127.0.0.1 --port 9091"
        }
      }, 
       "problemMatcher": "$func-watch"
    },
    {
      "label": "funcPack",
      "type": "shell",
      "osx": {
        "command": ". ${config:azureFunctions.pythonVenv}\\bin\\activate && func pack"
      },
      "windows": {
        "command": "${config:azureFunctions.pythonVenv}\\Scripts\\activate ; func pack"
      },
      "linux": {
        "command": ". ${config:azureFunctions.pythonVenv}\\bin\\activate && func pack"
      },
      "isBackground": true
    }
  ]
}
```

Terminal printed out the message below before the error window popped up 

> Executing task: .env\Scripts\activate ; func extensions install ; pip install -r requirements.txt ; func host start 
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by EricJizbaMSFT** [comment]
@hongyiqin please see this comment and let me know if it helps your situation: https://github.com/Microsoft/vscode-azurefunctions/issues/892#issuecomment-459054366

**Comment by hongyiqin** [comment]
@EricJizbaMSFT  Thanks! Changing the separator from ; to && works!

Changing the terminal to Powershell doesn't work for python, the command to activate virtual env fails in powershell.
