### ISSUE TITLE
ENOTFOUND error while deploying the app 

### ISSUE THREAD

**Issue by kavithamadhavaraj** [Microsoft/vscode-azurefunctions#961]
Repro steps:
Use VSCODE extension to deploy the app. Constantly getting this error message. But earlier today I was able to deploy.

I had associated a Blob Storage account to the function app instead of the required General Purpose Storage account. Linking to the later one also didn't solve the issue.

Action: azureFunctions.deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND myapp.blob.core.windows.net myapp.blob.core.windows.net:443

Version: 0.13.1
OS: linux
Trigger: EventGridTrigger

**Comment by EricJizbaMSFT** [comment]
@kavithamadhavaraj can you give more detailed steps on how to reproduce this error? How exactly did you create the function app? What language and triggers are you using? And how did you change the storage account link?

**Comment by kavithamadhavaraj** [comment]
@EricJizbaMSFT Apparently, this error went off. I created my app through VS Code with Python under Linux Consumption plan using EventGrid Trigger. Linking is done via "AzureWebJobsStorage" configuration of the function app. I think we can close this issue for now since I'm not able to reproduce it. Thanks.
