### ISSUE TITLE
Issue deploying to Azure GCC

### ISSUE THREAD

**Issue by awaldow** [Microsoft/vscode-azurefunctions#962]
I have used this extension to create a new Function App that will eventually live in our Azure GCC tenant. When attempting to deploy a net new Function App, I get the following notification from this extension:

> There was a conflict. The remote name could not be resolved: 'XXXXX.file.core.windows.net'

Now, I know well enough what the error is telling me; it can't resolve the host name. However, as far as I can tell the GCC naming convention is different for File Storage, along the lines of https://XXXXXX.file.core.usgovcloudapi.net. As there seems to be no way for me to inform the extension of what Azure environment I'm using outside of selecting "azure.cloud": "AzureUSGovernment" in the settings I'm at a loss of how to resolve this. I tried looking through the source to see where that URL is being generated but either I missed it or it's happening in some associated package.

Any help would be appreciated, thanks.

**Comment by EricJizbaMSFT** [comment]
@awaldow So this was only while deploying, not creating? What language is your project?

All you need to do is set the "azure.cloud" setting. There's probably a bug in our extension

**Comment by awaldow** [comment]
I have the function app set up as Javascript with a Service Bus Trigger. I said 'deploying' but this is net new so it'd be creating the resources it was missing on the Azure side were it not for this issue. I am using a preexisting resource group and storage account, both within our GCC tenant.

**Comment by awaldow** [comment]
Just to test I deleted our previously-created storage account (I had previously made a portal-driven function app, and was using the same storage account) and tried creating again from VS Code. Same issue.

**Comment by EricJizbaMSFT** [comment]
Again this is probably a bug in our extension that we will get fixed. But in the meantime you might try editing the application settings of your function app after you create it. Specifically:

1. look for any application setting that have a storage account connection string. (At least check `AzureWebJobsStorage` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`)
1. Find that storage account in the portal
1. Get the full connection string (Under the "Access Keys" section)
1. Replace the old application setting value with that new connection string.

I'm guessing the connection string from the portal will have something like `EndpointSuffix=core.windows.net` whereas the original application setting value did not.

**Comment by awaldow** [comment]
I think I will just have to create the function app via the portal for now and re-create it using this extension when whatever problem is occurring is fixed. As it stands, creating a net-new function app with a net-new storage account will see the storage account created but the function app itself, nor the app service plan or anything else in that workflow get completed.

**Comment by EricJizbaMSFT** [comment]
Oh I thought the portal wasn't working for you. If you have a workaround then yes that sounds good until we get this fixed
