### ISSUE TITLE
Unable to publish Python Azure Function from VS Code

### ISSUE THREAD

**Issue by VijayaMalla** [Microsoft/vscode-azurefunctions#963]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\.......\Desktop\Azure Python Function\Azure Python Function.zip

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@VijayaMalla I believe this may be a dupilcate of another bug we've been seeing. You can try the workarounds listed here: https://github.com/Microsoft/vscode-azurefunctions/issues/892#issuecomment-459054366

We've fixed on master already and plan to release soon, but you're welcome to try earlier:
How to install: https://aka.ms/azCodeInsiders
Build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2905

NOTE: This relies on VS Code v1.31.0 just released yesterday

If you're still having problems, please copy the full output of the "func pack" task here

**Comment by VijayaMalla** [comment]
@EricJizbaMSFT I am going to give another try and let you know, Thank You for your help
