### ISSUE TITLE
Can't deploy function from VSCode

### ISSUE THREAD

**Issue by somacdivad** [Microsoft/vscode-azurefunctions#972]
Trying to deploy function app from VSCode. The function app is written in Python on Linux consumption plan. Deploy worked fine a day ago, but not anymore. Looking at https://azure.microsoft.com/en-us/status/ shows Linux App Service operating normally, although I'm not 100% sure that's related.

Repro steps:
Deploy Python function app to Azure from VSCode on Linux consumption plan.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.13.1
OS: win32

**Comment by somacdivad** [comment]
Also, it would be nice if the service is unavailable to stop the deploy before it deletes the remote package so that the app doesn't go down. Is there a way to check availability before trying to deploy?

**Comment by somacdivad** [comment]
Works now. I'm guessing this is a temporary service outage due to Linux consumption plans being in "preview."

**Comment by EricJizbaMSFT** [comment]
Thanks for verifying @somacdivad. It could just be an outage, but we also made improvements in this area which should be released soon. For example, sometimes you'll get ServiceUnavailable when syncing triggers immediately after a deploy, but a few seconds later it'll work. That's why we added logic to retry a few times: https://github.com/Microsoft/vscode-azuretools/pull/372

**Comment by somacdivad** [comment]
@EricJizbaMSFT Thanks for the info. I'll keep an eye out for the update. Keep up the good work 😃

**Comment by EricJizbaMSFT** [comment]
No problem. You're welcome to try the latest insiders build as well if you want:
How to install: https://aka.ms/azCodeInsiders
Build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2905

NOTE: This relies on VS Code v1.31.0 just released yesterday
