### ISSUE TITLE
Deploying Python function twice returns "Forbidden"

### ISSUE THREAD

**Issue by psmaAaron** [Microsoft/vscode-azurefunctions#989]
Repro steps:
* open VS Code
* Deploy to Function App
* Edit code
* Deploy to Function App (again)

Action: azureFunctions.deploy
Error type: Forbidden
Error Message: Forbidden

Version: 0.14.0
OS: win32

I've had this happen regularly, across two projects. Both projects are Python-based and therefore are on Linux preview.
Most of the time restarting VS Code fixes it.

**Comment by psmaAaron** [comment]
Seems to happen on the `Uploading zip package to storage container...` step.

**Comment by EricJizbaMSFT** [comment]
@psmaAaron I'm having a hard time reproducing this. 

1. Do you have full permissions to the storage account associated with the function app?
1. Is this a large project?
1. Can you try deploying through the func cli? That might help us narrow down if this is a VS Code issue or a problem with the Azure Functions platform: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux#deploy-the-function-app-project-to-azure

**Comment by danielesiddi** [comment]
same here on mac/darwin

**Comment by ronendayan** [comment]
same here,
creating new works,
after editing getting forbidden.
Uploading from CLI seems to not change the code on the function app

**Comment by EricJizbaMSFT** [comment]
Can someone copy the full logs of deploying here? @psmaAaron mentioned it was happening after "Uploading to storage" and I just want to make sure that's the case. I'm also curious about the timestamps and wondering if this is taking a long time to upload for some reason.

Also how did you create this function app? Was it through VS Code or through the portal?
