### ISSUE TITLE
Deploying fails if user has defined a task to run both TS compiler and functions host

### ISSUE THREAD

**Issue by ilkka** [Microsoft/vscode-azurefunctions#990]
I'm writing my Azure Functions in TypeScript and I had defined a shorthand task in VS code for starting the compiler in watch mode and running the functions host. This caused deployment to fail with the message `cannot read property 'value' of undefined`. The reason seems to be that when the extension runs `func extensions install` during the deploy, it somehow ends up looking at my "Start compiler and functions host" task and tries to dereference its `command.name.value`, while `command.name` is undefined.

Here is the problematic tasks.json:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "runFunctionsHost",
      "type": "shell",
      "command": "func host start",
      "isBackground": true,
      "problemMatcher": "$func-watch",
      "options": {
        "env": {
          "languageWorkers__node__arguments": "--inspect=5858"
        }
      },
      "dependsOn": "installExtensions"
    },
    {
      "label": "installExtensions",
      "command": "func extensions install",
      "type": "shell"
    },
    {
      "label": "tsc-watch",
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "problemMatcher": ["$tsc-watch"],
      "isBackground": true,
      "group": "build"
    },
    {
      "label": "Start compiler and functions host",
      "type": "process",
      "dependsOn": ["tsc-watch", "runFunctionsHost"],
      "group": "build",
      "isBackground": true
    }
  ]
}
```

When breaking at the actual exception, the stack looks like it's only within VS code, so it's quite feasible that this is a VS code bug, in that either a) that tasks.json is invalid and should be marked as such in the editor, which it is not, or b) the task handling code should take this edge case (?) into account. Any insight on your part as experienced extension developers would be greatly appreciated, and I can then take this problem elsewhere if the root indeed is somewhere else :)

Repro steps:
1. Create an Azure Functions project
2. Replace `.vscode/tasks.json` with the above
3. Start a deploy from VS code

Action: azureFunctions.deploy
Error type: Error
Error Message: Cannot read property 'value' of undefined

Version: 0.13.1
OS: win32

**Comment by ilkka** [comment]
In the great tradition of discovering workarounds immediately upon taking the time to specify a problem, changing the "Start compiler and functions host" task to be a "shell" type task with `"command": "echo"` handily solves this problem, and indeed "command" is non-optional in [the schema](https://code.visualstudio.com/docs/editor/tasks-appendix). So, it would appear that the root cause is not flagging the tasks file as invalid. Still, it is curious that it does what it is supposed to in its incorrect form, all the way until the point when I try to deploy, and only fails then.

**Comment by EricJizbaMSFT** [comment]
Thanks for filing and glad you got a workaround. We're calling one of VS Code's api's to fetch tasks so that we can run the task specified by the setting `azureFunctions.preDeployTask` before you deploy. That api is throwing the error and that is why it happens you you deploy

Filed an issue on VS Code: https://github.com/Microsoft/vscode/issues/68550

**Comment by EricJizbaMSFT** [comment]
I verified on the latest insiders version of VS Code that this now shows a validation error in tasks.json. Closing as fixed
