### ISSUE TITLE
Prompt to install Linter pylint

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#995]
**OS**: Mac
**Node.js:** v10.15.1
**Func:** v2.4.317
**Regression**: Pervious Release

**Repro Steps:**
1. Create a python project.
2. Create a function with Http trigger template and Function level.

**Expect:**
Add pylint to Python projects by default.

**Actual:**
Prompt to install Linter pylint.
![image](https://user-images.githubusercontent.com/34729092/52846721-35bd5c80-30bf-11e9-801a-2c91bf6beb28.png)

**Comment by EricJizbaMSFT** [comment]
This is by design - see https://github.com/Microsoft/vscode-azurefunctions/issues/814. The source of this error is from the Python extension and it's up to the user if they want to install pylint or not.
