### ISSUE TITLE
Display 'ServiceUnavaliable' after deploying a Python project to a function app with Linux OS

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#996]
**OS**: Mac
**Node.js:** v10.15.1
**Func:** v2.4.317
**Regression**: Not a Regression

**Repro Steps:**
1. Create a Python project with Http trigger template and Function level.
2. Install  Linter pylint --> Debug.
3. Deploy to a function app with Linux OS --> Check the URL.

**Expect:**
Succeed to deploy and get a valid URL.

**Actual:**
Display 'ServiceUnavaliable' after deploying.
![image](https://user-images.githubusercontent.com/34729092/52847260-8d0ffc80-30c0-11e9-8efc-a40353797258.png)

**Comment by EricJizbaMSFT** [comment]
@v-dantch I agree this is annoying, but ServiceUnavailable is a common error we get from the platform. Linux function apps are still in preview and I believe they're actively working on fixing this. There's nothing we can really do from VS Code

**Comment by v-dantch** [comment]
Hi @EricJizbaMSFT got it, thanks a lot for your share.
