### ISSUE TITLE
Can't set the name of a new Azure Function App in VS Code Extension

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azurefunctions#999]
![2019-02-15_15-54-27](https://user-images.githubusercontent.com/1202528/52883862-57a7f500-313a-11e9-8e4d-3f3388cd5c87.gif)

**Comment by bnb** [comment]
I was also experiencing this last night. It seemed to work for me today, though 😬

**Comment by EricJizbaMSFT** [comment]
Looks similar to https://github.com/Microsoft/vscode-cosmosdb/issues/494. We're trying to validate the account name through Azure (to see if it's globally available) and it's probably just taking a really long time. We can add a timeout like we did in the Cosmos extension
